### ISSUE TITLE
allow transient land-use files when FATES is on?

### ISSUE THREAD

**Issue by ckoven** [ESCOMP/CTSM#1002]
Hi All,
I'd like to start working towards some implementation of linking up the land use datasets with FATES.  A first requirement is that we allow that to happen in the scripting infrastructure.  Currently its forbidden by https://github.com/ESCOMP/CTSM/blob/master/bld/CLMBuildNamelist.pm#L2205.  Does anyone object to the removal of those lines of code, at least in the fates_next_api branch?

**Comment by billsacks** [comment]
Fine with me.

**Comment by ekluzek** [comment]
I think on fates_next_api would be fine for awhile during the time it takes to get it actually working. You could have a branch where this work is happening and bring in. all the changes at once. I wouldn't be happy if you wanted to bring this to CTSM master or the release branch, but it would be fine for fates_next_api.

**Comment by ckoven** [comment]
ok thanks both.  I'll submit a PR to fates_next_api with this shortly.  I can confirm that (at least as of a few years into a transient historical run) the code does actually run in this configuration, though it obviously doesn't do anything sensible with the harvest info.

**Comment by ckoven** [comment]
actually, @ekluzek if you are opposed to this change being on master until the harvest is working, then I won't issue a PR to fates_next_api so as not to block any potential merging from fates_next_api to master.  I've made this change on https://github.com/ckoven/ctsm/tree/fates_landuse and will keep working there until I have something that is PR-ready.

**Comment by ekluzek** [comment]
That sounds good to me. I could back out that change when bringing a fates_next_api update to master. Especially since it's small. But, it also makes sense to me to wait until you have something that's fully working to bring this in.

**Comment by ckoven** [comment]
actually, sorry, another related question.  the idea here is that when FATES is enabled and working with transient land use, some but not all aspects of the land-use data will be used, and when used will be used differently.  So, currently, CLM has a few separate flags: do_harvest, do_transient_pfts, do_transient_crops.  At least in its initial version, FATES with land use would only do the harvest part, not any of the other transient PFT or crop dynamics.  Do you all have any preference for whether we repurpose the existing do_harvest variable to have a different meaning when use_fates==.true., versus create some new flag like do_fates_harvest?

**Comment by ekluzek** [comment]
That's a. good question @ckoven. I. think my answer is that it depends on how it nests into the code. If there is no overlap for the FATES control variable with. the main CTSM one -- I think it. should be separate. But, if there is a lot of overlap where you you need to call the main CTSM bits of code for either FATES or non-FATES -- then. I'd use the same variable. If it's somewhere in between it could go either way.

I suspect. that you will need to instantiate the same data modules and likely be calling the same. code, so I'm thinking using do_harvest for both FATES and non-FATES makes sense. So if I'm envisioning it right -- that's the way I'd suggest.

To start with we could. make sure that the flags that can't be used can't be set with FATES on, and only allow harvesting.

**Comment by ckoven** [comment]
OK, thanks. I don't think I'll know the answer to how it will look until its written, but I'll try with reusing do_harvest and hopefully can keep it clean.

**Comment by ekluzek** [comment]
This is allowed in ctsm5.1.dev022, so closing.
