### ISSUE TITLE
Help prevent problems with WACCM-X testing by modifying our waccmx_offline test

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1012]
To help prevent problems like #1010 I think we should add another standalone test that is transient starting in 1979. Also have it set ROF_NCPL, turn megan and drydep on and set land tuning mode to clm5_0_cam6.0, so it'll use the same finidat file as in #1010.

**Comment by billsacks** [comment]
Would it make sense to change the existing waccmx_offline test to add the changes you mention rather than adding a new test?

**Comment by ekluzek** [comment]
Yes, you might be right. I think I should look at the list of prealpha and prebeta tests for WACCM-X and make sure our standalone tests cover them reasonably well.

**Comment by ekluzek** [comment]
The current waccmx test is ERS_D_Ld5_P480x3.f19_g16.I2000Clm50SpGs.cheyenne_intel.clm-waccmx_offline for just aux_clm. "waccmx" tests for cam include f09 and f19 (there is one at f05 though). There's also tests with a start date of 2005-12-31. All of these tests are with CLM50%SP, MOSART and SGLC.

**Comment by billsacks** [comment]
If you add another test - especially at f09 - we should keep it short: probably a few time steps is sufficient: These high-resolution tests really eat up our computing allocation because of how frequently they end up being run.

**Comment by ekluzek** [comment]
I plan to just change the test, but I'll do this in the answer changing tag.
