### ISSUE TITLE
turn off transient land use time series data

### ISSUE THREAD

**Issue by qhgogogo** [ESCOMP/CTSM#1023]
Dear NCAR scientists,

I am trying to use static land use rather than transient land use time series data while running a case with compset:  ISSP245Clm50BgcCrop. Could you give some advises what options I should turn off or changes I should make?

Thank you,

Han

**Comment by olyson** [comment]
This is what we set in our user_nl_clm for our no land use land cover change experiments:

do_harvest = .false.
do_transient_crops = .false.
do_transient_pfts = .false.
flanduse_timeseries = ' '

**Comment by qhgogogo** [comment]
Thank you, Oleson! This really helps.

**Comment by ekluzek** [comment]
I'm closing this.
