### ISSUE TITLE
Do some cleanup of the WRF `lilac_cap` branch and move it to the WRF repo

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1028]
Based on discussion this morning, we should:

- [x] Merge the latest version of WRF develop into the `lilac_cap` branch

- [x] Change the numbering of the ctsm surface physics option from 51 to a single-digit number (whatever the next unused number is)

- [x] Push the `lilac_cap` branch to the WRF repository. **I think we should rename this branch to something more obvious, like `ctsm_coupling`.** Can talk to Dave Gill, Jimy Dudhia and Wei Wang about the mechanics of starting the feature branch there.

**Comment by negin513** [comment]
These issue has been addressed for WRF-CTSM  PR # https://github.com/wrf-model/WRF/pull/1275
