### ISSUE TITLE
Write LILAC documentation

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1031]
I have set up a tentative outline for the LILAC documentation and have begun writing a bit of it. There's a lot more still to write.

The documentation is on the lilac_cap branch, under `doc/source/lilac`. What I have so far can be seen here: https://escomp.github.io/ctsm-docs/versions/master/html/lilac/index.html

I have put TODO notes in the documentation for sections that still need to be written. We can remove those TODO notes as we write them. (`git grep TODO` from within `doc/source/lilac`)

@dlawrenncar @slevisconsulting @negin513 please let me know if you have any comments so far on this.

I can take the lead on most of this, but I'd like help with the following:

- [Overview of LILAC](https://escomp.github.io/ctsm-docs/versions/master/html/lilac/introduction-and-overview/overview-of-lilac.html) - @dlawrenncar I may want your help describing this in an appropriate high-level way. I can probably take a first stab at it, though.

- [WRF-specific notes](https://escomp.github.io/ctsm-docs/versions/master/html/lilac/specific-atm-models/wrf.html) - @negin513 and @slevisconsulting can you please take the lead on this section?

See https://github.com/ESCOMP/CTSM/wiki/Directions-for-editing-CLM-documentation-on-github-and-sphinx for instructions on how to build the documentation. (The build process builds this lilac documentation as well as the tech note and user's guide.)

**Comment by billsacks** [comment]
Notes from Fei Chen:

> Bill, thanks for initiating it! I had a quick a look at it and want to propose the following:
> 
> From potential WRF-CTSM users, the most useful information is perhaps the 3.4.1 section Using CTSM and WRF, which we should 
> envision as a stand-alone document (of course, with relevant links to your more comprehensive CTSM/LILAC description).
> 
> I’d suggest this stand-alone WRF-CTSM document to include several sections, for instance,
> 
> 
> 0. A general background information on using LILAC to couple CSTM and WRF
> 1. New modules added to WRF to accommodate CTSM and LILAC
>    - physics/module_sf_ctsm.F: contains 2-D WRF to 1-D LILAC conversion, CTSM initialization via LILAC, and ctsm_run to interface IO between CTSM and WRF
>   - …
> 
> 2. WRF modules modified
>   - /physics/module_surface_driver.F: call ctsm-run
>   - /physics//module_physics_init.F 
>  - /share//input_wrf.F
>   - /share/module_check_a_mundo.F
> 
> 3. Building and running WRF-CTSM: based on the current google doc, and add one example of running outside of US domain later
> 
> 4. Specification of static land and soil characteristics
>    - CTSM approach (link to CTSM)
>    - incorporate users’ data set (an item to be added in future)
>   
> 5. Initializing WRF-CTSM land states (soil moisture/temperature, soil ice, SWE, etc)
> 
> These are some suggestions regarding the organization of WRF-CTSM, feel free to add/delete. Hope this helps

**Comment by billsacks** [comment]
> From potential WRF-CTSM users, the most useful information is perhaps the 3.4.1 section Using CTSM and WRF, which we should 
> envision as a stand-alone document (of course, with relevant links to your more comprehensive CTSM/LILAC description).

I wasn't sure from this comment whether Fei was suggesting moving this to a different location, or still keeping it as a section of the CTSM-LILAC documentation, but just organizing the content so that a WRF user can read this page alone, without needing to read the other documentation first? (I agree on that second point at least.)

Fei replied:

> Bill - I meant a self contained doc about WRF-CTSM when writing that email. But now come to think of it, it may be a good idea to make it also a stand alone doc (rather than deeply embedded in other CTSM stuff).  My trouble was when looking at various pages you sent, I do not see anywhere WRF-CTSM is mentioned. Even the "CTSM-LILAC documentation" is less intuitive than, say, "CTSM-WRF" documentation, because LILAC is the tool to connect CTSM and WRF. 
> 
> Another thing we may want to mention in the WRF-CTSM documentation is the output. Although some common variables are stored in wrfout*, more LSM related variables are in test_lilac.clm2.h0*. 

I'm not at all tied to where this WRF-CTSM documentation lives. If it lives alongside the other ctsm documentation, we could pull it out to a higher level, if that would be desirable. Or it could live in some completely different location. Any opinions?

**Comment by slevisconsulting** [comment]
@billsacks @negin513 
I plan to have a first draft of
`.../doc/source/lilac/specific-atm-models/wrf.rst`
today.

**Comment by slevisconsulting** [comment]
> I'm not at all tied to where this WRF-CTSM documentation lives. If it lives alongside the other ctsm documentation, we could pull it out to a higher level, if that would be desirable. Or it could live in some completely different location. Any opinions?

We're likely to stay on top of maintaining it if it resides here rather than in a separate location. If the choice is between here and elsewhere, I vote for here. 

Could it possibly reside here and be linked to a second "standalone" location (wherever Fei has in mind)?

**Comment by slevisconsulting** [comment]
Thank you @billsacks , I like this solution. I have made the change and pushed it.

**Comment by slevisconsulting** [comment]
From my google doc notes that I shared in today's meeting:

**wrf.rst updates still needed**

(I'm willing to do these once Negin completes the first one. Recall that at this point changes come in via Pull Requests.)

- Negin will add how to generate fsurdat for a new domain and Sam will test
- Replace `git clone https://github.com/billsacks/WRF.git` with `git clone https://github.com/negin513/WRF-1.git` and later with WRF feature branch
- Delete `git checkout lilac_cap`
- Replace `Section 3.2.2 (next)` with `in the next section (titled “Set CTSM runtime options”) OR make link that automatically inserts the correct section number
- Move `Set CTSM runtime options` just before `Compile WRF Preprocessing System`
- Reorder Tip and Note here (optional; just my preference)
- Replace `section 3.2` with `the section titled “Obtaining, building and running CTSM with LILAC”` unless the link automatically inserts the correct section number
- Replace `instructions in this section` w a link that inserts the section number
- Replace `In step 3` w `In step 2`
- Replace
`/glade/work/slevis/git_wrf/WRF/test/em_real/namelist.input.ctsm.2013.d01.12month`
`/glade/work/slevis/git_wrf/WRF/test/em_real/wrfinput_d01.ERAI.12month`
`/glade/work/slevis/git_wrf/WRF/test/em_real/wrfbdy_d01.ERAI.12month`
with
`cp /glade/work/slevis/git_wrf/WRF/test/em_real/namelist.input.ctsm.2013.d01.12month namelist.input`
`cp /glade/work/slevis/git_wrf/WRF/test/em_real/wrfinput_d01.ERAI.12month wrfinput_d01`
`cp /glade/work/slevis/git_wrf/WRF/test/em_real/wrfbdy_d01.ERAI.12month wrfbdy_d01`

**Comment by billsacks** [comment]
@negin513 is going to take the lead on the remaining pieces of documentation, with help from @slevisconsulting and myself as needed. I am changing the assignments of this issue to reflect that she will be the primary lead.

**Comment by billsacks** [comment]
Message from @negin513 with my responses inserted:

> How much detail do we need to provide on the LILAC API section? I will try to stay consistent with the amount of detail you provided in other sections. 

That's hard for me to answer in the abstract. I think we want enough detail to provide helpful guidance to someone who wants to plug LILAC-CTSM into a new atmosphere model.

> Should the LILAC API section ( i.e. 3.3. Calling CTSM from an atmosphere model ) be geared towards developers who want to couple other atmospheric models to CTSM? Or should it be more focused on explaining what has been done for WRF for WRF-CTSM users?

I'd say the first: developers who want to couple other atmospheric models to CTSM. Explaining what was done in WRF seems best done in the PR where we merge the lilac_dev branch to WRF master. However, it's certainly reasonable to provide examples from the WRF code if you feel that would be helpful.

> I'd like to propose adding a section called "How to adapt atmospheric models for LILAC?" under the LILAC API section.

Sounds good, if you have ideas for what would go in this section.

> I also want to suggest a title change for section  3.4. from "Notes on specific atmosphere models" to "Instructions on running CTSM with specific atmosphere models". 

Sounds good.

**Comment by billsacks** [comment]
This is largely done. Unfortunately, with no current support dedicated to LILAC, we're going to close this without doing the outstanding pieces.
