### ISSUE TITLE
Branch run fails because of "missing" clm and cism restart files

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#1035]
### Brief summary of bug

Switching from a startup to a branch run to get extra history output fails because model reports that clm and cism restart files are missing (even though they are present in the run directory).

### General bug information

**CTSM version you are using:** [output of `git describe`]

clm4_5_18_r272-2361-g159d3b03 (this is Erik's lmbirch_kattge branch)

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** --compset HIST_DATM%GSWP3v1_CLM50%BGC-CROP_SICE_SOCN_MOSART_CISM2%NOEVOLVE_SWAV --res f19_g17_gl4

### Details of bug

First of all, I'm not sure if this is actually a bug or a new feature, but it is different behavior.   At year 1989 of a historical run I typically reconfigure the case to a branch in order to add more history output streams:

./xmlchange RUN_TYPE=branch
./xmlchange RUN_REFCASE={$CASENAME}
./xmlchange RUN_REFDATE=1989-01-01
./xmlchange STOP_OPTION=nyears
./xmlchange STOP_N=16
./xmlchange CONTINUE_RUN=FALSE
./xmlchange RESUBMIT=0

And then add some history streams to user_nl_clm.  Then submit the case.  This used to work fine. 
However, now when I do this, the model fails during case.submit with this error:

Loading input file list: 'Buildconf/clm.input_data_list'
  Model clm missing file nrevsn = 'clm50_ctsm10d089_2deg_GSWP3V1_lmbirch_wkattge_jmaxb1-0.17_slatopA_leafcnA_stemleafA_sdt_hist.clm2.r.1989-01-01-00000.nc'
Loading input file list: 'Buildconf/cpl.input_data_list'
Loading input file list: 'Buildconf/datm.input_data_list'
Loading input file list: 'Buildconf/cism.input_data_list'
  Model cism missing file cisminputfile = 'clm50_ctsm10d089_2deg_GSWP3V1_lmbirch_wkattge_jmaxb1-0.17_slatopA_leafcnA_stemleafA_sdt_hist.cism.r.1989-01-01-00000.nc'

In other words, the model doesn't seem to look in the run directory for the restart files (which are there).  I have to provide the full path for nrevsn and cisminputfile in user_nl_clm and user_nl_cism, respectively.

nrevsn = '/glade/scratch/oleson/clm50_ctsm10d089_2deg_GSWP3V1_lmbirch_wkattge_jmaxb1-0.17_slatopB_leafcnA_hist/run/clm50_ctsm10d089_2deg_GSWP3V1_lmbirch_wkattge_jmaxb1-0.17_slatopB_leafcnA_hist.clm2.r.1989-01-01-00000.nc'

cisminputfile = '/glade/u/home/oleson/clm50_ctsm10d089_2deg_GSWP3V1_lmbirch_wkattge_jmaxb1-0.17_slatopB_leafcnA_hist.cism.r.1989-01-01-00000.nc'

### Important details of your setup / configuration so we can reproduce the bug

My case directory:

/glade/work/oleson/ctsm_lmbirch_wkattge/cime/scripts/clm50_ctsm10d089_2deg_GSWP3V1_lmbirch_wkattge_jmaxb1-0.17_slatopA_leafcnA_stemleafA_sdt_hist

### Important output or errors that show the problem

**Comment by ekluzek** [comment]
@olyson in our discussion this morning we'd like to have you try replicating this same problem with the latest CTSM master (so ctsm1.0.dev100). Both @billsacks and I looked at the code and didn't see anything about why this would be different for a test than for a regular case. So we'd like you to replicate it again with the latest code and we hope you won't see it. If you do we'll need to look at this more...

**Comment by olyson** [comment]
I'll give it a try.  FYI,  I changed the "download" to False in this line in check_input_data.py:

success = self.check_input_data(protocol=protocol, address=address, download=True,
                                        input_data_root=input_data_root, data_list_dir=data_list_dir, 
                                        chksum=chksum and chksum_found)

During case.submit, the files were still reported as missing but it didn't try to download them, and it submitted the case successfully.  I'm sure this isn't a real solution, but might be ok as a workaround for my case.

**Comment by olyson** [comment]
Actually it was this line where I changed download to False:

def check_all_input_data(self, protocol=None, address=None, input_data_root=None, data_list_dir="Buildconf", download=True, chksum=False):

**Comment by ekluzek** [comment]
Hmmm, interesting. It looks like that default has always been True, so it's nothing new.

But, let us know if you see the same problem in the latest CTSM.

**Comment by olyson** [comment]
My new case using latest CTSM worked fine.  It didn't even complain about missing files.

**Comment by ekluzek** [comment]
OK, I'll close this as a WONTFIX. That seems to be the closest description. It seems to be a problem for some versions, but not in the latest. So it wouldn't be anything that we'd work on.
