### ISSUE TITLE
Non-standard namelist parameter: cmb_cmplt_fact

### ISSUE THREAD

**Issue by djk2120** [ESCOMP/CTSM#1053]
cmb_cmplt_fact is a parameter under namelist control pertaining to the fire model (combustion completion factor [unitless])

As far as I can tell it is the only real-valued, namelist-controlled parameter that is not a single value. Instead it has two elements, which are by default: 0.5 and 0.25. The first values corresponds to litter and the second to coarse woody debris. 

If possible we might split this into two parameters to avoid having a special case when it comes to editing namelist parameters.

**Comment by ekluzek** [comment]
It wouldn't be too hard to split it into two with adding for example a "_cwd" and "_litter" suffix to it. I wonder if we should bring it directly to the params file though? If so would you want it separated out there as well?

There are a few other array valued real namelist items, but I think you likely wouldn't be messing with them: soil_layerstruct_userdefined, initial_Cstocks, initial_Cstocks_depth, albice, lake_melt_icealb. Do you agree that you wouldn't be changing any of those?

**Comment by djk2120** [comment]
Either way I think it would be ideal to separate them. Agreed on the suffix idea. I would say perhaps namelist for now, because several other fire parameters are controlled directly from the namelist. But I would certainly defer to you on that...

**Comment by djk2120** [comment]
And yes, agreed, we have no plans to alter any of those other namelist items.
