### ISSUE TITLE
Expand potential vcmax:jmax ratio

### ISSUE THREAD

**Issue by djk2120** [ESCOMP/CTSM#1055]
For the perturbed parameter experiment we are interested in exploring lower jmax:vcmax ratios than are currently allowed in the model. This will require commenting out a cap on wc2wj that exists in LunaMod:

https://github.com/ESCOMP/CTSM/blob/3029203daa9af4dc1ac03242462f3315746d20ca/src/biogeophys/LunaMod.F90#L1050

**Comment by ekluzek** [comment]
OK, this goes back to our first version of Luna that came into CLM. It also looks like to me that this can allow answers to change even if the value of wc2wjb0 is unchanged (if I'm reading the code correctly). So we should evaluate if that's so or not, and under what conditions it does change answers.

**Comment by djk2120** [comment]
Agreed. I think answer changes are certainly possible, but I would not
expect them to aggregate to significant differences globally using the
default value of wc2wjb0.

**Comment by wwieder** [comment]
@djk2120 you can test  out the impact on this change by running  a control and modified 4x5 case.  Since changes would just  be to GPP,  you can likely  get away without completely spinning the model up.

An example case with a recent code base is here
/glade/work/wwieder/ctsm/ctsm1.0.dev094/cime/scripts/clm5_4x5_woodCN_cont_spin

Alternatively try it out on the sparse grid and see if answers are different?

**Comment by ekluzek** [comment]
I've tried two tests from the test suite so far and both are showing bit-for-bit: SMS_D_Ld3.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default, SMS_Lm13.f19_g17.I2000Clm50BgcCrop.cheyenne_intel.clm-cropMonthOutput

So I'll try the longest tests from the test suite and make sure they don't change answers. If so I'll treat this as a bit-for-bit change.

**Comment by ekluzek** [comment]
OK, a longer list of tests is showing identical answers. So I'm going to treat this as a bit-for-bit change.

ERP_Ly3_P72x2.f10_f10_musgs.IHistClm50BgcCrop.cheyenne_intel.clm-cropMonthOutput			
ERP_P72x2_Lm25.f10_f10_musgs.I2000Clm50BgcCrop.cheyenne_intel.clm-monthly			
ERP_P72x2_Lm36.f10_f10_musgs.I2000Clm50BgcCrop.cheyenne_intel.clm-clm50cropIrrigMonth_interp			
ERP_P72x2_Ly3.f10_f10_musgs.I2000Clm50BgcCrop.cheyenne_intel.clm-irrig_o3_reduceOutput			
ERS_Lm20_Mmpi-serial.1x1_smallvilleIA.I2000Clm50BgcCropQianGs.cheyenne_gnu.clm-monthly_noinitial			
ERS_Lm40_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianGs.cheyenne_gnu.clm-monthly			
ERS_Lm54_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianGs.cheyenne_intel.clm-cropMonthOutput			
ERS_Ly20_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianGs.cheyenne_intel.clm-cropMonthOutput			
ERS_Ly3.f10_f10_musgs.I1850Clm50BgcCropCmip6.cheyenne_intel.clm-basic			
ERS_Ly3_Mmpi-serial.1x1_smallvilleIA.IHistClm50BgcCropQianGs.cheyenne_gnu.clm-cropMonthOutput			
ERS_Ly3_P72x2.f10_f10_musgs.IHistClm50BgcCropG.cheyenne_intel.clm-cropMonthOutput			
ERS_Ly5_Mmpi-serial.1x1_smallvilleIA.I2000Clm50BgcCropQianGs.cheyenne_gnu.clm-ciso_monthly			
ERS_Ly5_P144x1.f10_f10_musgs.IHistClm50BgcCrop.cheyenne_intel.clm-cropMonthOutput			
LCISO_Lm13.f10_f10_musgs.IHistClm50BgcCrop.cheyenne_intel.clm-ciso_monthly			
SMS_Lm13.f19_g17.I2000Clm50BgcCrop.cheyenne_intel.clm-cropMonthOutput			
SMS_Ly3_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianGs.cheyenne_intel.clm-clm50dynroots	

I'm also testing ERS_Ly6_Mmpi-serial.1x1_smallvilleIA.IHistClm50BgcCropQianGs.cheyenne_intel.clm-cropMonthOutput, but it's having some problems.
