### ISSUE TITLE
Evaluate WRF-CTSM when using reinitialization

### ISSUE THREAD

**Issue by negin513** [ESCOMP/CTSM#1057]
So far, we evaluated the performance of WRF-CTSM simulations for a 6-month free-running simulation. And we plan to do more evaluation for a 12-month simulation. 

However, it is not advisable to run WRF for more than two weeks without revitalization.
Without initialization, WRF will diverge significantly from global meteorological fields which provide boundary conditions. 

There are two options to avoid this problem:
1) Reinitalization.
2) WRF spectral nudging technique.

Most papers running WRF for more than a few days use one of the above techniques. 

Instead of our 6 or 12-month simulation, it might worth thinking about reinitializing every 72 hours or 96 hours, etc.

**Comment by billsacks** [comment]
@negin513 is the point of this issue that we should redo the evaluation of WRF-CTSM (comparing to Noah / Noah-MP) when using reinitialization? If so, can you change the title accordingly? (e.g., "Evaluate WRF-CTSM when using reinitialization")

**Comment by billsacks** [comment]
Given lack of resources for WRF-CTSM, I am closing this as a wontfix.
