### ISSUE TITLE
Some code cleanup of luna bug fixes

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1060]
These are from some comments of the luna bug fix branch (PR #961). 

My main thought was to avoid having "yr" / "year" in the name. I suggested vcmx_last_active_day, but I'm not sure if that's the best. @ekluzek suggested something including "last_valid", which also seems reasonable. Good naming is so hard... (and yet so important).

 @billsacks
billsacks on Apr 16 Member
Another note about these names: they need _patch suffixes. Also, it's probably best if they maintain the 25_z that appears in vcmx25_z and jmx25_z variable names, to show the correspondence between these variables.

Photosynthesis:

As in LunaMod, this comment is misleading since we're not taking the running average. We should be consistent with LunaMod.

**_Initial values for the previous year settings should also be fixed (but as potentially answer changing that will be separate from this)._**

long names here should match what we're using in the description above, something about the previous year?

Minor correction, but jmx25_z_patch and jmx_prevyr long_name should be maximum rate of electron transport at 25 celsius for canopy layers, with units umol electron/m**2/s

**Comment by billsacks** [comment]
Discussion on initial values: @wwieder suggests initializing `vcmx_prevyr` to 30 and `jmx_prevyr` to 60 (matching the initial values for `vcmx25_z_patch` and `jmx25_z_patch`).

**Comment by negin513** [comment]
> Minor correction, but jmx25_z_patch and jmx_prevyr long_name should be maximum rate of electron transport at 25 celsius for canopy layers, with units umol electron/m**2/s

Just to confirm this requires changing `long_name` for `jmx25_z_patch` in both  restart files and history files to 
'maximum rate of electron transport at 25 Celcius for canopy laters`

Should the long_name`jmx25_z_last_valid_patch` in restart outputs be named "avg" rate of electron transport at 25 Celcius for canopy layers instead of "maximum"? consistent `vcmx25_z_last_valid_patch` which is named "avg" carboxylation rate at 25 celsius for canopy layers

**Comment by negin513** [comment]
> Discussion on initial values: @wwieder suggests initializing `vcmx_prevyr` to 30 and `jmx_prevyr` to 60 (matching the initial values for `vcmx25_z_patch` and `jmx25_z_patch`).

Acknowledged and already done for #1102 .
