### ISSUE TITLE
Decrease log message output from LILAC runs

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1070]
I'm noticing that there is a lot of output to the various PET*.ESMF_LogFile files in a LILAC run. We should reduce this output, since it may have an impact on performance, particularly at higher processor counts.

**Comment by negin513** [comment]
Yes! There are many unnecessary information and print statements in the outputs. I put all these print messages there when I was developing and debugging the code, but at this point, they should definitely be removed.

**Comment by mvertens** [comment]
@billsacks @negin513  - the creation of the PET log files is turned on by a flag in the ESMF_Initialize call
What you have now is

```Fortran
call ESMF_Initialize(mpiCommunicator=mpicom, defaultCalKind=ESMF_CALKIND_GREGORIAN, &
         logappendflag=.false., rc=rc)
```
 
What you want is a new variable - logkindflag (for CMEPS we obtain this from a namelist variable called create_esmf_pet_files

```Fortran
  if (create_esmf_pet_files) then
     logkindflag = ESMF_LOGKIND_MULTI
  else
     logkindflag = ESMF_LOGKIND_MULTI_ON_ERROR
  end if
```
And then you can use it in the ESMF_Initialize as follows (we also have added the ioUnit flags)

```Fortran
call ESMF_Initialize(mpiCommunicator=COMP_COMM, logkindflag=logkindflag, logappendflag=.false., &
       defaultCalkind=ESMF_CALKIND_GREGORIAN, ioUnitLBound=5001, ioUnitUBound=5101, rc=rc)
```
You can see the full documentation here:
(http://www.earthsystemmodeling.org/esmf_releases/last_built/ESMF_refdoc/node4.html#SECTION04024100000000000000)

**Comment by billsacks** [comment]
I have fixed this on the `lilac_cap` branch, thanks to @mvertens 's suggestions above. I have NOT added `ioUnitLBound` and `ioUnitUBound` arguments, because I'm not sure what they should be here. It looks like the values above are chosen to make it less likely to have collisions in unit numbers, but I'm not sure. For now, I'll leave these out, but we may want to return to that.
