### ISSUE TITLE
Test failure for transient 48x96 in build-namelist_test.pl

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1074]
Running build-namelist_test.pl from master (ctsm1.0.dev103), I'm getting a failure in one test:

```
392/842 < FAIL> <Test Id: 392> <Desc: -res 48x96 -use_case 20thC_transient -envxml_dir .  -phys clm5_0: lnd_in file exists>
Successfully ran all testing for build-namelist
```

**Comment by ekluzek** [comment]
This is because of a landuse timeseries file that is missing it should point to: lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_48x96_hist_16pfts_Irrig_CMIP6_simyr1850-2015_c190214.nc

**Comment by ekluzek** [comment]
This is also noted in #1036
