### ISSUE TITLE
NUOPC cap: use named constants rather than literal strings in state_getimport and state_setexport

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1083]
I was looking quickly at the NUOPC cap. It looks like `state_getimport` and `state_setexport` return silently if the given field doesn't exist. I feel that this behavior, combined with the use of strings (rather than defined constants that can be checked at compile time) is an opening for bugs due to typos.

I feel it would be more robust to make these routines abort if the given field isn't found. I realize that there may then need to be some logic around the calls to `state_getimport` and `state_getexport` so that they aren't called if a given field is known not to exist.

For example, this line would probably then result in an error, because methane currently isn't added to the field list:

```Fortran
call state_getimport(importState, 'Sa_methane', bounds, output=atm2lnd_inst%forc_pch4_grc, rc=rc )
```

Alternatively, the use of strings throughout the cap could be replaced with constants. For example, the use of `Faxa_snowc` in these lines:

```Fortran
    call fldlist_add(fldsToLnd_num, fldsToLnd, 'Faxa_snowc'   )
```
```Fortran
    call state_getimport(importState, 'Faxa_snowc', bounds, output=forc_snowc, rc=rc )
```

would be replaced by reference to a named constant (whose value could still be `Faxa_snowc`). This would ensure that you don't try to reference a non-existent name in the `state_getimport` call.

@mvertens I'm tentatively assigning you. Feel free to comment if you feel my suggestions aren't feasible.

**Comment by mvertens** [comment]
@billsacks - I think both of these are good ideas. We have historically always used string and not named constants  -but I think your suggestion makes a lot of sense. Thanks for pointing this out.

**Comment by mvertens** [comment]
@billsacks - in terms of your first point - there is just a check to see if this field is in the import state and is based on the handshaking that occurred with the mediator at initialization. If this field is not connected, then it will not be in the import state - and nothing should happen. So I do not agree that it should die. Methane is an optional field determined based on the fldlist_add call. The fldlist_add call should ensure that this field exists - and the import state just queries if it exists. I'm happy to have a more detailed discussion of this to clarify the implementation.

**Comment by billsacks** [comment]
@mvertens I may be misunderstanding your argument, but let me try to clarify my thinking.

When you make a call like this:

```Fortran
call state_getimport(importState, 'Sa_methane', bounds, output=atm2lnd_inst%forc_pch4_grc, rc=rc )
```

there are two possible reasons why this could return without doing anything – i.e., without filling `forc_pch4_grc` with any data:

(1) The expected reason: methane is not connected

(2) The unexpected reason: There is a typo in the string (for example, the field name is actually 'Sa_Methane', not 'Sa_methane').

My understanding from a quick read of the code is that both reasons would result in the same behavior, whereas I would want (2) to result in a runtime error. It seems like this can be achieved by adding an abort in `state_getimport` along with some explicit logic around optional fields (so that it avoids calling `state_getimport` if it isn't connected), or can be at least partially ameliorated by using named constants instead of literal strings.

If you still think I'm misunderstanding this, we can talk further.

**Comment by billsacks** [comment]
I just talked about this with @mvertens . She pointed out the challenge in trying to add error checking to `state_getimport`, but agrees that we should add some named constants (which are used by both `state_getimport` and `fldlist_add`). This is good enough, as far as I'm concerned, because she pointed out that there will be an error raised if you try to give a non-existent field to the `fldlist_add` call.

I am renaming this issue accordingly.

**Comment by billsacks** [comment]
Yes, sounds good - thanks @ekluzek
