### ISSUE TITLE
Memory corruption when reading a netcdf variable into a variable of a different type, at least with PIO1

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1091]
### Brief summary of bug

I have observed what appears to be memory corruption when reading a netcdf variable of one type into a variable of a different type, at least with PIO1. I have NOT seen any evidence that this impacts current code on master, but this is a potential problem for future code.

### General bug information

**CTSM version you are using:** Observed with `ctsm1.0.dev101-24-g4b7c985e3`

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** No existing configurations, as far as I know

### Details of bug

When running a case from the `dynlakes_master` branch from the Ivanderkelen fork of CTSM (Ivanderkelen/CTSM@4b7c985e3), an odd error appeared in `decompInitMod`. I eventually tracked this down to an `ncd_io` call that was reading the new `HASLAKE` variable (which was double-precision on the landuse_timeseries file) into an integer variable. Changing the code to read it into a same-type (i.e., double precision) variable made the problem go away (Ivanderkelen/CTSM@5e2e25a5d).

I was also able to resolve the problem by reverting the `ncdio_pio` changes that @jedwards4b implemented in #939 , which changed the way type conversion is done. Specifically: If I start with Ivanderkelen/CTSM@4b7c985e3 but revert b6a1d505aa88304a8ef010d85d76e3a7609642af, 814e8809a2d3464c7741a07279861abc02905f10 and 1d9bd3e7bdc59df96f2f4eef228658afb0d582dd, the previously-failing case works.

I was also able to resolve the problem by using PIO2 instead of PIO1 (via a new case with  `./xmlchange PIO_VERSION=2`). However, I'm not confident if that truly resolves the issue, or if it possibly just changes the symptom of the memory corruption to something less obvious, since these memory corruption bugs can manifest in different ways depending on all sorts of details.

### Important details of your setup / configuration so we can reproduce the bug

From Ivanderkelen/CTSM@4b7c985e3:

```
./create_newcase --case $scratch/test_dynlake_0720a --res f19_g17 --compset IHistClm50Sp
```

Then:

```
./xmlchange RUN_STARTDATE=1900-01-01
./xmlchange DEBUG=TRUE
./xmlchange JOB_WALLCLOCK_TIME=0:20:00
./xmlchange JOB_QUEUE=premium
./case.setup

echo "check_dynpft_consistency = .false." >> user_nl_clm
echo "do_transient_crops=.true." >> user_nl_clm
echo "do_transient_pfts =.true." >> user_nl_clm
echo "do_transient_lakes = .false." >> user_nl_clm
echo "flanduse_timeseries='/glade/u/home/ivanderk/clm5.0/tools/mksurfdata_map/landuse.timeseries_1.9x2.5_hist_16pfts_Irrig_CMIP6_simyr1850-2015_c190715.nc'" >> user_nl_clm
echo "fsurdat = '/glade/u/home/ivanderk/clm5.0/tools/mksurfdata_map/surfdata_1.9x2.5_hist_16pfts_Irrig_CMIP6_simyr1850_c190715.nc'" >> user_nl_clm
```

### Important output or errors that show the problem

The above test leads to:

```
37:forrtl: severe (408): fort: (3): Subscript #1 of the array ALLVECL has value 0 which is less than the lower bound of 1
37:
37:Image              PC                Routine            Line        Source
37:cesm.exe           0000000005433726  Unknown               Unknown  Unknown
37:cesm.exe           0000000000A4CCF0  decompinitmod_mp_         490  decompInitMod.F90
37:cesm.exe           0000000000900F46  clm_initializemod         213  clm_initializeMod.F90
37:cesm.exe           000000000088291F  lnd_comp_mct_mp_l         200  lnd_comp_mct.F90
37:cesm.exe           0000000000458D33  component_mod_mp_         257  component_mod.F90
37:cesm.exe           000000000041A752  cime_comp_mod_mp_        1350  cime_comp_mod.F90
37:cesm.exe           000000000044F92D  MAIN__                    122  cime_driver.F90
37:cesm.exe           0000000000407EE2  Unknown               Unknown  Unknown
37:libc.so.6          00002AACA1E3F6E5  __libc_start_main     Unknown  Unknown
37:cesm.exe           0000000000407DE9  Unknown               Unknown  Unknown
```

**Comment by billsacks** [comment]
@jedwards4b - Summarizing the above: there appears to be memory corruption when using PIO1 when reading a netcdf variable of one type into a variable of a different type, since the changes you made in CTSM's ncdio_pio in #939 . Although I didn't see the same error when using PIO2, I can't tell if this problem may exist in some different form with PIO2. So I'm hoping for some help from you here:

1. With your changes in #939 , was it supposed to work to do this kind of type conversion (e.g., reading a double-precision variable on the file into an integer variable in the code)?

2. Was this supposed to work with PIO1 as well as PIO2?

3. If this was supposed to work, can you help with what changes would be needed to actually make this work? Alternatively, if this is not supposed to work (at least with PIO1), can you help with what error checking can be added so that the code dies with a reasonable error message if you are trying to do type conversion that will lead to problems?

**Comment by billsacks** [comment]
@jedwards4b I should add: Since we seem close to having PIO2 working (thank you!), I don't feel that we need to spend a lot of time getting this worked out with PIO1. However, these memory corruption bugs make me nervous, so I'm hesitant to drop this unless you're confident that this works fine with PIO2 despite not working with PIO1; and even if that's the case, if it isn't too hard to get it working with PIO1 and/or add appropriate error checking, that still feels ideal, since this bug resulted in an issue that was time-consuming to track down.

**Comment by billsacks** [comment]
I'm marking this as high priority, because it's important that we either resolve it or determine pretty definitively that it won't be an issue with pio2.

**Comment by jedwards4b** [comment]
Running as /glade/scratch/jedwards/SMS_D.f19_g17.IHistClm50Sp.cheyenne_intel.20201006_121228_3b7m7l  
I am not reproducing the problem, @billsacks can you have a look and see if you see why?

**Comment by jedwards4b** [comment]
@billsacks Hang on, I may have had the wrong source tree, retesting now.

**Comment by billsacks** [comment]
Thanks @jedwards4b . Do let me know if you have trouble reproducing this... I'm not positive the necessary input files are still around, but I can help you recreate this if you have trouble.

**Comment by jedwards4b** [comment]
In file surfrdMod.F90 subroutine surfrd_lakemask the variable used to read haslake_id is already a temporary variable, so
making this temporary variable fit the type of the actual variable on the file would be an easy fix.

**Comment by billsacks** [comment]
@jedwards4b yes I fixed it in this way already. This was just meant to be an illustration of the general issue. This has come up for other scientists using CTSM, too.

**Comment by jedwards4b** [comment]
@billsacks In ncdio_pio.F90.in the type is read from the file to get the iodesc, but that type is not used in the call to pio_read_darray
this the 8 byte values from the file are being read into 4 byte variables.  I have fixed this in ncdio_pio.F90.in but I am not clear about what the PR target should be?

**Comment by billsacks** [comment]
Thanks! It can just go into master.
