### ISSUE TITLE
CTSM should handle lakes in the WRF-CTSM system

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1092]
As @dlawrenncar pointed out: Currently, in the WRF-CTSM system, lakes are treated as oceans. We'd like CTSM to handle lakes (in a 2-way interactive way).

 I think there are two pieces needed for this to happen:

1. The land mask on the CTSM domain file needs to be set appropriately so that lakes are considered land, not ocean.

2. WRF needs to be told that these lake grid cells should be governed by CTSM, not the ocean.

One way to accomplish both could be to adjust WRF's underlying land/ocean mask to call these lake points land rather than ocean; if CTSM's domain file is generated consistently with that, then point (1) should be addressed automatically.

Alternatively, Fei Chen thinks that WRF has a mask of lake points. So we could use this mask to modify CTSM's domain file. Then we could turn on WRF's flag to use a lake model and add some logic so that, when running with CTSM, it uses CTSM for lake grid cells rather than using its own lake model.

**Comment by billsacks** [comment]
My notes from today's meeting with Jimy Dudhia:

Jimy Dudhia's feeling is that it will work well to use the option where we include the lake mask in WRF. Then, in the code, we should be able to just include the lake flag along with the xland mask.

However, a problem is that WRF currently considers large lakes (like the Great Lakes) to be ocean. (This is set using a script that Michael Duda wrote. It currently has some size threshold; we could probably just get rid of that size threshold.)

So a new proposal is:
- We provide a separate landmask dataset to GeoGrid that calls all lakes "land", and then put a second mask field on WRF's datasets that uses this new mask (alongside the existing mask, so both are options in a given run)
	- Update: Negin points out that we may be able to use the existing lake depth field on GeoGrid: any point with a lake depth is also considered lake
- In the WRF code, where xland is created, we use different logic if running with CTSM: we include points considered lake and/or use this alternate mask.

@negin513 does this agree with your understanding? Do you want to add any details?

**Comment by negin513** [comment]
For running CTSM for lake points, there are intrinsically two different issues that should be addressed:

**1. From WRF standpoint, CTSM should be called for lake points besides land points. This can be addressed in `module_surface_driver.F` using `lakemask` variable or `lakedepth` variable.** 

This can be handled in multiple different ways, for example:

``` FORTRAN
           DO j=j_start(ij),j_end(ij)
           DO i=i_start(ij),i_end(ij)                                                          
              if(lakemask(i,j).eq.1.) then
                WRITE( message,* ) 'lakemask was 1 so xland ==1'
                CALL wrf_message ( message )
                xland (i,j)  = 1  
              end if
          ENDDO 
          ENDDO
```
which is implemented here:

https://github.com/negin513/WRF-1/blob/e91d059c2b3f9495b25b11d0bb6c5c39c587c62d/phys/module_surface_driver.F#L3898-L3913

**Comment by negin513** [comment]
**2. We should update the pre-processing steps for CTSM, so that when creating surface and domain files for CTSM, we include lake points.** 

Currently, for pre-processing for WRF-CTSM simulations, we use landmask definition from WRF `geo_em` files. There are no lakemask definition in `geo_em` files and landmask in these files exclude inland lakes. Multiple ways can be used to address this issue for example using lakedepth fields. 

 My point in the above comment also talks about this:
> * Update: Negin points out that we may be able to use the existing lake depth field on GeoGrid: possibly any point with a lake depth is also considered lake.

Another possible method is using ``lu_index`` field. Following this shows correct `fatmlndfrc` :

![Screen Shot 2020-11-17 at 1 03 21 PM](https://user-images.githubusercontent.com/17344536/99441589-5094b480-28d5-11eb-84c5-112f7f4dd2d6.png)

**Comment by negin513** [comment]
Overall, we can currently use the above method for running CTSM over lake points but for developing the streamlined toolchain this should be specially considered possibly using some lake_options to create correct files whenever the user wants to run CTSM over lake points.

**Comment by billsacks** [comment]
Skimming back through this: I thought we had resolved this... I'll keep it open pending discussion & agreement that this is done. Or @negin513 , if you see this, can you let us know if this is done (enough)?
