### ISSUE TITLE
Failing ISSP585Clm50BgcCrop test for ARCTICGRIS

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1096]
### Brief summary of bug

The test SMS.ne0ARCTICGRISne30x8_ne0ARCTICGRISne30x8_mt12.ISSP585Clm50BgcCrop.cheyenne_intel.clm-clm50cam6LndTuningMode
failed in ctsm1.0.dev105. It's a new test added in, and for some reason I missed the fact that it wasn't passing.

### General bug information

**CTSM version you are using:** ctsm1.0.dev105

**Does this bug cause significantly incorrect results in the model's science?** No
**Configurations affected:** Just this test

### Details of bug

I think the walltime is just too short.

**Comment by billsacks** [comment]
@ekluzek I feel like this test and `SMS.ne30pg2_ne30pg2_mg17.I2000Clm50BgcCrop.cheyenne_intel.clm-clm50cam6LndTuningMode` could be changed to be really short – like 5 time steps. It seems like the main point of these tests is to make sure that the model gets off the ground with these grids, so 5 days seems like overkill for these high-resolution cases.
