### ISSUE TITLE
QBOT is zero for 2014 for GSWP3v1 data

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1099]
QBOT is zero for all of 2014 for the GSWP3v1 data. In order to fix this we need to bring in a cime update that points to the new data. The cime issue that documents this problem is here: https://github.com/ESMCI/cime/issues/3653

@negin513 @billsacks

**Comment by ekluzek** [comment]
We think the first stop gap measure we should put in place is to change the end year to 2013 rather than 2014. And try to add some notes about this problem.

**Comment by billsacks** [comment]
The stop-gap measure was done in https://github.com/ESMCI/cime/pull/3679 . From discussion with @dlawrenncar we might stop using the GSWP data, so let's hold off on doing anything major until that's decided.

**Comment by ekluzek** [comment]
We did the stop-gap measure, and that is all we plan to do at this point. So closing.
