### ISSUE TITLE
problem with FATES exact restarts

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#110]
**Mariana Vertenstein < mvertens > - 2014-11-02 14:26:06 -0700**
**Bugzilla Id:** [2082](http://bugz.cgd.ucar.edu/show_bug.cgi?id=2082)
**Bugzilla CC:**  andre,  erik,  muszala,  rfisher,  sacks, 

I have found the that comparing the first ED history files upon restarts - they are not bit-for-bit - even though the model remains bit-for-bit and the restart test passes. In particular - for clm4_5_1_r091. As an example - if I look at the case 

ERS_D_Mmpi-serial.1x1_brazil.ICLM45CNED.yellowstone_gnu.clm-edTest

and write 1d history files daily  - I will see that upon restart (which starts from the beginning of day 7)

clm2.h0.0001-01-08-00000.nc is different between the initial and restart runs in the following fields:

 RMS GPP                              2.2001E-04            NORMALIZED  3.1505E-02
 RMS LITTER_OUT                       4.2088E+00            NORMALIZED  2.8284E+00
 RMS NPP                              1.1212E-04            NORMALIZED  3.2232E-02

However clm2.h0.0001-01-12-00000.nc are identical between the initial and restart runs.

The same thing holds for clm4_5_1_r091 with the koven refactoring  changes I have brought in. However, in this case there are now only 2 fields that are different.

 RMS GPP                              2.2001E-04            NORMALIZED  3.1505E-02
 RMS NPP                              1.1212E-04            NORMALIZED  3.2232E-02

The LITTER_OUT problem is not longer there - but the other two are still persistent.

This should be fixed - but it also points to the need to compare history files upon restart as well.

**Comment by ekluzek** [comment]
This is also referenced in FATES under: https://github.com/NGEET/fates/issues/315

This does continue to be a problem as all of the Fates Exact Restart tests continue to fail in the latest version.

**Comment by rgknox** [comment]
@ekluzek 
The problem as it stands, is that even though restart tests are passing, it is only the final history file in the comparison that is passing. The history files at other times are not similar? And this is something that is not in an isolated test, but for at least more than 1 test?

**Comment by samsrabin** [comment]
This can probably be closed, no? Note that the corresponding FATES issue, NGEET/fates#315, is closed.

**Comment by ekluzek** [comment]
Yeah, I think this can be closed. But, I want to confirm with @rgknox and @glemieux, which we can do tomorrow at the CTSM SE meeting.

**Comment by glemieux** [comment]
Yes, I believe we can go ahead and close this since the fates issue is closed.  The closest related test in that issue is passing.
