### ISSUE TITLE
ARCTIC test failing in ctsm1.0.dev107

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1113]
### Brief summary of bug

This test fails:

ERS_Ln9.ne0ARCTICne30x4_ne0ARCTICne30x4_mt12.IHistClm50Sp.cheyenne_intel.clm-clm50cam6LndTuningMode_1979Start

### General bug information

**CTSM version you are using:** ctsm1.0.dev107

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** ERS sub day test with CISM

### Details of bug

CISM can't run a sub-day restart test.

**Comment by billsacks** [comment]
I've been feeling for other reasons (mainly to speed up testing) that we should switch more of our testing like this to using stub glc.
