### ISSUE TITLE
overwrite `fun_cost_fix`

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1115]
@rosiealice curious is you recall why `fun_cost_fix` is calculated once and then overwritten? The second equation,  linked below, is what's provided in the tech note.  Filing an issue here so I don't forget to ask when you're back in town.
 https://github.com/ESCOMP/CTSM/blob/32964a832c2a11e70af48ca60d8c769d46a9e895/src/biogeochem/CNFUNMod.F90#L1604

**Comment by rosiealice** [comment]
Looks like I wrote the second equation as a replacement for the first (according to all of the logic in the comments) and then didn't delete the original term...
