### ISSUE TITLE
elai and esai for non-SP runs should use frac_sno

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1116]
### Brief summary of bug

I noticed that the formulation for elai and esai includes frac_sno for satellite phenology runs, but not for CN/BGC runs. @dlawrenncar thinks this is a bug, and that CN/BGC should include frac_sno (see https://github.com/ESCOMP/CTSM/pull/1112#issuecomment-677799822).

### General bug information

**CTSM version you are using:** Latest master

**Does this bug cause significantly incorrect results in the model's science?** Yes

**Configurations affected:** All non-SP cases

### Details of bug

For Satellite Phenology, I see:

https://github.com/ESCOMP/CTSM/blob/32964a832c2a11e70af48ca60d8c769d46a9e895/src/biogeochem/SatellitePhenologyMod.F90#L419-L420

whereas for BGC, there is no accounting for frac_sno in the similar lines:

https://github.com/ESCOMP/CTSM/blob/32964a832c2a11e70af48ca60d8c769d46a9e895/src/biogeochem/CNVegStructUpdateMod.F90#L295-L296

**Comment by billsacks** [comment]
@danicalombardozzi @swensosc would one of you want to confirm @dlawrenncar 's feelings that this is a bug, and that CNVegStructUpdate should use the same formulation as in SatellitePhenologyMod?

@danicalombardozzi I'm thinking we could fold this bug fix into #1112 .

**Comment by swensosc** [comment]
I agree that it should be the weighted average of the snow-covered and
snow-free areas, like in satellite phenology.

**Comment by danicalombardozzi** [comment]
Yes, this looks like a bug, and I can fold it into #1112
