### ISSUE TITLE
CLMBuildNameList error for fates_main_api regression testmod

### ISSUE THREAD

**Issue by glemieux** [ESCOMP/CTSM#1125]
### Brief summary of bug

The recently added `fates_nat_and_anthro_ignition` testmod to the `fates` regression test suite is failing during the SHAREDLIB_BUILD phase.  The issue occurs in CLMBuildNameList.pm and appears to be due to a problem with `use_init_interp`.

### General bug information

**CTSM version you are using:** ctsm1.0.dev093-109-ge4679200

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No] No

**Configurations affected:** 

### Details of bug

This bug has presented itself in the fates_main_api since the rebasing of #991 and should replicate with any version since then. 

Test output location:
```
/glade/u/home/glemieux/scratch/ctsm-tests/tests_fates-timing-merge/ERS_D_Lm12.1x1_brazil.I2000Clm50FatesCruGs.cheyenne_intel.clm-Fates_nat_and_anthro_ignitions.C.fates-timing-merge_int
```

### Important output or errors that show the problem

From the TestStatus.log:
```
err=ERROR : CLM build-namelist::CLMBuildNamelist::setup_logic_initial_conditions() : clm_start_type is startup so an initial conditions (finidat) file is required, but can't find one without use_init_interp being set to true'
  File "/glade/u/home/glemieux/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 777, in _run_catch_exceptions
    return run(test)
  File "/glade/u/home/glemieux/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 704, in _setup_phase
    expect(cmdstat in [0, TESTS_FAILED_ERR_CODE], "Fatal error in case.cmpgen_namelists: {}".format(output))
  File "/glade/u/home/glemieux/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 137, in expect
    raise exc_type(msg)

```

**Comment by ekluzek** [comment]
OK, I looked into this. And I see the problem on the fates_main_api branch. There's a fix that went into  ctsm1.0.dev105 in namelist_defaults_overall.xml. We could fix it either by updating to at least that version of CTSM, or by bringing a change to clm_start_type settings to that file by hand. @glemieux how would you like to handle this?

**Comment by glemieux** [comment]
@ekluzek I merged 105 into fates_main_api without any conflicts.  I'm going to try running a build test and the fates lightning test.

**Comment by glemieux** [comment]
A simple 1x1 site test and the `Fates_nat_and_anthro_ignitions` testmod passed tests.  I'll create a PR for this merge update and run the full fates regression suite in the near future.

**Comment by glemieux** [comment]
Closing per https://github.com/ESCOMP/CTSM/pull/1137
