### ISSUE TITLE
mksurfdata_map failing to run on hobart

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1133]
### Brief summary of bug

mksurfdata tests fail on hobart...

003 smi54 TSMscript_tools.sh mksurfdata_map mksurfdata.pl mksrfdt_10x15_1850^tools__ds .......... rc=6 FAIL
005 smi57 TSMscript_tools.sh mksurfdata_map mksurfdata.pl mksrfdt_10x15_1850^tools__do .......... rc=6 FAIL
007 smiT4 TSMscript_tools.sh mksurfdata_map mksurfdata.pl mksrfdt_1x1_numaIA_crp_2000^tools__ds . rc=6 FAIL

### General bug information

**CTSM version you are using:** ctsm1.0.dev108-7-g4f678353

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** Just running mksurfdata_map
### Details of bug

[Fill in details here.]

### Important details of your setup / configuration so we can reproduce the bug

All the tests are failing (but they run on cheyenne and izumi).

### Important output or errors that show the problem

Seems to have trouble opening the file again.

>  Set wetland to 0% over land
> In mkpftMod::mkpftInit()...
> forrtl: severe (168): Program Exception - illegal instruction
> Image              PC                Routine            Line        Source             
> mksurfdata_map     000000000058FA6B  Unknown               Unknown  Unknown
> libpthread-2.17.s  00002B8AA9C136D0  Unknown               Unknown  Unknown
> libnetcdf.so.13.1  00002B8AA965A5D7  Unknown               Unknown  Unknown
> libnetcdf.so.13.1  00002B8AA96588A9  NC4_open              Unknown  Unknown
> libnetcdf.so.13.1  00002B8AA95D6854  NC_open               Unknown  Unknown
> libnetcdf.so.13.1  00002B8AA95D5A9B  nc_open               Unknown  Unknown
> libnetcdff.so.6.1  00002B8AA9197E7F  nf_open_              Unknown  Unknown
> mksurfdata_map     000000000053E3F1  mkurbanparmod_mp_          80  mkurbanparMod.F90
> mksurfdata_map     00000000004F6ED5  MAIN__                    389  mksurfdat.F90
> mksurfdata_map     00000000004051A2  Unknown               Unknown  Unknown
> libc-2.17.so       00002B8AA9E42445  __libc_start_main     Unknown  Unknown
> mksurfdata_map     00000000004050A9  Unknown               Unknown  Unknown
> ERROR in mksurfdata_map: 43008

**Comment by ekluzek** [comment]
Since it works on cheyenne and izumi I'm marking this as a wontfix. I think we should remove the testing on hobart.

**Comment by billsacks** [comment]
@ekluzek I assume you meant to actually close this issue. I'm doing so.
