### ISSUE TITLE
mkmapdata.sh is failing to run on cheyenne

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1134]
### Brief summary of bug

Simple test of mkmapdata.sh is failing

qsub -- env RES=4x5 regridbatch.sh

### General bug information

**CTSM version you are using:** ctsm1.0.dev108-5-g1aa1df61
**Does this bug cause significantly incorrect results in the model's science?** No
**Configurations affected:** 

Just creation of mapping files

### Important details of your setup / configuration so we can reproduce the bug

[Specify anything relevant: the compset, resolution, machine, compiler, any xml or namelist changes, etc. You don't have to repeat anything that you have already noted above.]

### Important output or errors that show the problem

> un with standard options
> Create mapping files for this list of resolutions: 4x5
> Create mapping files for: 4x5
> /var/spool/pbs/mom_priv/jobs/3939474.chadmin1.ib0.cheyenne.ucar.edu.SC: line 73: [: !=: unary operator expected
> global
> global
> args: -r 4x5    -t global -b
> time env REGRID_PROC=8 ./mkmapdata.sh -r 4x5    -t global -b\n
> ./mkmapdata.sh
> Script to create mapping files required by mksurfdata_map
> query command is ./../../bld/queryDefaultNamelist.pl -silent -namelist clmexp  -justvalue -options sim_year=2000 -csmdata /glade/p/cesmdata/cseg/inputdata
> 
> Using default scrip grid file: /glade/p/cesmdata/cseg/inputdata/lnd/clm2/mappingdata/grids/SCRIPgrid_4x5_nomask_c110308.nc
> Output grid resolution is 4x5
> Hostname = r7i0n29
> Lmod has detected the following error: These module(s) exist but cannot be
> loaded as requested: "esmf_libs/7.1.0r"
>    Try: "module spider esmf_libs/7.1.0r" to see how to load the module(s).
> 
> 
> 
> 
> Due to MODULEPATH changes, the following have been reloaded:
>   1) mpt/2.22     2) ncarcompilers/0.5.0     3) ncl/6.6.2     4) netcdf/4.7.3
> 
> The following have been reloaded with a version change:
>   1) intel/19.0.5 => intel/18.0.5
> 
> Lmod has detected the following error: These module(s) exist but cannot be
> loaded as requested: "esmf-7.1.0r-ncdfio-mpi-O"
>    Try: "module spider esmf-7.1.0r-ncdfio-mpi-O" to see how to load the
> module(s).
> 
> 
> 
> Path to ESMF binary directory does NOT exist: 
> Set the environment variable: ESMFBIN_PATH

**Comment by ekluzek** [comment]
I'm thinking this might have been fixed in #1255?

**Comment by ekluzek** [comment]
A Forum person noticed this error

https://bb.cgd.ucar.edu/cesm/threads/mkmapdata-sh-error-for-3x3min_modis-wcsp.6076/

@jtruesdal @MiCurry

**Comment by MiCurry** [comment]
@ekluzek I was able to run mkmapdata.sh correctly on Cheyenne, but that's with the release-clm5.0.34 tag. (Currently, I'm just creating mapping and domain files for the 60 km mesh just to get my feet wet. Not for anything official). Is that version older than this version of mkmapdata.sh?

As well, FYI, the forum poster, Jihyeon Jang is an MMM scientific staff who is analyzing CAM-MPAS simulation, and helping initialize the land component.

**Comment by ekluzek** [comment]
@MiCurry hmmm I'm not sure. But, if the release-clm5.0.34 version is working for you you should be good to go at least to make the mapping files. I'm somewhat surprised that it works there, but not on the development version. This problem causes the whole process to fail so its unusable in its current form, so the fact that you get it to run is good.

I do recommend making surface datasets with the latest development version. And after I fix this I suggest doing the whole process on the latest development version. When ctsm5.2.0 comes out it'll include changes in mksurfdata so you'll absolutely need the development version over the release version at that point.

**Comment by MiCurry** [comment]
@ekluzek sounds good. I'll be sure to use the development version once you add in the fix!
