### ISSUE TITLE
Global history attribute 'source' for CLM5 (and CLM4.5) history files is incorrect

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#1138]
The global attribute source = "Community Land Model CLM4.0" that appears in the CLM5 (and presumably CLM4.5) history files and timeseries files is a bit confusing to some users.

This appears to be coded in components/clm/src/main/clm_varctl.F90:

character(len=256), public :: source   = "Community Land Model CLM4.0"

The 'version' history attribute is more informative, e.g., for one of the CMIP6 simulations, it is:

version = "cesm2.1.1-exp14"

So maybe 'source' can be deleted, or updated.

**Comment by wwieder** [comment]
This would be nice to change!  Maybe info on the tag it was even made from in a land only run?

**Comment by ekluzek** [comment]
Looks like this was fixed in bb9fe21c5. So closing.
