### ISSUE TITLE
Decrease expense of ne0ARCTICGRISne30x8 test and C96 tests

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1139]
The test `SMS_Ln9.ne0ARCTICGRISne30x8_ne0ARCTICGRISne30x8_mt12.ISSP585Clm50BgcCrop.cheyenne_intel.clm-clm50cam6LndTuningMode` takes 470 core-hours to run, which is about 3x as expensive as any other test in the aux_clm test suite. To put this in perspective: If the aux_clm test suite is run 100 times per year (which is not at all unreasonable), this one test would use up nearly 1% of the SEWG annual allocation.

Nearly all of the time in this test is spent in model initialization – probably (though I haven't confirmed) in init_interp.

We should think about what is really important about this test, and trim it down so that it is just testing the aspects that are truly important to test here. My guess is that we're not getting any additional code coverage (of the Fortran code) from this test, so it is mostly about testing compatibility of datasets. If so, can we cover this well enough with a cold start test? Or even by just relying on build-namelist testing for this resolution?

I know that it would be ideal to have a somewhat realistic test of every supported resolution, but our aux_clm test suite is unmanageably large, so I feel we need to be a little more thoughtful here, and cut some corners even if it means slightly increasing the risk that issues will be discovered in production. I feel it's important to ensure that as much as possible of our Fortran code is covered in the test suite, but if a user occasionally runs into a problem where a run at a particular (fairly obscure) resolution doesn't get off the ground, I feel that's an acceptable risk to take.

**Comment by billsacks** [comment]
When I was looking at test expense last week, I somehow missed these extremely expensive C96 tests:

- `ERS_D_Ld10.C96_C96_mg17.IHistClm50Sp.cheyenne_intel.clm-decStart` - 450 core hours

- `ERI_D_Ld9.C96_t061.I2000Clm50SpRsGs.cheyenne_intel.clm-default` - 610 core hours

- `ERP_D_Ld5.C96_C96_mg17.IHistClm50BgcCrop.cheyenne_intel.clm-allActive` - 690 core hours

I feel it is high priority to figure out a way to remove these or significantly decrease their expense, since they are burning our allocation and slowing down our testing.

**Comment by billsacks** [comment]
At a minimum: high-res cases should just be short smoke tests, non-debug or very short debug. But we may want to do more than that.

**Comment by ekluzek** [comment]
C96 is one degree resolution. So it's not really a high resolution case. And we should compare it to other 1-degree cases. One thing we could do is to make sure they are using stub glacier and stub river, and then just do a 9 step test for them.

**Comment by ekluzek** [comment]
I'm thinking the best to do for the ne0ARCTICGRISne30x8 case is to rely on the build-namelist testing for it (I already have it in place for it and other special resolutions as well). So we could remove the explicit test for it. The build-namelist test takes care of most of what's needed, making sure the namelist is created and the datasets are in place.

**Comment by ekluzek** [comment]
Possibly another thing we should have is an additional test list to run for scientifically supported resolutions. aux_clm could be the one we do for most tags. But, sci_clm (or whatever we call it) would be additionally run for release tags or at times we want to make sure the scientifically supported resolutions are all working well.

**Comment by billsacks** [comment]
@ekluzek I agree with all of your thoughts here. See also #1141 for some additional thoughts, but I'm comfortable just relegating this to a build-namelist test if you are. The idea of having a `sci_clm` list (or release test list, etc.) also seems reasonable. Another option would be to do what CAM is doing: putting some of these additional resolutions in the prealpha or prebeta test lists rather than aux_clm.

Regarding C96 being at 1 degree resolution: About a year ago, I changed our 1-degree tests to generally be short-ish non-debug smoke tests, leaving the debug and ERP/ERI testing for coarse resolutions. So that should be done here, too.

**Comment by billsacks** [comment]
@ekluzek 's feeling that I'm good with: let's just rely on build-namelist testing, together with a sci_clm test list.

**Comment by billsacks** [comment]
I have resolved this in c7723f917. Note that this is on a branch off of the branch for #1151 . I'm not sure if we'll end up merging that branch; if not, c7723f917 can be cherry-picked elsewhere.

**Comment by ekluzek** [comment]
We should talk more about the C96 tests. Since it's the standard fv3 resolution, I don't want to just remove them. I think we should at least have one in place, but keep it short and non-debug. The others we should move to the new ctsm_sci list. We can talk more at our meeting this afternoon.

**Comment by billsacks** [comment]
I'd also like to talk about removing some of these tests or at least reducing their core counts:
- ERS_Ln9.ne0ARCTICne30x4_ne0ARCTICne30x4_mt12.IHistClm50SpGs.cheyenne_intel.clm-clm50cam6LndTuningMode_1979Start
- SMS_Ln9.ne0ARCTICGRISne30x8_ne0ARCTICGRISne30x8_mt12.IHistClm50Sp.cheyenne_intel.clm-clm50cam6LndTuningMode_1979Start
- SMS_Ln9.ne0CONUSne30x8_ne0CONUSne30x8_mt12.IHistClm50Sp.cheyenne_intel.clm-clm50cam6LndTuningMode_2013Start

While not as expensive as the others in this issue, their high core counts means that their queue wait times are high, so they hurt test suite turnaround time.

**Comment by ekluzek** [comment]
> I'd also like to talk about removing some of these tests or at least reducing their core counts:
> 
> * ERS_Ln9.ne0ARCTICne30x4_ne0ARCTICne30x4_mt12.IHistClm50SpGs.cheyenne_intel.clm-clm50cam6LndTuningMode_1979Start
> * SMS_Ln9.ne0ARCTICGRISne30x8_ne0ARCTICGRISne30x8_mt12.IHistClm50Sp.cheyenne_intel.clm-clm50cam6LndTuningMode_1979Start
> * SMS_Ln9.ne0CONUSne30x8_ne0CONUSne30x8_mt12.IHistClm50Sp.cheyenne_intel.clm-clm50cam6LndTuningMode_2013Start
> 
> While not as expensive as the others in this issue, their high core counts means that their queue wait times are high, so they hurt test suite turnaround time.

We decided to move these into the "ctsm_sci" test list.
