### ISSUE TITLE
Fire btran2 is only computed for exposed veg patches, but is used over all veg patches

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1153]
### Brief summary of bug

From examining the fire code, it looks like btran2 is used over all vegetated patches, but it is only computed each time step over the exposed veg patches. I think this means that, for non-exposed patches, it is using the btran2 value from whenever the patch was last exposed. This seems scientifically questionable.

### General bug information

**CTSM version you are using:** master

**Does this bug cause significantly incorrect results in the model's science?** Yes (I think... but impact is probably relatively small)

**Configurations affected:** All configurations with fire active

### Details of bug

btran2 is accessed for all vegetated patches:

https://github.com/ESCOMP/CTSM/blob/5cd28a0db17c22f10447c819edfad38d5239dab3/src/biogeochem/CNFireLi2016Mod.F90#L346-L360

yet I'm pretty sure its calculation is just done over the exposed veg filter (in calc_root_moist_stress_clm45default).

#1151 refactors this, but I don't think it changes the points over which btran2 is calculated. In fact, I noticed this when reviewing #1151, because that PR makes the filter over which btran2 is calculated more explicit.

I think this means that the btran2 values over non-exposed vegetated patches are taken from some previous time step – whenever the given patch was last exposed. I'm not sure how much of an impact this has on the results, but it feels wrong.

Probably what should be done is that some assumed btran2 value is used over non-exposed vegetated patches – probably 1. In principle this could require retuning of the fire model, but I hope the impact would be relatively small because there hopefully aren't many fires in these non-exposed (which I think implies snow-covered) points.

I'm hopeful that this change would also allow us to remove btran2 from the restart file.

**Comment by ekluzek** [comment]
This is the advantage of having the fire-specific setting of btran2 in the fire code, it makes this more obvious. When they are strewn around it's harder to tell if things like this match up.

We should bring @lifang0209 into the conversation to ask about if this was intentional or not, and the impacts of changing it.

**Comment by billsacks** [comment]
From @dlawrenncar and myself: if there's no exposed veg, let's set btran2 to 1. I'll fold this into the upcoming btran2 tag.

**Comment by billsacks** [comment]
Actually, given @dlawrenncar 's point mentioned here https://github.com/ESCOMP/CTSM/issues/1170#issuecomment-702255734 - that btran2 is spval over bare patches, and so these bare patches are currently excluded from the average: I think the most consistent thing to do is to only include currently exposed veg patches in the btran2 column averages. This will treat veg patches that are either (a) leaf-free or (b) fully snow-covered the same as the bare ground patch, which feels like the right thing to do.

One implication of this is that, if there is currently no exposed veg on a column, my proposal will lead to the block of code that forces `fire_m = 0` (because wtlf will be 0). Currently, in contrast, it looks like fire_m is allowed to be non-zero even if there is currently no exposed veg, because btran2 and wtlf are accumulated if a patch *ever* was exposed in the past.

@dlawrenncar - can you let me know if my plan of only averaging btran2 over exposed veg patches makes sense to you (as opposed to our earlier plan of prescribing btran2 = 1 over non-exposed patches)?

**Comment by dlawrenncar** [comment]
Yes.  Your proposal sounds correct to me.

**Comment by billsacks** [comment]
Even though btran2 is now only referenced over exposed veg patches, I still need to set it to some value over non-exposed patches for the sake of history diagnostics. The original btran variable is set to 0 over these non-exposed patches, so that's what I'll do here, too.

**Comment by ekluzek** [comment]
@billsacks I thought it set the entire array of btran2 to spval, just before setting up the history variable. So shouldn't that be what's done? Or are you talking about patches that go from non-exposed to exposed and vice-versa? Those would've just retained their previous value until they are exposed again and can change, which isn't likely the right thing.

**Comment by billsacks** [comment]
> Or are you talking about patches that go from non-exposed to exposed and vice-versa? Those would've just retained their previous value until they are exposed again and can change, which isn't likely the right thing.

Yes, that's exactly what I mean.
