### ISSUE TITLE
PHS parameters (kmax, krmax) inappropriate for the parameter perturbation experiment

### ISSUE THREAD

**Issue by djk2120** [ESCOMP/CTSM#1162]
The CLM5 default values of 2 PHS parameters (kmax, krmax) seem to be outside the reasonable range for some PFTs. 
Example 1: kmax is likely too high for grasses and shrubs
Example 2: krmax is an order of magnitude smaller for needleleaf temperate trees than for any other PFT

GPP will generally increase with increases to either kmax or krmax, but with a highly saturating effect. We found that for several PFTs you could lower these parameters significantly without large effects on mean GPP (e.g. lowering C3G kmax by ~10x resulted in a change in GPP of only -0.3%). Even though mean GPP doesn't change much in this case, we expect that this could have an effect on GPP IAV (e.g. that change sees C3G GPP IAV increase by 2.3%) and will certainly affect the model sensitivity to changes in the other PHS parameter psi50. Likewise, having kmax so far beyond where there is meaningful increases in GPP does not comport well with hydraulic theory.

Our goal with a new set of default kmax/krmax values is to set the default values somewhere near the center of their reasonable ranges. We have provided a new set of default values for kmax and krmax for the natural vegetation PFTs. This was considered important for the impending CLM5 parameter perturbation experiment. We will likely revisit parameter estimation after the PPE, when we will have more information to consider addressing model biases. 

Overall we expect neither major improvements nor degradations to model climatology from this effort. NEMT GPP and LAI will likely be degraded, but we could not justify maintaining the highly restrictive krmax from CLM5.0

More information on our process can be found online [here](https://nbviewer.jupyter.org/github/djk2120/CLM5PPE/blob/master/pyth/PHSparams.ipynb).
Some results comparing the new parameter set to two recent branch tags can be found [here](http://webext.cgd.ucar.edu/I20TR/clm50_ctsm10d089_2deg_GSWP3V1_luna3_hist/lnd/_build_LMBIRCH4_PHSPARAM/index.html).

**Comment by billsacks** [comment]
@djk2120 what's the status of this? Is this already done with recent parameter file updates? If not, can you tell us what exact changes should be made?

**Comment by wwieder** [comment]
great, looks like this is resolved.
