### ISSUE TITLE
CNFireLi2021Mod reintroduces a number of bugs that were fixed in earlier versions

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1169]
### Brief summary of bug

From comparing CNFireLi2016Mod.F90 with CNFireLi2021Mod.F90 I see that the latter reintroduces a number of bugs that were fixed in earlier versions.

### General bug information

**CTSM version you are using:** ctsm5.1.dev004

**Does this bug cause significantly incorrect results in the model's science?** Yes

**Configurations affected:** CLM51 compsets

### Details of bug

Issues that I see are:

#### Significant issues

** @ekluzek can you please work on the following, some of which are answer-changing: **

- [x] The accumulations of trotr1_col and trotr2_col should not have `*col%wtgcell(c)` (fixed in `clm4_5_12_r195` for the older fire modules)
  - (2020-10-01) Fixed in 7a7ab79dc

- [x] The accumulation of dtrotr_col should not have `*col%wtgcell(c)` (fixed in `clm4_5_14_r223` for the older fire modules)
  - (2020-10-01) Fixed in 7a7ab79dc

- [x] nfire(c) needs to be initialized to 0 (fixed in 1b6c2bae3 for the older fire modules)
  - (2020-10-01) Fixed in b45f492f4

- [ ] Two hard-coded parameters that were recently pulled out to the parameter file have returned to being hard-coded in this version of the fire code: prh30 and ignition_efficiency

- [ ] Given these regressions, the other diffs between the 2016 and 2021 modules in the loop starting with the comment "begin column loop to calculate fractional area affected by fire" should be carefully reviewed to confirm that all of these differences are intentional (and not other regressions of bugs we have previously fixed).

#### Minor issues

**I'll fix these myself in an upcoming tag**

- [x] CNFireLi2021Mod uses `SHR_ASSERT_ALL` rather than the newer & preferred `SHR_ASSERT_ALL_FL`

- [x] dt should be set from `get_step_size_real()`

Edit: I have fixed both of these in #1155

**Comment by ekluzek** [comment]
@olyson this first issue in this list would be a problem in your simulations you are doing with the arctic branch. We don't think it should matter much, but it would be an issue.

**Comment by olyson** [comment]
I had restarted the spinup yesterday with that branch due to the organic_frac_squared issue, and then saw the the fire issue, so I've stopped the spinup until we decide how/if we want to resolve the fire issue.  I assume we'll discuss at the PPE meeting.

**Comment by ekluzek** [comment]
@billsacks I looked at the original issue and the first two of your suggestions contradict what Fang Li asked for in the changes. She actually explicitly asked to add *col%wtgcell(c) to trotr1_col, trotr2_col, and dtrotr_col.

nfire should be changes as suggested, although it likely won't matter much.

**Comment by ekluzek** [comment]
Fang's original issue is #889

**Comment by ekluzek** [comment]
The fix for prh30 and ignition_efficiency looks like this...

``` fortran
@@ -601,7 +601,7 @@ subroutine CNFireArea (this, bounds, num_soilc, filter_soilc, num_soilp, filter_
            if (trotr1_col(c)+trotr2_col(c)<=0.6_r8) then  
               afuel  =min(1._r8,max(0._r8,(fuelc(c)-2500._r8)/(5000._r8-2500._r8)))
               arh=1._r8-max(0._r8, min(1._r8,(forc_rh(g)-rh_low)/(rh_hgh-rh_low)))
-              arh30=1._r8-max(0.7_r8, min(1._r8,rh30_col(c)/90._r8))
+              arh30=1._r8-max(cnfire_params%prh30, min(1._r8,rh30_col(c)/90._r8))
               if (forc_rh(g) < rh_hgh.and. wtlf(c) > 0._r8 .and. tsoi17(c)> SHR_CONST_TKFRZ)then
                 fire_m   = ((afuel*arh30+(1._r8-afuel)*arh)**1.5_r8) &
                              *((1._r8-btran_col(c)/wtlf(c))**0.5_r8)
@@ -611,8 +611,8 @@ subroutine CNFireArea (this, bounds, num_soilc, filter_soilc, num_soilp, filter_
               lh       = pot_hmn_ign_counts_alpha*6.8_r8*hdmlf**(0.43_r8)/30._r8/24._r8
               fs       = 1._r8-(0.01_r8+0.98_r8*exp(-0.025_r8*hdmlf))
               ig       = (lh+this%forc_lnfm(g)/(5.16_r8+2.16_r8* &
-                     cos(SHR_CONST_PI/180._r8*3*min(60._r8,abs(grc%latdeg(g)))))*0.22_r8)  &
-                         *(1._r8-fs)*(1._r8-cropf_col(c))
+                     cos(SHR_CONST_PI/180._r8*3*min(60._r8,abs(grc%latdeg(g)))))* &
+                         cnfire_params%ignition_efficiency)*(1._r8-fs)*(1._r8-cropf_col(c))
               nfire(c) = ig/secsphr*fb*fire_m*lgdp_col(c) !fire counts/km2/sec
               Lb_lf    = 1._r8+10._r8*(1._r8-EXP(-0.06_r8*forc_wind(g)))
               spread_m = fire_m**0.5_r8
```

**Comment by billsacks** [comment]
We think the parameter issue was fixed in the PPE branch. The remaining issue was just to do a more careful review of the 2021 code, but we'll close this issue as fixed enough.
