### ISSUE TITLE
btran2 not initialized to zero in CNFireLi2021Mod.F90

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1171]
### Brief summary of bug

When I updated CNFire_calc_fire_root_wetness for CNFireLi2021, I left off the initialization of btran2 to zero like it's done in the base class. It was in originally, but I left it off when I refactored for Li2021 to have it's own subroutine.

### General bug information

**CTSM version you are using:** ctsm5.1.dev001

**Does this bug cause significantly incorrect results in the model's science?** Yes (for clm5_1)

**Configurations affected:** clm5_1 with fire turned on (for Clm51Bgc compsets)

### Details of bug

The problematic commit is 7f0025bf58b49296fda63a2ec957e62e5c93ca13.

**Comment by ekluzek** [comment]
One reason for this bug is that I didn't check answers for clm5_1, since they were already changing. But, I needed to separate out the answer changes from the changes that should be bit-for-bit, and neglected to do that. This would have required separating steps and creating separate baselines (or at least for a single sample case). I usually do this, but neglected to do this in this instance.

**Comment by ekluzek** [comment]
I'm going to run more tests on this. But, I have shown that the following test is identical with or without the zeroing of btran2. I'd still say the zeroing is correct though.

SMS_Lm13.f19_g17.I2000Clm51BgcCropGs.cheyenne_intel.clm-cropMonthOutput

**Comment by billsacks** [comment]
> I have shown that the following test is identical with or without the zeroing of btran2.

Thanks for doing that testing. That was a red flag for me, which led me to find #1173 . With the #1173 fix in place off of ctsm5.1.dev004 (before the fix here), I verified that btran2 quickly blows up into huge values.

**Comment by ekluzek** [comment]
With the fix in #1173 in place my testing is now showing that answers change as they should to the ctsm5.1.dev001 tag. I'm now going to test using the methodology before btran was inside of cnfire.

**Comment by ekluzek** [comment]
OK, I've now done the testing for the clm5_1 refactor that I should have done and shown that with #1173 in place the clm5_1 tests preserve answers versus the version where btran2 was calculated in SoilMoistStress. This tells me there weren't any other issues that I introduced in do that refactor of moving btran2 for clm5_1 into CNFire.

So the following tests give identical answers between those two as expected...

ERI_D_Ld9.f10_f10_musgs.I1850Clm51BgcGs.cheyenne_gnu.clm-default			
ERI_N2_Ld9.f19_g17.I2000Clm51BgcCropGs.cheyenne_intel.clm-default			
ERP_D.f10_f10_musgs.IHistClm51BgcGs.cheyenne_gnu.clm-decStart			
ERP_D.f10_f10_musgs.IHistClm51BgcGs.cheyenne_intel.clm-decStart			
ERP_D_Ld10_P36x2.f10_f10_musgs.IHistClm51BgcCropGs.cheyenne_intel.clm-ciso_decStart			
ERP_D_P36x2_Ld3.f10_f10_musgs.I2000Clm51BgcCropGs.cheyenne_intel.clm-coldStart			
ERP_D_P36x2_Ld5.f10_f10_musgs.I2000Clm51BgcCropGs.cheyenne_intel.clm-irrig_spunup			
ERP_Ld9.f45_g37.I2000Clm51BgcGs.cheyenne_intel.clm-default			
ERP_P36x2_Lm13.f10_f10_musgs.IHistClm51BgcGs.cheyenne_gnu.clm-monthly			
ERP_P36x2_Lm13.f10_f10_musgs.IHistClm51BgcGs.cheyenne_intel.clm-monthly			
ERP_P72x2_Lm25.f10_f10_musgs.I2000Clm51BgcCropGs.cheyenne_intel.clm-monthly			
ERS_Ly5_P144x1.f10_f10_musgs.IHistClm51BgcCropGs.cheyenne_intel.clm-cropMonthOutput			
LCISO_Lm13.f10_f10_musgs.IHistClm51BgcCropGs.cheyenne_intel.clm-ciso_monthly			
LVG_Ld5_D.f10_f10_musgs.I1850Clm51BgcGs.cheyenne_intel.clm-no_vector_output			
SMS_Lm13.f19_g17.I2000Clm51BgcCropGs.cheyenne_intel.clm-cropMonthOutput			
SSP_D_Ld10.f19_g17.I1850Clm51BgcGs.cheyenne_intel.clm-rtmColdSSP
