### ISSUE TITLE
mkmapdata needs input option for large file support, current defaults unsuitable for high res grids.

### ISSUE THREAD

**Issue by jtruesdal** [ESCOMP/CTSM#1183]
### Brief summary of bug

mkmapdata fails while trying to create a mapping file for high resolution grids.  Problem solved by allowing large file support for output map.  Would be nice to have some check to see if large file support necessary or put in support for passing that option as a parameter to regrid_batch.sh and mkmapdata.sh

### General bug information

**CTSM version you are using:** ctsm1.0.dev108

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** 
I was creating land mapping files for a spectral ne480pg3 resolution when the failure occurred.

### Details of bug

I was able to manually reset the script variable DST_LRGFIL to "64bit_offset" and the script to complete successfully
``` bash
#   DST_LRGFIL="none"
    DST_LRGFIL="64bit_offset"
```

### Important output or errors that show the problem

> NetCDF Error: map_5x5min_nomask_to_ne480pg3_nomask_aave_da_c201009.nc : NetCDF: One or more variable sizes violate format constraints
>  ERROR: Problem on processor            0 
>  . Please see the PET*.RegridWeightGen.Log files for a traceback.
> Error status returned from mkmapdata script

**Comment by billsacks** [comment]
Discussion from ctsm-software meeting: Maybe just always use 64-bit offset.
