### ISSUE TITLE
SLATOP param value incorrect for Generic C3 irrigated crop

### ISSUE THREAD

**Issue by dlawrenncar** [ESCOMP/CTSM#1184]
### Brief summary of bug

It looks like slatop for generic C3 irrigated crop is 'wrong'.  Not sure what the right value is, but it should be consistent with C3 unirrigated, which is currently set to 0.04024 (same as C3 grass).  Instead, generic C3 irrigated crop is set to 0.035.

### General bug information

**CTSM version you are using:** [output of `git describe`]

**Does this bug cause significantly incorrect results in the model's science?** Yes-ish.  Would only impact non-crop simulations with irrigation on. 

**Configurations affected:** All CLM5 parameter files?

### Details of bug

No more details.  Can be easily rectified when we move to new parameter file for CTSM5.1.  Not sure how important to fix in CTSM5 parameter file.

**Comment by ekluzek** [comment]
Here's what the three are for sample clm4_5, clm5_0 and ctsm5_1 files:

here index 15 is grass, 16 is unirrigated, and 17 is irrigated.

> src/fates> ncdump -f f -v slatop $CSMDATA/lnd/clm2/paramdata/clm45_params.c200926.nc | grep 'slatop(1[567])'
>     0.03,   // slatop(15)
>     0.03,   // slatop(16)
>     0.03,   // slatop(17)
> src/fates> ncdump -f f -v slatop $CSMDATA/lnd/clm2/paramdata/clm50_params.c200926.nc | grep 'slatop(1[567])'
>     0.03846,   // slatop(15)
>     0.04024,   // slatop(16)
>     0.035,   // slatop(17)
> src/fates> ncdump -f f -v slatop $CSMDATA/lnd/clm2/paramdata/ctsm51_params.c200926.nc | grep 'slatop(1[567])'
>     0.03846,   // slatop(15)
>     0.04024,   // slatop(16)
>     0.035,   // slatop(17)

So they are consistent for clm4_5. We can easily change for ctsm5_1, we just have to decide if clm5_0 should be changed.

**Comment by billsacks** [comment]
Discussion from today's ctsm-software meeting: Fix it for both clm5_0 and ctsm5_1.
