### ISSUE TITLE
hist_avgflag_pertape doesn't always produce desired averaging type for some history file streams

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#1191]
### Brief summary of bug

The hist_avgflag_pertape doesn't always produce the desired averaging type for some history file streams in a global simulation

### General bug information

release-cesm2.1.2 (release-clm5.0.30)

**Does this bug cause significantly incorrect results in the model's science?** Yes

**Configurations affected:** Global B-case and global I-case.  Single point I-case seems to work fine.

### Details of bug

A user reported that they weren't getting the desired averaging type in some of their history file streams.  For example, they specified hist_avgflag_pertape = 'X' for a history stream and got an average value instead of a maximum value for the variable of interest.  The time attribute is indeed cell_methods = "time: mean", not cell_methods = "time: maximum"
Their specific configuration is:

h0 'A' works
h1 'X' works
h2 'A' works
h3 'A' works
h4 'X' doesn't work
h5 'M' doesn't work
h6 'A' works
h7 'A' works
h8 'X' doesn't work
h9 'X' doesn't work

I reproduced this problem in my own version of their simulation (global fully coupled).
I then tried a single point simulation with the same history file configuration and it works fine.
I tried a global land-only simulation and had the same problem as in the full coupled simulation.

So far I can't figure out why the hist_avgflag_pertape is being overwritten or ignored for the global simulations for some history file streams but not in the single point case.  I've simplified the streams by just asking for "TSA" in each of the streams.  It's interesting that the specification of 'X' for h1 works, but not for h4, h8, or h9.

### Important details of your setup / configuration so we can reproduce the bug

My global land-only case that has the problem is:

/glade/work/oleson/release-cesm2.1.2/cime/scripts/clm50_cesm212R_2deg_GSWP3V1_TestAvgFlag_1850

My single point simulation that works fine is:

/glade/work/oleson/release-clm5.0.34/cime/scripts/conclm50r34wspinsp_AR-SLu_TESTAVGFLAG_I1PtClm50SpGs

### Important output or errors that show the problem

The history files that are generated are in my scratch directory with these case names.

**Comment by olyson** [comment]
An additional piece of information is that the lnd.log file shows the proper averaging for each history file.  So hist_avgflag_pertape is being read in correctly, e.g.,

 htapes_fieldlist : Included fields tape            2 =           1
           1  TSA
           1  X
 htapes_fieldlist : Included fields tape            3 =           1
           1  TSA
           1  A
 htapes_fieldlist : Included fields tape            4 =           1
           1  TSA
           1  A
 htapes_fieldlist : Included fields tape            5 =           1
           1  TSA
           1  X
 htapes_fieldlist : Included fields tape            6 =           1
           1  TSA
           1  M
 htapes_fieldlist : Included fields tape            7 =           1
           1  TSA
           1  A
 htapes_fieldlist : Included fields tape            8 =           1
           1  TSA
           1  A
 htapes_fieldlist : Included fields tape            9 =           1
           1  TSA
           1  X
 htapes_fieldlist : Included fields tape           10 =           1
           1  TSA
           1  X

**Comment by billsacks** [comment]
I think I see the issue, but haven't tested to confirm:

I think this mpi_bcast isn't broadcasting enough bytes:

https://github.com/ESCOMP/CTSM/blob/d3c31a3764c26135d58797cb2e753dbd438e5e62/src/main/controlMod.F90#L810

In place of `size(hist_avgflag_pertape)` I think we need `len(hist_avgflag_pertape)*size(hist_avgflag_pertape)`.

**Comment by billsacks** [comment]
Or, better, replace this call (and other calls) to mpi_bcast with `shr_mpi_bcast`, which does what I suggested for you.

**Comment by olyson** [comment]
So glad you figured that out!  I never would have...
I tried your first suggestion and that worked.
I'll try your second suggestion also.

**Comment by billsacks** [comment]
Well, consider it good teamwork: it was all of the clues put together from your extensive testing and documentation of the problem that led me right to the bug.

Actually, for now, I probably wouldn't worry about the second suggestion: the first suggestion keeps things consistent with the rest of the code in that routine, and it probably makes sense for us to do a pass through that whole subroutine at some point, replacing all of the mpi_bcast calls with shr_mpi_bcast.

**Comment by ekluzek** [comment]
Thanks @olyson and @billsacks for getting a solution to this. This would be a problem on both master and releases. It seem like we should fix it in both master and release-clm5.0. I think I'll leave release-cesm2.2 alone unless we have to do something else there. Somebody let me know if you think we shouldn't fix it on release-clm5.0, or think we should fix release-cesm2.2.

**Comment by billsacks** [comment]
@ekluzek I agree with your plan. Though it seems like a simple enough fix that, if we end up needing to make another tag on the release-cesm2.2 branch anyway, this could be folded in to it. The hardest part would be remembering to do so....
