### ISSUE TITLE
Concatenated ndep file was put together incorrectly 

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1202]
### Brief summary of bug

The. ndep file: /glade/p/cesmdata/cseg/inputdata/lnd/clm2/ndepdata/fndep_clm_f09_g17.CMIP6-SSP3-7.0-WACCM_1849-2101_monthly_c191007.nc

was put together just using ncrcat, but the time-axis units from the two files are different and hence time is incorrect on the file. The first file is relative to 1849 and the second part relatie to 2014, hence they won't join together correctly.

### General bug information

**CTSM version you are using:** release-clm5.0.34

**Does this bug cause significantly incorrect results in the model's science?** Yes
**Configurations affected:** BGC

### Details of bug

When putting the two files together the total length should have been 1980 (the length of the historical period). + 3036 (the length of the future scenario) so 5016. The length is 3036, because the time units are different. Hence it's really just the future scenario, but labeled as a 1849 reference time.

### Important details of your setup / configuration so we can reproduce the bug

I noticed this in. the SMYLE setup with the following...

```
 model_year_align_ndep = 1850
 ndep_taxmode = 'limit'
 stream_year_first_ndep = 1850
 stream_year_last_ndep = 2025
```

### Important output or errors that show the problem

Using the file to start in 1850 I get the following error...

> (shr_strdata_print) nvectors    =      0
> (shr_strdata_print) ----------------------------------------------------------
>  (shr_stream_findBounds) ERROR: limit on and rDateIn lt rDatelvd
>    18500101.0000000        18500116.5000000     
>  ERROR: (shr_stream_findBounds) ERROR: rDateIn lt rDatelvd limit true

**Comment by ekluzek** [comment]
I thought population density might have the same problem. But, it looks like they are put together correctly.

**Comment by olyson** [comment]
You must mean some other file that was created after the initial ndep files were generated.  The one you mentioned is the SSP370 file that runs from 2014-2101.

**Comment by klindsay28** [comment]
In my experience, ncrcat properly handles the situation of input files having different time units. It internally converts time values to uniform units.

**Comment by ekluzek** [comment]
Yes, correct. I just updated the filename. The concatenated file is: fndep_clm_f09_g17.CMIP6-SSP3-7.0-WACCM_1849-2101_monthly_c191007.nc and the original file is: fndep_clm_SSP370_b.e21.BWSSP370cmip6.f09_g17.CMIP6-SSP3-7.0-WACCM.001_2014-2101_monthly_0.9x1.25_c190401.nc

This is also my fault. I had thought that ncrcat would put them together correctly, but that's only in the case when the record dimension has the same units (in this case that means the same reference time).

**Comment by ekluzek** [comment]
@klindsay28 that is what I had thought as well, but it looks like it didn't do it correctly in this case. And I'm finding the same thing for some files I'm putting together now. Does that mean this is a bug? Or maybe there's a special option to do the conversion?

**Comment by ekluzek** [comment]
The discussion on the NCO forum says that there is a feature that can do this rebase if UDUNITS is installed.I wonder if the install is different on for example CGD systems than on cheyenne.

The example, they give also has to do something explicit to make it happen, but I still wonder if the build on cheyenne is different from CGD.

https://sourceforge.net/p/nco/discussion/9830/thread/00da810a/

**Comment by olyson** [comment]
The time dimension of the ncrcatted file should be (2101-1849+1)*12 = 3036, which it is, right?

**Comment by klindsay28** [comment]
Could you elaborate on the problem with `time` in the file `fndep_clm_f09_g17.CMIP6-SSP3-7.0-WACCM_1849-2101_monthly_c191007.nc`? I don't see any jumps in `time`, and the values appear to range from the beginning of 1849 to the end of 2101.

Shouldn't there be 3036 values for 1849-2101? I'm not sure where 5016 comes from.

**Comment by billsacks** [comment]
@ekluzek you labeled this as closed, but didn't actually close it... did you mean to close it?
