### ISSUE TITLE
Should we add this "point of interest" code somewhere?

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1208]
### Background

Yesterday, talking with @ekluzek @olyson and @negin513 , I showed them this "point of interest" code that I often plug in to my model build to assist with printing values for a given grid cell: https://github.com/billsacks/ctsm-debugging-aids/blob/master/point_of_interest.F90

The idea behind this is: When I'm seeing unexpected answer changes or problematic behavior, my first step is often to find one grid cell that exhibits the problem. I then identify the lat & lon of that grid cell (which I plug into `poi_lat` and `poi_lon` in the above code). Often I am particularly interested in a certain landunit, column or pft type, which I use to customize other parts of the above module. Then I use this code to print values of certain variables throughout the code, like:

```Fortran
use point_of_interest

  do fc = 1, num_nolakec
     c = filter_nolakec(fc)

     ! Various code here, maybe setting foo and bar variables

     if (poi_c(c)) then
        write(iulog,*) 'WJS: foo, bar = ', foo(c), bar(c)
     end if
  end do
```

@olyson says he basically does the same thing (he has done it so many times that he can essentially write the above `poi` code in his sleep each time he needs it – my words, not his). There was general agreement that it would be good to put code like this somewhere where it could be useful to others.

### My questions

1. Two possibilities that we discussed yesterday are either putting this module in the source code or posting it on the wiki. My inclination would be to put it in the source code and then mention it somewhere on the wiki. Do others have feelings about this? I know it's kind of weird to put this normally-uninvoked module in the source code, but it seems like doing so would make it easier for people to use it, and to keep it up to date if it needs to change. But I don't have strong feelings about that.

2. As it currently stands, it provides an initial skeleton that you then need to customize. For example, if you are interested in patch-level variables, you will need to write a `poi_p` function that is similar to the existing `poi_c` example (or change `poi_c` to `poi_p`). This has worked fine for my own use, but do people feel it's fine to just bring this in as it currently is or that it's important to clean this up in any way to make it more generally usable?

**Comment by wwieder** [comment]
I think this seems really useful!  should it go  into tools/contrib?

**Comment by billsacks** [comment]
Thanks, Will. My inclination was to put it directly in the source code – e.g., `src/utils/point_of_interest.F90`. That way it gets compiled in to every model build, which helps ensure that it stays up to date and I think makes it easier for someone to use it. True, it is unnecessarily included in the build in most cases, but I'd think that it would build very quickly so this shouldn't be a big issue.

**Comment by wwieder** [comment]
That makes sense to me.  It seems that a bit of documentation about how to
use the module would be helpful in the user's guide too?

**Comment by dlawrenncar** [comment]
Yes.  I agree.  Source code makes sense.  And a mention in the User's Guide
(section on Debugging?) and a link from the Wiki would make a lot of
sense.  I wonder if we could ask Keith to write up the short section, maybe
he can include some additional tips.

Dave

**Comment by olyson** [comment]
There is a already a "Trouble shooting" section in the User's Guide.  Maybe we could add it to that section.

**Comment by ekluzek** [comment]
It seems like you could add just a little more to make this useful. You could add optional namelist items to pick the lat and long of the point. Maybe there should be something in the namelist to say whether its turned on or not.

You could also add some code that uses it to print something out that could be useful when it's turned on. Then the instructions would just be how to turn it on in the namelist and how to copy the existing call for it. You'd want the existing call to be at a high level and maybe only called once a day so it wouldn't slow down the code. And by default turned off, but you don't want to add a lot of additional if statements that have to be evaluated constantly.

**Comment by billsacks** [comment]
Thanks, all, for your thoughts. @ekluzek I know I invited comments on whether we should try to make this more general, but reflecting on this, I'm having trouble seeing the value in some of these extra things. Regarding having an existing call in the code: I have trouble seeing how this helps, since each time this is applied it would be at a different place in the code and for a different variable or set of variables. And regarding having namelist control over the lat / lon: I see a bit of value in that, but in almost all cases, you still need to customize aspects of this code for it to be useful, so I actually feel that it's simpler to just keep this all hard-coded – so that the customization only consists of Fortran changes – rather than requiring the user to do some customizations in the code and others in namelist settings.

So I guess I'd propose bringing this in essentially as it is now and then just adding some documentation with examples of how to (1) customize it, and (2) apply it in the code.

**Comment by billsacks** [comment]
Thanks all for your comments. I have opened #1210 and #1211 describing what we want to do (separate issues for the addition of the code and for the documentation).
