### ISSUE TITLE
Frac_sno_eff out of range (larger than 1.0)

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#121]
**Leo van Kampenhout < l.vankampenhout > - 2015-08-24 05:06:03 -0600**
**Bugzilla Id:** [2203](http://bugz.cgd.ucar.edu/show_bug.cgi?id=2203)
**Bugzilla CC:**  l.vankampenhout,  sacks,  swensosc, 
**Bugzilla Attachment:**  Screen Shot 2015-08-06 at 12.09.04.png - example of a run with out-of-bound frac_sno_eff

I've tried diagnosing this myself last week but had to give up due to lack of time. Just wanted to report this here so maybe someone else or the future me has time to look at this further. 

How to reproduce: just set up any offline CLM compset, run it for a month or even a few days and notice that the variable FRAC_SNO_EFF becomes larger than 1.0 in the history files. As this is a fractional number that should range between 0 and 1 , this is a bug. Interesting is that the FRAC_SNO variable is not out of range. 

./create_newcase -case i1850_2d -res f19_g16 -project $PROJECT -compset I1850CLM45 -mach yellowstone

CLM version affected: development trunk clm4_5_1_r118

**Comment by ekluzek** [comment]
**Leo van Kampenhout < l.vankampenhout > - 2015-08-24 09:59:57 -0600**

Created attachment 59
example of a run with out-of-bound frac_sno_eff

**Comment by ekluzek** [comment]
**Leo van Kampenhout < l.vankampenhout > - 2015-10-26 07:11:01 -0600**

Still present in clm4_5_3_r142

**Comment by billsacks** [comment]
Since there has been a some work / rework of snow fraction in the last few years, we're going to close this in hopes that it has been fixed... @lvankampenhout or others, feel free to reopen or open a new issue if this is still an issue.
