### ISSUE TITLE
Add documentation on "point of interest" code once it is incorporated

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1211]
Emerging from #1208: Once we have added the "point of interest" code to the source tree (#1210), we'd like:

- [ ] Some documentation in the User's guide (troubleshooting section) about how to customize it and apply it in the code

- [ ] Some mention of this somewhere on the wiki, too?

Blocked by #1210

**Comment by billsacks** [comment]
I added the "point of interest" code in ctsm5.1.dev015, resolving #1210 . @dlawrenncar suggested that @olyson could perhaps work on this documentation issue at some point: https://github.com/ESCOMP/CTSM/issues/1208#issuecomment-724097852

**Comment by olyson** [comment]
I'll take a look at this next week.

**Comment by olyson** [comment]
I'm looking at the wiki, but I'm a little confused on how to edit, build, and commit the documentation for this.  I assume I don't need to use Docker for this.
Seems like I just need to clone the ctsm and ctsm-docs repositories, make my changes to the User's Guide, build and review the build, and then push to ctsm-docs.  Is that correct?

**Comment by billsacks** [comment]
@olyson - Long-term, we're trying to move to a Docker-based workflow for the documentation build to ensure that everyone is using the same version of sphinx and other related packages, so that the documentation appears consistently no matter who built it. If you have built the documentation recently and so have all of the prerequisites installed, and don't feel like dealing with the Docker installation right now, then it's okay for now if you stick with the old approach (either using the 'build_docs' command without the '-d' argument, or using the old approach of directly invoking 'make BUILDDIR=... html'). Long-term, though, I think it would be good if we converge on this Docker-based approach. Let me know if you have concerns about that.

(As an aside, this documentation build has proven to be something of a pain to support. I keep being tempted to either set up an automated documentation build on the cloud or suggesting moving to readthedocs, which does an automated build itself. However, neither of those would solve the problem of people wanting to do a test build for their own review, so I'm not sure how much they would help. If you or anyone else sees ways this could be made easier, I'm all ears.)

**Comment by olyson** [comment]
My only concern with the Docker approach is that I don't have permission to install software on my work laptop.  So I have to get a one-time password anytime I need to install new software.  I'm not sure if others have this problem, maybe I'm just not trustworthy.  
I haven't build the documentation for quite a while, so I will try the Docker approach.

**Comment by olyson** [comment]
I have Docker installed now.  But when I try to run it I get: Docker Desktop - Access denied. You are not allowed to use Docker. You must be in the "docker-users" group.  Any hints?  Should I contact ISG?

**Comment by billsacks** [comment]
Yes, please contact ISG.

**Comment by olyson** [comment]
I've installed Docker and am able to run it.  I've also installed python (3.9), git, and git lfs.
Has anyone tried this on a windows machine?
I have tried:

bash .\build_docs -b C:\Users\oleson\ctsm-repos\ctsm-docs\ -d

and got:

Running: doc-builder/build_docs --fetch-images -b C:\Users\oleson\ctsm-repos\ctsm-docs\ -d
/usr/bin/env: 'python3': Permission denied

I changed python3 to python in doc-builder/build_docs and got this error:

Running: doc-builder/build_docs --fetch-images -b C:\Users\oleson\ctsm-repos\ctsm-docs\ -d
make fetch-images
Traceback (most recent call last):
  File "C:\Users\oleson\ctsm-repos\ctsm\doc\doc-builder\build_docs", line 14, in <module>
    build_docs.main()
  File "C:\Users\oleson\ctsm-repos\ctsm\doc\doc-builder\doc_builder\build_docs.py", line 151, in main
    fetch_images()
  File "C:\Users\oleson\ctsm-repos\ctsm\doc\doc-builder\doc_builder\build_docs.py", line 140, in fetch_images
    subprocess.check_call(["make", "fetch-images"])
  File "C:\Users\oleson\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\oleson\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\oleson\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\oleson\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

I believe I have the directories setup correctly, I can't figure out what file it can't find....

**Comment by olyson** [comment]
Ok, looks like I needed to install make, which I've done, and the build seems to be proceeding now.

**Comment by olyson** [comment]
The build completed successfully and I looked at the documentation and it looked fine.
I then make some changes to an rst file and tried to rebuild but got this:

Running: doc-builder/build_docs --fetch-images -b C:\Users\oleson\ctsm-repos\ctsm-docs\versions\master\ -d
make fetch-images
git lfs pull --exclude=""
docker run --name build_docs_bxaxwggl --volume C:\Users\oleson:/home/user/mounted_home --workdir /home/user/mounted_home/ctsm-repos/ctsm/doc -t --rm escomp/base /bin/bash -c sudo mkdir -p C:\Users && sudo ln -s /home/user/mounted_home C:\Users\oleson && make BUILDDIR=C:\Users\oleson\ctsm-repos\ctsm-docs\versions\master\ -j 4 html
ln: failed to create symbolic link 'C:Usersoleson/mounted_home': File exists
Traceback (most recent call last):
  File "C:\Users\oleson\ctsm-repos\ctsm\doc\doc-builder\build_docs", line 14, in <module>
    build_docs.main()
  File "C:\Users\oleson\ctsm-repos\ctsm\doc\doc-builder\doc_builder\build_docs.py", line 190, in main
    run_build_command(build_command=build_command)
  File "C:\Users\oleson\ctsm-repos\ctsm\doc\doc-builder\doc_builder\build_docs.py", line 114, in run_build_command
    subprocess.check_call(build_command)
  File "C:\Users\oleson\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'run', '--name', 'build_docs_bxaxwggl', '--volume', 'C:\\Users\\oleson:/home/user/mounted_home', '--workdir', '/home/user/mounted_home/ctsm-repos/ctsm/doc', '-t', '--rm', 'escomp/base', '/bin/bash', '-c', 'sudo mkdir -p C:\\Users && sudo ln -s /home/user/mounted_home C:\\Users\\oleson && make BUILDDIR=C:\\Users\\oleson\\ctsm-repos\\ctsm-docs\\versions\\master\\ -j 4 html']' returned non-zero exit status 1.

The "mounted_home" file does already exist as a symbolic link.  I tried deleting the mounted_home file and got:

Running: doc-builder/build_docs --fetch-images -b C:\Users\oleson\ctsm-repos\ctsm-docs\versions\master\ -d
make fetch-images
git lfs pull --exclude=""
docker run --name build_docs_onvizvrt --volume C:\Users\oleson:/home/user/mounted_home --workdir /home/user/mounted_home/ctsm-repos/ctsm/doc -t --rm escomp/base /bin/bash -c sudo mkdir -p C:\Users && sudo ln -s /home/user/mounted_home C:\Users\oleson && make BUILDDIR=C:\Users\oleson\ctsm-repos\ctsm-docs\versions\master\ -j 4 html
sphinx-build -M 4 "source" "C:Usersolesonctsm-reposctsm-docsversionsmaster -j"
Running Sphinx v3.2.1

Sphinx error:
Builder name 4 not registered or available through entry point
make: *** [Makefile:42: 4] Error 2
Traceback (most recent call last):
  File "C:\Users\oleson\ctsm-repos\ctsm\doc\doc-builder\build_docs", line 14, in <module>
    build_docs.main()
  File "C:\Users\oleson\ctsm-repos\ctsm\doc\doc-builder\doc_builder\build_docs.py", line 190, in main
    run_build_command(build_command=build_command)
  File "C:\Users\oleson\ctsm-repos\ctsm\doc\doc-builder\doc_builder\build_docs.py", line 114, in run_build_command
    subprocess.check_call(build_command)
  File "C:\Users\oleson\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'run', '--name', 'build_docs_onvizvrt', '--volume', 'C:\\Users\\oleson:/home/user/mounted_home', '--workdir', '/home/user/mounted_home/ctsm-repos/ctsm/doc', '-t', '--rm', 'escomp/base', '/bin/bash', '-c', 'sudo mkdir -p C:\\Users && sudo ln -s /home/user/mounted_home C:\\Users\\oleson && make BUILDDIR=C:\\Users\\oleson\\ctsm-repos\\ctsm-docs\\versions\\master\\ -j 4 html']' returned non-zero exit status 2.

No idea what "Builder name 4" is.

**Comment by billsacks** [comment]
@olyson I'm very sorry that you have been running into all of these issues. To be honest, I was never certain that the Docker-based documentation build script would work correctly as it is currently written on Windows, and I think you have demonstrated that it does not.... I think I know the problem with your last error, but to fix it – and to fix some of the other problems you ran into – I think I need to do a bit of rework of the build_docs script. If you can wait a bit, I'll get back to you once I have made some changes; at that point, maybe we can have a zoom call to try it out together.

**Comment by olyson** [comment]
Sounds good, thanks.

**Comment by olyson** [comment]
I've added documentation in the troubleshooting chapter of the User's Guide for review per PR#1223
