### ISSUE TITLE
In WRF-CTSM coupling, diagnostic variables in  WRF ouputs should be updated to reflect values sent from CTSM 

### ISSUE THREAD

**Issue by negin513** [ESCOMP/CTSM#1217]
In the WRF output files (`wrfout*` files) a set of diagnostic variables should be updated to reflect values sent from CTSM for land points. 

This topic is also discussed in other issues (such as #917, #911, and #915). This issue is specifically for checking **WRF diagnostic variables** reflect CTSM values and the related discussions. 

`T2` and `Q2` are calculated using a subroutine call (``SFCDIAGS``) in `module_surface_driver.F` for some land surface models but not NOAHMP. Similar to NOAH-MP, as we [concluded](https://github.com/ESCOMP/CTSM/issues/915#issuecomment-673149347) in previous meetings since we are sending correct `T2` and `Q2`, we should be able to avoid calling ``SFCDIAGS``.  

Other fields that I've noticed needed to be updated are accumulated fluxes :
``ACHFX`` : Accumulated upward heat flux at the surface (J m-2)
``ACLHF`` :  Accumulated upward latent heat flux at the surface  (J m-2)
``ACGRDFLX`` : Accumulated ground heat flux (J m-2)

``SFCEVP``  : total surface evaporation 

``` FORTRAN
+           DO j=j_start(ij),j_end(ij)                                               
+           DO i=i_start(ij),i_end(ij)
+               SFCEVP(I,J)= SFCEVP(I,J) + QFX(I,J)*DTBL
+               IF(PRESENT(ACHFX))ACHFX(I,J)=ACHFX(I,J) + HFX(I,J)*DT
+               IF(PRESENT(ACLHF))ACLHF(I,J)=ACLHF(I,J) + LH(I,J)*DT
+               IF(PRESENT(ACGRDFLX))ACGRDFLX(I,J)=ACGRDFLX(I,J) + GRDFLX(I,J)*DT
+           ENDDO
+           ENDDO
```

I've added the code needed for the accumulated fields above to the  ``module_surface_driver.F`` for CTSM.

**Comment by billsacks** [comment]
Given lack of resources for WRF-CTSM, I am closing this as a wontfix.
