### ISSUE TITLE
Naming conflic in the CTSM-Wiki documentation? 

### ISSUE THREAD

**Issue by sunnivin** [ESCOMP/CTSM#1218]
In the wikipage for the CTSM development guide (https://github.com/ESCOMP/CTSM/wiki/Quick-start-to-CTSM-development-with-git) it is described how to create the branch MY_BRANCH from master. The command is given as: 

`git checkout -b MYBRANCH main`

I guess it is linked to the idea of renaming master to main (https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/), but as the default repository still is named master this is a bit confusing for new learners. If the purpose is to create a branch from the main/default starting place I think the command should have been:  

`git checkout -b MYBRANCH master`

Or is this done on purpose? 

People involved: @devarajun , @sunnivin

**Comment by billsacks** [comment]
Good point. @dlawrenncar it looks like you made this change (along with a number of other changes in the wiki changing 'master' to 'main'). Do you think we should revert this until we make the change from 'master' to 'main'? I'm hopeful we can do that within the next couple of months (according to the "by the end of the year" target stated by GitHub here https://github.com/github/renaming), so I'm not sure if you were maybe thinking that we'd just keep this as 'main' and live with some user confusion until we do the rename?

**Comment by dlawrenncar** [comment]
I guess I was thinking that we would live with the confusion.  Though at
the time, I thought the change to main was more imminent.

**Comment by billsacks** [comment]
Okay, I fixed this (I think) by reverting the wiki commit where this changed: https://github.com/ESCOMP/CTSM/wiki/Quick-start-to-CTSM-development-with-git/_compare/257b349ff7f1874c291400906aa942dce2cff1c9...443e84d46baf3d3f1ccdfe89caf62cc306c5d480
