### ISSUE TITLE
Add new dust emission scheme

### ISSUE THREAD

**Issue by L3atm** [ESCOMP/CTSM#1230]
We propose to add a new dust emission scheme improving the dust mobilization parameterizations in CESM2. We also propose to add a namelist entry and switches in the code, such that CESM2 users could turn on and off this new dust emission scheme easily. These will imply changes in the following files:

- clm/src/biogeochem/DUSTMod.F90

- cam/src/chemistry/modal_aero/dust_model.F90

- clm/src/main/clm_varctl.F90

- clm/src/main/controlMod.F90

- cam/bld/build-namelist

- cam/bld/namelist_files/namelist_definition.xml

- clm/bld/namelist_files/namelist_definition_clm4_5.xml

- clm/bld/namelist_files/namelist_definition_clm4_0.xml

- user_nl_cam

- user_nl_clm

**Brief science information:**
The physically-based new dust emission scheme produces a statistically significant improvement in the representation of dust emission compared to the default scheme used in the current CESM2. This new dust emission scheme also reduces the need to use an empirical source function in the dust cycle simulation to shift emissions toward the word's most erodible regions.

**Pseudocode for all file changes:**

- _clm/src/biogeochem/DUSTMod.F90_: implementing the new dust mobilization parameterization due to wind from the surface into the lowest atmospheric layer

- _cam/src/chemistry/modal_aero/dust_model.F90_: turning off the soil erodibility map used by the default old scheme

- _clm/src/main/clm_varctl.F90_: adding a switch to turn on and off the new dust emission scheme

- _clm/src/main/controlMod.F90_ plus _clm/bld/namelist_files/namelist_definition_clm4_5.xml_ and _namelist_definition_clm4_0.xml_ along with _cam/bld/build-namelist_: adding a flag to read the new namelist entry

- _user_nl_cam_ and _user_nl_clm_: setting the new namelist entry by the users to use the new scheme for simulation

**Long term goal:**
To add the suggested feature to the master branch of CESM2.

**Comment by wwieder** [comment]
@L3atm thanks for filing this issue and letting is know about this plan.  We look forward to hearing more about your work.  Out of curiosity, who are you & where do you work?  It's helpful on our end to  be able to talk about the people who are making the science of CTSM happen.

**Comment by L3atm** [comment]
@wwieder Hi! Nice to meet you here. This is Longlei Li, a postdoc working with Natalie Mahowald at Cornell. We look forward to working with you on this too.

**Comment by wwieder** [comment]
awesome. Thanks Longlei. Good to meet you too.  How mature is this work? Do
you see yourself submitting a pull request soon, or is it just getting
started?
Regardless, keep us up to date on your progress.  Best, Will

**Comment by L3atm** [comment]
Hi Will!    
Thanks for the question. I think I will submit a pull request soon, and will keep you up to date!       
Best regards, Longlei

**Comment by wwieder** [comment]
Hello, any updates on this issue? Is it still an active project?

**Comment by lkemmons** [comment]
It sounds like the dust code needs to be moved to current CTSM code.  Who
will be able to do that?
Francis will be putting the MAM5 code into current CAM code soon.
Would it be helpful to meet to discuss the next steps?

**Comment by ekluzek** [comment]
@lkemmons yes it sounds like we need to get the group together to talk about how to move forward with this. @wwieder should be part of the discussion so he can talk about who can work on it here in CESM. Can you propose a meeting?

**Comment by wwieder** [comment]
From our call today: 

- @ekluzek suggested it would be best to start with a CTSM PR so there's a tag CAM can point to.
- @L3atm has all these code mods made and will point to the branch he's working on.
- @fvitt will work to bring in the CAM, but these changes are relatively modest
- @fvitt noted that since this will be answer changing for CAM it will need to be validated by AMP
- @lkemmons suggested that tuning for climate runs take place after additional CAM-CHEM modifications come into CESM.  

We decided NOT to maintain backwards compatibility with the old dust scheme, which will be available in CESM2.1 and this new scheme will replace the current version.

**Comment by lkemmons** [comment]
The CAM climate tuning can be done with the new dust scheme and MAM5 (5-mode Modal Aerosol Model), which will have a different coarse mode size for dust than MAM4.

**Comment by ekluzek** [comment]
I'm closing this because we decided to go with #1604 which is based on this work, but adds some additional improvements to it. We also decided we didn't need to support this solution in addition to it.
