### ISSUE TITLE
ndep forcing incorrect when receiving ndep from CAM (starting with ctsm5.1.dev002)

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1233]
### Brief summary of bug

There is a bug in ndep forcing (`forc_ndep_grc`) when receiving ndep from CAM (ndep_from_cpl true). This first appears in ctsm5.1.dev002.

### General bug information

**CTSM version you are using:** ctsm5.1.dev002 and later

**Does this bug cause significantly incorrect results in the model's science?** Yes

**Configurations affected:** Any configurations that get ndep from coupler. My guess is that we missed this bug because we don't have any such configurations in our test suite, maybe because this isn't possible in I compsets?

### Details of bug

This showed up in CESM prealpha testing as a failure in `ERP_Ld3.f09_f09_mg17.FCfireHIST.cheyenne_intel.cam-outfrq1d`: the base and restart runs differed.

@fischer-ncar tracked this down to ctsm5.1.dev002, and I have tracked it down to a problem when a loop was split: a local index variable was not set in the second loop. We need this diff:

```diff
diff --git a/src/cpl/mct/lnd_import_export.F90 b/src/cpl/mct/lnd_import_export.F90
index 459faead..afdf575a 100644
--- a/src/cpl/mct/lnd_import_export.F90
+++ b/src/cpl/mct/lnd_import_export.F90
@@ -169,6 +169,7 @@ contains
     ! Note that forc_pbot is in Pa
 
     do g = begg,endg
+       i = 1 + (g - begg)
 
        forc_pbot = atm2lnd_inst%forc_pbot_not_downscaled_grc(g)
```

and maybe similar in the other caps.

@slevisconsulting FYI. I'll fix this.

**Comment by ekluzek** [comment]
@billsacks thanks for catching this and figuring it out. Yes, this is a situation we can't test for with an I compset, we need at least an F compset to do it. If datm sent ndep rather than CTSM reading it in, the two situations would be closer and we would catch such problems.

We do have an issue for this, but no time to do it...

https://github.com/ESMCI/cime/issues/3549

It would also be better in that we would know that ndep sent to both ocn and lnd would be identical.

**Comment by billsacks** [comment]
Thanks @ekluzek . As you were writing your comment, I was in the process of reading that issue and opening a corresponding issue in CDEPS: https://github.com/ESCOMP/CDEPS/issues/36.

**Comment by billsacks** [comment]
This is only an issue in the mct cap: the nuopc cap doesn't have a loop like this, and the lilac cap doesn't currently handle ndep from atm.
