### ISSUE TITLE
For nuopc cap: add a namelist flag, force_send_to_atm

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1237]
@mvertens has implemented some code in the nuopc cap that avoids sending lnd -> atm fields to the mediator if the atmosphere isn't prognostic. This is helpful for performance, but is problematic for testing, where we want to be able to confirm that we haven't changed any lnd -> atm fields despite running our tests with datm.

I proposed, and @mvertens agreed, that we should handle this by having a namelist flag like `force_send_to_atm`. Our default testmod (as well as other testmods that don't inherit from default) can set this to true, so that, for testing, we'll send lnd -> atm fields even if running with datm, so that they will be output to the cpl history files. However, at least once we switch to mainly running our tests with nuopc, we should have at least one test that *does not* set this, so that we have a test of the standard production configuration, to make sure that works. (As a general rule, we should have at least one test that doesn't include test-specific options, such as those included in the `default` testmod.)

For now, I'm keeping @mvertens 's code in place, but I'm putting in a kludge to act as if such a namelist flag is always present and set to true.

**Comment by billsacks** [comment]
At a glance, there may be an issue with where the namelist is read relative to where it is needed for this. So we may either need to move CTSM's main namelist read relative to the `advertise_fields` call, or we need to add a small namelist read that just reads this one namelist item earlier.

**Comment by ekluzek** [comment]
Right now this is in the code, but it's hardcoded to true. So this just needs to be added to the namelist.
