### ISSUE TITLE
Error in HumanIndexMod (QSat_2 subroutine)

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#1250]
### Brief summary of bug

Calculation of derivative in QSat_2 is missing a term (reported by J. Buzan).  This only affects diagnostic quantities that use the advanced wet bulb temperature calculation (when calc_human_stress_indices = 'ALL').   The corrected web bulb temperature and associated indices differ by +-0.00001 K in a 1 month simulation.

### General bug information

**CTSM version you are using:** ctsm5.1.dev021

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** Any that use calc_human_stress_indices = 'ALL' (not the default in CLM/CTSM).

### Details of bug

This line in QSat_2:

fdT = -lambd_a*(1._r8/T_k + vkp*de_mbdT/pminuse + gdT)

Should be:

fdT = -lambd_a*(1._r8/T_k + vkp*de_mbdT/pminuse + gdT) * foftk

### Important details of your setup / configuration so we can reproduce the bug

Corrected in my branch:

https://github.com/olyson/ctsm/tree/fixhumanindexmod

**Comment by billsacks** [comment]
Not really bfb: will change answers in just a few diagnostic fields.

**Comment by ekluzek** [comment]
OK, this should affect the test: 

ERP_P36x2_D_Ld3" grid="f10_f10_musgs" compset="I1850Clm50BgcCrop" testmods="clm/extra_outputs
