### ISSUE TITLE
New urban raw dataset currently inconsistent with CTSM code and urban temperature streams file

### ISSUE THREAD

**Issue by slevisconsulting** [ESCOMP/CTSM#1252]
### Brief summary of bug

The CTSM currently crashes when using a newly generated surface dataset. Mksurfdat points to a new urban raw dataset that puts nlevurb = 10 in surface datasets, while the CTSM hardwires nlevurb = 5. See recommended workaround below.

### General bug information

**CTSM version you are using:** ctsm5.1.dev021

**Does this bug cause significantly incorrect results in the model's science?** Model crashes

**Configurations affected:** All

### Details of bug

Relates directly to #1157 #591 
Relates tangentially to #1195 #674 

**Recommended workaround:** Manually make mksurfdat point to the old raw dataset `mksrf_furban = '/glade/p/cesm/cseg/inputdata/lnd/clm2/rawdata/mksrf_urban_0.05x0.05_simyr2000.c120621.nc'`.

**Not recommended:** Setting nlevurb = 10 in the CTSM because the urban temperature streams file will still be inconsistent with the new mksrf_furban.

**Comment by ekluzek** [comment]
@slevisconsulting this is a known issue. Although I should have made it clearer for people. Current ctsm5.1 development is including updates that will lead to new surface datasets which is what ctsm5.2 development will be.

As such if you need to make new datasets for ctsm5.1 work, you should use: ctsm1.0.dev113.

**Comment by billsacks** [comment]
@ekluzek I feel like we have always had the (unwritten) rule that, for any given model tag, the surface datasets created in that tag should be compatible with the code in that tag. That was a very helpful rule and I think we should maintain that.

That said, I don't understand all the subtleties here. If there is some problem with maintaining compatibility between the code & mksurfdata_map, then we should discuss that further.

**Comment by slevisconsulting** [comment]
I do not need to weigh in on the above comments. Regarding any new WRF/LILAC datasets, I am comfortable with either @ekluzek 's suggestion to use ctsm1.0.dev113 or @olyson 's suggestion to point to the old mksrf_furban.
