### ISSUE TITLE
h2osoi_ice can go significantly negative

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1253]
### Brief summary of bug

In some situations (I haven't determined exactly when), it's possible for h2osoi_ice to go significantly negative, triggering an abort due to an error check: "In UpdateState_TopLayerFluxes, h2osoi_ice has gone significantly negative". This is due to some code changes I made in ctsm1.0.dev060.

### General bug information

**CTSM version you are using:** reproduced using release-cesm2.2.01, but I'm guessing this issue exists on master, too.

**Does this bug cause significantly incorrect results in the model's science?** No, but can cause model to crash in some circumstances

**Configurations affected:** Observed with `--compset 1850_DATM%GSWP3v1_CLM45%SP_SICE_SOCN_MOSART_SGLC_SWAV --res f09_g17` on cheyenne, but it seems like this might appear in other situations, too.

### Details of bug

This was reported in https://bb.cgd.ucar.edu/cesm/threads/negative-h2osoi_ice-about-300-years-into-a-ctsm-standalone-spin-up.5183/#post-38818.

I have added extra write statements and determined the following (note that this is for the single point showing the error in this case; these statements may not always be true)
- The error occurs on a column with a single layer snow pack
- This is on the natural veg landunit

Digging into the code, it looks like the problem is that `topsoil_evap_tot` is based on `qflx_evap_soi`, but `qflx_ev_snow` is the important quantity for fluxes. In SoilFluxes, there is some flux limiting done based on `topsoil_evap_tot` (thus on `qflx_evap_soi`), but in this case,`qflx_ev_snow` is greater than `qflx_evap_soi`.

Off-hand, I see two possible solutions:

1. Change the flux limiting code in SoilFluxes so that it separately considers `qflx_ev_snow` and `qflx_ev_soil`. I'm not sure what that should look like, exactly. My sense is that this would be keeping more in the spirit of the original limiting code: my sense is that the limiting code in SoilFluxes may not have been working quite right ever since the separation of the evaporation terms into these different components. I don't know exactly what would be needed for this. I'm also not sure what to do about `qflx_ev_h2osfc`: I tried seeing how this is limited, but I haven't been able to follow this well enough.

2. Revert the changes in ctsm1.0.dev060: Return to having code that loops through layers until sufficient supply is found to meet the evaporation / sublimation flux demand. The reason I got rid of this in the first place was because it would be tricky to accommodate tracers with this code, but with some effort I think it could be rewritten similarly to the irrigation code.

### Important details of your setup / configuration so we can reproduce the bug

```
./create_newcase --case $scratch/negative_h2osoi_ice_0111a --compset 1850_DATM%GSWP3v1_CLM45%SP_SICE_SOCN_MOSART_SGLC_SWAV --res f09_g17 --run-unsupported

./xmlchange STOP_OPTION=nyears,STOP_N=20
```

From release-cesm2.2.01 on cheyenne. This dies a couple of months into the run.

### Important output or errors that show the problem

```
1156: ERROR: In UpdateState_TopLayerFluxes, h2osoi_ice has gone significantly negativ
1156: e
1156: Bulk/tracer name = bulk
1156: c, lev_top(c) =        62140           0
1156: h2osoi_ice_top_orig =   1.822218438931472E-002
1156: h2osoi_ice          =  -3.011219323010204E-003
1156: frac_sno_eff        =   0.307512444417167
1156: qflx_soliddew_to_top_layer*dtime =   0.000000000000000E+000
1156: qflx_solidevap_from_top_layer*dtime =   6.904892500389338E-002
1156: ENDRUN:
1156: ERROR:
1156: In UpdateState_TopLayerFluxes, h2osoi_ice has gone significantly negative
```

**Comment by billsacks** [comment]
I tried the same case as above from ctsm master; it failed similarly:

```
1156: ERROR: In UpdateState_TopLayerFluxes, h2osoi_ice has gone significantly negativ
1156: e
1156: Bulk/tracer name = bulk
1156: c, lev_top(c) =        62149           0
1156: h2osoi_ice_top_orig =   1.084776485752420E-002
1156: h2osoi_ice          =  -4.780265947447054E-003
1156: frac_sno_eff        =   0.313925015362895
1156: qflx_soliddew_to_top_layer*dtime =   0.000000000000000E+000
1156: qflx_solidevap_from_top_layer*dtime =   4.978268707546402E-002
```

Note that the column index and exact values differ, but the general failure is the same. This fails in mid-March.

**Comment by olyson** [comment]
I'm going to re-open this as we've had a couple of instances of this error triggering in coupled simulations.  See here:

https://bb.cgd.ucar.edu/cesm/threads/error-in-updatestate_toplayerfluxes-h2osoi_ice-has-gone-significantly-negative.7634/#post-46072

and more recently:

https://github.com/NCAR/amwg_dev/issues/227

Thus far, these errors can be avoided by changing custom_rel_epsilon to 1.e-11_r8 in this block of code:

call truncate_small_values_one_lev( &
     num_f = num_snowc, &
     filter_f = filter_snowc, &
     lb = bounds%begc, &
     ub = bounds%endc, &
     lev_lb = -nlevsno+1, &
     lev = lev_top(bounds%begc:bounds%endc), &
     data_baseline = h2osoi_ice_top_orig(bounds%begc:bounds%endc), &
     data = h2osoi_ice(bounds%begc:bounds%endc, :), &
     custom_rel_epsilon = 1.e-12_r8)

But we need to discuss whether this is really what we want to do to fix this.

**Comment by swensosc** [comment]
Not sure if the surface type is relevant, but in amwg 227 it looks like it was urban pervious road.  Do you know if rich's was the same?  I couldn't tell what surface type was triggering the error for rich.

**Comment by swensosc** [comment]
I also notice that the absolute error is 1e-18 in both cases.

**Comment by olyson** [comment]
I don't know/remember the surface type that Rich's error was for.
It looks like the suggested change for custom_rel_epsilon is working for amwg 227 for now, as the simulation has gone past the time of the error.
Yes, the error is very small in both cases.  In my own case that I alluded to, the error was the same magnitude (1e-18).  I'm not sure I can find that case to see what the surface type was.

**Comment by olyson** [comment]
I did find my own case and the error also occurred for pervious road:

563: ERROR: In UpdateState_TopLayerFluxes, h2osoi_ice has gone significantly negativ
563: e
563: Bulk/tracer name = bulk
563: c, lev_top(c) =           96           0
563: h2osoi_ice_top_orig =   1.999323742483267E-006
563: h2osoi_ice          =  -2.100641709190665E-018
563: frac_sno_eff        =    1.00000000000000
563: qflx_soliddew_to_top_layer*dtime =   0.000000000000000E+000
563: qflx_solidevap_from_top_layer*dtime =   1.999323742485367E-006
563:iam = 527: local  column   index = 96
563:iam = 527: global column   index = 158792
563:iam = 527: global landunit index = 55159
563:iam = 527: global gridcell index = 13128
563:iam = 527: gridcell longitude    =   96.2500000
563:iam = 527: gridcell latitude     =   38.1675393
563:iam = 527: column   type         = 75
563:iam = 527: landunit type         = 8
563: ENDRUN:
563: ERROR:
563: In UpdateState_TopLayerFluxes, h2osoi_ice has gone significantly negative

That should be easier to troubleshoot than a coupled case.

**Comment by swensosc** [comment]
The limit is calculated like this:
evaporation_limit = h2osoi_ice(c,j)/(dtime*(1._r8 - frac_h2osfc(c)))
frac_h2osfc should always be zero for urban, but is it possible the denominator is introducing a roundoff error?

**Comment by olyson** [comment]
Since lev_top = 0, doesn't this mean that there is a snow layer?  The statement you are referring to is within a j=1 if statement, so it doesn't seem like it would be called?

**Comment by billsacks** [comment]
Just catching up from my vacation.... Based on the magnitude of the error here, I think the problem is actually more similar to the one in #988 (which is where I changed the rel_epsilon for this truncation to 1e-12 instead of 1e-13) rather than this issue (where there was a significant bug that caused much larger errors). Not a big deal to be discussing it here, but I just wanted to point to that earlier issue, in part to reference my earlier statement:

> The value in this case just slightly exceeds the 1e-13 threshold. Changing this to 1e-12 seems safe here, and it could possibly even go a bit larger.

which supports changing this to 1e-11.

That said, @olyson and @swensosc you seem to be looking into the possibility that there is a real issue here that we may not want to sweep under the rug, so I'll defer to your sense at this point as to whether changing this to 1e-11 is the way to go or if this warrants more investigation.

**Comment by olyson** [comment]
Ah, yes, I forgot about #988 .  In that case I'm fine with changing this to 1.e-11.  I've looked through the code and don't see anything obviously wrong.

**Comment by billsacks** [comment]
Because the recent issue isn't too closely related to the original issue, I have opened a new issue for this (#1979 ) and will submit a fix shortly.
