### ISSUE TITLE
Leaf biomass is not updated for BGC phenology in ctsm5.1.dev021

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1268]
The setting of leafbiomass (needed for clm5_1 physics with biomass heat storage on) is in a "if woody" statement so isn't set for grasses and should be. This just means the statement needs to be moved higher up outside of that if statement and only the stem_biomass part of the calculation should be within an if woody statement.

**Comment by ekluzek** [comment]
The new statement I got from @olyson looks like this. It's moved outside of the if woody block and on it's own. Then it has it's own if woody section for stem_biomass. Other than that it's identical to before. The main effect is to set leaf biomass for grasses.

``` fortran
+             ! calculate vegetation physiological parameters used in biomass heat storage
+             if (use_biomass_heat_storage) then
+                ! Assumes fbw (fraction of biomass that is water) is the same for leaves and stems
+                leaf_biomass(p) = max(0.0025_r8,leafc(p)) &
+                     * c_to_b * 1.e-3_r8 / (1._r8 - fbw(ivt(p)))
+ 
+                if (woody(ivt(p)) == 1._r8) then
+                   if (spinup_state == 2) then
+                      stem_biomass(p) = (10._r8*deadstemc(p) + livestemc(p)) &
+                           * c_to_b * 1.e-3_r8 / (1._r8 - fbw(ivt(p)))
+                   else
+                       stem_biomass(p) = (1._r8*deadstemc(p) + livestemc(p)) &
+                          * c_to_b * 1.e-3_r8 / (1._r8 - fbw(ivt(p)))  
+                   end if
+                else
+                   stem_biomass(p) = 0_r8
+                end if
+             else
+                leaf_biomass(p) = 0_r8
+                stem_biomass(p) = 0_r8
+             end if
```

**Comment by billsacks** [comment]
Minor nit: 0_r8 should be 0._r8 (note the decimal) – otherwise it is an integer with some ambiguous kind.
