### ISSUE TITLE
A clm5_0 fire term is hardcoded for AD spinup rather than set to 1 when AD spinup is off

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1279]
### Brief summary of bug

Root carbon term in CNFireLi2016Mod.F90 is hardcoded with a multiple of 10 (used in AD spinup) for deadcroot, it should only be done so during AD spinup. When AD spinup is off the multiple should not be done (or use a multiple of 1.0_r8). 

### General bug information

**CTSM version you are using:**branch_tags/PPE.n02_ctsm5.1.dev021

**Does this bug cause significantly incorrect results in the model's science?** Yes

The code in question is this...

```
               end if
            end if
            rootc_col(c) = rootc_col(c) + (frootc(p) + frootc_storage(p) + &
                    frootc_xfer(p) + deadcrootc(p) * 10.0_r8 +       &
                    deadcrootc_storage(p) + deadcrootc_xfer(p) +    &
                    livecrootc(p)+livecrootc_storage(p) +           &
                    livecrootc_xfer(p))*patch%wtcol(p)
```

The hardcoded 10.0_r8 should be 10 for AD spinup (spinup_state==2), but 1.0 otherwise.

These factors of 10.0_r8 in every other part of the code were added on only for spinup_state==2 and go with settings of dead?rootc or dead?stem (? meaning both Carbon (c) and Nitrogen (n)).

@ckoven can you verify that I'm correct about this problem? 

We also need to estimate if this is a significant issue for simulations or not. It's impact is on fuelc in the following part of the code...

```
           fuelc(c) = totlitc(c)+totvegc(c)-rootc_col(c)-fuelc_crop(c)*cropf_col(c)
           if (spinup_state == 2) then
              fuelc(c) = fuelc(c) + ((spinup_factor_deadwood - 1._r8)*deadstemc_col(c))
              do j = 1, nlevdecomp
                 fuelc(c) = fuelc(c)+decomp_cpools_vr(c,j,i_cwd) * dzsoi_decomp(j) * spinup_factor(i_cwd) &
                            * get_spinup_latitude_term(grc%latdeg(col%gridcell(c)))
              end do
           else
              do j = 1, nlevdecomp
                 fuelc(c) = fuelc(c)+decomp_cpools_vr(c,j,i_cwd) * dzsoi_decomp(j)
              end do
           end if
```

So fuelc is adjusted depending on the spinup state. And its use later on does have max thresholds for its use. So it's not clear to me how much of an impact this will have. But, it does mean fuelc will be too large for non-spinup cases.

**Comment by ekluzek** [comment]
This is actually fixed in ctsm5.1.dev023, but we should assess how much the impact is on control simulations.

**Comment by ckoven** [comment]
Hi @ekluzek, my knowledge of the CNFireLi2016Mod.F90 code is limited, but this does seem like a mistake.  Though I also wouldn't really think of coarse root carbon as being a very effective fuel source in any case. Will be interesting to see how this changes simulations.

**Comment by ekluzek** [comment]
OK, it turns out this is only a problem on the PPE branch. It comes in with branch_tags/PPE.n02_ctsm5.1.dev021. I'm fixing it in the n05 branch tag.

**Comment by olyson** [comment]
It's a problem on master (ctsm5.1.dev021 and ctsm5.1.dev022) as well.

**Comment by ekluzek** [comment]
> It's a problem on master (ctsm5.1.dev021 and ctsm5.1.dev022) as well.

@olyson I rechecked this and don't see it there. Issue #1261 is the issue for those versions which is slightly different than this, though related. In there the spinup_factor_deadwood should be 10 for AD spinup, but only is for restarts. The value should be correctly 1.0 for non-spinup cases. Can you check again to make sure I'm not missing it? And if so let's go over it to make sure we are on the same page.

**Comment by ekluzek** [comment]
Fixed in branch_tags/PPE.n05_ctsm5.1.dev021

**Comment by olyson** [comment]
Ah yes, I see what you mean, sorry.  I saw the single statement for rootc_col, but didn't note the spinup_factor_deadwood variable.
