### ISSUE TITLE
Inconsistent logic for VIC initialization can cause crash in debug mode

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1287]
### Brief summary of bug

@mvertens had this test crash: `ERP_D_Ld5_Vnuopc.f09_g17.I2000Clm50Vic.cheyenne_intel.clm-vrtlay`. She found that there is inconsistent logic in VIC initialization; this happens to show up in nuopc and not mct, but it is not specific to nuopc.

### General bug information

**CTSM version you are using:** master? (I'm not sure what version @mvertens was using, but it looks like the problem exists on master)

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** All VIC configurations

### Details of bug

The problem appears in SoilHydrologyInitTimeConst. As @mvertens found, some of the arrays that are initialized to spval from 1:nlayer here:

https://github.com/ESCOMP/CTSM/blob/d4dd6c236f4150cdbd68fea86ac8baf8ecfcf5dc/src/biogeophys/SoilHydrologyInitTimeConstMod.F90#L131-L146

are later accessed in deeper layers in initSoilParVIC (e.g., sandcol, claycol). This results in accessing some uninitialized memory. @mvertens suggested a fix of changing that initialization loop to go down to nlevsoi rather than just nlayer. I think that would solve the issue. However, I'd suggest a different fix: I think the real problem here is that the conditionals used in this block of code:

https://github.com/ESCOMP/CTSM/blob/d4dd6c236f4150cdbd68fea86ac8baf8ecfcf5dc/src/biogeophys/SoilHydrologyInitTimeConstMod.F90#L152-L171

is inconsistent with the conditionals used in this block of code:

https://github.com/ESCOMP/CTSM/blob/d4dd6c236f4150cdbd68fea86ac8baf8ecfcf5dc/src/biogeophys/SoilHydrologyInitTimeConstMod.F90#L173-L193

In particular, it looks like the second block operates over some landunits not included in the first block (specifically, wetland and glacier). My guess is that this only is supposed to operate over the set of points in the first block, but I'm not sure about that. If that's true, then a fix could be to merge these two blocks into one, by moving this code:

https://github.com/ESCOMP/CTSM/blob/d4dd6c236f4150cdbd68fea86ac8baf8ecfcf5dc/src/biogeophys/SoilHydrologyInitTimeConstMod.F90#L186-L191

up to here:

https://github.com/ESCOMP/CTSM/blob/d4dd6c236f4150cdbd68fea86ac8baf8ecfcf5dc/src/biogeophys/SoilHydrologyInitTimeConstMod.F90#L168

(Note that the block of code I am suggesting moving up is currently duplicated: once for urban and once for non-urban; I see no reason to have this duplication, since the two appear to be doing the same thing.)

@swensosc I'm thinking you are at least as familiar with this as anyone. Can you please confirm whether my suggestion makes sense? In particular, is it right that these VIC variables only need to be set over soil & road landunits (not wetlands & glaciers)?

**Comment by swensosc** [comment]
I wasn't involved with the vic code, and I have never used it.  But I think that you are correct that it should only be used on vegetated landunits and pervious road columns.

**Comment by billsacks** [comment]
I just spent a few minutes looking through the code, and I'm also pretty sure that the variables set in initSoilParVIC are only used in the hydrology filter, in agreement with @swensosc 's feeling. So I think my proposed solution should work.
