### ISSUE TITLE
Update FATES on CTSM main-dev

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1293]
FATES needs to be updated to sci.1.43.3_api.14.2.0. FATES in CTSM is currently one tag behind FATES main-dev.

**Comment by rgknox** [comment]
@ekluzek should we bring this up at the software meeting?  ie, when/how-often/quickly to update the CTSM pointer to FATES, following non-api changes to fates

**Comment by ekluzek** [comment]
@rgknox yes we should. I added the "next" label to this for that reason. I think it will be good to have an issue like this for FATES in CTSM whenever CTSM main-dev is behind FATES. That makes it more visible. I think the goal right now is to keep CTSM main-dev as close to the latest FATES version as we can. But, having an issue like this can document exactly where we are at in that respect.
