### ISSUE TITLE
Make a checklist of issues to check for when running a simulation.

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1296]
We need to create a README file that gives some suggestions on things to check for your simulation to make sure it's correct.

@olyson

Here's things I can think of right now:

-  Make sure CLM_ env settings are correct (./xmlquery -p CLM)
- Make sure you are using the correct CLM_PHYSICS_VERSION
- Make sure you are running the appropriate overall CLM vegetation model. The "-bgc" option of either Satellite Phenology (sp), or Full BioGeoChemistry (bgc), or FATES (fates) (./xmlquery CLM_BLDNML_OPTS)
-  Also if you are running the bgc model, check to see if you should be running the prognostic crop model (option -crop in CLM_BLDNML_OPTS)
-  Make sure the LND_TUNING_MODE is correct (./xmlquery LND_TUNING_MODE)
-  For an "I compset" make sure you are running over the right forcing years (usually ./xmlqueary -p ATM_CLMNCEP_YR)
- First and align year for streams should be the start year of a historical simulation (grep stream_year_first; grep model_year_align)
- Last year for streams should be the last year you are going to run to (or beyond it)  (grep stream_year_last)
-  Make sure you are starting from appropriate spunup initial conditions (check finidat or nrevsn)

Should we also give instructions on how to do a spinup sequence? Maybe that should wait until CN-Matrix comes to CTSM main-dev.

**Comment by olyson** [comment]
I find it useful to run a short test simulation first (e.g., a month or two) and then examine the lnd.log (and atm.log if an I-case) to verify the correct model configuration.  There is a lot of good information in the logs that one can use to make sure the right datasets and time slices are being read in from streams files and other input datasets.  There is also additional information provided about certain namelist options, e.g., initialization, spinup, etc.
I think we'll need to do some experimentation with CN-Matrix on CTSM main-dev first before recommending a spinup procedure.

**Comment by wwieder** [comment]
thanks, Keith.
