### ISSUE TITLE
Soil vertical interpolation in init_interp gives incorrect results when layer thicknesses vary

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1298]
### Brief summary of bug

When interpolating from one soil layer structure to another using init_interp, extensive properties (e.g., water mass per layer) (https://www.thoughtco.com/intensive-vs-extensive-properties-604133) are not handled properly. They should be scaled by layer thickness in doing the interpolation. The current code can result in much too dry or much too wet soils, along with other issues.

@slevisconsulting ran into this issue and figured out the problem and solution – thank you, Sam!!!

### General bug information

**CTSM version you are using:** master, but this applies to all versions since vertical interpolation was introduced a few years ago.

**Does this bug cause significantly incorrect results in the model's science?** Yes

**Configurations affected:** Any configuration where the soil layer structure in the current run differs from that in the finidat file.

### Details of bug

@slevisconsulting and I discussed this yesterday and came up with the following path forward (some of the details here are ones we discussed, others are ones I'm filling in myself):

- [x] If not already done (which I think it is not), `dzsoi` needs to be added to the restart file.
- [x] The constructor for `interp_multilevel_interp_type` then needs to also take in these `dzsoi` values and store them, both for the source and destination grids.
- [x] Some consideration needs to then be given to backwards compatibility: how will we handle source files that don't have `dzsoi`?
- [x] For each 2-d field on the restart file, we should add metadata to the restart file saying whether this field needs to be scaled by layer thickness in doing the interpolation.
  - Note: Actually, this isn't needed for all 2-d fields, but is needed for all of them that do an actual vertical interpolation from source to dest. Currently, I believe this is done for fields that are dimensioned by levgrnd or levmaxurbgrnd. However, this should be implemented in a way that an obvious error message is generated if you don't add this new argument explicitly for some field that needs it – if not at compile time, then at least while attempting to do the interpolation.
- [x] In `init_interp`, we should read this new piece of metadata for each 2-d field and pass it to the call to `call multilevel_interpolator%interp_multilevel`.
- [x] The implementation of `interp_onelevel` in `interp_multilevel_interp_type` then needs to examine this argument and do or not do scaling by layer thicknesses as needed. I think that other classes will currently ignore this metadata, though we may want to add error checking ensuring that fields haven't asked for scaling by layer if we can't do it.
- [x] We should have unit tests for the scaled interpolation, as well as maintaining some unit tests that cover the unscaled case: I view these unit tests of the interpolation code as very important because many situations are not tested thoroughly via our system tests.

**Comment by billsacks** [comment]
Regarding backwards compatibility: probably just throw up an error message if you are trying to change soil layer structure and have a source file without dzsoi (but handle old initial conditions files if you're not changing soil layer structure).

**Comment by slevisconsulting** [comment]
Confirmed dzsoi not in restart.
