### ISSUE TITLE
Update Anomaly forcing data and contrib script

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1300]
@swensosc has updates to the ssp_anomaly_forcing_smooth in tools/contrib that also processes winds among other changes. The current script was used to create the data under $DIN_LOC_ROOT/tm/datm7/anomaly_forcing/CMIP6-SSP*/ directories. Also the simulations pointed to when that data was created has been superseded by new simulations because the emissions were wrong in the first set.

@danicalombardozzi

**Comment by ekluzek** [comment]
Notes on the simulation difference is here:

# original runs had incorrect emissions
#The SSP Tier1 simulations are on casper (not cheyenne):

basedir = '/glade/campaign/collections/cmip/CMIP6/timeseries-cmip6/'

'''
The corrected SSP simulations:

    b.e21.BSSP126cmip6.f09_g17.CMIP6-SSP1-2.6.101
    b.e21.BSSP126cmip6.f09_g17.CMIP6-SSP1-2.6.102 (MOAR)
    b.e21.BSSP126cmip6.f09_g17.CMIP6-SSP1-2.6.103

    b.e21.BSSP245cmip6.f09_g17.CMIP6-SSP2-4.5.101
    b.e21.BSSP245cmip6.f09_g17.CMIP6-SSP2-4.5.102 (MOAR)
    b.e21.BSSP245cmip6.f09_g17.CMIP6-SSP2-4.5.103

    b.e21.BSSP370cmip6.f09_g17.CMIP6-SSP3-7.0.101
    b.e21.BSSP370cmip6.f09_g17.CMIP6-SSP3-7.0.102 (MOAR)
    b.e21.BSSP370cmip6.f09_g17.CMIP6-SSP3-7.0.103

    b.e21.BSSP585cmip6.f09_g17.CMIP6-SSP5-8.5.101
    b.e21.BSSP585cmip6.f09_g17.CMIP6-SSP5-8.5.102 (MOAR)
    b.e21.BSSP585cmip6.f09_g17.CMIP6-SSP5-8.5.103

**Comment by ekluzek** [comment]
The new script is here:  /glade/u/home/swensosc/research/clm/scripts/AnomalyForcing/SSP_anomaly_forcing_corrected.py. It also processes WIND, and handles SNOW differently, not with the other variables, but as a special case of RAIN.

**Comment by olyson** [comment]
I have a set of anomaly forcing here from Sean where the history attribute indicates that they are based on ensemble 103 of the SSPs:

/glade/p/cgd/tss/people/oleson/anomaly_forcing

I had run a simulation using one of these (SSP370) for an urban project:

/glade/work/oleson/release-clm5.0.30/cime/scripts/clm50_r-clm5.0.30_1deg_GSWP3V1_iso_SSP3-7_AnomalyF2

**Comment by wwieder** [comment]
maybe we can run a clean set of anomaly forced runs for each SSP with this
new set of CTSM5.1 simulations we're doing?
This would be low priority, after coupled CTSM5.1 and even Fcase w/ FATES

**Comment by wwieder** [comment]
Two more followup questions:

1. Can we work on the documentation here too?  Currently I'm looking at [these instructions from the users_guide](https://github.com/ESCOMP/CTSM/blob/cd26076b7effe0986b3372637e8350d112190a28/doc/source/users_guide/running-special-cases/Running-with-anomaly-forcing.rst), but would have a hard time creating a specific case with anomaly forced runs based on this information.    Specifically:
  - How do users create the case they're interested in running?  
  - Are there other xml or namelist changes that need to be made?  
  - Can we provide a list of these changes as an example?

2. Based on the discussion above, it  seems like the directories below should not be used, or are these the corrected forcings?  /glade/p/cesmdata/cseg/inputdata/atm/datm7/anomaly_forcing/CMIP6-*

**Comment by wwieder** [comment]
Here's a followup based on my comments above:
- [ ] make sure we have updated forcing data in the right place (I think these should be  here `/glade/p/cesmdata/cseg/inputdata/atm/datm7/anomaly_forcing/CMIP6-*`)
- [ ] Add the right domain files to this path
- [ ] Can the default paths created by `user_nl_clm` with `anomaly_forcing = 'xxx'` reflect the changes above for a CESM2 simulation

- [ ] Should we do all this for the 2300 extension, 3 of these have been done with CESM2-WACCM simulations? @dlawrence

**Comment by wwieder** [comment]
@swensosc and @olyson can you confirm what anomaly and domain files should be put here? `/glade/p/cesmdata/cseg/inputdata/atm/datm7/anomaly_forcing/CMIP6-*`

Talking with @dlawrenncar I think we'd like to have CESM2 anomaly forcings that represent the ensemble mean for each of the SSP's.  Was this done in the most recent (corrected) files?  

When this is ready, does @ekluzek post these files in the `cesmdata` directory?

**Comment by wwieder** [comment]
I'm assigning @negin513 to this too, since @swensosc asked for her help bringing the python scripts that generate the anomaly forcing into the ctsm python toolbox.

**Comment by wwieder** [comment]
sounds like @ekluzek will replace the current anomaly forcing in `inputdata` with the updated datasets that @olyson has in his personal directory.  Keith, is this path still accurate  `/glade/p/cgd/tss/people/oleson/anomaly_forcing`, files created in 2020 or 2021?

**Comment by olyson** [comment]
Yes, that is the correct path.

**Comment by ekluzek** [comment]
I'm working on updating the ssp_anomaly forcing script with the new version that @swensosc developed. A complex thing is that they were developed independent of each other and outside of git, and there are important parts inside of the CTSM version as well as in the new version. So I have to merge the two by hand. It's short enough that I can go through it, but it's made more difficult by all being done outside of version control. I look forward to making this a standard supported tool, which will make working with it easier and faster.
