### ISSUE TITLE
Answer changes by PE layout for some longish BGCCROP simulations

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#131]
**Erik Kluzek < erik > - 2016-02-19 09:14:14 -0700**
**Bugzilla Id:** [2286](http://bugz.cgd.ucar.edu/show_bug.cgi?id=2286)
**Bugzilla Depends:**  1993, 
**Bugzilla CC:**  andre,  dlawren,  rfisher,  sacks,  swensosc, 

I found this in clm4_5_7_r166, but probably goes before it. It's probably also OK (so will likely close as a WONTFIX), but I want to document it.

When changing the PE layout from the default of a sequential 180x1 to a concurrent 540x1 (clm) and 30x1 (datm) answers change as follows...

For SMS_Ld5.f19_g16.IRCP45CLM45BGC.yellowstone_intel.clm-decStart

--- Baseline Comparison ---: 
FAIL SMS_Ld5.f19_g16.IRCP45CLM45BGC.yellowstone_intel.clm-decStart.clm2.h0.nc : baseline compare clm2.h0 (baseline: compare .base file with clm4_5_7_r166 file) 
PASS SMS_Ld5.f19_g16.IRCP45CLM45BGC.yellowstone_intel.clm-decStart.clm2.h1.nc : baseline compare clm2.h1 (baseline: compare .base file with clm4_5_7_r166 file) 
FAIL SMS_Ld5.f19_g16.IRCP45CLM45BGC.yellowstone_intel.clm-decStart.cpl.hi.nc : baseline compare cpl.hi (baseline: compare .base file with clm4_5_7_r166 file) 
PASS SMS_Ld5.f19_g16.IRCP45CLM45BGC.yellowstone_intel.clm-decStart.rtm.h0.nc : baseline compare rtm.h0 (baseline: compare .base file with clm4_5_7_r166 file) 
FAIL SMS_Ld5.f19_g16.IRCP45CLM45BGC.yellowstone_intel.clm-decStart : baseline compare summary (baseline: compare .base file with clm4_5_7_r166 file) 

[erik@yslogin1 scripts]$ grep RMS SMS_Ld5.f19_g16.IRCP45CLM45BGC.yellowstone_intel.clm-decStart.C.160219-001241/TestStatus.log 
   RMS TWS                              1.2087E-14            NORMALIZED  7.2685E-19
    RMS VOLR                             1.5567E-06            NORMALIZED  4.1736E-15
    RMS VOLRMCH                          1.5567E-06            NORMALIZED  4.1736E-15
   RMS x2l_Flrr_volr                    9.5518E-18            NORMALIZED  1.4040E-15
    RMS x2l_Flrr_volrmch                 9.5518E-18            NORMALIZED  1.4040E-15

I'm also testing longer cases to make sure the signal looks similar.

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2016-02-19 11:26:01 -0700**

It does get worse for longer simulations....

FAIL SMS_Lm25.f19_g16.ICLM45BGCCROP.yellowstone_gnu.clm-cropMonthOutput.clm2.h0.nc : baseline compare clm2.h0 (baseline: compare .base file with clm4_5_7_r166 file) 
FAIL SMS_Lm25.f19_g16.ICLM45BGCCROP.yellowstone_gnu.clm-cropMonthOutput.clm2.h1.nc : baseline compare clm2.h1 (baseline: compare .base file with clm4_5_7_r166 file) 
FAIL SMS_Lm25.f19_g16.ICLM45BGCCROP.yellowstone_gnu.clm-cropMonthOutput.cpl.hi.nc : baseline compare cpl.hi (baseline: compare .base file with clm4_5_7_r166 file) 
FAIL SMS_Lm25.f19_g16.ICLM45BGCCROP.yellowstone_gnu.clm-cropMonthOutput.rtm.h0.nc : baseline compare rtm.h0 (baseline: compare .base file with clm4_5_7_r166 file) 
FAIL SMS_Lm25.f19_g16.ICLM45BGCCROP.yellowstone_gnu.clm-cropMonthOutput : baseline compare summary (baseline: compare .base file with clm4_5_7_r166 file) 

   RMS ERRSOI                           5.8251E-12            NORMALIZED  8.9433E-02
    RMS FCEV                             2.6698E-03            NORMALIZED  6.1681E-04
    RMS FCTR                             1.0327E-03            NORMALIZED  8.5970E-05
    RMS FGEV                             1.2422E-02            NORMALIZED  1.0727E-03
    RMS FGR                              1.5871E-02            NORMALIZED  1.0567E-03
    RMS FIRA                             6.2943E-03            NORMALIZED  1.3382E-04
    RMS FIRE                             6.2943E-03            NORMALIZED  2.2276E-05
    RMS FSA                              1.5189E-02            NORMALIZED  1.6907E-04
    RMS FSH                              7.7797E-03            NORMALIZED  2.3141E-04
    RMS FSR                              1.5189E-02            NORMALIZED  4.8312E-04
    RMS FSRND                            1.9019E-03            NORMALIZED  1.4342E-04
    RMS FSRNI                            7.3052E-04            NORMALIZED  1.9230E-04
    RMS FSRVD                            7.2809E-03            NORMALIZED  8.4667E-04
    RMS FSRVI                            5.5099E-03            NORMALIZED  9.5318E-04
    RMS H2OSNO                           3.8885E-02            NORMALIZED  4.2228E-04
    RMS H2OSOI                           8.1366E-05            NORMALIZED  3.8102E-04
    RMS LWup                             6.2943E-03            NORMALIZED  2.2276E-05
    RMS QRUNOFF_R                        3.1225E-09            NORMALIZED  3.3684E-04
    RMS RH2M                             1.0818E-03            NORMALIZED  1.2780E-05
    RMS RH2M_R                           1.3486E-03            NORMALIZED  1.5549E-05
    RMS SABG                             1.4827E-02            NORMALIZED  2.7866E-04
    RMS SABV                             3.8115E-03            NORMALIZED  1.0406E-04
    RMS SOILICE                          3.6482E-03            NORMALIZED  1.8500E-05
    RMS SOILLIQ                          3.1434E-03            NORMALIZED  6.2646E-05
    RMS SWup                             1.5189E-02            NORMALIZED  4.8312E-04
    RMS TG                               9.3921E-04            NORMALIZED  3.3576E-06
    RMS TG_R                             3.3882E-03            NORMALIZED  1.2149E-05
    RMS TREFMNAV_R                       1.6421E-03            NORMALIZED  6.1001E-06
    RMS TREFMXAV_R                       3.7410E-04            NORMALIZED  1.3483E-06
    RMS TSA                              9.0321E-04            NORMALIZED  3.2828E-06
    RMS TSA_R                            1.1260E-03            NORMALIZED  4.1238E-06
    RMS TSOI                             5.0202E-04            NORMALIZED  1.7702E-06
   RMS l2x_Sl_avsdr                     5.5267E-04            NORMALIZED  6.3151E-04
    RMS l2x_Sl_anidr                     1.2131E-04            NORMALIZED  1.5495E-04
    RMS l2x_Sl_avsdf                     5.6460E-04            NORMALIZED  6.4925E-04
    RMS l2x_Sl_anidf                     1.6401E-04            NORMALIZED  2.0692E-04
    RMS l2x_Sl_tref                      2.4176E-04            NORMALIZED  9.2262E-07
    RMS l2x_Sl_qref                      8.1951E-08            NORMALIZED  1.7482E-05
    RMS l2x_Sl_t                         9.1557E-04            NORMALIZED  3.5086E-06
    RMS l2x_Sl_fv                        2.1176E-05            NORMALIZED  1.1119E-04
    RMS l2x_Sl_ram1                      4.6841E-02            NORMALIZED  1.1511E-04
    RMS l2x_Sl_snowh                     9.5734E-05            NORMALIZED  2.5947E-04
    RMS l2x_Sl_u10                       8.6799E-05            NORMALIZED  2.9998E-05
    RMS l2x_Fall_swnet                   4.2353E-02            NORMALIZED  1.0601E-03
    RMS l2x_Fall_taux                    6.0736E-06            NORMALIZED  9.1967E-05
    RMS l2x_Fall_tauy                    6.0736E-06            NORMALIZED  9.1967E-05
    RMS l2x_Fall_lat                     3.6518E-03            NORMALIZED  2.5048E-04
    RMS l2x_Fall_sen                     4.1014E-03            NORMALIZED  2.1172E-04
    RMS l2x_Fall_lwup                    4.1975E-03            NORMALIZED  1.5080E-05
    RMS l2x_Fall_evap                    1.4229E-09            NORMALIZED  2.4634E-04
    RMS l2x_Fall_flxdst1                 4.8704E-15            NORMALIZED  2.0036E-04
    RMS l2x_Fall_flxdst2                 2.6143E-14            NORMALIZED  2.0036E-04
    RMS l2x_Fall_flxdst3                 6.1303E-14            NORMALIZED  2.0036E-04
    RMS l2x_Fall_flxdst4                 5.7745E-14            NORMALIZED  2.0036E-04
    RMS l2x_Flrl_rofsur                  1.3261E-09            NORMALIZED  6.7267E-04
    RMS l2x_Flrl_rofsub                  1.6917E-09            NORMALIZED  5.3497E-04
    RMS x2l_Flrr_volr                    9.4158E-07            NORMALIZED  8.4403E-05
    RMS x2l_Flrr_volrmch                 9.4158E-07            NORMALIZED  8.4403E-05
    RMS r2x_Forr_rofl                    1.5252E-08            NORMALIZED  1.2185E-02
    RMS r2x_Forr_rofi                    7.8624E-23            NORMALIZED  1.2486E-16
    RMS r2x_Flrr_volr                    1.4482E-06            NORMALIZED  3.1306E-04
    RMS r2x_Flrr_volrmch                 1.4482E-06            NORMALIZED  3.1306E-04
    RMS x2r_Flrl_rofsur                  2.6800E-09            NORMALIZED  3.9684E-03
    RMS x2r_Flrl_rofsub                  2.0646E-10            NORMALIZED  2.1599E-04
   RMS QCHANR                           1.4626E+00            NORMALIZED  8.8120E-03
    RMS QCHANR_ICE                       6.1338E-16            NORMALIZED  4.0484E-17
    RMS QCHOCNR                          2.2583E-01            NORMALIZED  4.3812E-02
    RMS QCHOCNR_ICE                      1.5925E-16            NORMALIZED  1.7625E-16

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2016-02-19 11:28:20 -0700**

I talked to Sean about this. He was surprised at the VOLR change. And he thought that if VOLR changes -- it shouldn't affect the rest of CLM (other than TWS). I also found that answers change on a longer test, so there may be an additional bug that is causing answers to change.

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2016-02-19 14:20:28 -0700**

For the short case, if I turn RTM off (by setting it to a NULL grid) answers are again identical.

[erik@yslogin1 SMS_Lm25.f19_g16_rn.ICLM45BGCCROP.yellowstone_gnu.clm-cropMonthOutput.C.160219-135252]$ cat ../SMS_Ld5.f19_g16_rn.IRCP45CLM45BGC.yellowstone_intel.clm-decStart.C.160219-133805/TestStatus
DONE SMS_Ld5.f19_g16_rn.IRCP45CLM45BGC.yellowstone_intel.clm-decStart : (test finished, successful coupler log) 
 --- Test Functionality: ---
PASS SMS_Ld5.f19_g16_rn.IRCP45CLM45BGC.yellowstone_intel.clm-decStart : successful coupler log 
PASS SMS_Ld5.f19_g16_rn.IRCP45CLM45BGC.yellowstone_intel.clm-decStart.memleak
--- Baseline Comparison ---: 
PASS SMS_Ld5.f19_g16_rn.IRCP45CLM45BGC.yellowstone_intel.clm-decStart.clm2.h0.nc : baseline compare clm2.h0 (baseline: compare .base file with clm4_5_7_r166 file) 
PASS SMS_Ld5.f19_g16_rn.IRCP45CLM45BGC.yellowstone_intel.clm-decStart.clm2.h1.nc : baseline compare clm2.h1 (baseline: compare .base file with clm4_5_7_r166 file) 
PASS SMS_Ld5.f19_g16_rn.IRCP45CLM45BGC.yellowstone_intel.clm-decStart.cpl.hi.nc : baseline compare cpl.hi (baseline: compare .base file with clm4_5_7_r166 file) 
PASS SMS_Ld5.f19_g16_rn.IRCP45CLM45BGC.yellowstone_intel.clm-decStart : baseline compare summary (baseline: compare .base file with clm4_5_7_r166 file) 
PASS SMS_Ld5.f19_g16_rn.IRCP45CLM45BGC.yellowstone_intel.clm-decStart.memcomp.clm4_5_7_r166 
PASS SMS_Ld5.f19_g16_rn.IRCP45CLM45BGC.yellowstone_intel.clm-decStart.tputcomp.clm4_5_7_r166

I'm running the longer case to see what happens there.

**Comment by ekluzek** [comment]
**Bill Sacks < sacks > - 2016-02-19 14:23:46 -0700**

Erik: Maybe you already know this, but this is a duplicate of bug 1993

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2016-02-19 15:06:27 -0700**

The longer test (without RTM) fails with lots of differences as before. So there seems to be a bug outside the VOLR issue. It starts after the 5 day test though. So I wonder if it's an issue at the end of year.

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2016-02-19 16:26:31 -0700**

12 month tests fail as well, so changing the name of this bug. This isn't just the VOLR issue in 1993.

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2016-02-20 19:52:45 -0700**

A 12-month BGC (no-crop) case passes. And looking at the 12-month BGCCROP case, it fails just at the very end. So I'm assuming it's something at the year boundary for CROP.

**Comment by billsacks** [comment]
Given that we have multi-year ERP crop tests that are passing, we assume this was fixed at some point.
