### ISSUE TITLE
t_startf/t_stopf mismatch found with update to ctsm5.1.dev027

### ISSUE THREAD

**Issue by glemieux** [ESCOMP/CTSM#1336]
### Brief summary of bug

The `t_stopf` string for the `wrap_update_hifrq_hist` subroutine does not match it's `t_startf` companion resulting in a RUN failure for `ERS_D_Ld3.f19_g17.I2000Clm50FatesCru.cheyenne_gnu.clm-FatesColdDef` test from the `fates` suite of regression tests, but only for ctsm dev tags from `ctsm5.1.dev027` and onwards.

### General bug information

**CTSM version you are using:** ctsm5.1.dev027

**Does this bug cause significantly incorrect results in the model's science?** Not expected, but unknown due to RUN failure

**Configurations affected:** 

### Details of bug

Note this bug was initially reported with [fates issue #728](https://github.com/NGEET/fates/issues/728).

@rgknox discovered this bug while testing [fates pr #723](https://github.com/NGEET/fates/pull/723) with the `ctsm5.1.dev029`.  Interestingly, the error was present in prior dev tags since `ctsm5.1.dev022` (when `fates_main_api` branch was merged with ctsm `master`), but the above test always passed previous.

It should be noted that the `intel` version of this test in the `fates` regression test suite passes.

### Important details of your setup / configuration so we can reproduce the bug

Tested on cheyenne.

### Important output or errors that show the problem
From the cesm.log in `/glade/u/home/glemieux/scratch/tests_0413-143428ch/ERS_D_Ld3.f19_g17.I2000Clm50FatesCru.cheyenne_gnu.clm-FatesColdDef.0413-143428ch_gnu/run`
```
4778 1437:GPTLstopf thread 0: timer for l:fates_wrap_hifrq_hist had not been started.
4779 1151:#0  0x2ac128b95aff in ???
4780 1151:#1  0x838176 in __fateshistoryinterfacemod_MOD_update_history_hifrq
4781 1151:   at /glade/u/home/glemieux/ctsmbase/src/fates/main/FatesHistoryInterfaceMod.F90:3716
4782 1151:#2  0x541c95 in __clmfatesinterfacemod_MOD_wrap_update_hifrq_hist
4783 1151:   at /glade/u/home/glemieux/ctsmbase/src/utils/clmfates_interfaceMod.F90:2154
4784 1151:#3  0x5200a2 in __clm_driver_MOD_clm_drv
4785 1151:   at /glade/u/home/glemieux/ctsmbase/src/main/clm_driver.F90:1089
4786 1151:#4  0x50d38d in __lnd_comp_mct_MOD_lnd_run_mct
4787 1151:   at /glade/u/home/glemieux/ctsmbase/src/cpl/mct/lnd_comp_mct.F90:456
4788 1151:#5  0x42c074 in __component_mod_MOD_component_run
4789 1151:   at /glade/u/home/glemieux/ctsmbase/cime/src/drivers/mct/main/component_mod.F90:714
4790 1151:#6  0x412a41 in __cime_comp_mod_MOD_cime_run
4791 1151:   at /glade/u/home/glemieux/ctsmbase/cime/src/drivers/mct/main/cime_comp_mod.F90:2817
4792 1151:#7  0x42ab4f in cime_driver
4793 1151:   at /glade/u/home/glemieux/ctsmbase/cime/src/drivers/mct/main/cime_driver.F90:153
4794 1151:#8  0x42ac5b in main
4795 1151:   at /glade/u/home/glemieux/ctsmbase/cime/src/drivers/mct/main/cime_driver.F90:23
4796 0: memory_write: model date =   20000102       0 memory =  131278.25 MB (highwater)        105.45 MB (usage)  (pe=    0 comps= ATM IAC ESP)
4797 -1:MPT ERROR: MPI_COMM_WORLD rank 1151 has terminated without calling MPI_Finalize()
4798 -1:     aborting job
4799 MPT: Received signal 8
```

**Comment by rgknox** [comment]
Is this a duplicate of #1248 ?

**Comment by glemieux** [comment]
Totally.
