### ISSUE TITLE
Floating point exception in fates gnu compiler regression test with ctsm5.1.dev027

### ISSUE THREAD

**Issue by glemieux** [ESCOMP/CTSM#1338]
### Brief summary of bug

The update to `ctsm5.1.dev027` results in the `ERS_D_Ld3.f19_g17.I2000Clm50FatesCru.cheyenne_gnu.clm-FatesColdDef` test from the `fates` suite of regression tests to failing during runtime with a floating point exception.

### General bug information

**CTSM version you are using:** ctsm5.1.dev027

**Does this bug cause significantly incorrect results in the model's science?** Unknown, RUN failure

**Configurations affected:** 

### Details of bug

Note this bug was initially presented in [fates issue #728](https://github.com/NGEET/fates/issues/728).

This bug was discovered this bug while testing [fates pr #723](https://github.com/NGEET/fates/pull/723) with the `ctsm5.1.dev029`.  Upon locally fixing issue #1336, the gnu version of `ERS_D_Ld3.f19_g17.I2000Clm50FatesCru` fails with a floating point exception.  The most recent fates initiated changes to the ctsm-side code was with `ctsm5.1.dev022` and the the same code modification for fixing #1336 was tested on `ctsm5.1.dev026` without any runtime failure.

It should be noted that the intel version of this test in the fates regression test suite passes.

### Important details of your setup / configuration so we can reproduce the bug

Tested on cheyenne only so far.

### Important output or errors that show the problem

From cesm.log in `/glade/u/home/glemieux/scratch/tests_0413-152656ch/ERS_D_Ld3.f19_g17.I2000Clm50FatesCru.cheyenne_gnu.clm-FatesColdDef.0413-152656ch/run`
```
3332 1475:MOSART decomp info proc =      1439 begr =    259021 endr =    259200 numr =       180
3333 0:(seq_domain_areafactinit) : min/max mdl2drv    1.00000000000000       1.00000000000000    areafact_a_ATM
3334 0:(seq_domain_areafactinit) : min/max drv2mdl    1.00000000000000       1.00000000000000    areafact_a_ATM
3335 0: memory_write: model date =   20000101       0 memory =  131278.23 MB (highwater)        105.48 MB (usage)  (pe=    0 comps= ATM IAC ESP)
3336 1151:
3337 1151:Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
3338 1151:
3339 1151:Backtrace for this error:
3340 1151:#0  0x2b32def31aff in ???
3341 1151:#1  0x838176 in __fateshistoryinterfacemod_MOD_update_history_hifrq
3342 1151:   at /glade/u/home/glemieux/ctsmbase/src/fates/main/FatesHistoryInterfaceMod.F90:3716
3343 1151:#2  0x541c95 in __clmfatesinterfacemod_MOD_wrap_update_hifrq_hist
3344 1151:   at /glade/u/home/glemieux/ctsmbase/src/utils/clmfates_interfaceMod.F90:2154
3345 1151:#3  0x5200a2 in __clm_driver_MOD_clm_drv
3346 1151:   at /glade/u/home/glemieux/ctsmbase/src/main/clm_driver.F90:1089
3347 1151:#4  0x50d38d in __lnd_comp_mct_MOD_lnd_run_mct
3348 1151:   at /glade/u/home/glemieux/ctsmbase/src/cpl/mct/lnd_comp_mct.F90:456
3349 1151:#5  0x42c074 in __component_mod_MOD_component_run
3350 1151:   at /glade/u/home/glemieux/ctsmbase/cime/src/drivers/mct/main/component_mod.F90:714
3351 1151:#6  0x412a41 in __cime_comp_mod_MOD_cime_run
3352 1151:   at /glade/u/home/glemieux/ctsmbase/cime/src/drivers/mct/main/cime_comp_mod.F90:2817
3353 1151:#7  0x42ab4f in cime_driver
3354 1151:   at /glade/u/home/glemieux/ctsmbase/cime/src/drivers/mct/main/cime_driver.F90:153
3355 1151:#8  0x42ac5b in main
3356 1151:   at /glade/u/home/glemieux/ctsmbase/cime/src/drivers/mct/main/cime_driver.F90:23
3357 -1:MPT ERROR: MPI_COMM_WORLD rank 1151 has terminated without calling MPI_Finalize()
3358 -1:     aborting job
3359 MPT: Received signal 8
```

**Comment by jkshuman** [comment]
@glemieux I see this PR is merged. Can this be closed?

**Comment by glemieux** [comment]
Yes, I think so.  Looking at the code that was failing out, it appears that it may have been an initialization issue.  It looks like we may have fixed it (prompted by a different issue) via: https://github.com/NGEET/fates/pull/807
