### ISSUE TITLE
Create NEON surface dataset

### ISSUE THREAD

**Issue by negin513** [ESCOMP/CTSM#1352]
NEON surface data will be provided for NEON compset, but for other single point simulations we will need to create this on the fly. See also #935
-  [x] This will be a generic function to be used in any single point simulation building of of `singlept` in _tools/contrib_ 
- [x] Default surface dataset will subsequently be modified for NEON towers where data are available. 
- [x] Possibly explore adding regional case functionality to the same code. 
- Doing this in the containerized code in an efficient way would be great (e.g. by entering lat-lon without downloading surface dataset?).

**possibly looking into taking this out of contrib folder by adding testing.**

**Comment by wwieder** [comment]
@negin, can you update the readme for the tools/contrib directory with a bit of information on your new script?

**Comment by wwieder** [comment]
After this is done, I think you can close this issue?
