### ISSUE TITLE
Modify NEON surface data

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1353]
- [x] Build off of existing script `tools/contrib/modify_singlept_site` with **`modify_singlept_NEON`**
- [x] Include these modified surface dataset in `inputdata` (or do users run this script)?
  - @danicalombardozzi suggested these be provided for the users and included in the NEON workflow that @jedwards4b developed.
  - Link with #1411, or another PR.
   
- [x]  **Updating PFTs**
  - `PCT_NAT_PFT` should reflect vegetation at the site
  - This is now being done in `subset_data.py` frrom #1360 reading in data file used to generate surface datasets. 
  - This will may require input from the NEON team on [this file](https://docs.google.com/spreadsheets/d/1htjacmMJp1eDVglezwvde72ZzL0N0qg3NddNF7rN0_A/edit?usp=sharing).
    - A copy of this file on Cheyenne is available here /glade/p/cgd/tss/people/wwieder/inputdata/single_point/NEON_SiteData/NEONtowerSiteMetadata.csv
  - **How do we handle sites with mixed vegetation `KONZ` or crops `KONA`?**
  
- [x] **Soil Properties, soil texture**
  - Modify surface data with NEON observations that are posted in NEON bucket (soil texture, PFTs, etc).
  - `PCT_SAND`, `PCT_CLAY` on surface data should come from `sandTotal` and `sandTotal` on NEON.  
  - This will require mapping depths associated with `nlevsoi` on the surface dataset with `biogeoTopDepth` and `biogeoBottomDepth` in NEON data.  
  - Here, I'd suggest that for CTSM soil levels that cover two NEON layers the **data are NOT averaged**, but CTSM use the largest depth measured
  - [Sample data can be seen here](https://docs.google.com/spreadsheets/d/1e5MHoeJ-S4Z5zgjovZ8mccchH66beo5R9jS4811LIHU/edit?usp=sharing)
- [x] **Soil Properties, ORGANIC**
  - `ORGANIC` on surface dataset needs to be "kg/m3 (assumed carbon content 0.58 gC per gOM)". 
*Notes below should be checked (including units of NEON data)*  
  - `carbonTot` in NEON data are given as gC/kg soil, bulk density is reported as g/cm3 and depth is in cm
  - Thus for this conversion:
`ORGANIC` = `carbonTot` * `bulkDensity` / 0.58 **This has been modified based on this [comment](https://github.com/ESCOMP/CTSM/pull/1375/files#r669590971) 
- [x] check metadata provided with NEON observations
- [x] **depth to bedrock, `zbedrock`** 
  - Megapit data should all be from 0-200 cm.  Thus, rocky sites that don't get that deep should also modify `zbedrock`
  - Here's a quick look at sampling depth by sites
![image](https://user-images.githubusercontent.com/8031012/118702112-be149580-b7d1-11eb-8051-a4da161ab582.png)
   
  - This raises some interesting questions:
    - RMNP and HARV, I'd expect to see shallower soils 
    - Elsewhere (HEAL and TOOL) it looks like sampling didn't drill down into permafrost?  Is this accurate?  
    - Elsewhere, I don't really know what to expect (e.g. BARR, PUUM, OAES)?

**Comment by wwieder** [comment]
Initially I'd suggest we just use a single PFT for each site, even those with mixed vegetation, as it will make analyses much easier.  It also is easier than trying to determine the relative cover of each pft over the tower footprint.  @danicalombardozzi we can discuss further.

**Comment by wwieder** [comment]
Eventually we may want to let users more easily define the PFT's present at a site (and their % cover).  *@negin513 is this simple to implement or should we wait to do it later?*

**Comment by ekluzek** [comment]
@wwieder my understanding is that the originating subset_data.py script handles the changes for PFT's. This is doing the changes on top of that script that are needed just for NEON sites. So I think you would handle any changes to PFT's in that original script.

@negin513 can you clarify here?

**Comment by wwieder** [comment]
closed with #1474
