### ISSUE TITLE
Visualization: Python scripts for NEON analyses

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1355]
To be included in ESM-lab materials (and elsewhere?).  These can build on the example here
- https://github.com/wwieder/ctsm_py/blob/master/notebooks/ptCLM_NEON.ipynb and here
- https://github.com/wwieder/ctsm_py/blob/master/notebooks/ptCLM_multi.ipynb.

@negin has some ideas from the ESDS discussions about how this can be done
These plots should include:
- [x] Fluxes over time (line plots w/ model & obs, mean +- SD)
   -  Diel cycle
   - Seasonal or annual cycle
- [x] Scatter plot of model state or fluxes (model vs. obs)
   - broken down by season (e.g. DJF, JJA, etc)
- [x] depth vs. time soil temp, moisture & C stocks
- [x] synthesis diagnostics, evaluation statistics (e.g. RMSE) across multiple sites grouped by pft.
- [x] scatter plots of variable vs. variable to show relationships (e.g. GPP vs. incoming shortwave for LUE)
- [x] create table of ecosystem properties (summary statistic by sites, e.g. productivity, climate, C stocks).

These are being handled in https://github.com/NCAR/NEON-visualization
see also https://github.com/negin513/neon_scripts

**Comment by wwieder** [comment]
assigned @briandobbins so we can work with him on integration into ESM-lab as this effort matures

**Comment by wwieder** [comment]
This script will have to read in separate `eval_files` with the NEON observations where they are provided 
https://neon-ncar.s3.data.neonscience.org/NEON/eval_files/v1/BART/2018-02.nc

Gordon recommended now worrying about where these files are stored, but focusing on scripts to do monthly, seasonal, or annual plots are most valuable.  This will tie in with the CICoE visualization WG

**Comment by wwieder** [comment]
This is an excellent place to leverage tools with ESDS and CESM-lab?

**Comment by ekluzek** [comment]
If this is added to CTSM it will be under contrib and as such can come to CTSM main dev without running standard testing. But as already said this may make more sense to be in CESM-lab or somewhere else.

**Comment by wwieder** [comment]
Notes from @negin513's work so far (LINK TO REPO HERE)

- **Annual cycle plots**
  - [x] Clean up statistics on linear regression (Valerio), this is now the title of the plot.
  - [ ] Check that linear regression line is updating.
  - [ ] Print integral under the curve, annual flux
  - [ ] Include option to average over day of year (true annual cycle, lower priority?).
  - [ ] Plot gap filled NEON data with another color (using flags)
  - [ ] allow plotting of other (CLM only) variables.
- **Diel fluxes**
  - [ ] Check that linear regression line is updating.
  - [ ] Include other derived fluxes 
    - Net radiation (FSA - FIRA) 
    - Latent heat (FCTR+FGEV+FCEV)
    - NEE (GPP - ER *or* GPP - AR - HR)
  - [x] Subset / filter by season
  - [x] Add y axis labels
  - [ ] add y axis units
  - [x] Shift time so CLM-NEON align 
  - [ ] Shift time so local noon is midday & centered on the plot
  - [x] Include x-y scatter plot of CLM-NEON on plot too (this is not critical)
- **Vertically resolved contour plots over time**
  - This is working for matplotlib, but may need help for bokeh

**Do we need additional output by default?**

**Comment by wwieder** [comment]
As with #1385, this seems like something we want for the paper but that's not critical for the release to beta testers.
