### ISSUE TITLE
src_type and dst_type no longer needed in mkmapdata.sh

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1359]
With later versions of ESMF the --src_type and --dst_type flags aren't needed anymore.
It gives warnings as follows...

>  WARNING: deprecated switch -src_type will be ignored.  The file type will be de
>  tected automatically
>  
>  WARNING: deprecated switch -dst_type will be ignored.  The file type will be de
>  tected automatically

**Comment by billsacks** [comment]
Will be fixed in new tool chain work.
