### ISSUE TITLE
HR fluxes don't include CWD

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1361]
Since CLM4 coarse woody debris physically fragments into `LIT2` and `LIT3` pools with zero respiration fraction.
`rf_cwdl2_bgc = 0.`  

As a result this HR flux will not be calculated if `rf_cwdl2_bgc > 0.` 
https://github.com/ESCOMP/CTSM/blob/61770ad07d6eeecc0b6c5e9447c95f7c63e605d5/src/soilbiogeochem/SoilBiogeochemCarbonFluxType.F90#L242

Maybe not a big deal with our current parameterization, but it causes balance check errors in the PPE runs that @djk2120 is running.

@dlawrenncar and @djk2120 do you want this fixed for the PPE, or should we table it for now?  Regardless, this may be something @slevisconsulting addresses in his soil BGC refactoring we're doing for the MIMICS project.

**Comment by billsacks** [comment]
@slevisconsulting - @wwieder is going to talk with you about this.
