### ISSUE TITLE
Change NEON surface datasets to 79PFT files to facilitate the crop sites...

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1364]
The initial version of the NEON surface datasets is with 16PFT surface datasets. There are a few sites that will have crops so we think the surface datasets should use the 79PFT crop surface datasets for all cases so everything looks the same. The compsets will also be BgcCrop and always used that way so you don't do something different for a crop site verses a non crop site. The other way to do this would be to have different names for the crop sites. The surface datasets could be different and the compset used could be different.

If we make them all the same for 79PFT, the non-crop sites will set use_crop to FALSE.

@negin513 @jedwards4b

**Comment by wwieder** [comment]
@negin513 can will your PR for #1375 resolve/ close this issue?
