### ISSUE TITLE
NUOPC changes DATM_CLMNCEP_YR_START/END to DATM_YR_START/END

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1365]
This appears to just be a problem in some of the tools, documentation, the User's Guide and the USUMB test case. But between the MCT and NUOPC data models the DATM_CLMNCEP_YR xml variables were renamed to remove the CLMNCEP part of it. xmlchange shows an error when you try to change something that doesn't exist, so you have to know which one is being used in order to run. So tools or user-mods that assume one or the other have to know which driver is being used.

We'll need a testmod for USUMB that's specific for NUOPC, or it needs to check the driver being used.

The tools:

tools/contrib/run_clm_historical
tools/contrib/run_clmtowers

should either change to assume NUOPC (once we make it the default) or have a switch for the coupler being used. I suppose we should just change the User's Guide when NUOPC is the default.

FYI: @jedwards4b @mvertens

**Comment by billsacks** [comment]
@ekluzek is making the needed changes to get USUMB working with NUOPC.

Plan is to fix tools/contrib & the documentation once we switch to using nuopc by default.
