### ISSUE TITLE
Snowgrain size is zero

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#137]
**Erik Kluzek < erik > - 2016-05-03 12:47:27 -0600**
**Bugzilla Id:** [2310](http://bugz.cgd.ucar.edu/show_bug.cgi?id=2310)
**Bugzilla Depends:**  2027,  1934, 
**Bugzilla CC:**  dlawren,  fischer,  jedwards,  mflanner,  rfisher, 

Chris Fisher ran into the following problem

It looks like Intel 16 is causing "SNICAR ERROR: snow grain radius of 0".  The error message about
"calling inside a threaded region" is caused by the call to endrun.  So the real problem is SNICAR.
I'm using f19_g16.I1850CLM45.

This is the errors when NTHRDS=2
   98: SNICAR ERROR: snow grain radius of            0  out of bounds.
  98: NSTEP=            2
  98: flg_snw_ice=            1
  98: column:        38652  level:            0  snl(c)=           -1
  98: lat=    27.4736842105262       lon=    100.000000000000     
  98: h2osno(c)=   1.316051427843381E-005
  98: calling getglobalwrite with decomp_index=        38652  and clmlevel= column
  98: local  column   index =        38652
  98: ERROR: get_proc_bounds ERROR: Calling from inside  a threaded region
  98:Image              PC                Routine            Line        Source             
  98:cesm.exe           0000000003459153  Unknown               Unknown  Unknown
  98:cesm.exe           0000000002B075C0  shr_sys_mod_mp_sh         401  shr_sys_mod.F90
  98:cesm.exe           0000000002B071E3  shr_sys_mod_mp_sh         230  shr_sys_mod.F90
  98:cesm.exe           00000000007E0AA7  decompmod_mp_get_         218  decompMod.F90
  98:cesm.exe           0000000001092139  getglobalvaluesmo          43  GetGlobalValuesMod.F90
  98:cesm.exe           0000000001094751  getglobalvaluesmo         115  GetGlobalValuesMod.F90
  98:cesm.exe           0000000000752566  abortutils_mp_end          69  abortutils.F90
  98:cesm.exe           00000000013CD34C  snowsnicarmod_mp_         423  SnowSnicarMod.F90
  98:cesm.exe           0000000001A47C2C  surfacealbedomod_         616  SurfaceAlbedoMod.F90
  98:cesm.exe           0000000000777ABB  clm_driver_mp_clm         814  clm_driver.F90
  98:libiomp5.so        00002B3A71D039B3  Unknown               Unknown  Unknown
  98:libiomp5.so        00002B3A71CD29A7  Unknown               Unknown  Unknown
  98:libiomp5.so        00002B3A71CD2095  Unknown               Unknown  Unknown
  98:libiomp5.so        00002B3A71D03D33  Unknown               Unknown  Unknown
  98:libpthread.so.0    00002B3A72A109D1  Unknown               Unknown  Unknown
  98:libc.so.6          00002B3A73C0B8FD  Unknown               Unknown  Unknown

This is the error when NTHRDS=1
 167: SNICAR ERROR: snow grain radius of            0  out of bounds.
 167: NSTEP=            2
 167: flg_snw_ice=            1
 167: column:        64665  level:            0  snl(c)=           -1
 167: lat=    40.7368421052631       lon=    110.000000000000     
 167: h2osno(c)=    1.22099255624464     
 167: calling getglobalwrite with decomp_index=        64665  and clmlevel= column
 167: local  column   index =        64665
 167: global column   index =        36670
 167: global landunit index =        12010
 167: global gridcell index =         3663
 167: gridcell longitude    =    110.000000000000     
 167: gridcell latitude     =    40.7368421052631     
 167: column   type         =            1
 167: landunit type         =            1
 167: ENDRUN:
 167: ERROR in SnowSnicarMod.F90 at line 423                                         
 167:                                                                                
 167:                                                                                
 167:                                                                                
 167:                                                                                
 167:                                                                                
 167:                                       
 167: ERROR: Unknown error submitted to shr_sys_abort.
 167:Image              PC                Routine            Line        Source             
 167:cesm.exe           00000000034BC9CE  Unknown               Unknown  Unknown
 167:cesm.exe           0000000002B85E82  shr_sys_mod_mp_sh         401  shr_sys_mod.F90
 167:cesm.exe           0000000002B85AAF  shr_sys_mod_mp_sh         230  shr_sys_mod.F90
 167:cesm.exe           000000000074D60D  abortutils_mp_end          77  abortutils.F90
 167:cesm.exe           0000000001400CC6  snowsnicarmod_mp_         423  SnowSnicarMod.F90
 167:cesm.exe           0000000001AB06BB  surfacealbedomod_         616  SurfaceAlbedoMod.F90
 167:cesm.exe           000000000076EE22  clm_driver_mp_clm         814  clm_driver.F90
 167:cesm.exe           00000000007275BD  lnd_comp_mct_mp_l         437  lnd_comp_mct.F90
 167:cesm.exe           00000000004595D6  component_mod_mp_        1079  component_mod.F90
 167:cesm.exe           00000000004308A3  cesm_comp_mod_mp_        2509  cesm_comp_mod.F90
 167:cesm.exe           000000000044327F  MAIN__                     93  cesm_driver.F90
 167:cesm.exe           000000000040BA1E  Unknown               Unknown  Unknown
 167:libc.so.6          00002B9C5E114D5D  Unknown               Unknown  Unknown

It looks like Intel 16 is causing "SNICAR ERROR: snow grain radius of 0".  The error message about
"calling inside a threaded region" is caused by the call to endrun.  So the real problem is SNICAR.
I'm using f19_g16.I1850CLM45.

This is the errors when NTHRDS=2
   98: SNICAR ERROR: snow grain radius of            0  out of bounds.
  98: NSTEP=            2
  98: flg_snw_ice=            1
  98: column:        38652  level:            0  snl(c)=           -1
  98: lat=    27.4736842105262       lon=    100.000000000000     
  98: h2osno(c)=   1.316051427843381E-005
  98: calling getglobalwrite with decomp_index=        38652  and clmlevel= column
  98: local  column   index =        38652
  98: ERROR: get_proc_bounds ERROR: Calling from inside  a threaded region
  98:Image              PC                Routine            Line        Source             
  98:cesm.exe           0000000003459153  Unknown               Unknown  Unknown
  98:cesm.exe           0000000002B075C0  shr_sys_mod_mp_sh         401  shr_sys_mod.F90
  98:cesm.exe           0000000002B071E3  shr_sys_mod_mp_sh         230  shr_sys_mod.F90
  98:cesm.exe           00000000007E0AA7  decompmod_mp_get_         218  decompMod.F90
  98:cesm.exe           0000000001092139  getglobalvaluesmo          43  GetGlobalValuesMod.F90
  98:cesm.exe           0000000001094751  getglobalvaluesmo         115  GetGlobalValuesMod.F90
  98:cesm.exe           0000000000752566  abortutils_mp_end          69  abortutils.F90
  98:cesm.exe           00000000013CD34C  snowsnicarmod_mp_         423  SnowSnicarMod.F90
  98:cesm.exe           0000000001A47C2C  surfacealbedomod_         616  SurfaceAlbedoMod.F90
  98:cesm.exe           0000000000777ABB  clm_driver_mp_clm         814  clm_driver.F90
  98:libiomp5.so        00002B3A71D039B3  Unknown               Unknown  Unknown
  98:libiomp5.so        00002B3A71CD29A7  Unknown               Unknown  Unknown
  98:libiomp5.so        00002B3A71CD2095  Unknown               Unknown  Unknown
  98:libiomp5.so        00002B3A71D03D33  Unknown               Unknown  Unknown
  98:libpthread.so.0    00002B3A72A109D1  Unknown               Unknown  Unknown
  98:libc.so.6          00002B3A73C0B8FD  Unknown               Unknown  Unknown

This is the error when NTHRDS=1
 167: SNICAR ERROR: snow grain radius of            0  out of bounds.
 167: NSTEP=            2
 167: flg_snw_ice=            1
 167: column:        64665  level:            0  snl(c)=           -1
 167: lat=    40.7368421052631       lon=    110.000000000000     
 167: h2osno(c)=    1.22099255624464     
 167: calling getglobalwrite with decomp_index=        64665  and clmlevel= column
 167: local  column   index =        64665
 167: global column   index =        36670
 167: global landunit index =        12010
 167: global gridcell index =         3663
 167: gridcell longitude    =    110.000000000000     
 167: gridcell latitude     =    40.7368421052631     
 167: column   type         =            1
 167: landunit type         =            1
 167: ENDRUN:
 167: ERROR in SnowSnicarMod.F90 at line 423                                         
 167:                                                                                
 167:                                                                                
 167:                                                                                
 167:                                                                                
 167:                                                                                
 167:                                       
 167: ERROR: Unknown error submitted to shr_sys_abort.
 167:Image              PC                Routine            Line        Source             
 167:cesm.exe           00000000034BC9CE  Unknown               Unknown  Unknown
 167:cesm.exe           0000000002B85E82  shr_sys_mod_mp_sh         401  shr_sys_mod.F90
 167:cesm.exe           0000000002B85AAF  shr_sys_mod_mp_sh         230  shr_sys_mod.F90
 167:cesm.exe           000000000074D60D  abortutils_mp_end          77  abortutils.F90
 167:cesm.exe           0000000001400CC6  snowsnicarmod_mp_         423  SnowSnicarMod.F90
 167:cesm.exe           0000000001AB06BB  surfacealbedomod_         616  SurfaceAlbedoMod.F90
 167:cesm.exe           000000000076EE22  clm_driver_mp_clm         814  clm_driver.F90
 167:cesm.exe           00000000007275BD  lnd_comp_mct_mp_l         437  lnd_comp_mct.F90
 167:cesm.exe           00000000004595D6  component_mod_mp_        1079  component_mod.F90
 167:cesm.exe           00000000004308A3  cesm_comp_mod_mp_        2509  cesm_comp_mod.F90
 167:cesm.exe           000000000044327F  MAIN__                     93  cesm_driver.F90
 167:cesm.exe           000000000040BA1E  Unknown               Unknown  Unknown
 167:libc.so.6          00002B9C5E114D5D  Unknown               Unknown  Unknown

**Comment by billsacks** [comment]
Closing because we haven't seen this in a while.
