### ISSUE TITLE
Invalid xml for namelist_definition file: missing end tag

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1379]
There is a missing `</entry>` tag here:

https://github.com/ESCOMP/CTSM/blob/c9775200b5e3ad0c1cbbffb94c396bc47b7e3d4c/bld/namelist_files/namelist_definition_ctsm.xml#L334-L336

I'm surprised this doesn't cause any problems in parsing the xml, but in any case, we should fix it.

**Comment by ekluzek** [comment]
xmllint does show that as a problem. I'm surprised it works ok as well...
