### ISSUE TITLE
write out friction velocity to history files by default

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1382]
The NEON simulations (and other tower simulations need this).

Also update the long-name to remove 'dust model'

**Comment by wwieder** [comment]
https://github.com/ESCOMP/CTSM/blob/075b273c682de56a7f87e389ec9b4c90570bce3d/src/biogeophys/FrictionVelocityMod.F90#L235

**Comment by wwieder** [comment]
@ekluzek if you have any BFB tags coming up can you make this change?

**Comment by billsacks** [comment]
@wwieder will confirm that this variable is truly the friction velocity used generally (@dlawrenncar recalls that we may have two similar variables).

**Comment by wwieder** [comment]
This is the variable ustar. It's used in the dust model, but not modified there.  As such, I recommend we just call this 'friction velocity'.  I'll let @dlawrenncar check on the consistency with wind used for the calculation here.  
* Note this comment in the code https://github.com/ESCOMP/CTSM/blob/075b273c682de56a7f87e389ec9b4c90570bce3d/src/biogeophys/FrictionVelocityMod.F90#L781

**Comment by wwieder** [comment]
Move outside of BGC loop
make active by default https://github.com/ESCOMP/CTSM/blob/93749b9cc0bbd9d522f15bba37937d0eef54b5a8/src/biogeophys/FrictionVelocityMod.F90#L238

**Comment by billsacks** [comment]
@wwieder it looks like this (and maybe some other) issues accidentally got linked to #1467 . GitHub says that this issue will auto-close when #1467 is merged, but I don't think that's right. I'm not sure how you linked this to that PR, but is there a way to unlink it?

**Comment by wwieder** [comment]
unlinked
