### ISSUE TITLE
Change shebang of python to python3 in buildlib /buildnml

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1383]
This is for compatibility with the latest cime which we are using. But we should change the shebang lines for python programs to use "python3" rather than "python". It needs to be done for buildlib and buildnml (and should also be done for MOSART, RTM and mizuRoute). It could also be done for other python scripts as well.

**Comment by ekluzek** [comment]
I think this doesn't actually matter since it's calling buildnml as a python subroutine rather than a script as indicated by the following log output in the preview_namelist...

> 06-09 12:02 CIME.case.preview_namelists INFO       2021-06-09 12:02:25 lnd 
> 06-09 12:02 CIME.case.preview_namelists INFO     Create namelist for component clm
> 06-09 12:02 CIME.utils   INFO        Calling /glade/work/erik/ctsm_cn-matrix_v3/cime_config/buildnml

**Comment by billsacks** [comment]
See also https://github.com/ESMCI/cime/issues/3919

**Comment by ekluzek** [comment]
The most recent email from @sacks says we should do the following steps (the first one is already done).

> (2) [Optional, but suggested] Add a warning message if buildnml / buildlib are being called as subprocesses, in the 'if __name__ == "__main__":' or _main_func functions (or equivalent in your script).
> 
> (3) Change the shebang lines to "python3": even if they are typically called as subroutines (where the shebang line doesn't matter), the desire to maintain the ability for them to be called as subprocesses means that we should be sure they use python3 in that case.

**Comment by ekluzek** [comment]
There seems to be some issues with modify_singlept_site. I'm not sure if this is important to update now or not, and I can't seem to quickly get it working. So I'm going to leave it as is.
