### ISSUE TITLE
Fix documentation on number of snow layers

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1389]
@timhoar points out that the documentation in https://escomp.github.io/ctsm-docs/versions/master/html/tech_note/Soil_Snow_Temperatures/CLM50_Tech_Note_Soil_Snow_Temperatures.html still refers to there being five snow layers (search for "five"). It looks like, when the number of snow layers was expanded to 12, https://escomp.github.io/ctsm-docs/versions/master/html/tech_note/Snow_Hydrology/CLM50_Tech_Note_Snow_Hydrology.html was updated but not the chapter on soil & snow temperatures.

**Comment by olyson** [comment]
This is done.
