### ISSUE TITLE
Some soil decomposition  history fields have the pool number rather than a description in their name

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1392]
This is a change in ctsm5.1.dev043. Some soil decomposition history fields now have the pool number in their name rather than description. Previously they had LIT, CEL, or MET in the name and now they have a number 1,2, or 3. I think it will be easier for people to have the description in the name rather than a number where they have to examine the code to figure out which pool it refers to.

These fields are default inactive:

DWT_FROOTN_TO_LITR_*_N
C13_DWT_FROOTC_TO_LITR_*_C
C14_DWT_FROOTC_TO_LITR_*_C

@wwieder

**Comment by ekluzek** [comment]
I also wonder if we should add some tests that output these fields.

**Comment by wwieder** [comment]
@slevisconsulting let's talk about this after the CESM workshop.  This is related to concerns @ekluzek raised about readability of the code.  Maybe we can just add long names that are more descriptive for each model (e.g. when to define lit-met vs. lit-struc for mimcs vs. lit-met, lit-cel, lit-lig for century)?  Similarly soils should be 'available', 'chemically protected' and 'physically protected' in mimics vs. active, slow & passive for century

**Comment by wwieder** [comment]
@ekluzek I understand you concern but have two thoughts in advance of our call.

Currently the soil model uses numbering for LIT and SOIL pools  
https://github.com/ESCOMP/CTSM/blob/2a90c2063ad5b61f381b9cd69c1c6e47850ee1fb/src/soilbiogeochem/SoilBiogeochemDecompCascadeBGCMod.F90#L356

can MIMICS use the same approach here, by defining LIT_1 as METABOLIC and LIT_2 as STRUCTURAL, but then just using the numbered pools in the code?  Maybe I'm not completely understanding your concern?

**Comment by ekluzek** [comment]
Yes, I am just talking about the name on the history files, and NOT what's in the code. The code would continue to have it as a numbered pool, but the name of the history variable would include the pool description (so you don't have to look up the meaning of each numbered pool). The idea is to just make this easier for scientists who are running the model and looking at the history fields.

In our discussion you suggested using a short descriptor of 3 or 4 characters, and just have it longer in the long_name.

**Comment by wwieder** [comment]
@ekluzek and I talked more about this and I agree with him that on the name on history fields would be more instructive and helpful for scientists looking at output.  

For the current BGC these should be: 

- LIT_MET_C, LIT_CEL_C, and LIT_LIG_C that correspond to litter carbon in metabolic, cellulose, and lignin pools (with parallel pools for N). then for soils:
- SOIL_FAST_C, SOIL_SLOW_C, SOIL_PASS_C for active, slow and passive soil C pools.    I'm happy with any abbreviations, underscores, etc that keep this consistent with CTSM naming conventions

Second, as it would be fine to bring this in with #1400, but the CWD work is important for the PPE branch and should be prioritized.  This can go in with another bfb tag.
