### ISSUE TITLE
Not all SCRIPgrid_files required for the mkmapdata.sh are available

### ISSUE THREAD

**Issue by irismuz** [ESCOMP/CTSM#1393]
For example, `SCRIPgrid_0.125x0.125_nomask_*.nc` is not available for download in the repository (https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/lnd/clm2/mappingdata/grids/).
Could you please check the availability of SCRIPgrids specified in `mkmapdata.sh` between line 286 and 295?
```
    grids=(                    \
           "0.5x0.5_nomask"     \
           "0.25x0.25_nomask"   \
           "0.125x0.125_nomask"   \
           "3x3min_nomask" \
           "5x5min_nomask"     \
           "10x10min_nomask"   \
           "0.9x1.25_nomask" \
           "1km-merge-10min_HYDRO1K-merge-nomask" \
          )
```

**Comment by slevisconsulting** [comment]
@irismuz and @billsacks thank you for bringing this to my attention. I just added the 0.125x0.125 file to the repository. 

Sorry for the omission. I had expected this file to have been available due to it's old (2014) time stamp. I will now confirm that the rest of the files are there, too.

**Comment by slevisconsulting** [comment]
As far as I can tell, the remaining files listed in `bld/namelist_files/namelist_defaults_ctsm_tools.xml` for each of the source resolutions listed above are present in the repo.

**Comment by irismuz** [comment]
@slevisconsulting thank you very much.
