### ISSUE TITLE
Max partial pressure of CO2 be should be 1.e-6 rather than 10.e-6 which it is for ci_func_PHS

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1394]
In looking at the changes for Medlyn photosynthesis I noticed a difference between the PHS code and the non-PHS code for calculation of "cs". 

In ci_func_PHS for PHS you have the following for cs_sun (and the same for cs_sha)

``` fortran
       cs_sun = cair - 1.4_r8/gb_mol * an_sun(p,iv) * forc_pbot(c)
       cs_sun = max(cs_sun,10.e-06_r8)
```

While for ci_func for non-PHS you have this...

``` fortran
      cs = cair - 1.4_r8/gb_mol * an(p,iv) * forc_pbot(c)
      cs = max(cs,1.e-06_r8)
```

Note, also that 1.e-6_r8 is used for the copy of the same code in PhotosynthesisHydraulicStress. This is also true of the non-PHS main Photosynthesis subroutine. Which makes me think that 1.e-06 is the correct one to use.

So the constant is 10.e-6 for PHS (in ci_func_PHS) while it's 1.e-6 for non-PHS. Is this intentional? Or should they both be the same? And if so which one?

This is the nature of having code that should be identical, but copied rather than used in one place. It's too easy for things to be slightly modified even unintentionally.

I'm assuming this will make a small difference in the model, but likely hard to tell the difference in climate, but likely larger than roundoff.

@djk2120

**Comment by djk2120** [comment]
Hi Erik,
Agree with you on all fronts. This is clearly a typo and should be 1e-6
throughout. I'll file an issue to keep track of this. I would guess that
this is triggered very seldomly, and won't change the model much at all.

I would really like to unify the two photosynthesis schemes in a future
pull request. I'll add this to the list for that PR. I don't think it needs
immediate attention.

Thanks for letting me know. Nice catch!

**Comment by ekluzek** [comment]
Thanks for that update @djk2120. Good to know. I'll include this as part of an answer changing tag.

I'm glad to hear you are working on unifying photosynthesis. The issue about reducing duplication in Photosynthesis is #139. I have some thoughts on that, that I'll add there.

I did run some of the longer tests in the test suite to see if they change answers and the following did change answers:

ERP_P36x2_Lm13.f10_f10_mg37.IHistClm51Bgc.cheyenne_gnu.clm-monthly
ERP_P36x2_Lm13.f10_f10_mg37.IHistClm51Bgc.cheyenne_intel.clm-monthly
ERS_Ly5_P144x1.f10_f10_mg37.IHistClm51BgcCrop.cheyenne_intel.clm-cropMonthOutput
LCISO_Lm13.f10_f10_mg37.IHistClm51BgcCrop.cheyenne_intel.clm-ciso_monthly

While these ones did not...

SMS_Lm13.f19_g17.I2000Clm51BgcCrop.cheyenne_intel.clm-cropMonthOutput
ERP_P72x2_Lm25.f10_f10_mg37.I2000Clm51BgcCrop.cheyenne_intel.clm-monthly

**Comment by ekluzek** [comment]
So this technically does affect science answers, but it looks like the affect is very small, so I'm not going to mark the changes science label.
