### ISSUE TITLE
remove cprnc.pl and cprnc.ncl; use standard cprnc instead

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#14]
**Bill Sacks < sacks@ucar.edu > - 2013-05-29 12:59:52 -0600**
**Bugzilla Id:** [1716](http://bugz.cgd.ucar.edu/show_bug.cgi?id=1716)
**Bugzilla CC:**  muszala@ucar.edu,  rfisher@ucar.edu, 

My understanding is that cprnc.ncl and its cprnc.pl wrapper exist only because the standard fortran-based cprnc wasn't able to compare files without a time dimension. As of cprnc_130529, this is fixed. So I propose removing these CLM-specific cprnc scripts, and switching testing to use the standard cprnc instead.

Advantages:

(1) no longer need to maintain these scripts

(2) I recently found a problem with the cprnc.ncl script - it doesn't flag files as different if they differ in where there are missing values (see bug 1714). The fortran-based cprnc handles this correctly

(3) The fortran-based cprnc gives you more information about differences than you can get from cprnc.ncl.

(4) Post-processing scripts that look at cprnc output (e.g., summarize_cprnc_diffs) don't work on cprnc.ncl output; so if we switch to using the fortran-based program, these post-processing scripts can be used.

**Comment by ekluzek** [comment]
We've done this, so closing.
