### ISSUE TITLE
Issue with frootc/frootn for C4 crops

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#140]
**Erik Kluzek < erik > - 2016-07-06 14:37:21 -0600**
**Bugzilla Id:** [2330](http://bugz.cgd.ucar.edu/show_bug.cgi?id=2330)
**Bugzilla CC:**  dlawren,  dll,  oleson,  rfisher, 

In clm4_5_9_r184 the following has to be commented out for CROP to work well (otherwise C4 crops don't grow).

``` fortran
+      ! froot C and N
+      ! EBK KO DML: For some reason frootc/frootn can go negative and allowing
+      ! it to be negative is important for C4 crops (otherwise they die) Jun/3/2016
+      call TruncateCandNStates( bounds, filter_soilp, num_soilp, cs%frootc_patch(bounds%begp:bounds%endp),  &
+                                ns%frootn_patch(bounds%begp:bounds%endp), pc(bounds%begp:), pn(bounds%begp:), __LINE__, &
+                                c13=c13cs%frootc_patch, c14=c14cs%frootc_patch,  &
+                                pc13=pc13(bounds%begp:), pc14=pc14(bounds%begp:), allowneg=.true. )
```

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2016-07-29 17:27:25 -0600**

*** Bug 2341 has been marked as a duplicate of this bug. ***

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2016-11-09 14:48:21 -0700**

clm4_5_12_r200 has this workaround put into the code for when running with clm50.

**Comment by ekluzek** [comment]
It's still in the latest code. The call is turned on for clm4_5 (which sets use_nguardrail=F) and off for clm5_0 (which sets use_nguardrail=T).

**Comment by billsacks** [comment]
Feeling from today's ctsm-software meeting: this isn't worth the time to try to figure out.
