### ISSUE TITLE
1-Degree methane finundated stream data is labeled as if it's 2-degree

### ISSUE THREAD

**Issue by mvertens** [ESCOMP/CTSM#1401]
### Brief summary of bug
In namelist_defaults_ctsm.xml - the specification of the finundated stream seems incorrect

### General bug information
In namelist_defaults_ctsm.xml - the specification of the finundated stream seems incorrect

**CTSM version you are using:** ctsm5.1.dev038

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** Any configuration where methane is used (e.g. %Bgc)

### Details of bug
The following is the logic in namelist_defaults_ctsm.xml
```
<finundation_res finundation_method="TWS_inversion">1.9x2.5</finundation_res>
<finundation_res finundation_method="ZWT_inversion">1.9x2.5</finundation_res>

<stream_fldfilename_ch4finundated finundation_method="TWS_inversion" hgrid="1.9x2.5"
>lnd/clm2/paramdata/finundated_inversiondata_0.9x1.25_c170706.nc</stream_fldfilename_ch4finundated>
<stream_fldfilename_ch4finundated finundation_method="ZWT_inversion" hgrid="1.9x2.5"
>lnd/clm2/paramdata/finundated_inversiondata_0.9x1.25_c170706.nc</stream_fldfilename_ch4finundated>
```
In CLMBuildNamelist.pm the following logic is used to parse this:
```
my $finundation_method = remove_leading_and_trailing_quotes($nl->get_value('finundation_method' ));
add_default($opts, $nl_flags->{'inputdata_rootdir'}, $definition, $defaults, $nl, 'finundation_res',
          'finundation_method'=>$finundation_method );
add_default($opts, $nl_flags->{'inputdata_rootdir'}, $definition, $defaults, $nl, 'stream_fldfilename_ch4finundated',
         'finundation_method'=>$finundation_method,
         'finundation_res'=>$nl->get_value('finundation_res') );
add_default($opts, $nl_flags->{'inputdata_rootdir'}, $definition, $defaults, $nl, 'use_aereoxid_prog',
```
So it looks like

1. The only file is for 0.9x1.25 - so the finundation_res_finundation_methods seems wrong (although this variable does not even appear in the namelist_defaults_ctsm.xml file).
2. hgrid="1.9x2.5" is not used

So unless I am not seeing something it seems like all you want in the namelist_defaults_ctsm.xml is
```
<stream_fldfilename_ch4finundated finundation_method="TWS_inversion"
>lnd/clm2/paramdata/finundated_inversiondata_0.9x1.25_c170706.nc</stream_fldfilename_ch4finundated>
<stream_fldfilename_ch4finundated finundation_method="ZWT_inversion"
>lnd/clm2/paramdata/finundated_inversiondata_0.9x1.25_c170706.nc</stream_fldfilename_ch4finundated>
```

### Important details of your setup / configuration so we can reproduce the bug

[Specify anything relevant: the compset, resolution, machine, compiler, any xml or namelist changes, etc. You don't have to repeat anything that you have already noted above.]

### Important output or errors that show the problem

[Fill this in with anything relevant that you haven't already noted; if there is nothing to add, delete this section.]

**Comment by ekluzek** [comment]
OK, it looks like you are correct that this is done in a screwy manner. It labels a 1-degree file as 2-degree, and since there is only one file available the logic might as well be simplified.

As far as I can tell however, a stream_fldfilename_ch4finundated file is always assigned when it's needed to. As a matter of fact if a file weren't assigned the model would abort with an error.

One way I'm examining this is by looking at the 200  BGC namelists that are created from the unit tester framework, and I don't find any that are incorrect. @mvertens let me know if you do find a case that's incorrect, otherwise I'm labelling this as a code cleanup project.
