### ISSUE TITLE
Some PBL schemes are incompatible with WRF-CTSM

### ISSUE THREAD

**Issue by irismuz** [ESCOMP/CTSM#1410]
In the running phase of WRF-CTSM, we have noticed that setting `bl_pbl_physics` and `sf_sfclay_physics` to -1 in `namelist.input` reveals the following error message:

![PBL scheme](https://user-images.githubusercontent.com/63979539/123420301-b1971000-d5bb-11eb-9db2-8841cd67bef2.PNG)

The issue was resolved when these two parameters were set to 1. We would thus kindly appreciate it if there would be an overview of schemes that are compatible with WRF-CTSM.

**Comment by billsacks** [comment]
Unfortunately, with no current support dedicated to WRF-CTSM, we're going to close this as a wontfix.
