### ISSUE TITLE
Don't allow end dates that go beyond the end of available tower data

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1416]
NEON simulations need to end for the last day of available data

**Comment by wwieder** [comment]
this will be a cdeps PR that CTSM can update

**Comment by wwieder** [comment]
@jedwards4b was this resolved with the CDEPs changes you pushed yesterday?

**Comment by jedwards4b** [comment]
@wwieder no, this one has not yet been addressed.
