### ISSUE TITLE
.config_files.xml points to incorrect location for slnd and xlnd

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CTSM#1438]
### Brief summary of bug

Not sure how testing missed this but the toplevel .config_files.xml has incorrect locations for the 
mct slnd and xlnd COMP_ROOT_DIR_LND

### General bug information

**CTSM version you are using:** ctsm5.1.dev049

**Does this bug cause significantly incorrect results in the model's science?**  

**Configurations affected:** [Fill this in if known.]

### Details of bug

[Fill in details here.]

### Important details of your setup / configuration so we can reproduce the bug

[Specify anything relevant: the compset, resolution, machine, compiler, any xml or namelist changes, etc. You don't have to repeat anything that you have already noted above.]

### Important output or errors that show the problem

[Fill this in with anything relevant that you haven't already noted; if there is nothing to add, delete this section.]

**Comment by ekluzek** [comment]
Ugg. This likely is because our CTSM testing only tests cases with CTSM and never SLND or XLND. As such if I understand the problem it's likely not critical to fix for CTSM right away. But, obviously we do need to bring the fix in.
