### ISSUE TITLE
rename NEON files for CLM 

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1442]
To avoid confusion we've asked NEON to change the naming conventions for how files are named.
Paths will be identical as before but now will include site names and either `atm` or `eval`. For example
- `HARV_atm_2018-01.nc` & 
- `HARV_eval_2018-01.nc` 

@jedwards4b will you update this in the NEON compset so `datm_streams.xml` is populated correctly for each site?
@negin513, will you updated this in your visualization scripts?
@ddurden, will you update this on the NEON side and let us know when this is finished. (I'll create an issue on the [NCAR-NEON repo too](https://github.com/NEONScience/NCAR-NEON/issues/45)).

**Comment by wwieder** [comment]
@jedwards4b from our conversation today it sounds like you've modified this in the code you're running? If so, we can close this issue when we create a new tag for the containerized system.

**Comment by jedwards4b** [comment]
It looks like one site, JERC has been renamed, since they also fixed a problem in the data with this rename I am going to rerun the spin-up for this site.

**Comment by wwieder** [comment]
Are scripts for running cases (@jedwards4b) and visualizing results(@negin513 ) now updated to reflect this change in file names being provided by NEON.

**Comment by jedwards4b** [comment]
scripts for running are and are working fine.
