### ISSUE TITLE
Modified neon data: dimensions lsmlat and lsmlon are missing where zbedrock is updated. 

### ISSUE THREAD

**Issue by negin513** [ESCOMP/CTSM#1446]
### Brief summary of bug

For some neon sites where we updated the `zberock` variable, the updated `zbedrock` does not have dimensions `lsmlat` and `lsmlon` which causes some issues. 

 This is where the `zbedrock` gets updated in the script:

https://github.com/ESCOMP/CTSM/blob/84e970fe5125ab97b93e6937afaed4539ef2ac33/tools/contrib/modify_singlept_site_neon.py#L516-L523

I should be able to resolve this issue. 

### General bug information

** CTSM version you are using: ctsm5.1.dev049 

**Configurations affected:** Neon simulations where `zbedrock` is updated, which are the following:
ORNL, CLBJ, HARV, BONA, OAES, TOOL, BARR, HEAL, PUUM, RMNP, SJER

Thanks to @ekluzek for bringing this to my attention.

**Comment by wwieder** [comment]
@negin513 let's address this with #1437 and #1429, but not until after we get the visualization scripts to a good place

**Comment by wwieder** [comment]
Also, given #1429 and this we're likely going to have a bunch of issues with particular sites running with the modified surface datasets.  If this is problematic, are we best just pointing to the original surface datasets for testing?
