### ISSUE TITLE
NEON test fails on cheyenne: unable to download data from server

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1450]
In my last two runs of the test suite, the test `SMS_D_Vnuopc_Mmpi-serial.CLM_USRDAT.I1PtClm51Bgc.cheyenne_intel.clm-default--clm-NEON-NIWO` has failed in the SHAREDLIB_BUILD phase with:

```
WARNING: No .input_data_list files found in dir 'Buildconf'
Using protocol wget with user None and passwd None
Could not connect to repo 'https://s3.data.neonscience.org/neon-ncar/NEON/'
This is most likely either a proxy, or network issue .
Could not connect to repo 'https://s3.data.neonscience.org/neon-ncar/NEON/'
This is most likely either a proxy, or network issue .
ERROR: Could not download NEON data listing file from server'
  File "/glade/work/sacks/ctsm_code/current_branch1/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 821, in _run_catch_exceptions
    return run(test)
  File "/glade/work/sacks/ctsm_code/current_branch1/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 746, in _setup_phase
    expect(cmdstat in [0, TESTS_FAILED_ERR_CODE], "Fatal error in case.cmpgen_namelists: {}".format(output))
  File "/glade/work/sacks/ctsm_code/current_branch1/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 152, in expect
    raise exc_type(msg)
```

Rerunning has gotten past this issue, but I'd like to avoid having flaky tests in the aux_clm test suite, because this lengthens an already-too-long testing process.

If it isn't possible to address the underlying issue (flakiness of the data server?), then maybe we could consider some workaround like having the aux_clm test use some pre-existing file (which could be staged via shell commands in a testmod directory) rather than hitting the server every time we need to run this test – and then having a test in our less-frequently-run clm_science test list that covers the full workflow including downloading from the server.

**Comment by billsacks** [comment]
@jedwards4b or @negin513 - can one of you take this on?

**Comment by ekluzek** [comment]
In my testing I hadn't seen this before. And I'm guessing @jedwards4b didn't either. This was setup this way on purpose so that the data would be the latest possible when using NEON data, especially since the data download is small. But, if this is going to be a persistent problem I see where we might need to do something about it. I would like to hear from NEON what we expect the expected percent daily uptime for NEON data should be. If it's very high and this is an exception I don't know that we need a workaround. 

@wwieder and @danicalombardozzi can you check with the NEON data folks about what the expected uptime of NEON data servers is? And maybe find out what was going on this week for it to be down? It could also be helpful if we know about these downtimes in advance since it's now intwined into our testing.

**Comment by billsacks** [comment]
Okay, from some additional testing, I think I slightly misdiagnosed the problem. I think the actual problem is that the server isn't accessible from the cheyenne compute nodes. If I run case.build and case.submit from the login nodes, it works fine, but I repeatedly get this error when I run the build and submit from the compute nodes (via run_sys_tests or the equivalent of qcmd). (I'm not 100% sure this is the problem. There is a lot of output from the job when I run case.build & case.submit on the compute nodes, and I can't tell for sure what the original source of the error is: see files STDIN.o9680699 and STDIN.e9680699 in `/glade/scratch/sacks/tests_0803-163021ch/SMS_D_Vnuopc_Mmpi-serial.CLM_USRDAT.I1PtClm51Bgc.cheyenne_intel.clm-default--clm-NEON-NIWO.GC.0803-163021ch_int`.)

I see that we already have an identical test on izumi. I feel like it's probably overkill anyway to have two identical tests of this, one on cheyenne and one on izumi – given how unwieldy our test suite is – so I'm going to "solve" this problem by removing the cheyenne test, leaving just the izumi one.

**Comment by ekluzek** [comment]
OK, so this is probably an artifact of cheyenne's recent downtime rather than the NEON servers themselves. I guess it's OK to have just one NEON test in place, although we also want it to work both places.

**Comment by jedwards4b** [comment]
@wwieder right - this works fine if the test is run from the login nodes, but when tests are run from compute nodes we can't reach the neon server to download data.

**Comment by billsacks** [comment]
People might run into this in a non-test case depending on workflow: I think that it could happen if you run the build and/or submit on the compute nodes via something like qcmd. I'm not sure whether that's something people are typically doing. It may be that running preview_namelists first on the login node will prevent the problem from happening – I haven't tested thoroughly.
