### ISSUE TITLE
run_sys_tests with --rerun-existing-failures option gives confusing result when testid doesn't exist

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1454]
### Brief summary of bug

When you give the wrong testid for --rerun-existing-failures, it reports an error that's confusing and not clear what the problem is.

### General bug information

**CTSM version you are using:** ctsm5.1.dev051

**Does this bug cause significantly incorrect results in the model's science?** No
**Configurations affected:** Just running run_sys_tests with --rerun-existing-failures option

### Important output or errors that show the problem

The result it gives looks like this and it isn't obvious what the problem is...

> Traceback (most recent call last):
>   File "./run_sys_tests", line 20, in <module>
>     main(cime_path=cime_path)
>   File "/fs/cgd/data0/erik/ctsm_neon/python/ctsm/run_sys_tests.py", line 76, in main
>     extra_create_test_args=args.extra_create_test_args)
>   File "/fs/cgd/data0/erik/ctsm_neon/python/ctsm/run_sys_tests.py", line 148, in run_sys_tests
>     _record_git_status(testroot, retry_final, dry_run)
>   File "/fs/cgd/data0/erik/ctsm_neon/python/ctsm/run_sys_tests.py", line 453, in _record_git_status
>     with open(git_status_filepath, 'w') as git_status_file:
> FileNotFoundError: [Errno 2] No such file or directory: '/scratch/cluster/erik/tests_ctsm51d52_na/SRCROOT_GIT_STATUS'

**Comment by ekluzek** [comment]
This will be easy to fix, and I'll do it in the next tag.

**Comment by billsacks** [comment]
Thanks @ekluzek . I'll be honest that I didn't put a lot of effort into pretty error reporting of run_sys_tests, instead relying on exceptions with their ugly backtraces for the most part.

As a side note: coming up with a consistent way that we want to do error handling & reporting in the ctsm python scripts would be another good thing to discuss at some point.
