### ISSUE TITLE
Update raw soil-color and LAI datasets

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1463]
@lawrencepj1 has new raw datasets for mksufdata_map to use for soil-color and LAI. We'll bring these in as part of ctsm5.2.

**Comment by wwieder** [comment]
@swensosc noted there's also a new dataset for drip vs. sprinkler irrigation.  What's the best way to keep track of all of these? maybe a new label `update datasets`?

**Comment by billsacks** [comment]
> What's the best way to keep track of all of these? maybe a new label update datasets

I'd suggest a project. I've been trying to use projects for grouping together issues with a similar theme like this, reserving labels for things that describe the characteristics of issues. This keeps labels more stable over time, and projects are nice in that they let you see the status of the various pieces.

**Comment by ekluzek** [comment]
I agree with Bill. I'll go ahead and get a project started and we can review tomorrow.

**Comment by wwieder** [comment]
oh, I already started a project. sorry, should have posted here.  we can delete the redundant one...

**Comment by ekluzek** [comment]
Ill just add to the one you created.

**Comment by billsacks** [comment]
@slevisconsulting will check if this is done.

**Comment by slevisconsulting** [comment]
@lawrencepj1 the new mksurfdata_esmf points to these lai and soil color files. Please let me know if I need to change them:

```
lnd/clm2/rawdata/pftcftdynharv.0.25x0.25.LUH2.histsimyr1850-2015.c20220305/mksrf_lai_ctsm52_histLUH2_2005.c220305.nc
lnd/clm2/rawdata/pftcftdynharv.0.25x0.25.LUH2.histsimyr1850-2015.c20220305/mksrf_soilcolor_ctsm52_histLUH2_2005.c220305.nc
```

For hires_pft='on'
``` lnd/clm2/rawdata/pftcftdynharv.0.05x0.05.LUH2.histsimyr2005.c190116/mksrf_lai_histclm52deg005_earthstatmirca_2005.cdf5.c220228.nc
lnd/clm2/rawdata/pftcftdynharv.0.05x0.05.LUH2.histsimyr2005.c190116/mksrf_soilcolor_histclm52deg005_earthstatmirca_2005.cdf5.c220228.nc
```

**Comment by slevisconsulting** [comment]
I see no objections to the lai and soilcolor datasets that mksurfdata_esmf points to, so I will close this issue.

Discussion (in this issue) of new irrigation data continues in #565 .
