### ISSUE TITLE
Change FATES to run with use_nitrif_dentrif TRUE

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1465]
By default FATES is being run with use_nitrif_dentrif=FALSE, we'd like to change this so that use_nitrif_dentrif is hardcoded to true (see #1356). This does mean answers will change for FATES cases.

@rgknox @ckoven @rosiealice do you need to do any testing to ensure that FATES simulations are fine to run with use_nitrif_dentrif to TRUE?

**Comment by ckoven** [comment]
@ekluzek it shouldn't matter, since we haven't been using FATES with the N cycle yet. So yes it should be fine.

**Comment by rgknox** [comment]
agreed
