### ISSUE TITLE
decomp_depth_efolding appears (with the same value) in the namelist and the params files; the model ends up using the one from the namelist

### ISSUE THREAD

**Issue by slevisconsulting** [ESCOMP/CTSM#1473]
### Brief summary of bug
`decomp_depth_efolding` appears (with the same value) in the namelist and the params files; the model ends up using the one from the namelist. I report this as a bug because users may wrongly believe that they can change the value of this parameter by updating the params files.

### General bug information

**CTSM version you are using:**
ctsm5.1.dev053-48-g1c1a9451

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]
No, unless user thought that they were modifying the value via the params files.

**Configurations affected:**
Configurations using vertically resolved DecompCascadeBGC or DecompCascadeCN (deprecated) for below-ground decomposition.

### Details of bug
Summary gives enough detail.
To correct, @slevisconsulting will remove `decomp_depth_efolding` from the namelist.

**Comment by wwieder** [comment]
@ekluzek, @olyson, or @djk2120 is this corrected on the PPE branch?

**Comment by djk2120** [comment]
We didn't change anything. I just switched to using the namelist for
perturbations instead of the paramfile.

**Comment by dlawrenncar** [comment]
Seems like we should fix this somehow to avoid future errors.  Maybe the
best in the long run would be to remove teh namelist option and use what's
on parameter file, to be more consistent with what we do with most
parameters.

**Comment by wwieder** [comment]
@olyson can you update this on the PPE branch, then we can merge to master?

**Comment by olyson** [comment]
@ekluzek how would you like me to handle this?  Branch off of latest master? I think you've been managing the PPE branch.

**Comment by wwieder** [comment]
oh,  maybe we can just make the change on main, that's where the change actually could come it.  it should be a simple bfb change?

**Comment by olyson** [comment]
It should be bfb.  Looking at the issue, it seemed like Sam had already done this on the mimics branch?  When does that come to main?

**Comment by dlawrenncar** [comment]
If it is on mimics branch already, seems like we can just wait and let this
get sorted with mimics comes on.

**Comment by wwieder** [comment]
Makes sense, without a real need to push for 'release' of CTSM5.1 we can let this get fixed with #1318
