### ISSUE TITLE
Missing images in the CLM5 user's guide and technical note

### ISSUE THREAD

**Issue by djk2120** [ESCOMP/CTSM#1486]
### Brief summary of bug

Images seem to be missing from the online versions of the CLM5 user's guide and technical note. See for example: [bgc spinup](https://escomp.github.io/ctsm-docs/versions/release-clm5.0/html/users_guide/running-special-cases/Spinning-up-the-biogeochemistry-BGC-spinup.html)

**Comment by billsacks** [comment]
@slevisconsulting from a quick look through the history, it looks like this may have gotten broken during your recent documentation update. Would you be willing to take a look at this? My first thought is that something is wrong with your setup of git lfs (large file support) as described in https://github.com/ESCOMP/CTSM/wiki/Directions-for-editing-CLM-documentation-on-github-and-sphinx . You could test that by manually pulling down the image files as described in https://github.com/ESCOMP/CTSM/wiki/Directions-for-editing-CLM-documentation-on-github-and-sphinx#management-of-image-files . Once you get that working, you should probably do a clean build of both the master and release-clm5.0 versions of the documentation, from their appropriate branches.

Let me know if you want help.

**Comment by slevisconsulting** [comment]
@billsacks 
I am trying to get things to work with Docker on my Windows10 laptop, but I'm stuck trying to run
./manage_externals/checkout_externals -o
which currently does nothing.

@olyson 
Bill tells me that you have managed to get it all to work on your laptop, so I'm copying you here in case you have suggestions.

**Comment by slevisconsulting** [comment]
@billsacks I know you mentioned copying the python executable to python3.

I believe that my python came with an installation of conda or miniconda. When I type python at the prompt and hit tab once I get python.exe and when I hit tab a second time I get python3.exe.

But maybe I need to download a separate python for windows that will appear in `C:\Users\USERNAME\AppData\Local\Programs`?

**Comment by olyson** [comment]
I downloaded a separate python for windows that shows up in:

C:\Users\oleson\AppData\Local\Programs\Python\Python39

**Comment by slevisconsulting** [comment]
Thanks @olyson 
checkout_externals now worked, when I typed py in front:
`py .\manage_externals\checkout_externals -o`
:-)

Next I activated bash (any other way I tried to run `./build_docs -b ~/ctsm-repos/ctsm-docs -d` failed)
but I get `': No such file or directory`
:-(

@billsacks 
at this point I'm stopping this exploration because I am burning contract hours...

**Comment by olyson** [comment]
Using bash didn't work for me...so I use the "Relying more heavily on the Docker container" approach.
Here are the step-by-step instructions that work for me:

USE windows powershell.
cd C:/Users/oleson/
mkdir ~/ctsm-repos
cd ctsm-repos/
git clone https://github.com/ESCOMP/CTSM.git ./ctsm_masterdoc
cd ctsm_masterdoc
git lfs install
python ./manage_externals/checkout_externals –o
cd ..
git clone https://github.com/ESCOMP/ctsm-docs.git
cd ~/ctsm-repos/ctsm-docs
git checkout -- .
git pull

Start the docker desktop from the windows start icon.

cd ~/ctsm-repos/ctsm_masterdoc/doc

docker run -i -t --rm -v ${HOME}:/home/user/mounted_home escomp/base

cd /home/user/mounted_home/ctsm-repos/ctsm_masterdoc/doc

./build_docs -b /home/user/mounted_home/ctsm-repos/ctsm-docs/versions/master –c

**Comment by slevisconsulting** [comment]
Thanks @olyson I will give it a try tomorrow.

**Comment by slevisconsulting** [comment]
The good news is that I got all the way to the final command.

> ./build_docs -b /home/user/mounted_home/ctsm-repos/ctsm-docs/versions/master –c

The bad news is that the last command gives me:
`env: ‘bash\r’: No such file or directory`
Something in my environment is still different. I'm open to further suggestions...

**Comment by billsacks** [comment]
@slevisconsulting - From a quick google search, I think this has to do with Windows vs Unix line endings - e.g., see https://pauledenburg.com/docker-on-windows-usr-bin-env-bashr-no-such-file-or-directory/ and https://stackoverflow.com/questions/29045140/env-bash-r-no-such-file-or-directory/29045187 . Those suggest running `git config --global core.autocrlf false` before doing the git clone, but I think that could cause some other problems. My guess is that an alternative solution that would also fix the problem would be to do the git clone (and all of the other git commands) from within the docker environment. That is, do the `docker run` command as one of the first steps, then do all of the other steps (including git stuff) from within the docker environment. I'm not 100% sure if that will work or if it may cause other problems, though.

If this is burning too much of your time, though, then one of us can build the documentation for you, at least for now.

**Comment by olyson** [comment]
Yes, I agree with Bill about the line endings. I ran across this when I was trying to build using the recommended method.
You could try:

vim build_docs +"set ff=unix" +wq

and then try the build.  I didn't think it was needed though for the "docker-centric" build method....

**Comment by slevisconsulting** [comment]
Keith's suggestion gave a different error and seems to have made it a bit further along:
```
Running: doc-builder/build_docs --fetch-images -b /home/user/mounted_home/ctsm-repos/ctsm-docs/versions/master/ -c
env: ‘python3\r’: No such file or directory
```

Bill's suggestion worked, and I'm currently building masterdoc. If all goes well, I will repeat the process for release-clm5.0.

Thank you for your help @billsacks and @olyson ! I will write out my process as well as I can in the next post.

**Comment by slevisconsulting** [comment]
I downloaded Docker for Windows following relevant instructions in the wiki.
I downloaded Python for Windows.
In `C:\Users\Sam and Suki\AppData\Local\Programs\Python\Python39` I copied `python` to `python3` as recommended in the wiki.
I may have downloaded one or two other things, but I've lost track so maybe not, and they may have been unnecessary in retrospect.
I already had git for Windows.
I already had a Powershell application (by Anaconda, miniconda).

Sequence of commands:
(base) PS C:\Users\Sam and Suki> mkdir ctsm-repos
(base) PS C:\Users\Sam and Suki> cd ctsm-repos
(base) PS C:\Users\Sam and Suki\ctsm-repos> docker run -i -t --rm -v ${HOME}:/home/user/mounted_home escomp/base
[user@escomp ~]$ cd mounted_home/ctsm-repos
[user@escomp ctsm-repos]$ git clone https://github.com/ESCOMP/CTSM.git ctsm_masterdoc
[user@escomp ctsm-repos]$ cd ctsm_masterdoc/
[user@escomp ctsm_masterdoc]$ git lfs install
[user@escomp ctsm_masterdoc]$ python ./manage_externals/checkout_externals -o
[user@escomp ctsm_masterdoc]$ cd ..
[user@escomp ctsm-repos]$ git clone https://github.com/ESCOMP/ctsm-docs.git
[user@escomp ctsm-repos]$ cd ctsm-docs
[user@escomp ctsm-docs]$ git checkout -- .
[user@escomp ctsm-docs]$ git pull
[user@escomp ctsm-docs]$ cd ../ctsm_masterdoc/doc/
[user@escomp doc]$ ./build_docs -b /home/user/mounted_home/ctsm-repos/ctsm-docs/versions/master/ -c

**Comment by slevisconsulting** [comment]
To repeat for release-clm5.0, I stayed in the already running docker container. Some of these commands may have been redundant, but I'm repeating to take no chances:
[user@escomp ctsm-repos]$ cd ctsm_masterdoc/
[user@escomp ctsm_masterdoc]$ git checkout -b release-clm5.0 escomp/release-clm5.0
[user@escomp ctsm_masterdoc]$ git lfs install
[user@escomp ctsm_masterdoc]$ python ./manage_externals/checkout_externals -o
[user@escomp ctsm_masterdoc]$ cd ../ctsm-docs/
[user@escomp ctsm-docs]$ git checkout -- .
[user@escomp ctsm-docs]$ git pull
[user@escomp ctsm-docs]$ cd ../ctsm_masterdoc/doc/
[user@escomp doc]$ ./build_docs -b /home/user/mounted_home/ctsm-repos/ctsm-docs/versions/release-clm5.0/ -c

**Comment by slevisconsulting** [comment]
For completeness, here are my steps for committing and pushing:

After confirming locally (on my laptop) that my changes worked, I committed and pushed.
[user@escomp doc]$ cd ../../ctsm-docs/
[user@escomp ctsm-docs]$ git status
[user@escomp ctsm-docs]$ git add versions
[user@escomp ctsm-docs]$ git status
Before committing from here the first time, I was instructed to run the following two lines:
[user@escomp ctsm-docs]$ git config --global user.email "my@email.address"
[user@escomp ctsm-docs]$ git config --global user.name "My Name"
[user@escomp ctsm-docs]$ git commit -m 'Explained commit with short msg'
[user@escomp ctsm-docs]$ git status
[user@escomp ctsm-docs]$ git push

**Comment by billsacks** [comment]
@slevisconsulting I'm glad you got things working, and thanks a lot for writing this up.

Just for future reference: I think that, with how heavily you relied on the Docker environment, you probably didn't need to install python (or really anything else: all you should have needed is whatever was needed to run the Docker container).

@slevisconsulting and @olyson - I have a hard time knowing what's useful to include in the wiki directions. If either of you feel that it's worth including some of Sam's directions in https://github.com/ESCOMP/CTSM/wiki/Directions-for-editing-CLM-documentation-on-github-and-sphinx – along with the general direction to rely more heavily on Docker if building the docs on Windows – then would you be willing to update the wiki page accordingly?

I'm going to close this issue, because it seems like the original issue here is now resolved.
