### ISSUE TITLE
Remove `all_soil_patches` filter and use and filter_inactive_and_active(nc)%soilp in it's place

### ISSUE THREAD

**Issue by glemieux** [ESCOMP/CTSM#1488]
In PR #1182, we introduced an `all_soils_patch` filter input for the `SatellitePhenology` subroutine that is identical to the `soilp` filter with the exception that the `all_soils_patch` does not include a check on the patch being `active` or the `include_inactive` flag.  

`soilp`:
https://github.com/ESCOMP/CTSM/blob/fdf5ef1618b0eadae23b0cf66b4acf64a5193cd5/src/main/filterMod.F90#L384-L394

When trying to utilize the `soilp` filter however, the science results diverge from the expectation.  I'd like to discuss how the filters work in more detail and determine if I'm using them correctly, in particular, whether or not I was appropriately utilizing the `include_inactive` flag to mimic what is desired for `all_soils_patches`.  Tagging @rosiealice and @ekluzek.  

Initial discussion: https://github.com/ESCOMP/CTSM/pull/1182#discussion_r710780938

This new filter should be identical to the filter_inactive_and_active(nc)%soilp and so we should be able to remove it.

**Comment by billsacks** [comment]
I don't think this addresses your main question, but from my read of the code you added, it was unnecessary: We already have two sets of filters, the standard `filter(nc)%FOO` and the less-commonly-used `filter_inactive_and_active(nc)%FOO` for any given filter `FOO`. It looks like what you did is to introduce a new `all_soil_patches` filter (which will be present in both of these filter groups) that just replicates what is already in `filter_inactive_and_active(nc)%soilp`. So, as a first step, I'd suggest doing away with your new filter and just using the existing `filter_inactive_and_active(nc)%soilp`; based on my read of the code, the results should be identical.

(I know this is a bit confusing and not intuitive.)

**Comment by ekluzek** [comment]
Yes, that's my read of the code as well, that the new filter is unnecessary, because you should get identical answers with filter_inactive_and_active(nc)%soilp. If you dont' both @billsacks and I are confused. But, that should be the first thing that's done.

**Comment by ekluzek** [comment]
The second thing is to evaluate why you need to run over the inactive points. It's a little surprising to me that you do, but that might be correct and there's some subtlety that I'm missing. But, if that is the case we should make sure we understand why, make sure it's correct, and add some comments to the code that explain it.

**Comment by glemieux** [comment]
> Yes, that's my read of the code as well, that the new filter is unnecessary, because you should get identical answers with filter_inactive_and_active(nc)%soilp. If you dont' both @billsacks and I are confused

Yeah, that what I'm confused on too.  Here's the results of the SatellitePhenology testmod during the ERS regression test for the two different filters.  The `all_soil_patch` is on the left, the `soilp` filter is in the middle and the difference is on the right:

![Screenshot from 2021-09-17 12-57-44](https://user-images.githubusercontent.com/7565064/133846883-a633fd27-c700-467a-8c1e-e68b7910b53a.png)

If I run with the `nolakep` filter and do a comparison against the `soilp` I get b4b between the two which also seems weird.  Is it user error; am I setting this up wrong?

![Screenshot from 2021-09-17 13-13-22](https://user-images.githubusercontent.com/7565064/133848189-6a079f92-7b2f-4709-a273-ac6ef037c846.png)

**Comment by glemieux** [comment]
My jupyter notebook for this comparison is here: https://github.com/glemieux/fates-jupyter/blob/main/spmode/spmode-ERS-visualization.ipynb

**Comment by ekluzek** [comment]
@glemieux there are two soilp filters, I'm assuming the above results are with the filter one and NOT the filter_inactive_and_active one. If it is with the later one, then both @billsacks and I are confused. So we really need to look at your code you used to run this. Do you have the two code bases around still somewhere?

**Comment by rosiealice** [comment]
Those results do look confusing @glemieux . Just to get @ekluzek up to speed on the weird need to do this loop for so-called inactive points. What FATES does as standard, when reporting back to the HLN, is group all of it's active points together at the beginning, as  say .
1, 1, 1, 0, 0, 0, 0
but in the HLM, we get info on the SP drivers in the native HLM PFT space, say
0, 1, 0, 0, 1, 0, 1
If we thus only update the SP TLAI, HTOP and TSAI for the active points, we only do the first three of these, and thus only one of the PFTs, and thus the second a d third pft remain at there initial values. 

A very slightly better filter would only update the points with actual area/Lai present, but this is only for one loop and so probably isn't worth it from a computing cost perspective. 

A different solution would be to report FATES-SP results in the native HLM form (and not put them in the first three points on the array). But that's likely more work. Maybe?

One thing I was going to do was play with the all_soik_pstches filter a bit to see whether one particular PFT triggered the restart bug but I've been at a meeting...

**Comment by glemieux** [comment]
> So we really need to look at your code you used to run this. Do you have the two code bases around still somewhere?

I don't, but I'll create and push branches to my personal fork when I double check this.

**Comment by billsacks** [comment]
Regarding no difference between using soilp and nolakep: I'm not too surprised by this myself. I can't tell why SatellitePhenology was ever set up to use nolakep: at a glance it seems like it should be sufficient to just run it over the soil filter. But maybe I'm missing something that is making you feel surprised about this?

**Comment by ekluzek** [comment]
@rosiealice awesome thanks for that description. I think I see why you need to run over inactive and active now. So I'd like to see that explanation in the code so we don't forget it.

The other part is just that the new filter should be identical to the filter_inactive_and_active@soilp one so we should be able to remove the new one and use that one without a change in answers.

**Comment by glemieux** [comment]
@billsacks that's good to hear.  No my expectation was not very sophsticated; I just compared the code of the two filters and saw that they are populating the filter with a different logical case and assumed that this should result in non-b4b comparisons.  I didn't actively compare the filters during the runs (yet).

**Comment by glemieux** [comment]
> The other part is just that the new filter should be identical to the filter_inactive_and_active@soilp one so we should be able to remove the new one and use that one without a change in answers.

Ah, ok, so here's where I think I'm making the mistake.  I had missed in filterMod description that I need to use the `filter_inactive_and_active` type as the necessary type to pass to include everything.  I couldn't figure out how `.or. include_inactive` was been exercised in the filter loops.  I had simply been calling the `filter%soilp` in the input call to `SatellitePhenology`.  I'll give this a shot.

**Comment by glemieux** [comment]
Good lord, I totally missed the fact that you explicitly wrote out the call in both the change of the title of this issue.  I guess I need more coffee?  <facepalm>

**Comment by ekluzek** [comment]
It's a Friday after a long week. :-) 

And to be fair since you created this issue you might have missed some of the changes that I made to it. But, feel free to have more coffee!
