### ISSUE TITLE
Run generic single point

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1490]
We need to streamline the workflow for running single point cases with nuopc.

Erik suggested that `subset_data.py` creates a `usermods_dirs` that will be used when creating a new case.

This will include: 
- `user_nl_clm` that points to the newly created surface data
- `shell_commands` with .xml changes
- Populates the `user_nl_datm_stream` file with datm flies that were created and handles <taxmode>,  <tInterpAlgo>, etc for each stream
  - *NOTE* currently this is just called `datm.stream.xml`, but the way to change settings will be improved in an upcoming cdeps tag (the neon UI PR #1467 brings this capability in)
-

**Comment by ekluzek** [comment]
Some overlap with #1565

**Comment by ekluzek** [comment]
One thing we realized with this is that we'd like for the user-mod directory that's created to be as machine independent as possible. This means there should be one a few xmlsettings that set the overall path to the files in the directory created. The paths  for the files are going to be machine dependent by the machine that created them.

**Comment by adrifoster** [comment]
@ekluzek, @billsacks, @negin513 and I just met about this and the plan is to create a new xml variable `CLM_USRDAT_DIR` which users can set as the directory for their subset files (surface data, landuse, datm). This will be set in the `shell_commands` file by `subset_data` to the full path to its current location, but users can update this line in `shell_commands` if they do move the directory with the subset data.

> One thing we realized with this is that we'd like for the user-mod directory that's created to be as machine independent as possible. This means there should be one a few xmlsettings that set the overall path to the files in the directory created. The paths for the files are going to be machine dependent by the machine that created them.

**Comment by wwieder** [comment]
@ekluzek you added next to this, but I think we have a working example with[ this tutorial example](https://github.com/NCAR/CTSM-Tutorial-2022/blob/main/notebooks/Day2a_GenericSinglePoint.ipynb). Since I think this meets the definition of done, I'll close this issue
