### ISSUE TITLE
Need to update LILAC build process to use cmake macros instead of config_compilers.xml

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1492]
If I understand https://github.com/ESMCI/cime/pull/4093 correctly, the LILAC build on a user-defined machine may stop working out of the box once that CIME PR is merged (though it may continue to work for some time depending on how backwards compatibility is implemented). To keep things working, rather than filling out a config_compilers.xml template, we'll instead need to fill out a cmake macros file.

Blocked: depends on https://github.com/ESMCI/cime/pull/4093

**Comment by billsacks** [comment]
ESMCI/cime#4093 has been merged, so this can come in when we do a cime update to that version.

**Comment by ekluzek** [comment]
This comes with cime6.0.10 and the build for the LILACSMOKE test does break with cime6.0.11.

**Comment by ekluzek** [comment]
Here's a log of the error in the atm_driver.bldlog

```
2021-11-08 20:38:37: MODEL_BUILD FAILED for test 'LILACSMOKE_D_Ld2.f10_f10_mg37.I2000Ctsm50NwpSpAsRs.cheyenne_intel.clm-lilac'.
Command: ./case.build --model-only
Output: WARNING: Found difference in test STOP_N: case: 2 original value 5
Setting resource.RLIMIT_STACK to -1 from (-1, -1)
Building test for LILACSMOKE in directory /glade/scratch/erik/tests_ctsm51d62acl/LILACSMOKE_D_Ld2.f10_f10_mg37.I2000Ctsm50NwpSpAsRs.cheyenne_intel.clm-lilac.GC.ctsm51d62acl_int
ERROR: Command: 'make COMPILER=intel DEBUG=TRUE CTSM_MKFILE=/glade/scratch/erik/tests_ctsm51d62acl/LILACSMOKE_D_Ld2.f10_f10_mg37.I2000Ctsm50NwpSpAsRs.cheyenne_intel.clm-lilac.GC.ctsm51d62acl_int/lilac_build/ctsm.mk atm_driver' failed with error 'See /glade/scratch/erik/tests_ctsm51d62acl/LILACSMOKE_D_Ld2.f10_f10_mg37.I2000Ctsm50NwpSpAsRs.cheyenne_intel.clm-lilac.GC.ctsm51d62acl_int/lilac_atm_driver/bld/atm_driver.bldlog' from dir '/glade/scratch/erik/tests_ctsm51d62acl/LILACSMOKE_D_Ld2.f10_f10_mg37.I2000Ctsm50NwpSpAsRs.cheyenne_intel.clm-lilac.GC.ctsm51d62acl_int/lilac_atm_driver/bld'

 ---------------------------------------------------
tests_ctsm51d62acl/LILACSMOKE_D_Ld2.f10_f10_mg37.I2000Ctsm50NwpSpAsRs.cheyenne_intel.clm-lilac.GC.ctsm51d62acl_int> cat /glade/scratch/erik/tests_ctsm51d62acl/LILACSMOKE_D_Ld2.f10_f10_mg37.I2000Ctsm50NwpSpAsRs.cheyenne_intel.clm-lilac.GC.ctsm51d62acl_int/lilac_atm_driver/bld/atm_driver.bldlog 
Makefile:19: Macros.make: No such file or directory
make: *** No rule to make target 'Macros.make'.  Stop.
```

**Comment by billsacks** [comment]
I'll start working on this.

**Comment by billsacks** [comment]
FYI, the error above that @ekluzek ran into is somewhat separate from the initial issue I foresaw, though probably related: this error in the LILACSMOKE test arises because a Macros.make file is no longer generated in the case directory. I'll work on fixing that, too.

**Comment by billsacks** [comment]
The issue @ekluzek raised is fixed in https://github.com/ekluzek/CTSM/pull/2 . I'll work on the initial issue with a user-defined machine next.
