### ISSUE TITLE
Modifying parameter files

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1510]
I'd suspect there's a bit of a cottage industry with tools to modify CTSM parameter files.  Is this something that we should more formally support or provide tools for?  This could be basic scripts in `tools/contrib` where we start by collecting example scripts that provide basic functionality?  Maybe this already exists and I'm just unaware?  More likely I'd suspect @olyson, @ekluzek, @billsacks, @slevisconsulting, @swensosc, @rosiealice, @djk2120 or others have lots of examples around? Should any of these be curated (even informally)?

The second part of this question is what's motivating the broader discussion.  Specifically, I'd like to create a duplicate arctic C3 grasses for pft 12 & 13 grasses that are all based on the same parameterization, but that differ in some luna/phs/or stomatal conductance parameters to represent vegetation that is more resource acquisitive vs. conservative.  What tools do we already have to to start thinking about this on the technical side?

**Comment by djk2120** [comment]
two examples here: https://github.com/djk2120/ppe_tools/tree/main/params

modify_params.ipynb is in line with what you've mentioned

ensemble.ipynb is more involved, and is specifically catered to generating
ensembles

**Comment by wwieder** [comment]
@djk2120 I noticed you had a comment in your script that xarray didn't write out .nc files correctly. This is a bummer, now that I have a script that overwrites parameters as I want them for simulations at Niwot.  But that can't be read by the model 

```
Attempting to read PFT physiological data .....
 (GETFIL): attempting to find local file
 ctsm51_params.c210803.NIWO_critDay13h_c3ArcticMods.nc
 (GETFIL): failed getting file from full path:
 /glade/work/wwieder/modified_inputs/NEON/ctsm51_params.c210803.NIWO_critDay13h_c3ArcticMods.nc
```

I wonder if others can make suggestions for a workaround that would let me use this .nc file, or the script that produced it, which can be found here.
https://github.com/wwieder/NWT_CLM/blob/master/notebooks/modifyParameters.ipynb

Thanks in advance.
Will

**Comment by djk2120** [comment]
Not sure of a solution, per se, or if the bug I experienced is still an
issue. I can check.
My workaround was to use the NetCDF4 package to write the files.

But I would double-check your problem, because that error looks like it
can't find the file, which is different from what I was describing.

**Comment by djk2120** [comment]
I.e. I can't stat that file, which means it was never written to that path.
Whereas my files would write, but were somehow corrupted according to CLM.

**Comment by ekluzek** [comment]
@wwieder at least one of your files in that directory was in NetCDF-4 format, which CESM can't use. So you need to convert them to a different format. One way to do that is to use nccopy to change the format to HDF-5 for example

So for example...

nccopy -k 5 ctsm51_params.c210803.NIWO_critDay13h_fastOnset_c3ArcticMods.nc **ctsm51_params.c210803.NIWO_critDay13h_fastOnset_c3ArcticMods_cdf5.nc

But, most likely in your script that you create the file you just need to change the format of the output file. You should be able to do that on the open statement.

**Comment by djk2120** [comment]
It looks like you're missing "fastOnset" in the path name in your
user_nl_clm

**Comment by wwieder** [comment]
Thanks for your suggestions @djk2120 and @ekluzek. Sorry for some of the confusion. Almost as soon as I posted my question I realized I wasn't pointing to the right file in my user_nl_clm and edited my posting (but you don't get updates on that...).

As far as I can tell the NetCDF-4 format doesn't seem to be an issue, as the model is currently running with the correct file.  Is that surprising, Erik?  All of this is qualified by saying I haven't looked at any results to see if they are sensible... more on that tomorrow.

**Comment by rgknox** [comment]
> I think for my purposes, the tools from this script in FATES may be particularly helpful, as for now I just want to make all pfts
> different flavors of arctic C3 grasses. @rgknox, Am I correct in understanding that this script overwrites all pft-specific values
> with ones from a PFT that a user defines? If so, I wonder how hard it would be to adapt this to a CLM parameter file for big 
> leaf runs?

@wwieder, the script you mention only overwrites the pft of interest, it will not overwrite all pfts with the same value.

**Comment by billsacks** [comment]
> As far as I can tell the NetCDF-4 format doesn't seem to be an issue

NetCDF4-formatted files work on cheyenne, we just avoid adding them to inputdata because they don't work on some CESM-supported systems.
