### ISSUE TITLE
ERROR in UrbanTimeVarType.F90 at line 294

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CTSM#1512]
### Brief summary of bug
Error in UrbanTimeVarType apparently pe-layout dependant.  

### General bug information
On cesm master running test PFS.f09_g17.B1850.cheyenne_intel with pelayout:

Comp  NTASKS  NTHRDS  ROOTPE PSTRIDE
CPL :   1800/     1;      0      1
ATM :   1800/     1;      0      1
LND :    900/     1;      0      1
ICE :    756/     1;   1044      1
OCN :    360/     1;   1800      1
ROF :    900/     1;      0      1
GLC :     36/     1;      0      1
WAV :    144/     1;    900      1
ESP :      1/     1;      0      1
ESMF_AWARE_THREADING is False
ROOTPE is with respect to 36.0 tasks per node

**CTSM version you are using:**  ctsm5.1.dev053

**Does this bug cause significantly incorrect results in the model's science?** Yes

**Configurations affected:** 
f09 at I1850 for Clm50 with 900 tasks?

### Details of bug

Something to do with 900 tasks for CLM at f09?

### Important output or errors that show the problem

```
(shr_strdata_readstrm) reading file lb: /glade/p/cesmdata/cseg/inputdata/lnd/clm2/urbandata/CLM50_tbuildmax_Oleson_2016_0.9x1.25_simyr1849-2106_c160923.nc       2
(shr_strdata_readstrm) reading file ub: /glade/p/cesmdata/cseg/inputdata/lnd/clm2/urbandata/CLM50_tbuildmax_Oleson_2016_0.9x1.25_simyr1849-2106_c160923.nc       2
 ERROR: no valid urban data for g=           11
 landunit type:              8
 urban_valid:      T
 t_building_max:    0.000000000000000E+000
iam = 0: local  landunit index = 38
iam = 0: global landunit index = 18842
iam = 0: global gridcell index = 8641
iam = 0: gridcell longitude    =  321.2500000
iam = 0: gridcell latitude     =   -4.2408377
iam = 0: landunit type         = 8
 ENDRUN:
 ERROR: ERROR in UrbanTimeVarType.F90 at line 294
```

**Comment by billsacks** [comment]
Thanks for reporting this, @jedwards4b . Did you observe this working correctly with a different PE layout?

**Comment by jedwards4b** [comment]
Yes I ran several times with NTASKS_LND values 360,392,468 without issue.

**Comment by billsacks** [comment]
I also just ran that test and a number of variations:

```
PFS_Ld20.f09_g17.I2000Clm50BgcCrop.cheyenne_intel
PFS_P900_Ld20.f09_g17.I2000Clm50BgcCrop.cheyenne_intel
PFS_P900_Ld20.f09_f09_mg17.I2000Clm50BgcCrop.cheyenne_intel
PFS_P900_Ld20.f09_f09_mg17.I1850Clm50BgcCrop.cheyenne_intel
SMS_P900.f09_f09_mg17.I1850Clm50BgcCrop.cheyenne_intel
```

and they all passed for me out of ctsm5.1.dev054 with two different sets of externals:

(1) Externals I used for testing a month ago:

```
    ./cime
        clean sandbox, on cime6.0.8
    ./components/cdeps
        clean sandbox, on cdeps0.12.21
    ./components/cdeps/fox
        clean sandbox, on 4.1.2.1
    ./components/cdeps/share/genf90
        clean sandbox, on genf90_200608
    ./components/cism
        clean sandbox, on cismwrap_2_1_88
    ./components/cism/source_cism
        clean sandbox, on cism_main_2.01.004
    ./components/cmeps
        clean sandbox, on cmeps0.13.25
    ./components/cpl7
        clean sandbox, on cpl7.0.5
    ./components/mizuRoute
        clean sandbox, on 34723c2e4df7caa16812770f8d53ebc83fa22360
    ./components/mosart
        clean sandbox, on mosart1_0_43
    ./components/rtm
        clean sandbox, on rtm1_0_77
e-o ./doc/doc-builder
        -, not checked out --> v1.0.5
    ./libraries/mct
        clean sandbox, on MCT_2.11.0
    ./libraries/parallelio
        clean sandbox, on pio2_5_4
    ./share
        clean sandbox, on share1.0.8
    ./src/fates
        clean sandbox, on sci.1.46.2_api.16.1.0
    ./tools/site_and_regional/PTCLM
        clean sandbox, on PTCLM2_20210810
```

(2) Externals in current cesm master:

```
    ./cime
        clean sandbox, on cime6.0.8
    ./components/cdeps
        clean sandbox, on cdeps0.12.21
    ./components/cdeps/fox
        clean sandbox, on 4.1.2.1
    ./components/cdeps/share/genf90
        clean sandbox, on genf90_200608
    ./components/cism
        clean sandbox, on cismwrap_2_1_88
    ./components/cism/source_cism
        clean sandbox, on cism_main_2.01.004
    ./components/cmeps
        clean sandbox, on cmeps0.13.25
    ./components/cpl7
        clean sandbox, on cpl7.0.5
    ./components/mizuRoute
        clean sandbox, on 34723c2e4df7caa16812770f8d53ebc83fa22360
    ./components/mosart
        clean sandbox, on mosart1_0_43
    ./components/rtm
        clean sandbox, on rtm1_0_77
e-o ./doc/doc-builder
        -, not checked out --> v1.0.5
    ./libraries/mct
        clean sandbox, on MCT_2.11.0
    ./libraries/parallelio
        clean sandbox, on pio2_5_4
    ./share
        clean sandbox, on share1.0.8
    ./src/fates
        clean sandbox, on sci.1.46.2_api.16.1.0
    ./tools/site_and_regional/PTCLM
        clean sandbox, on PTCLM2_20210810
```

I think these are slightly different versions from what @jedwards4b was testing with: It looks like (a) his externals use ctsm5.1.dev053 instead of dev054, and (b) some of his externals are updated beyond what's currently in cesm master.

**Comment by jedwards4b** [comment]
Why are you adding _Ld20 to your PFS tests?  That's the default.

**Comment by jedwards4b** [comment]
I ran test SMS_Vnuopc_P900.f09_f09_mg17.I1850Clm50BgcCrop.cheyenne_intel using  
ctsm5.1.dev057 and it works so I think that @billsacks is correct and I messed up something in my sandbox.

**Comment by billsacks** [comment]
I just realized that I made a copy/paste error in listing the externals in part (2) of https://github.com/ESCOMP/CTSM/issues/1512#issuecomment-938183565 - I have fixed them.

**Comment by jedwards4b** [comment]
I had a mismatch between the ctsm and the fates version.

**Comment by billsacks** [comment]
Okay, thanks. So can we close this ctsm issue @jedwards4b ?
