### ISSUE TITLE
Inefficient and confusing looping structures in UrbanTimeVarType.F90

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1514]
In subroutine urbantv_interp in UrbanTimeVarType.F90, there are a few inefficient and confusing looping structures:

(1) The retrieval of ig here:

https://github.com/ESCOMP/CTSM/blob/3dcbc7499a57904750a994672fc36b4221b9def5/src/cpl/share_esmf/UrbanTimeVarType.F90#L255-L259

This could simply set `ig = lun%gridcell(l) - bounds%begg + 1`, avoiding the nested loop.

(2) The loop in this block seems unnecessary:

https://github.com/ESCOMP/CTSM/blob/3dcbc7499a57904750a994672fc36b4221b9def5/src/cpl/share_esmf/UrbanTimeVarType.F90#L260-L264

If I understand the code correctly: `stream_varnames(lun%itype(l)) == stream_varnames(n)` will be true if and only if `lun%itype(l) == n`. So then we can remove the loop and simply set `this%t_building_max(l) = dataptr2d(ig,lun%itype(l))`.

(3) ig is never used in this block doing error checking, so it can be removed:

https://github.com/ESCOMP/CTSM/blob/3dcbc7499a57904750a994672fc36b4221b9def5/src/cpl/share_esmf/UrbanTimeVarType.F90#L275-L279

**Comment by johnpaulalex** [comment]
@billsacks, a few clarifying questions:
For (1), is the 'if' case guaranteed to happen? i.e. is lun%gridcell(l) guaranteed to be within the bounds? I would think I'd need to check for that, and set ig = bounds%endg - bounds%begg + 1 otherwise.

For (2), same question - is lun%itype(l)) guaranteed to be within isturb_MIN and isturb_MAX? (if not, the code is a no-op)

Also for (2): just confirming that you know that stream_varnames has no repeated values? so there's no way stream_varnames(a) could equal stream_varnames(b) unless a == b?

**Comment by billsacks** [comment]
@johnpaulalex very good questions - thanks for asking, both to confirm your understanding and my own!

> For (1), is the 'if' case guaranteed to happen? i.e. is lun%gridcell(l) guaranteed to be within the bounds? I would think I'd need to check for that, and set ig = bounds%endg - bounds%begg + 1 otherwise.

Great question. Yes, this is guaranteed to happen based on the construction of bounds and lun%gridcell. (Each grid cell, `g`, is divided into multiple landunits, `l`. `lun%gridcell(l)` tells you the grid cell index for a given landunit index. It is guaranteed that, if `l` is within `bounds%begl:bounds%endl` then the corresponding grid cell index `g` is within `bounds%begg:bounds%endg` – which generally means that the grid cell index is owned by the same processor as the landunit index. I realize that these kinds of invariants are not documented well.)

> For (2), same question - is lun%itype(l)) guaranteed to be within isturb_MIN and isturb_MAX? (if not, the code is a no-op)

Another great question. Yes, since this is inside an `if (lun%urbpoi(l))` conditional, this is guaranteed to be an urban landunit, which implies that `lun%itype` is within isturb_MIN and isturb_MAX.

> Also for (2): just confirming that you know that stream_varnames has no repeated values? so there's no way stream_varnames(a) could equal stream_varnames(b) unless a == b?

Good point. Yes, these are intended to differ and they do in practice:

https://github.com/ESCOMP/CTSM/blob/cdb61872e8338650aca696fe3102150bdb170853/src/cpl/share_esmf/UrbanTimeVarType.F90#L129-L131

I'm not sure how / where we can document this kind of thing better (ideas are welcome).... I picked this as a good first issue exactly because it forced (or encouraged) this kind of learning about the subgrid structure, which is one of the biggest learning curves of CTSM.
