### ISSUE TITLE
PerchedLateralFlow in SoilHydrologyMod uses hardcoded value instead of parameter perched_baseflow_scalar

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#1534]
### Brief summary of bug

PerchedLateralFlow in SoilHydrologyMod uses hardcoded value instead of parameter perched_baseflow_scalar

### General bug information

**CTSM version you are using:** branch_tags/PPE.n11_ctsm5.1.dev030

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** All

### Details of bug

In SoilHydrologyMod.F90:

q_perch_max = 1.e-5_r8 * sin(col%topo_slope(c) * (rpi/180._r8))

but it should use the parameter perched_baseflow_scalar:

q_perch_max = params_inst%perched_baseflow_scalar * sin(col%topo_slope(c) * (rpi/180._r8))

The value of perched_baseflow_scalar is the same as the hardcoded value (1.e-5) so this should be a bfb change.

**Comment by ka7eh** [comment]
Looks like this was resolved in https://github.com/ESCOMP/CTSM/pull/1738.

**Comment by billsacks** [comment]
Good point - thanks @ka7eh
