### ISSUE TITLE
Sparse grid for development

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1549]
Work on the PPE by @djk2120 and @olyson suggests that creating a sparse grid resolution of CTSM would be useful for users who want to run fast 'global' simulations. @ekluzek suggested that we could create a user_mod directory to do this pretty quickly.  If this is a tool that people are using we could then coordinate the PR that would go into CIME.  I'm imagining that this could be used instead of a coarse grid (e.g. 10x10 or 4x5) resolution simulation that's commonly used for development by @rosiealice and others.

**Comment by wwieder** [comment]
Assuming the user-mods directory is helpful, I'd suggest more support come in with CTSM5.2

**Comment by rosiealice** [comment]
This sounds like it would be an awesome idea. Just to check, you're not proposing getting rid of 10x10 / 4x5?  :)

**Comment by ekluzek** [comment]
@rosiealice no we are not getting rid of existing grids. Just adding a user mod directory for a new one. f10 and f45 are important in their own right.

**Comment by billsacks** [comment]
@olyson says: what they've done for the PPE is:
- used the f19 grid but with a different ocean mask to mask out most points

**Comment by rosiealice** [comment]
@olyson that's an awesome hack! Extra points for whomever came up with it :)
