### ISSUE TITLE
Urban time-varying streams

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#155]
**Keith Oleson < oleson > - 2016-12-19 12:53:26 -0700**
**Bugzilla Id:** [2390](http://bugz.cgd.ucar.edu/show_bug.cgi?id=2390)
**Bugzilla CC:**  dlawren,  erik,  oleson,  rfisher,  sacks, 

Bob Tomas encountered an urban time-varying stream related error with cesm2_0_beta04:

```
(shr_dmodel_readLBUB) file lb: /glade/p/cesmdata/cseg/inputdata/lnd/clm2/urbandata/CLM50_tbuildmax_Oleson_2016_0.9x1.25_simyr1849-2106_c160923.nc       2
(shr_dmodel_readstrm) open   : /glade/p/cesmdata/cseg/inputdata/lnd/clm2/urbandata/CLM50_tbuildmax_Oleson_2016_0.9x1.25_simyr1849-2106_c160923.nc
(shr_dmodel_readLBUB) file ub: /glade/p/cesmdata/cseg/inputdata/lnd/clm2/urbandata/CLM50_tbuildmax_Oleson_2016_0.9x1.25_simyr1849-2106_c160923.nc       2
 ERROR: no valid urban data for g=            1
 landunit type:              7
 RROR: Unknown error submitted to shr_sys_abort.

```
This occurs in UrbanTimeVarType.F90 (which I wrote for the urban time-varying streams).
He is running an LGM simulation for which there are no urban areas.

There is a check in that routine to see if there is valid urban data if urbpoi is true. I had forgotten that urbpoi could be true even if pct_urban = 0, because it looks like it is simply keyed off of URBAN_REGION_ID from the surface dataset, regardless of the value of pct_urban.  It looks like I need to also check whether or not the landunit is active, perhaps using lun%active(l)?  Or is there a better way to do this?  The relevant code is:

 ```
  found = .false.
   do l = bounds%begl,bounds%endl
      if (lun%urbpoi(l)) then
         glun  = lun%gridcell(l)
         !
         ! Determine vector index corresponding to glun
         !
         ig = 0
         do g = bounds%begg,bounds%endg
            ig = ig+1
            if (g == glun) exit
         end do

         if ( .not. urban_valid(g) .or. (this%t_building_max(l) <= 0._r8)) then
            found = .true.
            gindx = g
            lindx = l
            exit
         end if
      end if
   end do
   if ( found ) then
      write(iulog,*)'ERROR: no valid urban data for g= ',gindx
      write(iulog,*)'landunit type:   ',lun%itype(l)
      write(iulog,*)'urban_valid:     ',urban_valid(gindx)
      write(iulog,*)'t_building_max:  ',this%t_building_max(lindx)
      call endrun(msg=errmsg(sourcefile, __LINE__))
   end if

```
So I was thinking of modifying the if statement as:

`if (lun%urbpoi(l) .and. lun%active(l)) then`

**Comment by ekluzek** [comment]
**Keith Oleson < oleson > - 2016-12-20 16:10:12 -0700**

Changing "fillalgo" for the urbantv stream from the current value of "none" to "nn" (nearest neighbor) allows the model to run. This implies that gridcells that have no data are being filled in with valid data.

To check the actual data being filled in, I ran an "allurban" run where urban landunits run everywhere and I output a dov2xy=false file that contains "TBUILD_MAX" which is the field read in from the urbantv stream.  I converted this to 2d and I see that this has the effect of filling in a nearest neighbor valid value for every gridcell that has non-zero URBAN_REGION_ID, e.g, for this particular simulation there are now valid values of TBUILD_MAX in Antarctica.  These values are 380K which is what I expect for an 1850 simulation.

So, I think there are two changes to be made.  As I previously mentioned, the first is to additionally check whether the urban landunit is active, i.e., in UrbanTimeVarType.F90:

< !KO      if (lun%urbpoi(l)) then
< !KO
<       if (lun%urbpoi(l) .and. lun%active(l)) then
< !KO

And the second is to change fillalgo from "none" to "nn".

**Comment by ekluzek** [comment]
OK, we are doing one of the things here as we use fillalgo as "nn".

The other thing we've done for handling if urban is active or not is the new namelist item: run_zero_weight_urban, which is normally False. I think it amounts to the same thing as adding the "if  ... lun%active" part here.

@olyson as such I think I can close this issue. Do you agree?

**Comment by olyson** [comment]
I think I agree yes.
