### ISSUE TITLE
Uncomment fates_levleaf fields

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1561]
In ctsm5.1.dev062 I brought in PR #1540, but in order to not have to include a new FATES tag I commented out two lines for the fates_levleaf dimension in this commit...

5e1adf8a909386fbef33c9eacef725a992588df4

We didn't want to bring in a new FATES tag since we didn't have one that just did that one change. And we needed answers for FATES to be identical, since we were already bringing in answer changes going to NUOPC as the new driver.

@glemieux @rgknox let me know if you have any feedback on this. @adrifoster

**Comment by glemieux** [comment]
I think we can leave this commented out as is; the fates-side change that will utilize this will be https://github.com/NGEET/fates/pull/752, but @ckoven wanted to re-evaluate this PR after we've integrated @adrifoster's #1542.  So for now the DIFFs on the `fates_levleaf` dimension output will be junk, which is as expected until we hook it up on the fates side.

**Comment by ekluzek** [comment]
Some of the discussion on this is here in PR #1540...

My finding of the problem...

https://github.com/ESCOMP/CTSM/pull/1540#issuecomment-960457567

@glemieux response...

https://github.com/ESCOMP/CTSM/pull/1540#issuecomment-961197552

And my comments about what I did..

https://github.com/ESCOMP/CTSM/pull/1540#issuecomment-961375669
