### ISSUE TITLE
increase skip_steps for balance checks by one to permit new CAM physics re-ordering

### ISSUE THREAD

**Issue by adamrher** [ESCOMP/CTSM#1563]
BalanceChecks are only applied at nstep=3 or later, since the balance checks don't pass for nstep=0,1,2. This is controlled by the ```skip_steps``` variable in BalanceCheckMod.F90:
https://github.com/ESCOMP/CTSM/blob/679f1eba01a27d03536a3e924484f12f83ca1622/src/biogeophys/BalanceCheckMod.F90#L85

The importance of nstep=3 is that this is when the first non-initialization phase radiation is passed from CAM to the surface components. CAM is rearranging it's physics time-loop (see https://github.com/ESCOMP/CAM/pull/387), such that the first non-initialization phase radiation will be sent one time-step later, at nstep=4. Hence, we need to increase the ```skip_steps``` variable from 2->3, or else the BalanceChecks will end the run at nstep=3. (It's possible I'm wrong on the details; this is what I am able to infer from lots of debugging ... and the fact remains that the new physics ordering only works when I increase ```skip_steps``` to 3).

An aside. If someone can explain why the balance checks fail for the first few time-steps, that would be good to know. Specifically, the balance checks fail when this ```errsol``` number is large:
https://github.com/ESCOMP/CTSM/blob/679f1eba01a27d03536a3e924484f12f83ca1622/src/biogeophys/BalanceCheckMod.F90#L884-L885

Which basically says the ```fsa+fsr``` (absorbed + reflected radiation, which is computed earlier in clm time-loop via SurfaceRadiationMod) is very different from the sum of the incident radiation from the ```atm2lnd_inst``` object/array.

@cacraigucar @mvertens (<- whom I know is on vacation, but is also interested in understanding this issue further)

**Comment by ekluzek** [comment]
@adamrher does this behavior depend on the time-step and/or resolution?

Note, that in above skip_size is currently 3600 seconds for timesteps at 1 or 2 degree of 1800 seconds. So if the new standard should be 3, skip_size should also be increased to 5400 seconds.

It's a good question about why the balance checks fail. What I do know is that they often fail, but the amount they fail for is generally damped each time-step in. So time-step 0 is horrible, 1 is a bit better, and until now 2 was reasonable. I think it really comes down to the initial state being out of balance when you startup. You don't see these variations on restart, only on startup, but that's when the initial conditions aren't coming from a previous spun-up state (at least for exactly the same model and same resolution etc.).

**Comment by adamrher** [comment]
> Note, that in above skip_size is currently 3600 seconds for timesteps at 1 or 2 degree of 1800 seconds. So if the new standard should be 3, skip_size should also be increased to 5400 seconds.

I agree. And what I think this skip_size should represent is the absolute number of seconds it takes to send a proper radiation (what I'm calling "non-initialization phase radiation") to the land model. The balance checks fail because for some reason ```errsol``` is large during these initialization phase radiation time-steps, but immediately goes to very tiny values the first time a proper radiation is sent to the land model (and/or b/c the land albedo's are properly consistent with the sent radiation field at this time).

I did a run where I halved the time-step to 900s in the default model (normal physics ordering), and it is actually the second argument (3600/dtime) that is necessary for the balance checks to succeed, not the first argument (the hard coded value of 2). This seems to be because the radiation time-steps are *not* a function of physics time-step; the radiation time-step is fixed to one hour regardless of physics time-step. 

So for the new physics reordering to work for any arbitrary physics time-step, then ```skip_size``` should be increased to 5400s as you have indicated. Then I wouldn't even bother modifying the 2 in the max argument ... I don't even know if this additional argument is even necessary.

I have not checked different grid resolutions. At least for the radiation balance checks, it seems like it shouldn't matter for the reasons I just discussed. But maybe the water balance checks are sensitive to resolution?

**Comment by billsacks** [comment]
@adamrher thanks a lot for opening this issue and sharing your insights. This is something I'd like to understand better myself.

Am I understanding right that the need for skipping this balance check in the first few time steps is partly (or wholly) related to the fact that CTSM doesn't do radiation/albedo calculations every time step (as controlled by nextsw_cday)?

**Comment by adamrher** [comment]
Bill I really can't make a definitive statement on the cause of the imbalances, only that things fall in to line once the first non-initialization phase radiation is sent to the land model. Here's an example of the diagnostics that backs up that statement.

Default CAM physics order, w/ a 900s physics time-step. Here skip_size=3600s, and so skip_steps=4:
   
 clm/SurfaceRadiation: fsa+fsr,    478.637985414271     
 clm/SurfaceRadiation: forc_tot,    490.176252335921     
 B4:clm/BalanceCheck: nstep, nextsw_cday,            0   1.05208333333333     <-- nextsw_cday>0
 B4:clm/BalanceCheck: errsol_max_val,    11.5382669216499     
     
 clm/SurfaceRadiation: fsa+fsr,    478.637985414271     
 clm/SurfaceRadiation: forc_tot,    490.176252335921     
 B4:clm/BalanceCheck: nstep, nextsw_cday,            1   1.05208333333333      <-- nextsw_cday>0
 B4:clm/BalanceCheck: errsol_max_val,    11.5382669216499     
    
 clm/SurfaceRadiation: fsa+fsr,    478.637985414271     
 clm/SurfaceRadiation: forc_tot,    490.176252335921     
 B4:clm/BalanceCheck: nstep, nextsw_cday,            2  -1.00000000000000     
 B4:clm/BalanceCheck: errsol_max_val,    11.5382669216499     
     
 clm/SurfaceRadiation: fsa+fsr,    478.637985414271     
 clm/SurfaceRadiation: forc_tot,    490.176252335921     
 B4:clm/BalanceCheck: nstep, nextsw_cday,            3  -1.00000000000000     
 B4:clm/BalanceCheck: errsol_max_val,    11.5382669216499     
    
 clm/SurfaceRadiation: fsa+fsr,    478.637985414271     
 clm/SurfaceRadiation: forc_tot,    490.176252335921     
 **clm/SurfaceAlbedo: nstep, nextsw_cday,            4   1.05208333333333     <-- doalb=T**
 B4:clm/BalanceCheck: nstep, nextsw_cday,            4   1.05208333333333     <-- nextsw_cday>0
 B4:clm/BalanceCheck: errsol_max_val,    11.5382669216499
    
 clm/SurfaceRadiation: fsa+fsr,    442.768574344513     <-- first non-initialization phase radiation
 clm/SurfaceRadiation: forc_tot,    442.768574344513     
 B4:clm/BalanceCheck: nstep, nextsw_cday,            5  -1.00000000000000     
 B4:clm/BalanceCheck: errsol_max_val,   **2.273736754432321E-013**

So as you can see it's not until ntep=5, that errsol_max_val is small. But what's is weird, and perhaps a hint to what's going on, is that my write statement "clm/SurfaceAlbedo: nstep, nextsw_cday..." that is contained in the doalb=T if statements, only trigger for the the nextsw_cday>0 of nstep=4. Whereas elsewhere in nstep=0,1, nextsw_cday>0, yet the doalb loop is not executed.

The same type of analysis for my physics reordering run, also w/ a 900s physics time-step, shows the same thing, that even though nextsw_cday>0 for nstep=0,1, the doalb loop is not executed. But owing to the new ordering the next nextsw_cday>0 occurs at nstep=5, it triggers the doalb loop, and the first non-initialization phase radiation comes in at nstep=6, and errsol_max_val is small and passes the balance checks for the first time.

So I think I'm getting closer to the "why is this happening" question. But FYI, the physics reordering PR is currently a top priority for AMP as a whole, and so Id like to come up with a solution for that PR ASAP. That is, changing skip_steps=5400 does the trick, and will allow us to move forward w/ our work. I suspect fixing the underlying issue, i.e, so we don't need time-step conditionals on the balance checks, may take some time to sort out. I'm hoping y'all will entertain this short term solution in addition to the longer term goal. Hope that makes sense.

**Comment by billsacks** [comment]
Thanks a lot for all of these details @adamrher . This is really helpful to move us all closer to understanding the fundamental reason why this is needed. As I said in an email but will repeat here: I am personally fine with putting in place whatever fix is needed for now, even if we don't 100% understand this. Worst case scenario is that we skip the balance check for an extra time step or two beyond what's really needed, which doesn't seem like a huge deal to me since if the balance check is going to fail a few time steps into a run, it seems like it will be very likely to continue to fail later in the run. i.e., I don't think there's a big risk in missing a problem by making the skip steps too large.

Also, to record this all in one place: @ekluzek said:

> I think what you really need is skip_size to stay at 3600, but you need skip_steps to be 1 step bigger than 3600/dt

and @adamrher agreed:

> I think you're right; I only need to push skip_steps by 1, and so setting skip_steps = 3600/dtime+1 seems like the appropriate fix

**Comment by adamrher** [comment]
Thanks @billsacks. @cacraigucar just finished a tag updating our externals to dev64. Could someone @ me when CTSM makes a tag for dev66?

@ekluzek just to reiterate. I am sure the appropriate mod is to increase step size from 3600/dtime -> 3600/dtime+1. I have moved radiation from before coupler physics to after coupler physics, and so the radiation fields sent to the coupler will be delayed by on time step. This means that the sun in the sky is always from the prior time-step ... I worked with Marianna to make sure that nextsw_cday has been modified appropriately to reflect this delayed azimuth angle (no pun intended). The impact on climate is nil.

**Comment by ekluzek** [comment]
Ahhh yes that's very clear. Ok thanks for that explanation that really helps.

**Comment by adamrher** [comment]
@ekluzek it looks like you made tag dev66, but it does not include these mods. I thought this was supposed to go into dev66?

**Comment by ekluzek** [comment]
Hi @adamrher yes, we had another tag that needed to come in before this one. So now the plan is for it to be in dev067. And I should that one this week.

**Comment by adamrher** [comment]
thanks @ekluzek. Is this new tag bfb w/ dev64 (not referring to neon or fates changes, just from the perspective of cam's testlist).

**Comment by ekluzek** [comment]
It should be bfb with dev64 from CAM's perspective. The two tags in there change answers for FATES, but won't matter for CAM's test list.
