### ISSUE TITLE
documentation: single scattering albedo

### ISSUE THREAD

**Issue by robin-zweigel** [ESCOMP/CTSM#1566]
Issue with Eq. 3.16 in current CLM5 documentation:
The explanatory text states that a term is limited to avoid low values, yet in the equation a minimum restriction is applied.
Should this instead be a maximum restriction?

**Comment by olyson** [comment]
Good catch, thanks.  Yes, it should be max() in the documentation, as it is in the code.
We'll fix this.

**Comment by olyson** [comment]
I've made this modification to the master version of the documentation.  I was going to commit and push but I'm wondering if I should also modify the release documentation as well and if so how to do that.  Do I need to check out the release branch and repeat the process?  @billsacks

**Comment by billsacks** [comment]
@olyson thanks a lot for fixing this. Yes, I agree with what you say about repeating the process for the release branch.

**Comment by olyson** [comment]
This was fixed in the master and release technical note documentation so I'm closing this.
