### ISSUE TITLE
History output for DISPLA is incorrect when vegetation is buried by snow

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#1569]
### Brief summary of bug

History output for DISPLA is incorrect when vegetation is buried by snow because the variable displa is declared as a local variable within BareGroundFluxesMod.F90 and hence the global variable used for history output is not updated.  DISPLA should be 0 in this case but instead remains at the value set in CanopyTemperatureMod.F90.
Reported by Ronny Meier and confirmed by myself.

### General bug information

**CTSM version you are using:** release-clm5.0.34-2-ga2989b04 (but master/main tags are affected as well)

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** All when history variable DISPLA is active and vegetation is buried by snow

**Comment by olyson** [comment]
There is a similar issue with lakes in that a local variable displa is set to zero.  Since displa for lakes isn't set elsewhere presumably this means that lakes aren't included in the grid cell average since they will be spval.  Urban has a bit of a different issue in that it has its own definition of displacement height (z_d_town) and so presumably it doesn't get included in the grid cell average either.  I'm wondering if the right thing to do is to restrict the output to vegetated landunits only (set_spec=spval, l2g_scale_type='veg'). And include "(vegetated landunits only)" in the long_name.

**Comment by billsacks** [comment]
@dlawrenncar suggests looking through BareGroundFluxes for other variables that might have the same issue. Someone pointed out a similar seeming issue with roughness length (z0 and variations).

In terms of the history attributes: if you set `l2g_scale_type='veg'`, you don't need `set_spec=spval`.

**Comment by ekluzek** [comment]
@olyson is this still a problem in the latest development versions? This seems like an important thing to make sure is fixed. We don't need to worry about if for past release versions, but it does seem like it should be fixed for CESM3. The #1570 PR sounds like maybe it was corrected. Although another suggestion was to look at this for other variables and maybe that needs to be done?

**Comment by olyson** [comment]
I believe this was all fixed by #1570 , including looking at other variables.

**Comment by ekluzek** [comment]
OK, nice I'm closing then...
