### ISSUE TITLE
Need to replace SSP370 ndep file with new one

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#1578]
### Brief summary of bug

Need to replace SSP370 ndep file with new one

### General bug information

**CTSM version you are using:** [output of `git describe`] N/A

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No] Maybe

**Configurations affected:** [Fill this in if known.]  Any that use SSP370 ndep file

### Details of bug

There was an error in landuse in b.e21.BWSSP370cmip6.f09_g17.CMIP6-SSP3-7.0-WACCM.**001** (the landuse file was labeled SSP3-7, but in fact had SSP1-2.6 data in it).
A **002** simulation already partially run (which used the correct landuse file/data) was extended through 2100.
I generated a new ndep file from this extended **002** simulation:

/glade/p/cgd/tss/people/oleson/CLM5_ndep/fndep_clm_SSP370_b.e21.BWSSP370cmip6.f09_g17.CMIP6-SSP3-7.0-WACCM.002_2014-2101_monthly_0.9x1.25_c211210.nc

The old ndep file was generated from the incorrect b.e21.BWSSP370cmip6.f09_g17.CMIP6-SSP3-7.0-WACCM.**001**.  Presumably, we will want to update our SSP370 namelists to the new file.

**Comment by olyson** [comment]
Based on an email from Mike Mills, I see that **001** used the wrong landuse data.

**Comment by dlawrenncar** [comment]
Did simulation 001 use landuse data that was completely wrong (like pointed
to a file labeled as SSP1-2.6 or do you mean that it used the file that is
labeled SSP3-7, but in fact had SSP1-2.6 data in it ... i.e, the problem
that we had previously detected and are now trying to resolve?

**Comment by olyson** [comment]
Simulation 001 used "the file that is labeled SSP3-7, but in fact had SSP1-2.6 data in it ... i.e, the problem
that we had previously detected and are now trying to resolve".
I've updated the original issue to make this clearer.

**Comment by ekluzek** [comment]
The file is in the usual place:

lnd/clm2/ndepdata/fndep_clm_SSP370_b.e21.BWSSP370cmip6.f09_g17.CMIP6-SSP3-7.0-WACCM.002_1849-2101_monthly_0.9x1.25_c211216.nc
