### ISSUE TITLE
Change HASLAKE to PCT_LAKE_MAX

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1582]
To work with the upcoming changes in #1579 we need to change the HASLAKE variable (read from the landuse timeseries file) to PCT_LAKE_MAX. The check for `if (haslake(gi))` will need to be changed to `if (pct_lake_max(gi) > 0._r8)`.

Currently no out-of-the-box datasets have this variable on them, but the dataset used in the `smallville_dynlakes_monthly` testmod does, and that will need to be changed.

This change should be made before #1579 comes to master, which is intended to happen with the ctsm5.2.mksurfdata branch.

**Comment by slevisconsulting** [comment]
I hope it's ok if I resolve this in #1732 
I'm getting every last new dataset working and then will merge #1732 to the ctsm5.2.mksurfdata branch.

**Comment by slevisconsulting** [comment]
I merged #1732 so I'm closing this issue.
