### ISSUE TITLE
Remove unused uses of cism_evolve in nuopc cap

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1583]
With the changes in #1495 , the retrieved cism_evolve flag in the nuopc cap is no longer referenced anywhere. We should clean things up by removing this variable (from lnd_comp_nuopc.F90 and lnd_import_export.F90).

**Comment by ekluzek** [comment]
@billsacks cism_evolve is still a valid option right? Does it only affect things in the mediator now and not inside of CTSM? I guess I can see that CTSM doesn't really need to know, but other components would (of course CISM itself, and CAM for example).

**Comment by billsacks** [comment]
Right. Particularly now that we have multiple ice sheets, the overall cism_evolve isn't something that most components need to know about: this is false if and only if NO ice sheets are evolving. CTSM *does* need to know where there is an evolving vs. non-evolving ice sheet underneath (or, more precisely, where CISM is potentially accumulating SMB and sending runoff fluxes to the ocean), but that is done via a spatial mask rather than a single logical flag.

However, now that I'm writing this out, I'm remembering that it could be helpful to look at this cism_evolve flag as a slight performance enhancement, since we could skip some code if we know that cism isn't evolving at all (see https://github.com/ESCOMP/CTSM/issues/300 ). So maybe we should leave this in place after all. I'll close this issue and make a note in #300.
