### ISSUE TITLE
Carbon root profiles aren't modified with dynamic roots

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#160]
**Erik Kluzek < erik > - 2017-01-19 10:29:36 -0700**
**Bugzilla Id:** [2411](http://bugz.cgd.ucar.edu/show_bug.cgi?id=2411)
**Bugzilla CC:**  dlawren,  dll,  oleson,  rfisher, 

Currently carbon root profiles are unmodified when use_dynroots=.true. as it only varies rootfr and not crootfr.

**Comment by wwieder** [comment]
dynamic roots are not planned for any upcoming CLM developments.  I'll close this issue for now
