### ISSUE TITLE
Documentation errors in tech note related to phenology

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1607]
The technote says leaf off is triggered for stress deciduous phenology scheme with a counter that looks at days with soil water potential < -2 MPa (`psi_offset`, see equation 2.20.68).  But this is now a parameter on the default parameter file `soilpsi_off = -0.8`

I'm imagining a number of these parametric changes have crept into the code, and more will happen with the PPE.  This one is pretty straightforward to change, but may not be worth rebuilding the whole tech note for?

NOTE, @danicalombardozzi and I found this because of conversations with Andrew Richardson, who was looking into results from the NEON-NCAR project and couldn't figure out why C3 grasses seemed to be unexpectedly losing their leaves in the middle of the growing season.

More broadly, I wonder when this parameter change came into the code? Was it with Kyla's phenology changes from long ago?  

Finally, may will need to be reassessed with we update surface datasets with different soil properties?

**Comment by olyson** [comment]
It looks like this changed from -2 to -0.8 in the transition from CLM4.5 to CLM5.

**Comment by olyson** [comment]
This is done.
