### ISSUE TITLE
Change CropPhenology to look at the day of year as of the start of the time step, not the end of the time step

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1623]
Currently, subroutine CropPhenology gets the day of year here:

https://github.com/ESCOMP/CTSM/blob/0b5d7e07a90b8e9a3aff6c01da98880d12bc964a/src/biogeochem/CNPhenologyMod.F90#L1753

This gives the calendar day as of the *end* of the current time step. This means that, in the last time step of the year (with a 1/2 hour time step, that would be the time step going from 84600 - 86400 seconds on Dec 31) jday will be 1. This means that – I think – crops that have a planting window beginning Jan 1 could actually be planted on the last time step of the previous year. This doesn't seem like a huge problem by itself, but it complicates the computing and outputting of crop planting dates, as in #1616 .

Therefore, I propose to change this determination of jday to look at the calendar day as of the *start* of the current time step (either by directly specifying an offset to `get_curr_calday` or – more likely – by introducing a new function, `get_prev_calday`). This will change answers, but I believe not hugely; the main change that I can think of will be that crops with a planting window starting Jan 1 will need to wait until the new year to be planted.

From a skim through CNPhenologyMod, I can't see any problems this will cause (hah! famous last words! but I'm hopeful), and it doesn't look like anything else would need to be changed.

**Comment by billsacks** [comment]
@samsrabin @danicalombardozzi - I propose making this change prior to #1616 . I think this will allow us to clean up some of the subtle code that @samsrabin needed to add in #1616 . I will add a comment there shortly, but need to run now.

I can't think of any problems this will cause, but I would like to hear from both of you if you feel this is a safe change to make or if you can think of any issues with making this change.

**Comment by samsrabin** [comment]
Good point. This is actually causing me a bit of a headache; we probably should find a good solution.

I'm not sure `get_prev_calday()` is the right way to go, though, at least given how I read the name of that function. It's more like we want the _true_ current calday.

This can presumably be accomplished by specifying an offset of `TimeStep`/-2, but I'm not sure how to do that. I think also specifying an offset of -1 second would accomplish the same thing.

Of course, whatever we do won't be fixed in the restart files until those runs are actually redone, so I don't think I can actually yet get rid of the code you refer to in #1616.

**Comment by billsacks** [comment]
The names in clm_time_manager can be a bit unintuitive, but in most (all?) current cases in CTSM, when we want to know the current day / time, we look at either (1) the time as of the end of the time step, or (2) the time as of the start of the time step. Routines for (1) are called "get_curr_*", and routines for (2) are called "get_prev_*". So "get_prev_calday" would imply getting the time as of the start of the time step. "prev" is unintuitive here because really the time as of the start of the time step is just as "true" of a time as that at the end of the time step. I think we need to come up with better names here (suggestions welcome).

That said, I definitely see your argument for using an offset of `-dtime/2`. That wouldn't be hard to do, but I don't think we do that anywhere currently, and I'd prefer not to add a third time option like this unless it's really needed: even though it kind of feels like the most correct time for this situation, I think it would be confusing to have this one place that uses a different notion of time. Long-term, maybe we should move towards being more rigorous/deliberate about the time we use for things like this, and that might lead us to using a time in the middle of the time step for this and similar situations.

In practice, though, since we never (or at least only extremely rarely... but I'm going to go out on a limb and say never) have time steps that span a day boundary, any option other than the time at the end of the time step would return the same value for day of year.

Regarding restarts with old restart files: I think I need to talk with you about this to understand the issue better. I have some pending comments in #1616 about this that I'll post soon, but I think you have gotten a better understanding of this issue than I have so I'd be interested in hearing your explanation of the issue.

**Comment by ekluzek** [comment]
So are we saying that we want the time for the midpoint of the "prev" and "curr" timestep? So that could be something like "get_midpoint_calday"? I think if you realize that "previous" and "current" means relative to the current time-step that they are understandable,. and I think we should keep them consistent, until we change them all at once.

Maybe

get_beginngof_timestep_calday
get_midpointof_timestep_calday
get_endof_timestep_calday

start, middle, ending would be different names to use. Yes, the question is when do you use each of those? Is it always clear from the context which one should be used?

**Comment by billsacks** [comment]
I realized that, in the current code on master (if we do this before we bring in #1616), then we should probably also change this call:

https://github.com/ESCOMP/CTSM/blob/0b5d7e07a90b8e9a3aff6c01da98880d12bc964a/src/biogeochem/CNPhenologyMod.F90#L1754

to use the start of the time step. I'm not 100% sure that's the right thing to do, but I think it correctly keeps the two things consistent, and I think it would make the current code more consistent with what's now happening in #1616 (i.e., resetting things in the first time step of the new year rather than the last time step of the previous year), avoiding potential answer changes in #1616 .

**Comment by billsacks** [comment]
> So are we saying that we want the time for the midpoint of the "prev" and "curr" timestep? So that could be something like "get_midpoint_calday"?

Right, although my suggestion would be that, if we make that change anywhere, then it should be in the context of a full analysis of which time is appropriate to use in each context in the code (which may or may not be worth the time).

> the question is when do you use each of those? Is it always clear from the context which one should be used?

I think the answer is "no", that this is somewhat subjective and ad hoc, at least until we are more rigorous in how we do time integration in CTSM (Martyn Clark's vision).

**Comment by billsacks** [comment]
That said, @samsrabin I am very interested in hearing your point of view on this since you have been thinking a lot about it lately. I can certainly be swayed in my current thinking.

**Comment by samsrabin** [comment]
Now that you've explained the existing convention of `get_prev_*` as referring to "the beginning of the current timestep" it makes sense. There certainly could be a longer-term discussion about rethinking time integration, but for now your solution seems good. No need to add a third `get_mid_*` realization.

**Comment by billsacks** [comment]
In a discussion with @samsrabin yesterday, we realized that this change could cause problems when starting from existing restart files (i.e., restart files created before this change) if CropPhenology is called on time step 0: In this case, the restart file could indicate that a currently-live crop was planted on Jan 1 (because, with the current crop code, the last time step of the year is considered Jan 1) but time step 0 would now be considered Dec 31, leading the crop to be immediately harvested (because CropPhenology will think that the crop has been alive for 365 days). So we thought we should add a conditional around the call to CropPhenology to avoid calling it on this 0th time step.

But I did a little investigation and it turns out that CropPhenology is already skipped on time step 0, because it is only done when `doalb` is true (I'm not sure why: see https://github.com/ESCOMP/CTSM/issues/1626 ), and `doalb` is always false on time step 0. So I don't think we need to worry about this happening.

That said, I think I'll still add an extra conditional to be safe, in case the resolution of #1626 is that we should remove this `doalb` conditional.

**Comment by billsacks** [comment]
Actually, my latest plan is to remove the `doalb` condition around the `CropPhenology` call, replacing it with just a condition on whether it is time step 0. For I compsets (at least with the nuopc driver), it appears that the only impact of this change will be that we will now call CropPhenology on time step 1 of the run, which wasn't being done before.

See https://github.com/ESCOMP/CTSM/issues/1626#issuecomment-1028608449 and https://github.com/ESCOMP/CTSM/pull/1616/files#r798210796 .

**Comment by billsacks** [comment]
I thought about whether the calls to `get_curr_date` in `CNPhenologyClimate` and `CropIncrementYear` should also be changed to `get_prev_date`. These are used for the 20-year running average GDD accumulation (`CropIncrementYear` is used for updating `nyrs_crop_active_patch`, but that in turn is just used for the GDD accumulation). But these really do feel like they are appropriate to happen at the end of the year – not the first time step of the new year. (One reason why the current end-of-year timing is better is for the sake of diagnostics – so that the 20-year averages have been updated before writing an end-of-year history file.) It feels like the ideal time for it to happen would be *after* the other crop phenology stuff, but I don't think it's a big deal for it to happen before the other crop phenology stuff in the last time step of the year, as is currently the case.
