### ISSUE TITLE
Why is the CropPhenology call in a doalb conditional?

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1626]
Does anyone know why CropPhenology is in a doalb conditional?

https://github.com/escomp/ctsm/blob/master/src/biogeochem/CNPhenologyMod.F90#L358-L363

None of the other phenology calls are in a doalb conditional, so why crop? Looking through the history, it looks like this has been the case ever since the CropPhenology subroutine was introduced in clm4_0_27.

@slevisconsulting @ekluzek @mvertens do any of you remember why we have this doalb conditional here and whether it's important to keep it?

**Comment by billsacks** [comment]
Also, can anyone comment on when we expect doalb to be true and false? Here is the relevant code, I think:

https://github.com/ESCOMP/CTSM/blob/8d9f988f94720cee94c48a21b1f8bc865c9d2409/src/cpl/nuopc/lnd_comp_nuopc.F90#L818-L824

So doalb is always false on time step 0 (i.e., that extra 0th time step we're thinking of getting rid of - #925 ). On time step 1, I'm not sure what to expect in general, though in an I compset that I just ran, doalb is also false in time step 1. For time steps after time step 1, do I understand this code correctly that doalb will always be true for these subsequent time steps?

The main thing I'm interested in at the moment is whether we can rely on CropPhenology always being called in the first time step of each year for all years after the first year of the run, because logic that @samsrabin has added in #1616 relies on this being the case.

**Comment by slevisconsulting** [comment]
If my memory serves me, doalb would have been a naïve time saver, because we didn't need to update the phenology more frequently than the albedo. I'm pretty sure that doalb was .true. in an albedo timestep. I cannot comment on whether doalb still serves a useful purpose.

**Comment by billsacks** [comment]
Thanks for your thoughts, @slevisconsulting . It's also the case that LAIs and SAIs are only updated when doalb is true, so I can see why this doalb conditional around CropPhenology might have been put in to be consistent with that. I guess that begs the question of why LAIs and SAIs are only updated when doalb is true, since LAIs and SAIs influence more than just albedos. (I wonder if there was an intention at some point that phenology should only need to be updated hourly, regardless of the atmosphere's physics time step, e.g., to save time in the reading of satellite phenology, but now there are only remnants of that original intention??? I wonder, for example, if it used to be the case that doalb was false more often in an I compset???)

I think this doalb conditional is going to cause problems for #1616 - see https://github.com/ESCOMP/CTSM/pull/1616/files#r798210796 . **So I propose removing this doalb conditional, and replacing it with a conditional that just avoids calling CropPhenology at nstep == 0.** I plan to make that change as part of #1623 .

**Comment by billsacks** [comment]
If there are some situations where doalb is only true on some time steps (e.g., on the hour boundary), then one thing that looks like it could change is the vernalization subroutine: it looks like this is doing some accumulations, so it seems like answers could differ depending on whether it is called (e.g.) every time step vs. every other time step. Again, it seems like doalb is true for every time step after the first two in an I compset, but I'm not sure about coupled configurations.

**Comment by billsacks** [comment]
Ah, I just found this from the CLM software meeting January 25, 2017:

> **CropPhenology only called when doalb is true**
> 
> Even though other phenology-related things don't depend on doalb...
> 
> We're not sure why this is here.
> 
> Feeling is that this is more likely to cause problems than not, and we should probably remove it.
> 
> In terms of testing it: Probably do it in a short simulation...
>

**Comment by samsrabin** [comment]
For what it's worth, I tried going back in time with `git blame` but I hit a wall at the "Move crop branch to trunk" commit (bc3005b196) back on 2011-05-02. Maybe some justification was given on a commit message in the crop branch, but I don't know if that's still available anywhere.

**Comment by billsacks** [comment]
@mvertens says: In a run coupled to CAM, doalb will generally only be true every hour. I think this gives more motivation for removing the doalb conditional, as I do in #1628 .

**Comment by billsacks** [comment]
I feel like I understand this well enough now, so I'm closing this issue. Thanks, all, for your comments.
