### ISSUE TITLE
2100 to 2500 Extension compset for SSP3-7.0

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1633]
There is a need for a new extension compset for SSP3-7.0. For CLM we will have to do that by having fixed 2100 conditions. There isn't extension landuse data available for it. And of course WACCM has not been run for the extension so we will have to have fixed Nitrogen deposition.

The CESM documentation on this is here: 

https://github.com/ESCOMP/CESM/pull/203

The main thing to do is to setup compsets for this, and have a use-case that does fixed 2100 conditions.

**Comment by ekluzek** [comment]
In order to get harvest for 2100 every year, we need to have a landuse time series file, which means to set it up with teh 1850 surface dataset and 1850-2100 landuse timeseries, which will then use 2100 for landuse and 2100 for harvesting.

**Comment by wwieder** [comment]
@ekluzek we have the 2300 extension runs that Mike Mills ran and Charlie is publishing on.  Do these not include SSP3-70 runs?  This would provide land use and N deposition data we can use out to 2300 if it's helpful.

**Comment by ekluzek** [comment]
Hi @wwieder. We do have extension compsets for the ones that Mike ran. The three that were setup before were SSP1-2.6, SS, SSP5-8.5, and SSP5-3.4. I think Mike ran the last two. So it doesn't include SSP3-7.0. And we already asked @lawrencepj1 if there's extension data for landuse for SSP3-7.0 and there isn't. In the PR for this I have included the ndep files for the cases that Mike ran for the extensions.

However, this case is for a Large Ensemble run that will be done on aleph in South Korea. So it has a specific purpose. And unfortunately we don't have all the data needed to run it "properly". But, it's still interesting to run at fixed 2100 conditions....

**Comment by wwieder** [comment]
Ok thanks for clarifying.  I assumed this was for the CESM2-LE extensions. I'd forgotten that the previous 2300 extensions were with the SSP1 and SSP5 scenarios (not SSP3-70).  Is the Korean group running these with WACCM anyway, or are they just planning on CAM6 runs?

**Comment by dlawrenncar** [comment]
For the prior extensions, we ran WACCM I believe.

**Comment by wwieder** [comment]
Yes, that's accurate @dlawrenncar we did WACCM runs to 2300 to get transient Ndep (and other aerosols).  I'm not sure who's making decisions for the CESM2-LE extensions @ekluzek, but it seems warranted to run a single WACCM ensemble member to generated these fields for CAM6?   Should I bring this up with Gokhan or Keith Rodgers?

**Comment by dlawrenncar** [comment]
Yes.  I think we should at least inquire about whether or not that is
what we want to do.  If we don't run WACCM, it makes the definition of the
simulation considerably more complex.

**Comment by ekluzek** [comment]
We don't have raw PFT data for this extension nor from other datasets. The underlying CESM issue was merged and closed, and hence I think this is handled. But, if someone knows this shouldn't be closed please reopen.
