### ISSUE TITLE
c181220 SSP126 and SSP370 landuse files are identical and are still in cesmdata

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#1634]
### Brief summary of bug

A user reported these SSP126 and SSP370 landuse files are identical and are still present in cesmdata:

/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_map/landuse.timeseries_0.9x1.25_SSP1-2.6_78pfts_CMIP6_simyr1850-2100_c181220.nc
/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_map/landuse.timeseries_0.9x1.25_SSP3-7.0_78pfts_CMIP6_simyr1850-2100_c181220.nc

I verified that these files are indeed identical and present in cesmdata.

### General bug information

**CTSM version you are using:** N/A

**Does this bug cause significantly incorrect results in the model's science?** Yes
**Configurations affected:** [Fill this in if known.]

### Details of bug

The user reported: "I came across an issue a few months ago which I discussed with NCAR colleagues who resolved it as a science issue on their end, but it looks like the problematic data are still in the public areas of Glade. "

So it sounds as if the issue was resolved, however, the incorrect data hasn't been removed from glade, unless this is intentional for some reason.
@ekluzek or @lawrencepj1 , do you have any recollection of this issue?

### Important details of your setup / configuration so we can reproduce the bug

[Specify anything relevant: the compset, resolution, machine, compiler, any xml or namelist changes, etc. You don't have to repeat anything that you have already noted above.]

**Comment by lawrencepj1** [comment]
Thanks Keith @olyson . Yes as these files are not related to a release it seems that they should not be available in the CLM input data directory. I continue to have people use these files and find the same issue. Peter

**Comment by olyson** [comment]
The user reports: " I found the files by looking in the input directories for CLM while setting up some experiments using a user-defined compset within CESM2.2.0 - I was interested in how land use changed in different SSP scenarios so these files seemed like the right place to look."
My last thought on this is that maybe we can zip the files?  That way they stand out and we also don't lose them in our history.

**Comment by ekluzek** [comment]
I saw this searching for issues with cesm2.2. I'm zipping the files on glade in Cheyenne so they will be flagged as be "weird" which might help. If someone runs a case with older code, though they'll reappear and they won't realize the zipped version of the files are there. So it might help...
