### ISSUE TITLE
why are  pct_sand and pct_clay not zero  over greenland in surface datasets?

### ISSUE THREAD

**Issue by mvertens** [ESCOMP/CTSM#1645]
### Brief summary of bug
why are  pct_sand and pct_land not zero  greenland in surface datasets?

In refactoring the surface dataset generation to be parallel (both in regridding and io) - I am encountering the following issue.
- If you look at the mapunit output for the input soil texture dataset - surfdata_1.9x2.5_hist_78pfts_CMIP6_simyr2000_c190304.nc you see that over greenland it is set to 6998. 
- If you then check the value of pct_sand and pct_clay in for a mapunit of 6998  - it is 0.
- From what I can see of the code in mksurfdata_map/src/mksrfdata.F90 - there is a forced setting of loam values only over points where the pctlnd_pft values are less than 1.e-6. This is not the case for greenland. 
- My new code gives me a pctland of zero over greenland - but this is NOT the case when comparing to the following release surface dataset: `/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_map/releaseclm5.0.18/surfdata_1.9x2.5_hist_78pfts_CMIP6_simyr2000_c190304.nc`

Am I missing something - or is this a real problem?

### General bug information

**CTSM version you are using:** ctsm5.1.dev070

**Does this bug cause significantly incorrect results in the model's science?** If this is a bug in the surface datasets previously created - then the answer is yes.

**Configurations affected:** [Fill this in if known.]

### Details of bug

[Fill in details here.]

### Important details of your setup / configuration so we can reproduce the bug
Rerun the surface dataset generation code to regenerate the released surface dataset.

**Comment by mvertens** [comment]
I see what I am missing - the land mask over greenland is mostly zero - so my new code is not treating the masking correctly. There is no problem with the current implementation.

**Comment by mvertens** [comment]
@olyson - I am actually re-opening the issue. Why are we masking out greenland in the surface dataset. If we don't mask it out - the we get zero %sand and %clay - which makes a lot more sense to me.

**Comment by slevis-lmwg** [comment]
I labeled "wontfix" because this pertains to mksurfdata_map.

**Comment by ekluzek** [comment]
Part of the question here was if mksurfdata_esmf was correct in this respect. Looking at the ctsm5.2.0 datasets I see that the behavior is the same as mksurfdata_map so I'm closing as a wontfix.
