### ISSUE TITLE
The c3psn list in CTSM's params files has four crops set incorrectly

### ISSUE THREAD

**Issue by slevis-lmwg** [ESCOMP/CTSM#1652]
### General bug information

**Does this bug cause significantly incorrect results in the model's science?** If millet and sorghum are used, then maybe.

**Configurations affected:** If millet and sorghum are used, then the crop configuration.

### Details of bug

`c3psn` in CTSM's params files sets most pfts/cfts to 1. It sets the following pfts/cfts to 0:
pft 14: c4 grass
pfts 17-18: temperate corn
pfts 67-68: sugarcane
pfts 71-76: miscanthus, switchgrass, tropical corn

However, it should also set the following pfts/cfts to 0:
pfts 51-52: millet
pfts 63-64: sorghum

I likely assembled this c3psn list many years ago. I don't remember if there was a reason to set c3psn = 1 for millet and sorghum, so I am opening this issue.

### Relates to issue

#342 seems to have addressed the same problem but for the `medlynslope` parameter only.

**Comment by billsacks** [comment]
These currently map to tropical corn, but it could be an issue long-term or for anyone who tries to run these crops.

**Comment by wwieder** [comment]
Seems like this is an error on the parameter file that currently doens't change answers.  This would be nice to fix, but not critical.

**Comment by wwieder** [comment]
Could be brought in with PPE work

**Comment by slevis-lmwg** [comment]
In prep. for PPE, I will update the latest param files, so that @linniahawkins can start with the correct value.
