### ISSUE TITLE
gddplant_patch (GDDPLANT) is misleadingly named

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#1655]
The output variable `GDDPLANT` is described as "Accumulated growing degree days past planting date for crop." Its corresponding variable in `CropType` is `gddplant_patch`: "patch accum gdd past planting date for crop (ddays)." Arguably, these are both misleadingly named and described because of the following in `CropPhenology()` (where `hui => crop_inst%gddplant_patch`):
https://github.com/ESCOMP/CTSM/blob/d9ae4b48d9c55fe3c998019bcf76817da570db87/src/biogeochem/CNPhenologyMod.F90#L2044-L2046
This bumps `gddplant_patch` up to the value where grain filling will begin if the crop has already reached peak LAI before that many GDDs have actually accumulated. Thus, `gddplant_patch` is not an actual measurement of GDD accumulation. (As far as I can tell, this is the only place anything like this happens.)

This might not have been an issue for anyone before, but it means I need to add a new output variable for my work on #519.

How I'm thinking this should be fixed:
- Rename `gddplant_patch` to `hui` ("heat unit index"), as it is more of an index than an actual measurement. `hui` makes sense because that's how `gddplant_patch` is typically `associate`d in the code.
- Rename `GDDPLANT` to `HUI`.
- Make a new variable in `CropType`, `gddaccum_patch`, to actually track the GDDs accumulated.
- Make a new output variable, `GDDACCUM`, to track `gddaccum_patch`.

This provides a complete separation from previous variable and output names and will thus break any postprocessing scripts that rely on `GDDPLANT`, but I consider that a feature, because it will force users to choose whichever of the new outputs is right for them. It's entirely possible that, as for me, `GDDPLANT` wasn't what they were expecting.

For consistency with the first bullet point, the `CNVegStateType` member `gddmaturity_patch` ("patch growing degree days (gdd) needed to harvest (ddays)") should be renamed `huimaturity_patch`. This would also be consistent with the existing `huileaf_patch` and `huigrain_patch`, also in `CNVegStateType`.

As far as I can tell—although I haven't done a very thorough check—it doesn't seem that any parts of the code using `gddplant_patch` or `gddmaturity_patch` were actually expecting true GDDs accumulated. Instead, it all looks like the HUI is expected, so I don't think anything needs to be reworked. But again, someone should check me on that.

**Comment by billsacks** [comment]
Thanks for the detailed description @samsrabin . I haven't looked at the relevant code, but your description makes sense, and based on that, I agree with your suggestions.

@danicalombardozzi do you want to provide input when you get a chance?
