### ISSUE TITLE
ERROR in BalanceCheckMod.F90

### ISSUE THREAD

**Issue by tilmes** [ESCOMP/CTSM#1657]
### Brief summary of bug
I am running the latest CESM2 version using 2 different configurations, WACCM middle atmosphere, and CAMchem (with a new aerosols scheme). Both simulations experience sometimes that this error in the model is triggered: ERROR in BalanceCheckMod.F90 at line 765 , which happens only at the last day of the year, so December 31st. There seems to be something triggering this error, at the same day for any year. After running one day in ignoring the end run call in the Balance Check, the model continues running without a problem.

[Give a one or two sentence summary. This could be the same as the issue title if you feel that is a sufficient summary.]

### General bug information

**CTSM version you are using:** cam6_2_003-1935-g9d4415d8
compset: HIST_CAM60%CARMATS%NUDG_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV_SIAC_SESP
Model case: /glade/p/cesm/chwg_dev/tilmes/cases/carma/FCnudged_f19.carma_trop_strat.2000.wetdep.test3

**Does this bug cause significantly incorrect results in the model's science?** No
It stops the model, ignoring the endrun does not seem to be a problem.

**Configurations affected:** 

### Important details of your setup / configuration so we can reproduce the bug

This has been experience in a sandbox, more information can be provided:
 /glade/work/fvitt/camdev/carma_trop_strat/

**Comment by billsacks** [comment]
Are the affected runs using a Gregorian calendar? @olyson recently discovered some balance check errors that are triggered in transient runs with a Gregorian calendar, which we fixed in ctsm5.1.dev073 (made Jan 25) (see #1593).

**Comment by tilmes** [comment]
Yes, these problems  happened while using a Gregorian calendar. Are there any code changes I can  use?

**Comment by ekluzek** [comment]
@tilmes I think the easiest way for you to try this would be to have @fvitt update the Sandbox by updating the clm version in Externals.cfg from ctsm5.1.dev069  to ctsm5.1.dev073. I think that should work for you. If we have to you could try some code mods, but just getting the newer version is likely the easiest first thing to try.

**Comment by tilmes** [comment]
OK, we can try that, thanks!

**Comment by ekluzek** [comment]
@tilmes I'm thinking that since we haven't heard from you, that this is now resolved? As such I'm closing, but feel free to reopen if it's still an issue.
