### ISSUE TITLE
Make options in some tools more similar to each other for modify_fsurdat and subset_data

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1662]
There are some tools that use different terms for doing essentially the same thing. We should consolidate these to one way of doing the same thing.

modify_fsurdat and subset_data all have some similar options:

The following list of options operate on the same things, but call them something different
modify_fsurdat: configure file options
dom_plant
zero_nonveg
std_elev
max_sat_area
subset_data:
--dom_pft
--include-nonveg
--uniform-snowpack (sets STD_ELEV to 20)
--cap-saturation (sets FMAX to zero)

@negin513 pointed this out in #1615

**Comment by ekluzek** [comment]
Also modify_fsurdat should have a line in the tools README file, and likely a README file in it's directory as well. And we should have some documentation that describes when you use it as opposed to subset_data.

**Comment by slevisconsulting** [comment]
Thank you, @ekluzek , this makes sense to me.

I think it also makes sense to make each tool even more specific in its purpose. In this case subset_data would specialize in subsetting global fsurdat files to regional or 1x1, while fsurdat_modifier would specialize in modifying global fsurdat files. This way users would understand which tool to use for what purpose and would proceed in this order according to need:
- mksurfdata to generate new global fsurdat
- fsurdat_modifier to modify global fsurdat
- subset_data to go from global to regional or 1x1

**Comment by ekluzek** [comment]
We've scheduled a meeting in a few weeks to discuss this with a subgroup.

Note, that currently subset_data when used for a single-point also modifies the dataset with some options. I think this is still good to do, as otherwise we'd need to run subset_data and then a modify script afterwards. This makes it a one step process for most single-point datasets.

Anyway, we'll have the subgroup discuss and present recommendations about moving forward.

**Comment by wwieder** [comment]
Hi Erik.  if you think it's helpful I'm happy to come to these meetings.

**Comment by wwieder** [comment]
In our call today we agreed that this fell into the category of _wouldn't it be nice_ feature, but not an issue that's critical to address right now.  

@negin513 noted that if the modify_fsurdat tool is something that is used beyond its immediate user community we can work to harmonize the user interface and code interoperability.  

@slevisconsulting noted that the duplication here reflects the simultaneous work that was being done for two different projects.  

@adrifoster emphasized the value of creating a design document for each project / PR to help guide our coding practices.

@ekluzek agreed that this isn't critical to address right now, but something to be aware of moving forward.

All, please add to these notes if I missed anything

**Comment by slevisconsulting** [comment]
Let me just add that I will be happy to spend time on eliminating redundancy and making the user interfaces more similar between these tools, but such time would need to be signed off by Isla Simpson and Scott Bachman.

**Comment by wwieder** [comment]
Thanks @slevisconsulting , do you want to ask Scott and Isla about this?  If they're not supportive of this, maybe we should close the issue with a won't fix?

**Comment by slevisconsulting** [comment]
> do you want to ask Scott and Isla about this?

I will raise the question at an upcoming meeting with them.

**Comment by slevisconsulting** [comment]
Good news:
Isla and Scott support my charging CSSI time toward eliminating redundancy and making the user interfaces more similar between these tools.

**Comment by wwieder** [comment]
this is good news!  thanks for following up, Sam.

**Comment by slevisconsulting** [comment]
Adding a relevant thought here to avoid forgetting:
The `write_output` function has the potential of looking the same in these tools (modify_fsurdat, subset_data, and modify_mesh #1677), so we may be able to avoid repetition there, too.

**Comment by ekluzek** [comment]
@slevisconsulting your explanation above makes sense to me. 

However, if I understand both scripts I do think that dom_plant and dom_pft represent the same thing. If you want to set something to a crop CFT you set with --dom_pft in subset_data. So I think we should use dom_pft in modify_fsurdat. I think you are right that this was different in earlier versions of subset_data.

**Comment by ekluzek** [comment]
@slevisconsulting is this taken care of now? Or is there more to do here?

**Comment by slevisconsulting** [comment]
> @slevisconsulting is this taken care of now? Or is there more to do here?

Yes, I consider this done. At some point -- I don't rememer when -- I changed dom_plant to dom_pft for consistency with subset_data.
