### ISSUE TITLE
Remove override options from mksurfdata process

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1664]
mksurfdata previously as part of PTCLM included some override options for creating single point tower sites. We've moved our process over from being inside of mksurfdata to outside tools that do this functionality in subset_data and modify_fsurdat.

So the following options in mksurfdata.pl can be removed (as well as the corresponding changes in the mksurfdata_map code). It looks like they were already removed in toolchain/gen_mksurf_namelist, since we realized they didn't need to be moved to the new toolchain process.

> OPTIONS to override the mapping of the input gridded data with hardcoded input
> 
>      -pft_frc "list of fractions"  Comma delimited list of percentages for veg types
>      -pft_idx "list of veg index"  Comma delimited veg index for each fraction
>      -soil_cly "% of clay"         % of soil that is clay
>      -soil_col "soil color"        Soil color (1 [light] to 20 [dark])
>      -soil_fmx "soil fmax"         Soil maximum saturated fraction (0-1)
>      -soil_snd "% of sand"         % of soil that is sand

**Comment by billsacks** [comment]
This is done on the 5.2 branch.

**Comment by slevisconsulting** [comment]
> This is done on the 5.2 branch.

@ekluzek 
I'm closing this PR as "done on the 5.2 branch."
Let me know if I should reopen.
