### ISSUE TITLE
Isotopic values of grain_mr not set correctly when use_grainproduct is false

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1666]
### Brief summary of bug

From reading through the code, it looks like isotopic values of grain_mr are not set correctly when use_grainproduct is false. This could then impact other summary variables that depend on grain_mr – such as total ecosystem respiration.

### General bug information

**CTSM version you are using:** master

**Does this bug cause significantly incorrect results in the model's science?** Yes - but only for C isotopes in crop runs with use_grainproduct false (typically just the case in clm4_5 runs)

**Configurations affected:** Configurations with C isotopes and crops with use_grainproduct false (typically just the case in clm4_5 runs)

### Details of bug

The problem appears here:

https://github.com/ESCOMP/CTSM/blob/157f7192090267c4f65aaf5e31abfb45a16a4a22/src/biogeochem/CNCIsoFluxMod.F90#L479-L487

This was introduced in clm4_5_16_r255, which made a bunch of changes to get crops working with C isotopes. The first line in the block (setting grainc_to_cropprodc_patch) is correctly only done if use_grainproduct is true, but I'm pretty sure the second line (setting grain_mr_patch) should be done regardless of the value of use_grainproduct.

use_grainproduct is typically true in clm5_0 (and later) runs and false in clm4_5 runs. So this would impact runs that use C isotopes with crop with clm4_5. We don't have any aux_clm tests of that configuration.

Since this doesn't impact any tests, I'll go ahead and fix it in an upcoming tag.

@danicalombardozzi @ekluzek @ckoven

**Comment by billsacks** [comment]
@danicalombardozzi @ekluzek @ckoven From looking through the code I'm pretty sure this is wrong and should be changed as I mention above, but let me know if you think differently.

**Comment by billsacks** [comment]
I have fixed this on a branch that I'll bring in with other changes (21c305be17484c74c0c856d66987df659ad41ec3). I ran the following tests (which are not part of our standard testing):

```
ERP_D_Ld10_P36x2.f10_f10_mg37.IHistClm45BgcCrop.cheyenne_intel.clm-ciso_decStart
ERP_Ld3.f09_g17.I1850Clm45BgcCrop.cheyenne_intel.clm-ciso
ERS_Ly5_Mmpi-serial.1x1_smallvilleIA.I2000Clm45BgcCropQianRs.cheyenne_gnu.clm-ciso_monthly
LCISO_Lm13.f10_f10_mg37.IHistClm45BgcCrop.cheyenne_intel.clm-ciso_monthly
SMS_Ly2_P72x1.f10_f10_mg37.I1850Clm45BgcCrop.cheyenne_gnu.clm-ciso--clm-cropMonthOutput
```

All tests passed both before and after this fix. Baselines were bit-for-bit for three tests but differed for:

```
ERP_D_Ld10_P36x2.f10_f10_mg37.IHistClm45BgcCrop.cheyenne_intel.clm-ciso_decStart
SMS_Ly2_P72x1.f10_f10_mg37.I1850Clm45BgcCrop.cheyenne_gnu.clm-ciso--clm-cropMonthOutput
```

Baseline differences were only in the fields: C13_AR, C13_NBP, C14_AR, C14_NBP

Due to #1358 these fields (as with other C isotope fields) are currently garbage, so it's hard to assess whether this change is definitely correct or not, but from my understanding of the code, I'm pretty sure it's right. So I'm planning to go ahead with it unless anyone objects.

**Comment by danicalombardozzi** [comment]
Thanks for catching and correcting this problem @billsacks!
