### ISSUE TITLE
Update FATES documentation

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1671]
@glemieux is working on i[mproving the FATES documentation](https://fates-users-guide.readthedocs.io/en/latest/index.html).  

Should the replace the FATES documentation that's currently in the [CTSM tech note](https://escomp.github.io/ctsm-docs/versions/master/html/tech_note/DGVM/CLM50_Tech_Note_DGVM.html#technical-documentation-for-fates) from @rosiealice 's 2015 paper with a link to the updated FATES-side documents?

**Comment by billsacks** [comment]
From today's ctsm software discussion: probably leave the CLM5.0 documentation as is, change the latest to just be a pointer to Greg's documentation.

**Comment by adrifoster** [comment]
I believe this is closed now. Not sure why it didn't get closed when the PR came in....

**Comment by ekluzek** [comment]
@adrifoster to get an issue to autoclose in a PR you have to put them on one line each issue, with a declaration word just in front of it. So

Closes #1671

For example. Lots of other words can be used: fixes, fixed, resolve, resolved etc...

This has been confusing for many people!
