### ISSUE TITLE
cesm-lab-2.2 container run issue

### ISSUE THREAD

**Issue by khorsans** [ESCOMP/CTSM#1679]
Dear all,
I used FWscHIST compset with f09_f09_mg17 resolution to run the cesm model. But unfortunately, I encountered an error while running the model. I pulled the escomp / cesm-lab-2.2 container and I want to run the model through Docker. I will send you the errors during the execution. Thank you for your help.

yours sincerely,
Parisa
![Capture3](https://user-images.githubusercontent.com/56936152/157203266-2abb14f7-b8fe-4d91-8868-f40c5c15ebcc.PNG)
[cesm_log.txt](https://github.com/ESCOMP/CTSM/files/8204382/cesm_log.txt)

**Comment by negin513** [comment]
Thanks Parisa for creating this issue. 
This is a temporary issue cause by change of servers from neon side. We are currently working on fixing this issue. 

I will get back to you on how to proceed with this.

**Comment by negin513** [comment]
For my own reference, I am linking the related issues here:

- CTSM/Issue #1668 
- CTSM/Issue #1675 
- [Related forum post from another user](https://bb.cgd.ucar.edu/cesm/threads/cannot-see-submit-job-case-st_archive.7126/)

**Comment by khorsans** [comment]
Dear Negin,
Thank you for your prompt reply. I look forward to hearing from you.

Best regards,
Parisa

**Comment by khorsans** [comment]
Dear Negin,

I happened to look at the DiscussCESM Forums section and came across a
similar problem with myself. But here it does not mention the server
problem. I will send you the link.

https://bb.cgd.ucar.edu/cesm/threads/error-in-running-cesm213-pio_support-pio_die-myrank-1-error-ionf_mod-f90-235.7150/

Best Wishes

**Comment by negin513** [comment]
Dear Parisa,
We have created a new container image with some updates regarding neon workflow. 
Can you please try pulling the new container image and rerun this to see if this issue is resolved?

You can update your container image by:
```
docker pull escomp/ctsm-lab-2.3-preview
``` 
Are you running a global simulation or a single point simulation?

Please let us know if you are still having a problem with this. 
Thanks!
Negin
