### ISSUE TITLE
Create FATES-SP compset

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1697]
It seems like FATES-SP should be a major configuration of CTSM that warrants its own compset. 

@adrifoster explained: There's no specific compset for SP, you have to use the user_nl_clm file to set it up (https://fates-users-guide.readthedocs.io/en/latest/user/Namelist-Options-and-Run-Time-Modes.html):

This is what I use:
```
Compset: 2000_DATM%GSWP3v1_CLM50%FATES_SICE_SOCN_SROF_SGLC_SWAV

user_nl_clm changes:
 use_fates_sp = .true.
```
.... with many other user_nl_clm chaanges

@ekluzek mentioned this requires some code refactoring to facilitate.  

Is the refactoring just on the CTSM side, or also on FATES @glemieux @rgknox?  
If also for FATES, let's create a parallel issue in the FATES repository.

**Comment by ekluzek** [comment]
Personally I envision it would be mostly in CTSM. And we'd add a compset as well as a build-namelist trigger for this. There's a couple different options on how this would be done, and we need to iteratively start from where we are to the final solution.

It's possible this would be moved to a higher level in FATES, but I don't even see how that would be done. So we'll discuss this more.

**Comment by ekluzek** [comment]
Some of the refactoring I mention is talked about in #942. And this document...

https://docs.google.com/spreadsheets/d/1wwI_RuQ87FNk4PdrSLtlplisEMTRqDCxFeqG6Wbxt_

**Comment by rgknox** [comment]
I agree, there should be no refactoring necessary on the FATES side.  I would expect the compset would generate the use_fates_sp setting, and that would continue to be passed in the same as it was before.

**Comment by wwieder** [comment]
In the SE meeting we agreed that the long-term goal of a CTSM-FATESsp compset is desired, as  for CTSM-SP runs, but for the purposes of the tutorial we'll just use namelist changes to set up this case.

**Comment by billsacks** [comment]
This has been done.
