### ISSUE TITLE
Example, user_nl_datm_streams for TRENDY.2020 simulation for NUOPC coupler

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1701]
The previous years TRENDY simulations were done using the MCT coupler and hence the user_datm.streams.txt.* files that were used no longer function for the NUOPC coupler. As such we need to develop new user_nl_datm_streams example files that can be used for this type of purpose.

**Comment by ekluzek** [comment]
I have a sample that creates the namelist and streams files.

It relies on the following setting of DIN_LOC_ROOT_CLMFORC

`./xmlchange --force DIN_LOC_ROOT_CLMFORC="/glade/p/cgd/tss/people/dll/TRENDY2020_Forcing"`

[user_nl_datm_streams.txt](https://github.com/ESCOMP/CTSM/files/8457706/user_nl_datm_streams.txt)

An example from the file for CO2 is like this:

```
   ! CO2 time series for TRENDY 1700 to 2020
   co2tseries.20tr:year_first = 1700
   co2tseries.20tr:year_align = 1700
   co2tseries.20tr:year_last  = 2020
   co2tseries.20tr:datafiles = $DIN_LOC_ROOT_CLMFORC/fco2_datm_global_simyr_1750-2014_CMIP6_c180929.nc
```

**Comment by ekluzek** [comment]
One issue with the above is that previously for TRENDY we used a domain file that had a land-mask. The mesh standard mesh file being used here is 1 everywhere.

The other issue I have with actually running the above case is that there are some NetCDF4 files somewhere in the list that the model can't read.

**Comment by ekluzek** [comment]
The CO2 file is fine, but it looks like the forcing files are in NetCDF-4 format and will need to be converted.

**Comment by dlawrenncar** [comment]
I think it varies.  Sometimes they just add a year, but often, e.g., when
they find a bug or some other limitation, they update the entire record.

**Comment by dlawrenncar** [comment]
@olyson converted some files for testing.  There are ten years here (1901-1910):
/glade/p/cgd/tss/people/oleson/TRENDY2020_Forcing/three_stream_files

These were converted from: /glade/p/cgd/tss/people/dll/TRENDY2020_Forcing/three_stream_files/

**Comment by dlawrenncar** [comment]
@ekluzek I tried to run using the user_datm_streams from above, and the converted files, but am getting the following error in the cesm log file.

26: ERROR:
26: (datm_init_pointers): ERROR: wind and tbot must be in streams for CLMNCEP

WIND and TBOT which point to wind and tbot are on the files that Keith converted, so I'm not sure where the error is coming from.  My case is here, which is running from the most modern ctsm.

/glade/u/home/dlawren/cases/clm5sp_hd_crujra2020_createICs

**Comment by olyson** [comment]
@ekluzek can confirm but I think the stream variable names have changed:

swdndr -> Faxa_swdndr
swdndf -> Faxa_swdndf
precn -> Faxa_precn
tbot -> Sa_tbot
wind -> Sa_wind
shum -> Sa_shum
pbot -> Sa_pbot

**Comment by dlawrenncar** [comment]
OK.  Tried removing the datavars from user_nl_datm_streams and am now getting more standard errors on the first timestep.  

 g, newsum_lwrad_g, sum_wts_g, forc_lwrad_g:            4
  3.970527130136304E+112  0.990000000000000       4.010633464784145E+112
iam = 0: local  gridcell index = 4
iam = 0: global gridcell index = 5470
iam = 0: gridcell longitude    =  214.7500000
iam = 0: gridcell latitude     =  -86.2500000
 ENDRUN:
 ERROR:
  ERROR: Energy conservation error downscaling longwaveERROR in atm2lndMod.F90 a
 t line 561

Note that I also tried running at the more standard f09 resolution, because I know that we have had problems with the 0.5degree resolution before (though using out of box CRUNCEP forcing, it ran fine at this resolution).  With the f09 resolution, I got a column-level water balance error instead.  Maybe the mesh file being 1 everywhere is a problem, especially if the actual realistic data coverage in the CRUJRA forcing is not complete, which I think it is not.

**Comment by dlawrenncar** [comment]
@ekluzek Do you have any updates on a process to create a new mesh file for CRUJRA that would work?

**Comment by ekluzek** [comment]
I had trouble with the script, but worked with @uturuncoglu to get it working. I used the following conda environment in a requirements text file, that @uturuncoglu helped me to put together.

python=3.9.7
numpy=1.21.2
dask=2021.2.0
xarray=0.17.0
pandas=1.4.1
netcdf4=1.5.7

There was also a change to the script to recast mask as a dask array when it was created.

I put a copy of the file here:

/glade/p/cesmdata/cseg/inputdata/share/meshes/clmforc.crujra200728.cdf5.c2016.0.5d.ESMFmesh_c20220504.nc

The user_nl_datm_streams file also needs the addition of the following:

```
   CLMCRUNCEPv7.Solar:meshfile = $DIN_LOC_ROOT/share/meshes/clmforc.crujra200728.cdf5.c2016.0.5d.ESMFmesh_c20220504.nc
   CLMCRUNCEPv7.Precip:meshfile = $DIN_LOC_ROOT/share/meshes/clmforc.crujra200728.cdf5.c2016.0.5d.ESMFmesh_c20220504.nc
   CLMCRUNCEPv7.TPQW:meshfile = $DIN_LOC_ROOT/share/meshes/clmforc.crujra200728.cdf5.c2016.0.5d.ESMFmesh_c20220504.nc
```

**Comment by dlawrenncar** [comment]
I tried with this new mesh file, but am running into a different problem, not sure if this is related to NUOPC or not.  I am setting DIN_LOC_ROOT_CLMFORC in env_run.xml to the location of some TRENDY data that @olyson has stored for me.
    <entry id="DIN_LOC_ROOT_CLMFORC" value="/glade/p/cgd/tss/people/oleson/TRENDY2020_Forcing">

But, the datm.streams.xml file doesn't seem to be picking this up.  The user_nl_datm_streams file has lines like this:

   CLMCRUNCEPv7.Solar:datafiles = $DIN_LOC_ROOT_CLMFORC/three_stream_files/clmforc.TRENDY.c2020.0.5x0.5.Solr.1901.nc, \

But the resulting datm.streams.xml file has lines like this (pointing to the wrong location, and probably the out of the box location):
  <file>/glade/p/cesmdata/cseg/inputdata_CLMFORC/three_stream_files/clmforc.TRENDY.c2020.0.5x0.5.Solr.1901.nc</file>

Case directory is here: /glade/u/home/dlawren/cases/clm5sp_hd_crujra2020_createICs

**Comment by dlawrenncar** [comment]
I checked and it looks like adding the line
    CLMCRUNCEPv7.Solar:meshfile = $DIN_LOC_ROOT/share/meshes/clmforc.crujra200728.cdf5.c2016.0.5d.ESMFmesh_c20220504.nc
into user_nl_datm_streams changes the outcome of the datm.streams.xml file.  If that line is in user_nl_datm_streams, then the value of $DIN_LOC_ROOT_CLMFORC in env_run.xml is ignored and the default is used instead.

**Comment by ekluzek** [comment]
@dlawrenncar your last result is really odd to me. But, it makes me wonder if you copy the mesh file pointed to inside of $DIN_LOC_ROOT_CLMFORC/three_stream_files/ if that would work? I actually intended to do that, but didn't have permission. @olyson could you open up /glade/p/cgd/tss/people/oleson/TRENDY2020_Forcing to group write so that we could add files there?

**Comment by olyson** [comment]
Ok, done.

**Comment by dlawrenncar** [comment]
To be clear, adding this (and equivalents for Precip and TPQW) to user_datm_streams worked:

CLMCRUNCEPv7.Solar:meshfile = $DIN_LOC_ROOT_CLMFORC/three_stream_files/clmforc.crujra200728.cdf5.c2016.0.5d.ESMFmesh_c20220504.nc

**Comment by dlawrenncar** [comment]
@olyson Could you convert (not sure what needed to be converted anymore, can't remember) the rest of the 2020 CRU-JRA forcing dataset?

**Comment by wwieder** [comment]
I wondered if we should also have a discussion on input datm data we'll support moving forward for CTSM development?  Could be a topic for the Thursday  SE and Science meetings?

**Comment by ekluzek** [comment]
OK, there is an issue to resolve about supporting CRUJRA, but the core of this issue having an example for TRENDY is now done.
