### ISSUE TITLE
Input files missing for ne120pg3 grid

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CTSM#1704]
@hanli-liu would like to run FXHIST compset on ne120pg3 grid.  However, needed input file(s) are not found by default.

See error message:

ERROR: Command /glade/work/fvitt/camdev/cam6_3_054/components/clm/bld/build-namelist failed rc=255
out=
err=ERROR : CLM build-namelist::CLMBuildNamelist::add_default() : No default value found for flanduse_timeseries.
            Are defaults provided for this resolution and land mask?

Grid and compset details:
  GRID: a%ne120np4.pg3_l%ne120np4.pg3_oi%ne120np4.pg3_r%r05_g%null_w%null_z%null_m%gx1v7
  COMPSET: HIST_CAM60%WXIE_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV_SESP

**Comment by ekluzek** [comment]
We on purpose didn't create landuse.timeseries for these high resolution cases. I would suggest that you use either the 1850 or 2000 surface dataset and hold the landuse constant.

The way to do that is to add this to the user_nl_clm

flanduse_timeseries = ' '

That will use the 1850 surface dataset. If the 2000 dataset is more appropriate you'll have to set that in the user_nl_clm as well.

**Comment by ekluzek** [comment]
If you do really need a landuse.timeseries dataset, we could produce it. In a lot of cases though you don't need the full 1850 to 2015 length and for these high resolution datasets we might as well cut it short to just the years that you will need.

**Comment by hanli-liu** [comment]
Thanks. We are making a short run for a geomagnetic storm. So a workaround like you suggested should work. If we want to use 2000 surface dataset, what do I set in user_nl_clm (in addition to setting flanduse_timeseries to null)?

**Comment by ekluzek** [comment]
@hanli-liu add this:

fsurdat = '$DIN_LOC_ROOT/lnd/clm2/surfdata_map/release-clm5.0.30/surfdata_ne120np4.pg3_hist_78pfts_CMIP6_simyr2000_c200427.nc'

**Comment by ekluzek** [comment]
Let me know if that's sufficient for you and I'll close this. Glad we could get something for you.

**Comment by hanli-liu** [comment]
I was able to build the case now with these two changes in user_nl_clm. I will submit a test job. Thanks, Erik!
