### ISSUE TITLE
Create create_test system test for running mksurfdata_esmf

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1717]
The new MPI program mksurfdata_esmf doesn't lend itself well to use the standard serial testing setup for the other tools. Since, all of the other tools are serial, it wouldn't be efficient to have some tests serial and some using multi-processors. So a better way to do it is to take advantage of the batch capability in cime create_test SystemTests and create a python test that builds and runs mksurfdata_esmf. Having at least system tests for mksurfdata_esmf will be critical in being able to bring it to CTSM main-dev. We also should assess adding unit testing for the new mksurfdata_esmf (see https://github.com/ESCOMP/CTSM/issues/842#issuecomment-1098697255).

**Comment by mvertens** [comment]
@ekluzek - I do not think that we want to use any serial testing with the new create_test system. The whole reason for this new capability was to enable memory and performance scalability.  I don't think that the unit testing that is in place for other tools applies here. That said a system test would be helpful at some point. I am happy to discuss this in more detail.

**Comment by billsacks** [comment]
@ekluzek thanks for opening this issue. I think having a system test that runs mksurfdata_esmf and then runs the model with the created dataset would be great – that would show us both that mksurfdata_esmf works and also that you can run the model with the created surface dataset. I think this could follow a pattern similar to what @slevisconsulting and I put together recently to test the fsurdat_modifier tool: https://github.com/ESCOMP/CTSM/blob/master/cime_config/SystemTests/fsurdatmodifyctsm.py – although there may be some extra complexities here due to wanting to run mksurfdata_esmf on multiple nodes (as opposed to the single-processor run of fsurdat_modifier).

**Comment by mvertens** [comment]
@billsacks @ekluzek - I think all of this will become much easier once @jedwards4b and I have had a chance to update the build system for mksurfdata_esmf to be entirely CMake based. I would wait until then to have this implemented.

**Comment by billsacks** [comment]
I think the two pieces (system test and more general build) are likely orthogonal, as long as we only want to run the test on cheyenne (which I think is fine): I think it would be fine to put in place a system test with a fragile build system for now. That said, I'm not personally trying to push one way or the other in terms of prioritization of putting in place this system test.

**Comment by mvertens** [comment]
@billsacks - the reason I suggest waiting for the new build is because the commands to build the component will be different and not use a Makefile in the tools/mksurfdata_esmf/src/  directory. So the test would have to be rewritten with the new build.

**Comment by slevisconsulting** [comment]
I'm running into a problem on izumi and wanted to check whether this is expected. In the following sequence, the last command gives an error:
```
git checkout -b mksurfdata_esmf_sys_test ctsm5.2.mksurfdata
module load lang/python/3.7.0 
cd python
make utest
make stest
```
The first error says
`Current machine izumi does not match case machine ctsm-build`
and then the first three system tests fail with
`/fs/cgd/data0/slevis/git/mksurfdata_toolchain/python/ctsm/test/testinputs/surfdata_5x5_amazon_16pfts_Irrig_CMIP6_simyr2000_c171214.nc is not a valid NetCDF 3 file`
The last two failures (using LILAC) may be expected with what I'm running:
`alpha-ctsm5.2.mksrf.03_ctsm5.1.dev090`

Possibly relevant information:
`module list` shows only python loaded.

**Comment by jedwards4b** [comment]
The file /fs/cgd/data0/slevis/git/mksurfdata_toolchain/python/ctsm/test/testinputs/surfdata_5x5_amazon_16pfts_Irrig_CMIP6_simyr2000_c171214.nc is not a valid NetCDF file.

**Comment by slevisconsulting** [comment]
Ha! Didn't occur to me to check that because it used to be a valid netCDF file...

**Comment by slevisconsulting** [comment]
Thank you @jedwards4b

**Comment by slevisconsulting** [comment]
After conversation with @billsacks 
Added and trying this test
`./create_test MKSURFDATAESMF_P144x1.f19_g17.I1850Clm50BgcCrop.cheyenne_intel.clm-default`
