### ISSUE TITLE
Turn off unneeded soil BGC history file output

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1737]
I noticed that a bunch of MIMICS history outputs are being written out in BGC runs with CENTURY soil biogeochemistry.  Likewise, I'd assume that CENTURY specific variables are being written out for MIMICS simulations. 

If it's not too much work, I suggest we turn off missing / unused soil BGC variables to avoid user confusion.

**Comment by wwieder** [comment]
A *very* quick look of a CENTURY run suggests that this may be limited to `MICC_HR` & `TOTMIC*`, which I think are just MIMICS variables?  Maybe this isn't much of an issue, but it could use some deeper investigation?

**Comment by slevis-lmwg** [comment]
I thought this issue would have closed by my mentioning it as "fixed" in #1745, but I think I needed to repeat the word "fixes" before the number in order to accomplish that. In any case, I'm closing it.

**Comment by ekluzek** [comment]
@slevis-lmwg and @samsrabin and others. There's a couple things you have to do to get an issue to auto-close when it's mentioned in the PR. 
- Each issue needs to be on a separate line
- Each issue needs one of the acceptable verbs in front of it which are variations of: fix, close, or resolve
- The PR has to to to the main branch, and not a different branch (until the other branch comes to main)

Personally I always make the line start with "Fixes: " and then the issue, so there's nothing else on the line. But, I think additional text is actually OK as long as you have that verb in front of the issue.

You can also add it be auto-closed by adding the issue in the "Development" menu on the right side column, where labels and other descriptors can be set.

https://stackoverflow.com/questions/12235620/automatically-closing-issue-from-pull-request-in-github

**Comment by ekluzek** [comment]
@slevis-lmwg yeah looking at #1745 the reason it didn't auto-close is that it needed "Fixed:" on the same line in front of it.
