### ISSUE TITLE
NEON test failing on izumi in ctsm5.1dev095

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1743]
### Brief summary of bug

The NEON test is failing on izumi starting in ctsm5.1.dev095 with externals updates.

### General bug information

**CTSM version you are using:** ctsm5.1.dev095

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** NEON test case

### Details of bug

SMS_D_Mmpi-serial.CLM_USRDAT.I1PtClm51Bgc.izumi_nag.clm-default--clm-NEON-NIWO

### Important output or errors that show the problem

There is nothing in the cesm.log file. The lnd.log and med.log terminate early in initialization
The batch output says ending on signal 15.

**Comment by ekluzek** [comment]
@negin513 pointed out to me that perhaps @briandobbins changes need to come in here. And indeed when I set

`./xmlchange PIO_REARRANGER=2`

the test passes. I think this change should be put into the NEON user-mod so that it will apply whether run_neon.py is used or not.

**Comment by briandobbins** [comment]
It seems, per another thread, there's some uncertainty about this -- I'm
going to look into it next week in more detail.  Did it actually make a big
difference in your runs, Adrianna?  From what I saw, it looked like it
didn't change much, per the timing files.

Anyway, let's talk about it, as there's some confusion about this.

  - Brian

**Comment by jedwards4b** [comment]
I am looking into this now.   Seems to be a memory corruption issue.

**Comment by jedwards4b** [comment]
I've found the error in the NEON test - for NEON I created reduced sized lnfm files to reduce the amount of data transfer required for NEON datasets.  
 /glade/p/cesmdata/cseg/inputdata/atm/datm7/NASA_LIS/clmforc.Li_2016_climo1995-2013.360x720.lnfm_Total_NEONarea_c210625.nc
However the mesh file used is a full global mesh
 /glade/p/cesmdata/cseg/inputdata/atm/datm7/NASA_LIS/clmforc.Li_2016_climo1995-2013.360x720_ESMFmesh_cdf5_150621.nc

You need to either generate a reduced mesh file or use the original lightning file.

**Comment by jedwards4b** [comment]
We should do better error checking here:
https://github.com/ESCOMP/CDEPS/issues/164

**Comment by ekluzek** [comment]
This came up again, but I see that @jedwards4b gave us the solution of getting the right mesh file to go with the reduced lightning file. We do have a script to modify mesh files for a new grid now. A future version of CDEPS will have better error checking and notice this problem, but we aren't there yet, and we'll still need a new mesh file to use.

**Comment by wwieder** [comment]
OK, now I see this thread... can we generate this mesh file with the tools we have now, @ekluzek ?  @negin513 can't even run 200 years of AD spinup without running out of wall clock time, which seems pretty slow.

**Comment by ekluzek** [comment]
@wwieder yes I should be able to figure out the mesh tools in order to modify it as needed for the lightning file. I'll start working on that as part of the sparse grid work.

**Comment by ekluzek** [comment]
This is working now, and we don't have to set the PIO rearranger anymore. And we have the mesh file in place. So I think we've resolved everything around this.
