### ISSUE TITLE
WRF-CTSM zero soil moisture in wrfout files

### ISSUE THREAD

**Issue by negin513** [ESCOMP/CTSM#1757]
### Brief summary of bug

While running WRF-CTSM 4km simulations, I noticed that soil moisture is all zero in wrfout file (SMOIS and SH2O* )for all the soil layers, but soil moisture (H2OSOI) in CTSM history output files are showing valid values for different layers. This could be possibly due to an issue transferring soil moisture between WRF and CTSM. 

This means that potentially soil moisture from CTSM is not getting transferred back to WRF. 

*SMOIS from wrfout is "SOIL MOISTURE" in "m3 m-3" .
SH2O from wrfout is "SOIL LIQUID WATER" in "m3 m-3".
H2OSOI from CTSM output is "volumetric soil water (natural vegetated and crop landunits only)" in  "mm3/mm3". 

### General bug information

**CTSM version you are using:** ctsm5.1.dev088

**Does this bug cause significantly incorrect results in the model's science?** NA
**Configurations affected:** WRF-CTSM

### Details of bug

I have attached a screenshot showing the soil moisture discrepancy between WRF and CTSM history files:
![Screen Shot 2022-05-17 at 1 58 13 PM](https://user-images.githubusercontent.com/17344536/168900104-d103a803-07fd-4bc4-a618-97f4b5a943b7.png)

**Comment by billsacks** [comment]
If I remember correctly, we decided not to transfer soil moisture back to WRF, in part because it isn't a standard coupling field from CTSM, in part for performance reasons, and in part (the biggest part?) because WRF's representation of the soil layer structure doesn't match CTSM's.
