### ISSUE TITLE
CNDV bug: ntree used before it's set in pftconMod.F90

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#176]
**Erik Kluzek < erik > - 2017-08-25 18:31:41 -0600**
**Bugzilla Id:** [2506](http://bugz.cgd.ucar.edu/show_bug.cgi?id=2506)
**Bugzilla CC:**  dlawren,  mvertens,  rfisher,  slevis, 

Sam Levis found this problem. The variable ntree is used before it's set in pftconMod.F90, which means the variable "tree" will be set incorrectly. It looks like the only use of the variable "tree" is when Dynamic Vegetation is used in CNDVLightMod.F90.

This goes back to the beginning of pftconMod.F90 in some refactoring that went on in clm4_5_1_r097.

**Comment by billsacks** [comment]
It looks like this is truly a bug that just impacts CNDV (specifically, in CNDVLightMod, through its use of `tree`).

**Comment by ekluzek** [comment]
Since, we've deprecated CNDV, I'm closing this as a wontfix.

**Comment by ekluzek** [comment]
This was refactored in #1016 so this problem no longer applies. ntree is technically still in the code, but it's not used anymore.
