### ISSUE TITLE
Slow single point throughput

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1761]
### Brief summary of bug

- @adrifoster noticed very slow production in single point cases that was running with `PIO_REARRANGER_LND=1`
her case directory is here: /glade/u/home/afoster/tutorial_spinup/I2000_CTSM51_spinup
- @briandobbins suggested using `PIO_REARRANGER_LND=2` to try and speed things up.

### General bug information

Generally, it would be helpful to figure out what NEON and single point cases need to run efficiently on different systems.

**Comment by ekluzek** [comment]
This is related to #1743. The fix we did there was just for NEON, but yes it's likely required for all single point cases, and it really should be set in cime.

**Comment by wwieder** [comment]
Is there anything that can be done to make single point cases run more efficiently?  Currently @negin513 can't run 200 years  in < 6 hour wall clock time, even with limited history file output.  This kind of throughput seems kind of absurdly low.  Why have things slowed down so much?

**Comment by ekluzek** [comment]
I'm going to close this since we think the issue had to do with the lightning mesh file.
