### ISSUE TITLE
Bug in CNFireFluxes for m_livestemc_to_litter_fire, m_livestemc_to_deadstemc_fire, m_deadstemc_to_litter_fire, m_livecrootc_to_litter_fire

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#178]
**Erik Kluzek < erik > - 2017-09-27 11:59:43 -0600**
**Bugzilla Id:** [2516](http://bugz.cgd.ucar.edu/show_bug.cgi?id=2516)
**Bugzilla CC:**  dlawren,  lifang,  oleson,  rfisher, 

This goes back to the first versions of CLM4.5 fire. This problem was found by Hui Tang. We don't believe they cause a large change to the climate, but seem to be more intuitively correct.

Setting of the following arrays in CNFireFluxes had an incorrect term in them:
m_livestemc_to_litter_fire, m_livestemc_to_deadstemc_fire, m_deadstemc_to_litter_fire, m_livecrootc_to_litter_fire

The m_*_fire arrays are all in units of gC/m2/s, and are the fire emissions of Carbon from the given type.

Here's the change for CNFireBaseMod.F90 in clm4_5_16_256 (the same change also needs to go into CNFireLi2014Mod.F90 as well for clm4_5).

```
@@ -650,7 +651,7 @@
              fm_other(patch%itype(p))
         m_livestemc_to_litter_fire(p)               =  livestemc(p) * f * &
              (1._r8 - cc_lstem(patch%itype(p))) * &
-             fm_droot(patch%itype(p))    
+             fm_lstem(patch%itype(p))    
         m_livestemc_storage_to_litter_fire(p)       =  livestemc_storage(p) * f * &
              (1._r8 - cc_other(patch%itype(p))) * &
              fm_other(patch%itype(p))
@@ -659,10 +660,10 @@
              fm_other(patch%itype(p))
         m_livestemc_to_deadstemc_fire(p)            =  livestemc(p) * f * &
              (1._r8 - cc_lstem(patch%itype(p))) * &
-             (fm_lstem(patch%itype(p))-fm_droot(patch%itype(p)))
+             (fm_lstem(patch%itype(p))-fm_dstem(patch%itype(p)))
         m_deadstemc_to_litter_fire(p)               =  deadstemc(p) * f * m * &
              (1._r8 - cc_dstem(patch%itype(p))) * &
-             fm_droot(patch%itype(p))    
+             fm_dstem(patch%itype(p))    
         m_deadstemc_storage_to_litter_fire(p)       =  deadstemc_storage(p) * f * &
              (1._r8 - cc_other(patch%itype(p))) * &
              fm_other(patch%itype(p))
@@ -678,7 +679,7 @@
              (1._r8- cc_other(patch%itype(p))) * &
              fm_other(patch%itype(p))
         m_livecrootc_to_litter_fire(p)              =  livecrootc(p)         * f * &
-             fm_droot(patch%itype(p))
+             fm_lroot(patch%itype(p))
         m_livecrootc_storage_to_litter_fire(p)      =  livecrootc_storage(p) * f * &
              (1._r8- cc_other(patch%itype(p))) * &
              fm_other(patch%itype(p))

```

Note here: f is the fire rate (1/sec), m is the acceleration factor, cc_* terms are combustion completeness factor, and fm_* terms are fire related mortality terms.

So this means

fire emission of transfer of live-stem to litter = live-stem * f * (1 - cc(livestem))*fm(live-stem) (rather than fm(dead-root))

fire emission of transfer of live-stem to deadstem = livestem * f * (1 - cc(live-stem)*(fm(live-stem) - fm(dead-stem)) (rather than fm(deadroot))

fire emission of transfer of dead-stem to litter = deadstem * f * m * (1 - cc(dead-stem))*fm(dead-stem)) (rather than fm(dead-root))

fire emission of transfer of live-root to litter = liveroot * f * fm(live-root) (rather than fm(dead-root))

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2017-09-27 14:08:21 -0600**

OK, the guiding principle seems to be that when cc_* and fm_* is used in a calculation of fire emission the two should match each other and they should either be the main type, unless it's (type)_storage or (type)_xfer then it should be "other".

That principle seems to be born out in the code. With the following exception where the same problem shows up for Nitrogen....

Index: CNFireBaseMod.F90
===================================================================
--- CNFireBaseMod.F90	(revision 86763)
+++ CNFireBaseMod.F90	(working copy)
@@ -716,7 +716,7 @@
              fm_other(patch%itype(p))
         m_livestemn_to_litter_fire(p)              =  livestemn(p) * f * &
              (1._r8 - cc_lstem(patch%itype(p))) * &
-             fm_droot(patch%itype(p))
+             fm_lstem(patch%itype(p))
         m_livestemn_storage_to_litter_fire(p)      =  livestemn_storage(p) * f * &
              (1._r8 - cc_other(patch%itype(p))) * &
              fm_other(patch%itype(p))   
@@ -728,7 +728,7 @@
              (fm_lstem(patch%itype(p))-fm_droot(patch%itype(p)))
         m_deadstemn_to_litter_fire(p)              =  deadstemn(p) * f * m * &
              (1._r8 - cc_dstem(patch%itype(p))) * &
-             fm_droot(patch%itype(p))    
+             fm_dstem(patch%itype(p))    
         m_deadstemn_storage_to_litter_fire(p)      =  deadstemn_storage(p) * f * &
              (1._r8 - cc_other(patch%itype(p))) * &
              fm_other(patch%itype(p))

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2017-09-27 15:03:23 -0600**

Dave verified that the change in comment 1 should be applied as well. So I'll go forward with it as well.

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2017-10-02 12:45:23 -0600**

Fang Li, let us know that this "fix" is incorrect. Hence, we need to revert.

   "Your changes in CNFireBaseMod.F90 for clm4_5_16_r257 are wrong, please change back to clm4_5_16_r256.
    In fire code, fm_droot represents the fraction of whole-plant mortality in post-fire regions, and also used to represent the fraction of plant-tissue mortality for deadstem, croot, and fraction of transport from livestem/livecroot to litter. fm_dstem is useless and can be removed from parameter file."

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2017-10-02 13:04:45 -0600**

Note, the code doesn't define the meaning of the fm_ terms. The params file has them defined as follows (note that fm_dstem has the wrong long_name):

        double fm_droot(pft) ;
                fm_droot:units = "0 to 1" ;
                fm_droot:long_name = "Fire-related mortality factor for dead roots" ;
                fm_droot:_FillValue = -999.99 ;
        double fm_dstem(pft) ;
                fm_dstem:units = "0 to 1" ;
                fm_dstem:long_name = "Fire-related mortality factor for dead roots" ;
                fm_dstem:_FillValue = -999.99 ;
        double fm_leaf(pft) ;
                fm_leaf:units = "0 to 1" ;
                fm_leaf:long_name = "Fire-related mortality factor for leaf" ;
                fm_leaf:_FillValue = -999.99 ;
        double fm_lroot(pft) ;
                fm_lroot:units = "0 to 1" ;
                fm_lroot:long_name = "Fire-related mortality factor for live roots" ;
                fm_lroot:_FillValue = -999.99 ;
        double fm_lstem(pft) ;
                fm_lstem:units = "0 to 1" ;
                fm_lstem:long_name = "Fire-related mortality factor for live stem" ;
                fm_lstem:_FillValue = -999.99 ;
        double fm_other(pft) ;
                fm_other:units = "0 to 1" ;
                fm_other:long_name = "Fire-related mortality factor for other plant" ;
                fm_other:_FillValue = -999.99 ;
        double fm_root(pft) ;
                fm_root:units = "0 to 1" ;
                fm_root:long_name = "Fire-related mortality factor for fine roots" ;
                fm_root:_FillValue = -999.99 ;

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2017-10-02 14:05:33 -0600**

In terms of values for the arrays on the params file in both CLM45/CLM50:

fm_droot, fm_lroot, and fm_root are all the same

fm_other, fm_lstem are the same

In CLM50:

fm_dstem and fm_droot are the same

In CLM45:

fm_dstem and fm_other are the same
(also note that prog crop PFT's are set to zero)

So in terms of how they are currently used the dead, live, and fine root terms are identical (so one term for all roots could be used). livestem and other are the same. And then dead-stem is different between CLM45 and CLM50. So you could reduce the parameters to:

fm_root (live, dead or fine roots)
fm_dstem (dead stem)
fm_other (everything else including live-stem)

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2017-10-02 14:07:03 -0600**

for the cc_* terms there's fewer, but only three have different values.

there's: dead-stem, live-stem, leaf and other (and for both CLM45 and CLM50 dead-stem and live-stem are equal).

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2017-10-03 10:09:17 -0600**

Add Fang to the bug report.

**Comment by ekluzek** [comment]
The current code is correct as per Fang Li, and it has some documentation in the code to say why it looks the way it does. So closing this...

For example there are lines like this...

 ``` fortran
       ! NOTE: It looks incorrect to use fm_droot here, but it's used to represent fraction of transport from livestem/livecroot to litter
        ! EBK Oct/06/2017 see bug 2516 http://bugs.cgd.ucar.edu/show_bug.cgi?id=2516 (stem and root live or dead assumed to have the same transport)
        m_livestemc_to_litter_fire(p)               =  livestemc(p) * f * &
             (1._r8 - cc_lstem(patch%itype(p))) * &
```

**Comment by billsacks** [comment]
@ekluzek you said you're closing this in the last comment, but it's still open. Did you mean to close it?
