### ISSUE TITLE
ncar_pylib

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1786]
looks like CISL is changing how they handle ncar_pylib.  Not sure how this needs to change our workflow for python tools, but I wanted to raise the issue here to consider.  Below is the error I received when activating ncar_pylib
```
**************************
*
*   DEPRECATION NOTICE!
*
*   The "ncar_pylib"-based NCAR Package Library has been deprecated in favor of
*   the newer conda-based NPL. Please migrate your workflows to the conda solution
*   as soon as possible. This older method and associated virtual environments
*   will be removed from the system in the coming months. A specific date will be
*   announced once it is known via the Daily Bulletin.
*
*   See https://arc.ucar.edu/knowledge_base/83853599 for documentation on using the
*   conda-based NCAR Python Library environments.
*
**************************
```

**Comment by ekluzek** [comment]
Yes, this is where using the conda python environment that we setup becomes important. We do have a conda text file for ctsm_py to run the tools under the python directory. I did add a bash script that helps at setting up that environment as well "manage_python_env" at the top level. There's more we need to do, and for example we want to change the name. But, we do have an initial setup that addresses this. The advantage of this is also that the conda environment is general and can be used on any system, including for example izumi.

**Comment by ekluzek** [comment]
We talked about this some in our standup meeting this morning. Another solution is to have a wrapper around the test system that sets up the conda environment. Although that is problematic for the parts that are sent to batch nodes, as I don't know if the conda environment is inherited when sent to the batch machine.

**Comment by ekluzek** [comment]
This is mostly handled with the addition of the script to help build a conda environment. py_env_create. The thing left to do is remove the customization that fsurdat_modifier has for ncar_pylib.

**Comment by ekluzek** [comment]
@slevisconsulting I'd like to assign this to you to remove the customization that fsurdat_modifier has for ncar_pylib. Is that something you could do and appropriately charge to your current contracts? I assume you might need to make sure this is an appropriate use of your time.

**Comment by slevisconsulting** [comment]
@ekluzek 
fsurdat_modifier does not need ncar_pylib to work, so we should be all set. Current instructions in README.fsurdat_modifier state:
```
To run on Cheyenne/Casper/Izumi
1) (Un)load, execute, and activate the following:
module unload python
module load conda
./py_env_create
conda activate ctsm_py
(Use "deactivate" to reverse the latter.)
```
As we discussed this morning, these instructions won't work on izumi and my workaround there is to `conda activate ctsm_py`

**Comment by ekluzek** [comment]
OK, the one thing to do then @slevisconsulting would be to remove the code in the system test for it
Right now this test invokes ncar_pylib from a specific path on cheyenne...

cime_config/SystemTests/fsurdatmodifyctsm.py

It should be changed to run py_env_create as you outline above.
