### ISSUE TITLE
albgrd_col not set to spval before call to hist_addfld2d

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#1788]
### Brief summary of bug

albgrd_col is not set to spval before call to hist_addfld2d in SurfaceAlbedoType.F90

### General bug information

**CTSM version you are using:** ctsm5.1.dev082

**Does this bug cause significantly incorrect results in the model's science?** No (but not checked)

**Configurations affected:** All

### Details of bug

I see this in SurfaceAlbedoType.F90:

    this%albgri_col(begc:endc,:) = spval
    call hist_addfld2d (fname='ALBGRD', units='proportion', type2d='numrad', &
         avgflag='A', long_name='ground albedo (direct)', &
         ptr_col=this%albgrd_col, default='inactive')

    this%albgri_col(begc:endc,:) = spval
    call hist_addfld2d (fname='ALBGRI', units='proportion', type2d='numrad', &
         avgflag='A', long_name='ground albedo (indirect)', &
         ptr_col=this%albgri_col, default='inactive')

The first line above should be:

    this%albgrd_col(begc:endc,:) = spval

**Comment by ekluzek** [comment]
I fixed this in ctsm5.1.dev100 for a simple f09 case and it showed identical answers.

SMS_Ld1_PS.f09_g17.I2000Clm50BgcCru.cheyenne_gnu.clm-datm_bias_correct_cruv7

I think that likely means this can be treated as a simple bit-for-bit change, so I'm marking it as such.

**Comment by billsacks** [comment]
So are you saying this is fixed and this issue should be closed? Or just that you tested the fix?

Note that ALBGRD is not output in any of our tests (as far as I can see). This may change that diagnostic field when it's output, but I still think simple bfb is a reasonable designation for this.

**Comment by billsacks** [comment]
Checking code: this still needs to be fixed.
