### ISSUE TITLE
FATES doesn't call SoilBiogeochemCompetitionInit

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#180]
**Erik Kluzek < erik > - 2017-11-09 13:12:23 -0700**
**Bugzilla Id:** [2531](http://bugz.cgd.ucar.edu/show_bug.cgi?id=2531)
**Bugzilla CC:**  dlawren,  rfisher, 

In look at the code for clm4_5_16_r258 it looks like FATES wouldn't call SoilBiogeochemCompetitionInit. The main thing that does is to do some settings based on suplnitro. Which might not be used for fates. 

But, it also sets: dt, and bdnr, so it's possible when running fates this isn't being done -- and that could be a problem that affects answers.

**Comment by billsacks** [comment]
@rgknox we came across this old issue. Do you have any sense whether this is a problem?

**Comment by ekluzek** [comment]
OK, this isn't a problem for FATES since FATES doesn't handle Nitrogen. FATES doesn't call SoilBGC Competition either, and since it's purpose is to compete for mineral Nitrogen. So closing this as not a problem.
