### ISSUE TITLE
Conflicting ctsm5.1.dev061 tag and branch when running manage_externals

### ISSUE THREAD

**Issue by fischer-ncar** [ESCOMP/CTSM#1808]
### Brief summary of bug

Manage_externals fails the checkout older alpha tags because there's a conflict with ctsm5.1.dev061 tag
and branch existing.

### General bug information

**CTSM version you are using:** [output of `git describe`]
ctsm5.1.dev061

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]
Fails to be cloned for alpha tags

**Configurations affected:** [Fill this in if known.]

### Details of bug

[Fill in details here.]

git clone -b cesm2_3_alpha07b https://github.com/ESCOMP/cesm cesm
cd cesm
./manage_externals/checkout_externals

**ERROR: In repo "clm": tag "ctsm5.1.dev061" is both a branch and a tag. git may checkout the branch instead of the tag depending on your version of git.**

### Important details of your setup / configuration so we can reproduce the bug

[Specify anything relevant: the compset, resolution, machine, compiler, any xml or namelist changes, etc. You don't have to repeat anything that you have already noted above.]

### Important output or errors that show the problem
**ERROR: In repo "clm": tag "ctsm5.1.dev061" is both a branch and a tag. git may checkout the branch instead of the tag depending on your version of git.**

**Comment by ekluzek** [comment]
OK, so there is a rogue branch called the same name as the tag for ctsm5.1.dev061, the branch is a mistake. It looks like the tag is correct though. The branch actually points to ctsm5.1.dev062, so isn't far off, but it's not correct.

So I think all we need to do is to delete the branch.

**Comment by fischer-ncar** [comment]
That's funny, my work around was to use ctsm5.1.dev062.

**Comment by ekluzek** [comment]
OK I deleted the branch on ESCOMP which I think should resolve the problem. People's clone's will still have the branch, but I think that's harmless.

@fischer-ncar let me know if that resolves the problem and we'll close this.

**Comment by ekluzek** [comment]
OK, this works for me, so I'm closing.
