### ISSUE TITLE
My izumi environment is incompatible with py_env_create

### ISSUE THREAD

**Issue by slevisconsulting** [ESCOMP/CTSM#1821]
### Details of bug

This seems to be specific to my izumi environment because @ekluzek tried on izumi on my branch and did not see the problem. When I follow the instructions in py_env_create:
```
>>> module load lang/python
>>> ./py_env_create
Use conda to install the python environment needed to run the CTSM python tools in the conda environment: ctsm_py
Using the file: ./python/conda_env_ctsm_py_cgd.txt
Create ctsm_py
conda create --force -n ctsm_py -q

CustomValidationError: Parameter channel_priority = 'strict' declared in <<merged>> is invalid.
The value 'strict' cannot be boolified.

Error creating conda environment ctsm_py
```
ADDITIONAL INFO
I tried this next:
```
conda env list
conda activate /home/slevis/anaconda/envs/ctsm_py
./fsurdat_modifier fillindianocean/modify_fsurdat.cfg
```
and got a malformatted .nc file as in #1658 but fixed the problem by unloading python:
`module unload lang/python`

Next (out of curiosity) I tried `./py_env_create` from the already active ctsm_py enviroment and didn't get an error.

### General bug information

**CTSM version you are using:** [output of `git describe`]
ctsm5.1.dev100-115-g492efe355

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]
No

**Comment by ekluzek** [comment]
The original problem seems to be that the following was in @slevisconsulting .condarc file on izumi:

`channel_priority: strict`

Removing that line seems to allow it to go through.

**Comment by ekluzek** [comment]
@slevisconsulting also had previously installed miniconda on his own, and we removed the lines that had to do with that in the .tcshrc. I had the same thing happen, and had removed those lines as well.

**Comment by ekluzek** [comment]
@slevisconsulting is this working for you now? If so can we close this?

**Comment by slevisconsulting** [comment]
> @slevisconsulting is this working for you now? If so can we close this?

I tested on izumi as follows:
cd /fs/cgd/data0/slevis/git/mksurfdata_toolchain
git branch  # says master
git describe  # says ctsm5.1.dev114
./py_env_create  # started this around 11a PT; so far it says:
```
Use conda to install the python environment needed to run the CTSM python tools
Using the file: ./python/conda_env_ctsm_py_cgd.txt
ctsm_py environment already exists
Install ctsm_py this can take a long time, be patient....
conda install --yes -q -c conda-forge -n ctsm_py --file ./python/conda_env_ctsm_
Solving environment: ...working...
```
I will update this post when I get to next steps.
