### ISSUE TITLE
`seq_drydep_mod` should be replaced by `shr_drydep_mod`

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CTSM#1822]
The use of `seq_drydep_mod` in source code should be replaced by `shr_drydep_mod`.  As of CMEPS tag `cmeps0.13.70` and cpl7 tag `cpl7.0.14`, `seq_drydep_mod.F90` is merely a wrapper to `shr_drydep_mod.F90` and is subject to be removed in a future CMEPS tag when CTSM is ready.

**Comment by ekluzek** [comment]
@fvitt does this change answers at all or are answers identical with either version?

**Comment by fvitt** [comment]
This change does not change answers

**Comment by ekluzek** [comment]
@billsacks and @adrifoster this is the thing that gets in the way of the Ozone tag.

**Comment by billsacks** [comment]
I think there's more than just that: It looks like we also need to stop setting drydep_method in drv_flds_in, possibly replacing it with some new variable. @fvitt can you please give us some guidance on what we need in CTSM to be compatible with https://github.com/ESCOMP/CMEPS/pull/303, similar to whatever was done in https://github.com/ESCOMP/CAM/pull/602?

**Comment by fvitt** [comment]
> @billsacks and @adrifoster this is the thing that gets in the way of the Ozone tag.

What is the "Ozone tag"?

**Comment by fvitt** [comment]
> I think there's more than just that: It looks like we also need to stop setting drydep_method in drv_flds_in, possibly replacing it with some new variable. @fvitt can you please give us some guidance on what we need in CTSM to be compatible with [ESCOMP/CMEPS#303](https://github.com/ESCOMP/CMEPS/pull/303), similar to whatever was done in [ESCOMP/CAM#602](https://github.com/ESCOMP/CAM/pull/602)?

Would it help if I prepare a PR to ESCOMP/CTSM for this?

**Comment by ekluzek** [comment]
@fvitt that would be great if you could make a PR for this!

The "Ozone tag" by the way is some work that @adrifoster is bringing in that passes some Ozone fields from ATM to LND. There are PR's in both CMEPS and CDEPS for it. I think the CMEPS one is cmeps0.13.71 just after your CMEPS changes came in.
