### ISSUE TITLE
Need v2 versions of initial conditions for year 1991 from b.e21.BWHIST.f09_g17.CMIP6-historical-WACCM.001 and 002

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#1823]
I'm opening an issue for this just so we have documentation in case this comes up again.
From Mike Mills:

Would you be able to make v2 versions of the ICs below?

/glade/p/cesmdata/cseg/inputdata/cesm2_init/b.e21.BWHIST.f09_g17.CMIP6-historical-WACCM.001/1991-01-01

/glade/p/cesmdata/cseg/inputdata/cesm2_init/b.e21.BWHIST.f09_g17.CMIP6-historical-WACCM.002/1991-01-01

Currently there are files for 1950 and 2015 of b.e21.BWHIST.f09_g17.CMIP6-historical-WACCM.001 here:
/glade/p/cesmdata/cseg/inputdata/cesm2_init/b.e21.BWHIST.f09_g17.CMIP6-historical-WACCM.001_v2/1950-01-01
/glade/p/cesmdata/cseg/inputdata/cesm2_init/b.e21.BWHIST.f09_g17.CMIP6-historical-WACCM.001_v2/2015-01-01

**Comment by ekluzek** [comment]
I'm reaching out to @mmills to learn more about this and if we really need this in CESM and CAM CESM2.1 release tags, or if we just need to get the simulations they are doing to run. The importance of creating the "v2" versions is to support this as an out of the box option in tags, or for important production runs that are going to this same thing for many cases.

**Comment by olyson** [comment]
According to Mike Mills this is a one-off simulation.  The change below enables the simulation to run, so I'm closing this.

./xmlchange CLM_NAMELIST_OPTS="use_init_interp=.true. init_interp_method='general'"
