### ISSUE TITLE
MIMICS related parameters missing name and units in paramfile

### ISSUE THREAD

**Issue by ecaas** [ESCOMP/CTSM#1845]
Currently, most MIMICS parameters in file "ctsm51_params.c211112.nc" are missing both long names and units.

Another minor thing, somewhat related; the comment in the line below refers to Wieder et al 2015 in which the parameters are actually multiplied (Eq. 2), not divided. Referring to the testbed version instead would reduce confusion. 
https://github.com/ESCOMP/CTSM/blob/56878b6a77e167c1c875aa9cabdf6ea2e482d737/src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90#L93

**Comment by slevis-lmwg** [comment]
Something else that I came across that may need updating in restart files for use with MIMICS:
`decomp_cascade_state`

**Comment by slevis-lmwg** [comment]
In prep for meeting with @wwieder
Suggested long names and units for MIMICS params:
- `mimics_cn_k` C:N of oligotrophic microbes, fraction
- `mimics_cn_mod_num` Adjustment of microbial C:N based on fmet, unitless
- `mimics_cn_r` C:N of copiotrophic microbes, fraction
- `mimics_densdep` Exponent controlling the density dependence of microbial turnover, unitless
- `mimics_desorp` Two parameters involved in determining desorption as a function of clay fraction, ?
- `mimics_desorpQ10` Desorption Q10 = 1.1 with reference temperature of 25 degrees C, unitless
- `mimics_fmet` Four parameters involved in determining fmet as a function of ligninNratioAvg, ?
- `mimics_fphys_k` Two parameters involved in determining fraction of physically protected oligotrophic microbes as a function of clay fraction, ?
- `mimics_fphys_r` Two parameters involved in determining fraction of physically protected copiotrophic microbes as a function of clay fraction, ?
- `mimics_kint` Regression intercept for each pool, ?
- `mimics_kmod` kmod = ak / kmod from Wieder et al. (2015), ?  <-- division correct here?
- `mimics_ko_k` ko for oligotrophic microbes, ?
- `mimics_ko_r` ko for copiotrophic microbes, ?
- `mimics_kslope` Regression coefficient for each pool, ?
- `mimics_mge` Microbial growth efficiency for each pool, mg/mg
- `mimics_nue_into_mic` Microbial N use efficiency for N fluxes, ?
- `mimics_p_scalar` Two parameters involved in determining p_scalar as a function of clay fraction, ?
- `mimics_t_soi_ref` Reference soil temperature, degrees C
- `mimics_tau_k` Two parameters involved in determining tau for oligotrophic microbes as a function of fmet, ?
- `mimics_tau_mod_factor` (1 / tauModDenom) from testbed code, ?
- `mimics_tau_mod_max` Maximum tau_mod, ?
- `mimics_tau_mod_min` Miniimum tau_mod, ?
- `mimics_tau_r` Two parameters involved in determining tau for copiotrophic microbes as a function of fmet, ?
- `mimics_vint` Regression intercept for each pool, 5.47 ln(mg Cs (mg MIC)-1 h-1)
- `mimics_vmod` For each pool, vmod = vmod * av from Wieder et al. (2015), ?
- `mimics_vslope` Regression coefficient for each pool, ln(mg Cs (mg MIC)-1 h-1) ¡C-1  <-- ?
- `mimics_fchem_k` Three parameters involved in determining fraction of chemically active oligotrophic microbes as a function of fmet, ?
- `mimics_fphys_r` Three parameters involved in determining fraction of chemically active copiotrophic microbes as a function of fmet, ?

**Comment by slevis-lmwg** [comment]
Add comment in MIMICS code about mimics_densdep being set to 1 and, therefore, having no effect. Also the reference:
Georgiou, K.,et al. Nat Commun (2017). https://doi.org/10.1038/s41467-017-01116-z

Collapse fchem_p1 and _p3 into single parameter.

**Comment by slevis-lmwg** [comment]
Reminder that we want to include the above param file mods in #2040 
All changes are summarized in the above [post.](https://github.com/ESCOMP/CTSM/issues/1845#issuecomment-1712071791)
