### ISSUE TITLE
Add "only" clause to a problematic use statement in lnd_comp_nuopc for cce compiler

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CTSM#1846]
In ctsm5.1.dev106 while building with the cce compiler on gust I ran into an error:
ftn-487 ftn: ERROR CHECKIMPORT, File = ../../../../../work/jedwards/sandboxes/cesm2_x_alpha/components/clm/src/cpl/nuopc/lnd_comp_nuopc.F90, Line = 1279, Column = 9 
  The specific interfaces for "ESMF_INFOINQUIRE" and "ESMF_INFOGETI4" make the GENERIC interface "ESMF_INFOGET" ambiguous.

Looking at the interfaces for ESMF_InfoInquire and ESMF_InfogetI4 this is clearly a compiler issue and not a ctsm issue.  HOWEVER I believe that issues like this can mostly be avoided by always using the only clause to use statements.     https://github.com/ESCOMP/CTSM/blob/master/src/cpl/nuopc/lnd_comp_nuopc.F90#L1278

**Comment by billsacks** [comment]
From discussion at today's ctsm-software meeting: we mostly agree with this general principle. For now, though, it sounds like the high priority thing is fixing this particular issue. I'm going to change this issue title to reflect that. But @jedwards4b can you clarify what the necessary fix is for this specific case?

**Comment by jedwards4b** [comment]
@billsacks Gust is down and should return to service next week.   But I have not yet made any code changes to try to work around this compiler issue.

**Comment by billsacks** [comment]
@jedwards4b - we don't want to drop this if it's important, but aren't clear on what's needed for it. Let me know if you'd like to talk about it.

**Comment by jedwards4b** [comment]
Well I would like to try using the cce compiler on gust again with a lnd_comp_nuopc.F90 in which all use statements have only clauses.  What isn't clear?

**Comment by billsacks** [comment]
I originally had the impression that you might have a version where you had fixed this by determining the correct "only" clauses for this module. If you haven't, then we can do it.

**Comment by jedwards4b** [comment]
@billsacks  I have this done and will submit a PR.

**Comment by billsacks** [comment]
Thank you @jedwards4b . And I apologize: I just took the time to re-read the whole thread here, and you were very clear in your comment 4 weeks ago that you hadn't yet made any changes. I'm sorry that I didn't see that. This came from a rapid issue triage in our weekly ctsm-software meeting and I apologize for not having re-read the thread before firing off a quick reply.
