### ISSUE TITLE
ICE in src/cpl/share_esmf/ch4FInundatedStreamType.F90

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CTSM#1857]
### Brief summary of bug
ICE when using intel/19.1.1

### General bug information

**CTSM version you are using:**  ctsm5.1.dev106

**Does this bug cause significantly incorrect results in the model's science?**  No

**Configurations affected:**  ne30pg3_t061.B1850MOM is what I am working on

### Details of bug
On cheyenne with:
Currently Loaded Modules:
  1) ncarenv/1.3    4) intel/19.1.1      7) esmf-8.4.0b08-ncdfio-mpt-O  10) pnetcdf/1.12.3
  2) python/3.7.9   5) esmf_libs/8.2.0   8) mpt/2.25                    11) ncarcompilers/0.5.0
  3) cmake/3.18.2   6) mkl/2020.0.1      9) netcdf-mpi/4.9.0

### Important details of your setup / configuration so we can reproduce the bug
ERS.ne30pg3_t061.B1850MOM.cheyenne_intel

### Important output or errors that show the problem

catastrophic error: **Internal compiler error: internal abort** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
compilation aborted for /glade/work/jedwards/sandboxes/cesm2_x_alpha.async2/components/clm/src/cpl/share_esmf/ch4FInundatedStreamType.F90 (code 1)

**Comment by jedwards4b** [comment]
Still get the error when using intel/2022.1

**Comment by jedwards4b** [comment]
This appears to only happen in my asyncio branch of cesm.  It does not occur in cesm2.3-alpha10 (hash f55550643b)

**Comment by jedwards4b** [comment]
This went away when I switched to a different version of the esmf library.

**Comment by billsacks** [comment]
@jedwards4b given that this has gone away in your latest testing (with a different esmf version), is this still an issue you feel should be addressed?

**Comment by jedwards4b** [comment]
no, i think we can close.
