### ISSUE TITLE
Distinguish between ocean and true wetlands on surface dataset

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1886]
Currently we use the wetland landunit to represent ocean points as well as true (inland) wetlands. This could cause problems for the changes in #1878 as well as for those in #1716. For the sake of those changes and possibly other reasons, we should distinguish between ocean points and true wetlands on the surface dataset by adding a new PCT_OCEAN field and using that rather than the PCT_WETLAND field for points where we don't have any land cover data. At runtime these could still be combined into the wetland landunit (though with the changes for #1878 ocean would instead be changed to bare ground), but separating them would allow us to distinguish between these two very different land covers for #1878 and #1716 – and we could possibly also have some metadata describing the separation of the wetland landunit into ocean vs. true wetland for each grid cell.

Currently we (by default) do not include inland wetlands on the surface dataset, so this isn't a problem, but it would become problematic if we started including inland wetlands again.

**Comment by ekluzek** [comment]
The fact that wetland means ocean-points in CTSM is very confusing for users. So making this clear by calling it what we actually use it for makes the code much more readable. And it makes the surface datasets more readable and understandable as well. So I really like this idea. I was going to suggest it as well.

**Comment by wwieder** [comment]
To avoid confusion can we go ahead and call these coastal areas PCT_OCEAN in CTSM5.2 to avoid confusion on PCT_WETLAND, especially since we don't actually have inland wetlands?

**Comment by ekluzek** [comment]
@wwieder I do support that idea. It would require some code changes. But, hopefully not too hard. @billsacks you worked on the current implementation how hard would it be to do this? I don't think you should do it, but if you can assess it as not being too hard someone else could and get advice from you on what to do...

**Comment by billsacks** [comment]
I would budget a few days of work for this. It will require changes in mksurfdata as well as surfrdMod.

**Comment by ekluzek** [comment]
Done on the ctsm5.2 branch and will close with it.
