### ISSUE TITLE
Is `f - baf_crop` necessary in fire calculations for `is_cwd`?

### ISSUE THREAD

**Issue by slevisconsulting** [ESCOMP/CTSM#1891]
From looking at this with @wwieder and @klindsay28 on 2022/11/02 in the context of spinning up ctsm bgc with Newton-Krylov...

Why not use `f` rather than `f - baf_crop` with is_cwd in the following?

CNFireBaseMod.F90
```
f = farea_burned(c)
do j = 1, nlevdecomp
           ! carbon fluxes
           do l = 1, ndecomp_pools
              if ( is_litter(l) ) then
                 m_decomp_cpools_to_fire_vr(c,j,l) = decomp_cpools_vr(c,j,l) * f * &
                      cmb_cmplt_fact_litter
              end if
              if ( is_cwd(l) ) then
                 m_decomp_cpools_to_fire_vr(c,j,l) = decomp_cpools_vr(c,j,l) * &
                      (f-baf_crop(c)) * cmb_cmplt_fact_cwd
              end if
           end do
```
and similarly in the nitrogen loop.

Reasoning:
- Currently crops shouldn't generate cwd, so `is_cwd` should occur only when `baf_crop = 0`.
- Even if crops generated cwd (e.g. simulating orchards), why handle litter and cwd differently?
- Crop and non-crop veg. should not coexist in a column (pls correct my assumption if I'm wrong), so I would expect `baf_crop = f` in crop columns and `baf_crop = 0` in non-crop columns.

I will share this question with Fang Li for clarification.

**Comment by slevisconsulting** [comment]
Fang responded that this was done for the generic crops, which could coexist in a column with non-crop pfts depending on user-defined settings. If we still permit generic crops and non-crop pfts coexisting in a column, then Fang wants us to keep the code as written.

I believe the ctsm defaults to `create_crop_landunit = .true.`, so we can assume baf_crop = 0 for the purposes of a Newton-Krylov spin-up. However, the ctsm code should remain as written as long as `create_crop_landunit = .false.` is an option.

**Comment by wwieder** [comment]
Thanks for following up with Fang on this @slevisconsulting.  Can you make sure Keith Lindsay keeps this in the preconditioner for the N-K solver.

**Comment by wwieder** [comment]
Now I see @klindsay28 is already on the thread!  I'll close this issue with a won't fix label

**Comment by ekluzek** [comment]
@slevisconsulting FYI we currently only allow create_crop_landunit=FALSE for FATES. But, we actually want to change this option so it's turned on all the time including for FATES.
