### ISSUE TITLE
LUNA fixes and VOC emissions

### ISSUE THREAD

**Issue by kjetilaas** [ESCOMP/CTSM#1917]
Not sure if this is the right place for this post. It might mainly be important for NorESM and WACCAM users, but it relates to (previous) CLM bugfixes so I thought it could be of interest to others here.

Background: 
A while back, we updated to [NorESM2.2](https://github.com/NorESMhub/NorESM/tree/noresm2.2) with new components from CESM2.2 and discovered several substantial changes. Much of it relates to updates to CLUBB (in CAM), but there are also important changes that seems to come from CLM. See @dirkolivie's notes here: 
http://ns2345k.web.sigma2.no/people/olivie/noresm2.2/noresm2.2.v1.0.pdf 

Particularly, there is a roughly 10% increase in certain VOC emissions (isoprene and monoterpene). These are used in NorESM and WACCAM chemistry schemes (affecting aerosols and clouds), but not in CESM (as I understand). 

After digging a bit into this, I think these VOC emission changes are related to TLAI changes related to LUNA bug fixes #961.

Here is the change in TLAI (NorESM2.2-NorESM2, mean of simulation year 6-20, see Dirk's notes for details):
![image](https://user-images.githubusercontent.com/45290761/205081337-e5d760be-d3cb-45c2-87df-9345c7865e73.png)

with corresponding changes in (MEGAN) isoprene emissions:
![image](https://user-images.githubusercontent.com/45290761/205081613-36f65360-0e7c-4524-9024-b46655ca5a5e.png)

These TLAI changes in turn correlate well TLAI changes between ctsm1.0.dev093 and ctsm1.0.dev.104 that were "climate changing, but tuned to respond similar to clm5.0" (see comments 2020-09-06 [here](https://github.com/ESCOMP/CTSM/wiki/Answer-changing-tags)), and figures [here](https://webext.cgd.ucar.edu/I20TR/clm50_ctsm10d104_2deg_GSWP3V1_hist/lnd/clm50_ctsm10d104_2deg_GSWP3V1_hist.1995_2014-clm50_ctsm10d093_2deg_GSWP3V1_hist.1995_2014/set2/set2_ANN_TLAI.png). As I understand, this relates to this bug fix #961.

As I understand, these were included in CESM2.2: https://www.cesm.ucar.edu/models/cesm2/whatsnew.html

**Comment by wwieder** [comment]
@kjetilaas it looks like your changes are consistent with changes in LAI that came in with the LUNA bug fixes.  Are you raising this issue just to document the BVOC changes, or is there more we need to consider?

**Comment by kjetilaas** [comment]
For documentation. This has been lying there for a while, and I thought it would be good to write up and make the findings available for others (and potentially get a second opinion on my interpretation). Feel free to close this or let me know if this would be better suited somewhere else, @wwieder.

**Comment by wwieder** [comment]
Ok, thanks. Also note that there are plans to upgrade to MEGAN v3.x with #1323, which will change answers further.
