### ISSUE TITLE
Add documentation on excess ice to the technical note

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1923]
With #1229 and PR #1787 we need to have excess ice documented in the tech note.

**Comment by mvdebolskiy** [comment]
Comment to assign myslef.

**Comment by mvdebolskiy** [comment]
Do I understand correctly that I can append the equations and a write up [here](https://github.com/ESCOMP/CTSM/blob/17e2acb6acf943a9a89853330925efee182d470b/doc/source/tech_note/Soil_Snow_Temperatures/CLM50_Tech_Note_Soil_Snow_Temperatures.rst)?

**Comment by ekluzek** [comment]
@mvdebolskiy yes, that's correct. @olyson can you give @mvdebolskiy some guidance on editing the Tech note as well?

There are directions on the wiki, for example here...

https://github.com/ESCOMP/CTSM/wiki/Directions-for-editing-CLM-documentation-on-github-and-sphinx

**Comment by olyson** [comment]
I use the instructions that Erik provided, on my windows machine using the docker method.

**Comment by mvdebolskiy** [comment]
@dlawrenncar @swensosc I've pushed a small writeup into the documentation. Can you check it? Let me know if I need to expand it.

**Comment by samsrabin** [comment]
@mvdebolskiy, what's the latest on this?

**Comment by mvdebolskiy** [comment]
@samsrabin  just waiting for Sean or Dave to review #2161 and this can be closed.
