### ISSUE TITLE
North and South pole set to glacier on surface datasets regardless of raw data specification

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1930]
### Brief summary of bug

mksurfdata has been forcing the North and South Poles to glacier on the surface datasets regardless of the raw data specification. In general this won't cause problems – the South Pole truly should be glacier, and the North Pole is typically owned by the ocean – but in unusual cases (e.g., different continental arrangements or very warm paleo climates) this could cause incorrect land cover at the poles.

### General bug information

**CTSM version you are using:** Latest master, but has existed essentially forever.

**Does this bug cause significantly incorrect results in the model's science?** Yes, but only very small and only in rare setups

**Configurations affected:** Rare cases (see above)

**Comment by slevisconsulting** [comment]
#1920 fixed this.
@billsacks @ekluzek I hope it's ok that I'm closing this issue.
