### ISSUE TITLE
Is it a problem to use a CROP surface dataset for FATES?

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1948]
I thought because of #1505 that we couldn't use 78pft surface datasets for FATES. But, in ctsm5.1.dev116, I did just that for the 1x1_brazil site, and yet my testing and follow up testing for FATES by @adrifoster for ctsm5.1.dev117 showed that 1x1_brazil FATES tests seem to pass.

I think this either means that something is wrong in the setup for these cases. Or that it just means that reduced complexity modes (like FATES-SP) wouldn't work. Or that we aren't testing in a way that we'd see it fail (like running in DEBUG mode or something).

**Comment by rgknox** [comment]
FATES without reduced complexity (fixed biogeography) should not use any of the patch level data in the surface file, so it shouldn't matter how the PFTs are setup, or if they are natveg or crop.  I'm not surprised by the results, and would had expected that test to pass with the 78 pft surface file.

**Comment by samsrabin** [comment]
Closing as a child of #1505.
