### ISSUE TITLE
Make PCT_URBAN on surface datasets scalar and add CLM_URB_DENS for the densities to make it more similar to other

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1953]
In looking at the surface datasets I noticed that all PCT_* variables other than urban, have a scalar variable to give the total for the landunit, and then a separate one to give the subgrid fractions. So you have PCT_NATVEG, PCT_CROP and PCT_GLACIER to give the total for the landunit, but PCT_NAT_PFT, PCT_CFT, and PCT_GLC_MEC to give the breakdown within the landunit. To make it more similar we could have PCT_URBAN and PCT_URB_DENS to give the breakdown.

I'm not sure if this is worth doing. But, I wanted to bring it up before we push the "go button" on CTSM5.2 as this would be a natural time to make this change. It wouldn't be too hard to do. But, fundamentally it's only a code cleanup so it's not clear to me if it's worth it or not.

**Comment by olyson** [comment]
I agree that it would be nice to have something that is more consistent with the other surface types. Obviously the time to do that would have been when we went from a single urban density class in CLM to the multiple density classes in CLM4.5.  However, I'd vote against doing this right away now given that we want to generate a surface dataset for the CESM3 development simulations soon.  Aside from having to change the model code, it seems like we'd also have to change mksurfdata_esmf as well as change all of the raw datasets which are already generated and installed in inputdata for all of the historical and SSP times slices.  And also modify the THESIS tool to do that.

**Comment by billsacks** [comment]
I would actually argue that the current formulation **is** consistent with other landunits: PCT_URBAN gives the % of the grid cell covered by each of the three urban landunits. If we had a situation where we had a single urban landunit that was broken down at a lower subgrid level into the different landunit types, then I would agree with @ekluzek 's suggestion, but since we have three separate urban landunits, I think the current way it's specified feels right to me.

**Comment by ekluzek** [comment]
Thanks for the feedback and discussion both of you. @olyson I wasn't thinking of changing the raw datasets, only the surface datasets. But, I like @billsacks point that this is at the landunit level (not beneath that), so it currently makes sense. As such let's leave it alone. I'm good with that. I just wanted to discuss.

I'll close this as a won't fix.
