### ISSUE TITLE
include optional case directory in run_neon.py?

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1970]
Currently `run_neon` automatically puts creates the run directory inside of the case directory. Users can decide where this goes using the `----output-root flag`. This is likely helpful for new users, but it's not typically how we teach more advanced tutorials where these case directory is created in *home* or *work* and the run directory ends up *scratch*.  

Should we include an option in `run_neon` to separate the location of the case and run directories? (The default functionality would function as designed with run inside of case directories).  It doesn't seem like this should be very difficult, but I struggled to do this quickly.  I also worried adding this feature would break the existing (simple) workflow of running AD, postAD, and transient cases.  Would adding this feature end up causing a bunch of work while accomplishing relatively little? 

See also directory structure [suggested in this tutorial](https://github.com/NCAR/CTSM-Tutorial-2022/blob/newTutorials/notebooks/Template_bash.ipynb) vs. how things are currently set up in the [Day0b tutorial](https://github.com/NCAR/CTSM-Tutorial-2022/blob/main/notebooks/Day0b_NEON_Simulation_Tutorial.ipynb)

What are your thoughts, @danicalombardozzi @adrifoster @TeaganKing @briandobbins

**Comment by adrifoster** [comment]
We decided not to do this.
