### ISSUE TITLE
fsurdatmodifyctsm test should abort if it has trouble running the python script

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1971]
I just ran into a problem with the FSURDATMODIFYCTSM script where it couldn't run the python because I didn't have the ctsm conda environment. The good news is that I got a helpful message in TestStatus.log telling me what to do. The bad news is that it happily proceeded past that point, creating a `done_FSURDATMODIFYCTSM_setup.txt` file (which I don't think should have been created) and trying to run the model.

I think the problem is in the exception-handling here:

https://github.com/billsacks/ctsm/blob/4620ac444804d2d1f1a8238ec304167d97aa2c33/cime_config/SystemTests/fsurdatmodifyctsm.py#L77-L91

It's helpful to have that exception handling in order to print a useful message, but I think the exception should be re-raised here, or some other exception / error should be raised so that the test aborts when this happens.

@slevisconsulting @ekluzek

**Comment by ekluzek** [comment]
Yes, I agree there should be a raise when that happens so that it doesn't continue on. Thanks for seeing this.

**Comment by billsacks** [comment]
I can add the raise in my tag.

**Comment by slevisconsulting** [comment]
Sounds good to me; thanks, @billsacks .
