### ISSUE TITLE
Change output from FATES tests to be double precision

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1986]
The FATES test mods appear to result in single precision history output, in contrast to most of our tests that output in double precision. Double precision output is useful for picking up small changes that may not be expected. I'd suggest that the FATES test mods be changed to use double precision output (hist_ndens = 1).

I feel like we have discussed this before, so apologies if I'm rehashing something that was already discussed and decided to stay as is.

@ekluzek @adrifoster @glemieux @rgknox

**Comment by adrifoster** [comment]
This sounds like a good idea to me.

**Comment by ekluzek** [comment]
Yes, you need to make sure hist_ndens is 1 for every set of history stream files being output. There usually are more than one output stream for our tests so you'll want it to be "1, 1" is there are two streams and "1,1,1" for three etc. It would also be fine to always set it to 1,1,1,1 to be sure you set enough of them...
