### ISSUE TITLE
Clean up relationship between h2ocan, snocan and liqcan

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#199]
_From @billsacks on March 9, 2017 20:39_

Currently, it appears that snocan and liqcan are only set if `snowveg_flag` is ON or ON_RAD; it looks like they are set to 0 otherwise. This tripped me up: I assumed that we would always have h2ocan = (snocan + liqcan), regardless of the value of snowveg_flag.

Furthermore, the updating of h2ocan, snocan and liqcan currently duplicates some code - e.g., with some updates being applied to h2ocan if snowveg_flag is OFF, but to snocan and/or liqcan if snowveg_flag is ON.

I would find it easier to read and modify the code if we always maintained h2ocan = (snocan + liqcan), and if h2ocan were just a diagnostic quantity computed as that sum - so that all fluxes got applied directly to snocan and/or liqcan. That is, anywhere where h2ocan is currently adjusted, we should instead adjust snocan and/or liqcan, and then later re-compute h2ocan as (snocan + liqcan). If snowveg_flag is OFF, I think this would mean applying all fluxes to liqcan.

Caveat: I haven't come to totally understand the relevant code, so I may be misunderstanding something.

_Copied from original issue: NCAR/CLM#1_

**Comment by billsacks** [comment]
_From @JustinPerket on May 30, 2017 23:14_

Hi Bill, I just got onto this github to write this area up in the tech note, so dunno if this issue is still open. If it's still relevant, your understanding and recommendation sounds good to me. Here's a path to implement them:

### 1. Replace uses of ho2can

It looks like ho2can is only explicitly utilized in the code in a couple of places, and can be safely replaced with liqcan+snocan:
- calculation of rpp in CanopyFluxes
- calculation of ecidif and qflx_evap_veg(p)  in CanopyFluxes
- use in water balance check in BalanceCheckMod and endwb in HydrologyDrainage. Averaging for h2ocan in clm_drv_patch2col would have to be replaced with averaging for liqcan and snocan

### 2. Clean up snow vegetation code to remove explicit ho2can updates

**It seems that this is still currently in CanopyFluxes:**

```fortran
         ! Update dew accumulation (kg/m2)                                                                       
         h2ocan(p) = max(0._r8,h2ocan(p)+(qflx_tran_veg(p)-qflx_evap_veg(p))*dtime)

         if (snowveg_on .or. snowveg_onrad) then
            if (t_veg(p) > tfrz ) then ! above freezing, update accumulation in liqcan                           
               if ((qflx_evap_veg(p)-qflx_tran_veg(p))*dtime > liqcan(p)) then ! all liq evap                    
                  ! In this case, all liqcan will evap. Take remainder from snocan                               
                  snocan(p)=snocan(p)+liqcan(p)+(qflx_tran_veg(p)-qflx_evap_veg(p))*dtime
               end if
               liqcan(p) = max(0._r8,liqcan(p)+(qflx_tran_veg(p)-qflx_evap_veg(p))*dtime)

            else if (t_veg(p) <= tfrz) then ! below freezing, update accumulation in snocan                      
               if ((qflx_evap_veg(p)-qflx_tran_veg(p))*dtime > snocan(p)) then ! all sno evap                    
                  ! In this case, all snocan will evap. Take remainder from liqcan                               
                  liqcan(p)=liqcan(p)+snocan(p)+(qflx_tran_veg(p)-qflx_evap_veg(p))*dtime
               end if
               snocan(p) = max(0._r8,snocan(p)+(qflx_tran_veg(p)-qflx_evap_veg(p))*dtime)
            end if
         end if
```
And can be replaced with:

```fortran
         ! Update dew accumulation (kg/m2)
         if (snowveg_on .or. snowveg_onrad) then
            if (t_veg(p) > tfrz ) then ! above freezing, update accumulation in liqcan                           
               if ((qflx_evap_veg(p)-qflx_tran_veg(p))*dtime > liqcan(p)) then ! all liq evap                    
                  ! In this case, all liqcan will evap. Take remainder from snocan                               
                  snocan(p)=snocan(p)+liqcan(p)+(qflx_tran_veg(p)-qflx_evap_veg(p))*dtime
               end if
               liqcan(p) = max(0._r8,liqcan(p)+(qflx_tran_veg(p)-qflx_evap_veg(p))*dtime)

            else if (t_veg(p) <= tfrz) then ! below freezing, update accumulation in snocan                      
               if ((qflx_evap_veg(p)-qflx_tran_veg(p))*dtime > snocan(p)) then ! all sno evap                    
                  ! In this case, all snocan will evap. Take remainder from liqcan                               
                  liqcan(p)=liqcan(p)+snocan(p)+(qflx_tran_veg(p)-qflx_evap_veg(p))*dtime
               end if
               snocan(p) = max(0._r8,snocan(p)+(qflx_tran_veg(p)-qflx_evap_veg(p))*dtime)
            end if ! above freezing
         else ! snowveg_flag is OFF, so liqcan defaults to old h2ocan behavior
            liqcan(p) = max(0._r8,liqcan(p)+(qflx_tran_veg(p)-qflx_evap_veg(p))*dtime)
         end if ! snowveg_on .or. snowveg_onrad

```

**Similarly, this line in CanopyHydrology could then be removed:**
```fortran
! Water storage of intercepted precipitation and dew
h2ocan(p) = max(0._r8, h2ocan(p) + dtime*qflx_prec_intr(p))
``` 


**Shortly after that, there's this:**
```fortran
                   if (snowveg_on .or. snowveg_onrad) then
                      if (forc_t(c) > tfrz) then ! Above freezing (Use t_veg?)                                                                        
                         xliqrun = (liqcan(p) - liqcanmx)/dtime
                         if (xliqrun > 0._r8) then
                            qflx_liqcanfall(p) = xliqrun
                            liqcan(p) = liqcanmx
                         end if
                      else ! Below freezing                                                                                                           
                         xsnorun = (snocan(p) - snocanmx)/dtime
                         if (xsnorun > 0._r8) then ! exceeds snow capacity                                                                            
                            qflx_snocanfall(p) = xsnorun
                            snocan(p) = snocanmx
                         end if
                      end if
                      qflx_candrip(p) = qflx_snocanfall(p) + qflx_liqcanfall(p)
                      h2ocan(p) = snocan(p) + liqcan(p)
                   else
                      ! Excess water that exceeds the leaf capacity                                                                                   
                      xrun = (h2ocan(p) - h2ocanmx)/dtime

                      ! Test on maximum dew on leaf                                                                                                   
                      ! Note if xrun > 0 then h2ocan must be at least h2ocanmx                                                                        
                      if (xrun > 0._r8) then
                         qflx_candrip(p) = xrun
                         h2ocan(p) = h2ocanmx
                      end if
                   end if
```
that can be replaced with:
```fortran
                   if (snowveg_on .or. snowveg_onrad) then
                      if (forc_t(c) > tfrz) then ! Above freezing (Use t_veg?)                                                                        
                         xliqrun = (liqcan(p) - liqcanmx)/dtime
                         if (xliqrun > 0._r8) then
                            qflx_liqcanfall(p) = xliqrun
                            liqcan(p) = liqcanmx
                         end if
                      else ! Below freezing                                                                                                           
                         xsnorun = (snocan(p) - snocanmx)/dtime
                         if (xsnorun > 0._r8) then ! exceeds snow capacity                                                                            
                            qflx_snocanfall(p) = xsnorun
                            snocan(p) = snocanmx
                         end if
                      end if
                   else !  snowveg_flag is OFF, liqcan assumes old h2ocan behavior
                      ! Excess water that exceeds the leaf capacity                                                                                   
                      xliqrun = (liqcan(p) - liqcanmx)/dtime

                      ! Test on maximum dew on leaf                                                                                                   
                      ! Note if xliqrun > 0 then liqcan must be at least liqcanmx                                                                        
                      if (xliqrun > 0._r8) then
                         qflx_liqcanfall(p) = xliqrun
                         liqcan(p) = liqcanmx
                      end if
                   end if

```

**Finally, there's this section in CanopyHydrology where wind- and temperature-based unloading fluxes are removed from the snocan store:**
```fortran
                if (snowveg_on .or. snowveg_onrad) then
                   qflx_snowindunload(p)=0._r8
                   qflx_snotempunload(p)=0._r8
                   snounload(p)=0._r8
                   if (snocan(p) > 0._r8) then
                      qflx_snotempunload(p) = max(0._r8,snocan(p)*(forc_t(c)-270.15_r8)/1.87e5_r8)
                      qflx_snowindunload(p) = 0.5_r8*snocan(p)*forc_wind(g)/1.56e5_r8
                      snounload(p) = (qflx_snowindunload(p)+qflx_snotempunload(p))*dtime ! total canopy unloading in timestep                         
                      if ( snounload(p) > snocan(p) ) then ! Limit unloading to snow in canopy                                                        
                         snounload(p) = snocan(p)
                         write(iulog,"(A,I2.2,A,ES13.4E2)") "snocan",p,": ",snocan(p)
                      end if
                      snocan(p) = snocan(p) - snounload(p)
                      h2ocan(p) = h2ocan(p) - snounload(p)
                   endif
                   qflx_prec_grnd_snow(p) = qflx_through_snow(p) + qflx_snocanfall(p)  + snounload(p)/dtime
                   qflx_prec_grnd_rain(p) = qflx_through_rain(p) + qflx_liqcanfall(p)

                else
                   qflx_prec_grnd_snow(p) = qflx_through_snow(p) + (qflx_candrip(p) * fracsnow(p))
                   qflx_prec_grnd_rain(p) = qflx_through_rain(p) + (qflx_candrip(p) * fracrain(p))
                end if
```
Here now the ` h2ocan(p) = h2ocan(p) - snounload(p)` line can be removed.

After that, h2ocan can just be the sum of snocan and liqcan in the history, and there shouldn't be any answer changes, though I haven't tested this.

**Comment by billsacks** [comment]
@JustinPerket - thanks a lot for your thoughts. Yes, this is still an open issue. I haven't read your suggestions carefully yet (still digging out from my vacation), but thank you for taking the time to respond to this.

**Comment by billsacks** [comment]
I think it would be helpful to do this before #360

**Comment by billsacks** [comment]
@JustinPerket Just a heads-up that I'm hoping to do this cleanup this week.

**Comment by billsacks** [comment]
@dlawrenncar @olyson @swensosc - is it important to keep H2OCAN on the history file, or is it sufficient to have LIQCAN and SNOCAN? If we keep H2OCAN, it will just be the sum of LIQCAN and SNOCAN. After doing the cleanup in this issue, we'd need to do a bit of extra work to maintain this extra diagnostic field (e.g., introducing a new routine in WaterDiagnosticType that computes this diagnostic field)... it's not too much work, but I wanted to check whether you actually want to retain this field before we do this work.

**Comment by olyson** [comment]
I would lean toward keeping it.  That variable has a long history in CLM and it's convenient to have the total water on the canopy instead of having to add two variables.

**Comment by billsacks** [comment]
Okay, thanks - we can keep it.

**Comment by billsacks** [comment]
@dlawrenncar and @swensosc have given the okay for removing the old version of this code - i.e., removing the option, snowveg_flag = 'OFF'. We should continue to support snowveg_flag = 'ON' and 'ON_RAD'. The clm45 default will become snowveg_flag = 'ON_RAD' (as for clm50); this will change clm4_5 scientifically (at least somewhat).

I think we should do this in two steps:

1. Remove support for snowveg_flag = 'OFF', and change the clm4_5 defaults. This will be answer changing for clm4_5.

2. Do some additional cleanup, as discussed above, making h2ocan just set once near the end of the driver loop, and replace all uses of this variable in the code with liqcan+snocan. This should be bit-for-bit with (1).

**Comment by billsacks** [comment]
Now that we're not supporting snowveg_flag = 'OFF' (so are just supporting 'ON' and 'ON_RAD'), I'm changing the string-valued snowveg_flag to a logical, `snowveg_affects_radiation`, because this feels cleaner both in the namelist and in the code. @ekluzek @dlawrenncar @olyson let me know if you object to this change.

**Comment by dlawrenncar** [comment]
This sounds reasonable to me.
