### ISSUE TITLE
ILAMB installation, data, documentation, and upkeep

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#2001]
Based on a meeting with @olyson , @slevis-lmwg , and @adrifoster , it was decided to move forward with a more permanent location for ILAMB code and data that could be shared by users.
Currently, ILAMB data is located here under @olyson 's personal directory:

/glade/p/cesm/lmwg_dev/oleson/ILAMB/ILAMB_all/DATA

Currently, the ILAMB github repository is cloned by individual users and then an ILAMB conda environment is created by each user.

We propose instead to put ILAMB data and code in the lmwg/diag space under subdirectories, e.g.,

/glade/p/cesm/lmwg/diag/ILAMB/DATA
/glade/p/cesm/lmwg/diag/ILAMB/CODE

Users would set their ILAMB_ROOT to /glade/p/cesm/lmwg/diag/ILAMB.
If possible, users would then share a common conda environment, or create their own environment based on the shared code (@adrifoster to investigate).
Maintaining the DATA and CODE directories would be the responsibility of the CTSM science liaison(s).
A README would be included containing instructions for creating a conda environment if necessary, running ILAMB, and the procedure for liaison(s) to update code and data.

Suggestions/comments welcome.

**Comment by ekluzek** [comment]
I think this makes sense. My guess is that individuals won't be playing with their local sandbox for ILAMB, especially for the data. If people were going to customize their local version you would want them to have their own copy (especially if it were small). But, this set is extremely large, so having it shared in a more public place makes sense.

On the conda environment, we could have a script in CTSM that creates the conda environment. I would think most of the people who will use ILAMB will also be using CTSM. One way to do this would be to add a "--ilamb" argument to py_env_create and have it create an environment say called ilamb_pylib. CTSM could manage any changes to ILAMB that way. Or you could add a similar script to the ILAMB directory to make a conda environment.

**Comment by wwieder** [comment]
I love this idea.  Thanks for making it happen.

**Comment by olyson** [comment]
@ekluzek , could you remove this very old installation of ILAMB to avoid confusion:

/glade/p/cesm/lmwg/ilamb

**Comment by ekluzek** [comment]
OK, I was able to remove most of it. @swensosc and @dlawrenncar some of the files under there are owned by you. Could you delete them? You should be able to do

\rm -rf /glade/p/cesm/lmwg/ilamb

and it'll delete the files that are yours. I'll probably need to do the same again after you are done to delete all of the directories.

**Comment by dlawrenncar** [comment]
OK.  I've deleted my files.

**Comment by olyson** [comment]
Some tasks:

- [x] Place ILAMB data in /glade/p/cesm/lmwg/diag/ILAMB/DATA
- [x] Place ILAMB code in /glade/p/cesm/lmwg/diag/ILAMB/CODE
- [x] Create ilamb_lmwg conda environment (@olyson for now)
- [x] Place sample run script, configuration files, and model_setup.txt files in /glade/p/cesm/lmwg/diag/ILAMB/SCRIPTS
- [x] Verify proper operation.
- [ ] Remove /glade/p/cesm/lmwg_dev/oleson/ILAMB/ILAMB_all installation.

**Comment by olyson** [comment]
Thanks @adrifoster .  It seems like it would be useful to look at a copy of the one of the scripts used for installing the E3SM diagnostics (which include ILAMB).  They are on machines that I don't have access to:

"To get all of the tools in the metapackage installed, use one of the sets of commands below and the activation path from the table below.

Default (without conda-forge version of MPI) for bash or csh shells:
source <activate_path>/load_latest_e3sm_unified_<machine>.sh
  or
source <activate_path>/load_latest_e3sm_unified_<machine>.csh
 

Path to activation script: <activate_path>

ACME1 (LLNL) – /usr/local/e3sm_unified/envs
Anvil/Blues & Chrysalis (ANL) – /lcrc/soft/climate/e3sm-unified
Compy (PNNL) – /share/apps/E3SM/conda_envs
Cooley  (ALCF) – /lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified
Cori (NERSC) – /global/common/software/e3sm/anaconda_envs"

I'm wondering if @rgknox or @glemieux have access to one of these machines and would be willing to provide a copy (maybe one of the bash scripts).

**Comment by olyson** [comment]
@slevis-lmwg has successfully created an ilamb environment, from a shared code base, and completed a run, following the instructions given here:

/glade/p/cesm/lmwg/diag/ILAMB/README

Other people with access to cheyenne are welcome to try this as well.

**Comment by rgknox** [comment]
@olyson just seeing the request for the script on NERSC now... is this still something that I can retrieve, or has this been solved?

**Comment by olyson** [comment]
@rgknox , I think we are in good shape, but it might still be useful to look at a copy if it is easily retrieved, thanks.

**Comment by rgknox** [comment]
```
~> cat /global/common/software/e3sm/anaconda_envs/load_latest_e3sm_unified_pm-cpu.csh 
```
```
source /global/common/software/e3sm/anaconda_envs/base/etc/profile.d/conda.csh

setenv E3SMU_SCRIPT "/global/common/software/e3sm/anaconda_envs/load_e3sm_unified_1.8.1_pm-cpu.csh"
setenv E3SMU_MACHINE "pm-cpu"

if ( ! $?SLURM_JOB_ID && ! $?COBALT_JOBID ) then
# we seem to be on a login node, so load the no-MPI environment

setenv E3SMU_MPI "NOMPI"
conda activate e3sm_unified_1.8.1_nompi

setenv HDF5_USE_FILE_LOCKING FALSE

else
# we seem to be on a compute node, so load the MPI environment

setenv E3SMU_MPI "SYSTEM"
conda activate e3sm_unified_1.8.1_pm-cpu

source /global/common/software/e3sm/anaconda_envs/spack/spack_for_mache_1.10.0/share/spack/setup-env.csh
spack env activate e3sm_unified_1_8_1_pm-cpu_gnu_mpich

setenv HDF5_USE_FILE_LOCKING FALSE

endif

```

**Comment by olyson** [comment]
Thanks @rgknox
