### ISSUE TITLE
Test ERR_Ld5.f09_t061.B1850MOM.cheyenne_intel.allactive-defaultio failing

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CTSM#2003]
### Brief summary of bug

In the rpointer.lnd file is ./init_generated_files/finidat_interp_dest.nc  
however this file does not exist for run2.

### General bug information

**CTSM version you are using:**  ctsm5.1.dev122

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:**  ERR test

### Details of bug

[Fill in details here.]

### Important details of your setup / configuration so we can reproduce the bug

[Specify anything relevant: the compset, resolution, machine, compiler, any xml or namelist changes, etc. You don't have to repeat anything that you have already noted above.]

### Important output or errors that show the problem

[Fill this in with anything relevant that you haven't already noted; if there is nothing to add, delete this section.]

**Comment by ekluzek** [comment]
@jedwards4b it looks to me like this is maybe a new test that's maybe just being added? And that's why we haven't seen this before? I didn't see this test on baselines on cheyenne for cesm2_3 tags. If it was working in the past I wanted to compare to a previous working version. But, if there isn't such a version, that approach isn't going to help me. So I wanted to understand the history of this test...

**Comment by jedwards4b** [comment]
It's in the cmeps test list, here is a baseline:
 /glade/p/cesmdata/cseg/cmeps_baselines/cesm2_3_beta08_cmeps0.13.47/ERR_Vnuopc_Ld5.f09_t061.B1850MOM.cheyenne_intel.allactive-defaultio/

**Comment by jedwards4b** [comment]
It's interesting that ERR_Vnuopc_Ld5.f09_t061.B1850MOM.cheyenne_intel.allactive-defaultio.20230511_124427_2661ny passed - I made a change in the restart_tests.py in cime 
which I decided before the run ended wouldn't work - I didn't expect that run to pass.   I wonder if there is a
race condition between copying the rpointer file to the archive directory and updating it.

**Comment by billsacks** [comment]
It looks like you may have run `ERR_Vnuopc_Ld5.f09_t061.B1850MOM.cheyenne_intel.allactive-defaultio.20230511_103340_ih649u` multiple times, and I wonder if something got messed up from doing that?? I see two sets of logs in the archive/logs directory from that case, and the time stamps on the restart files in /glade/scratch/jedwards/archive/ERR_Vnuopc_Ld5.f09_t061.B1850MOM.cheyenne_intel.allactive-defaultio.20230511_103340_ih649u/rest/0001-01-04-00000 have a confusing pattern, where most of them are from 11:27 or 11:28, but the rpointer.lnd is from 11:40, and the restart files in /glade/scratch/jedwards/ERR_Vnuopc_Ld5.f09_t061.B1850MOM.cheyenne_intel.allactive-defaultio.20230511_103340_ih649u/run are from a few minutes after that. So it feels like something wrong happened on the archiving side, but I can't tell what.

**Comment by jedwards4b** [comment]
I tried again from scratch and this time it passed.

**Comment by billsacks** [comment]
Great, thanks a lot @jedwards4b !
