### ISSUE TITLE
Five izumi NEON tests fail (for me) because the testnames include L10d instead of Ld10

### ISSUE THREAD

**Issue by slevis-lmwg** [ESCOMP/CTSM#2043]
### Brief summary of bug

See title.

### General bug information

**CTSM version you are using:** ctsm5.1.dev129

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** Five izumi NEON tests

### Details of bug

- The tests work for me when I change L10d to Ld10, so I made the change in my testlist_clm.xml.
- The same tests worked for @ekluzek without this change, and we were unable to understand why.

**Comment by glemieux** [comment]
I'm seeing the same thing in testing #2009 and associated  https://github.com/NGEET/fates/pull/958#issuecomment-1615059133.  Should I roll the fix into #2009?

**Comment by glemieux** [comment]
> I'm seeing the same thing in testing #2009 and associated [NGEET/fates#958 (comment)](https://github.com/NGEET/fates/pull/958#issuecomment-1615059133). Should I roll the fix into #2009?

I've got a commit for this in #2009: https://github.com/ESCOMP/CTSM/pull/2009/commits/74f9bd1c433908743fff34d6a0259434507de28e

**Comment by slevis-lmwg** [comment]
I would support rolling the fix into #2009.
