### ISSUE TITLE
Allow an override for ndep so that it isn't applied?

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2050]
This is a question that @rgknox asks here: https://github.com/ESCOMP/CTSM/pull/1959#discussion_r1204600763.

"I suppose we should accommodate an override, if a user really wants to turn off deposition with an active N cycle". He asks this in the context of FATES, but I think the option could also be applied to BGC. The question is if this is something that would be desired?

@adrifoster @wwieder @olyson @dlawrenncar @danicalombardozzi  and others any thoughts on this?

**Comment by danicalombardozzi** [comment]
I have turned off Ndep in CLM4.5 to determine the magnitude of impact on carbon fluxes. Has something has changed in CLM5 that would make this not possible?

**Comment by ekluzek** [comment]
We certainly haven't changed anything intentionally for this. But, we also don't test with ndep off. And if this is an important mode maybe we should? 

I actually didn't think that you could easily turn ndep off, but looking at the code I think maybe you could if you set stream_fldfilename_ndep and stream_meshfile_ndep to blank, and also trigger "---ignore_warnings" in CLM_BLDNML_OPTS. So it's possible this already works. Does setting that to blank sound like how you did this in the past? And do you think this is an important mode that we should make sure still works? If so I'll just change this to adding a test for this.

**Comment by billsacks** [comment]
From discussion at ctsm-software: closing as wontfix for now (because a user can modify the ndep file as needed); can reopen in the future if needed.
