### ISSUE TITLE
Add option to hist_addfld call to convert NaN's to spval?

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2064]
Some of @johnpaulalex work got me thinking about this. Our current practice is to initialize arrays to signaling NaN's just after allocation, but then just before the hist_addfld call to set everything to spval. One problem with this practice is if you forget to initialize it to spval before the hist_addfld call, this is especially a problem for variables that are optionally output and not output in our normal testing.

A better way to do it would be to have an optional argument to hist_addfld, that converts values initialized to NaN to spval. This allows us to convert to this paradigm over time. A slightly better way to do it would be for a flag to be set at the hist_addfld field call, but that it wouldn't be acted upon until the end of initialization, when you can determine if that field is going to be output. If it's not output, it wouldn't be changed. At this point the field is likely set, so NaN values are just going to be at locations that aren't defined, so it's a robust.

**Comment by ekluzek** [comment]
An alternative way to think about this is that the reason we have to set values output by history to spval, is so that averaging isn't done over spval values. But, that's because we don't keep the associated filter with the data when we do averaging. If averaging knew what filter to run over, it wouldn't average in data outside its domain.

The philosophy of setting values to signaling NaN so that if it's used when it shouldn't be is really useful. The fact that we have to break that philosophy for history variables points out a weakness in our code.

**Comment by ekluzek** [comment]
Some thoughts that @johnpaulalex had on this:

> "Longer-term,  one idea to make the NaN-error-detector mechanism actually work aka surface bugs for you:
> Continue to initialize all history arrays to NaN.
> Stop blindly overwriting entire arrays, for every timestamp, to spval.  
> Instead, make it the responsibility of the history-field-owning code to fill in spval's where necessary.  iiuc there are often holes in these history fields - fine - but it should be up to the particular history field to say  "fill [0] with a value but [1] with an spval then [2] with a value, etc" or, if needed, "for this specific special case, fill the entire thing with spval's, because we can't compute this field at all, and ps no one will override any of these spval's."  I guess this applies both to filling in every element of the array at a particular point in time _and_ filling in every instance of the array for every point in time.  Does that sound doable? I'm not familiar with the flow of the code filling these variables. [This code](https://github.com/ESCOMP/CTSM/blob/4a868c1ccd700e78b5a2c2f064441a1d612c57bf/src/biogeophys/CanopyFluxesMod.F90#L1047C24-L1047C27) fills rah1 but it's iterating [1,fn] (fn = 'number of values in vegetated patch filter') and then transforming that index to a 'p' variable (p = filterp(f)).  I don't know if p is meant to map to time or to an index within an array for a given time.
> Might be a lot of work to convert existing variables but maybe at least it could be a convention going forward.
> 
> On a smaller note I think it wouldn't be hard to make this type of crash, when it does happen, to more easily surface the related bug. Rather than have it die with an opaque stack trace wherever it touches the NaN, add an explicit NaN check in the code that provides more info. I'd guess this could be in hist_update_hbuf_field_1d and 2d ([pointer to the 1d code](https://github.com/ESCOMP/CTSM/blob/4a868c1ccd700e78b5a2c2f064441a1d612c57bf/src/main/histFileMod.F90#L1397))  where it creates a 'field' variable, which afaict is the array that it expects to be filled.  Would it be too expensive to have the code check that every entry in there is !shr_infnan_isnan()? (iiuc this method is called for every field over every time value: [loop](https://github.com/ESCOMP/CTSM/blob/4a868c1ccd700e78b5a2c2f064441a1d612c57bf/src/main/histFileMod.F90#L1310)) Then if it finds a NaN, it can print an informative error with field name and field idx and die.   And there could be a comment there describing how to debug and common cases (e.g. right now, it could advise confirming that the history field is initted to spval)."

**Comment by glemieux** [comment]
> The philosophy of setting values to signaling NaN so that if it's used when it shouldn't be is really useful. The fact that we have to break that philosophy for history variables points out a weakness in our code.

As a related aside, this came up during my work to bring elm up to date with fates spitfire https://github.com/E3SM-Project/E3SM/pull/5369#discussion_r1128773267, which itself points to a different e3sm issue discussion about moving away from using nan generally.

**Comment by billsacks** [comment]
The ideas raised here are great. They are also in line with earlier discussion we have had. See #1297 (especially the "My preferred solution" heading in the initial comment in that issue) and the project we created for this: https://github.com/ESCOMP/CTSM/projects/35. I'd be happy to discuss this further.

Because of the substantial overlap between this issue and #1297 (and other issues in the above-referenced project) I would suggest closing this issue as a duplicate and folding this discussion into those other issues. @ekluzek @johnpaulalex does that sound okay to you?

**Comment by ekluzek** [comment]
Duplicate of #1297 which provides a better solution.
