### ISSUE TITLE
Change names on ctsm5.2 datasets to include context for "_78_" to "_78pfts"

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2073]
Names for landuse.timeseries on the ctsm5.2 branch currently should change.

We want to go to this format:

lnd/clm2/surfdata_esmf/ctsm5.2.0/landuse.timeseries_0.9x1.25_hist_1850-2015_78pfts_c230601.nc
lnd/clm2/surfdata_esmf/ctsm5.2.0/fsurdat_0.9x1.25_hist_1850_78pfts_c230601.nc
lnd/clm2/surfdata_esmf/ctsm5.2.0/fsurdat_0.9x1.25_hist_2000_78pfts_c230601.nc
lnd/clm2/surfdata_esmf/ctsm5.2.0/fsurdat_0.9x1.25_hist_2015_78pfts_c230601.nc
lnd/clm2/surfdata_esmf/ctsm5.2.0/landuse.timeseries_0.9x1.25_SSP2-4.5_1850-2100_78pfts_c230601.nc
lnd/clm2/surfdata_esmf/ctsm5.2.0/fsurdat_0.9x1.25_SSP2-4.5_2100_78pfts_c230601.nc

The _78_ part should become _78pfts_

**Comment by ekluzek** [comment]
Also should 1850-2015 become _simyr1850-2015 as we had before?

**Comment by slevis-lmwg** [comment]
@ekluzek while we're updating the file names, I have additional suggestions.

Starting from names like the one that you presented above:
`landuse.timeseries_0.9x1.25_hist_78_CMIP6_1850-2015_c230601.nc`
...what if we changed to:
`landuse.timeseries_0.9x1.25_hist_1850-2015_78pfts_c230601.nc`

I have made three changes to the file name:
1) Added `pfts` back, as you recommended.
2) Did not add `simyr` as it seems unnecessary to me but moved the year range right after `hist` because these two are related.
3) Removed CMIP6 and understand if this needs to stay.

**Comment by ekluzek** [comment]
@slevis-lmwg I like your proposal. The one question I have is if we should keep CMIP6, this does tell you what generation of data was used. @lawrencepj1 do you have an opinion on keeping (or not keeping) the CMIP6 identifier in the surface dataset names? This part only changes every few years with the next CMIP cycle. I think it can be helpful to see what generation the data is from, but I'd like to hear from others if they think it's useful.

**Comment by lawrencepj1** [comment]
Hi Erik

I think as long as we have the CTSM version in the name we don't need to
have the CMIP version as well. There will be overlap from CMIP6 to CMIP7
for SSP3-7.0 but other scenarios will have different names. The netcdf
metadata would be a better place to include that information.

Thanks
Peter
-- 
Dr Peter Lawrence
Terrestrial Science Section
National Center for Atmospheric Research
1850 Table Mesa Drive
Boulder Colorado 80305

Work: 1-303-497-1727
Cell: 1-303-956-6932

**Comment by slevis-lmwg** [comment]
> Hi Erik I think as long as we have the CTSM version in the name we don't need to have the CMIP version as well. 

So back to my example, maybe something like this?
`landuse.timeseries_0.9x1.25_hist_1850-2015_78pfts_ctsm52_c230601.nc`
I added the `ctsm52` right before the date stamp, because the two are somewhat related.

**Comment by lawrencepj1** [comment]
Thanks Sam,

Yes that looks perfect way to capture the version of the landuse data.

Peter
-- 
Dr Peter Lawrence
Terrestrial Science Section
National Center for Atmospheric Research
1850 Table Mesa Drive
Boulder Colorado 80305

Work: 1-303-497-1727
Cell: 1-303-956-6932

**Comment by slevis-lmwg** [comment]
Reminder from meeting with @ekluzek :
- The same renaming proposal applies to the fsurdat files, as well
- The renaming will require a repeat of ./rimport
- The ne120 file is large, so maybe trying an svn copy for that one if it will work

**Comment by slevis-lmwg** [comment]
@adamrher also asks whether fsurdat files generated for transient cases need to include the range of years in their name, as is done now. I think the answer is: No, they do not and to reduce potential confusion, how about we return fsurdat names to including the start year, rather than the range.

**Comment by slevis-lmwg** [comment]
Also, we are now discussing possibly completing #1886 to clarify when ocean is ocean and not wetland in fsurdat files. If so, then we will regenerate all fsurdat files after #1886 is completed.

**Comment by ekluzek** [comment]
@slevis-lmwg and I went over the naming convention and went with what what I changed the introduction to this to. Here's an example:

lnd/clm2/surfdata_esmf/ctsm5.2.0/landuse.timeseries_0.9x1.25_hist_1850-2015_78pfts_c230601.nc
