### ISSUE TITLE
Add unit test for making fsurdat with all crops everywhere

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2079]
Given a surface dataset file, [make_fsurdat_all_crops_everywhere.py](https://github.com/ESCOMP/CTSM/blob/ctsm5.1.dev131/python/ctsm/crop_calendars/make_fsurdat_all_crops_everywhere.py) makes a version of it that has (a) all natural land moved into cropland and (b) cropland split evenly among all CFTs. This special file is used to generate prescribed crop maturity requirements, with the idea being that we want a value for every crop in every gridcell regardless of whether the crop is currently there.

@ekluzek suggested, rightly, that I add a unit test for this script. Things to test:

- [ ] Every land gridcell has `PCT_CROP` > 0
- [ ] Every land gridcell has `PCT_CFT` > 0 for all crops

I should be able to use the existing surface datasets in `python/ctsm/test/testinputs/` for this.

**Comment by samsrabin** [comment]
Hmm. In searching for an example of a Python test, I realized that this functionality should probably just be built into the existing modify_fsurdat.py, rather than being an entirely separate (although small) script. 

Tagging @slevis-lmwg, whose work seems to dominate the `git blame` for that. What do you think?

**Comment by slevis-lmwg** [comment]
> [...] this functionality should probably just be built into the existing modify_fsurdat.py, rather than being an entirely separate (although small) script.

@samsrabin you are likely correct OR the functionality already exists in the `modify_fsurdat` tool's function `read_cfg_subgrid`.

@ekluzek added the section of code that may already do what you need, and I have not tried this functionality. I would be happy to meet with you to go over how the tool works, and then try out such functionality already exists.
