### ISSUE TITLE
Rework master_list_(no)?fates.rst?

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2083]
My first big-kid PR merge got me thinking about the files `master_list_nofates.rst` and `master_list_fates.rst`. Primarily, I'm wondering if we really need the line numbers included, as doing so means editing the list causes huge diffs in the git history. For example, adding 11 variables in #1863 caused [over 750 lines of diffs](https://github.com/ESCOMP/CTSM/pull/1863/files#diff-8609dcf1357cc3e508de7c54449b7169dcbd926eeb575a221da0286acd08584f).

Some other thoughts:
* We should probably remove "master" from the filenames.
* The filenames should more clearly describe what is in the files.

**Comment by billsacks** [comment]
Good points, @samsrabin - I agree with all of these suggestions.

**Comment by ekluzek** [comment]
I agree as well. Your suggestions would be a nice improvement.
