### ISSUE TITLE
Add a fates test suite for perlmutter

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2085]
@glemieux and I talked about this a bit. It would be sometimes helpful to have the fates test suite to have tests to run on perlmutter. In instances like this week when cheyenne is down. perlmutter is also an important machine for LBL folks, so it could be helpful to have it as an option to run on occasion.

**Comment by glemieux** [comment]
Closing this out as https://github.com/E3SM-Project/E3SM/issues/5548 better addresses the issue of attain test parity on perlmutter since  e3sm is actively supported on that machine.
