### ISSUE TITLE
Add "parameter type: CN vs FATES, etc." attribute to parameter file

### ISSUE THREAD

**Issue by adrifoster** [ESCOMP/CTSM#2104]
It would be nice to have an attribute for all parameters on the CLM parameter file that indicated whether they were effective in CN vs. FATES or either ("land"?) mode. 

I have done a PPE in FATES SP mode (perhaps should try full FATES) that should tell us which parameters have any effect with FATES turned on. It would be nice to add this to the parameter file in some respect. 

We should make this some kind of consistent flag so that it can be accessed and analyzed programmatically.

Also in discussion with @slevis-lmwg, this could go along with cleaning up the MIMICS parameters since many are missing units and long names (see #1845)

**Comment by samsrabin** [comment]
From CTSM SE meeting today: Adrianna would need to do more testing in modes other than FATES-SP to figure this out. It's not CN vs. FATES _parameters_; it's just parameters that _change answers_ in different modes.

We think this would be nice but better as a wiki page—we don't want to have to re-check everything with every tag.
