### ISSUE TITLE
conda run -n can fail if a conda environment is already active

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2109]
### Brief summary of bug

For tests that invoke `cmds_to_setup_conda()`, manually calling the script invoking that function (e.g., `case.build` for `FSURDATMODIFYCTSM`) could fail if doing so with a conda environment already activated. The problem is that

```bash
conda run -n ctsm_pylib ...
```

seems to not actually use ctsm_pylib if, for instance, the conda base environment is active.

Note that this is a _different_ issue (and gives a different sort of error) from #2111.

### General bug information

**CTSM version you are using:** `ctsm5.1.dev133`

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** FSURDATMODIFYCTSM and RXCROPMATURITY tests.

### Important details of your setup / configuration so we can reproduce the bug

Calling `case.build` for an `FSURDATMODIFYCTSM` test fails for me if I've previously done `conda activate base`.

### Important output or errors that show the problem

In TestStatus.log, something like:
```
subprocess.CalledProcessError: Command '. /glade/scratch/afoster/tests_0814-163644ch/FSURDATMODIFYCTSM_D_Mmpi-serial_Ld1.5x5_amazon.I2000Clm50SpRs.cheyenne_intel.C.0814-163644ch_int/.env_mach_specific.sh;  conda run -n ctsm_pylib python3 /glade/work/afoster/CTSM/tools/modify_input_files/fsurdat_modifier /glade/scratch/afoster/tests_0814-163644ch/FSURDATMODIFYCTSM_D_Mmpi-serial_Ld1.5x5_amazon.I2000Clm50SpRs.cheyenne_intel.C.0814-163644ch_int/modify_fsurdat.cfg' returned non-zero exit status 1.
```
And in fsurdat_modifier.log, something like:
```
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_standardize-time-metadata/tools/modify_input_files/fsurdat_modifier", line 15, in <module>
    from ctsm.modify_input_files.fsurdat_modifier import main
  File "/glade/u/home/samrabin/ctsm_standardize-time-metadata/tools/modify_input_files/../../python/ctsm/modify_input_files/fsurdat_modifier.py", line 20, in <module>
    from ctsm.modify_input_files.modify_fsurdat import ModifyFsurdat
  File "/glade/u/home/samrabin/ctsm_standardize-time-metadata/tools/modify_input_files/../../python/ctsm/modify_input_files/modify_fsurdat.py", line 12, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

ERROR conda.cli.main_run:execute(47): `conda run python3 /glade/u/home/samrabin/ctsm_standardize-time-metadata/tools/modify_input_files/fsurdat_modifier /glade/scratch/samrabin/tests_0815-121457ch/FSURDATMODIFYCTSM_D_Mmpi-serial_Ld1.5x5_amazon.I2000Clm50SpRs.cheyenne_intel.0815-121457ch/modify_fsurdat.cfg` failed. (See above for error)
```
(The missing module could be something other than `numpy`.)

**Comment by ekluzek** [comment]
@samsrabin thanks for adding this issue and figuring out how to fix it!

This is important to fix for me since I normally use python via a conda environment. And there seems to be python issues if you try to run the standard python scripts without a current version of python (such as run_sys_tests and create_test, etc.).
