### ISSUE TITLE
Add LND_TUNING_MODE for CAM4, CAM5, CAM7

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2117]
We have LND_TUNING_MODE as an XML variable that gets input into the build-namelist that determines specific tunings for some parameters in the model. LND_TUNING_MODE is the clm physics version (clm4_5, clm5_0, or clm5_1) and then the atmospheric forcing (GSWP3, CRU, or QIAN, and then CAM physics). Right now we only have an option for CAM6.0 physics.

So I suggest that add tuning modes for CAM4, and CAM5 because of this issue pointed out with dust emissions...

https://github.com/ESCOMP/CTSM/pull/1967#issuecomment-1684546728

At the same time if the CAM physics is CAM3 -- I'll set it to CAM6 settings.

Originally I was thinking CAM%DEV and CAM%SPCAM might be importan as said here....
I also figure we should add CAM%DEV in preparation for setting tuning for the latest development version of CAM.
The other physics option for CAM is CAM%SPCAM*. I suppose I'll have it set the same as the CAM%DEV version. If we do customize tuning for CAM%DEV vs. CAM%SPCAM* we can add that in later.

However, on discussion we realized this would only be important if we were going to tune CTSM parameters for those configurations. And I think the only time tuning of CTSM parameters will be done is with finalized CAM versions. So CAM7 will have tuned CTSM settings -- but the development versions will rely on the last tuned settings.

**Comment by ekluzek** [comment]
With the upcoming CESM3 release CAM is going to have a CAM7 option and we might as well add it in preparation for the CESM3 release.

**Comment by samsrabin** [comment]
From SE meeting today: Don't add it for `CAM%DEV` and `CAM%SPDEV`.

**Comment by ekluzek** [comment]
CAM7 isn't added yet (nor available). So opening another issue for this.
