### ISSUE TITLE
C isotope fields get bad values after a few time steps when starting from initial conditions without C isotopes

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#2119]
### Brief summary of bug

When running in a configuration with C isotopes, but starting from an initial conditions file without C isotopes, the C isotope fields get bad values within the first few time steps of the run.

### General bug information

**CTSM version you are using:** Recent versions

**Does this bug cause significantly incorrect results in the model's science?** Yes, but only in limited configurations

**Configurations affected:** Configurations with C isotopes, but with finidat from a run without C isotopes

### Details of bug

This finding emerged from @olyson 's investigations of #1358 . However, we are going to resolve that issue by re-introducing initial conditions files with C isotopes for use in C isotope runs / tests; we are opening this new issue to track the more general problem that C isotope fields become garbage when starting from a finidat file without C isotopes. It is not clear when this problem started, but it presumably started sometime before ctsm5.1.dev008: C isotope tests started having garbage values in ctsm5.1.dev008, and it now seems like that was due to the combination of two things: (1) Changing the initial conditions file used in C isotope tests to one that doesn't have C isotopes on it (which happened in ctsm5.1.dev008: changed from clmi.I1850Clm50BgcCrop-ciso.1366-01-01.0.9x1.25_gx1v7_simyr1850_c200428.nc to clmi.I2000Clm50BgcCrop.2011-01-01.1.9x2.5_gx1v7_gl4_simyr2000_c190312.nc) and (2) a bug that causes C isotope fields to become garbage when starting from an initial conditions file without C isotopes on it (we don't know when that bug began; I think it was lurking undetected until we switched to initial conditions files without C isotopes in ctsm5.1.dev008).

Note that this differs from #67 , which is specific to using init_interp: this current issue exists even when not interpolating initial conditions, according to @olyson 's testing.

See some comments in  #1358 for details - especially: https://github.com/ESCOMP/CTSM/issues/1358#issuecomment-1670447381 https://github.com/ESCOMP/CTSM/issues/1358#issuecomment-1672076583 and https://github.com/ESCOMP/CTSM/issues/1358#issuecomment-1672076583

**Comment by wwieder** [comment]
At the SE meeting we agreed that initializing an isotope run from a non-iso restart is going to be challenging to support.  Instead, let's have a run fail that tries to do this with a meaningful error message.

**Comment by olyson** [comment]
I forgot that there is an error check on initializing an isotope run from a non-iso restart file, which is triggered if use_init_interp=.true. (implemented due to issue #67 ), and ends the run.  But for the purposes of this issue here, maybe this should be done even when use_init_interp=.false.?
Regardless, I'm feeling a bit guilty about dropping my investigation of this.  I had spent a few days investigating but didn't get anywhere.  I'm thinking about going back to it and maybe getting a fresh look at it will help.  @billsacks , what do you think?  I'm not sure how important it is to support going from non-isotope initial file to an isotope run, since even if the bug is fixed, the isotopes will not be spunup.

**Comment by billsacks** [comment]
I don't have strong feelings one way or the other. My recollection is that, at one point – including in the lead-up to CESM2 and CLM5 – it was important to have the capability to start a run with isotopes from an initial conditions file without isotopes. I guess this was because spinup was commonly done without isotopes and there was some value in starting from that point rather than doing a completely new spinup for isotopes? But you all (@olyson @wwieder and others) probably understand this better than I do, so I am totally happy to defer to you as to whether this is still an important capability.

**Comment by olyson** [comment]
Ok thanks @billsacks , that was my recollection as well.  I've been regularly spinning up isotopes in my land-only (and CPLHIST) simulations for CESM3 development, so as long as we keep doing that I think we're ok.

**Comment by slevis-lmwg** [comment]
Closing due to the merge of #2229 as a result of merging #2253.
