### ISSUE TITLE
baset_latvary_slope and baset_latvary_intercept not used

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2127]
### Brief summary of bug

Namelist parameters `baset_latvary_slope` and `baset_latvary_intercept` don't seem to actually be used. Instead, the default values (4 and 12, respectively) are hard-coded in `CropType%InitCold`.

### General bug information

**CTSM version you are using:** `ctsm5.1.dev139-1-g6282180d9`

**Does this bug cause significantly incorrect results in the model's science?** Not unless the user wanted to set those, which I can't imagine happens often.

**Configurations affected:** Crop compsets.

### Details of bug
They're hard-coded here:
https://github.com/ESCOMP/CTSM/blob/1e2e2c35d9568c94eac6cb606f37c18294158682/src/biogeochem/CropType.F90#L373-L379

In addition, I think that whole `if` block could be refactored into a one-liner that would additionally avoid hard-coding the ±30° boundaries:
```fortran
this%latbaset_patch(p) = pftcon%baset(ivt) + baset_latvary_intercept &
    - max(baset_latvary_intercept, baset_latvary_slope * abs(grc%latdeg(g)))
```

In addition, for ease of user understanding, I think it'd be preferable to replace `baset_latvary_slope` as a namelist parameter with `baset_latvary_maxlat`, which would allow them to specify the absolute latitude where `baset` is no longer affected. `baset_latvary_slope` would still be used in the above equation and calculated like so:
```fortran
baset_latvary_slope = baset_latvary_intercept / baset_latvary_maxlat
```

**Comment by ekluzek** [comment]
@samsrabin thanks for filing this. I think this is one of the last things that's fixed on the PPE branch that still needs to come to main development. I'll check later...

**Comment by ekluzek** [comment]
Hmm, interesting. Thanks for looking at that. I think there might be things that aren't on the PPE branch, but in sourcemods, so I'll check on that.

In any case this is certainly something to fix, so thanks for noticing. We've had things like this that are important to fix so you can really use those parameters.
