### ISSUE TITLE
Duplicate lines of code in BareGroundFluxesMod.F90

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#2129]
### Brief summary of bug

There are 3 duplicate lines of code in BareGroundFluxesMod.F90

### General bug information

Lines 302-304 are duplicated in lines 309-311

`302          z0mv(p)   = 0._r8`
`303          z0hv(p)   = 0._r8`
`304          z0qv(p)   = 0._r8`
`305          dlrad(p)  = 0._r8`
`306          ulrad(p)  = 0._r8`
`307          dhsdt_canopy(p) = 0._r8`
`308          eflx_sh_stem(p) = 0._r8`
`309          z0mv(p)   = 0._r8`
`310          z0hv(p)   = 0._r8`
`311          z0qv(p)   = 0._r8`

**CTSM version you are using:** [output of `git describe`]
ctsm5.1.dev139

**Does this bug cause significantly incorrect results in the model's science?** No

**Comment by wwieder** [comment]
Address in #1861
