### ISSUE TITLE
Misc. behind-the-scenes doc improvements

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2135]
As discussed in #2093, some changes are needed to the .rst files in order to get them to render correctly in VSCode. These changes seem to have no impact on the generated HTML, at least as rendered in the browser.
- [ ] Delete `imgmath` lines from `doc/source/conf.py`.
- [ ] Delete all instances of `\kern-\nulldelimiterspace`.

There are also some changes that would improve searchability within the docs code:
- [ ] Remove all manual line breaks; each paragraph should be its own line.
- [ ] Convert all "smart/curly" punctuation (`’ “`) to "straight" versions (`' "`).

**Comment by samsrabin** [comment]
To elaborate on the removal of manual line breaks:

The idea is mainly to enhance searchability. If I want to edit [equation 2.26.2](https://escomp.github.io/ctsm-docs/versions/release-clm5.0/html/tech_note/Crop_Irrigation/CLM50_Tech_Note_Crop_Irrigation.html#equation-25-2), I can't search the .rst files for the equation number, because those are generated in the HTML. I might instead search for some text near it—maybe, "are the 20-year running mean growing degree-days". That doesn't give me any hits because there's a line break in the .rst file:

```rst
where :math:`{GDD}_{0}`, :math:`{GDD}_{8}`, and :math:`{GDD}_{10}` are the 20-year running mean growing
degree-days tracked from April through September (NH) over 0\ :sup:`o`\C, 8\ :sup:`o`\C, and
```

Line length limits in .rst files also lead to the problem where you might need to add text to a line near the top of a paragraph, but then that line becomes too long, so you then need to edit all the subsequent lines in the paragraph. In addition to being a pain in the butt, this makes it hard to figure out from git diffs what text was actually added.

Some RestructuredText [style](https://www.john-cd.com/cheatsheets/Markup_and_Documentation/reStructuredText) [guides](https://documentation-style-guide-sphinx.readthedocs.io/en/latest/style-guide.html) recommend line length limits, sometimes even implying there's [a maximum](https://escomp.github.io/ctsm-docs/versions/release-clm5.0/html/tech_note/Introduction/CLM50_Tech_Note_Introduction.html#clm5-0). If there is one, though, it's more than 2,144 characters, which is the longest line we have (second paragraph [here](https://escomp.github.io/ctsm-docs/versions/release-clm5.0/html/tech_note/Introduction/CLM50_Tech_Note_Introduction.html#clm5-0)).

There are lots of reasons for line length limits when it comes to code, but text is a different beast. In code, searchability is less of an issue. It also doesn't suffer so much from the "edits made this line too long, so now I have to edit all the subsequent lines" problem. This is helped by the ability to break code up into different lines semantically, which isn't possible with text, where the fundamental semantic units (clauses) can be extremely long.

**Comment by billsacks** [comment]
Thanks @samsrabin - both for taking this on and for your great description of the rationale. I am definitely in favor of removing manual line breaks. I have a feeling that the history of them is that they can be better than the alternative if your editor doesn't have good support for soft wrapping on word boundaries, but as long as most people are now using editors with good support for that, then I agree that it makes sense to only have  manual line breaks at paragraph boundaries.

**Comment by wwieder** [comment]
I like having text render correctly.

**Comment by samsrabin** [comment]
@wwieder Not hard at all. Later today, I'll submit one PR with the changes described here and another with some minor fixes.
