### ISSUE TITLE
Script to create surface datasets for PLUMBER2 sites

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2138]
As part of #2137 surface datasets need to be created for the PLUMBER2 sites. @olyson has already created surface datasets for these sites, and they can be checked into CESM inputdata and pointed to in the user-mod-directories. He also has a script that created these datasets, and that should be checked into CTSM as well. We also want to transition that script to python and have it based on the NEON version of the same. But, that will be an upcoming development.

Definition of Done:
- [ ] Move the new surface datasets created here `/glade/u/home/wwieder/CTSM/tools/site_and_regional/subset_data_single_point` to under CESM inputdata `lnd/clm2/surfdata_map/PLUMBER2` (similar to the NEON sites)
- [ ] Create a list of the current PLUMBER2 surface datasets (with a lnd/clm2/surfdata_map... relative path)
- [ ] rimport the current PLUMBER2 datasets
- [ ] Checkin the current script into CTSM
- [x] Develop a python script that can do this similar to the NEON surf wrapper script
- [x] Modify canopy heights on surface datasets from PLUMBER2 (currently on 'older' plumber2 surface data).
- [ ] CLM_USRDAT_NAME needs to accept PLUMBER2 (not sure what xml changes needed here)?
- [ ] List of accepted PLUMBER2SITES added for env_run.

**Comment by olyson** [comment]
The script that created these surface datasets (which I believe is in python) is held by @swensosc .  Sean, can you point us to that script?
The current surface datasets created from this script (16 and 78 pft versions) are in:
/glade/work/oleson/PLUMBER2/input_files/$SITE
In those directories, the domain files (which I understand are no longer needed in NUOPC) and the lai streams files can be found.

**Comment by TeaganKing** [comment]
I'm going through the PLUMBER-related issues; I think this one may be complete, unless @olyson or @wwieder wanted to add anything else?

**Comment by wwieder** [comment]
No, just that this needs to be redone once 5.3 surface datasets are generated in #2500, but it's already on @slevis-lmwg's radar.

**Comment by TeaganKing** [comment]
Ok, great, thanks Will. This was wrapped up in #2485 and 5.3 datasets should be generated but an issue for this is described in the comment above. Closing this issue.
