### ISSUE TITLE
PE layout for hcru_hcru needs to be increased so that it can run

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#216]
The following test dies in CLM initialization. ERP_D_Ld5.hcru_hcru.I2000Clm50BgcCruGs.cheyenne_gnu By default the PE layout for this is one node 36x1, and it will run successfully at 720x1. I assume this means it's running out of memory? The log files don't give a clear reason, but it obviously needs more resources.

**Comment by ekluzek** [comment]
This is still an issue as there is no PE layout for hcru_hcru in config_pes.xml.

**Comment by billsacks** [comment]
It looks like this has been fixed.
