### ISSUE TITLE
Don't create/test most SSP landuse timeseries datasets for CTSM5.2

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2178]
Since the future scenarios will be replaced with CMIP7 it doesn't seem important to make all of the CMIP6 scenarios with CTSM5.2. However, what is important is to make sure the process works, and to make datasets if needed for use by a group. The SSP scenarios are also important to have in order to have data to run transient simulations that go up to present-day, rather than being restricted to 2015, because of out historical landuse data currently ends there.

@lawrencepj1 and I talked about this a bit yesterday, and he also recommended that SSP2-4.5 be used as the one SSP scenario that we create datasets for, because it's a nice "middle of the road" scenario.

We currently test 4 of the SSP's at f10 resolution and one grid for CAM ne0ARCTICGRISne30x8_ne0ARCTICGRISne30x8_mt12, for SSP5-8.5. So for CTSM5.2 I suggest we only make SSP2-4.5 datasets and only test a couple resolutions for these. Although we'd also use the SSP2-4.5 landuse.timeseries for some resolutions so we don't make both a SSP scenario and a historical, with the SSP scenario covering 1850-2100.

@slevis-lmwg any thoughts on this?

**Comment by slevis-lmwg** [comment]
I'm comfortable with this decision. Do we know the timeline for generating cmip7 timeseries, yet?

**Comment by dlawrenncar** [comment]
The timeline is not imminent, especially for the projection period.
Historical timeseries might come sometime over the next year.

**Comment by lawrencepj1** [comment]
Thanks everyone. Yes my thought was that we have the raw data and the tools available so if requested other time series can be generated at the resolution required on a needs basis. @ekluzek Yes exactly SSP2-4.5 is a middle of the road land use that tracks the observed changes over the 2015-2023 period so for extending the historical this is useful as well.

**Comment by ekluzek** [comment]
In our discussion this morning we decided to do ALL the SSP's for the fv0.9x1.25 resolution, but only SSP2-4.5 for the others that we want to have a transient version for.

@slevis-lmwg and I also met with a bunch of CAM and CSEG people to come up with the list needed for CAM. Here is the updated table for that...

https://docs.google.com/spreadsheets/d/1Osq56e423CF107zhoNQ0VS7-iH_JXLF9AtCvBdXyfJ4

**Comment by slevis-lmwg** [comment]
Thanks, @ekluzek.
In the meeting with CAM/CSEG people, I thought I heard someone say that the ne30 grids would go away soon. So I was surprised when they recommended supporting almost all (3 of the 4) ne30 grids. I noticed you asked them to confirm, and they confirmed that they wanted us to support 3 of the 4 ne30 grids.

**Comment by ekluzek** [comment]
@slevis-lmwg it's definitively not ne30 in general. That is the workhorse resolution. However, looking at the list I think what you are referring to is ne30np4.pg4 -- that specific one isn't one they want to support going forward. But it's a specific SE grid/physics grid combination for ne30. There's a bunch of complexity in these SE grid/physics grid combinations that they went over roughly, but for CTSM it just means a different grid that we need to have surface datasets for.
