### ISSUE TITLE
Add PLUMBER2SITE list to config_component.xml

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2186]
Add the list of PLUMBER2SITE's to the config_component.xml. And also bring in the CDEPS tag around this from:

https://github.com/ESCOMP/CDEPS/issues/248

**Comment by TeaganKing** [comment]
FYI I've made changes to address this issue within the updates that I'm making to add plumber capabilities... I'll tag this once I have the PR open but just wanted to note the progress in order to avoid any possible duplication.

**Comment by TeaganKing** [comment]
This was resolved by #2485
