### ISSUE TITLE
Too many references to /glade/p/ in testmods_dirs/clm

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CTSM#2196]
### Brief summary of bug
Many of the ctsm test mods make reference to /glade/p.   This won't work on systems outside of NCAR and results in a lot of forum posts and other communications from users outside NCAR who want to run and confirm tests.

### General bug information
In many cases this is completely unnessasary as the data is in inputdata.

**CTSM version you are using:** ongoing problem, latest version

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No] No

**Configurations affected:** [Fill this in if known.]

### Details of bug
 grep -r glade
USUMB_mct/user_nl_clm:! ./PTCLMmkdata --cesm_root ../../../.. -s US-UMB -d /glade/p/cesm/cseg/inputdata --mydatadir=/glade/p/cesm/cseg/inputdata/lnd/clm2/PTCLMmydatafiles.c171024 
USUMB_mct/user_nl_clm: fsurdat = '/glade/p/cesm/cseg/inputdata/lnd/clm2/PTCLMmydatafiles.c171024/1x1pt_US-UMB/surfdata_1x1pt_US-UMB_16pfts_Irrig_CMIP6_simyr2000_c171024.nc'
USUMB_mct/shell_commands:# ./PTCLMmkdata --cesm_root ../../../.. -s US-UMB -d /glade/p/cesm/cseg/inputdata --mydatadir=/glade/p/cesm/cseg/inputdata/lnd/clm2/PTCLMmydatafiles.c171024 
USUMB_mct/shell_commands:./xmlchange ATM_DOMAIN_PATH=/glade/p/cesm/cseg/inputdata/lnd/clm2/PTCLMmydatafiles.c171024/1x1pt_US-UMB
USUMB_mct/shell_commands:./xmlchange LND_DOMAIN_PATH=/glade/p/cesm/cseg/inputdata/lnd/clm2/PTCLMmydatafiles.c171024/1x1pt_US-UMB
USUMB_mct/shell_commands:./xmlchange DIN_LOC_ROOT=/glade/p/cesm/cseg/inputdata
USUMB_mct/shell_commands:./xmlchange DIN_LOC_ROOT_CLMFORC=/glade/p/cesm/cseg/inputdata/lnd/clm2/PTCLMmydatafiles.c171024
smallville_dynurban_monthly/user_nl_clm:! /glade/p/cgd/tss/people/oleson/modify_surfdata/modify_smallville_with_dynurban.ncl
smallville_dynurban_monthly/user_nl_clm:! /glade/p/cesm/cseg/inputdata/lnd/clm2/surfdata_map/landuse.timeseries_1x1_smallvilleIA_hist_78pfts_simyr1850-1855_c160127.nc
smallville_dynurban_monthly/modify_smallville_with_dynurban.ncl: infile  = "/glade/p/cgd/tss/people/oleson/modify_surfdata/landuse.timeseries_1x1_smallvilleIA_hist_78pfts_simyr1850-1855_c160127.nc"
smallville_dynurban_monthly/modify_smallville_with_dynurban.ncl: outfile = "/glade/p/cgd/tss/people/oleson/modify_surfdata/landuse.timeseries_1x1_smallvilleIA_hist_78pfts_simyr1850-1855_dynUrban_c220223.nc" 
smallville_dynurban_monthly/modify_smallville_with_dynurban.ncl: outf@history = "This file was created with the following NCL script: /glade/p/cgd/tss/people/oleson/modify_surfdata/modify_smallville_with_dynurban.ncl.  The file used as a template is: /glade/p/cesm/cseg/inputdata/lnd/clm2/surfdata_map/landuse.timeseries_1x1_smallvilleIA_hist_78pfts_simyr1850-1855_c160127.nc.  Key points are that urban area starts as 0, increases after the first year, then decreases after the second year.  Medium density urban is set to zero to test the memory-saving behavior of PCT_URBAN_MAX.  PCT_CROP is also changed so that PCT_URBAN + PCT_CROP <= 100. (Here, PCT_CROP increases and decreases at the same time as PCT_URBAN in order to exercise the simultaneous increase or decrease of two landunits, but that isn't a critical part of this test.). Note that the use of this file means that this testmod can only be used with the 1x1_smallvilleIA grid."
DA_multidrv/user_nl_clm_0001: finidat = '/glade/p/cisl/dares/RDA_strawman/CESM_ensembles/CLM/CLM5BGC-Crop/ctsm_2001-01-01-00000/clm5_f09_spinup80.clm2_0001.r.2001-01-01-00000.nc'
DA_multidrv/user_nl_clm_0002: finidat = '/glade/p/cisl/dares/RDA_strawman/CESM_ensembles/CLM/CLM5BGC-Crop/ctsm_2001-01-01-00000/clm5_f09_spinup80.clm2_0002.r.2001-01-01-00000.nc'
ciso_cwd_hr/user_nl_clm:paramfile = '/glade/p/cesm/cseg/inputdata/lnd/clm2/paramdata/ctsm51_ciso_cwd_hr_params.c211112.nc'
cplhist/shell_commands:./xmlchange DATM_CPLHIST_DIR=/glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.cdeps_datm.CPLHIST_cam6ctsm51_cesm23a12c_ne30pg3g17_1850
FatesFireLightningPopDens/README:where {...} = /fs/cgd/data0/slevis on izumi and /glade/work/slevis on cheyenne.
USUMB_nuopc/user_nl_clm:! ./PTCLMmkdata --cesm_root ../../../.. -s US-UMB -d /glade/p/cesm/cseg/inputdata --mydatadir=/glade/p/cesm/cseg/inputdata/lnd/clm2/PTCLMmydatafiles.c171024 
USUMB_nuopc/user_nl_clm: fsurdat = '/glade/p/cesm/cseg/inputdata/lnd/clm2/PTCLMmydatafiles.c171024/1x1pt_US-UMB/surfdata_1x1pt_US-UMB_16pfts_Irrig_CMIP6_simyr2000_c171024.nc'
USUMB_nuopc/shell_commands:# ./PTCLMmkdata --cesm_root ../../../.. -s US-UMB -d /glade/p/cesm/cseg/inputdata --mydatadir=/glade/p/cesm/cseg/inputdata/lnd/clm2/PTCLMmydatafiles.c171024 
USUMB_nuopc/shell_commands:./xmlchange DIN_LOC_ROOT=/glade/p/cesm/cseg/inputdata
USUMB_nuopc/shell_commands:./xmlchange DIN_LOC_ROOT_CLMFORC=/glade/p/cesm/cseg/inputdata/lnd/clm2/PTCLMmydatafiles.c171024
collapse_pfts_78_to_16_decStart_f10/README:/glade/work/slevis/git/collapse_pfts/bld/namelist_files/namelist_defaults_clm4_5.xml
collapse_pfts_78_to_16_decStart_f10/README:fsurdat = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_map/surfdata_10x15_78pfts_CMIP6_simyr1850_c170824.nc'
collapse_pfts_78_to_16_decStart_f10/README:flanduse_timeseries = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_map/landuse.timeseries_10x15_hist_78pfts_CMIP6_simyr1850-2015_c170824.nc'
collapse_pfts_78_to_16_decStart_f10/user_nl_clm:fsurdat = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_map/surfdata_10x15_78pfts_CMIP6_simyr1850_c170824.nc'
collapse_pfts_78_to_16_decStart_f10/user_nl_clm:flanduse_timeseries = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_map/landuse.timeseries_10x15_hist_78pfts_CMIP6_simyr1850-2015_c170824.nc'

[Fill in details here.]

### Important details of your setup / configuration so we can reproduce the bug

[Specify anything relevant: the compset, resolution, machine, compiler, any xml or namelist changes, etc. You don't have to repeat anything that you have already noted above.]

### Important output or errors that show the problem

[Fill this in with anything relevant that you haven't already noted; if there is nothing to add, delete this section.]

**Comment by ekluzek** [comment]
There's also some references under the directories: bld, python, and the file tools/site_and_regional/default_data.cfg.

There's also the lilac and contrib directory (see #2277) that needs to be dealt with somehow. And the doc directory needs to be handled as well, but can be done with (#2223).

Things that we don't need to update as they are going away are: tools/mksurfdata_map and tools/mkmapdata

**Comment by ekluzek** [comment]
This also applies to the release-cesm2.2 branch and a little bit to release-clm5.0.
