### ISSUE TITLE
For new standalone organization, need to generalize paths for tools and testing

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#220]
With the new standalone organization, where clm is no longer under `components/clm`, `build-namelist` unit tests currently fail. I haven't tried tools testing (or building the tools manually for that matter), but I strongly suspect they will fail similarly.

Many (and maybe all) problems with assumed paths can be found by searching for uses of:

1. `../cime`

2. `CLM_ROOT` in the `test` directory

Off-hand, I'm imagining that we could have a utility in CLM to find the root level by continually looking up a level until either (a) we find a directory containing cime (in which case this directory is the root level), or (b) we reach '/' (in which case we error out). That should be easy enough to write, though the harder part is making sure we have found all the places where it needs to be applied.

**Comment by billsacks** [comment]
@ekluzek is this fixed now?

**Comment by ekluzek** [comment]
I'm going to call this done. The tools and such all work now. And I'm pretty sure they work with both a CESM checkout and a CTSM checkout. There isn't a nice utility that figures this out in one place, but this is taken care of in the tools that need to figure out the path.
