### ISSUE TITLE
Derecho transition: Move stuff from /glade/p

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2200]
Originally part of #1995 from @slevis-lmwg:
> /glade/p will be discontinued, so move stuff from there to Derecho replacement. A lot of this is CESM-wide stuff like inputdata, though we may have some CTSM-specific stuff, such as /glade/p/cgd/tss.

@ekluzek made this [google document](https://docs.google.com/document/d/1vL2haCsuNGXGPNCBOf-rdV-4M4-bNVQs38uBi5t8eFg/edit?usp=sharing).

Also, see some updates there:
- [Sam L. 2023-08-10](https://github.com/ESCOMP/CTSM/issues/1995#issuecomment-1673664640)
- [Will 2023-08-10](https://github.com/ESCOMP/CTSM/issues/1995#issuecomment-1673668882)
- [Erik 2023-08-10](https://github.com/ESCOMP/CTSM/issues/1995#issuecomment-1673697410)

**Comment by ekluzek** [comment]
We need to move:

tss
lmwg
lmwg_dev
sdwg_dev

And datm forcing directories.

**Comment by ekluzek** [comment]
I think for the datm forcing directories they just need to be moved over to:

$DIN_LOC_ROOT/atm/datm7

which should have enough room now.

**Comment by swensosc** [comment]
@erik can you delete this directory, and I will copy over the newer nldas
data in its place?

/glade/campaign/cesm/cesmdata/cseg/inputdata/atm/datm7/NLDAS/

**Comment by wwieder** [comment]
@swensosc it looks like Tony Craig is the owner of that file.
`/glade/campaign/cesm/cesmdata/cseg/inputdata/atm/datm7/NLDAS/`

Can you coordinate with @ekluzek to make sure we have a single copy of the most up to date nldas data?

**Comment by ekluzek** [comment]
One part of this is Keith Lindsay did the following move for us

``` text
The contents of
/glade/p/cesm/bgcwg_dev/forcing/b.e20.B1850.f09_g17.pi_control.all.221.cplhist/cpl/hist.mon
are now at
/glade/campaign/cesm/development/bgcwg/forcing/b.e20.B1850.f09_g17.pi_control.all.221.cplhist/cpl/hist.mon
```

We need to update the code accordingly.
