### ISSUE TITLE
Error in view factor for urban building energy model

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#2208]
### Brief summary of bug

Linying Wang and Dan Li (Boston University) reported problems with energy balance of longwave radiation in the building energy model (BEM).
This is due to an error in one of the view factors (vf_fw - view factor for floor to wall).  There is an energy balance check related to this, but it is also formulated incorrectly and thus balances for the wrong reason.

PR with fix to follow.

### General bug information

**CTSM version you are using:** ctsm5.1.dev142-2-g1b3d377bf

**Does this bug cause significantly incorrect results in the model's science?** Larger than roundoff but not urban climate changing.  

Standard diagnostics that demonstrate very small changes in gridcell averages of important variables are here:

https://webext.cgd.ucar.edu/I2000/ctsm51_ctsm51d75_1deg_GSWP3V1_CON_VF_2000/lnd/ctsm51_ctsm51d75_1deg_GSWP3V1_CON_VF_2000.1991_2010-ctsm51_ctsm51d75_1deg_GSWP3V1_CON_2000.1991_2010/setsIndex.html

An assessment of impacts on anthropogenic heat flux and urban air temperature can be found here:

[CTSM51d115_BUILDENERGY_VF_Analysis.xlsx](https://github.com/ESCOMP/CTSM/files/13034700/CTSM51d115_BUILDENERGY_VF_Analysis.xlsx)

**Configurations affected:** CLM5 and later versions.
### Details of bug

In UrbBuildTempOleson2015Mod.F90 we have:
vf_fw(l) = vf_wf(l) / building_hwr(l)
where vf_fw in terms of per unit wall area.
This should be 
vf_fw(l) = vf_wf(l)
where now vf_fw (and vf_wf) are in terms of per unit floor area.
Longwave radiation inside the building is solved in terms of per unit floor area.

The energy balance check for building longwave radiation is:
qrd_building(l) = qrd_roof(l) + building_hwr(l)*(qrd_sunw(l) + qrd_shdw(l)) + qrd_floor(l)

but should be:
qrd_building(l) = qrd_roof(l) + qrd_sunw(l) + qrd_shdw(l) + qrd_floor(l)

such that roof, walls, and floor area all in terms of per unit floor (roof) area.

**Comment by ekluzek** [comment]
This was resolved in #2212
