### ISSUE TITLE
CLM45 FATES IC files can't be used for CLM50 and vice-versa

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#221]
This is mostly because of #211, but FATES Initial condition files run with CLM45 can't be used for CLM50 and vice-versa because of the number of snow layers.

So the following tests fail...

SMS_D_Ld5.f45_f45_mg37.I2000Clm50Fates.cheyenne_intel.clm-Fates         
SMS_D_Lm6.f45_f45_mg37.I2000Clm50Fates.cheyenne_intel.clm-Fates         
SMS_D_Lm6_P144x1.f45_f45_mg37.I2000Clm50Fates.cheyenne_intel.clm-Fates

It fails with an error that looks like:

```
 Reading initial conditions from 
 /glade/p/cesmdata/cseg/inputdata/lnd/clm2/initdata_map/clmi.I2000Clm45Fates.012
 1-01-01.4x5_mgx3v7_simyr2000_c180122.nc
 (GETFIL): attempting to find local file 
 clmi.I2000Clm45Fates.0121-01-01.4x5_mgx3v7_simyr2000_c180122.nc
 (GETFIL): using 
 /glade/p/cesmdata/cseg/inputdata/lnd/clm2/initdata_map/clmi.I2000Clm45Fates.012
 1-01-01.4x5_mgx3v7_simyr2000_c180122.nc
 Reading restart dataset
 check_dim ERROR: mismatch of input dimension            5  with expected value 
          12  for variable levsno
You can deal with this mismatch by rerunning with use_init_interp = .true. in user_nl_clm
 ERROR: 
 ERROR in /glade/p/work/erik/clm_fates/components/clm/src/main/ncdio_pio.F90.in 
 at line 368
```

Although it says, you can use interpolation, you can't because this is FATES (#211).

**Comment by billsacks** [comment]
@ekluzek @rgknox - Would a reasonable workaround for this be to have separate Fates initial conditions files for clm45 vs clm50 - at least until we're able to run init_interp on Fates initial conditions files?

**Comment by rgknox** [comment]
It is ok with me if you guys want to just do coldstarts (finidat='') for FATES testing when integrating non-fates developments (ie your standard integration suite).

For fates developments on NGEET/fates repository, I am still using NGEET/fates-clm as the driver.  In this situation, I am using cold-starts for CLM50, and generating the finidats for CLM45 (via the scripts I shared), but I'm not going to keep this as a long term solution.  

I think sometime in the next two weeks or so, we will be submitting a PR on NCAR/fates to bring it in-line with our development repo.  At that point, we can re-evaluate, and probably generate either one set, or two sets of finidats with a spun up forest.

**Comment by billsacks** [comment]
@ekluzek @rgknox can we close this as a wontfix?

**Comment by ekluzek** [comment]
@billsacks I think that's OK. You should make the aux_clm tests cold start. And for the next fates update, we might want to bring in more IC files for the fates test list.
