### ISSUE TITLE
Restart subroutines for C13 and C14 totvegc and totvegc_col are never called

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#2216]
### Brief summary of bug

The restarts for totvegc_13, totvegc_col_13, totvegc_14, totvegc_col_14 are never called because they are contained within a carbon_type = 'c12' if statement, in CNVegCarbonStateType.F90.

### General bug information

**CTSM version you are using:** ctsm5.1.dev145

**Does this bug cause significantly incorrect results in the model's science?** I don't know yet

**Configurations affected:** All with C13 and C14

### Details of bug

At line 1172:

`if (carbon_type == 'c12') then`

the end if for this appears to be at line 1584.
In between, there are a couple of ifs for c13 and c14 at lines 1353 and 1388, respectively.

### Important details of your setup / configuration so we can reproduce the bug

ERP_D_Ld10_P36x2.f10_f10_mg37.IHistClm51BgcCrop.cheyenne_intel.clm-ciso_decStart

Note that this test has carbon isotopes on but is starting from an initial file without isotopes on it.

### Important output or errors that show the problem

I would expect the test above to have a message in the log file about not finding totvegc_col_13, similar to this one for leafc_13:

 Skipping     : leafc_13 variable is NOT on input file

**Comment by slevis-lmwg** [comment]
Closing due to the merge of #2229 as a result of merging #2253.
