### ISSUE TITLE
Tags for building CTSM library on Derecho [WRF-CTSM]

### ISSUE THREAD

**Issue by negin513** [ESCOMP/CTSM#2217]
Hello, 

I was wondering if the in what CTSM tags, `build_ctsm` script works on Derecho. 

@irismuz is interested in running WRF-CTSM on Derecho and she was wondering which tag she should use to build the ctsm library on Derecho. 

This is relevant to #2147.

**Comment by wwieder** [comment]
Should be solved wqith #1995

**Comment by samsrabin** [comment]
For now, it should be possible to build CTSM on Derecho by manually updating `Externals.cfg` to match the version on the `CESM3_dev` branch: https://github.com/ESCOMP/CTSM/blob/CESM3_dev/Externals.cfg
