### ISSUE TITLE
CTSM5.2 branch dies weirdly when clm5.0/ctsm5.1 datasets are used -- die with an error

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2218]
### Brief summary of bug

When ctsm5.1/clm5.0 surface datasets are used in the ctsm5.2 branch, the model blows up and dies in a weird way, that's hard to figure out. We need to detect if this happens and abort with a graceful error.

### General bug information

This was discovered on the CESM3_dev branch
**CTSM version you are using:** ctsm5.1.dev143-350-gda5beb800

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:**

 cttsm5.2 branch with clm5.0/ctsm5.1 surface datasets.

### Details of bug

This was talked about in this issue, with some examples of the error. The example shows what happens when run in debug mode, but it also has problems in productive mode which is harder to figure out.

**Comment by ekluzek** [comment]
A couple ideas @slevis-lmwg and I had discussing this.

One simple idea is when PCT_OCEAN is checked for it gives a message about this changing with mksurfdata_esmf in ctsm5.2 versions and following.

Another set of fields that are new are: mapunits, ORGC, BULK, CFRAG, PHAQ. So those could be queried. But, they also might not be read in yet.

The dimension for nlevurb changes as well, but the urban single point sites still have the old dimension size, so that's not a robust way to do it.

Another idea is to have a version string as a global attribute on the files to check for compatibility. If the string doesn't match what's expected then it dies with an error. This can then be updated anytime we have something that is NOT backward compatible.

**Comment by slevis-lmwg** [comment]
Tested the behavior by running the latest ctsm5.2 (git describe: `ctsm5.2.mksrf.19_ctsm5.1.dev125`)
with this ctsm5.1 file:
fsurdat = '/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/surfdata_map/release-clm5.0.18/surfdata_1.9x2.5_hist_78pfts_CMIP6_simyr1850_c190304.nc`
and with this ctsm5.2 file before we introduced PCT_OCEAN:
fsurdat = '/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/surfdata_esmf/ctsm5.2.0/surfdata_1.9x2.5_hist_78pfts_CMIP6_2000_c230517.nc`

Both stopped with this error:
```
 check_var: variable xc is not on dataset
 surfrd_get_data lon_var = LONGXY lat_var =LATIXY
 ncd_inqvid: variable PCT_OCEAN is not on dataset
 ENDRUN:
 ERROR:  ERROR: PCT_OCEAN NOT on surfdata fileERROR in surfrdMod.F90 at line 419
```

I will make the error more helpful by adding "PCT_OCEAN required when running ctsm5.2 or newer"

**Comment by slevis-lmwg** [comment]
This is a simple one-line edit to an error message, so I will commit and push to existing PR #2318.
