### ISSUE TITLE
Fixing Negative Ice Fluxes from Ocean to Glacier

### ISSUE THREAD

**Issue by Katetc** [ESCOMP/CTSM#2222]
The default method of running CISM in CESM is "No-Evolve" or non-active ice sheet. Because the ice sheet can't grow or change in this configuration, all water fluxes through the ice sheet must be balanced. As long as CISM is running in any form, CTSM will calculate and downscale surface mass balance over the ice sheet(s), including melt fluxes in the summer and high snow amounts in the winter. In order to balance summer time melt fluxes from the ice sheet, CTSM will pull water from the ocean (a negative ice flux) to counter ice sheet melting in the summer. 

A more realistic method for handling this need for balance would be to store the excess snow that is sent as run-off in the winter (due to the inactive ice sheet not being able to grow) in a water reservoir that can be accessed in the summer months to balance glacier melt. Our plan is to have excess snow capping over Greenland added to a "snow reservoir" that can be dealt out to balance melt in the summer months and decrease the need for water from the ocean.

I have started implementation of this and we would love to see it go into the CTSM version for CESM3.

**Comment by ekluzek** [comment]
@Katetc thanks for filing this. Is this related to #423?

**Comment by ekluzek** [comment]
@Katetc is this being worked on? Is there still desire for this for the CESM3 release?

**Comment by ekluzek** [comment]
In discussion with @Katetc the plan now is to move this functionality out of CTSM and into a Data Glacier model dglc into CDEPS.

**Comment by ekluzek** [comment]
We are going to do #1136 rather than this, so closing this one.
