### ISSUE TITLE
COMPILER ERROR problem in cropcalStreamMod

### ISSUE THREAD

**Issue by adrifoster** [ESCOMP/CTSM#2232]
### Brief summary of bug

I am having an annoying compiler error running on my personal computer (Mac, with compiling with GNU 13.2.0).

The compiler error seems to originate somewhere in the cropcalStreamMod:

```
f951: internal compiler error: Segmentation fault: 11
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
gmake: *** [/Users/afoster/Documents/ncar/NEON/NEON_runs/cases/BONA_run_test/Tools/Makefile:975: cropcalStreamMod.o] Error 1
gmake: *** Waiting for unfinished jobs....
```
### General bug information

I tested `ctsm5.1.dev146` and it compiled, whereas 147 and above do not. 

At @billsacks's suggestion I am going to try changing the `use ESMF` statement to have `only`s for what the module specifically needs, as this *could* be the problem. Otherwise I will need to start commenting out blocks of the code to figure out what the offending lines could be.

**CTSM version you are using:** `ctsm5.1.dev147` and above

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** Using latest (or above 12.2) gnu fortran to compile

**Comment by billsacks** [comment]
As @adrifoster alluded to, I compiled successfully on my mac with gfortran 12.2, so this appears to be a regression in recent versions of gfortran.

**Comment by adrifoster** [comment]
Unfortunately the ESMF trick didn't work so time to hack away.... @samsrabin if you have any ideas let me know!

**Comment by adrifoster** [comment]
okay update, thanks @billsacks:

offending lines are between [399 and 430](https://github.com/ESCOMP/CTSM/blob/914cb27519ced3478a0657af36af47e42101ba3f/src/cpl/share_esmf/cropcalStreamMod.F90#L399)

Potentially due to some complex "any" expressions...

**Comment by samsrabin** [comment]
The `any()` statements could be refactored away, with the checks happening [here](https://github.com/ESCOMP/CTSM/blob/914cb27519ced3478a0657af36af47e42101ba3f/src/cpl/share_esmf/cropcalStreamMod.F90#L390-L392) instead. I did the check outside that loop using `any()` statements to vectorize the check, but I don't think that's performance-critical.

**Comment by adrifoster** [comment]
okay thanks again to @billsacks, but the fix is to use `begp:endp` for the associated `starts` and `ends` arrays...

PR forthcoming!

**Comment by adrifoster** [comment]
> The `any()` statements could be refactored away, with the checks happening [here](https://github.com/ESCOMP/CTSM/blob/914cb27519ced3478a0657af36af47e42101ba3f/src/cpl/share_esmf/cropcalStreamMod.F90#L390-L392) instead. I did the check outside that loop using `any()` statements to vectorize the check, but I don't think that's performance-critical.

ah okay, if you'd like to change it let me know, but this fix works!
