### ISSUE TITLE
Get ILAMB working on Casper or Derecho

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2242]
@slevis-lmwg tested this on derecho and casper:
```
cd /glade/p/cesm/lmwg/diag/ILAMB/CODE/ilamb/
module load conda
conda env create -f ilamb-sysmpi.yml
```
As of now I get the same result on derecho and casper as on cheyenne, i.e. the process gets stuck spinning in the third line below:
```
Retrieving notices: ...working... done
Collecting package metadata (repodata.json): done
Solving environment: /
```
If nothing works, @wwieder suggested getting on a call with CISL (help@ucar.edu).

**Comment by olyson** [comment]
I have this running on casper from its new location at /glade/campaign/cesm/community/lmwg/diag/ILAMB.
