### ISSUE TITLE
Move SNICAR parameter to parameter file

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#2247]
In [this thread](https://github.com/ESCOMP/CTSM/pull/1861#issuecomment-1804576651), @cenlinhe recommended moving the following parameters to the CLM parameter file.
(1) C2_liq_Brun89 (wet aging coeff, **on parameter file**), 
(2) snw_rds_refrz (refrozne grain size, **on parameter file**), 
(3) fresh_snw_rds_max (max fresh snow grain size) [AerosolMod.F90](https://github.com/ESCOMP/CTSM/blob/dc164d54716eaeab23d7b692258a2e49b614c9c6/src/biogeophys/AerosolMod.F90#L30), 
(4) snw_rds_min (cold snow size), [AerosolMod.F90](https://github.com/ESCOMP/CTSM/blob/dc164d54716eaeab23d7b692258a2e49b614c9c6/src/biogeophys/AerosolMod.F90#L29)
(5) scvng_fct_mlt_bcphi, scvng_fct_mlt_bcpho, scvng_fct_mlt_dst1~4 [src/biogeophys/SnowHydrologyMod.F90](https://github.com/ESCOMP/CTSM/blob/dc164d54716eaeab23d7b692258a2e49b614c9c6/src/biogeophys/SnowHydrologyMod.F90#L123)

This isn't urgent, but could be helpful for subsequent OAAT parameter perturbation experiments as we look at tuning snow albedos.

**Comment by slevis-lmwg** [comment]
Linking another list that seems slightly different, but maybe refers to all the same params:
https://github.com/ESCOMP/CTSM/pull/1861#issuecomment-1815545764

**Comment by slevis-lmwg** [comment]
This parameter moved from the namelist to the params file. I have a feeling this means that I need to update the clm50 and clm45 params files, as well...
