### ISSUE TITLE
Units of gdp on surface datasets should be "k 1995US$ capita-1", not "unitless"

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#2252]
Reported by Junjie Yu at University of Manchester, the units on the gdp variable on the surface datasets are reported as "unitless", but should be "k 1995US$ capita-1" as noted in the code and the technical note.
I'm assigning @slevis-lmwg , because I assume this could be included in ctsm5.2 mksurfdata code.

**Comment by slevis-lmwg** [comment]
While I'm at it, I'm also correcting "agricultural fire peak month" from unitless to "month" so...
this requires that I change two lines in /tools/mksurfdata_esmf/src/mkfileMod.F90 as follows:
```
        call mkpio_def_spatial_var(pioid=pioid, varname='abm', xtype=PIO_INT, &
-            long_name='agricultural fire peak month', units='unitless')
+            long_name='agricultural fire peak month', units='month')

        call mkpio_def_spatial_var(pioid=pioid, varname='gdp', xtype=xtype, &
-            long_name='gdp', units='unitless')
+            long_name='gdp', units='k 1995US$ capita-1')
```
I will run a simple test and then merge without opening a PR for this, unless I hear an objection.

**Comment by slevis-lmwg** [comment]
Generated file with the new units here
/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/surfdata_0.9x1.25_hist_78pfts_CMIP6_1850_c231114.nc

**Comment by slevis-lmwg** [comment]
Merged and tagged: alpha-ctsm5.2.mksrf.18_ctsm5.1.dev123

I debated (with myself) and decided to make a new tag to lower the likelihood of accidentally dropping the change (maybe that's an unfounded concern). In any case, it's in, so I'm closing the issue.
