### ISSUE TITLE
Explicitly representing air-conditioning adoption in CESM

### ISSUE THREAD

**Issue by cathyxinchangli** [ESCOMP/CTSM#2254]
## Scientific Relevance
Improved representation of urban processes in Earth System Models (ESMs) is a pressing need for climate modeling and climate-driven urban energy studies. The CLMU in CESM is one of the few dynamic urban parameterizations in ESMs with a fully coupled, physics-based building energy model, and can simulate the anthropogenic heat flux reasonably well. However, a critical limitation remains, where urban air-conditioning (AC) adoption is modeled implicitly with the use of interior building thermostat setpoints. This undermines CESM’s fidelity in modeling urban climate and energy use, and limits its use in climate and energy risk assessments. 

In this project, we implement a new explicit-AC-adoption parameterization scheme in CLMU by adding an AC adoption rate parameter. This scheme separates building thermostat setpoint and AC adoption rate into independent parameters that can be tuned separately. In support of the new scheme, we develop a present-day, global, survey-based, and spatially explicit AC adoption rate dataset at country and sub-country level that is integrated within CESM, and can also be leveraged for other ESMs or global-scale models and analyses. The explicit-AC-adoption scheme and the AC adoption rate dataset significantly improve the accuracy of anthropogenic heat modeling due to AC in CESM. The new parameterization scheme makes it possible to evaluate the effects of changing AC adoption on global urban energy and climate using CESM. 

Details of the project is available in Li et al. (2023) (preprint; in review at _Journal of Advances in Modeling Earth Systems_).

## Plan of Implementation
The following tasks have been completed in the forked directory here: https://github.com/cathyxinchangli/CTSM/tree/explicit-hac-adoption, in branch `explicit_ac_adoption`. The code base is consistent with ctsm5.1.dev115 (master branch commit c155ccb).

**1. Code modification**

- [x] **Task 1: Derive a mathematical model for the explicit-AC-adoption scheme**
The model assumes an AC setpoint, "saturation setpoint", which replaces the previous building thermostat setpoints. The saturation AC energy flux is calculated based on the saturation setpoint. The actual AC energy flux is then scaled by the AC adoption rate, and the interior building temperature is updated based on energy balance. 

- [x] **Task 2: Modify the code to implement the explicit-AC-adoption scheme**
The code in CLMU is updated to implement the mathematical model derived in Task 1. This includes adding a new parameter, AC adoption rate (`p_ac`) for each urban density type, modifying the AC energy flux and building temperature calculations, and implementing a namelist variable, `urban_explicit_ac`, as a toggle/switch to control whether the explicit AC adoption scheme is used.

**2. Data curation and generation**

- [x] **Task 3: Collect present-day AC adoption rate data**
We collect present-day AC adoption rate data (roughly defined as between 2010 and 2020) from International Energy Agency (IEA), national surveys, scientific literature, and others (see Table S1 in Li et al., 2023). Some data are available as numbers of AC units per household, which are converted to AC adoption rates based on a linear model with saturation effect (two-segment piecewise linear fit) derived from countries/regions where data on both quantities are available. For Australia, China, and the U.S., we obtain data at sub-country level (state or province level) to better represent the heterogeneity in these countries spanning highly diverse climate zones.

- [x] **Task 4: Generate gridded data for each urban density type**
All data collected in Task 3 are residential sector data, so they are assigned to the Medium Density (MD) class which primarily represent residential areas. Tall Building Districts (TBD) are assumed to have saturated AC adoption, and High Density (HD) class is assigned the simple average of the AC adoption rates from TBD and MD classes. We perform a grid-cell-based nearest neighbor gap filling to obtain a complete global land coverage for CESM simulations. 

- [x] **Task 5: Update AC thermostat setpoints to saturation setpoints**
We update the AC thermostat setpoints (`tbuildmax_[TBD/HD/MD]`) of all urban density types in all grid cells to 300 K, the lowest AC setpoint in the original surface data, to approximate the saturation behavior in the model. This setpoint was applied in the original scheme to all three density classes in the southeast U.S., a region with one of the highest, and near-saturated AC adoption rates in the world (88% - 96% for MD). 
Both AC adoption rate and AC thermostat setpoints data are added to the urban time varying input data file (currently in my personal directory on Cheyenne) and supplied to the model using the namelist variable `stream_fldfilename_urbantv`. Following the assumption made for AC thermostat setpoints in the original dataset, AC adoption rates for all urban density types globally are assumed to be zero between 1849 - 1949 and 2102 - 2106, and kept constant to the present-day data between 1950 and 2101 (see Future Work below).

**3. Model tests**

- [x] **Task 6: Validate model performance with land-only simulations using the new scheme and the new dataset**
We run land-only simulations at 0.9 by 1.25 degree resolution for 2005 - 2014. The new explicit-AC-adoption parameterization and the AC adoption rate dataset improve the performance of AC energy flux simulation both in magnitude of anthropogenic heat flux (AHF) due to AC and in spatial variability, when validated with published AHF datasets.

## Future work
The current dataset contains present-day AC adoption rates that are kept constant between 1950 and 2101. Future AC adoption rate projections consistent with SSP-RCP scenarios can be made utilizing empirical models of AC adoption rate as a function of income and climate (temperature or cooling degree-days) available in the literature.  

## Additional Notes
The explicit-AC-adoption scheme is compatible with the dynamic urban scheme (#1445).
The code also includes the bug fix for issue #2208, as in pull #2212.

## Collaborators
Keer Zhang (@keerzhang1), Bowen Fang (@fang-bowen). Advisors: Dr. Lei Zhao (@face2sea), Dr. Keith Oleson (@olyson).

## References
Xinchang Li, Lei Zhao, Keith W Oleson, et al. Enhancing Urban Climate-Energy Modeling in the Community Earth System Model (CESM) through Explicit Representation of Urban Air-conditioning Adoption. _ESS Open Archive_. November 08, 2023.
DOI: [10.22541/essoar.169945607.70663662/v1](https://doi.org/10.22541/essoar.169945607.70663662/v1)

**Comment by olyson** [comment]
Thanks @cathyxinchangli !  I think the first step is for me to review the code in more detail than I have thus far.  In particular, we'll want to determine if we want to update this to the latest tag on main all at once, or do it in parts to avoid conflicts.

**Comment by cathyxinchangli** [comment]
Sounds good, thank you @olyson! Please let me know if you need any further information from me.
