### ISSUE TITLE
release-cesm2.2 tags needed for Derecho support for the upcoming CESM2.2.2

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2257]
A CESM2.1.5 and CESM2.2.2 release tags are going to be made because of an issue with CAM. The plan is also to change support from Cheyenne to Derecho in that tag. So this means we will need to have CLM and CTSM release tags for those versions that change testing over to Derecho, and add PE layouts for Derecho. And we might as well remove support for Cheyenne.

**Comment by wwieder** [comment]
This tag will include:
- [ ] PE layouts
  - Optimized PE layouts are less critical here, we just want something that works.
- [ ] Updates to the CTSM test list
  - do not do this for RTM and MOSART? No, Eriks' suggesting the test lists aren't need.

**Comment by ekluzek** [comment]
I'm splitting this into two since the tags are on separate branches.
