### ISSUE TITLE
run_neon fails

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#2266]
### Brief summary of bug
Any idea what may be generating this error?  It seems like we've broken run_neon at some point.

Running in bash with ctsm_pylib activated

$./run_neon --help
```
Traceback (most recent call last):
  File "./run_neon", line 44, in <module>
    from ctsm.site_and_regional.run_neon import main
  File "/glade/u/home/wwieder/CTSM/tools/site_and_regional/../../python/ctsm/site_and_regional/run_neon.py", line 69, in <module>
    from CIME import build
ModuleNotFoundError: No module named 'CIME'
```
### General bug information

**CTSM version you are using:** [output of `git describe`]
ctsm5.1.dev152

**Does this bug cause significantly incorrect results in the model's science?** 
Yes, it breaks a feature we'd like to be supporting

**Configurations affected:** [Fill this in if known.]

### Details of bug

externals have been updated and my branch just has a few updates to usermods

### Important details of your setup / configuration so we can reproduce the bug
@adrifoster has the same issue running on dev155

**Comment by adrifoster** [comment]
I believe this will be fixed if we move the line `from ctsm import add_cime_to_path` to right before we call `from CIME import build`
