### ISSUE TITLE
What to do with tools/contrib tools that are designed to work on Cheyenne?

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2277]
Some of the tools under the tools/contrib directory are setup to work on Cheyenne. Should these tools be ported to Derecho? Removed? Left in place until the Author can port them?

**Comment by slevis-lmwg** [comment]
+1 @samsrabin

**Comment by ekluzek** [comment]
Closing as wontfix. We will wait until someone either wants to update something here, or mentions a specific problem they have with one of these codes.
