### ISSUE TITLE
t_startf is within an if statment and t_stopf is not in CNDriverMod.F90

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#2291]
### Brief summary of bug

In CNDriverMod.F90, there is a t_startf call that is within an if statement, but the t_stopf is outside the if statement. 
Reported by @olyson , solution by @mvdebolskiy 

### General bug information

**CTSM version you are using:** ctsm5.1.dev156

**Does this bug cause significantly incorrect results in the model's science?** No?

**Configurations affected:** CLM-FATES regional simulation, maybe others.

### Details of bug

In CNDriverMod.F90, the "call t_startf('CNZero-vegbgc-nflux')" is within a "if(num_bgc_vegp>0)then" statement but the "call t_stopf('CNZero-vegbgc-nflux')" is not.  This results in a bunch of PET log files in the run directory with the error:

20231213 121004.634 ERROR            PET059 /glade/p/cesmdata/cseg/PROGS/build/28281/esmf-8.5.0b19/src/Infrastructure/Trace/src/ESMCI_Trace.C:1617 ESMCI::TraceEventRegionExit() Wrong argument specified  - Trace regions not properly nested. Attempt to exit region: CNZero-vegbgc-nflux that was never entered.
20231213 121004.634 ERROR            PET059 /glade/p/cesmdata/cseg/PROGS/build/28281/esmf-8.5.0b19/src/Infrastructure/Trace/interface/ESMCI_Trace_F.C:141 c_esmftrace_region_exit() Wrong argument specified  - Internal subroutine call returned Error
20231213 121004.640 ERROR            PET059 /glade/p/cesmdata/cseg/PROGS/build/28281/esmf-8.5.0b19/src/Infrastructure/Trace/src/ESMCI_Trace.C:1617 ESMCI::TraceEventRegionExit() Wrong argument specified  - Trace regions not properly nested. Attempt to exit region: CNZero-vegbgc-nflux that was never entered.
20231213 121004.640 ERROR            PET059 /glade/p/cesmdata/cseg/PROGS/build/28281/esmf-8.5.0b19/src/Infrastructure/Trace/interface/ESMCI_Trace_F.C:141 c_esmftrace_region_exit() Wrong argument specified  - Internal subroutine call returned Error

https://github.com/ESCOMP/CTSM/blob/03246f8c6bdf287d7c1d678955bb720f2dfec3ed/src/biogeochem/CNDriverMod.F90#L263-L291

### Important details of your setup / configuration so we can reproduce the bug

Case Directory:
/glade/work/oleson/ctsm5.1.dev156/cime/scripts/Dec05_d156

**Comment by ekluzek** [comment]
This was fixed in #2358 so closing.
