### ISSUE TITLE
Changes to xdrdt in the parameter file have no effect because of a hard-coded flag set to .false. (flg_snoage_scl    = .false.)

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#2298]
Changes to xdrdt in the parameter file have no effect because of a hard-coded flag set to .false. in SnowSnicarMod.F90

  ! scaling of the snow aging rate (tuning option):
  logical :: flg_snoage_scl    = .false.                 ! flag for scaling the snow aging rate by some arbitrary factor

            ! Multiply rate of change of effective radius by some constant, xdrdt
            if (flg_snoage_scl) then
               dr = dr*params_inst%xdrdt
            endif

The suggested fix is to remove flg_snoage_scl completely such that xdrdt will always have an effect if changed in the parameter file.

**Comment by wwieder** [comment]
Thanks for creating this issue (and spotting it in the first place!), @olyson. I think this is a good idea to avoid confusion.
