### ISSUE TITLE
how to modify the total albedo in couple model

### ISSUE THREAD

**Issue by liujia96** [ESCOMP/CTSM#2299]
I want to modify the surface albedo in a latitude and longitude range, but I do not find any data directly representing the albedo in the input data.

**Comment by wwieder** [comment]
This is really a question that I'd encourage you to post questions on the [CESM bulletin board](https://bb.cgd.ucar.edu/cesm/).  We use github issues to manage model development, software engineering resources, and provide model documentation to users.
