### ISSUE TITLE
len function is around the wrong variable

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2305]
### Brief summary of bug

The len function in the MPI broadcast is around the wrong string variable.

https://github.com/ESCOMP/CTSM/pull/2076#discussion_r1437502750

### General bug information

**CTSM version you are using:**ctsm5.1.dev160

**Does this bug cause significantly incorrect results in the model's science?** No

**Comment by glemieux** [comment]
@rgknox could we get the fix in for this with #2265?

**Comment by rgknox** [comment]
that works for me

**Comment by glemieux** [comment]
thanks
