### ISSUE TITLE
Potential vegetation surface dataset for CTSM5.2 for f09

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2320]
Another dataset to create is the surface dataset for the PotentialVeg dataset for 1-degree 0.9x12.5.

**Comment by wwieder** [comment]
Is this raw dataset already available, @lawrencepj1 ? If so, is this just a surface dataset that needs to be added to the makefile?

**Comment by lawrencepj1** [comment]
Hi Will

Yes the potential vegetation raw data exists but I don't know if it has been processed by @slevis-lmwg. I am talking with Sam and @ekluzek in 10 minutes so I will bring it up. Sorry I have been sick for weeks trying to get back into work now.

See you
Peter

**Comment by slevis-lmwg** [comment]
As @lawrencepj1 said, the raw dataset exists, so this issue is a subset of #1903. 

Issue 1903 links to the spreadsheet that lists all the grids and cases that I will be generating files for; therefore, we do not need this as a separate issue, and I will close it.
