### ISSUE TITLE
FORTRAN unit testing is broken on Derecho

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2329]
Errors with
```
ERROR: PFUNIT_PATH not found for this machine and compiler
```

This can be fixed with an externals update. For now, testing on Izumi works. I'll soon submit a PR moving the `FUNITCTSM_P1x1.f10_f10_mg37.I2000Clm50Sp.derecho_intel` to Izumi, at least until we get Derecho working.

Assigning to @ekluzek, who will update externals based on the next CESM beta tag.

**Comment by ekluzek** [comment]
The ccs_config issue covering this is:

ESMCI/ccs_config_cesm#131

**Comment by glemieux** [comment]
Is this fixed?  I saw discussion in the CTSM SE chat for the recent b4b-dev that suggested it was.

**Comment by ekluzek** [comment]
Yes, this is fixed with the externals update in ctsm5.1.dev172. So closing.
