### ISSUE TITLE
py_env_create fails on Izumi

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2332]
### Brief summary of bug

Calling `./py_env_create` on Izumi fails with the error `CondaValueError: Malformed version string '~': invalid character(s).` This happens even if the conda environment name is changed from ctsm_pylib to ctsm_pylib2 (or something else not matching an existing conda environment).

### General bug information

**CTSM version you are using:** ctsm5.1.dev163

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** n/a

### Important output or errors that show the problem
```
Use conda to install the python environment needed to run the CTSM python tools in the conda environment: ctsm_pylib2
Using the file: ./python/conda_env_ctsm_py_cgd.txt
ctsm_pylib2 environment already exists
Install ctsm_pylib2 this can take a long time, be patient....
conda install --yes -q -c conda-forge -n ctsm_pylib2 --file ./python/conda_env_ctsm_py_cgd.txt
Solving environment: ...working... failed

CondaValueError: Malformed version string '~': invalid character(s).

Trouble installing the ctsm_pylib2 python environment
There must be a problem in the ./python/conda_env_ctsm_py_cgd.txt conda specification environment file
Change the file and try again

On CGD systems you may need to do the following...
Create a bin subdirectory and then link the python version into it...
   mkdir /home/samrabin/.conda/envs/ctsm_pylib2/bin/
   ln -s /usr/local/anaconda-3.7.0/bin/python /home/samrabin/.conda/envs/ctsm_pylib2/bin/python3.7
```
(And yes, the error happens even if I do the "you may need to do the following" steps.

**Comment by slevis-lmwg** [comment]
I get the same error.

**Comment by slevis-lmwg** [comment]
Linking related issue #2331

**Comment by ekluzek** [comment]
Yep, I'm getting the same error. My existing conda environment works, but the py_env_create fails.

When I do the conda install part by hand, it seems to actually work -- I think although it does show the error above. But, status seems to be OK. Although I also don't think it did anything.

This also has to do with the screwy way that conda is installed on izumi. But, is izumi going to continue to be around?

**Comment by samsrabin** [comment]
As a workaround, it might be best to add special handling for Izumi that does everything except the `conda install` part, then prompts the user to do that part manually.

**Comment by glemieux** [comment]
Is there a recommended workaround in practice for this issue currently?  Do we simply build the conda environment manually using the environment yaml file in the python directory?

**Comment by slevis-lmwg** [comment]
@glemieux it's possible that each of us has come up with our own workaround. Mine is
```
source ~/.bashrc
conda activate ctsm_pylib
```
The former activates for me a "base" conda environment. The latter activates a ctsm_pylib that I generated some number of months ago.

**Comment by samsrabin** [comment]
@glemieux  There's a conda update coming hopefully today that should fix the issue.

**Comment by samsrabin** [comment]
Okay, seems to now be working. I did have to change a line in my .bash_profile from
```bash
module load lang/python/3.7.0
```
to
```bash
module load lang/anaconda/23.11.0/python/3.11.5
```

@glemieux can you try it? If it works, I'll close this issue.

**Comment by glemieux** [comment]
@samsrabin I was able to successfully run `py_env_create` with that module loaded.
