### ISSUE TITLE
Build fails with run_neon in dev166

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#2340]
### Brief summary of bug

Build fails for a single point case created with the run_neon script in tag dev166.  The build works as expected in dev162.

### General bug information

**CTSM version you are using:** [output of `git describe`]
ctsm5.1.dev166

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]
NO

**Configurations affected:** [Fill this in if known.]
Only tested for case created with run_neon.

### Details of bug
ERROR: BUILD FAIL: clm.buildlib failed, cat `/glade/derecho/scratch/wwieder/mimics_NEON/ABBY/bld/lnd.bldlog.240130-100833`

The case that built as expected with dev162 can be seen at `/glade/derecho/scratch/wwieder/mimics_NEON/BART`

### Important details of your setup / configuration so we can reproduce the bug

Cases created with the run_neon command
`/run_neon --neon-sites ABBY --output-root /glade/derecho/scratch/wwieder/mimics_NEON`

### Important output or errors that show the problem

The dev162 branch had minor changes to the order of import statements for the run_neon.py script to get it to run.

**Comment by wwieder** [comment]
After updating my externals I confirmed that run_neon and a generic single point case both built and ran as expected.
I'm closing this issue with a sheepish `user_error` label.

**Comment by ekluzek** [comment]
@wwieder and all -- just pointing out I'd rather have a culture where we feel free to point out issues than one where everyone is too afraid to do that. I suppose there is a balance there, but we are in no way encumbered by people pointing out too many issues that don't really exist. So it's fine to point out a problem that doesn't turn out to be one especially when it's not very often. These kind of problems are also the easiest things to fix!
