### ISSUE TITLE
Parameter file formatting has changed

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#2347]
### Brief summary of bug

Changes to the formatting of the default parameter file make the file difficult to work with outside of python.

### General bug information
for example, an ncdump on the new parameter file produces this:
```
ncdump -v bgc_rf_l1s1 /glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/paramdata/ctsm51_params.c240105.nc 
bgc_rf_l1s1 = _ ;
```

whereas doing this for an older file shows:
```
ncdump -v bgc_rf_l1s1 /glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/paramdata/ctsm51_params.c231117.nc 
bgc_rf_l1s1 = 0.55
```

Besides making it difficult to quickly query default parameter values, this bug makes modifying a parameter file as we [describe on the wiki](https://github.com/ESCOMP/CTSM/wiki/Moving-a-parameter-to-the-params-file) impossible.  It also makes it difficult to use nco commands, like ncap2, because it's difficult to then check that modified parameter values have been changed as intended.

**CTSM version you are using:**  
latest master tag, ctsm5.1.dev166

**Does this bug cause significantly incorrect results in the model's science?** 
No, but it does make modifying the parameter file with ncdump or nco commands difficult

**Configurations affected:** [Fill this in if known.]
All

**Comment by wwieder** [comment]
note here, this would be an easy one for a bfb_dev tag, but if you can share a corrected parameter file that I can more easily edit it would be helpful, Sam.

**Comment by olyson** [comment]
Yes, I can't seem to use the approach detailed on the wiki to add a new parameter to the parameter file.  I can run through the steps ok, but when I try to use the new parameter file in a simulation I get:

ERROR:  ERROR: crop has wrong valuesERROR in pftconMod.F90 at line 1344

which is not something I changed.  An ncdump -v crop of the file gives:

 crop = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _ ;

I think the "_"'s should be 1s.
I'm not sure how to resolve this so I can move forward with my deadveg PR. Suggestions?

**Comment by samsrabin** [comment]
@olyson I'll go ahead and make new parameter files later this afternoon.
