### ISSUE TITLE
The Meier roughness could be connected to dust Prigent roughness streams..

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2349]
The Meier roughness work had development that including using the Prigent roughness data with it as an option. Since, this same dataset comes in with the dust work in #1897 it could be connected after that point. 

I'm thinking this is a low priority and maybe something that would happen after CESM3. Connecting the software to do this won't be hard, but it will need someone to evaluate the science. It could be straightforward though since the Meier paper could be used to verify that results are similar in the latest version. So it doesn't necessarily need extensive scientific analysis, nor extensive scientific research.

**Comment by wwieder** [comment]
Thanks for remembering this, Erik.  Is Prigent dataset also optional for the dust work?

**Comment by ekluzek** [comment]
It's currently on by default with Leung_2023. Technically it can be turned off, but it's not obvious how you do that. I'll make it more obvious on how to turn it on or off though when dust comes in. Since it's something that can be used for both it should be considered independent of either. That might make a small difference in how it comes in...

**Comment by ekluzek** [comment]
Research question and something probably post CESM3.

**Comment by ekluzek** [comment]
@olyson will look at the Meier paper to see if it was an important contribution and easy to follow. It might be easy to implement and check, if so we might do it.

**Comment by wwieder** [comment]
Thanks for looking into this, @olyson.  I'm not sure we gain much beyond satisfaction by using the dataset consistently for dust and roughness.  With limited scientific gains, I'm inclined to close this issue with a won't fix label.  What do others think?

**Comment by ekluzek** [comment]
I'm good with either. @dlawrenncar also looked at the Meier work when it was being developed, so would like to hear from him. It might also be good to hear from @dmleung as he is our local expert on the Prigent data.

The main argument I see is that the Prigent dataset gives us observational estimates of roughness over bare rock and soil, while without it we use a constant value everywhere. But, yes if it doesn't make much of a difference is it worthwhile? Also for Paleo climate we'll have to NOT use it, as it's from 2012 satellite observations.

I did look at the Meier roughness issue and PR and didn't see much I thought worth sharing. But, I link them below..

@dmleung did have a PDF that talks about the Prigent datasets (both 2005 and 2012). It's mostly a comparison between the two, but also gives some information on them.

https://github.com/ESCOMP/CTSM/pull/1596#issuecomment-1203217500

#1596
#1316

**Comment by dlawrenncar** [comment]
I don't have any significant additional recollection of the relevance of
this, so I think it probably makes sense to close this as a won't fix due
to all the other competing development demands.

**Comment by ekluzek** [comment]
Closing as a wontfix for now
