### ISSUE TITLE
Create USUMB tower site using subset_data and have a test for it

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2356]
We've supported the USUMB tower site with our testing to both demonstrate that PTCLM works and can work with the model. But, also to demonstrate how to setup a generic tower site for people that want to do that for their own site have a way forward to do that, as well as testing to make sure that a generic tower site works. NEON (and soon to be PLUMBER2) sites are highly curated and are substantially different from a random site.

Definition of done:

- [ ] Add a rule to the mksurfdata_esmf Makefile to create the USUMB surface dataset
- [ ] Add a test using the new surface dataset (it will be similar to the current test, but based on subset_data)

**Comment by wwieder** [comment]
Hi Erik,  Thanks for bringing this up.

Maybe it's worth clarifying what the purpose of this test is for? 
- Is it basically to run subset data and make sure we can run a 'generic single point' case with globally gridded DATM forcing?
- Alternatively the text above mentions the old USUMB was to _"demonstrate how to setup a generic tower site"_, which I assume requires having observed meterology from a flux tower formatted for the DATM?  I'm not sure that's something we should worry about creating / testing.  More broadly, do we need to continue testing for a workflow that's no longer supported or 'tutorial' examples that do not exist?
- Finally US-UMB is already a[ PLUMBER2 site](https://github.com/ESCOMP/CTSM/blob/8d3468597b0b9bb1db351f755c6662bb500e4b96/cime_config/usermods_dirs/PLUMBER2/US-UMB/shell_commands), so a supported tower site for CLM6, but I don't think this is what you're wanting to test?

**Comment by ekluzek** [comment]
@wwieder good questions there. I didn't realize USUMB was part of PLUMBER2 for example. I still think testing that datasets created by subset_data is a good thing to do. A better test would be a test that actually runs subset_data and shows that you can create a dataset and then use it for a simulation that actually works. I do think that testing the special case of showing how to set it up when the user has tower site data is a good thing, because there's extra work to get that case going.

However, based on your comments I'm wondering if just doing the BCI case in #2159 would be the best way to go? So we'd just get that case working and forget about USUMB as a separate test.

**Comment by wwieder** [comment]
Thanks Erik.  It sounds like the purpose of the test is  to run subset data and run a 'generic single point' case with globally gridded DATM forcing?  If so, I'd agree this sounds similar to the BCI test discussed in #2159

**Comment by ekluzek** [comment]
In meeting we decided to close this as a wontfix. I will open an issue about doing a system test for generic point with subsetting the datm data and then running a case for it.
