### ISSUE TITLE
Do some design work on the dust module: base, Zender_2003, and Leung_2023 classes.

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2360]
Do some design work on how the dust modules to support Zender_2003, and Leung_2023 will work together.

**Comment by wwieder** [comment]
Erik, I was thinking about this and wondered, does this get any easier if we don't have to support Zender_2003 moving forward, with CLM6 only having Leung_2023?  Would it be helpful to touch base with @tilmes again to see what's needed for CAM-Chem development for CESM3?

**Comment by ekluzek** [comment]
It's true that it gets a little easier if we don't support Zender moving forward. But, we lose a lot more doing that than allowing both gets us. It makes the transition for both CAM and CTSM more interconnected and entwined and also doesn't allow both to be easily compared as tuning goes on. And people working in dust are going to want to easily compare the options for publications. And eventually I'm going to expect that there will be future dust emission options that someone will want to try. Once, this is in place it will facilitate making that easy. We did this for fire for example and it makes it easy to compare the different methods, and to add a new updates option, which Fang has done now for several times. The methodology I'm going to use is the same as for fire, I just need a little planning to map it out. So I don't expect this to be that long. But, you are right that I shouldn't spend too much time on it, and if I do end up spending too much time -- I should end it early. Long term they don't think they need Zender, but it will help the transition part of this for sure. So let's monitor this for now...

**Comment by wwieder** [comment]
Sounds good, Erik.

To a certain extent, I think Danny's papers document some of the changes, but you're right in the short term it may be helpful to compare the two schemes easily.  The tradeoff may be that CAM-Chem wants this to come to main soon, as it's critical for cloud tuning and coupled model experiments.  I can't advise much on the prioritization here, as it's not LWMG science, so wanted to raise questions about the perfect (both schemes supported) being the enemy of the good (Leung brought to main).  I like your assessment _"if I end up spending too much time -- I should end it early"_.

**Comment by ekluzek** [comment]
OK, the design work is done. I'm having @slevis-lmwg, @dmleung and @adrifoster look it over.

https://docs.google.com/document/d/18nZ3LJF5W-YF9iBhqed6s_NWeKOvSSL2-k0Lye1nnLg

**Comment by ekluzek** [comment]
I met last Friday with the group, I've updated the document and this is completed.
