### ISSUE TITLE
ctsm_pylib on Izumi can now use Python 3.7.9

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2380]
Perhaps not worth worrying about, but after the recent `conda` upgrade on Izumi I was wondering if the Python 3.7.0 specification is unnecessary. It turns out, if you specify Python 3.7.9 in `python/conda_env_ctsm_py_cgd.txt`, it now installs just fine. Everything in `make all` works except the stuff dependent on cdo, nco, and the inputdata directory.

**Comment by ekluzek** [comment]
This would be a great thing to get in place so that we don't have a separate file for CGD than for elsewhere. So this is a nice bit of code cleanup. I'm glad you tested it and made sure it works. And if it does it would be good to bring this into b4b-dev.
