### ISSUE TITLE
Cold start soil temperature initialization when excess ice is on.

### ISSUE THREAD

**Issue by mvdebolskiy** [ESCOMP/CTSM#2384]
I have added a use_fates that encompasses the code in question as suggested by @wwieder in issue #2373 .  The test now passes. However, a couple of questions.
1. The setting of t_soisno to 5deg below the freezing temperature when excess_ice is on is outside of the use_fates check and so if the test is changed so that excess_ice is on ( the current default is off), this test will fail (confirmed).  I'm not sure what the future plans for excess_ice are and if it is intended for use with FATES.
2.  There is an indication from the excess_ice PR (https://github.com/ESCOMP/CTSM/pull/1787) that it might be ok to set the initial soil temperature to 272K instead of tfrz-5.  This would simplify the code, particularly if we want to run FATES with excess_ice on.  "src/biogeophys/TemperatureType.F90 -- initial soil temperature set to 268.15 K at the cold start (might be redundant if https://github.com/ESCOMP/CTSM/issues/1460 is added)"

_Originally posted by @olyson in https://github.com/ESCOMP/CTSM/issues/2355#issuecomment-1954837943_

**Comment by mvdebolskiy** [comment]
Proposed fix:
 - Remove condition for `use_excess_ice` in `TemperatureType.F90`
 - Change soil temperature below 0.5 m to ~272 K in the `WaterStateType.F90` `InitCold` when excess ice is read only for soil columns in gridcells that have excess ice.
 - Comment `TemperatureType.F90` that soil temperature will get adjusted later.
 - Check if FATES vegetation doesn't die in the gridcells with excess ice on in the first few years.
 - Check if FatesHydro doesn't fall apart.

**Comment by ekluzek** [comment]
@mvdebolskiy will create a PR with these changes and then have @olyson test it.
