### ISSUE TITLE
Figures are missing in the User's Guide (development version)

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#2392]
It seems like a recent build of the documentation has caused the figures to go missing.  E.g., the figures for SP and BGC spinup are missing:

https://escomp.github.io/ctsm-docs/versions/master/html/users_guide/running-special-cases/Spinning-up-the-Satellite-Phenology-Model-CLMSP-spinup.html

https://escomp.github.io/ctsm-docs/versions/master/html/users_guide/running-special-cases/Spinning-up-the-biogeochemistry-BGC-spinup.html

The CLM5 version appears to be ok.
Is this in process of being fixed maybe?

**Comment by ekluzek** [comment]
Hmmm. Thanks for noticing this @olyson. @samsrabin pushed the last build. @samsrabin do you have any idea on what might have happened? We should figure this out and correct....

**Comment by samsrabin** [comment]
No idea, sorry. Keith, would you mind building and fixing? I'll try to figure out what I did wrong later. Somehow I just wiped most data from the images:
<img width="805" alt="screenshot_0086" src="https://github.com/ESCOMP/CTSM/assets/10454527/80044301-2097-4803-bbc0-2760c530f0f9">

**Comment by olyson** [comment]
I'll take a look, thanks.  (Good luck on your talk!).

**Comment by olyson** [comment]
Ok, I've rebuilt the documentation and it looks good locally on my machine.  I can push directly to gh-pages if ok with everyone.  I also did fix one problem with a table in the methane chapter.  I seem to remember however that @samsrabin might have mentioned fixing this already maybe?  So I'm not quite sure I have the most recent ctsm master with respect to the rst files?

**Comment by samsrabin** [comment]
Oh, I mentioned this in the ctsm-docs PR but it's closed already so you probably didn't see. I used b4b-dev at f50a634.

**Comment by samsrabin** [comment]
I figured it out—I didn't have `git lfs` initialized. Will submit a PR to fail `doc/build_docs` if that's the case.
