### ISSUE TITLE
Put all .gitignore entries in top-level file

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#245]
I started having multiple `.gitignore` files in different places. However, I was just doing some googling, and it sounds like the most common convention is to put everything in the top-level .gitignore file. So I'd like to rework things to do that. So, for example, this entry in `src/unit_test_stubs/utils/.gitignore`: `restUtilMod_stub.F90` would go in the top-level as `/src/unit_test_stubs/utils/restUtilMod_stub.F90` (I think it's correct to have this leading slash here: I think this says to match exactly this path).

**Comment by ekluzek** [comment]
Moved a few to the top, but I left the unit tests ones and the ones that are about the generation of *.F90 files from .F90.in in place.
