### ISSUE TITLE
Add landuse.timeseries files for 1979-2026 for the three VR grids (CONUS, ARCTIC, ARCTICGRIS).

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2487]
For CAM-Chem it's become recognized that we need to support landuse.timeseries files for the three VR grids we (currently) support (CONUS, ARCTIC, ARCTICGRIS). Because these are high resolution datasets supporting the whole range of 1850-2100 isn't needed. But, they would like to support a shorter time-range for it. 

Since, this is beyond the historical data we have to pick a SSP for the data beyond 2015, so we'll use SSP2-4.5. This will allow CAM-Chem users to have transient PFT data that brings them into present day even for a few years into the future. Since, CMIP7 data will be coming online in a year or two and datasets will be redone, we don't need to go too far into the future, but we might as well give a few years leeway.

Definition of done:

- [x] Create new files from the ctsm5.2.0 tag (need both a 1979 surfdata files AND 1979-2026 landuse.timeseries)
- [x] Add the new files to namelist defaults
- [x] Add tests for these three to the ctsm_sci test list
- [x] Add creation of these to the gen_mksurfdata_jobscript_multi script (possibly all three together)
- [x] Add the creation of these to the tools/mksurfdata_esmf Makefile, so automatically built on "make all"
- [x] Make sure the build of the files works (and duplicates the ones from the first step when using same PE layout)
- [x] Rename files as detailed below
- [x] @ekluzek propose new compset and ctsm_sci test as detailed below
- [x] @slevis-lmwg add new test
- [x] Make sure the ctsm_sci test works with the new files in place after updating config_component.xml
- [x] ./rimport the files

**Comment by ekluzek** [comment]
Part of this comes about because of the following cesm2_3_alpha17d test failures...

```
PEND SMS_D_Ln9_Vnuopc_P1280x1.ne0CONUSne30x8_ne0CONUSne30x8_mt12.FCnudged.derecho_intel.cam-outfrq9s SHAREDLIB_BUILD
    err=ERROR : CLM build-namelist::CLMBuildNamelist::add_default() : No default value found for flanduse_timeseries.

PEND SMS_D_Ln9_Vnuopc_P1280x1.ne0CONUSne30x8_ne0CONUSne30x8_mt12.FHIST.derecho_intel.cam-outfrq9s SHAREDLIB_BUILD
     err=ERROR : CLM build-namelist::CLMBuildNamelist::add_default() : No default value found for flanduse_timeseries.
```

**Comment by slevis-lmwg** [comment]
@ekluzek I'm noting here: I think you said that these should be added to the mksurfdata_esmf Makefile, so as to be done whenever we make all.

**Comment by ekluzek** [comment]
@slevis-lmwg yes exactly. I've added a more detailed checklist to the top as a "definition of done". Technically all of that wouldn't need to be done now. But, it seems like it would be better to get it all done at once.

**Comment by slevis-lmwg** [comment]
I generated the new files' namelists using these settings:
```
./gen_mksurfdata_namelist --res ne0np4CONUS.ne30x8 --start-year 1979 --end-year 2026 --ssp-rcp SSP2-4.5
./gen_mksurfdata_namelist --res ne0np4.ARCTIC.ne30x4 --start-year 1979 --end-year 2026 --ssp-rcp SSP2-4.5
./gen_mksurfdata_namelist --res ne0np4.ARCTICGRIS.ne30x8 --start-year 1979 --end-year 2026 --ssp-rcp SSP2-4.5
```
Next I will submit jobs to generate the files.

**Comment by slevis-lmwg** [comment]
The new files are now in `/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/surfdata_esmf/ctsm5.2.0`.

@ekluzek I will let you check that these seem right to you before I ./rimport them.

**Comment by wwieder** [comment]
Thanks for doing this, @slevis-lmwg.

**Comment by slevis-lmwg** [comment]
ctsm_sci test-suite IN PROGRESS

**Comment by slevis-lmwg** [comment]
Submitted `make crop-global-SSP2-4.5-ne0np4`

**Comment by slevis-lmwg** [comment]
@ekluzek the sixth checkbox has raised a concerning problem:
I generated the files manually in step 1 and with the Makefile in step 6. I have now diff-ed the first two files:
`diff /glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/surfdata_esmf/ctsm5.2.0/surfdata_ne0np4.ARCTICGRIS.ne30x8_SSP2-4.5_1979_78pfts_c240425.asc /glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/surfdata_ne0np4.ARCTICGRIS.ne30x8_SSP2-4.5_1979_78pfts_c240426.asc > dif1.out`
I see differences in PCT_SAND, PCT_CLAY, ORGANIC, and mapunits. Currently, my only explanation is that these ran on different numbers of tasks:
```
<               :Host = "derecho7" ;
<               :Number-of-tasks = 256 ;
---
>               :Host = "derecho6" ;
>               :Number-of-tasks = 1152 ;
```

**Comment by ekluzek** [comment]
Hmmm. OK, a change in number of MPI tasks changes these fields. This could be an important bug, if the difference is large enough.

Compare the netcdf files with cprnc. So something like...

**Comment by ekluzek** [comment]
And is this related to #2430?

**Comment by slevis-lmwg** [comment]
From meeting with @ekluzek:
For now, call the new files good.
Open new issue about the problem and perform testing with f09 to make easier to visualize.
