### ISSUE TITLE
Bypass balance checks for first N steps after data assimilation

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#249]
@ekluzek and I met today with @timhoar @gold2718 @kdraeder and Andy Fox (anyone know his github user name?). Tim wants to put in place some mods to bypass the biogeophys and CN balance checks for at least the first time step after doing data assimilation (i.e., after mucking with the restart file); Andy says that at least a few time steps are needed in some cases for the CN balance checks.

Steve Goldhaber has a PR that will provide the signal needed to trigger this logic: https://github.com/ESMCI/cime/pull/2267 . Once that cime change is on master and we adopt a relevant cime version in CTSM, we should make Tim's changes.

The basic logic will look something like this:

- In `lnd_init_mct`, query the infodata field `lnd_resume`.

- Create a logical based on `lnd_resume`: if `lnd_resume` is non-blank, that implies that we just did data assimilation, and so should trigger the special post-data assimilation logic. So set some logical like `resume_from_data_assim` based on whether this is non-blank. (The exact value of `lnd_resume` doesn't matter for now; eventually it could be used to get the name of the restart file that was mucked with -- excuse me, "beautified" -- by the data assimilation.)

- Pass this logical (`resume_from_data_assim`) to the CLM time manager in its initialization

- Introduce a new function in the time manager: `nsteps_since_restart_modification()`. This will give the number of time steps since the time manager was initialized with `resume_from_data_assim` true. (If that was never true, this will simply equal nsteps.)

   I realized after this discussion that, in order to handle all edge cases, we'll need to add some extra information to the restart file. For example, imagine a case where the model restarted with `lnd_resume` non-blank, so `nsteps_since_restart_modification()` gets reset to 0. Then we run for (say) 2 time steps. Then restart, this time with `lnd_resume` blank. We'd expect `nsteps_since_restart_modification()` to pick up at 3. This will only work if some new piece of information is written to the restart file.

- Other code - such as the balance check code - can then call this new time manager function. Balance checks can then easily be bypassed for the first N steps since resuming from data assimilation.

**Comment by billsacks** [comment]
@timhoar would ideally like this in place by the CESM2 release. I have created a new milestone for this purpose.

**Comment by ekluzek** [comment]
Note, that @billsacks says we need to add information to the restart file in comment above. I don't think that is the case, as if LND_DATA_ASSIMILATION=TRUE it will send a pause/resume signal at startup. Technically there could be very strange setups where the nsteps_since_DA is incorrect, but for practical purposes I don't think there is any such important case. So we won't add anything to the restart file, unless we are shown that we really have to.

**Comment by ekluzek** [comment]
Note, this now coming to master, and has a test for it. There is an issue in cime associated with it though: https://github.com/ESMCI/cime/issues/2590

**Comment by billsacks** [comment]
> Note, that @billsacks says we need to add information to the restart file in comment above. I don't think that is the case, as if LND_DATA_ASSIMILATION=TRUE it will send a pause/resume signal at startup. Technically there could be very strange setups where the nsteps_since_DA is incorrect, but for practical purposes I don't think there is any such important case. So we won't add anything to the restart file, unless we are shown that we really have to.

I agree that it probably isn't critical to have this on the restart file, since the cases where it matters are rather contrived and unlikely to occur in practice.
