### ISSUE TITLE
Wrong long_name for RH2M_R

### ISSUE THREAD

**Issue by cathyxinchangli** [ESCOMP/CTSM#2506]
On [line 349 of CTSM/src/biogeophys/WaterDiagnosticBulkType.F90](https://urldefense.com/v3/__https:/github.com/ESCOMP/CTSM/blob/286146f4a34daed401c399e5ea76767482639c9f/src/biogeophys/WaterDiagnosticBulkType.F90*L344C1-L350C78__;Iw!!DZ3fjg!_hqwP_3f7BEnTW6BD7kK52thDkYvkwXpDZjKbpmtwqIEtslnwVKmqPEYaCEDP7DP25u3wyOIX1lT25JRvpT1$), the long_name for `RH2M_R` seems to be incorrectly labeled as 'Rural 2m **_specific_** humidity', which should instead be 'Rural 2m **_relative_** humidity'. This mistake is also propagated to [the CTSM History Fields in the user’s guide](https://urldefense.com/v3/__https:/escomp.github.io/ctsm-docs/versions/release-clm5.0/html/users_guide/setting-up-and-running-a-case/master_list_file.html*:*:text=947,2m*20specific*20humidity__;I34lJQ!!DZ3fjg!_hqwP_3f7BEnTW6BD7kK52thDkYvkwXpDZjKbpmtwqIEtslnwVKmqPEYaCEDP7DP25u3wyOIX1lT2-SIOsIk$).

**Comment by wwieder** [comment]
Thanks for finding this @cathyxinchangli we'll correct the code and documentation accordingly.  Mind if I assign this to you, @olyson

**Comment by wwieder** [comment]
Looks like this was merged
