### ISSUE TITLE
Change hist_type2d_pertape to hist_type1d_pertape in User's Guide

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#2509]
Change hist_type2d_pertape to hist_type1d_pertape in User's Guide.  hist_type2d_pertape isn't a valid namelist variable.
https://escomp.github.io/ctsm-docs/versions/master/html/users_guide/setting-up-and-running-a-case/customizing-the-clm-namelist.html?highlight=hist_type2d_pertape

**Comment by samsrabin** [comment]
Closing as a duplicate of #103.
