### ISSUE TITLE
Failures in build-namelist_test.pl

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2530]
### Brief summary of bug

build-namelist_test.pl has 456 tests fail (at least on Izumi), many due to missing files.

### General bug information

**CTSM version you are using:** ctsm5.2.003

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** n/a

### Important details of your setup / configuration so we can reproduce the bug

Testing on Izumi only, as Derecho is down today.

Called like so in `bld/unit_testers/`:
```bash
./build-namelist_test.pl -csmdata /fs/cgd/csm/inputdata
```

### Important output or errors that show the problem
See [this gist](https://gist.github.com/samsrabin/36d25e0a8e285b785ceabd8618345a76), since it's too long to include here.

**Comment by ekluzek** [comment]
With Derecho down I'm running into this as well. I'm working on bringing some files over to limit some of this.

As a workaround you can run it with the "--no-test" option so it doesn't look for the files. Doing that in a clone of ctsm5.2.003 everything passes for me.

**Comment by samsrabin** [comment]
Okay, yes, I'm seeing the same thing—a pass with the `-no-test` option. Could you let me know when the files are all transferred? I can then re-test and close this issue.

**Comment by briandobbins** [comment]
What files are these?  Are they data files, that perhaps should be in our input data repo?  (Or if exclusive to testing, perhaps a secondary file repo?)

Ideally, I'd like to have all _tests_ be as portable as all runs, especially if we want external folks to run tests themselves.  It's not a near-term need, but something good to shoot for, I think.

**Comment by samsrabin** [comment]
@briandobbins Good question. I think they might be in our repo but the testing doesn't try to download them? Is that right, Erik?

**Comment by ekluzek** [comment]
@briandobbins and @samsrabin these are tests for datasets that ARE in the repository. We just don't test as many resolutions on Izumi as on Derecho, so we haven't downloaded all the datasets to Izumi.

This is also the namelist testing so it checks for pretty much everything, and also doesn't make it easy to download everything. However, if I run the ctsm_sci Derecho test list on Izumi it should make cases for pretty much everything and then I can easily run check_input_data in those cases to get the data. So I'll do that.

Doing this kind of thing on Izumi is also one way I've used to make sure datasets ARE in the inputdata repo. So sometimes I catch things that aren't there by trying to do things like this on Izumi.

Does that answer everything you need @briandobbins?

**Comment by samsrabin** [comment]
@ekluzek Would it not be easier to just `rsync` the missing files from Derecho to Izumi? It would also be good, in the future, to give `build-namelist_test.pl` the ability to check the repo for any missing files and download them—is that possible?

**Comment by briandobbins** [comment]
I think that helps - it sounds like there's a namelist test that I'm not familiar with, and which _checks_ for things (data files?), but doesn't by itself download them, so that likely fails if things aren't present.  Whereas actual runs would run a check_input_data command and download data, and that's highlighted files that we have on Derecho but aren't yet in the input data svn/ftp server?

If that's about right, I'm just thinking -maybe per Sam's latest comment- that we'd want to add something to the namelist test to download files, though the practicality of that might depend on how much data it involves. 

Ultimately, my thinking is I want someone who decided to contribute to our code to run the test suite locally, and have it 'just work', vs needing to be on Derecho / Izumi.  Again, not a near-term need, but something that's a good practice for the future.

**Comment by ekluzek** [comment]
Hmmm. You are right about rsync, being faster for my time, but using the download mechanism does ensure that the files are in the inputdata repo. So I feel like that's a useful benefit. And there are tons of old files that aren't needed that rsync will copy over. So just bringing the files that are in the XML database seems better to me.

We could add some capability to download files for this. But, I also want to deprecate this perl code and get something better/modern/maintainable/usable in place.

I do personally depend on the namelist testing for making and verifying namelist modifications. As well as making sure consistency error checking is done for namelist setttings. So I think it's a vital tool, but it needs to be redone. Not, just refactored, but redone.

And @briandobbins you are correct this is a little known testing tool for CTSM namelist, and it doesn't do the download step. But, I only expect the CTSM SE to run the namelist test right now. With a better replacement we might start expecting others to use it, but not the current version.

**Comment by ekluzek** [comment]
I've downloaded and now this works on izumi in ctsm5.2.003.
