### ISSUE TITLE
Update documentation for git-fleximod

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2536]
Replace `checkout_externals` instructions with those for `git-fleximod`.

`git grep -i 'checkout_ext'`
returns the following list of files, though I have omitted here files from the /manage_externals directory that seem unnecessary in addressing the present issue:

- [x] Replace README_EXTERNALS.rst with new equivalent
- [x] bld/CLMBuildNamelist.pm
- [x] doc/README.CHECKLIST.master_tags
- [x] doc/build_docs
- [x] doc/design/python_script_user_interface.rst
- [x] doc/source/lilac/obtaining-building-and-running/obtaining-and-building-ctsm.rst
- [x] doc/source/lilac/specific-atm-models/wrf.rst
- [x] manage_externals/README.md and manage_externals/README_FIRST to be replaced with .lib/git-fleximod/README.md from #2443 
- [x] python/ctsm/site_and_regional/run_neon.py
- [x] tools/mksurfdata_esmf/README.md

Some of the above is not documentation. There may exist other issues/PRs that address those files.
Rerun the git grep command later to confirm that I didn't miss something.

Definition of DONE:
- [x] Update documentation in above list of files as needed (see list above, currently in review)
- [x] Update documentation in wiki; in particular:
- [x] https://github.com/ESCOMP/CTSM/wiki/Protocols-on-updating-FATES-within-CTSM
- [x] https://github.com/ESCOMP/CTSM/wiki/CTSM-Quickstart-Guide-for-Users
- [x] https://github.com/ESCOMP/CTSM/wiki/Directions-for-editing-CLM-documentation-on-github-and-sphinx
- [x] https://github.com/ESCOMP/CTSM/wiki/Quick-start-to-CTSM-development-with-git
- [x] https://github.com/ESCOMP/CTSM/wiki/System-Testing-Guide

**Comment by samsrabin** [comment]
In a README file but also probably on the wiki.

**Comment by slevis-lmwg** [comment]
@jedwards4b another TODO in this issue is to update the relevant documentation in the Wiki. Have you started working on that? Please let me know, because I was asked to work on it.

**Comment by jedwards4b** [comment]
No, I'm not aware of a wiki
