### ISSUE TITLE
Update manage_externals to git-fleximod in run_sys_tests

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2537]
Needed so it doesn't crash when we move to `git-fleximod` (#2559).

**Comment by ekluzek** [comment]
In #2559 git-fleximod outputs status to fleximod_status now. So this information is still there as it was before, which can be really helpful to confirm you tested with the submodules you thought you did.

**Comment by slevis-lmwg** [comment]
I looked at SRCROOT_GIT_STATUS and confirmed no change in submodules since I ran tests.
