### ISSUE TITLE
Do we need transient support for ne30np4 in addition to ne30np4.pg3? -- answer NO

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2549]
### Brief summary of bug

In the CESM3 grids document, we list transient support for ne30pg3 but NOT plain ne30np4.

https://docs.google.com/spreadsheets/d/1Osq56e423CF107zhoNQ0VS7-iH_JXLF9AtCvBdXyfJ4/

However CAM currently has a test for it...

ERP_Ln9.ne30_ne30_mg17.FCnudged.derecho_intel.cam-outfrq9s

which fails.

### General bug information

**CTSM version you are using:** ctsm5.2.005

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** ne30_ne30_mg17 with CLM50 for Hist compsets

### Important output or errors that show the problem

```
err=ERROR : CLM build-namelist::CLMBuildNamelist::add_default() : No default value found for flanduse_timeseries.
            Are defaults provided for this resolution and land mask?
```

**Comment by ekluzek** [comment]
@cacraigucar do we need transient support for both of these ne30 resolutions? If so we can add it to the document and bring in the dataset. If not, I'd like to close this as a wontfix.

**Comment by cacraigucar** [comment]
@peterjlauritzen and/or @adamrher will need to answer this question, as I don't know.

**Comment by adamrher** [comment]
This and issue https://github.com/ESCOMP/CTSM/issues/2547 makes clear that in the grid doc, we haven't thought about whether "Continue CLM Support" discontinues support for configurations that are currently being tested in CAM ("CAM test" column).

I think we are going to resolve the ne30 failure by changing it to a ne30pg3 test, same as proposed for https://github.com/ESCOMP/CTSM/issues/2547. I am going open a CAM issue for these two test failures.

**Comment by ekluzek** [comment]
Closing as a wontfix
