### ISSUE TITLE
Failing PEM (PE layout change test) in ctsm5.2.005

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2553]
### Brief summary of bug

The test PEM_D_Ld9.ne30pg3_t232.I1850Clm60BgcCropG.derecho_intel.clm-clm60cam6LndTuningMode  passed in ctsm5.2.004, but fails in ctsm5.2.005.

FAIL PEM_D_Ld9.ne30pg3_t232.I1850Clm60BgcCropG.derecho_intel.clm-clm60cam6LndTuningMode COMPARE_base_modpes

### General bug information

**CTSM version you are using:** ctsm5.2.005
**Does this bug cause significantly incorrect results in the model's science?** No
**Configurations affected:** only pelayout change for ne30pg3_t232 grid?

### Details of bug

Looks like this is just a CISM answer change on processor change the same as #2542.
Answers changed between ctsm5.2.004 and ctsm5.2.005 and might have shifted enough that this now fails, so it just
exposed an existing issue.

### Important output or errors that show the problem

```
grep RMS /glade/derecho/scratch/erik/tests_ctsm525acl/PEM_D_Ld9.ne30pg3_t232.I1850Clm60BgcCropG.derecho_intel.clm-clm60cam6LndTuningMode.GC.ctsm525acl_int/run/PEM_D_Ld9.ne30pg3_t232.I1850Clm60BgcCropG.derecho_intel.clm-clm60cam6LndTuningMode.GC.ctsm525acl_int.cism.gris.initial_hist.0001-01-01-00000.nc.base.cprnc.out
 RMS beta_internal                    7.8639E-09            NORMALIZED  1.0968E-10
 RMS iareag                           6.3477E-03            NORMALIZED  3.8147E-15
 RMS total_gl_flux                    8.2266E-06            NORMALIZED  1.3137E-11
 RMS uvel                             3.0215E-12            NORMALIZED  8.2006E-10
 RMS vvel                             2.4100E-12            NORMALIZED  1.1141E-09
tests_ctsm525acl/PEM_D_Ld9.ne30pg3_t232.I1850Clm60BgcCropG.derecho_intel.clm-clm60cam6Lnd
```

**Comment by wwieder** [comment]
@slevis-lmwg will check the PEM tests to see how to deal with this (expected fail vs. get rid of the G)

**Comment by slevis-lmwg** [comment]
> @slevis-lmwg will check the PEM tests to see how to deal with this (expected fail vs. get rid of the G)

...as part of PR #2539 which is where I encountered this test failure.

**Comment by slevis-lmwg** [comment]
I now think that the present issue may be redundant. I have found the following:
1) We thought that the test passed in ctsm5.2.004, but this test didn't exist in ctsm5.2.004
2) The test that passed didn't have the G
3) The G was added in ctsm5.2.005 and the test was already labeled EXPECTED FAILURE due to #2542 
4) However, there was a typo in ExpectedFailures, so I did not get the EXPECTED FAILURE message in my testing
5) I'm fixing the typo in my PR #2539 

@ekluzek I will let you decide whether to close this issue.

**Comment by ekluzek** [comment]
Ahhh, very good. Thanks @slevis-lmwg for the analysis. We only have a few tests at ne30 for this compset, and I think we should keep them around. So let's leave it like it is.

So closing as a wontfix.
