### ISSUE TITLE
checkout_externals fails with "unable to find" 

### ISSUE THREAD

**Issue by BradleyMorgan** [ESCOMP/ctsm#256]
Main output...

./manage_externals/checkout_externals 
Processing externals description file : Externals.cfg
Processing externals description file : Externals_CISM.cfg
Processing externals description file : Externals_CLM.cfg
Checking status of externals: cism, source_cism, clm, fates, ptclm, mosart, cime, rtm, 
Checking out externals: cism, clm, mosart, cime, 
ERROR: Failed with output:
    error: unable to find 82930617b1428b1a4eec84997fc895da3dc5b276
    fatal: object 82930617b1428b1a4eec84997fc895da3dc5b276 not found

ERROR: In directory
   ~/build/clm5.0/cime
Process did not run successfully; returned status 128:
    git fetch --tags origin
See above for output from failed command.
Please check the log file manage_externals.log for more details.

manage_externals.log indicates the error occurs in the git fetch in <trunk>/clm5.0/cime

cd clm5.0/cime
git fetch --tags origin --verbose
remote: Counting objects: 56, done.
remote: Compressing objects: 100% (5/5), done.
Unpacking objects: 100% (56/56), done.
remote: Total 56 (delta 1), reused 1 (delta 1), pack-reused 50
From https://github.com/CESM-Development/cime
 = [up to date]      2.0.0      -> 2.0.0
 = [up to date]      2.0.1      -> 2.0.1
 = [up to date]      2.0.2      -> 2.0.2
 = [up to date]      billsacks/always_glcmec_n01 -> billsacks/always_glcmec_n01
 = [up to date]      billsacks/always_glcmec_n02 -> billsacks/always_glcmec_n02
 = [up to date]      billsacks/always_glcmec_n03 -> billsacks/always_glcmec_n03
 = [up to date]      billsacks/always_glcmec_n04 -> billsacks/always_glcmec_n04
 = [up to date]      billsacks/test_lvirtualglc_n01 -> billsacks/test_lvirtualglc_n01
 = [up to date]      cam_topographic_height_n01 -> cam_topographic_height_n01
 = [up to date]      cam_topographic_height_n02 -> cam_topographic_height_n02
 = [up to date]      cesm-master -> cesm-master
 = [up to date]      cime-workflow-exp-rc01 -> cime-workflow-exp-rc01
 = [up to date]      cime-workflow-exp0.0.1 -> cime-workflow-exp0.0.1
 = [up to date]      cime0.1.0  -> cime0.1.0
 = [up to date]      cime0.1.1  -> cime0.1.1
 = [up to date]      cime0.1.2  -> cime0.1.2
 = [up to date]      cime0.1.3  -> cime0.1.3
 = [up to date]      cime0.1.4  -> cime0.1.4
 = [up to date]      cime0.1.5  -> cime0.1.5
 = [up to date]      cime0.1.6  -> cime0.1.6
 = [up to date]      cime0.1.7  -> cime0.1.7
 = [up to date]      cime0.1.8  -> cime0.1.8
 = [up to date]      cime0.1.9  -> cime0.1.9
error: unable to find 82930617b1428b1a4eec84997fc895da3dc5b276
fatal: object 82930617b1428b1a4eec84997fc895da3dc5b276 not found

**Comment by billsacks** [comment]
What git version are you using? Can you try running `git --version`? We've had problems like this with older versions of git (before version 1.8, I think), and I'm wondering if that's the problem here.

**Comment by BradleyMorgan** [comment]
Yeah, we are on a fairly old Linux distro and the system git is a bit old ... 1.7.1.   I did a custom install of git 2.7.1 and checkout_externals completed successfully.   I'll go ahead and close this issue.  Thanks!
