### ISSUE TITLE
NOANTHRO qualifier NOT working in ctsm5.2.005 for CLM51 physics (only for CLM50 or CLM60)

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2561]
### Brief summary of bug

This is from Jiang in the Paleo group:

> Please note that run 091 is using CLM51%BGC-CROP in its compset. Based on that, my LGM simulation is using CLM51%SP-NOANTHRO.

### General bug information

**CTSM version you are using:** ctsm5.2.005 (in cesm2_3_beta17)

**Does this bug cause significantly incorrect results in the model's science?** Yes

**Configurations affected:** CLM51%SP-NOANTHRO
### Important output or errors that show the problem

> See here
> /glade/campaign/cesm/cesmdata/cseg/runs/cesm2_0/b.e23_alpha17f.BLT1850.ne30_t232.091
> /glade/u/home/jiangzhu/cesm/cases/b.e23.BLT1850.ne30pg3_t232.cesm2_3_b17.21ka.01

**Comment by ekluzek** [comment]
The problem is here:

https://github.com/ESCOMP/CTSM/blob/master/cime_config/config_component.xml#L205-L206

where NOANTHRO is only defined for CLM50 and CLM60.

What we should setup is a way for options that are NOT defined to trigger an error and abort.

**Comment by ekluzek** [comment]
The same kind of problem shows up for DV and VIC for the setting of: CLM_BLDNML_OPTS, and for CLM_USER_MODS for CMIP6 and WACCMCMIP6 and FATES-SP.

For LND_TUNING_MODE invalid settings set an invalid value and hence die with an error. We should do something similar for these. 

There's also some restrictions to configuration setup for description at the top that would catch certain issues -- but NOT all of them.

**Comment by ekluzek** [comment]
This will be resolved in terms of NOANTHRO with #2379

**Comment by wwieder** [comment]
will be resolved in #2808
