### ISSUE TITLE
Fix or disable "Assign to High Priority project" workflow

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2562]
It's failing every time now with the error "GITHUB_TOKEN not defined" ([e.g.](https://github.com/ESCOMP/CTSM/actions/runs/9274778629)). I wouldn't care except for the emails I get every time it fails!

**Comment by ekluzek** [comment]
Yeah, I agree the emails are annoying. Turning it off for now seems like a good thing to do. It can be added back in later when it can be figured out.

Could you do a simple PR to b4b-dev that turns it off?
