### ISSUE TITLE
Quick start wiki not accurate for git-fleximod

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#2574]
The instructions on the [wiki's quick start](https://github.com/ESCOMP/CTSM/wiki/CTSM-Quickstart-Guide-for-Users) don't work as provided for the CLM5 release code.  is this something that still needs to be updated on release branches?

Those provided on the [developers wiki page](https://github.com/ESCOMP/CTSM/wiki/Quick-start-to-CTSM-development-with-git), which pulls from master, do work fine.

**Comment by slevis-lmwg** [comment]
@wwieder good point, I went through and updated the instructions without regard to model version. I can reverse the changes here with a comment that starting with ctsm5.2.007 use the new instructions.

**Comment by slevis-lmwg** [comment]
Pls let me know if you catch more instances of this...

**Comment by ekluzek** [comment]
FYI: I did a "git grep" on a clone of the wiki github.com:ESCOMP/CTSM.wiki (note the .wiki rather than .git), and this was the only file I saw.
