### ISSUE TITLE
Stop using the "subname" pattern and use ErrMsg instead

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2582]
I was about to add the old pattern using subname to give the name of a subroutine in an error message, when I realized that use of ErrMsg is just an all around better method.

In code we have patterns like this...

``` fortran
    character(len=*), parameter :: subname = 'create_soil_water_retention_curve'
.
.
.
       write(iulog,*) subname//' ERROR: unknown method: ', method
       call endrun(msg=errMsg(sourcefile, __LINE__))
```

There is nothing in subname that you don't get from the errMsg which gives the filename (even if changes) and the line number even as it changes. subname is a constant that has to be maintained if the subroutine changes name. And hence adds more maintenance with refactoring.

So what we should move to is simpler like this:

``` fortran

       write(iulog,*) ' ERROR: unknown method: ', method, errMsg(sourcefile, __LINE__)
       call endrun(msg="unknown method")
```

(I suggest putting the errMsg in the write statement which will make it easier to test the error condition
in PfUnit unit testing).

So in the above:
- For new code leave off defining and using subname in new work
- For old code if you are updating it remove the subname and just make sure errMsg is used
- Technically we could change this everywhere, but I don't think it's worth the time -- but we might as well go to the new pattern for new code and code that's changing

**Comment by samsrabin** [comment]
CTSM SE meeting today: If you see this in code you're already modifying, go ahead and change it. We don't need to systematically change this throughout the codebase, though.
