### ISSUE TITLE
need to update mosart_in file

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CTSM#2589]
### Brief summary of bug
mosart1.1.01 removes the rtm prefix from a number of variables. 

### General bug information
File ctsm/lilac/bld_templates/mosart_in will need to be updated to work

**CTSM version you are using:** None, until mosart1.1.01 is used

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** when using LILAC with mosart1.1.01

**Comment by ekluzek** [comment]
Blocker for #2590

**Comment by ekluzek** [comment]
@jedwards4b thanks for figuring this out for us!

**Comment by jedwards4b** [comment]
@ekluzek I have to disagree that a lilac issue is a blocker for cesm.

**Comment by ekluzek** [comment]
@jedwards good point. It is an easy thing to fix that can happen as part of #2590. You are right this isn't required, but something that might as well be done at that time. If it turns out there's some reason it causes trouble, we can move forward with it being broken and fix it later.

**Comment by ekluzek** [comment]
ctsm5.2.015 took care of this.
