### ISSUE TITLE
matrixcn does not work with nrepr != 1 (number of crop reproductive pools)

### ISSUE THREAD

**Issue by slevis-lmwg** [ESCOMP/CTSM#2621]
For now aborting when matrixcn is .true. and nrepr != 1.

The [original post](https://github.com/ESCOMP/CTSM/pull/640#issuecomment-1084926867) suggested using a fixed index for matrix. I don't know what that means, and I will not pursue it at this point. We can decide in this issue how to follow up.

**Comment by ekluzek** [comment]
Yes, @slevis-lmwg ignore the bit about a fixed index. That doesn't make sense to me either, and I'm the one that said that. I think I might have meant to make it a parameter for matrix -- but you can't actually do that. The important thing is to add the check and have it abort.
