### ISSUE TITLE
Unit testing is failing in cesm tags since cesm2_3_beta17

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2655]
### Brief summary of bug

If you run the PF unit tests under src directory for a CESM tag since cesm2_3_beta17 -- they fail.

### General bug information

**CTSM version you are using:** cesm3_0_alpha02a (but also see in cesm3_0_alpha01a and cesm2_3_beta17)

**Does this bug cause significantly incorrect results in the model's science?** No
**Configurations affected:** PF unit tests

### Details of bug

``` shell
cd components/clm/src
git clone --origin escomp -b cesm3_0_alpha02a $ESGITHUBS/CESM.git cesm3_0_alpha02a
```

### Important output or errors that show the problem

```
-- Check for working Fortran compiler: /glade/u/apps/derecho/23.09/spack/opt/spack/ncarcompilers/1.0.0/oneapi/2023.2.1/6q5s/bin/ifort - skipped
-- Cray Programming Environment 2.7.23 C
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /glade/u/apps/derecho/23.09/spack/opt/spack/ncarcompilers/1.0.0/oneapi/2023.2.1/6q5s/bin/icx - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Python: /glade/u/apps/derecho/23.09/opt/view/bin/python3.10 (found version "3.10.12") found components: Interpreter 
CMake Error at CMakeLists.txt:19 (add_subdirectory):
  add_subdirectory given source "../share/src" which is not an existing
  directory.


CMake Error at CMakeLists.txt:20 (add_subdirectory):
  add_subdirectory given source "../share/unit_test_stubs/util" which is not
  an existing directory.


CMake Error at CMakeLists.txt:21 (add_subdirectory):
  add_subdirectory given source "../share/src/esmf_wrf_timemgr" which is not
  an existing directory.


-- Configuring incomplete, errors occurred!' from dir '/glade/derecho/scratch/erik/cesm3_0_alpha02a/components/clm/src/unit_tests.temp/__command_line_test__/__command_line_test__'
```

**Comment by ekluzek** [comment]
Looks like one issue is that it assumes a CTSM standalone path for externals rather than a CESM path with for example:

``` cmake
set(CLM_ROOT "..")

# Add source directories from other share code (csm_share, etc.). This should be
# done first, so that in case of name collisions, the CLM versions take
# precedence (when there are two files with the same name, the one added later
# wins).
add_subdirectory(${CLM_ROOT}/share/src csm_share)
```

This may not be important to fix, but then we should remove the instructions in the README file that say how to run it in CESM tags. 

Since, submodules are often different in CESM tags there does seem some utility in having this work in CESM tags. And since the CESM tags are of most important it's useful to be able to show everything that works in CTSM standalone also works in CESM.

**Comment by ekluzek** [comment]
As a natural consequence of this -- that means that we couldn't add FUNITCTSM_P1x1 tests to the CESM test lists: prealpha nor prebeta.

**Comment by wwieder** [comment]
unit tests aren't run in CESM tags, so we won't fix this.
