### ISSUE TITLE
Test build failure: SMS_P128x1_Lm25.f10_f10_mg37.IHistClm60BgcCrop.izumi_nag.clm-RxCropCalsAdaptGGCMI

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2659]
### Brief summary of bug

For some reason this test build fails in my #2593 branch. Other nag tests work fine.

### General bug information

**CTSM version you are using:** Commit aeb41823 on my #2593 branch.

**Does this bug cause significantly incorrect results in the model's science?** No

### Important output or errors that show the problem

```
Panic: /home/samrabin/ctsm_scale-mat-reqs-pr2-ggcmiseas/src/fates/parteh/PRTAllometricCNPMod.F90: Unexpected expr node type 432
Internal Error -- please report this bug
Abort
gmake: *** [PRTAllometricCNPMod.o] Error 3
```

**Comment by samsrabin** [comment]
Just wanted to confirm that this happens after having merged, as of ctsm5.2.018. I think it would make sense to wait until after the next FATES update to see if that fixes anything.

**Comment by ekluzek** [comment]
@samsrabin actually this is an existing problem when we try to run without DEBUG on for the NAG compiler. So we should just change the test so that it as a _D in the test name.

We couldn't figure out the problem, so we just resigned ourselves to ALWAYS use DEBUG on for Nag on Izumi.

**Comment by samsrabin** [comment]
Yup, just saw that issue: #1129. Should I go ahead and submit a PR to b4b-dev doing that?

**Comment by ekluzek** [comment]
See #1129 for some discussion on tis.

**Comment by ekluzek** [comment]
Fixing this on b4b-dev would be great. Thanks!
