### ISSUE TITLE
1x1_cidadinhoBR tests fail in build-namelist_test.pl

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2666]
### Brief summary of bug

1x1_cidadinhoBR tests fail in `build-namelist_test.pl`.

### General bug information

**CTSM version you are using:** ctsm5.2.016

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** n/a

### Details of bug

Fine; that resolution isn't used by anything yet.

### Important output or errors that show the problem

```
862/3314 < FAIL> <Test Id: 862> <Desc: -bgc bgc -crop -res 1x1_cidadinhoBR -use_case 1850_control -envxml_dir . clm4_5-bgc: lnd_in file exists>
1273/3314 < FAIL> <Test Id: 1273> <Desc: -bgc bgc -crop -res 1x1_cidadinhoBR -use_case 1850_control -envxml_dir . clm5_0-bgc: lnd_in file exists>
1684/3314 < FAIL> <Test Id: 1684> <Desc: -bgc bgc -crop -res 1x1_cidadinhoBR -use_case 1850_control -envxml_dir . clm5_1-bgc: lnd_in file exists>
2095/3314 < FAIL> <Test Id: 2095> <Desc: -bgc bgc -crop -res 1x1_cidadinhoBR -use_case 1850_control -envxml_dir . clm6_0-bgc: lnd_in file exists>
```

**Comment by ekluzek** [comment]
This is failing because we only have present day surface dataset files for cidadinhoBR, and these tests ask for 1850. So we either need to change the tests to do 2000_control, or add 1850 surface dataset files for cisadinhoBR.
