### ISSUE TITLE
Add tag version to the netcdf header of files created by subset_data

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2669]
subset_data doesn't save the tag of the CTSM version that was used to create a new file. The potential concern here is being able to reproduce a dataset that was created without knowing the version that was used.

From looking at $CSMDATA/lnd/clm2/surfdata_esmf/surfdata_1x1_cidadinhoBR_hist_2000_78pfts_c240613.nc it saves the following:

```
		:Created_on = "2024-06-13" ;
		:Created_by = "samrabin" ;
		:Created_with = "./subset_data -- 7099fc9ff" ;
		:Created_from = "/glade/campaign/cesm/cesmdata/cseg/inputdata/lnd/clm2/surfdata_esmf/ctsm5.2.0/surfdata_0.9x1.25_hist_2000_78pfts_c240216.nc" ;
```

I can't find the hash it mentions under "Create_with". The most critical thing is the last line where it gives the surface dataset it was starting from, which does have a version for it.

Since, subset_data just overrides a few fields as the user specifies, it's also possible we don't need the tag of subset_data in order to replicate a given file. So perhaps this is not important to do.

**Comment by samsrabin** [comment]
It's possible that hash is from a branch I ended up abandoning or rebasing.

**Comment by wwieder** [comment]
There doesn't seem to be anything wrong with subset data here, and since there is metadata from the source of the surface data
