### ISSUE TITLE
Catch use of namelist attribute in failure testing in perl build-namelist tester

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2673]
Until #585 happens a little bit of error checking added to the failure and warning testing in ./build-namelist_test.pl could really help us with adding new tests. These tests set a hash, with options, namelst, phys, and XML variable names. If any of those are misspelled (with the misspelled namelist attribute namelst being particularly easy thing to miss) -- the test won't function correctly. But, just adding error checking to ensure the expected things are set would catch this for developers and make adding a new test much easier.

Also change namelst to namelist would also help as well.

**Comment by mvdebolskiy** [comment]
@ekluzek I haven't change the `namelst`. The error will give the spelling though.
