### ISSUE TITLE
CMIP6 output

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#268]
- [ ] NFIX_TO_SMINN: Will notes that this variable is only applicable for CLM4 and CLM4.5 so maybe should be turned off for CLM5?

- [ ] FROOTC_ALLOC reported, should there also be coarse root carbon allocation?  Look into whether COARSE ROOT could be archived.  Above and below ground liter, new variable from vertically resolved, 10cm?

- [ ] Stem respiration requested for CMIP6, not reported?

- [ ] Water table depth, create a new variables that combines ZWT_PERCH, ZWT and sets to missing value where no saturated portion of soil?

- [ ] Heat flux into snow in Eday

- [ ] Stomatal conductance maximum daily

- [ ] SLASH needs to be added both at patch and grid cell level?

**Comment by billsacks** [comment]
@dlawrenncar @ekluzek - If I'm reading the cmip6 tables right, it looks like there are a bunch of variables requested at daily frequency (e.g., those in the Eday sheet here: https://docs.google.com/spreadsheets/d/14bVnGtQpvK5XnaUn8IctuBTSnSWxDFZbwGYmd0K6GAI/edit#gid=153374762  - there may be others, too). Is that right? If so, it looks like we need to add another history tape for our cmip6 output: right now we just have 3 monthly tapes and an annual tape.

**Comment by billsacks** [comment]
It looks like some variables are being requested at even higher frequency, such as 6-hourly. At least some of these are land variables. But I could me misunderstanding the request.

**Comment by dlawrenncar** [comment]
@olyson I created a set of daily fields history tape that meets (most) of
the CMIP6 requirements.  Keith and I dug this list up as a template for the
daily output that we have been outputting for selected years for the CLM
release simulations.  We can double check that list and then we need to
discuss how to get this pulled in for CMIP6 simulations.  We didn't want to
add it to the standard user_mods CMIP6 output because we don't want to get
all these daily fields all the time because of the space and I/O issues.

**Comment by wwieder** [comment]
@ekluzek There are still issues with how NFIX_TO_SMINN is being calculated as a diagnostic, see also #426.  I'm not sure what's being done now, but it's not correct.

![](http://webext.cgd.ucar.edu/I20TR/i.e21.IHIST.f09_g17.CMIP6-land-hist.001/lnd/i.e21.IHIST.f09_g17.CMIP6-land-hist.001.1995_2014-clm50_r270_1deg_GSWP3V1_iso_newpopd_hist.1995_2014/set1/set1_NFIX_TO_SMINN.png)

For CLM5 @dlawrenncar recommended turning off NFIX_TO_SMINN, which for some reason (unclear to me) this is still an active field https://github.com/ESCOMP/ctsm/blob/a34404419aaa81f5021602963222c50daa10c0f6/src/soilbiogeochem/SoilBiogeochemNitrogenFluxType.F90#L319

**Comment by billsacks** [comment]
@dlawrenncar @wwieder should we close this old issue? I assume that it's too late at this point to do anything here that hasn't already been done?

**Comment by dlawrenncar** [comment]
Yes.  I think we have CMIP6 output as we want it now with our current
methods.
