### ISSUE TITLE
Make polarcap surface datasets in ctsm5.3.0, remove VR 1850 datasets

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2720]
Alongside #2716 we need to add creating 1979,1850,2000,1979-2026 surface datasets for the ne0.POLARCAP resolution. This means adding it to the ne0 and ne120 resolution list in the gen namelist multi script for mksurfdata_esmf.

As part of this we'll remove the 1850 VR datasets as they aren't planned to be needed by CAM as explained by @adamrher 

Definition of done:
- [x] Add polar grid to Makefile
- [x] Remove creation of 1850 files for VR grids (decided won't do, just won't import the 1850 datasets)

**Comment by wwieder** [comment]
Is this critical for a 5.3 milestone of does it just need to come in by the CESM3 release?

**Comment by ekluzek** [comment]
Always the right question to ask. In order to have a dataset for @adamrher to use in CTSM5.3 versions we might as well make it. It shouldn't be hard to add, unless we run into problems. So I suggest we do so unless it causes problems in making all the datasets. But, it's likely only needed by the release and not in 5.3.

**Comment by slevis-lmwg** [comment]
Confirming info listed here and in the [grids speadsheet](https://docs.google.com/spreadsheets/d/1Osq56e423CF107zhoNQ0VS7-iH_JXLF9AtCvBdXyfJ4/edit?gid=584342654#gid=584342654):
- no 1850
- yes 1979, 2000, 1979-2026 
- same for ne0np4.ARCTICGRIS.ne30x8, ne0np4.ARCTIC.ne30x4, ne0np4CONUS.ne30x8, ne0np4.POLARCAP.ne30x4

**Comment by adamrher** [comment]
Yes, that's correct @slevis-lmwg. I noticed however that CONUS only has finidat entries for year 2013. Perhaps we can just replicate the POLARCAP finidat entries for CONUS?

**Comment by slevis-lmwg** [comment]
Let's confer with @ekluzek on that.

@ekluzek does the finidat discussion go under #2558 or other similar issue?

**Comment by slevis-lmwg** [comment]
From meeting with @ekluzek 
Current Makefile generates 1850 fsurdat files for VR grids.
We decided to not mess with the scripts at this time and just not ./rimport the four 1850 fsurdat files.
We can leave this issue open as a reminder to correct gen_mksurfdata_jobscript_multi.py code later.
