### ISSUE TITLE
Version string on CTSM surface datasets to check for compatability

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2723]
CTSM5.3.0 datasets will NOT be compatible with CTSM5.2.0 datasets. In CTSM5.2.0 which had a similar problem, we handled this by checking for existence of the PCT_OCEAN field. In this case it won't be so easy to do a similar check. 

So that resurrects an idea we had for CTSM5.2....

> Another idea is to have a version string as a global attribute on the files to check for compatibility. If the string doesn't match what's expected then it dies with an error. This can then be updated anytime we have something that is NOT backward compatible.

_Originally posted by @ekluzek in https://github.com/ESCOMP/CTSM/issues/2218#issuecomment-1792919759_

**Comment by wwieder** [comment]
This is likely the most critical piece to be added, making sure we get the right surface data with the right version of the code. @ekluzek this is your top priority for remaining 5.3 milestones.

**Comment by slevis-lmwg** [comment]
The current error message when using a pre-5.3 dataset is posted here:
https://github.com/ESCOMP/CTSM/pull/2500#issuecomment-2319521923

**Comment by ekluzek** [comment]
Error message now looks like:

```
 Input surface dataset is: 
 /glade/work/erik/ctsm_worktrees/quickfix/cime/scripts/SMS_D_Ld1_PS.f09_g17.I185
 0Clm50Sp.derecho_intel.clm-default.20240830_132945_zua8jc/surfdata_0.9x1.25_sim
 yr1850_c130927.nc
This surface dataset is older than 4.5 and incompatible with this version of CTSM
Dataset version = 0.0 Version expected = 5.3
 ERROR in surfrdMod.F90 at line 106                                             
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                       
 ENDRUN:
 ERROR: ERROR: Incompatible surface dataset
```
