### ISSUE TITLE
debug and update in fire emission factors

### ISSUE THREAD

**Issue by lifang0209** [ESCOMP/CTSM#2734]
@samsrabin @ekluzek @wwieder We need set /glade/derecho/scratch/fangli/firedata/fire_emission_factors_78PFTs_c20240624.nc as the default fire emission factor file.
The emission factors for several trace gases in the current file created by Louisa (/glade/campaign/cesm/cesmdata/input data/and/clm2/fire data/fire_emission_factors_78PFTs_c20220111) are incorrect. For example, the CO2 emission factors for grass and shrub PFTs were incorrectly applied to temperate tree PFTs. 
 I've corrected this issue and updated the fire emission factor file for 44 trace gases and aerosols using data from Andreae (2019), Li et al. (2019), and Shahid et al. (2024).

**Comment by ekluzek** [comment]
Since this is just updating a file, this is an easy change to bring in. We'll rely on @lifang0209 having vetted that answers are correct with the changed file.

This will change answers for all tests with fire-emis on regardless of CLM physics version.

**Comment by wwieder** [comment]
Excellent.  Thanks for creating this issue and pointing to the new emissions factor file, @lifang0209 .  I suggest this come in with the other bug fixes suggested in #2728.  We need things to calm down from the code freeze and creation of the 5.3 tag before we'll have time to get to this.

As @ekluzek mentioned, we'll need some help evaluating new fire fluxes in *I* cases to make sure things look OK.  The first round of these historical simulations may be ready next week and we'll have a discussion on [LMWG-dev](https://github.com/NCAR/LMWG_dev) that I can alert you on.  It will be a bit longer before we have simulations with these requested updates ready.

**Comment by wwieder** [comment]
@samsrabin suggested making a PR to #2500 so this comes in on the 5.3 branch.  This seems pretty simple, so thanks for offering to do this.

**Comment by ekluzek** [comment]
OK I re-read the introduction and realize this is bringing in three updates:
- Bringing in the update to Louisa's file: fire_emission_factors_78PFTs_c20220111
- Fixing some minor problems in that file
- An update for fire-emission compounds based on the reference in the introduction

It sounds like all of them are potentially answer changing.

**Comment by lifang0209** [comment]
@ekluzek The difference between fire_emission_factors_78PFTs_c20220111 and /glade/derecho/scratch/fangli/firedata/fire_emission_factors_78PFTs_c20240624.nc is only Comp_EF (fire emission factors) in the two data files
