### ISSUE TITLE
Correct paths for surface datasets, esp NEON

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#2749]
### Brief summary of bug

It seems like with the addition of 5.3 surface datasets the paths to old surface datasets have now broken. 
This should be corrected early in the 5.3 tags.

### General bug information

**CTSM version you are using:** [output of `git describe`]
ctsm5.2.028

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]
no

**Configurations affected:** [Fill this in if known.]
currently running NEON cases (created with usermods_dirs) that point to the following path
 `/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/surfdata_esmf/NEON/surfdata_1x1_NEON_HARV_hist_2000_78pfts_c240206.nc`

This has now changed to the 5.3 surface data, which has a different creation date:
`/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/surfdata_esmf/NEON/surfdata_1x1_NEON_HARV_hist_2000_78pfts_c240908.nc`

Hopefully this is just a short term issue for people using older tags and usermods_dirs.

### Details of bug

Have not looked to see how other cases may be impacted here, but it's a good way to encourage people to use the 5.3 tag once it's created.

**Comment by slevis-lmwg** [comment]
I posted a similar comment in #2750:

I'm sorry about this confusion @wwieder and thank you for bringing to our attention.

@ekluzek and I decided to resolve this as follows:
- [x] I moved the original files back to where they used to be
- [x] I moved the new files to a ctsm5.3.0 subdirectory under the same path

I think this means that you may close this issue as fixed or add it to the issues to be closed by #2500.

**Comment by wwieder** [comment]
I'll close this here, but wanted to confirm that NEON user_mods will be corrected in #2500?

**Comment by slevis-lmwg** [comment]
Yes. We expect some of tests in the test-suites to fail initially for various user_mods and testmods that need updating. And I will make the updates in #2500.
