### ISSUE TITLE
Missing sa_leaf code from PPE branch in CanopyFluxesMod.F90

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#2777]
### Brief summary of bug

The PPE branch (latest tag being PPE.n16_ctsm5.1.dev030) had a change to sa_leaf in CanopyFluxesMod.F90 when biomass heat storage is on.  This didn't make it into the latest CTSM tag.

### General bug information

**CTSM version you are using:** ctsm5.2.028

**Does this bug cause significantly incorrect results in the model's science?** Maybe.  The code mod was put in place to improve survivability, but our survivability in the current model in general is pretty good so it may not have that much effect.  Although maybe it will improve our C4 grass which was at 58% survivability in a recent simulation.

**Configurations affected:** All with biomass heat storage on.

### Details of bug

The relevant code block that was in the last PPE tag is:

```
            if(.not.(is_tree(patch%itype(p)) .or. is_shrub(patch%itype(p))) &
                 .or. dbh(p) < min_stem_diameter) then
               frac_rad_abs_by_stem(p) = 0.0
               sa_stem(p) = 0.0
!KO
               sa_leaf(p) = sa_leaf(p) + esai(p)
!KO
            endif

```

The line bracketed by !KO is not in the current code.
My notes from January 2021 detail a conversation with @dlawrenncar and @swensosc in which we were trying to improve survivability with biomass heat storage on.  After various tests we came up with this modification: "For grasses and skinny trees/shrubs, add in esai to sa_leaf".  I believe it was added for the situation where elai could be zero and thus sa_leaf would be zero (sa_leaf is set equal to 2*elai in code above this).

**Comment by ekluzek** [comment]
@olyson thanks for pointing this out. I'm glad you did so we can bring it in. We thought we had everything, but good to get this last bit in as well.

It looks like this will have a small change to answers is that correct? The code change is simple, but we'll have to bring it in as part of an answer changing tag if so.

**Comment by olyson** [comment]
We should probably test this separately before bringing it in, but yes it should be part of an answer changing tag.  There is one other PPE-related code mod in CNVegStructMod.F90 that we'll need to test as well.  It may not have any effect, but I need to test it next week.  My opinion is that these shouldn't stop the CTSM5.3 tag, they could be part of the bug fix tags that come later, if @wwieder agrees.

**Comment by ekluzek** [comment]
Yes, this will NOT be part of ctsm5.3.0 -- but hopefully one of the quick follow on tags. Thanks for the update here.

Yes, if there are other changes you could test with it as well that sounds ideal. If you want to start testing now you could use the ctsm5.3.0 branch tag that Sam created for you yesterday.

**Comment by olyson** [comment]
I tested the sa_leaf change in 5 year I2000 cases:

/glade/work/oleson/ctsm5.3.n04_ctsm5.2.028/cime/scripts/ctsm53n04ctsm52028_f09_saleaf_2000
/glade/work/oleson/ctsm5.3.n04_ctsm5.2.028/cime/scripts/ctsm53n04ctsm52028_f09_2000

Diagnostics are here:

https://webext.cgd.ucar.edu/I2000/ctsm53n04ctsm52028_f09_saleaf/lnd/ctsm53n04ctsm52028_f09_saleaf_2000_2001_2004-ctsm53n04ctsm52028_f09_2000_2001_2004/setsIndex.html

The differences in JJA TLAI and GPP are pretty scattered and relatively small.  Mostly decreases in Asia, eastern Siberia, and western U.S., with increases in Alaska, northern Canada, and northern Europe.
We originally vetted this change with respect to survivability in 1850 spinups and eventually historical simulations, but I'm not we necessarily need to repeat that.
