### ISSUE TITLE
Github Action Automation for Release Pipelines

### ISSUE THREAD

**Issue by S-Panta** [ESCOMP/CTSM#2778]
I noticed that the release process for the project does not include any automated checksums (such as SHA-256 or MD5) for verifying the integrity of the assets. Including a cryptographic checksum could improve security by allowing users to verify the authenticity and integrity of the downloaded assets.

It looks like there is no separate pipeline currently automating the release process, but this could be implemented with just a few lines of code and a simple release pipeline in GitHub Actions. I'd be happy to contribute and set this up if this is considered useful!

Let me know what you think.

**Comment by wwieder** [comment]
wontfix
