### ISSUE TITLE
Error in FatescoldLandUse testmod

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2783]
### Brief summary of bug

Fails in:

ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdLandUse
ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.izumi_nag.clm-FatesColdLandUse

### General bug information

**CTSM version you are using:** ctsm5.3.0

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** FatesColdLandUse test mod

### Details of bug

The shell_commands file in the testmod has -i-clm_demand for CLM_BLDNML_OPTS rather than --clm_demand

### Important output or errors that show the problem

preview_namelist shows:

```
Create namelist for component clm
   Calling /glade/work/erik/ctsm_worktrees/answer_changes/cime_config/buildnml
WARNING: CLM is starting up from a cold state
ERROR: Command /glade/work/erik/ctsm_worktrees/answer_changes/bld/build-namelist failed rc=255
out=
err=Unknown option: i-clm_demand
Unknown option: flanduse_timeseries
SYNOPSIS
```

**Comment by glemieux** [comment]
I'll add a fix for this in #2700.

**Comment by glemieux** [comment]
@ekluzek using `./xmlchange CLM_BLDNML_OPTS="-clm_demand flanduse_timeseries" --append` I get the following error:
```
 60 2024-10-02 13:37:59: ERROR: Command /glade/u/home/glemieux/ctsm-test2/bld/build-namelist failed rc=255
 61 out=
 62 err=ERROR : CLM build-namelist::CLMBuildNamelist::add_default() : No default value found for flanduse_timeseries.
 63             Are defaults provided for this resolution and land mask?
```

Am I setting this correctly?

**Comment by ekluzek** [comment]
@glemieux yes you are testing it correctly. It's just we need a 16-pft landuse timeseries file for f45 that will work with FATES. The 78 pft one doesn't work with FATES.

So we need to add that to the list of files to support, create one, and add it to namelist_defaults. Sam Levis has  been working on these sorts of things. But, he's also out of office right now.

@glemieux is this the last thing holding you up? Should we talk about it today, or as part of tomorrows CTSM SE meeting?

**Comment by glemieux** [comment]
@ekluzek yes, technically it's holding up the final tests for the two fates PRs that are going to be integrated and come in with #2700.  

As a stop gap, could I manually revert back to the `ctsm5.2.0` 16 pft file or will that just crash in a different way?

**Comment by ekluzek** [comment]
Hmmm I expected using the old ctsm5.2.0 file would crash in a different way. If it works though maybe you can make progress on the tag, but there are a couple things to do still and do planning around. So we'll talk more tomorrow...
