### ISSUE TITLE
Potential typo/bug in EnergyFluxType.F90

### ISSUE THREAD

**Issue by cathyxinchangli** [ESCOMP/CTSM#2793]
### Brief summary of bug

[At Line 582](https://github.com/ESCOMP/CTSM/blob/a3459c54022057a2d5711c7fffdf5b3524623857/src/biogeophys/EnergyFluxType.F90#L582), when initializing the history field for EFLXBUILD, eflx_urban_ac_lun gets assigned spval, but it seems like it should be eflx_building_lun. 

### General bug information

**CTSM version you are using:** ctsm5.3.0

**Does this bug cause significantly incorrect results in the model's science?** I do not expect it to

**Configurations affected:** 

### Details of bug

I stumbled upon this today and I have not done any testing associated with it. If I should report this somewhere else or do any tests I will be happy to!

**Comment by olyson** [comment]
Yes, I agree, thanks @cathyxinchangli .  I will get it fixed.

**Comment by wwieder** [comment]
@olyson will add this to b4b-dev
