### ISSUE TITLE
Array elevclass_o in mksurfdata_esmf/src/mkglcmecMod.F90 is not allocated before use.

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#2802]
### Brief summary of bug

Allocatable array elevclass_o in mksurfdata_esmf/src/mkglcmecMod.F90 is not allocated before use.
I'm not clear though whether this statement effectively accomplishes that:
```
    elevclass_o(:) = elevclass(:)
```

### General bug information

**CTSM version you are using:** ctsm5.3.0

**Does this bug cause significantly incorrect results in the model's science?** Unknown

**Configurations affected:** Surface dataset creation.

### Details of bug

Reported by Yuan Sun (https://bb.cgd.ucar.edu/cesm/threads/mksurfdata_esmf-done-around-glcmec.9624/#post-57405)

**Comment by slevis-lmwg** [comment]
Testing on derecho:
PASS `qsub mksurfdata_jobscript_single_2000.sh` so as to compare today's output to that generated yesterday, now in `/glade/derecho/scratch/slevis/temp_work/new_rawdata/tools/mksurfdata_esmf/bkup_T42`
PASS `./run_ctsm_py_tests -s` and `./run_ctsm_py_tests -u`
PASS `make black` and `make lint`
PASS `build-namelist_test.pl`
IN PROGRESS aux_clm

**Comment by ekluzek** [comment]
Yes, my inspection shows this as a problem as well. It's an allocatable array that's neither allocated nor deallocated and hence a problem. Although the other thing is that it never seems to be used either. So the intel compiler on Derecho must be optimizing that bit of code out. And other compilers and/or maybe with lower optimization levels leave it in and have trouble when they get to it.

So yes something we should fix.

**Comment by YuanSun-UoM** [comment]
Yes, in my case, the current code works with openmpi but fails when using mpich.
