### ISSUE TITLE
ndep always sent from CAM or DATM now

### ISSUE THREAD

**Issue by mvertens** [ESCOMP/CTSM#2813]
Currently NDEP is always sent to the mediator from either CAM or DATM. However, CTSM is continuing to use  the call in lnd_import_export:
call shr_ndep_readnl("drv_flds_in", ndep_nflds)
However, datm is not setting the drv_flds_in variable for ndep and CAM only sets it when ndep is not read from a stream file.
It seems that at this point the shr_ndep_readnl should be deprecated in favor of ctsm always receiving the same value as would be sent to the ocean component from the atm.

**Comment by wwieder** [comment]
It looks like this is a duplicate of #1900?  If this is accurate maybe we can close one of the issues?

**Comment by wwieder** [comment]
I'll close this, since it's a duplicate of 1900, which has more notes, conversation.
