### ISSUE TITLE
build-namelist_test.pl: Add option to include only some tests

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2822]
build-namelist_test.pl takes a long time to run, which is annoying when you're trying to debug just one test. It would be nice to be able to pass a list of test names (or even better, a string with wildcards) that should be run.

**Comment by ekluzek** [comment]
This is correct thinking here. I'd like to see this update. But, we would really need to reimplement everything for this.

So closing as a duplicate of #92. Which probably should be closed as well, because we should reimplement this into python sys and unit tests in the python testing framework.
