### ISSUE TITLE
Rework handling of negative runoff: make MOSART / RTM responsible for doing this limiting

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#284]
**I'm moving this from a 2015-11-17 comment. I'm not sure if it's still relevant.**

@swensosc is adding some logic regarding the handling of negative runoff: If this would put VOLR below some spatially-variable threshold, then runoff is being routed directly to the ocean, rather than through the rivers. He is putting this limiter in CLM because it needs a temporal accumulator, which CLM has but RTM / MOSART do not.

We (CLM-CMT & Sean) agreed that, long-term, it would be better to make RTM & MOSART responsible for doing this limiting / routing of negative runoff themselves, rather than relying on CLM to figure it out on behalf of the river model.

**Comment by billsacks** [comment]
@swensosc is this still an open issue or has this been resolved?

**Comment by swensosc** [comment]
I think this is resolved in mosart.  Tony craig put in 'direct in place'
and 'direct to outlet' options so that negative runoff sent to mosart
(which can crash mosart) can bypass the normal river routing, and be sent
to the ocean  directly.

**Comment by billsacks** [comment]
Great, thanks. Closing this issue.
