### ISSUE TITLE
Add back the cn30 params file and test for it

### ISSUE THREAD

**Issue by slevis-lmwg** [ESCOMP/CTSM#2843]
`git grep -i cn30` returns
`cime_config/testdefs/testmods_dirs/clm/clm60_monthly_matrixcn_soilCN30/user_nl_clm:paramfile = '$DIN_LOC_ROOT/lnd/clm2/paramdata/ctsm60_params_cn30.c240822.nc'`
suggesting that we can remove this /testmods directory.

**Comment by ekluzek** [comment]
Adding notes I put in the CTSM chat space:

> That test came up in the context of testing for CN-Matrix where the matrix method failed for a high CN ratio. So we added a test to make sure that didn't break again. But, as @slevis-lmwg says we should make sure it's actually used in a test list and decide to either remove it or add it back in. In principle I think it is good to vary parameters in our testing to make sure the model works for the spectrum of values that might be used. But, I also wonder if this should be done varying more than just the one parameter, and maybe in a more systematic way...

The parameter file that goes with this just changes one parameter to 30 for a CN ratio. This is actually an example case where adopting the FATES on the fly conversion of the parameter file with the single change might make the most sense.

**Comment by slevis-lmwg** [comment]
I like that idea.

Also, an update:
Keith and I discussed this and decided that he will confirm the clm60...CN30 test works and will add it back to the testlist, as I have found no evidence that we removed this test intentionally. Keith is doing this as part of #2831.

**Comment by ekluzek** [comment]
Reviewing this today. This is done! Yay!
