### ISSUE TITLE
FATES will never start from specified finidat

### ISSUE THREAD

**Issue by mvdebolskiy** [ESCOMP/CTSM#2856]
### Brief summary of bug

When trying to run I2000Clm60FatesSpCruRsGs specifying `finidat=/path/to/finidat.nc`.

### General bug information

`namelist_defaults_overall.xml` sets `clm_start_type` to `cold`:
```perl=
<clm_start_type                use_fates=".true.">cold</clm_start_type>
```
which means that `CLMBuildNamelist.pm` in any fates run that is not branch or hybrid, you will hit this warning:
```perl
  my $var = "finidat";
  my $finidat = $nl->get_value($var);
  $nl_flags->{'excess_ice_on_finidat'} = "unknown";
  if ( $nl_flags->{'clm_start_type'} =~ /cold/ ) {
    if (defined $finidat ) {
      $log->warning("setting $var (either explicitly in your user_nl_clm or by doing a hybrid or branch RUN_TYPE)\n is incomptable with using a cold start" .
              " (by setting CLM_FORCE_COLDSTART=on)." );
      $log->warning("Overridding input $var file with one specifying that this is a cold start from arbitrary initial conditions." );
      my $group = $definition->get_group_name($var);
      $nl->set_variable_value($group, $var, "' '" );
    }
...
```

That makes it impossible to run not only that compset, but the coupled model with CLM[^_]*FATES ( you want it f.e. when you don't want to spinup the model every time you have added new things to the atmosphere)

**CTSM version you are using:** [output of `git describe`]
[ctsm5.3.009](https://github.com/ESCOMP/CTSM/releases/tag/ctsm5.3.009)

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]

Yes, if you pass -ignore-warnings to CLMBuildNamelist.pm, you will get acutally coldstart instead of finidat. And you will not see the warning for that, since when `-ignore-warnings` is not set, you don't see the second warning at all.

**Configurations affected:** [Fill this in if known.]

Any Fates configuration.

### Details of bug

Might be related to https://github.com/NGEET/fates/issues/1234

### Important details of your setup / configuration so we can reproduce the bug

`finidat='/not/an/empty/string'`

### Important output or errors that show the problem

[Fill this in with anything relevant that you haven't already noted; if there is nothing to add, delete this section.]

**Comment by wwieder** [comment]
This is an issue we need to address. @mvdebolskiy has a few ideas for how this could be done, but needs guidance / suggestions on where to fix this.  

@adrifoster noted this is likely related to #2670 (a symptom of the same issue)?

**Comment by samsrabin** [comment]
@ekluzek @mvdebolskiy Which do y'all prefer for non-FATES cases that are cold start but have finidat specified:
1. Warn and say that `-ignore_warnings` will set `finidat = ''`
2. Throw an error (i.e., require the user to remove the finidat specification)

**Comment by mvdebolskiy** [comment]
2nd  option.
