### ISSUE TITLE
For mksurfdata_map: use maps with no source masking, applying mask separately

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#286]
@swensosc suggested this 2015-10-19, and it seems like a good idea to me: When mapping files from their raw data grid to CLM resolutions, we could use maps with no source masking, and then apply the mask in a separate step.

We currently have a LOT of mapping files from the mksurfdata_map raw data files to the CLM grids. Much of the reason we have so many is that we have a separate set of mapping files for each raw data mask - e.g., even if many of the raw data files are at the same 3' resolution, we need different mapping files for the different masks.

Sean pointed out that we should be able to use mapping files without masks, and then tweak the mapping algorithms to apply the source masks separately. I think we do things like that in other parts of CESM (e.g., in the coupler?). This would greatly reduce the number of mapping files we need to maintain. Furthermore, if a raw dataset is updated, and this update involves changing the mask, you wouldn't need to remake mapping files. (This was Sean's original motivation, as he is updating the lake dataset in this way.) Instead, mksurfdata_map would simply read the mask off of the (updated) raw data file.

**Comment by ekluzek** [comment]
My understanding of how the ESMF regridding works is that this isn't something that you can do. But, I could be wrong. The mapping files created have the masks inherently embedded into them. I don't know of an easy way to extract them out. You could assume without a mask, but that means when you run the mapping you will be averaging in data that is outside the mask. That's the thing that I think we want to ensure doesn't happen.

I don't really think the burden is that high for carrying around files at the same resolution, but multiple masks. Right now there are three half degree, five 3x3 minute, and 2 10x10 minute grids. So you'd have some speedup with this, but still the 1km-merge-10min_HYDRO1K-merge-nomask grid is the one that far and away takes the most time.

**Comment by billsacks** [comment]
@ekluzek Unless I'm overlooking something: You _can_ have masks embedded in the grid files when creating the mapping files, but you don't have to. If you don't, then you need to do a bit more work in the mapping routine, but we actually already have code in place to do this: `gridmap_areaave_srcmask` in `mksurfdata_map`. This is used when the source mask isn't known ahead of time.

You may be right that the burden isn't that high for the different grid files, but the burden is higher for the combinatoric mapping files. I know we've talked about moving away from storing all of them eventually, though.

In the end, I don't have strong feelings about whether this should be done. I think it's a good idea, but I'm not sure if it gains us enough to be worth the development time.

**Comment by mvertens** [comment]
I think the right approach is to create these mapping files on the fly -
and not store them. I had demonstrated that this was feasible and showed
acceptable performance by simply translating the input format of the input
grid files. Only one file did not work well with this. I think that this is
the approach that should be pursued rather than still working with storing
mapping files.

**Comment by billsacks** [comment]
@mvertens I don't disagree. However, I'll point out that doing this suggestion could actually help at least as much if we're generating mapping files on the fly, because we'd only need to generate, say, 1/2 or 1/3 as many mapping files.

**Comment by ekluzek** [comment]
@mvertens as @billsacks says, yes, if that line of development (to create mapping files for mksurfdata_map on the fly) is taken up again, this change should happen along with it. It'll both shorten the time to make the mapping files and as @billsacks pointed out minimize how many are required. If we go to a paradigm of creating them on the fly, you want to create as few as possible as fast as possible. The time to create them needs to be sufficiently short though, to make that the standard mechanism.

**Comment by slevisconsulting** [comment]
Notes from my Feb 2019 Boulder visit:

The discussion focused on leveraging existing esmf capabilities. The conversation is ongoing via email between Bill S and Ben Koziol, Erik K, Mariana, Negin, Mike B, Rocky Dunlap...

A major incentive for pushing this issue forward is Mike B's NWP workflow. So here are Mike B's workflow notes for running NWP. **I will work with these notes to gain familiarity:**

`===================================================================
CTSM NLDAS test on cheyenne (new github version)
===================================================================

1. Check out code (you should already have this locally, if not):

git clone https://github.com/barlage/ctsm.git
cd ctsm
./manage_externals/checkout_externals
  
###2. Link generic and specific input data (only needed once until scratch gets purged)
###
###[run from old cesm script]
###
###/glade/u/home/barlage/src/cesm/cesm1_2_2/scripts/link_dirtree /glade/p/cesm/cseg/inputdata /glade/scratch/barlage/cesm/inputdata
###
###Copy domain files:
###
###cp /glade/work/barlage/ctsm/nldas_grid/gen_domain_files/*.nc /glade/scratch/barlage/cesm/nldas
###
###Copy map files:
###
###mkdir /glade/scratch/barlage/cesm/inputdata/lnd/clm2/mappingdata/maps/nldas
###cp /glade/work/barlage/ctsm/nldas_grid/map/*.nc /glade/scratch/barlage/cesm/inputdata/lnd/clm2/mappingdata/maps/nldas/
###
###Copy surface data files:
###
###cp /glade/work/barlage/ctsm/nldas_grid/surfdata_nldas/*.nc /glade/scratch/barlage/cesm/inputdata/lnd/clm2/surfdata_map/

3. Create newcase; this will create /scripts/nldas_test directory

cd cime/scripts
./create_newcase --project P48500028 --case nldas_test --mach cheyenne --res CLM_USRDAT --compset I2000Clm50SpGs --run-unsupported

cd nldas_test/
./xmlchange DIN_LOC_ROOT=/glade/p/cesm/cseg/inputdata
./xmlchange ATM_DOMAIN_PATH=/glade/work/barlage/ctsm/nldas_grid/gen_domain_files,LND_DOMAIN_PATH=/glade/work/barlage/ctsm/nldas_grid/gen_domain_files
./xmlchange ATM_DOMAIN_FILE=domain.lnd.wrf2clm_lnd_noneg_wrf2clm_ocn_noneg.190124.nc,LND_DOMAIN_FILE=domain.lnd.wrf2clm_lnd_noneg_wrf2clm_ocn_noneg.190124.nc
./xmlchange CLM_USRDAT_NAME=nldas

4. modify env_mach_pes.xml in /scripts/nldas_test directory

        <value component="ATM">1</value>
        <value component="CPL">1</value>
        <value component="OCN">1</value>
        <value component="WAV">1</value>
        <value component="GLC">1</value>
        <value component="ICE">1</value>
        <value component="ROF">1</value>
        <value component="LND">360</value>
        <value component="ESP">1</value>

5. ./case.setup in /scripts/nldas_test directory

setenv ACCOUNT P48500028
./case.setup

7. Modify some runtime numbers, e.g.,

#### env_run.xml

./xmlchange RUN_STARTDATE=1991-10-01
./xmlchange STOP_N=365
./xmlchange JOB_WALLCLOCK_TIME=1:00:00

#### user_nl_clm

   hist_fincl2 = 'TG:I', 'FSA:I', 'SWup:I', 'SOILLIQ:I'
   hist_mfilt  = 1, 1
   hist_nhtfrq = 0, -1

   fsurdat = '/glade/work/barlage/ctsm/nldas_grid/surfdata_nldas/surfdata_nldas_hist_16pfts_Irrig_CMIP6_simyr2000_c190124.nc'
   fsurdat = '/glade/work/barlage/ctsm/nldas_grid/surfdata_nldas_wrfmap_2pfts_urban_glacier.nc'

   soil_layerstruct = '4SL_2m'

6. Build model in scripts/nldas_test directory
6a. For a new build, do this first:  ./case.build --clean

./case.build

on cheyenne do:

qcmd -- ./case.build

8. Run the model in scripts/nldas_test directory

./case.submit


===================================================================
Creating setup based on WRF domain - CTSM Cheyenne/Geyser
===================================================================

1. Create SCRIP file from WRF geo_em file
-----------------------------------------

create_scrip_file.ncl

creates two files that are complements of each other only in the mask field

script and data reside: /glade/work/barlage/ctsm/nldas_grid/scrip

2. Create mapping file in tools/mkmapdata
-----------------------------------------

Modify mkunitymap.ncl with commented lines

+;  if ( any(ncb->grid_imask .ne. 1.0d00) )then
+;     print( "ERROR: the mask of the second file isn't identically 1!" );
+;     print( "(second file should be land grid file)");
+;     exit
+;  end if

Link scrip files

ln -sf /glade/work/barlage/ctsm/nldas_grid/scrip/wrf2clm_land_noneg.nc .
ln -sf /glade/work/barlage/ctsm/nldas_grid/scrip/wrf2clm_ocean_noneg.nc .

setenv GRIDFILE1 wrf2clm_ocean_noneg.nc
setenv GRIDFILE2 wrf2clm_land_noneg.nc
setenv MAPFILE wrf2clm_mapping_noneg.nc
setenv PRINT TRUE

ncl mkunitymap.ncl

Will throw some git errors if not run in a repo

*** takes a few seconds

3. Create ESMF mapping files in tools/mkmapdata
-----------------------------------------------

qsub regridbatch_barlage.sh

copy stored in ~/src/ctsm/regrid_scripts/

4. Create domain files in cime/tools/mapping/gen_domain_files/
--------------------------------------------------------------

Build:

cd src/
../../../configure --macros-format Makefile --mpilib mpi-serial
(source ./.env_mach_specific.csh ; gmake)
cd ..

./gen_domain -m /glade/work/barlage/ctsm/nldas_grid/scrip/wrf2clm_mapping_noneg.nc -o wrf2clm_ocn_noneg -l wrf2clm_lnd_noneg

creates:

domain.lnd.wrf2clm_lnd_wrf2clm_ocn.180808.nc  
domain.ocn.wrf2clm_lnd_wrf2clm_ocn.180808.nc  
domain.ocn.wrf2clm_ocn.180808.nc

copy to /glade/work/barlage/ctsm/nldas_grid/gen_domain_files

*** takes a few seconds

5. Create surface datasets in tools/mksurfdata_map [ run on cheyenne; takes ~3 minutes ]
--------------------------------------------------

First time:
  cd src
  gmake
  cd ..

*** note -no-crop flag ****

./mksurfdata.pl -res usrspec -usr_gname "nldas" -usr_gdate "190124" -usr_mapdir "/glade/work/barlage/ctsm/nldas_grid/map" -y 2000 -exedir "/glade/u/home/barlage/src/ctsm/ctsm_surfdata/tools/mksurfdata_map" -no-crop

mv surfdata_nldas_* /glade/work/barlage/ctsm/nldas_grid/surfdata_nldas

===================================================================
Creating forcing data on WRF domain - CTSM Cheyenne/Geyser
===================================================================

/gpfs/fs1/p/cesmdata/cseg/inputdata/atm/datm7/atm_forcing_iso.datm7.Qian.T62.c080727/Precip6Hrly

1. Create SCRIP file from WRF geo_em file

===================================================================Clone case
===================================================================

./create_clone --clone /glade/u/home/swensosc/cases/NLDAS_ctsm --case /glade/scratch/barlage/ctsm/NLDAS_ctsm_nwp --cime-output-root /glade/scratch/barlage/ctsm

setenv ACCOUNT P48500028
./case.setup
./case.build --clean
qcmd -- ./case.build

./xmlchange JOB_WALLCLOCK_TIME=4:00:00
./xmlchange CHARGE_ACCOUNT=P48500028
./xmlchange PROJECT=P48500028
./xmlchange STOP_N=16

7. Modify some runtime numbers, e.g.,

#### user_nl_clm

fsurdat = '/gpfs/p/work/barlage/ctsm/NLDAS/surfdata_nldas_wrfmap_2pfts_nourban_glacier_crop_sean.nc'

soil_layerstruct = '4SL_2m'

use_hydrstress = .false.

8. Run the model in scripts/region_test directory

./case.submit`

**Comment by barlage** [comment]
Yikes! I wasn't expecting these to be broadcast across GitHub. These should be edited before public release.

**Comment by slevisconsulting** [comment]
Related to #582

**Comment by slevisconsulting** [comment]
Tasks that I see mentioned above...

Sean's suggestion:
- Separate the masks from the mapping files to reduce the number of mapping files needed
- Keep the masks in new mask files and use when needed

Mariana's suggestion:
- Create the mapping files on the fly, while running mksurfdata_map. I expect that this is within the scope of #641

**Comment by slevisconsulting** [comment]
Corrected previous post to say #644

**Comment by billsacks** [comment]
@slevisconsulting - yes, Mariana's suggestion is in the scope of #644 , so this issue relates to Sean's suggestions, which we thought were a good idea both for the sake of dataset management and efficiency. Note that this will require changes to mksurfdata_map as well as the scripts / xml related to our dataset management.

**Comment by billsacks** [comment]
Once this issue is resolved, we can more easily resolve #8 .

**Comment by slevisconsulting** [comment]
An update:
To avoid unnecessary work in #815 I have switched my attention to the present issue (#286).

`qsub regridbatch.sh` is running right now with changes in...
`mkmapdata.sh`
`namelist_defaults_ctsm.xml`
`namelist_defaults_ctsm_tools.xml`
`namelist_definition_ctsm.xml`
that reflect the replacement of numerous SRC files containing various masks with one SRC file per SRC resolution that contains `grid_imask = 1`.

**Comment by slevisconsulting** [comment]
For now `regridbatch.sh` seems to be working for all the source (SRC) and destination (DST) resolutions except `1km-merge-10min_HYDRO1K-merge-nomask`

**Comment by slevisconsulting** [comment]
Resubmitted with a couple of changes and seems to work for the `1km-merge-10min_HYDRO1K-merge-nomask` SRC resolution.

I will open a PR soon to share my code mods to-date.
