### ISSUE TITLE
A bug in "quadraticMod.F90"?

### ISSUE THREAD

**Issue by huitang-earth** [ESCOMP/ctsm#318]
Hi,

There might be a bug in "quadraticMod.F90" at line 48.

Should "if ( sqrt(-root) **>** epsilon(b) )then"  be  "if ( sqrt(-root) **<** epsilon(b) )then"?

Also it appears that "sqrt(-root) **<** epsilon(b)" might be too rigorous. Will "(-root) **<** epsilon(b)" be more proper?

Hui

**Comment by ekluzek** [comment]
@huitang-earth note this check is ONLY done if root is negative to prevent taking a square root of a negative number on lines 57 or 59. Allowing a square root of a negative number will result in a floating point violation. If root is large we want the code to abort and show what's happening. Normally in practice this doesn't happen.

What we did find is that if root is a small value that is essentially zero, it would cause the code to crash. So we wanted to allow the code to continue if root is small and won't actually make a difference in the final result on lines 57 and 59.

But, yes it does look like the evaluation is backwards. It should say if sqrt(-root) is small enough that it's nearly zero, go ahead and assume it's zero. So yes that should be reversed.

I don't think there's much of a difference between using sqrt(-root) or -root itself. This is a condition that hardly happens at all. But, the final question is what's on line 57 as follows...

-0.5_r8 * (b + sqrt(root))

If sqrt(root) is small enough that when it's added to b, it register's as zero -- then it should be allowed. You are right practically it probably doesn't make much of a difference if the sqrt is taken or not. I think it's possible that if b is large that it could make a difference though.

**Comment by huitang-earth** [comment]
@ekluzek thanks for your response. 

The reason I think "sqrt(-root) < epsilon(b)" might be too rigorous is that:

If I use "sqrt(-root) < epsilon(b)", I got the following error message at one time step:

   Quadratic solution error: b^2 - 4ac is negative =  -7.845185276151439E-024
    ENDRUN:
    ERROR in quadraticMod.F90 at line 52

"root" seems to be smaller than epsilon(b) (i.e., 0.22204460E-15), but sqrt(-root) will be around 1E-12, which is larger than epsilon(b).

I don't know how to avoid this, if still using "sqrt(-root) < epsilon(b)".

**Comment by ekluzek** [comment]
OK, I added a unit-test to scope out what actually can be done with this, and make sure the error test is correct. I was able to back it off being as stringent. It will be coming to master shortly.

**Comment by ekluzek** [comment]
This will be done in clm5.0.dev010
