### ISSUE TITLE
typical and supported grid layouts for land testing

### ISSUE THREAD

**Issue by rgknox** [ESCOMP/ctsm#321]
For FATES developer testing, we have been using the f19_g16 and f45_f45_mg37 to handle the majority of our tests.  We test on other axes, like switching modules etc, so we can't be trying a million different grids.  Those two grids are used for about 80% of our tests.

I took a look at the grids used for testing I2000Clm50 compsets, and was surprised that we are almost the only ones using these two grids in our tests (fates developer tests).

```
cat ctsm/cime_config/testdefs/testlist_clm.xml | grep I2000Clm50 | grep f45
cat ctsm/cime_config/testdefs/testlist_clm.xml | grep I2000Clm50 | grep f19
```

Generally, I'm seeing lots of f19_g17.  I'm seeing the f45_f45_mg37 used for some SP mode tests, and only 1 50BGC test.

I was wondering if the f19_g16 and f45_f45_mg37 were still considered useful grids?  Are there better grids?  

I like the f45 because it seems to meet some vague balance between resources used, and resolution of terrestrial biomes and environmental conditions expressed.  I use the f19_g16, because its largish, tests a conditions where more cluster resources are used, and is maybe more likely to have a few grid-cells with weird vegetation/environment conditions exist.  We also run 1 test that is a short f09_g16 as well.

But, there are subtle differences it seems, between these two grids and other that are similar.

Any thoughts appreciated.

**Comment by billsacks** [comment]
We tend to use `f10_f10_musgs` as our workhorse resolution for global tests (I think this is 10x15 degrees - so about 1/4 as many grid cells as f45). I don't have strong feelings about what's best to use. My general feeling is that the chance you'll catch bugs that only show up infrequently scales with the number of grid cells and with the number of time steps (so running a coarser resolution for longer, or multiple coarse resolution tests with different forcings / configurations, is somewhat equivalent to running higher resolution for shorter) - but I have no sense for whether these tradeoff equally.

By the way: I'm removing the `help wanted` tag here: while this intuitively seems applicable, my feeling is that we should reserve that tag for when we want help from the wider community, which is how GitHub suggests that label be used.

**Comment by rgknox** [comment]
Thanks @billsacks , I might try swapping in some f10_f10_musgs grids.

**Comment by billsacks** [comment]
Looks like this has been resolved.
