### ISSUE TITLE
Move config_archive.xml to CTSM cime_config

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#343]
Move the CTSM portion of config_archive.xml to CTSM's cime_config.

**Comment by billsacks** [comment]
@ekluzek says: first we add it to ctsm, then later it can be removed from cime

**Comment by fischer-ncar** [comment]
Looks like config_archive.xml was added for the release tags, but not the development tags.  @jedwards4b did remove ctsm from the cime config_archive.xml.

**Comment by jedwards4b** [comment]
@fischer-ncar can you just copy the ctsm config_archive.xml from the release branch to the trunk?

**Comment by fischer-ncar** [comment]
Yes I could, but then I would still need a ctsm tag before I can start prealpha testing.

**Comment by billsacks** [comment]
@ekluzek you've done this now, right? Should this issue be closed?

**Comment by ekluzek** [comment]
This has now been done, both on the release branch and master.
