### ISSUE TITLE
In endrun: pass message to shr_sys_abort rather than writing it to iulog

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#347]
I want to write some expected-exception tests for my init_interp changes. For these to work robustly, I want to check the error message returned against the expected error message (to make sure it's not aborting for some completely different reason). In doing so, I noticed that our endrun calls don't actually pass the abort message on to shr_sys_abort:

```fortran
    if (present (msg)) then
       write(iulog,*)'ENDRUN:', msg
    else
       write(iulog,*)'ENDRUN: called without a message string'
    end if

    call shr_sys_abort()
```

@ekluzek - Do you know if that's intentional?

I'm thinking of changing this to pass msg on to shr_sys_abort rather than writing it to iulog, but don't want to mess with this if the current behavior is intentional.

Actually, the full implementation of what I'm thinking is: do what I'm saying above for the existing msg argument. But also add a new optional argument to endrun, additional_msg, which is written to iulog but not passed along to shr_sys_abort. This is to support expected-exception unit testing, particularly thinking about the common practice of writing out the line number: this is too volatile to test against in unit tests. So a call could look like this:

```fortran
call endrun(msg='Informative message', additional_msg=errmsg(__FILE__, __LINE__))
```

@ekluzek please let me know if you have any thoughts on this.

**Comment by billsacks** [comment]
See billsacks@7bf66b89 for the proposed change.

**Comment by ekluzek** [comment]
@billsacks this is a good change that makes sense to me. I see the point of separating out the file and line number for unit tests. It sounds like current calls would continue to work, but they could transition to the new form in order to get the separation you are looking for.

In terms of why msg isn't passed into shr_sys_abort -- from "svn blame" this is something that @mvertens put into place. It looks pretty intentional to me. But, I'm not clear on the reasons for it. Hopefully, she can comment.

**Comment by billsacks** [comment]
@ekluzek - I just traced the history back further and what I see is: @mvertens did do a major rewrite of the endrun code a few years ago, but the current behavior doesn't necessarily look intentional: Originally, the endrun code looked like this:
https://github.com/ESCOMP/ctsm/blob/353337abf3e59c619f86ca4488a0f1cd19437b84/src/util_share/abortutils.F90#L26-L69

@mvertens then refactored it to its current form, including putting in a call to `shr_sys_abort`. But she kept the message printing as it was before rather than sending the message into `shr_sys_abort` to be printed there. So I could see the current behavior being unintentional, but I'll let @mvertens comment if she feels it's intentional.
