### ISSUE TITLE
Put in place water isotope consistency checks

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#357]
An early step to support implementation of water isotopes should be putting in place consistency checks that confirm that isotopic quantities are being updated properly as they pass through the system. I believe that Ben Andre put something like this in place on the old water isotope branch.

**Comment by billsacks** [comment]
@mathewvrothstein I'm tentatively assigning this to you, thinking you might have a better sense of what needs to be done here, given your involvement with Ben earlier in this project. But I'm happy to help with it if you know as little as I do about it :-)

**Comment by davidnoone** [comment]
Hi Bill, 

1) The scattering of consistency checks will be super valuable for code development (and maintenance), but would not need to be in for production runs. In essence, you're checking that the tracer mass balance meets the same mass balance as the normal/bulk water. Doing this check after initialization and after each hydrology routine allows you to isolate any possible issue.

However, once the code development debugging is finished, you can be more sparing about where these are placed. One call at the end of the initialization would be fine. I'd keep one call after the canopy, soil, urban and lake routines too as a check. Finally one at the end of the step.

On entry to CLM from the driver, I suggest checking the inputs (precip and vapor), and on exit check the fluxes passed back to the coupler (qflx, runoff to RTM, etc). This way we can be sure that CTSM is communicating consistently. 



2)  "Is it important that we maintain the checks of all tracers if wiso_clm_unit_fractionation is true?"
Yes, as a unit check. The key goal here is to ensure the tracer scheme conserves mass when the full isotopic physics is used. During development this is used to test the mass balance is working with the isotope code, and for longer maintenance it allows future developers to check that they have accounted for the tracers in any new code changes.  With fractional set to 1, there should be no difference between the tracer water and the bulk water (to the desired numerical precision). 

Your point that they would all be the same is a good one, and correct. And this is the criteria for knowing the check has passed. There would only be a difference if there had been a code error.

I expect that wiso_clm_unit_fractionation only triggers changes in the tracer registration at the point where one configures what type of water tracer is in each array position. With this unit test flagged, the fractionation factors (and similar physical properties) would be set to 1. That should be it.

**Comment by billsacks** [comment]
@davidnoone thanks a lot for this. Your reply on (1) makes sense. My understanding from your reply is that having multiple checks throughout the driver loop does not catch any more problems, but helps people pinpoint where, exactly a problem occurred. Long-term, we'll try to strike a balance between having this extra pinpointing without cluttering the code too much.

For (2), I'm still not clear on what we gain by checking every tracer rather than just checking the single plain water tracer - assuming that any operation on tracers will be operating in a loop over all tracers. (Maybe the problem is that that assumption is wrong?)

**Comment by davidnoone** [comment]
1) Right.

2) Well, in principle yes. All tracers "should" work the same. It's good to check though :) There is a detail here which comes up in that the roudoff error need not be the same for all traces depending on what their magnitude is. Consider a tracer which happens to be 0.1 times the bulk. With the unit test on, this proportion should be preserved. (i.e. consider tracer(2)/tracer(1) = 0.1?) However, the roundoff error will be 10 times larger compared to the value itself. Since parts of the code rely on ratios (tracer/bulk, or tracers(2)/tracer(1)), small round off errors in the denominator lead can lead to massive errors in the ratio. One place where this plays out is where there are mass over runs (negative masses, excesses, etc), that have to have logical traps to correct them. Therefore, checking this for this type of problem as a second tracer in a unit test helps confirms that these types of exceptions have been managed properly. 

You're right tough, that in the normal production run tracer(1) should always be the same as bulk water, and it can always be checked. That test is straight forward. The test on tracer(2:N), needs to consider of the configuration.

In general, my thought here is that if you're in the business of running a unit test to check the tracers, you're going to be happy to spend some time looping over a tracer index. If you going to check, check them all.

**Comment by billsacks** [comment]
Okay, thanks a lot. Your point about checking tracers that aren't identical to the bulk, but rather are some fixed (possibly small) fraction of bulk water is a very good one. As far as I can tell, there weren't any checks like that in the previous water isotope branch, but I do see the value in checking that.

I'd propose that we do these tests in a somewhat more explicit (to my mind anyway) manner: Rather than adding something that we call HDO (for example) to the tracer array and turning on an override to set its fractionation to 1, then checking that that tracer stays consistent with the bulk: Instead, we would have a few named tracers with some specific properties that we add to the tracer arrays when this test code is enabled:

1. A plain water tracer that maintains a ratio of 1. This tests to make sure that tracers are updated wherever they should be.

2. A tracer that maintains a ratio of 0.1. This additionally tests that the code for updating tracers properly handles non-1 ratios.

3. A tracer that maintains some very small ratio, say, 1e-10. This additionally tests for numerical stability of tracer updates.

Then, when we're running the tracer test (which I imagine being a test in our test suite), we'd add these three tracers rather than any others that would typically be added, and do tests that all three are maintaining their desired ratios.

Does that seem reasonable to you? In my mind this will be a more rigorous and controlled test than what's currently in the code, but I could easily be missing something.

(Implementation thought: We can have a logical value in `water_info_tracer_type` saying whether this tracer maintains a fixed ratio, and a real value saying what that fixed ratio is. Then in doing the checks, we check any tracer that is supposed to maintain a fixed ratio, ensuring that its ratio to bulk matches the expected ratio within roundoff.)

**Comment by davidnoone** [comment]
Yep - sounds good.

This would indeed be best done in a level of abstraction, and be handled at the level of registration of the tracers. Exactly as you say, no need to have "HDO" names, etc.
A different registration sequence for tracer tests vs production mode was what I had in mind as well.
Within the block which specifics the tracer properties (water_info_tracer_type) on a per-tracer basis is a good place to do it. (CAM does it this way, but you're right that in the existing CAM and CLM code there is no single switch to configure the model for these tests. Most of those tests were done by hand.)

It's useful to note here that these types of unit tests are very close to scientifically useful in their own right as "tags". While there is a structure you're thinking about here for code testing, it also offers architecture that can be used to configure tracers generically that are of experimental interest. (Consider an experiment with 12 water tracers, where each one only receives precipitation that falls in a particular month. This configuration would track 'age of water' in the model, etc.) By ensuring these tracer checks pass, you also ensure that these types of exotic tags are robust, which is the goal.

**Comment by billsacks** [comment]
@davidnoone thanks a lot. I feel good about this path forward. (A few pieces will have to come into place to have this all truly runtime configurable, but that's my end vision as well.)

@mathewvrothstein we could think about putting in place this infrastructure for doing consistency checks on multiple artificial tracers initially, or we could add that in a second stage - whichever you prefer.

**Comment by billsacks** [comment]
@mathewvrothstein has put in place initial tracer consistency checks in commit dd9cd6d. We'll still need to address some of the other points in this issue, particularly adding checks for tracers other than the bulk water tracer.
