### ISSUE TITLE
Improve user friendliness of build-namelist

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#366]
Improve the user friendliness of build-namelist, but noting what the user has to change. Typically this is either user_nl_clm, or CLM_CONFIG_OPTS, or CLM_BLDNML_OPTS, or CLM_NAMELIST_OPTS. Rather than assuming the user knows which one to change, spell it out for them when it's defined, or mention all if not.

This could be changed in errors like...

      $log->fatal_error("-bgc option used with clm4_0 physics. -bgc can ONLY be used with clm4_5/clm5_0 physics");

or
                  $log->fatal_error("$var has a value ($val) that is NOT valid. Valid values are: @valid_values");

Reference: ESMCI/cime#827

**Comment by ekluzek** [comment]
Too risky to do this for cesm2.0 release -- we'll do for the CMIP6 update.

**Comment by billsacks** [comment]
Let's just try to make this better in the python, eventually.
