### ISSUE TITLE
variable soil depth and fates

### ISSUE THREAD

**Issue by rgknox** [ESCOMP/ctsm#370]
Hi all,

We have a compatibility issue between clm5 and fates right now.  Fates assumes a static depth of the soil column, and as I understand, soil depth is variable now in clm5.

What we need to do in fates is the identify the lowest soil layer at the column layer, and we will make sure that roots are not allowed to grow below that level.

It looks like the key variable is:   ``` col%nbedrock ```, right?

Thanks!

Issue in FATES for reference (private): https://github.com/NGEET/fates/issues/374

**Comment by dlawrenncar** [comment]
That's correct.  col%nbedrock is the number of soil layers down to the
bedrock.

**Comment by rgknox** [comment]
great, thanks for confirmation @dlawrenncar

**Comment by billsacks** [comment]
@rgknox is anything more needed on this in the ctsm side, or is this just a fates issue at this point? i.e., should I close this?

**Comment by rgknox** [comment]
There are a few more things that I'm checking through.

It appears that we we are also passing

canopystate_inst%altmax_lastyear_indx_col(c)

to fates.  I'm figuring that this soil layer depth will always be less than or equal to depth to bedrock, so I'm checking that now...

Could we leave this open until I make the PRs?

**Comment by billsacks** [comment]
Sure thing.

**Comment by pollybuotte** [comment]
I've just encountered this issue while trying to investigate the effect of soil depth on a single PFT FATES simulation.  Changing the zbedrock values from 20m to 5m in the surface data file has no effect on the history variable nbedrock - it stays at layer 20.  There are, however, changes in the simulated soil matric potential, as shown below.  Does it seem strange that there would be any change if FATES is not seeing the CLM soil depth?  I'm running with FATES tag c7fa7c2 518c862 from PR#514.

![image](https://user-images.githubusercontent.com/30528250/59119714-af988080-8910-11e9-8e1c-eadb7541973d.png)

**Comment by rgknox** [comment]
@pollybuotte , looking into this now.  I've never used this setting, but I do see that there is a use_bedrock flag (namelist), did you set that too?

**Comment by pollybuotte** [comment]
@rgknox, I missed that flag, thanks for pointing it out.  I will re-run with it on.

**Comment by rgknox** [comment]
although @pollybuotte , I'm running tests now, and it doesn't seem like the fates_next_api branch is reading in that value from the namelist, or able to use the bedrock data.  It seems like that part of the code just isn't called.  Maybe  this is different in ctsm master, or maybe there is an issue on this?

**Comment by rgknox** [comment]
https://github.com/ESCOMP/ctsm/issues/289#issuecomment-365436600

**Comment by pollybuotte** [comment]
@rgknox, just confirming that changing the soil depth without setting use_bedrock = .true. does not change answers.  I had changed soil texture as well as depth in the run I plotted above.

**Comment by rgknox** [comment]
ok, thanks for the update @pollybuotte . since the original work and discussion on this is completed, I'm going to close this issue
