### ISSUE TITLE
CLM5 crashes when reading netCDF domain file

### ISSUE THREAD

**Issue by thiagoveloso** [ESCOMP/ctsm#371]
Dear all, thank you very much for the ongoing hard work with CLM5!

This issue is regarding the thread started at https://bb.cgd.ucar.edu/error-porting-clm5-centos-linux-cluster. 

Basically, trying to run the case
```
./create_newcase --case ${CASEROOT} --res f19_g17 --compset I2000Clm50Sp --mach flux --compiler pgi 
```
crashes the CLM5 as soon as it starts to run. The combination of compset and grid was chosen based on `./query_config --compsets clm`. and  `cat ~/models/clm5.0/cime_config/testdefs/testlist_clm.xml | grep I2000Clm50`

Going a little deeper into that error with @jedwards4b's guidance, I looked at the `atm.log` file which says:

```
(datm_comp_init)  decomp   = 1d
(datm_comp_init)  iradsw   =        1
(datm_comp_init)  factorFn = null
(datm_comp_init)  restfilm = undefined
(datm_comp_init)  restfils = undefined
(datm_comp_init)  presaero =  T
(datm_comp_init)  force_prognostic_true =  F
(datm_comp_init)  wiso_datm   =  F
(datm_comp_init) inst_index  =         1
(datm_comp_init) inst_name   =  ATM
(datm_comp_init) inst_suffix =
(shr_strdata_readnml) reading input namelist file: datm_in
(shr_stream_init) Reading file datm.streams.txt.CLMGSWP3v1.Solar
(shr_file_freeUnit) unit   97 was not in use
(shr_stream_init) Reading file datm.streams.txt.CLMGSWP3v1.Precip
(shr_file_freeUnit) unit   97 was not in use
(shr_stream_init) Reading file datm.streams.txt.CLMGSWP3v1.TPQW
(shr_file_freeUnit) unit   97 was not in use
(shr_stream_init) Reading file datm.streams.txt.presaero.clim_2000
(shr_file_freeUnit) unit   97 was not in use
(shr_stream_init) Reading file datm.streams.txt.topo.observed
(shr_file_freeUnit) unit   97 was not in use
(datm_comp_init)  atm mode = CLMNCEP
 (shr_strdata_init)  stream             1
 (shr_strdata_init)  filePath =             1
 /nfs/alsteine2/shared_data/cesmdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/
 (shr_strdata_init)  fileName =             1
 /nfs/alsteine2/shared_data/cesmdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/domain.lnd.360x720_gswp3.0v1.c170606.nc
 (shr_strdata_init)  timeName =             1 time
 (shr_strdata_init)   lonName =             1 xc
 (shr_strdata_init)   latName =             1 yc
 (shr_strdata_init)   hgtName =             1 unknownname
 (shr_strdata_init)  maskName =             1 mask
 (shr_strdata_init)  areaName =             1 area
(shr_ncread_handleErr) netCDF error: NetCDF: Invalid argument
 ERROR: (shr_ncread_varDimSizes) ERROR inquire variable dimids
```
And this is the header of the `domain.lnd.360x720_gswp3.0v1.c170606.nc` file:

```
netcdf domain.lnd.360x720_gswp3.0v1.c170606 {
dimensions:
    scalar = 1 ;
    ni = 720 ;
    nj = 360 ;
    nv = 4 ;
variables:
    double xc(nj, ni) ;
        xc:long_name = "longitude of grid cell center" ;
        xc:units = "degrees_east" ;
        xc:mode = "time-invariant" ;
    double yc(nj, ni) ;
        yc:long_name = "latitude of grid cell center" ;
        yc:units = "degrees_north" ;
        yc:mode = "time-invariant" ;
    double xv(nv, nj, ni) ;
        xv:long_name = "longitude of grid cell vertices" ;
        xv:units = "degrees_east" ;
        xv:mode = "time-invariant" ;
    double yv(nv, nj, ni) ;
        yv:long_name = "latitude of grid cell vertices" ;
        yv:units = "degrees_east" ;
        yv:mode = "time-invariant" ;
    int mask(nj, ni) ;
        mask:long_name = "domain mask" ;
        mask:units = "unitless" ;
        mask:mode = "time-invariant" ;
    double area(nj, ni) ;
        area:long_name = "area of grid cell in radians squared" ;
        area:units = "area" ;
        area:mode = "time-invariant" ;

// global attributes:
        :case_title = "GSWP3 3-Hourly Atmospheric Forcing" ;
}
```
The `mask` variable looks rather strange - it is filled with `1's` (i.e. no discernible land/sea mask): 
![clm5_mask](https://user-images.githubusercontent.com/4642968/39678902-9a9f7ade-5163-11e8-8b30-4fa7158b2cb7.jpeg)

Jim also mentioned that there might be a `frac` variable missing in the file.

Do you guys think this can be causing the error on my case above? Is there any other version of the mask that I can use?

Thank you!

**Comment by thiagoveloso** [comment]
Hey guys,
I was just wondering if there are any thoughts on this issue?

**Comment by olyson** [comment]
That is the right domain file, it's the one we've been using successfully.  The mask is one everywhere because the GSWP3 data is global, not just over land.
I'll try the compset and resolution you are using on our machine here and see if it works....

**Comment by thiagoveloso** [comment]
Thank you very much for the follow-up Keith @olyson, I really appreciate it. In case you need further information, all files related to this error are posted on https://bb.cgd.ucar.edu/error-porting-clm5-centos-linux-cluster

**Comment by olyson** [comment]
Well, that case works here.  It does look like your system is having problems reading the domain file, but not sure how to proceed from here.
I've put my full case directory on our ftp site.  You could try comparing the datm streams files in .../CaseDocs with yours to see if there are any differences that might cause an error (i.e., datm.streams.txt.*).

You can either use the Globus web interface and use the "NCAR CGD Anon" server.

Or you can use the web link:  ftp://gridanon.cgd.ucar.edu:2811 

Or you can use ftp ftp.cgd.ucar.edu

cd pub/oleson/Thiago_Veloso

**Comment by ekluzek** [comment]
@thiagoveloso I'm suspicious that this is really an issue with getting the right version of NetCDF linked in the system. With the release I can't really help right now, and I think this is more of a porting issue of CESM rather than a strict issue with CTSM. I'm trying to point people to your issue on bb.cgd.ucar.edu, but I know people are overloaded right now, so I can't promise they'll be able to look at it either.

**Comment by ekluzek** [comment]
@thiagoveloso @jedwards4b suggests also trying to link pnetcdf in, and using it.

I also suggest doing the normal kind of things of trying with a simpler case first. Try a single point one processor case with mpi-serial, and make sure you can get that to work. And then try really low resolution cases with only a few processors, before you scale it up to more processors and higher resolution.

**Comment by thiagoveloso** [comment]
Thank you very much for the follow up @olyson and @ekluzek. Based on your comments I was able to get CLM5 running on an Amazon server, and I have also determined that the error I reported is probably with my cluster - I will talk to IT to see what's going on. I would say this ticket can be closed if you guys are OK with it.
