### ISSUE TITLE
create_newcase issue

### ISSUE THREAD

**Issue by pnlfang** [ESCOMP/ctsm#373]
I'm trying to create a test problem on PNNL's constance machine using :
./create_newcase --case testI --res f19_g17_gl4 --compset I2000Clm50BgcCrop --mach constance --compiler intel

Directory testI wasn't created and no error message was generated (same for other compsets).  Screen output shows:

./create_newcase --case testI --res f19_g17_gl4 --compset I2000Clm50BgcCrop --mach constance --compiler intel
Compset longname is 2000_DATM%GSWP3v1_CLM50%BGC-CROP_SICE_SOCN_MOSART_CISM2%NOEVOLVE_SWAV
Compset specification file is /pic/projects/ngee_tropics/d3m045/ctsm/cime/../cime_config/config_compsets.xml
Compset forcing is 1972-2004
ATM component is  Data driven ATM
LND component is clm5.0:
ICE component is Stub ice component
OCN component is Stub ocn component
ROF component is MOSART: MOdel for Scale Adaptive River Transport
GLC component is cism2 (default, higher-order, can run in parallel):
WAV component is Stub wave component
ESP component is
Pes     specification file is /pic/projects/ngee_tropics/d3m045/ctsm/cime/../cime_config/config_pes.xml
Machine is constance
Pes setting: grid match    is l%1.9x2.5
Pes setting: grid          is a%1.9x2.5_l%1.9x2.5_oi%null_r%r05_g%gland4_w%null_m%gx1v7
Pes setting: compset       is 2000_DATM%GSWP3v1_CLM50%BGC-CROP_SICE_SOCN_MOSART_CISM2%NOEVOLVE_SWAV
Pes setting: tasks       is {'NTASKS_ATM': -2, 'NTASKS_ICE': -2, 'NTASKS_CPL': -2, 'NTASKS_LND': -2, 'NTASKS_WAV': -2, 'NTASKS_ROF': -2, 'NTASKS_OCN': -2, 'NTASKS_GLC': -2}
Pes other settings: {}
 Compset is: 2000_DATM%GSWP3v1_CLM50%BGC-CROP_SICE_SOCN_MOSART_CISM2%NOEVOLVE_SWAV
 Grid is: a%1.9x2.5_l%1.9x2.5_oi%null_r%r05_g%gland4_w%null_m%gx1v7
 Components in compset are: ['datm', 'clm', 'sice', 'socn', 'mosart', 'cism', 'swav', 'sesp', 'drv', 'dart']

*********************************************************************************************************************************
This compset and grid combination is not scientifically supported, however it is used in 1 tests.
*********************************************************************************************************************************

No project info available
WARNING: No cesm Model version found.
ERROR: No queues found

**Comment by billsacks** [comment]
The relevant line is the last one (`ERROR: No queues found`). At a glance, it looks to me like constance is not fully supported for cesm-mode usage. You could try updating entries in config/cesm/machines to match what's in config/acme/machines (or config/e3sm/machines depending on the cime version) with respect to constance.

**Comment by billsacks** [comment]
In particular, this section is missing on the cesm side, in config_batch.xml:

```xml
    <queues>
      <queue walltimemax="00:59:00" default="true">slurm</queue>
    </queues>
```

but I wouldn't be surprised if other things are missing, too.

**Comment by pnlfang** [comment]
Resolved as suggested.  Thanks!
There are compilation errors related to fates dependency.  Looks like externals are required even though I don't need them now.

**Comment by billsacks** [comment]
Okay, good to know. I'll close this; feel free to reopen if there are still outstanding issues.
