### ISSUE TITLE
history ignoring first hist_mfilt value?

### ISSUE THREAD

**Issue by ckoven** [ESCOMP/ctsm#396]
Hi All,

I've set up a CLM-FATES ensemble and am trying to use hist_mfilt to keep the number of history files manageable.  So I set up two history streams, for monthly and annual variables, via the following in my namelist:
```
hist_mfilt = 60, 10
hist_nhtfrq = 0, -8760
```
But I am still getting individual monthly files for the first set of history tapes.  Is the first instance of the hist_mfilt array getting ignored somehow or have I done something wrong?

Thanks,
Charlie

**Comment by ekluzek** [comment]
@ckoven I think this is issue #85. Which it looks like has a proposed fix that hasn't gotten in the code. Can you verify that?

**Comment by ckoven** [comment]
@ekluzek yes that looks to be the same thing.  OK I'll just leave it as-is then for now.  thanks!

**Comment by ekluzek** [comment]
Closing this as it seems to be a duplicate.
