### ISSUE TITLE
minor format update needed in namelist_definition_clm4_5.xml

### ISSUE THREAD

**Issue by bertinia** [ESCOMP/ctsm#399]
In order for the nameilst_definition_clm4_5.xml file to pass a xmllint schema test and be used
in the autogenerated web documentation tools, ALL instances of the `&` need to be replaced
with `&amp;` this includes line 349:

-lower_boundary_condition = 4 : 11-layer solution w/ aquifer layer                                (only used with soilwater_movement_method=Zeng&Decker 2009)
+lower_boundary_condition = 4 : 11-layer solution w/ aquifer layer                                (only used with soilwater_movement_method=Zeng`&amp;`Decker 2009)

**Comment by ekluzek** [comment]
I searched for this in other CTSM xml files and only found it in that one place:

```
diff --git a/bld/namelist_files/namelist_definition_clm4_5.xml b/bld/namelist_files/namelist_definition_clm4_5.xml
index efa6637..e9dfcba 100644
--- a/bld/namelist_files/namelist_definition_clm4_5.xml
+++ b/bld/namelist_files/namelist_definition_clm4_5.xml
@@ -349,7 +349,7 @@ Index of lower boundary condition for Richards equation.
 lower_boundary_condition = 1 : flux lower boundary condition                                     (use with soilwater_movement_method=adaptive time stepping)
 lower_boundary_condition = 2 : zero-flux lower boundary condition                                (use with soilwater_movement_method=adaptive time stepping)
 lower_boundary_condition = 3 : water table head-based lower boundary condition w/ aquifer layer. (use with soilwater_movement_method=adaptive time stepping)
-lower_boundary_condition = 4 : 11-layer solution w/ aquifer layer                                (only used with soilwater_movement_method=Zeng&Decker 2009)
+lower_boundary_condition = 4 : 11-layer solution w/ aquifer layer                                (only used with soilwater_movement_method=Zeng&amp;Decker 2009)
 
 TODO(bja, 2015-09) these should be strings so they have meaningful names instead of ints. 
 </entry>

```

**Comment by billsacks** [comment]
@ekluzek it looks like you've already fixed this, so no need to change it back... but in general I'd prefer just spelling it out as "and" rather than using the hard-to-read "&amp;"

**Comment by ekluzek** [comment]
Fixed in clm5.0.dev013
