### ISSUE TITLE
More time needed for a fates test on hobart...

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#406]
The test

<test name="ERS_Ld60" grid="f45_f45_mg37" compset="I2000Clm45Fates" testmods="clm/Fates">

ERS_Ld60.f45_f45_mg37.I2000Clm45Fates.hobart_nag.clm-Fates

Is failing due to too short of a wallclock time. It currently has 20 minutes.

**Comment by ekluzek** [comment]
Looks like it nearly finished ran for 59 days and a little bit. So just needs a little more time.

**Comment by rgknox** [comment]
We could also try pairing this test down to 40-45 days, it does seem to be an outlier in terms of wallclock time.

**Comment by ekluzek** [comment]
I think giving it just a little more time is fine. If I give it 40 minutes, that still not bad. There's some aux_clm tests on cheyenne that I'm giving 3:40 which is getting too long.

**Comment by ekluzek** [comment]
This went into clm5.0.dev013.
