### ISSUE TITLE
path to test_build_namelist is wrong with move to git

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#409]
The test_build_namelist.pl doesn't work since the move to git, because of path. The fix looks simple.

**Comment by ekluzek** [comment]
The path update to get the test to work is simple. But, there are other changes to the build-namelist subroutine calls that would take some work to get working. Since, we are planning on moving to python, I don't think it's worth getting these working. It wasn't fully implemented yet anyway, nor used. The main utility now, might be to look at the code and see how it was configured as an example of a testing framework. So I figure I'll remove it, and look at previous versions if there's something useful to glean from it.

**Comment by billsacks** [comment]
Closing this wontfix issue.
