### ISSUE TITLE
better error checking needed for copying urban parameters in mksurfdata.pl

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#41]
**Bill Sacks < sacks@ucar.edu > - 2016-01-27 15:07:02 -0700**
**Bugzilla Id:** [2275](http://bugz.cgd.ucar.edu/show_bug.cgi?id=2275)
**Bugzilla CC:**  andre@ucar.edu,  rfisher@ucar.edu, 

For this code in mksurfdata.pl (which was added based on bug 1681):

            #
            # If urban point, overwrite urban variables from previous surface dataset to this one
            #
            if ( $urb_pt && ! $opts{'no_surfdata'} ) {
               my $prvsurfdata = `$scrdir/../../../bld/queryDefaultNamelist.pl $queryopts -var fsurdat`;
               if ( $? != 0 ) {
                  die "ERROR:: previous surface dataset file NOT found\n";
               }
               chomp( $prvsurfdata );
               my $varlist = "CANYON_HWR,EM_IMPROAD,EM_PERROAD,EM_ROOF,EM_WALL,HT_ROOF,THICK_ROOF,THICK_WALL,T_BUILDING_MAX,T_BUILDING_MIN,WIND_HGT_CANYON,WTLUNIT_ROOF,WTROAD_PERV,ALB_IMPROAD_DIR,ALB_IMPROAD_DIF,ALB_PERROAD_DIR,ALB_PERROAD_DIF,ALB_ROOF_DIR,ALB_ROOF_DIF,ALB_WALL_DIR,ALB_WALL_DIF,TK_ROOF,TK_WALL,TK_IMPROAD,CV_ROOF,CV_WALL,CV_IMPROAD,NLEV_IMPROAD,PCT_URBAN,URBAN_REGION_ID";
               print "Overwrite urban parameters with previous surface dataset values\n";
               $cmd = "ncks -A -v $varlist $prvsurfdata $fsurdat_fname";
               print "$cmd\n";
               if ( ! $opts{'debug'} ) { system( $cmd ); }
            }

I discovered – the hard way – that there is no error checking on the ncks command. I had been iteratively making new surface datasets and updating the namelist_defaults, and apparently one time I ran this not all of the surface datasets in namelist_defaults actually existed in the inputdata space. So the ncks command failed.

The big problem here is that, when this fails (or even if the 'die' near the start of this block is executed), the surface datasets are left there. So, unless you look carefully at the output of the mksurfdata.pl script, it looks like the surface datasets were created correctly, when in fact all of these urban fields are wrong.

So: I propose that, if either (a) the 'die' in this block is executed, or (b) the ncks command fails, then the surface dataset should be removed – or maybe renamed to something like "$fsurdat_fname.INCOMPLETE"... in any case, something that will prevent it from being used accidentally.

**Comment by ekluzek** [comment]
This has now been handled in ctsm5.1 and ctsm5.2 as we now create the urban datasets using subset_data and fsurdat_modifier and as such this is handled going forward.
