### ISSUE TITLE
 Do not allow SOYFIXN diagnostic field with FUN

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/ctsm#419]
-bug
Nitrogen fixation in soy should be handled by FUN in CLM5, thus CNSoyFix is not called in CNDriverMod.F90. The variable SOYFIXN should be off by default if FUN is active.  Otherwise the output is zero for default CLM5 runs, which may confuse users.  
When fun is on, users will need to turn of PFT level output of NFIX to get fixation rates from soy.

This can be done by changing line 954 of CNVegNitrogenFluxType.F90 as follows
    if (use_crop .and. .not. use_fun) then

**Comment by billsacks** [comment]
@wwieder does this just affect diagnostic fields, or does this actually affect the science?

**Comment by billsacks** [comment]
@ekluzek clarified for me that this just has to do with a diagnostic field.

**Comment by billsacks** [comment]
@wwieder I might fix this in a simple bfb tag today. But I wanted to check exactly what you want: The code change you suggest wouldn't even allow SOYFIXN to be output when FUN is off. Is that what you want, or do you want it to be allowed, but just off by default?

**Comment by dlawrenncar** [comment]
@billsacks Will is out today.  My reading of the suggested code change is
that this would allow SOYFIXN to be output if FUN is off, and would not
permit SOYFIXN to be output when FUN is on, which is the desired behavior.
With FUN on, SOYFIXN is not calculated so reporting it as zeros is clearly
misleading to users.

**Comment by wwieder** [comment]
Agreed with Dave

**Comment by billsacks** [comment]
@dlawrenncar thanks. You're right: I flipped the logic of the conditional. I'll go ahead with this change that doesn't permit this variable to be output when FUN is on.
