### ISSUE TITLE
FATES labels

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#421]
@rgknox @ckoven and @ekluzek - I noticed that there are some new labels: "type: FATES change" and "type: FATES Next API". I feel it's great to have these labels, but I don't think it's correct to prefix them with "type". Other than these, the "type" labels typically apply to issues. It looks like these labels apply to PRs.

I'd like to suggest a new "PR" prefix for labels that are meant to be added to PRs. So we'd have "PR: FATES change" and "PR: FATES Next API". How would that sound to you?

**Comment by ckoven** [comment]
makes sense to me

**Comment by rgknox** [comment]
yup, that sounds fine

**Comment by ekluzek** [comment]
Yeah, that sounds fine I think PR is obvious enough. The other general use category is "tag:" that are used for some items. Maybe they belong there? Are there other labels that would just attach to a PR and not an issue? In looking at the label list I didn't think so.

**Comment by billsacks** [comment]
Okay, I made this change. @ekluzek - currently, tags generally apply to issues, though "simple bfb" applies to both.
