### ISSUE TITLE
ARM Forge Notes Cheyenne

### ISSUE THREAD

**Issue by rgknox** [ESCOMP/CTSM#436]
I have been using the ARM Forge debugger (DDT) and profiler (MAP) with CTSM-FATES on Cheyenne.  I wanted to jot down some of my notes in case others try the same thing, or if others have notes or corrections they would like to contribute.

---

Firstly, the CISL instructions are great.  See: https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/code-development-support/running-ddt-map-and-pr-jobs

---

Summary of the overall process of debugging or profiling went like this, note that some things happen while logged directly into cheyenne and some happen on my desktop (local client):

1) (on cheyenne) Make slight adjustments to the cheyenne machine config file
2) (on cheyenne) Build a run with the debug=TRUE
3) (on local client) Install the ARM forge application to your local client, follow the CISL instructions linked above
4) (on local client) Run the MAP or ARM application, remote connect to cheyenne, again follow CISL instructions for connecting to cheyenne    
5) (on cheyenne) execute ./case.submit     

---

Notes, details on each step:

1) (on cheyenne) Adjust machine file:

- one could hack/modify the cime/config/cesm/machines/config_machines.xml  or the user specified override (I forget where that is put). I just hacked the main file temporarily.  Note that layout and threading information can be submitted in the ARM client later so that is removed.  @ekluzek @billsacks new mpilib entry for arm forge, better way to do this?

- important note: in the example below I am using the **profiler**, to use the DDT debugger change "map --connect" to "ddt --connect"

```
diff --git a/config/cesm/machines/config_machines.xml b/config/cesm/machines/config_machines.xml
index 755fbbf..2747e65 100644
--- a/config/cesm/machines/config_machines.xml
+++ b/config/cesm/machines/config_machines.xml
@@ -269,13 +269,7 @@
     <MAX_MPITASKS_PER_NODE>36</MAX_MPITASKS_PER_NODE>
     <PROJECT_REQUIRED>TRUE</PROJECT_REQUIRED>
     <mpirun mpilib="default">
-      <executable>mpiexec_mpt</executable>
-      <arguments>
-       <arg name="anum_tasks"> -np $TOTALPES</arg>
-       <arg name="labelstdout">-p "%g:"</arg>
-       <!-- the omplace argument needs to be last -->
-       <arg name="zthreadplacement"> omplace -tm open64 </arg>
-      </arguments>
+      <executable>map --connect</executable>
     </mpirun>
     <mpirun mpilib="openmpi">
       <executable>mpirun</executable>
@@ -301,6 +295,7 @@
       <modules>
        <command name="purge"/>
        <command name="load">ncarenv/1.2</command>
+       <command name="load">allinea-forge/18.0.2 </command>
       </modules>
       <modules compiler="intel">
        <command name="load">intel/17.0.1</command>
```

2) (on cheyenne) Build a run with the debug=TRUE

- There may be better ways to fine tune this step, but the key to both the ARM debugger and profiler is to make sure that all code is compiled with the "-g" flag.  For profiling, we may want to removing extensive checking like math overflows and array/pointer bounds and just make sure debug hooks are compiled in.

> ./xmlchange DEBUG=TRUE

3) (on local client) Install the ARM forge application

- Make sure you install the exact same ARM forge version on your local client, as the version that you use on cheyenne.  In the machine file above, you can see I am loading version 18.0.2, which is the default at the time of this note.  

5) (on cheyenne) execute ./case.submit  

-- I have the allinea forge module loaded before running the case submit script, but I think that as long as it is loaded like all the other module dependencies in the machine file, this is not necessary. Anyway: 
> module load allinea-forge/18.0.2

-- Run the case submit script

> ./case.submit

-- Accept the connection request prompted by the local ARM forge client

-- A dialog box will pop up.  Note that if you are running a single site case, you probably can just accept all the defaults. I have been doing this for a 1x1 brazil case.   But if this was a gridded simulation, here is where you specify the MPI execution directives and threading.  I'm currently doing a 1x1 case, but I think I might be able to reproduce a gridded run I did earlier.  

---

After this last step, everything is done via the gui, and since it runs on a local client, it runs smoothly

**Comment by billsacks** [comment]
Thanks very much for this! Could you start a page on the wiki with this information? That will be easier to find in the future than this issue.

**Comment by rgknox** [comment]
Sure thing @billsacks .  I wanted to see if other's had notes or questions and would convert to a wiki after suitable gestation.  But, I suppose other users can mark up the wiki too?

**Comment by rgknox** [comment]
@ekluzek those last set of notes don't seem to be accessible to me

**Comment by ekluzek** [comment]
OK updated the sharing so anyone with the link can view rather than just those in UCAR.

**Comment by rgknox** [comment]
@ekluzek , it looks like in your example, you were able to keep the specification of the "--np" and "--procs_per_node" flags in the machine file, and they passed to the debugger with no problem.

**Comment by ekluzek** [comment]
Yes, you can set the number of tasks so you don't have to correct it when the GUI comes up. You can also set the open-MP threads, but that's trickier. The cime issue talks about doing that.

**Comment by billsacks** [comment]
To do: move this to wiki

**Comment by jedwards4b** [comment]
@glemieux what did you use for the mpirun command?  I think that using mpirun_mpt will solve the array services error.

**Comment by glemieux** [comment]
@jedwards4b I gave that a shot as well, but I'm still getting the same error.  One of the things I'm struggling to understand here is which `mpirun` xml setting will get used and why.  I noticed that the "default" settings (which uses `mpiexec_mpt`) are not getting used if I check `./preview_run`;  Instead the the `mpilib="mpt"` settings are being run.  I'm guessing this is because of the shared queue setting?  As such I've been adding the `ddt --connect` command there.

Btw, if you have time and can take a look my case is here: /glade/scratch/glemieux/clmed-tests/my-test-name.fates.cheyenne.Ccd30b77b-Fd95e3564.  I saved a .back version of my original xml config file in that directory as well.

**Comment by jedwards4b** [comment]
Looking at your case - if you only need to use 1 task why not use mpi-serial?  That would solve the mpirun issue.   If you really do need to use mpi, then you should use the regular queue and not the shared queue.  (./xmlchange JOB_QUEUE=regular)

**Comment by glemieux** [comment]
I was wondering why not use mpi-serial as well, but I guess this shows how much I still have to learn in using ctsm.  My assumption was that cime would automatically handle the setup with mpi-serial based on the specification of the given resolution (in this case the 1x1 brazil).  For background, I just randomly picked that resolution.

**Comment by ekluzek** [comment]
It does recognize that it only needs one processor. In the past we had some logic to try to switch to mpi-serial, but I think we had some issues with it and removed it (or maybe it's still in there, but not working). I'd have to go back through and look at the history to figure out why. I'll try to do that...

**Comment by samsrabin** [comment]
Closing this; it will of course still be available for reference if needed.
