### ISSUE TITLE
Illegal argument aliasing caught by nag6.2

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#438]
### General bug information

**CTSM version you are using:** clm5.0.dev008, but it looks like the offending module (PhotosynthesisMod) hasn't changed between then and latest master. I'm using cime5.6.9.

**Does this bug cause significantly incorrect results in the model's science?** Unknown, but probably not.

**Configurations affected:** PHS, I think

### Details of bug

nag6.2 apparently adds a new check: You cannot pass the same actual argument to two dummy arguments of a subroutine if the subroutine modifies one of those arguments. Apparently this is not allowed by the fortran standard (https://stackoverflow.com/questions/7142233/fortran-passing-same-array-as-two-dummy-arguments-to-subroutine and https://software.intel.com/en-us/blogs/2009/07/10/doctor-fortran-in-ive-come-here-for-an-argument-side-2/), but our compilers haven't been checking it up until now.

When trying to run on the updated hobart, we get this death:

```
Runtime Error: /home/sacks/cesm_code/cism-wrapper/components/clm/src/biogeophys/PhotosynthesisMod.F90, line 4076: Assignment to GS_MOL_SUN affects dummy argument GS0SUN
Program terminated by fatal error
/home/sacks/cesm_code/cism-wrapper/components/clm/src/biogeophys/PhotosynthesisMod.F90, line 4076: Error occurred in PHOTOSYNTHESISMOD:CI_FUNC_PHS
/home/sacks/cesm_code/cism-wrapper/components/clm/src/biogeophys/PhotosynthesisMod.F90, line 3863: Called by PHOTOSYNTHESISMOD:BRENT_PHS
/home/sacks/cesm_code/cism-wrapper/components/clm/src/biogeophys/PhotosynthesisMod.F90, line 3672: Called by PHOTOSYNTHESISMOD:HYBRID_PHS
/home/sacks/cesm_code/cism-wrapper/components/clm/src/biogeophys/PhotosynthesisMod.F90, line 3260: Called by PHOTOSYNTHESISMOD:PHOTOSYNTHESISHYDRAULICSTRESS
/home/sacks/cesm_code/cism-wrapper/components/clm/src/biogeophys/CanopyFluxesMod.F90, line 850: Called by CANOPYFLUXESMOD:CANOPYFLUXES
/home/sacks/cesm_code/cism-wrapper/components/clm/src/main/clm_driver.F90, line 543: Called by CLM_DRIVER:CLM_DRV
/home/sacks/cesm_code/cism-wrapper/components/clm/src/cpl/lnd_comp_mct.F90, line 451: Called by LND_COMP_MCT:LND_RUN_MCT
/home/sacks/cesm_code/cism-wrapper/cime/src/drivers/mct/main/component_mod.F90, line 728: Called by COMPONENT_MOD:COMPONENT_RUN
/home/sacks/cesm_code/cism-wrapper/cime/src/drivers/mct/main/cime_comp_mod.F90, line 2662: Called by CIME_COMP_MOD:CIME_RUN
/home/sacks/cesm_code/cism-wrapper/cime/src/drivers/mct/main/cime_driver.F90, line 103: Called by CIME_DRIVER
[h019.cgd.ucar.edu:mpi_rank_15][error_sighandler] Caught error: Aborted (signal 6)
```

At least in this case, it looks like the duplicated gs0sun and gs0sha dummy arguments in ci_func_PHS (which duplicate the gs_mol_sun and gs_mol_sha arguments) aren't serving any purpose: the gs0* arguments could be dropped and the gs_mol_* arguments could be used in the call to calcstress from ci_func_PHS. But I haven't looked at other calls to ci_func_PHS to see if it's always safe to drop gs0sun and gs0sha. (And someone should double-check my feeling even for this case.)

### Important details of your setup / configuration so we can reproduce the bug

I saw this with SMS_D_Ld5_P24x1.T31_g37_gl20.I1850Clm50SpG.hobart_nag.cism-test_coupling, using a standalone cism checkout (ESCOMP/cism-wrapper@9b3dc61).

**Comment by billsacks** [comment]
See also 
https://www.nag.co.uk/nagware/np/r62_doc/relnotes.html#AUTOTOC_7

**Comment by olyson** [comment]
I can help with this if needed.

**Comment by ekluzek** [comment]
OK, I made a simple change in the code to get around this and the particular test in question now PASSes. There are some screwy things going on with this part of the code, but I'm ignoring that for now. I did notice that an array wasn't being initialized, so I'm having it initialized to zero. This might have bigger ramifications than the actual important change. So it'll be important to evaluate if answer changes with this...

Here's what I did.

``` fortran
diff --git a/src/biogeophys/PhotosynthesisMod.F90 b/src/biogeophys/PhotosynthesisMod.F90
index 8b6e7086..64770258 100644
--- a/src/biogeophys/PhotosynthesisMod.F90
+++ b/src/biogeophys/PhotosynthesisMod.F90
@@ -3578,6 +3578,8 @@ subroutine hybrid_PHS(x0sun, x0sha, p, iv, c, gb_mol, bsun, bsha, jesun, jesha,
     bflag = .false.
     b0sun = -1._r8
     b0sha = -1._r8
+    gs0sun = 0._r8
+    gs0sha = 0._r8
     bsun  = 1._r8
     bsha  = 1._r8
     iter1 = 0
@@ -3769,6 +3771,8 @@ real(r8), intent(out)   :: xsha                 ! independent variable of the si
     type(temperature_type) , intent(in)       :: temperature_inst
     !------------------------------------------------------------------------------
     ! !LOCAL VARIABLES:
+    real(r8)                :: gs0sun               ! sunlit leaf stomatal conductance (umol H2O/m**2/s)
+    real(r8)                :: gs0sha               ! shaded leaf stomatal conductance (umol H2O/m**2/s)
     integer                 :: phase                ! sun==1, sha==2
     integer , parameter     :: nphs = 2             ! number of phases for sun/shade
     integer , parameter     :: itmax = 20           ! maximum number of iterations
@@ -3860,7 +3864,9 @@ real(r8), intent(out)   :: xsha                 ! independent variable of the si
           endif
        enddo
        
-       call ci_func_PHS(x,b(sun), b(sha), fb(sun), fb(sha), ip, iv, ic, bsun, bsha, bflag, gb_mol, gs_mol_sun, gs_mol_sha,&
+       gs0sun = gs_mol_sun
+       gs0sha = gs_mol_sha
+       call ci_func_PHS(x,b(sun), b(sha), fb(sun), fb(sha), ip, iv, ic, bsun, bsha, bflag, gb_mol, gs0sun, gs0sha, &
             gs_mol_sun, gs_mol_sha, jesun, jesha, cair, oair, lmr_z_sun, lmr_z_sha, par_z_sun, par_z_sha, rh_can, &
             qsatl, qaf, atm2lnd_inst, photosyns_inst, canopystate_inst, waterstate_inst, soilstate_inst, &
             temperature_inst, waterflux_inst)

```

**Comment by ekluzek** [comment]
Fixed in ctsm1.0.dev003
