### ISSUE TITLE
Options for Filtering Averages in Output (albedo)

### ISSUE THREAD

**Issue by rgknox** [ESCOMP/ctsm#453]
@jenniferholm and I were investigating surface albedos.   Albedo of short-wave radiation, is by nature and definition, something that can only be evaluated when there is light.

We noticed that when the zenith angle is < 0, patches are then defined as part of the "novegsol" filter, and thus the "ALBD" diagnostic uses the "albgrd" value (which seems to be some average soil albedo from a table of map).

https://github.com/ESCOMP/ctsm/blob/master/src/biogeophys/SurfaceAlbedoMod.F90#L952

We were wondering if there could be an alternative to this (or we are interpreting this incorrectly), where the array that is passed to the history mean be given a "don't average me" flag, so that this calculation is only performed over the relevant time window with the relevant quantities.

**Comment by billsacks** [comment]
@rgknox just going through some old issues. Is this still something you'd like feedback on, or should we close it (apologetically) since it never generated any discussion?

**Comment by rgknox** [comment]
@billsacks , I think it is fair to close it.  I suppose if there is a need for a different metric, we could submit a PR with that change or addition, and sort things out from there.

**Comment by serbinsh** [comment]
Is this possibly leading to this response  I am seeing with hourly albedo output? I would expect that it would be ~1 in the winter and near 0.15 in the summer. But daily ranges are ~0.15 to 1.  Or I am doing something wrong

<img width="1009" alt="Screen Shot 2020-02-08 at 8 47 30 AM" src="https://user-images.githubusercontent.com/3067369/77101156-3e344500-69ed-11ea-8295-593327429e2d.png">

**Comment by dlawrenncar** [comment]
Not sure I fully understand the question, but I'll respond by answering
what I think the question might be.  :)

In CLM, albedo is set to 1 at night so if you try to output and analyze
daily average albedo directly, it will be aliased to higher than correct
values.  We generally do not evaluate albedo output from the model
directly, but instead evaluate albedo from, for example, monthly or daily
average solar fields (can split into direct and diffuse and visible and NIR
or consider full spectrum).  Not sure if this is helpful or not.

**Comment by rgknox** [comment]
Thanks @dlawrenncar, that is helpful.  sounds like most users should be calculating albedo by manually generating the ratio of upwelling/downwelling sw radiation then.
