### ISSUE TITLE
mkmapdata.sh map creation fails using ESMF with PGI

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#460]
### Brief summary of bug

The creation of mapping files for mksurfdata_map fails on the SCRIPgrid_3minx3min_MODISwcspsea_c151020.nc when using ESMF6.3.0rp1 
with the PGI compiler

### General bug information

**CTSM version you are using:** some version of "clm5"

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** Just creation of mapping files

### Details of bug

Edouard Davin of ETH found this problem.

### Important details of your setup / configuration so we can reproduce the bug

Edouard found this on a machine he uses at ETH, with the version of ESMF they have installed there. It "might" be "rosa" as that's the supported machine we have for ETH in cime.

### Important output or errors that show the problem

```
edavin@daint105:/scratch/snx3000/edavin/step1> ESMF_RegridWeightGen -s /scratch/snx3000/edavin/cesm_inputdata/lnd/clm2/mappingdata/grids/SCRIPgrid_3minx3min_MODISwcspsea_c151020.nc -d /scratch/snx3000/edavin/cesm_inputdata/lnd/clm2/mappingdata/grids/SCRIPgrid_3minx3min_MODISwcspsea_c151020.nc -w weight_file.nc
 Starting weight generation with these inputs: 
   Source File: /scratch/snx3000/edavin/cesm_inputdata/lnd/clm2/mappingdata/grids/SCRIPgrid_3minx3min_MODISwcspsea_c151020.nc
   Destination File: /scratch/snx3000/edavin/cesm_inputdata/lnd/clm2/mappingdata/grids/SCRIPgrid_3minx3min_MODISwcspsea_c151020.nc
   Weight File: weight_file.nc
   Source File is in SCRIP format
   Source Grid is a global grid
   Source Grid is a logically rectangular grid
   Destination File is in SCRIP format
   Destination Grid is a global grid
   Destination Grid is a logically rectangular grid
   Regrid Method: bilinear
   Pole option: ALL
   Norm Type: dstarea

 ERROR: Problem on processor            0 . Please see the PET*.RegridWeightGen.Log files for a traceback.


edavin@daint105:/scratch/snx3000/edavin/step1> cat PET0.RegridWeightGen.Log
20180713 151212.882 INFO             PET0 Running with ESMF Version 6.3.0rp1
20180713 151230.800 INFO             PET0 Running with ESMF Version 6.3.0rp1
20180713 151423.516 INFO             PET0 Running with ESMF Version 6.3.0rp1
20180713 151423.942 ERROR            PET0 ESMF_IOScrip.F90:99 ESMF_ScripInq netCDF Status Return Error
20180713 151423.943 ERROR            PET0 ESMF_RegridWeightGen.F90:619 ESMF_RegridWeightGenFile Failure - Internal subroutine call returned Error
20180713 151439.854 INFO             PET0 Running with ESMF Version 6.3.0rp1
20180713 151520.813 INFO             PET0 Running with ESMF Version 6.3.0rp1
20180713 151807.266 INFO             PET0 Running with ESMF Version 6.3.0rp1
20180713 153231.267 ERROR            PET0 Destination id=1699201 NOT found in weight matrix.
20180713 153231.276 ERROR            PET0 ESMCI_Regrid_F.C:267 c_esmc_regrid_create() Arguments are incompatible - There exist destination points (e.g. id=1699201) which can't be mapped to any source cell
20180713 153232.679 ERROR            PET0 ESMCI_Regrid_F.C:434 c_esmc_regrid_create() Arguments are incompatible Internal subroutine call returned Error
20180713 153233.559 ERROR            PET0 ESMF_Regrid.F90:321 ESMF_RegridStore Arguments are incompatible - Internal subroutine call returned Error
20180713 153233.562 ERROR            PET0 ESMF_FieldRegrid.F90:1008 ESMF_FieldRegridStoreNX Arguments are incompatible - Internal subroutine call returned Error
20180713 153233.566 ERROR            PET0 ESMF_RegridWeightGen.F90:1152 ESMF_RegridWeightGenFile Arguments are incompatible - Internal subroutine call returned Error
```

**Comment by ekluzek** [comment]
Currently on cheyenne we use ESMF7.0.0. In the past we've used ESMF 6.3.0r though (and using the above file that Edouard is showing as a problem). So I'm not clear what ESMF versions would have this as a problem.

**Comment by edavin** [comment]
I also tested ESMF version 7.0.1 (compiled with pgi) and I get the same issue:

20180730 110824.826 INFO             PET024 Running with ESMF Version 7.0.1
20180730 110855.949 INFO             PET024 Running with ESMF Version 7.0.1
20180730 111001.681 INFO             PET024 Running with ESMF Version 7.0.1
20180730 111036.397 INFO             PET024 Running with ESMF Version 7.0.1
20180730 112620.365 INFO             PET024 Running with ESMF Version 7.0.1
20180730 112623.643 ERROR            PET024 ESMF_Grid.F90:5161 ESMF_GridCreate Wrong argument specified  - - Bad corner array in SCRIP file
20180730 112623.644 ERROR            PET024 ESMF_Grid.F90:6307 ESMF_GridCreateFrmScrip Wrong argument specified  - Internal subroutine call returned Error
20180730 112623.649 ERROR            PET024 ESMF_Grid.F90:5976 ESMF_GridCreateFrmNCFile Wrong argument specified  - Internal subroutine call returned Error
20180730 112623.649 ERROR            PET024 ESMF_RegridWeightGen.F90:1027 ESMF_RegridWeightGenFile Wrong argument specified  - Internal subroutine call returned Error



So yes, the issue might be with the compiler to build ESMF.

**Comment by ekluzek** [comment]
Closing since this is a WONTFIX for PGI compiler.
