### ISSUE TITLE
Problem running with Crop and using ESMF library -- bad date in paramsfile

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#463]
### Brief summary of bug

DAE_N2_D_Lh12.f10_f10_musgs.I2000Clm50BgcCropGs.cheyenne_intel.clm-DA_multidrv which has a Gregorian calendar fails at runtime, when built with USE_ESMF_LIB=TRUE.

### General bug information

**CTSM version you are using:** release-clm5.0.04

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** Just when USE_ESMF_LIB=TRUE (whichever calendar is used GREGORIAN or NO_LEAP)
### Details of bug

@fvitt found this for a WACCM-X configuration  2000_CAM40%WXIE_CLM50%BGC-CROP_CICE%PRES_DOCN%DOM_MOSART_CISM2%NOEVOLVE_SWAV. A similar case in SP mode 2000_CAM40%WXIE_CLM50%SP_CICE%PRES_DOCN%DOM_RTM_SGLC_SWAV also fails, but with a balance check error, but runs on a cold start.

### Important details of your setup / configuration so we can reproduce the bug

This is on cheyenne with intel compiler. I don't think the resolution matters. It might work with
Clm40 (because WACCM-X does this), but would probably fail with Clm45.

### Important output or errors that show the problem

```
37: clm::TimeSetymd: error return from ESMF_TimeSet: setting get_calday
37: ERROR: CHKRC
43: clm::TimeSetymd: error return from ESMF_TimeSet: setting get_calday
43: ERROR: CHKRC
55: clm::TimeSetymd: error return from ESMF_TimeSet: setting get_calday
55: ERROR: CHKRC
42: clm::TimeSetymd: error return from ESMF_TimeSet: setting get_calday
42: ERROR: CHKRC
47: clm::TimeSetymd: error return from ESMF_TimeSet: setting get_calday
47: ERROR: CHKRC
130:Image              PC                Routine            Line        Source             
130:cesm.exe           00000000041513ED  Unknown               Unknown  Unknown
130:cesm.exe           000000000347B361  shr_abort_mod_mp_         114  shr_abort_mod.F90
130:cesm.exe           000000000347B1E2  shr_abort_mod_mp_          61  shr_abort_mod.F90
130:cesm.exe           00000000008D2EF9  clm_time_manager_        1752  clm_time_manager.F90
130:cesm.exe           00000000008C5F13  clm_time_manager_         396  clm_time_manager.F90
130:cesm.exe           00000000008D1167  clm_time_manager_        1332  clm_time_manager.F90
130:cesm.exe           00000000010C9B47  cnphenologymod_mp        2066  CNPhenologyMod.F90
130:cesm.exe           00000000010432ED  cnphenologymod_mp         407  CNPhenologyMod.F90
130:cesm.exe           0000000002C5AC2E  cndrivermod_mp_cn          73  CNDriverMod.F90
130:cesm.exe           0000000001171D4A  cnvegetationfacad         518  CNVegetationFacade.F90
130:cesm.exe           00000000008B374B  clm_initializemod         449  clm_initializeMod.F90
130:cesm.exe           00000000008454AE  lnd_comp_mct_mp_l         233  lnd_comp_mct.F90

```

**Comment by ekluzek** [comment]
In doing some debugging on this, this comes up in the setting of some Southern Hemisphere max planting dates to 1231. So it's a specific glitch for the Crop model, hence why we didn't see it in CLM40. I'm still not sure why only setting some of these dates is a problem, or why for 1231, which is a valid date.

**Comment by ekluzek** [comment]
I'm able to get this to fail in the much smaller single point case: SMS_D_Lh12.1x1_numaIA.I2000Clm50BgcCropGs.cheyenne_intel.clm-default

**Comment by ekluzek** [comment]
The real problem behind this might be that there is an invalid date in the clm5_params file for 6/31 (when June only has 30 days).

**Comment by mvertens** [comment]
This issue has nothing to do with the gregorian calendar - so I think a new
issue should be raised.

**Comment by mvertens** [comment]
The test I was doing had the calendar as NO_LEAP and still encountered the
problem.

**Comment by ekluzek** [comment]
The original title, said this was tied to the Gregorian calendar, but even the initial error report say's it's independent of calendar. And that's what I've verified as well.

I've also got it working now, with a dataset that has max_NH_planting_date that was 631 (an invalid date) set to 701. And answers are identical for a 5 year test case. Looking at the code in esmf_wrf_timemgr that's the actual time it would set the max planting date to.

Note, also that the clm45 paramsfile has the correct date of 701, it was only the clm50 paramsfile that was incorrect.

It's also disappointing that this problem wasn't more obvious to me in my initial investigation.

**Comment by mvertens** [comment]
Thanks for checking up on this and verifying this problem. Its good to know
that the results are bfb with the fix.

**Comment by mvertens** [comment]
When will a PR with this fix be put in? Not having this is making testing the NUOPC cap in more general situations impossible.

**Comment by ekluzek** [comment]
It's in the queue. Other things have been in front of it that are critical for ctsm. I have a tag in upcoming tags for it.

I'll make sure we talk about this on Mondays CLM CMT meeting.

**Comment by mvertens** [comment]
Thank you!
