### ISSUE TITLE
Should we avoid doing dynamic landunit adjustments for very small changes in area?

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#469]
As I just realized (reported in https://github.com/ESCOMP/ctsm/issues/340#issuecomment-410483131), it _seems_ that changing the PE layout could lead to small, fictitious dynamic landunit adjustment fluxes because the mapping of glacier areas from CISM to CLM will differ by roundoff (at least, that's my suspected reason for the changes reported in that comment). This means that, if you change the PE layout in the middle of a run, even with a non-evolving icesheet, you'll get some small dynamic landunit adjustment fluxes (in the first timestep - both fluxes of water and energy and some adjustments of the belowground C & N states).

As far as I can tell, these adjustments are themselves just roundoff-level, so shouldn't have any significant scientific impact. But they could be confusing if you expected them to be 0: you'd get some non-zero DYNBAL water and energy fluxes, and end up with non-zero C and N stocks under glaciers, when both should be identically zero.

Fixing this so that roundoff-level area changes are ignored should be possible in theory, but would (1) take some investigation as to how to code this; (2) take some care to make sure that we ignore meaningless changes but don't ignore any real changes.

Does anyone feel this is worth fixing, and if so, at what priority? (I especially welcome input from @dlawrenncar @olyson @ekluzek @whlipscomb @gunterl @lofverstrom; but anyone else should feel free to weigh in if you have thoughts.)

(For the record: my feeling is that this isn't worth fixing, but I at least wanted to bring this possible oddity to people's attention.)

**Comment by gunterl** [comment]
Hi Bill,

The way you describe it sounds like this is not worth fixing right now
unless this round off error could propagate somehow in the code with non
small effect which does not sound to be the case. So I would agree with you
that it might be worth fixing but should not be a high priority. It would
be great to reference this issue somewhere outside of this e-mail chain.

Thanks for all of your work.

Gunter

**Comment by billsacks** [comment]
Since nobody else besides Gunter has chimed in about this (and Bill L separately), I'll assume that nobody else cares that much about it, so I'll close it as a wontfix.
