### ISSUE TITLE
Have number of steps to skip balance-check based on time

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#475]
Right now the model is hard-coded to skip the balance check for two steps after a DA-step. This works well for a half-hour time-step. But, is too short for a shorter time step. We think the period should be set to an hour rather than a number of steps. In testing @olyson found this to work well with shorter time steps for a F case.

**Comment by billsacks** [comment]
We should probably still have a minimum of two steps - so, for example, for a one-hour (or two-hour, etc.) time step, we'd still skip the balance check for two steps.
