### ISSUE TITLE
Bare soil g1 should be missing value or zero

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#478]
A user reported the following:

Hi Keith

I hope all is well. I'm working with Peter Franks at the University of Sydney and we've noticed that in the input parameters for CLM5 (specifically in clm5_params.c171117.nc) that the g1 value for conductance-photosynthesis for the 'not_vegetated' PFT is 9. This should be 0 no? This is the case for both the Ball-Berry and Medlyn g1 values (mbbopt and medlynslope, respectively, in the above file). Can this get logged for correcting in the next release?

Regards

Nick.

**Comment by billsacks** [comment]
@dlawrenncar 's feeling: it's not worth making a whole new parameter file just for this, because it can be confusing to have so many different parameter files floating around. So let's wait to do this until we're updating the parameter file for other reasons.

**Comment by ekluzek** [comment]
This is still the case. So we should make sure we fix this in CTSM5.1
