### ISSUE TITLE
InitAccVars for AnnET initializing the wrong variable

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#480]
### Brief summary of bug

It looks like the InitAccVars code for AnnET (now in WaterFluxBulkType.F90) is initializing the wrong variable: It is initializing qflx_evap_tot_col, but I think it should be initializing AnnET.

### General bug information

**CTSM version you are using:** ctsm1.0.dev008. But looking at the git history, this dates back to the introduction of FUN into CTSM, in clm4_5_6_r155.

**Does this bug cause significantly incorrect results in the model's science?** No

As far as I can tell, the incorrect initialization of qflx_evap_tot_col doesn't have any impact on the code: it looks like this variable is reset before it's used later in the driver loop.

The fact that AnnET isn't initialized in InitAccVars may cause incorrect results in the first time step of a cold start run. In general, I think that this missing initialization would break exact restarts, but it looks like this is compensated by incorrectly having AnnET appear in the Restart routine (in general, accumulator variables don't need to explicitly appear in the Restart routines, because the accumulator infrastructure handles this for you).

**Configurations affected:** Runs with FUN active.

### Details of bug

(1) This code block should set AnnET rather than qflx_evap_tot_col:

https://github.com/ESCOMP/ctsm/blob/354ee027cfe4df411d931ce4093e602a46764865/src/biogeophys/WaterFluxBulkType.F90#L449-L452

(2) This restart variable should then be removed:

https://github.com/ESCOMP/ctsm/blob/354ee027cfe4df411d931ce4093e602a46764865/src/biogeophys/WaterFluxBulkType.F90#L533-L543

**Comment by ekluzek** [comment]
@billsacks yes, this fix looks correct to me as well.

I'm just going to note that this fix will JUST go into CESM2.2 development and NOT cesm2.1. I think that's fine. We could move it to cesm2.1, but because of the filename change it might not slide right in. I also don't think it's required for CESM2.1.

**Comment by billsacks** [comment]
Actually, I think this fix won't even change answers for cold start, because the code had this

https://github.com/ESCOMP/ctsm/blob/354ee027cfe4df411d931ce4093e602a46764865/src/biogeophys/WaterFluxBulkType.F90#L386

(which I'll now be able to remove as redundant).
