### ISSUE TITLE
nlevcan>1 is broken

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#484]
### Brief summary of bug

In talking with @olyson this is expected. But, the model currently doesn't run if you change nlevcan to something not equal to 1. Eventually want want nlevcan>1 to be a valid model option, so we want to leave the current support in, but we recognize that it's broken and will become more broken in time until it is worked on.

One thing we should do going forward is to document new things that are coming in that won't work or don't take nlevcan>1 into account. So those areas can be looked at when it does come in.

### General bug information

**CTSM version you are using:** ctsm1.0.dev007

**Does this bug cause significantly incorrect results in the model's science?** Maybe?

**Configurations affected:** All

### Details of bug

I ran a case where I set nlevcan=235. Note, I had to turn megan off and do a cold-start to get it to run. megan already can't run with nlevcan>1 and the interpolation can't handle a change in nlevcan. It ran for a few time steps and then failed inside of LUNA.

**Comment by billsacks** [comment]
You are listing this as wontfix, but it's open and assigned to you. So should we get rid of the wontfix label?

**Comment by ekluzek** [comment]
I wanted to leave it open for possible discussion for at least a while. I plan to close it and leave the wontfix label if there isn't more discussion. The main point is just to be aware that new features may not take into account nlevcan>1 so we should try to document potentially problems when we see them. We aren't planning on fixing it until some time in the future.
