### ISSUE TITLE
intel debug error

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/ctsm#485]
### Brief summary of bug
/home/jedwards/UFSCOMP/components/clm/src/main/glc2lndMod.F90(329): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.

/home/jedwards/UFSCOMP/components/clm/src/main/glc2lndMod.F90(330): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.

### General bug information

**CTSM version you are using:**  clm5.0.dev012-12-g88fc4799

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]

**Configurations affected:** [Fill this in if known.]

### Details of bug
Currently Loaded Modulefiles:
  1) tool/hdf5/1.8.20/intel
  2) tool/netcdf/4.6.1/intel
  3) compiler/intel/18.0.3
  4) mpi/intel/mvapich2-2.3rc2-intel-18.0.3

SMS_D.f19_g16.F2000Nuopc.hobart_intel

### Important details of your setup / configuration so we can reproduce the bug

[Specify anything relevant: the compset, resolution, machine, compiler, any xml or namelist changes, etc. You don't have to repeat anything that you have already noted above.]

### Important output or errors that show the problem

[Fill this in with anything relevant that you haven't already noted; if there is nothing to add, delete this section.]

**Comment by billsacks** [comment]
This issue looks specific to the branch you're using for the Nuopc work - the offending lines are not on master, or on any branch in this repository, as far as I know. So I'm going to close this issue here.

**Comment by mvertens** [comment]
@jedwards4b - yes this is must be something I did. I'll look at it tomorrow.
