### ISSUE TITLE
Set tracer versions of atm2lnd water variables

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#487]
As @mathewvrothstein recognized: One of the first steps in getting water tracers consistent with bulk will be setting tracer versions of atm2lnd water variables. For tracers that actually come from other components (like particular water isotopes), I imagine that we'll set the tracer quantities alongside the bulk in lnd_import. For now, though, we just want tracers set up artificially, as fixed constants times the incoming bulk quantity.

There are three pieces to this:

(1) The lower-level function that does this updating.

This is kind of like the function in CNCIsoFluxMod, but we'll also need a special form that, rather than accepting two states, just accepts a fixed ratio.

(2) When is this called?

This ties in with a broader question of where in the driver loop we'll do the updating of the water tracer fluxes. Ideally we'd do this only in a few places - similar to the few places where this is done in CNCIsoFluxMod. At least in the near-term, though, we may have to do this in more places, due to the fact that the biogeophysics has state updates at a lot of points.

That said: it's not too important to resolve that question right now. For now, we can have a separate call to calculate tracer fluxes for the atm2lnd fluxes, near the start of the driver loop. Later, we may be able to merge this with some other update, if the atm2lnd tracer fluxes aren't actually needed until later in the driver loop: We can update a given tracer flux any time up until the time it's actually needed, as long as this update happens before its "source" state has changed (see also the discussion in #490 ).

We can probably put this call after the call to `downscale_forcings`:  I think that no water-related atm2lnd stuff is used before that point in the driver loop, so it's safe to wait until then to calculate the tracer versions of atm2lnd variables. However, note that this means that tracers and bulk will be inconsistent for these variables until this point. I think that's okay; it just means that you can't arbitrarily put the consistency checks at any point in the driver loop. i.e., we can put a tracer consistency check call after this call to update atm2lnd tracers post-downscale_forcings, but not before then. In the very near-term, we may want to split this into two pieces: (i) update tracers for the non-downscaled quantities very first thing in the driver loop; call consistency checks (should pass); (ii) after downscale_forcings, update tracers for the downscaled quantities; again call consistency checks (should still pass). Pretty soon, though (perhaps even before merging this to master), I think I'd like to merge these two pieces, so that all of the atm2lnd tracer updates happen in (ii), and we do the first tracer consistency check at or after (ii). The main reason to separate these initially is to support incrementally getting tracer consistency in place - particularly for the pieces of code between the start of the driver loop and the call to downscale_forcings.

(3) How is this called?

I'm imagining a routine in WaterType like set_atm2lnd_tracers

This will only set the tracers that aren't set directly in lnd_import. I expect that tracers that actually come from the atm / rof will be set in lnd_import, so this routine will just be responsible for computing atm2lnd values for tracers for which we don't have explicit input values, and have to assume some value based on the bulk quantity.

Then this will have code like this:

```Fortran
  ! ------------------------------------------------------------------------
  ! WaterType.F90: set_atm2lnd_tracers()
  ! ------------------------------------------------------------------------

  do i = 1, this%num_tracers
     if (this%tracer_info(i)%has_fixed_ratio()) then
        call this%wateratm2lnd_tracer_inst(i)%set_vals_from_bulk(this%wateratm2lndbulk_inst)
     end if
  end do

  ! ------------------------------------------------------------------------
  ! Wateratm2lndType.F90: set_vals_from_bulk(bulk_inst)
  ! ------------------------------------------------------------------------

  ! forc_q isn't actually a flux, but we're abusing the flux routine for this purpose
  ! because the calculation we want is the same as for a flux
  call water_tracer_flux_calc_fixed_ratio( &
       tracer_flux = this%forc_q_not_downscaled_grc(begg:endg), &
       bulk_flux = bulk_inst%forc_q_not_downscaled_grc(begg:endg), &
       ratio = this%info%get_fixed_ratio())

  call water_tracer_flux_calc_fixed_ratio( &
       tracer_flux = this%forc_rain_not_downscaled_grc(begg:endg), &
       bulk_flux = bulk_inst%forc_rain_not_downscaled_grc(begg:endg), &
       ratio = this%info%get_fixed_ratio())

  call water_tracer_flux_calc_fixed_ratio( &
       tracer_flux = this%forc_snow_not_downscaled_grc(begg:endg), &
       bulk_flux = bulk_inst%forc_snow_not_downscaled_grc(begg:endg), &
       ratio = this%info%get_fixed_ratio())

  do c = begc, endc
     if (col%active(c)) then
        g = col%gridcell(c)
        forc_q_not_downscaled_tracer_col(c) = this%forc_q_not_downscaled_grc(g)
        precip_not_downscaled_tracer_col(c) = &
             this%forc_rain_not_downscaled_grc(g) + &
             this%forc_snow_not_downscaled_grc(g)

        ! the following lines will be done redundantly for every tracer; I'm not sure if
        ! it's worth trying to optimize this:
        forc_q_not_downscaled_bulk_col(c) = bulk_inst%forc_q_not_downscaled_grc(g)
        precip_not_downscaled_bulk_col(c) = &
             bulk_inst%forc_rain_not_downscaled_grc(g) + &
             bulk_inst%forc_snow_not_downscaled_grc(g)
     end if
  end do

  ! forc_q isn't actually a flux, but we're abusing the flux routine for this purpose
  ! because the calculation we want is the same as for a flux
  call water_tracer_flux_calc( &
       tracer_flux = this%forc_q_downscaled_col(begc:endc), &
       bulk_flux = bulk_inst%forc_q_downscaled_col(begc:endc), &
       tracer_source = forc_q_not_downscaled_tracer_col(begc:endc), &
       bulk_source = forc_q_not_downscaled_bulk_col(begc:endc))

  call water_tracer_flux_calc( &
       tracer_flux = this%forc_rain_downscaled_col(begc:endc), &
       bulk_flux = bulk_inst%forc_rain_downscaled_col(begc:endc), &
       tracer_source = precip_not_downscaled_tracer_col(begc:endc), &
       bulk_source = precip_not_downscaled_bulk_col(begc:endc))

  call water_tracer_flux_calc( &
       tracer_flux = this%forc_snow_downscaled_col(begc:endc), &
       bulk_flux = bulk_inst%forc_snow_downscaled_col(begc:endc), &
       tracer_source = precip_not_downscaled_tracer_col(begc:endc), &
       bulk_source = precip_not_downscaled_bulk_col(begc:endc))

  ! ------------------------------------------------------------------------
  ! water_tracer_flux_calc_fixed_ratio(tracer_flux, bulk_flux, ratio)
  !
  ! We may also need a version of this with a filter, as is done in CIsoFluxCalc (or at
  ! least using an 'active' array). But the gridcell-level quantities don't have a
  ! filter, and all gridcells are active implicitly.
  ! ------------------------------------------------------------------------

  my_lbound = lbound(tracer_flux)
  my_ubound = ubound(tracer_flux)
  do i = my_lbound, my_ubound
     tracer_flux(i) = bulk_flux(i) * ratio
  end do

  ! ------------------------------------------------------------------------
  ! water_tracer_flux_calc(tracer_flux, bulk_flux, tracer_source, bulk_source)
  ! Calculates a tracer flux based on a bulk flux, for a flux without fractionation
  !
  ! We may also need a version of this with a filter, as is done in CIsoFluxCalc. Or at
  ! least use an 'active' array.
  ! ------------------------------------------------------------------------

  my_lbound = lbound(tracer_flux)
  my_ubound = ubound(tracer_flux)
  do i = my_lbound, my_ubound
     if (bulk_source(i) == 0._r8) then
        if (tracer_source(i) == 0._r8) then
           tracer_flux(i) = 0._r8
        else
           ! tracer_source is non-zero despite bulk_source being 0. Carbon isotope code
           ! sets the flux to 0 in this case. This seems like an error, though: How can we
           ! have tracer state when we have 0 bulk state? It seems like this either would
           ! have arisen from a coding error or a numerical issue; to deal with the
           ! latter, we might need some code (elsewhere) that sets the tracer state to 0
           ! if the bulk state is 0 and the tracer state is non-zero. In any case, I feel
           ! better about aborting in this case.
           call endrun()  ! fill this in with a message
        end if
     else
        tracer_flux(i) = bulk_flux(i) * (tracer_source(i)/bulk_source(i))
     end if
  end do
```

(Note that #486 raises some similar questions regarding code structure, such as whether we have a wrapper routine in WaterType.)

**Comment by billsacks** [comment]
@davidnoone I wanted to bring this to your attention in case you'd like to provide feedback - though it's also fine if you'd prefer to wait to look until there's some real, working code.

**Comment by davidnoone** [comment]
@billsacks Looks like a solid plan to me!  Your comments in point 2 sound about right. For testing I suggest configuring with 3 tracers, with fixed ratios of 1.0, 0.9 and 0.5. Arguably a test with a ratio of 0.01 and something larger than one (say, 7, a happy prime!) would also be handy to exercise the code.

A minor detail, rather than "has_fixed_ratio()", consider something like "initialize_fixed_ratio()", or "forcing_fixed_ratio()" since it should only be used at input stages. The internal code would not need to know this (other than for debugging).

The code structure looks robust too. The last part, with a call to endrun, becomes an important detail. As you point out in the comment there is potential for mass balance problems, or (and) decoupling between the tracers and bulk here. Choices in the exception handling can compound to large errors. We may not be able to handle this generically (TBD).

**Comment by billsacks** [comment]
@davidnoone thanks, once again, for your time giving feedback on this. A few follow-ups:

> For testing I suggest configuring with 3 tracers, with fixed ratios of 1.0, 0.9 and 0.5. Arguably a test with a ratio of 0.01 and something larger than one (say, 7, a happy prime!) would also be handy to exercise the code.

Based on the discussion in #357, I had gathered that it was valuable to have a tracer with a very small ratio, say, 1e-10. Is that true? So I had imagined using tracers with ratios of 1.0, 0.1 and something like 1e-10. But I'm happy to defer to your intuition on what would be most useful here.

Would you ever have a tracer with a ratio greater than 1 in practice? If so, we can add a test tracer with a > 1 ratio. But if this would never occur in practice, then I'm a little worried that we'd end up spending extra effort making code more general than it really needs to be.

> A minor detail, rather than "has_fixed_ratio()", consider something like "initialize_fixed_ratio()", or "forcing_fixed_ratio()" since it should only be used at input stages. The internal code would not need to know this (other than for debugging).

I wasn't very clear here. I'm imagining that _all_ tracers will have some "standard" ratio that is used for initialization purposes. The "has_fixed_ratio()" logical function basically tells us whether this is a test tracer whose ratio _always_ should stay fixed at the fixed ratio – and thus, whether this tracer should be included in the tracer consistency check.

**Comment by davidnoone** [comment]
> Based on the discussion in #357, I had gathered that it was valuable to have a tracer with a very small ratio, say, 1e-10. Is that true?

Yep. 0.9 and 0,5 are an easy starting place. 1e-10 will be tough. In the end we'll test with several values.

> Would you ever have a tracer with a ratio greater than 1 in practice? If so, we can add a test tracer with a 1 ratio. 

The code should support it. The ratio should be coded as arbitrary. 
Usually < 1 is sensible. However, some tracers could be configured larger than this. In CAM for example we have numerical schemes that use the tracer infrustructure to trace other things, not just fractional concentration. Not limiting the concentration is essential for these, and consequently not placing this limit in the code now will be a godsend later.

> "has_fixed_ratio()" logical function
Right, yeah, that's fine. My suggestion was really just a name which gives that intent. 
Partly to discourage future developers from accidentally hard coding the constant ratio into fluxes (or states!). Consider:

! good
tracer_flux(m) = bulk_flux * (tracer_state(m)/bulk_state)

! bad - hijacks the scheme and prescribes the answer!
if tracer(m).has_fixed_ratio()
tracer_flux(m) = bulk_flux * standard_ratio(m)

**Comment by billsacks** [comment]
Great points - thanks a lot!

**Comment by billsacks** [comment]
I think we need to be more careful about how to set the tracer versions of rain and snow than I suggested in my original comment: This will depend on whether we're doing downscaling or not. So I think we want something like this pseudo-code:

```Fortran
  if (repartition_rain_snow) then
     rain_source_bulk = rain_bulk_grc + snow_bulk_grc
     snow_source_bulk = rain_bulk_grc + snow_bulk_grc
     ! and similarly for tracers
  else
     rain_source_bulk = rain_bulk_grc
     snow_source_bulk = snow_bulk_grc
     ! and similarly for tracers
  end if
```

Although, if we want to be rigorous, I think we want to do something better than what we currently have in the `if (repartition_rain_snow)` conditional. I'll open a separate issue to address that.

**Comment by billsacks** [comment]
Okay, I think I see how to do the more rigorous setting of the tracer versions of rain and snow. It shouldn't be too hard, so I'll do it as part of this issue.

We need to be explicit about the `rain_to_snow` and `snow_to_rain` fluxes that are currently implicit in the rain-snow repartitioning. This will look like the following pseudo-code:

```Fortran

  ! The following calculations are done on the bulk:
  if (rain > rain_orig) then
     snow_to_rain = rain - rain_orig
     rain_to_snow = 0
  end if
  if (snow > snow_orig) then
     rain_to_snow = snow - snow_orig
     snow_to_rain = 0
  end if

  ! Then, for each tracer:

  call water_tracer_flux_calc( &
       tracer_flux = rain_to_snow_tracer_col(begc:endc), &
       bulk_flux = bulk_inst%rain_to_snow_col(begc:endc), &
       tracer_source = forc_rain_not_downscaled_tracer_col(begc:endc), &
       bulk_source = forc_rain_not_downscaled_bulk_col(begc:endc))

  call water_tracer_flux_calc( &
       tracer_flux = snow_to_rain_tracer_col(begc:endc), &
       bulk_flux = bulk_inst%snow_to_rain_col(begc:endc), &
       tracer_source = forc_snow_not_downscaled_tracer_col(begc:endc), &
       bulk_source = forc_snow_not_downscaled_bulk_col(begc:endc))

  do c = bounds%begc, bounds%endc  ! or operate over a filter
     this%forc_rain_downscaled_col(c) = forc_rain_not_downscaled_tracer_col(c) + &
          snow_to_rain_tracer_col(c) - rain_to_snow_tracer_col(c)
     this%forc_snow_downscaled_col(c) = forc_snow_not_downscaled_tracer_col(c) + &
          rain_to_snow_tracer_col(c) - snow_to_rain_tracer_col(c)
  end do
```
