### ISSUE TITLE
total_plant_stored_h2o_col should be set upon restart

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#510]
### Brief summary of bug

`total_plant_stored_h2o_col` is referenced early in the driver loop, when computing total water content for the sake of dynamic landunits adjustments as well as water balance checks. However, as far as I can tell, it isn't set until CanopyFluxes (call clm_fates%wrap_hydraulics_drive). I believe this means that things will be done wrong in the first time step after restart – and possibly the first time step after cold start – in a run with FATES.

### General bug information

**CTSM version you are using:** ctsm1.0.dev011

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** Runs with FATES

**Comment by billsacks** [comment]
@rgknox could you take a look at this?

**Comment by billsacks** [comment]
(Not urgent, but should be looked at at some point.)

**Comment by rgknox** [comment]
Sure thing @billsacks

**Comment by rgknox** [comment]
tagging @xuchonggang and @bchristo

**Comment by jbeisman** [comment]
Brad and I will check on this early next week.

Yours
Chonggang

**Comment by xuchongang** [comment]
Based on the discussion with Brad, this bug echos well with the current behaviors of mass balance error for the first time step. Hope to resolve it this week.

**Comment by billsacks** [comment]
Just making sure this is hasn't slipped through the cracks.

**Comment by xuchongang** [comment]
@billsacks and @rgknox , for the ELM, it is set as zero for cold start, which should be ok. However, for the restart, it need to be fed into the restart file. We have not yet finished the restart component for hydraulics, but it should be a task to be done.
