### ISSUE TITLE
CRUNCEP V5 bug

### ISSUE THREAD

**Issue by nanr** [ESCOMP/ctsm#513]
### Brief summary of bug

i-case datm CRUNCEP V5 points to wrong domain file: 
                :  V4 points to domain.lnd.360x720_cruncep.130305.nc   !! mask = 1 everywhere     
        BAD:   **V5 points to domain.cruncep.V5.c2013.0.5d.nc**        !! doesn't have Antarctica
                :  V5 points to domain.lnd.360x720_cruncep.130305.nc  !! mask = 1 everywhere.
        NEW:  V7 points to domain.lnd.360x720_cruncep.130305.nc  !! mask = 1 everywhere.

### General bug information
CRUNCEP V4 is ok (cesm1_2)
bug seems to have been introduced in cesm1_3

**CTSM version you are using:** [output of `git describe`] 
n/a

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]
Antarctica has garbage forcing.

**Configurations affected:** [Fill this in if known.]
i-case:  CRUNCEP_V5

### Details of bug
Affects:
M       scripts/ccsm_utils/Case.template/config_definition.xml
M       models/atm/datm/bld/namelist_files/namelist_defaults_datm.xml
M       models/atm/datm/bld/namelist_files/namelist_definition_datm.xml

### Important details of your setup / configuration so we can reproduce the bug

CODE = cesm1_3 / cesm1_3_beta17_sehires22
COMPSET = ICRUCN

### Important output or errors that show the problem

Land files will have bad forcing over Antarctica.  Can see errors in regridded land data.

**Comment by ekluzek** [comment]
@nanr I'm pretty sure this is a known issue. And it's an issue that's really a cime issue rather than ctsm. I'm pretty sure it's this one...

https://github.com/ESMCI/cime/issues/604

So it's fixed in more recent versions of cime and ctsm. Please verify that the fix above resolves the issue.

**Comment by billsacks** [comment]
Closing this old issue.
