### ISSUE TITLE
crash in multi-instance run when ninst gets above ~100

### ISSUE THREAD

**Issue by ckoven** [ESCOMP/ctsm#515]
### Brief summary of bug

I'm trying a multi-instance run using CLM-FATES on edison at nersc.  The run I've set up runs when ninst = 95, but crashes at ninst = 191, 383, and 767 (in all cases, I'm setting it to fill up 24-cpu nodes on edison with a land rootpe of 1 togive 1 cpu for the datm)

### General bug information

**CTSM version you are using:** [output of `git describe`]
CTSM version is 959f7b55 (which is on my ctsm branch, it has a couple relevant bug-fixes cherry-piced onto the fates-next-api branch)
fates version is https://github.com/ckoven/fates/commit/377744d

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]
No

**Configurations affected:** [Fill this in if known.]
Not sure

### Details of bug
The issue here seems to be the max number of instances possible.  I've run larger ensembles on cheyenne in the past, so in principle this could work, but I suppose the maximum number of ensemble members is machine-dependent?

### Important details of your setup / configuration so we can reproduce the bug

the script I used to generate the multi-instance run is here: https://github.com/ckoven/runscripts/blob/master/cesm2_fates_edison_run_ensemble_v2_noinventory_180828.bash

### Important output or errors that show the problem

the relevant error messages I get look like this (only pasting the error from the process that first reports it, but all of the processes show similar errors):
```
145: Rank 145 [Tue Sep 18 21:14:22 2018] [c3-2c0s3n2] Fatal error in MPI_Irecv: Invalid tag, error stack:
145: MPI_Irecv(165): MPI_Irecv(buf=0xa3ad1a0, count=1, MPI_INTEGER, src=0, tag=2981455, comm=0xc4000006, request=0x7ffffffe5b20) failed
145: MPI_Irecv(109): Invalid tag, value is 2981455
145: forrtl: error (76): Abort trap signal
145: Image              PC                Routine            Line        Source             
145: cesm.exe           000000000268547E  Unknown               Unknown  Unknown
145: cesm.exe           00000000020BD170  Unknown               Unknown  Unknown
145: cesm.exe           000000000265990B  Unknown               Unknown  Unknown
145: cesm.exe           0000000002769EAA  Unknown               Unknown  Unknown
145: cesm.exe           0000000002483082  Unknown               Unknown  Unknown
145: cesm.exe           0000000002461B50  Unknown               Unknown  Unknown
145: cesm.exe           0000000002461C96  Unknown               Unknown  Unknown
145: cesm.exe           000000000244BC69  Unknown               Unknown  Unknown
145: cesm.exe           00000000020BDFDC  Unknown               Unknown  Unknown
145: cesm.exe           000000000114CFB5  m_rearranger_mp_r         930  m_Rearranger.F90
145: cesm.exe           00000000004D00B6  seq_map_mod_mp_se         301  seq_map_mod.F90
145: cesm.exe           0000000000427324  component_mod_mp_         565  component_mod.F90
145: cesm.exe           000000000041EDA0  cime_comp_mod_mp_        1737  cime_comp_mod.F90
145: cesm.exe           0000000000425F5E  MAIN__                    114  cime_driver.F90
145: cesm.exe           000000000040A80E  Unknown               Unknown  Unknown
145: cesm.exe           0000000002763BB9  Unknown               Unknown  Unknown
145: cesm.exe           000000000040A6F9  Unknown               Unknown  Unknown
srun: error: Task 145 reported exit for a second time.
srun: error: Task 145 reported exit for a second time.
srun: error: Task 145 reported exit for a second time.
lines 240-275/275 (END)

```

**Comment by klindsay28** [comment]
The following look like they might be relevant:

https://github.com/ESMCI/cime/pull/2804
Don't exceed maximum MPI tag value #2804

https://github.com/E3SM-Project/E3SM/issues/2487
MPI tag can overflow with multi-instance #2487

That said, I don't understand those threads well enough to figure out if this MPI tag issue is a factor here.

**Comment by ckoven** [comment]
thanks @klindsay28.  that does seem relevant, especially as edison is a cray machine whereas cheyenne isn't, and of the two, the problem seems to only happen on edison.

via ESMCI/cime#2804, it sounds like a possible solution is to make the run multi-driver?  I'm not sure that I understand how that would work in this case.  do i need to set ninst_atm = ninst_lnd?  or can i still have instances of DATM serving more than one instance of CLM -- which seems preferable to reduce the amount of i/o in the run...

**Comment by billsacks** [comment]
@ckoven while I haven't used multi-driver myself yet, there's some documentation here: http://esmci.github.io/cime/users_guide/multi-instance.html . I think the easiest thing to do is to specify this at create_newcase time using the `--ninst` and `--multi-driver` options to create_newcase. I think multi-driver is now the generally-recommended usage for reasons of performance etc.

**Comment by ckoven** [comment]
thanks @billsacks.  I'm trying a case right now using the `--ninst` and `--multi-driver` options to create_newcase. unfortunately it takes several hours just to build the datm namelists :( so I'll update if that works.

**Comment by ckoven** [comment]
An update on this: its possible that, in theory at least, the `--multi-driver` method works for large number of these single-point I-compset instances.  In practice though, the overhead of namelist building (in particular for the DATM) is way too high.  Just running the case.build step took around 4.5 hours, and then when the job ran it spent the whole time allocated to it running the namelist generation step again, and was still early in that process when it ran out of time.  I had only given it 30 minutes to fit within a debug queue, but given the number of nodes it was running on and the fact that it was only 10% through building the DATM namelists in that time, this method isn't going to be an efficient use of computing time even if I had asked for a longer queue.  Anyway, not sure what to do. I guess I'll cross-post to https://github.com/ESMCI/cime/pull/2804 to see if it is something that others are aware of.

**Comment by jedwards4b** [comment]
@ckoven you should be able to build the namelists interactively using preview_namelists from the command line and then submit with the --skip-preview-namelist flag to prevent it trying to rebuild them.

**Comment by ckoven** [comment]
just to update this thread; trying with --multi-driver and --skip-preview-namelist leads to crashes in the DATM code, which I don't understand the source of.  So, for now anyway, I'm thinking this isn't going to be a useful method.

```
543:  NetCDF: Variable not found
543:  pio_support::pio_die:: myrank=          -1 : ERROR: nf_mod.F90:         730 : 
543:  NetCDF: Variable not found
543: Image              PC                Routine            Line        Source             
543: cesm.exe           0000000002678681  Unknown               Unknown  Unknown
543: cesm.exe           0000000000F995D1  pio_support_mp_pi         118  pio_support.F90
543: cesm.exe           0000000000F976F2  pio_utils_mp_chec          74  pio_utils.F90
543: cesm.exe           0000000000F7D6C3  nf_mod_mp_inq_var         730  nf_mod.F90
543: cesm.exe           0000000000E9318D  shr_dmodel_mod_mp         914  shr_dmodel_mod.F90
543: cesm.exe           0000000000E9183F  shr_dmodel_mod_mp         657  shr_dmodel_mod.F90
543: cesm.exe           0000000000F2EC98  shr_strdata_mod_m         743  shr_strdata_mod.F90
543: cesm.exe           00000000004DABAC  datm_comp_mod_mp_         664  datm_comp_mod.F90
543: cesm.exe           00000000004E106F  datm_comp_mod_mp_         551  datm_comp_mod.F90
543: cesm.exe           00000000004D954F  atm_comp_mct_mp_a         167  atm_comp_mct.F90
543: cesm.exe           0000000000428CB6  component_mod_mp_         244  component_mod.F90
543: cesm.exe           0000000000418FCB  cime_comp_mod_mp_        1202  cime_comp_mod.F90
543: cesm.exe           0000000000425E7E  MAIN__                    114  cime_driver.F90
543: cesm.exe           000000000040A80E  Unknown               Unknown  Unknown
543: cesm.exe           00000000027627B9  Unknown               Unknown  Unknown
543: cesm.exe           000000000040A6F9  Unknown               Unknown  Unknown
543: Rank 543 [Fri Sep 28 03:37:25 2018] [c5-2c1s0n1] application called MPI_Abort(MPI_COMM_WORLD, 1) - process 543
543: forrtl: error (76): Abort trap signal
543: Image              PC                Routine            Line        Source             
543: cesm.exe           000000000268407E  Unknown               Unknown  Unknown
543: cesm.exe           00000000020BBD70  Unknown               Unknown  Unknown
543: cesm.exe           000000000265850B  Unknown               Unknown  Unknown
543: cesm.exe           0000000002768AAA  Unknown               Unknown  Unknown
543: cesm.exe           0000000002481C82  Unknown               Unknown  Unknown
543: cesm.exe           0000000002448D6B  Unknown               Unknown  Unknown
543: cesm.exe           00000000020BD4D5  Unknown               Unknown  Unknown
543: cesm.exe           0000000000F995E4  pio_support_mp_pi         124  pio_support.F90
543: cesm.exe           0000000000F976F2  pio_utils_mp_chec          74  pio_utils.F90
543: cesm.exe           0000000000F7D6C3  nf_mod_mp_inq_var         730  nf_mod.F90
543: cesm.exe           0000000000E9318D  shr_dmodel_mod_mp         914  shr_dmodel_mod.F90
543: cesm.exe           0000000000E9183F  shr_dmodel_mod_mp         657  shr_dmodel_mod.F90
543: cesm.exe           0000000000F2EC98  shr_strdata_mod_m         743  shr_strdata_mod.F90
543: cesm.exe           00000000004DABAC  datm_comp_mod_mp_         664  datm_comp_mod.F90
543: cesm.exe           00000000004E106F  datm_comp_mod_mp_         551  datm_comp_mod.F90
543: cesm.exe           00000000004D954F  atm_comp_mct_mp_a         167  atm_comp_mct.F90
543: cesm.exe           0000000000428CB6  component_mod_mp_         244  component_mod.F90
543: cesm.exe           0000000000418FCB  cime_comp_mod_mp_        1202  cime_comp_mod.F90
543: cesm.exe           0000000000425E7E  MAIN__                    114  cime_driver.F90
543: cesm.exe           000000000040A80E  Unknown               Unknown  Unknown
543: cesm.exe           00000000027627B9  Unknown               Unknown  Unknown
543: cesm.exe           000000000040A6F9  Unknown               Unknown  Unknown
srun: error: nid04097: task 543: Aborted
```

**Comment by billsacks** [comment]
Thanks for giving this a shot, @ckoven . Sorry you have run into these problems. I'm thinking this should really be opened as an issue in cime and closed here; would you agree with that course of action?

**Comment by ckoven** [comment]
@billsacks sure.  I guess it overlaps with https://github.com/ESMCI/cime/pull/2804 and it seems that people there are already aware of the issue.

**Comment by billsacks** [comment]
Would it make sense for you to add your latest comment to that issue, and we can close this CTSM issue?

**Comment by ckoven** [comment]
done.

**Comment by jedwards4b** [comment]
@ckoven this error indicates that the datm is looking for a variable that doesn't exist in the file and may indicate a corrupted stream file - can you verify that all of the stream files were created and have the same contents.

**Comment by billsacks** [comment]
I'm closing this issue here. Feel free to reopen if you feel it really is a ctsm issue.

**Comment by ckoven** [comment]
thanks @jedwards4b.  you are correct: it turns out that somehow the iterator in the bash script didn't apply the sed command deleting the FLDS field to 3 of the datm.streams.txt.CLM1PT.CLM_USRDAT_xxxx files.  I just manually removed that line from the three offending files.  I'm re-running now and can update if I can get it to work.
