### ISSUE TITLE
discrepancy in master and fates_next_api for 24hr averages precip/rh

### ISSUE THREAD

**Issue by rgknox** [ESCOMP/ctsm#520]
I noticed that in master, 24 hour averages of relative humidity and precipitation was dropped from atm2lndtype.F90.  In fates we need these as boundary conditions for the fire model.  Note these are still available in fates_next_api.  Did these variables get moved somewhere?  24hour winds were preserved. 
 Sorry if I missed anything.

https://github.com/ESCOMP/ctsm/blob/master/src/main/atm2lndType.F90#L893

https://github.com/ESCOMP/ctsm/blob/fates_next_api/src/main/atm2lndType.F90#L973

**Comment by billsacks** [comment]
In order to support water tracers, we have reorganized all water-related fields. These are now in https://github.com/ESCOMP/ctsm/blob/master/src/biogeophys/Wateratm2lndBulkType.F90.

**Comment by rgknox** [comment]
Thanks @billsacks
