### ISSUE TITLE
Organize usermods_dirs to facilitate running cases with the right output

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#529]
Based on discussion with @dlawrenncar and @ekluzek , we'd like to reorganize how the default output is specified in usermods_dirs (currently all in the cmip6_output usermods directory):

We should split the cmip6_output directory into two: one that just has
the low-frequency output, and one that adds high-frequency. Then we can
have a top-level cmip6 as well as `cmip6_high_frequency`. And do the
same thing at the CESM level. The main one will exclude the daily and
3-hourly output.

Actually: We should have different output directories:
- `output_sp`
- `output_bgc` (includes `output_sp`)
- `output_crop` (includes `output_bgc`)
- `output_sp_highfreq` (builds on `output_sp`)
- `output_bgc_highfreq`
- `output_crop_highfreq`

We'll also have `cmip6` (which includes `output_crop`) and
`cmip6_highfreq` (which includes `output_crop_highfreq`, which should be
identical to what is now `cmip6_output`).

**Comment by billsacks** [comment]
For the record: Last week, we brought up the question of whether these usermods directories can/should be included via the compset. At the time, I said that my vague recollection was that we felt that was a bad idea, but I couldn't remember the details. 

I looked back at some notes from last year on this issue (we discussed it a few times in clm-cmt meetings in 2017). My main takeaway from this was that, while we went back and forth on this issue, the most recent notes I could find from that series of discussions (from August 23, 2017) did suggest having the compset pick up a specific usermods directory.

However, I just talked with @mvertens about this, and she feels we want to move away from having so many things implicitly tied to the compset, moving towards having more things set separately via command-line arguments (I think partly to make things more explicit, and partly to avoid problems of combinatoric explosions). So she is now in favor of requiring the user to specify `--user-mods-dir`.

One other comment I found was Dave's request for a rename of `--user-mods-dir` to something like `--case-mods` or `--experiment-mods`. @dlawrenncar if you still feel that would be significantly clearer, we can consider adding that as an alternative name (probably maintaining the `--user-mods-dir` option for backwards compatibility... this is easy to do in the code).

**Comment by dlawrenncar** [comment]
I guess that --case-mods-dir or --experiment-mods-dir would be a bit
clearer to me.  Not super important.  Perhaps --case-mods-dir to be
consistent with our conventions (e.g., casename).  Or, should it be
--user-case-mods-dir?  Again, I think I prefer --case-mods-dir, because
really this isn't being used primarily as a mechanism that users can
provide user-oriented updates to their case.  It is being used to pull in
default(ish) options that are not included in compsets.

**Comment by billsacks** [comment]
I like `--case-mods-dir`. However, as I started looking into making this change, I realized that it's a bigger can of worms than I originally was thinking: in addition to the command-line flag (which is easy to change), there are xml variables (in cime) and directories (in various components) that use the name 'user_mods' or 'usermods'. So changing this name would either mean that some names would become inconsistent or would require many changes spanning multiple components. So I think I'd like a stronger opinion from more people before going there.

**Comment by olyson** [comment]
Bill, I have the following user_nl_clm files for SP, BGC, and CROP on hobart here:

/home/oleson/release-clm5.0.08/cime/scripts/clm50_Rclm5008_1deg_GSWP3V1_cmip6output_hist/user_nl_clm_sp

/home/oleson/release-clm5.0.08/cime/scripts/clm50_Rclm5008_1deg_GSWP3V1_cmip6output_hist/user_nl_clm_bgc

/home/oleson/release-clm5.0.08/cime/scripts/clm50_Rclm5008_1deg_GSWP3V1_cmip6output_hist/user_nl_clm_crop

As I said, untested.  I've put notes in each file regarding FPSN/GPP for SP/BGC and the empty h4 stream for SP.

**Comment by billsacks** [comment]
@olyson points out that we'll need a separate 'base' usermod and 'sp' usermod, with 'bgc' extending 'base' rather than 'sp', because 'sp' includes FPSN, which is not wanted in 'bgc'. (So both 'bgc' and 'sp' will extend 'base'.)

@olyson also points out another possible issue here: sp doesn't have anything in h4. If possible, I'll change the code to allow this (so we can have a "hole" in the history tapes: nothing in h4 but still have an h5). If that isn't possible, then we'll add some random field to h4 for SP.

**Comment by billsacks** [comment]
@ekluzek @olyson and/or @dlawrenncar - Currently, the cmip6_output usermods directory includes this setting:

```
./xmlchange CCSM_BGC=CO2A
```

This seems out of place here. Is this something that's wanted for all cmip6 runs? If so, should it be in a cmip6-specific directory, or one of the new, generic output directories?

**Comment by billsacks** [comment]
For what it's worth, the two cmip6 cases I've checked have CCSM_BGC=CO2C. So my guess is that we should remove that xmlchange command from our cmip6 directory. But I'd like confirmation on that.

**Comment by olyson** [comment]
Sorry, I don't know why that would be in there.  I've only coordinated the user_nl_clm CMIP6 output.
I doubt it's something we want for all CMIP6 runs.

**Comment by olyson** [comment]
There is one runoff model high frequency output field requested by CMIP6.  Can the following daily average field be added to the high frequency output option (for user_nl_mosart):

rtmhist_fincl2 = "RIVER_DISCHARGE_OVER_LAND_LIQ"
rtmhist_mfilt = 1,365
rtmhist_nhtfrq = 0,-24

**Comment by billsacks** [comment]
@olyson - we've (tentatively) decided not to have out-of-the-box support for high-frequency cmip6 output. That said, there is currently sort of a mechanism to get high-frequency output by changing the cmip6_deck usermods directory to point to output_crop_highfreq rather than just output_crop. My impression from talking to @dlawrenncar was that output_crop_highfreq is thought to be more general than just cmip6. So my question is: **should I add these settings to the general high-frequency output settings that a user can obtain with `--user-mods-dir output_crop_highfreq` (or `--user-mods-dir output_crop_sp` or `--user-mods-dir output_crop_bgc`)?** If so, I can easily do this; if not, we don't really have a mechanism for this right now.

If this doesn't make sense, we can talk in person: I'd like you to understand the mechanism behind getting cmip6 high-frequency output, since you'll likely be supporting this.

**Comment by olyson** [comment]
No, I don't think we should add it to the general high-frequency output settings.  Looking at Sheri's CMIP spreadsheet it looks like it's only required for LS3MIP.  So I will pass this on to Peter L. who is doing the LS3MIP runs.
