### ISSUE TITLE
ESMF coupling interface

### ISSUE THREAD

**Issue by jhamman** [ESCOMP/CTSM#530]
What is the current status of a ESMF coupling interface for CTSM?

@mvertens and @billsacks have mentioned that a NUOPC cap was under development but, to the best of my knowledge, no one has worked on a pure ESMF cap for CTSM. Is that correct?

This is something we're going to want later this year for the LILAC project.

**Comment by billsacks** [comment]
That's right (to my knowledge). @mvertens - where is the branch that has the nuopc cap? Is that ready to be brought to master?

**Comment by mvertens** [comment]
There is a nuopc cap to CTSM.
repo_url = https://github.com/mvertens/ctsm.git
branch = mvertens/nuopc_cap

This is working with the latest version of the CMEPS mediator.
You are right about a pure ESMF cap. We should cover that at our meeting.
Rocky - if possible it would be great to have you there.

Mariana

**Comment by jhamman** [comment]
Thanks both of you. Let's discuss in person and keep this on the front burner as we think about what needs to happen for LILAC on the CTSM side.

**Comment by mvertens** [comment]
Closing this issue since its no longer relevant to the current lilac development.
