### ISSUE TITLE
Transient cases coupled to CAM are matching the wrong IC file (2000 instead of 1850)

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#544]
### Brief summary of bug

SMS.f19_g17.BHISTWs.cheyenne_intel.allactive-defaultio is matching a 2000 file instead of an 1850 one.

### General bug information

**CTSM version you are using:** release-clm5.0.09

**Does this bug cause significantly incorrect results in the model's science?** Wrong initial conditions (so sort of)

**Configurations affected:** LND_TUNING_MODE=clm5_0_cam6_0 (and I think clm4_5_cam6_0)

### Details of bug

It's wrongly matching this file rather than the 1850 one...

``` xml
<!-- Present day crop spinup at 2-degree with irrigation on -->
<finidat hgrid="1.9x2.5"    maxpft="79"  mask="gx1v7" use_cn=".true." 
use_cndv=".false." use_fates=".false."
          ic_ymd="20110101" use_nitrif_denitrif=".true." 
use_vertsoilc=".true." sim_year="2000"
          ic_tod="0" glc_nec="10" use_crop=".true." irrigate=".true."
 >lnd/clm2/initdata_map/clmi.I2000Clm50BgcCrop.2011-01-01.1.9x2.5_gx1v7_gl4_simyr2000_c180715.nc
</finidat>
```

### Important details of your setup / configuration so we can reproduce the bug

It dies for cases that are on f19_g17_gl4 because it thinks it can run without interpolation and it can't. Other cases would run with interpolation, but from the wrong initial conditions.

### Important output or errors that show the problem

Dies since it isn't setup to run with interpolation

**Comment by ekluzek** [comment]
@dlawrenncar just want to ping you on this issue.

**Comment by ekluzek** [comment]
Fixed in release-clm5.0.12

**Comment by billsacks** [comment]
@ekluzek not a big deal, but in general I thought we're keeping issues open until they're merged to master.

**Comment by ekluzek** [comment]
On master this is causing the following test to fail: IRT_N3_PM3_Ld7.f19_g17.BHIST.cheyenne_intel.allactive-defaultio
