### ISSUE TITLE
Add no-anthro compset and options for CLM

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#557]
We need to add an option for paleo work for no-anthro turning off urban and any urban related effects. One part of this is to use surface datasets from mksurfdata that have urban turned off (so see #533)

use_crop=.false.
fsurdat='file without urban, GDP=0, potential-veg,all crops zeroed'
urban_hac='OFF'
calc_human_stress_indices='NONE'
stream_year_first_urbantv= 'Set to non-urban dataset'
stream_fldfilename_popdens='zero population dataset'
pot_hmn_ign_counts_alpha=0.0
do_harvest=.false.
stream_fldfilename_ndep='remove human component of ndep

If carbon isotopes on
atm_c14_filename=''without anthro'
atm_c13_filename='without anthro'

For datm:

prescribed aerosols without human affect
CO2 at 1850 level if CO2_TIME_SERIES is on

**Comment by dlawrenncar** [comment]
GDP also needs to be set to zero on surface dataset, potentially through
same mechanism as turning urban off (i.e., using a file with GDP set to
zero everywhere).

Also need to check fire code to make sure that nothing breaks with GDP = 0.

**Comment by klindsay28** [comment]
If the definitions of no-anthro compsets are growing to include ndep and
atmospheric C isotopic composition, then analogous changes should be made
in POP for these compsets. Is a consensus growing on how these compsets are
to be defined?

**Comment by ekluzek** [comment]
@klindsay28 yes we need some scientific oversight on this. Who is responsible for configuring this in the scientific sense? A few of us met in CTSM (@olyson @dlawrenncar and I) and we talked about everything in the list I gave. I'm thinking the first pass of this wouldn't be with changes to ndep, presaero, or Carbon isotopes -- because all of those will take more work than the others. But, we do need to know who's responsible to make that call. I know this is high priority, but I also don't have a good feel for how high of a priority either...

**Comment by ekluzek** [comment]
Here are the namelist setttings that I used for the first test case:

```
urban_hac='OFF'
calc_human_stress_indices='NONE'
stream_fldfilename_popdens='/glade/work/erik/Data/clmforc.no_anthro_zero_hdm_1x1_simyr1925_181113.nc'
pot_hmn_ign_counts_alpha=0.0
do_harvest=.false.
stream_year_first_urbantv=1850
stream_year_last_urbantv=1850
stream_year_first_ndep=1850
stream_year_last_ndep=1850
irrigate=.false.
cropfire_a1=0.0
popdensmapalgo = 'nn'
stream_year_first_popdens = 1925
stream_year_last_popdens = 1925
```

**Comment by ekluzek** [comment]
Note also #604 the atmospheric methane concentration is given by the input paramfile.
