### ISSUE TITLE
Replace a failing test in aux_cime_baselines

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#558]
This test is in aux_cime_baselines, but it has been expected to fail for a while, with no solution on the near-term horizon: `ERP_D_Ld10_P36x2.f10_f10_musgs.IHistClm50BgcCrop.cheyenne_intel.clm-ciso_decStart`. It would be really good if we could keep `aux_cime_baselines` entirely passing, because this is an important test suite that @fischer-ncar runs nightly. @ekluzek can you please replace this test with something that's expected to pass and provides similar coverage of whatever you especially wanted to test by having that in the `aux_cime_baselines` suite?

**Comment by ekluzek** [comment]
There were two things here, one was to have a test with carbon isotopes. Another was to do a transient test. That is the only global test of IHist with carbon isotopes. So I'm switching it out for
a cmip6 test as that will have isotopes turned on, and it's obviously an important configuration. It isn't transient though. We probably should add a transient test to the list at some point.

But, for now I'm doing this.

Change the aux_cime_baseline test from to the IHistClm50BgcCro ciso_DecStart
    to SMS_Ld5_D.f09_g1.I1850Clm50BgcCropCmip6.clm-basic

**Comment by billsacks** [comment]
When you bring this to master, can you please either add a transient test or open an issue so we don't forget to do this?
