### ISSUE TITLE
Surface dataset enhancements needed for irrigation method

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#565]
In #523 , @swensosc has introduced the ability to read grid cell and crop-specific irrigation methods (currently, sprinkler or drip) from the surface dataset. The following enhancements are needed to make this fully operational out-of-the-box:

- [ ] Add ability for mksurfdata_map to put this field on surface datasets

- [ ] Add a method like collapse_crop_types that can do this collapsing for discrete values like this irrigation method (probably taking the dominant type)

- [ ] [Optional] Make any changes needed to support irrig_method when create_crop_landunit is false. Note that we currently have a workaround (see commits 21616fc and 1074092) that avoids array bounds violations when create_crop_landunit is false, but additional changes would be needed (and the workaround could possibly be backed out) to actually allow this field to be specified on the surface dataset when create_crop_landunit is false.

- [ ] [Optional] Add this field to transient datasets, if there's a need to have this vary in time

**Comment by billsacks** [comment]
Until we can rely on irrig_method always being on the surface dataset, I am adding an irrig_method_default namelist parameter. This will especially be useful for testing.

**Comment by ekluzek** [comment]
@swensosc @samsrabin I think this is moot now that the approach we plan to take is to have irrigation type on streams files right (#2102)?

**Comment by samsrabin** [comment]
Yep, I agree.

**Comment by ekluzek** [comment]
Closing since this is taken care of with the move of irrigation data to streams files.

**Comment by samsrabin** [comment]
Reopening, as we haven't actually done that yet!

**Comment by samsrabin** [comment]
Oh sorry, I see what you mean now. Sorry!
