### ISSUE TITLE
Allow zeroing out special landunits if their area is below some threshold

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#581]
Connected with #457 - particularly for the NWP configuration, we want to allow using higher thresholds for whether special landunits are present. For example, maybe lake is only present if it takes up 10% or more of the grid cell? We may want these thresholds to be selectable via the mksurfdata_map namelist (currently I think they're hardcoded in mksurfdata_map), or – maybe better – we may want this selectable at runtime, as we're planning for #457 .

**Comment by slevisconsulting** [comment]
Notes from my Feb 2019 Boulder visit:

**User-set landunit cutoffs**
1) Run with N dominant landunits
2) Additionally turn off landunits individually with namelist thresholds; beware of situations that may break the model, eg gridcells ending up with no landunits
3) Remove this control from mksurfdat

**Comment by slevisconsulting** [comment]
@billsacks feel free to assign this issue to me. Thanks!

**Comment by slevisconsulting** [comment]
New sub-issue to address here:

In surfrdMod.F90 I wrote the comment:
"call collapse_to_dominant" does not appear in subroutine dynpft_interp: SHOULD IT?

As implemented, a TRANSIENT run that uses n_dom_pfts and/or n_dom_landunits will go back to the pfts and/or landunits read from the input files. I allowed this behavior because I reasoned that NWP applications would not perform transient runs.

It is risky to leave this behavior in the model so address in an upcoming PR.

@billsacks and @ekluzek please confirm whether you have the same understanding of this.

**Comment by billsacks** [comment]
@slevisconsulting if your new option is incompatible with transient, can you please put in an error check ensuring that these two options aren't set at the same time (if you haven't already)?

**Comment by ekluzek** [comment]
Yes, if it's incompatible with transient, an error should be triggered (both in code and in build-namelist) to say that this isn't something that's valid to do. You are probably right that for NWP you wouldn't likely be doing transient cases. Transient mode changes at most once a year, so that just doesn't make sense for weather prediction.

**Comment by slevisconsulting** [comment]
Alternatively, I could add the necessary calls in
subroutine update_landunit_weights and subroutine dynpft_interp
and just get it done. Would either of you be opposed to my trying?

I would do this as a new PR right after completing the PR that's currently open. If you're opposed, I'm happy to add the error checks as suggested.

**Comment by billsacks** [comment]
@slevisconsulting I'm fine with your giving this a shot if you don't think it will be too hard. One possible caveat relates to dynamic glaciers, whose areas come from the coupler. It's possible that those areas need to stay in agreement with CISM's for conservation purposes when running with fully active glaciers... I can't remember if that's still necessary. But I'm okay with your adding this as you suggest; please just add a note in the documentation of this variable in namelist definition that it *might* break conservation if running with an evolving ice sheet model.

**Comment by slevisconsulting** [comment]
Ok, so I get the following error when I test the above discussed mods with
ERS_D_Ld10.f10_f10_musgs.IHistClm50BgcCropGs.cheyenne_intel.clm-rm_individual_lunits_decStart

I get the feeling that maybe I should expect this error in a decStart run and should use the error suppression suggested (similar to the suppression used for pfts with check_dynpft_consistency=.F.):

`71: set_curr_delta ERROR: found unexpected non-zero delta mid-year
71: Dribbler name: dwt
[...]
71: This indicates that some non-zero flux was generated at a time step
71: other than the first time step of the year, which this dribbler was told not to
71:  expect.
71: If this non-zero mid-year delta is expected, then you can suppress this error
71: by setting allows_non_annual_delta to .true. when constructing this dribbler.`

Any intuition on this? Meanwhile I will try to diagnose.

**Comment by billsacks** [comment]
I wouldn't necessarily expect this error in a decStart run, but maybe there's something I'm not thinking about. This suggests to me that landunit weights are changing at a time step other than the year boundary. Can you tell when in the run you are getting this error?

**Comment by billsacks** [comment]
Thinking about this more: My guess is that you're running into this in the first time step of the run. I suspect the problem is that weights shift substantially in the first time step in this decStart run, because you're starting in a different year from the one given by the restart file. This change in weights in the first time step is then generating a dynbal flux.

But what I don't understand is why you would see this error arise when adding your code, if it doesn't arise on master. It may be that this is expected, but I think it's worth digging into further to try to understand it.

This also raises another question for me: Does the test you're running actually cover the situations you're trying to test - e.g., landunits coming in or out of existence mid-run?

**Comment by billsacks** [comment]
Wait, I may see a problem with trying to do the collapse to N dominant landunits in a transient run: Let's say the surface dataset specifies 20% lake, 30% crop and 50% nat veg for a given grid cell, and we are collapsing to the 2 dominant landunits. Then, in initialization, lakes would be set to 0, and crops and nat veg would be rescaled, right (to 37.5% crop and 62.5% nat veg?).

Now consider two scenarios on the landuse timeseries file for a given year:

(1) Crop area is reduced to 15% (implicitly replaced by natural veg). Now if you wanted the two dominant landunits, you would pick lake (20% before collapsing / rescaling) and nat veg (65% before collapsing / rescaling). However, the model does not currently have a memory of the pre-collapsing lake area, so it would mistakenly keep crop and natural veg.

(2) Crop area is reduced to 25% (implicitly replaced by natural veg). The desired end state would be crop = 25/80 = 31.25% after rescaling, and nat veg = 55/80 = 68.75% after rescaling. However, note that I generated those values based on my knowledge of the pre-rescaling values. The model doesn't remember that nat veg had 50% before rescaling, so it would set these to crop = 25%, nat veg = 75%. i.e., rather than seeing the crop area change as a reduction of 5% of the grid cell area (from 30% to 25%), it sees it as a reduction of 12.5% (from 37.5% to 25%).

With careful thought, it might be possible to fix this problem, but I'd say let's make the collapsing to N dominant landunits incompatible with anything transient for now. Ideally, we'd also stop this from operating when running with transient glacier areas, though I don't know how easy that will be to trap.

Problem (2) also applies to having a fixed cutoff for minimum landunit areas.

**Comment by billsacks** [comment]
So my conclusion is that we probably should not allow your new landunit-collapsing settings in a transient run.

Similarly, we probably should not allow these settings to be set in a run with `glc_do_dynglacier = .true.`. I'm not positive whether these settings are completely incompatible, particularly in the common case where we have `glc_do_dynglacier = .true.` but with a non-evolving ice sheet (so we just sync areas with CISM in initialization), but to be safe, let's not allow those settings together for now. Note that this means that compsets with CISM (even CISM2%NOEVOLVE) will not run with your new settings (unless you set the xml variable `GLC_TWO_WAY_COUPLING=FALSE`).

**Comment by slevisconsulting** [comment]
Seems reasonable and thank you for thinking this through @billsacks .

I was coming to a similar conclusion by trying this test:
- Set one of the urban landunits to disappear for a certain user-defined limit but then override the outcome to make the landunit not disappear but become half as large. No other changes.
- The result is still the same delta error in pft 0, which tells me that I'm introducing an inconsistency between transient pft weights and transient landunit weights. And it's starting to seem like a more complicated task to solve than I thought...

So I'll just add the error checks that you guys suggested in the beginning.

**Comment by slevisconsulting** [comment]
For future reference... 
I will keep my attempt at getting this to work in my "rm_individual_lunits" branch (as untracked files).
