### ISSUE TITLE
Are `create_crop_landunit` and `use_crop` redundant? 

### ISSUE THREAD

**Issue by bishtgautam** [ESCOMP/ctsm#606]
Based on [controlMod.F90#L358](https://github.com/ESCOMP/ctsm/blob/master/src/main/controlMod.F90#L358
), `use_crop=.true.` requires `create_crop_landunit=.true.`. Is there a valid senario for which  `create_crop_landunit=.true.` with `use_crop=.false.`?

**Comment by billsacks** [comment]
When running without prognostic crops – i.e., just the generic unirrigated and irrigated crops (i.e., `use_crop=.false.`) – we now typically run with `create_crop_landunit=.true.` despite `use_crop=.false.`. In fact, I believe that the only time we currently have `create_crop_landunit=.false.` now is when running with FATES.

**Comment by bishtgautam** [comment]
Few followup questions:
- My understanding is that `create_crop_landunit` is to turn on/off the dynamic landunits (DLU). Is that correct?
- Can DLU be turned on for generic unirrigated and irrigated crops?
- For a FATES run,
   - Can `use_crop` be `.true.`?
   - Can `create_crop_landunit` be `.true.`?

**Comment by ekluzek** [comment]
@bishtgautam create_crop_landunit=T, means that each crop type, will be in it's own landunit. While create_crop_landunit=F, means each crop type shares the landunit with the other crops. It doesn't really have anything to do with dynamic landunits, as that is something orthogonal to this.

And yes transient landunits can be turned on for generic crops.

For FATES, neither create_crop_landunit nor use_crop can be true.

**Comment by olyson** [comment]
I think of these namelist variables as turning on dynamic landunits:
do_transient_pfts
do_transient_crops

There was a bug that didn't allow DLU to be turned on for generic unirrigated and irrigated crops (do_transient_crops=.true., use_crop=.false.)
It looks like this was fixed on master in ctsm1.0.dev013 and on the release branch in release-clm5.0.11

**Comment by bishtgautam** [comment]
Thanks, @ekluzek, @olyson.

**Comment by billsacks** [comment]
> create_crop_landunit=T, means that each crop type, will be in it's own landunit. While create_crop_landunit=F, means each crop type shares the landunit with the other crops

I don't think this is quite right. I want to clarify, because this is a common source of confusion: create_crop_landunit=T means that there is a _single_ crop landunit, with each crop on its own column in that landunit. create_crop_landunit=F means that there is _no_ crop landunit, and the generic crops share the single natural vegetation soil column.

**Comment by ekluzek** [comment]
Yes, correct. Sorry for not being careful. Thanks for the clarification. There's only one additional land-unit for crop, but when there is the crop types within that landunit are on different columns. The important point about being on different columns is that they don't compete for the same water. Without this option on, crops are treated like other natural veg. types and they compete for water on the same column.

**Comment by hydrotian** [comment]
@billsacks I'm trying to run E3SM with use_crop=F, irrigation=T, and create_crop_landunit=T with 17 pft surface data (all counted nat pft, including generic unirrigated and irrigated crops) but got error complaining <sum of wt_cft not 1.0>. Then I modified the surface data to let nat_pft = 15 and cft = 2, and made sure sum of wt_cft = 1, but got another error message saying <This landunit type has already been set for this gridcell>. I think it's related to create_crop_landunit=T. Then I start to search online and found this post discussing relative stuff. Have you successfully used such configuration in E3SM or CESM?

**Comment by billsacks** [comment]
@hydrotian We cannot provide any support for using the E3SM model here.

**Comment by hydrotian** [comment]
I guess my question was have you successfully running the model with use_crop=F, irrigation=T, and create_crop_landunit=T in your model. If yes, maybe I can borrow some ideas from your successful cases. Thanks.

**Comment by billsacks** [comment]
Sorry, I can't remember whether we have run that way. Of course, feel free to try that with CTSM if you'd like.
