### ISSUE TITLE
Should SSP test set HIST_OPTION, HIST_N and some other variables?

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#61]
**Bill Sacks < sacks@ucar.edu > - 2017-06-13 20:46:37 -0600**
**Bugzilla Id:** [2475](http://bugz.cgd.ucar.edu/show_bug.cgi?id=2475)
**Bugzilla CC:**  andre@ucar.edu,  rfisher@ucar.edu, 

In moving the SSP test into CLM, I noticed that it doesn't set HIST_OPTION or HIST_N. All other system tests set these in order to produce and compare cpl hist files. Is this omission intentional, or should this be made consistent with the other tests in this respect?

Other common options missing from SSP are:

    <CONTINUE_RUN>FALSE</CONTINUE_RUN>

(not really needed since that's the default, but could be added to be consistent with other tests)

    <REST_OPTION>none</REST_OPTION>

I'm not clear on whether this last one is wanted for SSP.

**Comment by billsacks** [comment]
**Bill Sacks < sacks@ucar.edu > - 2017-06-13 20:47:00 -0600**

By the way: Once I bring my cime-update branch to the trunk, these can be set in components/clm/cime_config/config_tests.xml

**Comment by billsacks** [comment]
@ekluzek can you confirm my sense here? This one should be easy to fix so we should just slide it in to an upcoming tag.

**Comment by ekluzek** [comment]
You could compare the cpl hist for test to baseline. You don't want to compare restart to non restart. But, it probably does make sense to compare them to the baseline. So we should set them here. It's probably a good practice to set the same things to something, just for consistency sake.

**Comment by billsacks** [comment]
Okay, I'm adding the following:

```xml
    <CONTINUE_RUN>FALSE</CONTINUE_RUN>
    <HIST_OPTION>$STOP_OPTION</HIST_OPTION>
    <HIST_N>$STOP_N</HIST_N>
```

I am _not_ setting `<REST_OPTION>` to `never` (as is done for other tests), because it looks like this test relies on `<REST_OPTION>` remaining set to the default value.

@ekluzek does this look right to you?

**Comment by ekluzek** [comment]
@billsacks that looks right to me. That means it will produce a history file at the end of each run segment, and those files will then each be compared.  And since it's using the STOP variables, it should be updated for each segment. And yes, this one requires restarts to happen so it can run each run segment, so REST_* needs to be left alone.
