### ISSUE TITLE
QSNOEVAP history output incorrect

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#624]
### Brief summary of bug

QSNOEVAP history output is incorrect.

### General bug information

**CTSM version you are using:** release-clm5.0.15

**Does this bug cause significantly incorrect results in the model's science?** Yes, if QSNOEVAP is used for analysis

**Configurations affected:** All

### Details of bug

In WaterfluxType.F90, QSNOEVAP is defined as:

    this%qflx_ev_snow_patch(begp:endp) = spval
    call hist_addfld1d (fname='QSNOEVAP', units='mm/s',  &
         avgflag='A', long_name='evaporation from snow', &
         ptr_patch=this%qflx_tran_veg_patch, set_lake=0._r8, c2l_scale_type='urbanf')

but last line should be:

         ptr_patch=this%qflx_ev_snow_patch, set_lake=0._r8, c2l_scale_type='urbanf')

**Comment by ekluzek** [comment]
@olyson @dlawrenncar should this fix go into release-clm5.0 ASAP then?

**Comment by ekluzek** [comment]
I have a branch with the fix for this. I've also done some looking for this same type of problem elsewhere where ptr_patch points to the same array. There are some legit examples of this, where there is an ice mask for it. And there are some where a different name is allowed for the same variable.

**Comment by ekluzek** [comment]
So fixed on release branch will be fixed on master when those changes come in.
