### ISSUE TITLE
Change the ESMF library being used to ESMF7.1.0r

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#642]
### Brief summary of bug

From Chris Fischer, we need to use ESMF7.1.0r in place of ESMF7.0.0 which has a bug. mkmapdata.sh is currently using ESMF7.0.0.

### General bug information

**CTSM version you are using:** release-clm5.0.18

**Does this bug cause significantly incorrect results in the model's science?** Possibly

Potential problem 

Under certain conditions the mapping files created could be incorrect and cause problems.

**Configurations affected:** 

We aren't sure if this has caused problems with existing mapping files.

### Details of bug

The ESMF documentation of the bug says the following:

http://www.earthsystemmodeling.org/download/data/releases.shtml#v7_0_0

When the ESMF regrid weight generation methods and applications are used with nearest destination to source interpolation method, the unmapped destination point detection does not work. Even if the option is set to return an error for unmapped destination points (the default) no error will be returned.
The ESMF regrid weight generation methods and applications do not currently work for source Fields created on Grids which contain a DE of width less than 2 elements. For conservative regridding the destination Field also has this restriction.
The ESMF regrid weight generation methods and applications do not currently work on Fields created on Grids with arbitrary distribution.
When the ESMF regrid weight generation methods and applications are used to do conservative interpolation from a concave quadrilateral source cell to a destination cell which only partially overlaps the source cell, a weight of infinity can sometimes be generated.
When the ESMF regrid weight generation methods and applications are used for bilinear regridding with an extremely coarse spherical source grid (e.g. 5 cells to cover the entire Earth), then destination points can be mapped to the wrong side of the sphere leading to incorrect weights.

**Comment by billsacks** [comment]
@ekluzek - in #651 you said you fixed this issue on the release branch, but I don't see this fix in the latest `release-clm5.0` branch.

I'm going to fix this on master in an upcoming tag: see billsacks/ctsm@3383c41e

**Comment by ekluzek** [comment]
I was going to do that, but they needed to rebuild the ESMF libraries for them to work again. I intended to take that out of the notes. They've probably done that by now. But, you'll want to make sure that they are working again.

**Comment by billsacks** [comment]
I ran mkmapdata with 7.1.0r and it seemed to work. When you say they weren't working, were they totally broken (not able to run at all), or subtly broken (ran but buggy)?

**Comment by ekluzek** [comment]
It was totally broken, so it wouldn't work at all. So if it works now -- that means we are good. They had to totally rebuild all of the ESMF libraries to get them to work. The only subtle issue I know of is the difference between 7.0.0 and 7.1.0r where 7.0.0 can sometimes produce a bad mapping file.

**Comment by billsacks** [comment]
Given that I've done testing on master with this change, I'd suggest simply cherry-picking the relevant commit onto the release branch, without a need for further testing. @ekluzek if you're comfortable with this, I can go ahead and do it.

**Comment by ekluzek** [comment]
I need to make a new release tag with a FATES update and a bugfix. So I can include this cherry-pick there.

**Comment by billsacks** [comment]
@ekluzek this issue auto-closed because I fixed it on master, but I think it still needs to be fixed in the release branch. So I'll reopen it and label it appropriately.

**Comment by ekluzek** [comment]
Fixed in release-clm5.0.21
