### ISSUE TITLE
Convert SCRIP grid files used by mkmapdata.sh to ESMF unstructured format

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#648]
mkmapdata.sh currently uses SCRIP grid files to generate the mapping files. With the update in #643, we will want to update these files into ESMF UGRID format. UGRID format contains the connectivity information that helps with running in parallel. There are two tasks to do that.

First is to convert the current SCRIP files into ESMF format using the standard ESMF tool. ESMF_Scrip2Unstruct that is created with ESMF distributions. 

The second is to update the files in namelist_defaults_ctsm_tools.xml from SCRIP grid format to ESMF_UGRID. I think the first step would be to add new fields that parallel the following type of fields in the file:

`<scripgriddata hgrid="0.9x1.25"  lmask="nomask" >lnd/clm2/mappingdata/grids/0.9x1.25_c110307.nc</scripgriddata>`

with a new name something like "esmfgriddata".

**Comment by ekluzek** [comment]
The format should be ESMF unstructured mesh and NOT UGRID.

**Comment by ekluzek** [comment]
@bekozi @slevisconsulting @negin513 note this is something we talked about today, but we said we just needed SCRIP grid files. We do need the destination grids to be SCRIP grid files since gen_domain requires it. But, the source grids could be in a different format (and note the 1km file already is in UGRID format). This is still a possible performance optimization that we could take advantage of.

**Comment by slevisconsulting** [comment]
@ekluzek I'm writing a script to run ESMF_Scrip2Unstruct, and I thought I'd let you know in case you already had a script to share.

**Comment by ekluzek** [comment]
No I don't. @mvertens did this step for some of the SCRIP files, but I'm not sure how many she converted. So you might look to see if you can find the files she made.  I'm assuming they would be somewhere near the existing SCRIP grid files.

**Comment by slevisconsulting** [comment]
@mvertens I see that you made such files for all but the 0.25x0.25 resolution. This is the raw dataset resolution of the LAI, PFT, harvest, and soil color variables.

Do you happen to still have a copy to share of the script that you used to convert the SCRIP files to unstructured mesh?

**Comment by mvertens** [comment]
Unfortunatley, I no longer have that script. It would be useful frankly to
regenerate all of these files since I did not do a careful validation of
the conversion and the conversion script has been updated since then.

**Comment by ekluzek** [comment]
With #1663 this won't be needed.
