### ISSUE TITLE
inputdata file in netcdf4 format 

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/ctsm#649]
Can we get the file 
/glade/p/cesmdata/cseg/inputdata/lnd/clm2/mappingdata/grids/UGRID_1km-merge-10min_HYDRO1K-merge-nomask_c130402.nc 
converted to the 64bit_data type - netcdf4 is causing lots of headaches.

**Comment by billsacks** [comment]
This is not something I have time to work on imminently, so I'm unassigning myself. Also, as per some issues that @ekluzek has opened recently, we plan to convert this to a completely different format. 

Can you please describe what trouble this is causing for you?

**Comment by ekluzek** [comment]
I'm not sure we can. The format of this file was picked to be NetCDF4, because of it's size.

This file should only be read by the offline tools like mksurfdata_map though, so I'm not sure why it would be causing trouble. Is this for people trying to generate surface datasets for CLM?

**Comment by jedwards4b** [comment]
Yes - apparently netcdf-4 is not playing well with esmf at nersc - the 64bit_data format should be able to handle it.

**Comment by billsacks** [comment]
@jedwards4b can you please provide more information about who is running into this problem and what they're trying to do? For a number of reasons, we don't currently support the use of CLM's tools that use this file anywhere other than cheyenne. (By the way: This was discussed in an email May 18, 2017, when you raised the same issue and Erik replied the same way.)

**Comment by jedwards4b** [comment]
Ben Hillman is on slack - please communicate with him and get me out of the loop.  Thanks

**Comment by billsacks** [comment]
From reading the conversation on slack, it looks like Ben Hillman has resolved his problem (presumably for e3sm). We can revisit this on our side when we convert this file to the newer ESMF unstructured grid format that we plan to use. At that point, we can try using 64bit_offset or (as you recommended on slack, @jedwards4b ) 64bit_data (https://www.unidata.ucar.edu/software/netcdf/docs/netcdf_introduction.html#netcdf_64bit_data_format).
