### ISSUE TITLE
Floating overflow in SoilBiogeochemNitrifDenitrifMod.F90

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#65]
**Bill Sacks < sacks@ucar.edu > - 2017-07-06 13:16:08 -0600**
**Bugzilla Id:** [2488](http://bugz.cgd.ucar.edu/show_bug.cgi?id=2488)
**Bugzilla CC:**  andre@ucar.edu,  cdkoven@lbl.gov,  dlawren@ucar.edu,  rfisher@ucar.edu, 

On the compsetchanges branch (soon to be clm4_5_16_r249), the following tests are failing:

SMS_Ld5_D_P24x1.f10_f10_musgs.IHistClm50Bgc.hobart_nag.clm-decStart
ERP_D_P24x1.f10_f10_musgs.IHistClm50Bgc.hobart_nag.clm-decStart
ERP_D.f10_f10_musgs.IHistClm50Bgc.yellowstone_gnu.clm-decStart

The two hobart_nag tests point to line 443 of SoilBiogeochemNitrifDenitrifMod.F90. The last one dies in the same module; no line numbers are available, but my guess is that it's the same problem.

This death occurs in this block of code:

            if ( soil_co2_prod(c,j) > 0 ) then
               ratio_no3_co2(c,j) = smin_no3_massdens_vr(c,j) / soil_co2_prod(c,j)
            else
               ! fucntion saturates at large no3/co2 ratios, so set as some nominally large number
               ratio_no3_co2(c,j) = 100._r8
            endif

where line 443 is:

               ratio_no3_co2(c,j) = smin_no3_massdens_vr(c,j) / soil_co2_prod(c,j)

Probably the conditional needs to be changed so that if soil_co2_prod is *close* to 0, some alternative is used, but this needs some scientific input.

**Comment by billsacks** [comment]
**Erik Kluzek < erik@ucar.edu > - 2017-07-07 15:38:10 -0600**

I looked into the case on yellowstone with gnu in the ddt debugger, and soil_co2_prod(c,j) is order 1.e-317, so extremely small, while smin_no3_massdens_vr(c,j) was order 1.e-3.

**Comment by billsacks** [comment]
**Erik Kluzek < erik@ucar.edu > - 2017-09-14 13:57:09 -0600**

Here's the fix I have on a branch that I'll bring to the trunk...

Index: soilbiogeochem/SoilBiogeochemNitrifDenitrifMod.F90
===================================================================
--- soilbiogeochem/SoilBiogeochemNitrifDenitrifMod.F90	(revision 86613)
+++ soilbiogeochem/SoilBiogeochemNitrifDenitrifMod.F90	(working copy)
@@ -439,7 +439,7 @@
             ratio_k1(c,j) = max(1.7_r8, 38.4_r8 - 350._r8 * diffus(c,j))
 
             ! ratio function (figure 7c)
-            if ( soil_co2_prod(c,j) > 0 ) then
+            if ( soil_co2_prod(c,j) > 1.0e-9_r8 ) then
                ratio_no3_co2(c,j) = smin_no3_massdens_vr(c,j) / soil_co2_prod(c,j)
             else
                ! fucntion saturates at large no3/co2 ratios, so set as some nominally large number

**Comment by billsacks** [comment]
At least as of CLM tag r272 (that's as far back as I looked: for r272 I checked @ekluzek 's case directory from his testing), this test `ERP_D.f10_f10_musgs.IHistClm50Bgc.cheyenne_gnu.clm-decStart` is no longer failing due to this issue, but is instead failing due to https://github.com/escomp/mosart/issues/3

**Comment by ekluzek** [comment]
This issue does have a potential to change answers. For example this test case

LVG_Ld5_D.f10_f10.I1850Clm50Bgc.cheyenne_intel.clm-no_vector_output

Showed a roundoff difference in the field: F_N2O_DENIT.

**Comment by billsacks** [comment]
@ekluzek this was fixed by #333 and so should be closed, right?

**Comment by ekluzek** [comment]
Fixed in clm5.0.dev0004
