### ISSUE TITLE
ERP tests are failing on fates_next_api

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#668]
### Brief summary of bug

ERP tests fail on fates_next_api

### General bug information

**CTSM version you are using:** clm5.0.dev008-91-ga7aa4f9
**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** ERP tests

### Details of bug

ERP tests are failing, due to not finding the rof restart files. ERS tests pass. I think this is an issue with the version of cime being used.ERP_D_P32x2_Ld3.f19_g16.I2000Clm50FatesCruGs.cheyenne_intel.clm-FatesColdDef.GC.clm5d8-fna-n1chintelf

### Important details of your setup / configuration so we can reproduce the bug

FAIL       ERP_D_Ld3.f19_g16.I2000Clm50FatesCruGs.cheyenne_intel.clm-FatesColdDef                     RUN
FAIL       ERP_D_P32x2_Ld3.f19_g16.I2000Clm50FatesCruGs.cheyenne_intel.clm-FatesColdDef               RUN
FAIL       ERP_Ld9.f45_f45_mg37.I2000Clm50FatesCruGs.cheyenne_intel.clm-FatesAllVars                  RUN

### Important output or errors that show the problem

>  .clm5d8-fna-n1chintelf.mosart.r.0001-01-03-00000.nc
>  (GETFIL): failed getting file from full path: 
>  ./ERP_D_P32x2_Ld3.f19_g16.I2000Clm50FatesCruGs.cheyenne_intel.clm-FatesColdDef.
>  GC.clm5d8-fna-n1chintelf.mosart.r.0001-01-03-00000.nc                          
>                                                                                 
>                     
>  ERROR: 
>  GETFIL: FAILED to get ./ERP_D_P32x2_Ld3.f19_g16.I2000Clm50FatesCruGs.cheyenne_i
>  ntel.clm-FatesColdDef.GC.clm5d8-fna-n1chintelf.mosart.r.0001-01-03-00000.nc

**Comment by rgknox** [comment]
@ekluzek , the ERP tests with fates_next_api and fates/master do pass (the hydro was the only one that didn't)

**Comment by ekluzek** [comment]
@rgknox. Hmmm. I'm on a branch that based off of fates_next_api and using NGEET/fates/sci.1.23.0_api.7.1.0 (which is almost the same as NGEET/fates/master). The Externals in that version aren't working. But, if I update the Externals to those in ctsm1.0.dev031 I do get it to work. What externals are you using and on what machine?

**Comment by rgknox** [comment]
@ekluzek, I'm running a test on the following:

https://github.com/ESCOMP/ctsm/compare/fates_next_api...rgknox:rgknox-update-externals-FNA
