### ISSUE TITLE
mksurfdata.pl aborts with "** Invalid ssp_rcp:"  for default and explicit ssp_rcp argument. Quotation marks interfere in is_valid_value() function

### ISSUE THREAD

**Issue by lstrebel** [ESCOMP/ctsm#672]
### Brief summary of bug

While trying to create a custom data set, using the mksurfdata.pl script, it stops and claims that an invalid ssp_rcp was used as input. 
This error occurs regardless of the ssp_rcp argument, i.e. not providing it and using the default: hist or when explicitly providing a ssp_rcp value (e.g. hist, SSP1-2.6, or any other value listed in $CTSMROOT/bld/namelist_files/namelist_definition_clm4_5.xml).

### General bug information
**CTSM version you are using:** release-clm5.0.19-31-gc9868bf
**Does this bug cause significantly incorrect results in the model's science?** No
**Configurations affected:** Creating custom data sets

### Details of bug

As mentioned in the summary, the bug appears when using mksurfdata.pl with or without -ssp_rcp argument.
The error message originates from the "is_valid_value()" function for the "ssp_rcp" variable.
By looking at the values during processing of the "is_valid_value()" function in the $CTSMROOT/cime/utils/perl5lib/Build/NamelistDefinition.pm file I found that the source of the bug seems to be quotation marks.
The "get_valid_values" function used in the "is_valid_value()" function accepts an optional argument "noquotes" to return values without quotation marks.
So by adding "noquotes=>1" to the "is_valid_value" function call in mksurfdata.pl the error seems to be solved, e.g.

$CTSMROOT/tools/mksurfdata_map/mksurfdata.pl line 541 :
``` perl
      if ( ! $definition->is_valid_value( "ssp_rcp", $ssp_rcp, noquotes=>1) ) {
```
Seems to resolve the issue.

Since I did not see this problem mentioned in any issues or pull requests and it happened to me for default values I wanted to let you know about it.
The tests for the tools ($CTSMROOT/test/tools) including mksurfdata.pl tell me that they only work on cheyenne or hobart, so I did not run them to check if my change interferes with anything else.

### Important details of your setup / configuration so we can reproduce the bug
I am running on a custom machine, but I have made no changes to xml or namelist files.
Also the error appears on a completely fresh clone and using only default values, e.g. 
```shell
$ git clone -b release-clm5.0 https://github.com/ESCOMP/ctsm.git clm5.0
$ cd clm5.0
$ ./manage_externals/checkout_externals
$ cd tools/mksurfdata_map/
$ ./mksurfdata.pl
$ ** Invalid ssp_rcp: hist
$ SYNOPSIS (...)
```

**Comment by billsacks** [comment]
@lstrebel thank you for filing this issue and providing all of this information.

@ekluzek can you take a look at this?

**Comment by ekluzek** [comment]
This actually works for me in release-clm5.0.19 (at least if I specify a resolution). Giving no arguments to mksurfdata.pl actually makes it run over a default resolution which happens to be conus_30_x8, It dies for me, because of quotes around the resolution that it inserts into the filename.

```
 fdyndat        = ''
 numpft = 78
/
./mksurfdata_map < surfdata_'conus_30_x8'_hist_78pfts_CMIP6_simyr1850_c190401.namelist
sh: surfdata_conus_30_x8_hist_78pfts_CMIP6_simyr1850_c190401.namelist: No such file or directory
ERROR in mksurfdata_map: 256
```

@lstrebel the bug description says you are using "release-clm5.0.19-31-gc9868bf". So that shows changes beyond release-clm5.0.19. Is this a branch you are working with? What are the changes beyond release-clm5.0.19 that are part of what you are doing?

**Comment by lstrebel** [comment]
@ekluzek "release-clm5.0.19-31-gc9868bf" is what I get from git describe just after:
```shell
$ git clone -b release-clm5.0 https://github.com/ESCOMP/ctsm.git clm5.0
```
as described on the webpage. 

So I am not working with a different branch than the "release-clm5.0" branch from this repository at the moment. The changes after the "release-clm5.0.19" tag should be the same as the changes here, right? (The last commit in the log is c9868bf5743ababa9e156be9b280028b1ae06d73)

When I checkout the "release-clm5.0.19" tag and run mksurfdata.pl without argument I also get to the point where the default resolution is needed.

Quickly looking at the difference between the tag and the current commit I notice that there is a small difference in the $CTSMROOT/bld/namelist_files/namelist_definition_clm4_5.xml.
The entry for the ssp_rcp value changes from working with:
``` xml
<entry id="ssp_rcp" type="character*8" category="default_settings" group="default_settings" valid_values="hist,SSP1-2.6,SSP3-7.0,SSP5-3.4,SSP2-4.5,SSP1-1.9,SSP4-3.4,SSP4-6.0,SSP5-8.5">
```
to not working with
``` xml
<entry id="ssp_rcp" type="char*8" category="default_settings" group="default_settings" valid_values="hist,SSP1-2.6,SSP3-7.0,SSP5-3.4,SSP2-4.5,SSP1-1.9,SSP4-3.4,SSP4-6.0,SSP5-8.5">
```
(I quickly checked this on the current commit, reverting my "noquotes=>1" addition and only changing the type in the namelist_definition_clm4_5.xml file also solves the issue.)

I am not familiar enough with perl and xml parsing to know why that change in the type description causes this different behavior with quotation marks. But other entries are also using type="char*".

I hope this helps.

**Comment by ekluzek** [comment]
Ahhh, OK thanks @lstrebel. Yeah, there's a problem on our end regarding the release-clm5.0.20 tag in git. It's our problem (and specifically my mistake). I've pushed a commit to release-clm5.0, which should resolve that issue. So now release-clm5.0 and release-clm5.0.20 should look the same, and "git describe" in a checkout of release-clm5.0 should say "release-clm5.0.20" rather than "release-clm5.0.19-31-gc9868bf" as it did before.

So on your end, if you pull those changes down with...

`git pull escomp release-clm5.0`

Where, escomp is the main CTSM repo..

``` csh
git remote -v
escomp	git@github.com:ESCOMP/ctsm (fetch)
escomp	git@github.com:ESCOMP/ctsm (push)
```

that should get your release-clm5.0 branch matching release-clm5.0.20.

**Comment by ekluzek** [comment]
OK, now I'm seeing the problem, now that I straightened out the issue with the release branch...

**Comment by ekluzek** [comment]
@lstrebel OK, I have this simple fix that I'll be bringing into the release branch as a new tag. I haven't tested much with it, but it does seem to work. Thanks for pointing out the problem...

``` perl
diff --git a/tools/mksurfdata_map/mksurfdata.pl b/tools/mksurfdata_map/mksurfdata.pl
index ee7b180..72cc9eb 100755
--- a/tools/mksurfdata_map/mksurfdata.pl
+++ b/tools/mksurfdata_map/mksurfdata.pl
@@ -538,7 +538,7 @@ sub write_namelist_file {
    my @rcpaths = split( ",", $opts{'ssp_rcp'} );
    # Check that ssp_rcp is valid
    foreach my $ssp_rcp ( @rcpaths  ) {
-      if ( ! $definition->is_valid_value( "ssp_rcp", $ssp_rcp ) ) {
+      if ( ! $definition->is_valid_value( "ssp_rcp", "'$ssp_rcp'" ) ) {
           print "** Invalid ssp_rcp: $ssp_rcp\n";
           usage();
        }
```

**Comment by lstrebel** [comment]
@ekluzek 

> that should get your release-clm5.0 branch matching release-clm5.0.20.

Yes, thanks, now the branch matches the tag.

> @lstrebel OK, I have this simple fix that I'll be bringing into the release branch as a new tag. I haven't tested much with it, but it does seem to work. 

I can confirm that this fix also works for my case. So from my side this issue can be closed.

**Comment by ekluzek** [comment]
Fixed in release-clm5.0.21
