### ISSUE TITLE
small dataset option for DATM_PRESAERO

### ISSUE THREAD

**Issue by rgknox** [ESCOMP/ctsm#681]
### Details of support request

I don't have a great sense of what the DATM_PRESAERO data does.  I think its for snow albedo right?  But if this dataset does not have a significant impact on land simulations of terrestrial vegetation, I was wondering if there is a cheaper dataset that could be used instead of:

aerosoldep_WACCM.ensmean_monthly_hist_1849-2015_0.9x1.25_CMIP6_c180926.nc

I suppose its not a big deal to just download the dataset, but I was just curious if there something smaller that would work.

From env_run.xml:

```
    <entry id="DATM_PRESAERO" value="clim_2000">
      <type>char</type>
      <valid_values>none,clim_1850,clim_2000,clim_2010,trans_1850-2000,rcp2.6,rcp4.5,rcp6.0,rcp8.5,cplhist</valid_values>
      <desc>DATM prescribed aerosol forcing</desc>
    </entry>
```

Datasets available:

```
cheyenne5 home/rgknox> du -h $CESMDATAROOT/inputdata/atm/cam/chem/trop_mozart_aero/aero/* 
7.6G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aero_1.9x2.5_L26_1850-2005_c091112.nc
8.0G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aero_1.9x2.5_L26_1850-2020_c130627.nc
428M	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aero_1.9x2.5_L26_1850clim_c090420.nc
430M	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aero_1.9x2.5_L26_1850clim_c091112.nc
428M	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aero_1.9x2.5_L26_2000clim_c090803.nc
430M	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aero_1.9x2.5_L26_2000clim_c091112.nc
4.7G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aero_b.e11.TSREFC2.f19.f19.ccmi23.001_c141030.nc
5.9G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aero_rcp26_v1_1.9x2.5_L26_1995-2105_c100316.nc
5.9G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aero_rcp45_v1_1.9x2.5_L26_1995-2105_c100316.nc
6.3G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aero_rcp45_v1_1.9x2.5_L26_1995-2505_c100720.nc
12G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aero_rcp60_1.9x2.5_L26_1850-2105_c130815.nc
6.2G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aero_rcp60_1.9x2.5_L26_1995-2105_c100901.nc
12G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aero_rcp85_v1_1.9x2.5_L26_1850-2105_c140307.nc
5.9G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aero_rcp85_v1_1.9x2.5_L26_1995-2105_c100202.nc
6.3G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aero_rcp85_v2_1.9x2.5_L26_1995-2505_c100720.nc
2.8G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aerosoldep_monthly_1849-2006_1.9x2.5_c090803.nc
12G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aerosoldep_monthly_1849-2015_0.9x1.25_CMIP6_c180924.nc
32K	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aerosoldep_monthly_1850_1x1_tropicAtl_c091026.nc
18M	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aerosoldep_monthly_1850_mean_1.9x2.5_c090421.nc
18M	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aerosoldep_monthly_2000_mean_1.9x2.5_c090421.nc
4.5G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aerosoldep_rcp2.6_monthly_1849-2104_1.9x2.5_c100402.nc
18G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aerosoldep_rcp4.5_monthly_1849-2104_0.9x1.25_c100407.nc
4.5G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aerosoldep_rcp4.5_monthly_1849-2104_1.9x2.5_c100402.nc
4.5G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aerosoldep_rcp4.5_monthly_1849-2505_1.9x2.5_c100929.nc
4.5G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aerosoldep_rcp6.0_monthly_1849-2104_1.9x2.5_c100830.nc
4.5G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aerosoldep_rcp8.5_monthly_1849-2104_1.9x2.5_c100201.nc
4.5G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aerosoldep_rcp8.5_monthly_1849-2505_1.9x2.5_c100929.nc
1.9G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aerosoldep_rcp8.5_monthly_2000-2104_1.9x2.5_c100209.nc
12G	/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart_aero/aero/aerosoldep_WACCM.ensmean_monthly_hist_1849-2015_0.9x1.25_CMIP6_c180926.nc
```

My compset:

2000_DATM%CRUv7_CLM50%FATES_SICE_SOCN_SROF_SGLC_SWAV

**Comment by ekluzek** [comment]
The main affect is certainly in snow. But, I think it might have an effect on maybe a few other things, looking at the code. We used to have datasets for single years, and a different dataset for historical. But, this means you have to coordinate three files, rather than just one. And with the one dataset, you know each of the single years within it are going to be the same as the historical. This is something that I just fixed, so I am a bit loath to go back.

However, Jim Edwards also noticed that this file was large, and we made a change so that A compsets wouldn't need it. So if we really need to have a smaller dataset for tropical testing of present day -- I might be convinced to add that. We could add a single option that was for say "2000_test" to note that it was something that you'd only use for testing, and wouldn't be kept up to date with the latest transient dataset.

There is a workaround you can use, by adding some lines to user_nl_datm. Is that sufficient? The next level would be to add an extra option to DATM_PRESAERO as I talk about above. And the final level would be to have it turned on for certain compsets. So how would we identify which compsets this would be used for?

Would you be willing to run a test for a tropical Fates run, to see if using a different dataset changes answers?

**Comment by rgknox** [comment]
Sure, I could help run some tests @ekluzek.   I would label this as low-priority for my personal needs (just waiting for a download afaik), but if you think this would be a useful improvement, I'm happy to help.

**Comment by dlawrenncar** [comment]
For the record, aerosol deposition only affects snow albedos.

**Comment by ekluzek** [comment]
Thanks for that clarification @dlawrenncar. It looked like that was the case, but hard to tell for sure. And as with everything there could be a bug in the code that means it's not working the way it should.

**Comment by billsacks** [comment]
From @ekluzek - we probably won't do this.
