### ISSUE TITLE
Add a system test: turning on carbon isotopes shouldn't change answers

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#686]
We should have a test that runs done with and without carbon isotopes don't change answers. This would be similar to #571 , and similar to the existing LVG test.

With the new cprnc, for this to pass, we'd need a namelist flag that turns off the carbon isotope diagnostic fields so that there are no differences in field lists.

**Comment by ekluzek** [comment]
I've got this started. I'm calling it LCISO for Land Carbon ISOtope test.

**Comment by ekluzek** [comment]
A good test for this is: LCISO_Lm13.f10_f10_musgs.IHistClm50BgcCrop.cheyenne_intel.clm-ciso_monthly. It fails without the bug fix and passes with it.

**Comment by billsacks** [comment]
Great, thanks @ekluzek . I find it helpful when tests have a comment describing why we have this particular test - for the sake of later test suite rework. If you haven't already, can you please add a comment like, "Want a LCISO test of a transient case that crosses the year boundary. Would have used a decStart test if ESCOMP/ctsm#404 were resolved."
