### ISSUE TITLE
time_bnds not set by tools/ncl_scripts/getco2_historical.ncl

### ISSUE THREAD

**Issue by klindsay28** [ESCOMP/ctsm#708]
tools/ncl_scripts/getco2_historical.ncl
takes a greenhouse gas file used by CAM and produces one usable by streams

The script defines the variable `time_bnds` in the generated file, but never sets its value. So the values of `time_bnds` in the generated file end up being set to FillValue. While this is not a problem for datm, it does cause problems for other tools trying to parse the time variable's metadata.

Appropriate values are available in CAM files being read by tools/ncl_scripts/getco2_historical.ncl.

Could tools/ncl_scripts/getco2_historical.ncl be modified to copy time_bnds from the source file to the file being generated?

**Comment by ekluzek** [comment]
@klindsay28 yes I should be able to fix that. I'm also working on getting the CO2 files in place. Do we want this fix in for the CESM2.1.1 release?

**Comment by klindsay28** [comment]
I can work around the issues that I've encountered because of this, so I don't think it is urgent.
So I would not consider this as must have for the 2.1.1 release.

**Comment by klindsay28** [comment]
@ekluzek, while you're at it, could you also change attribute named `lname` in the generated file to `long_name`. `lname` is not a standard attribute for netCDF metadata, while `long_name` is.

I can put this in a separate issue if you prefer.

**Comment by ekluzek** [comment]
OK, looks like these are the changes needed:

``` ncl
diff --git a/tools/ncl_scripts/getco2_historical.ncl b/tools/ncl_scripts/getco2_historical.ncl
index 8558f6d..1df0f82 100644
--- a/tools/ncl_scripts/getco2_historical.ncl
+++ b/tools/ncl_scripts/getco2_historical.ncl
@@ -58,7 +58,7 @@ begin
    ntime   = dimsizes( ncg->date );
    sim_yr2 = ncg->date(ntime-1) / 10000;
 
-   sim_yr_rng = "_simyr_"+sim_yr0 + "-" + sim_yr2;
+   sim_yr_rng = "simyr_"+sim_yr0 + "-" + sim_yr2;
    
    cmip_vers = "_CMIP6_";
    outco2filename = "fco2_datm_"+hgrid+ssp_rcp+"_"+sim_yr_rng+cmip_vers+"c"+sdate+".nc";
@@ -103,7 +103,7 @@ begin
          end if
       end if
       nco->$vars(i)$@units = units(i);
-      nco->$vars(i)$@lname = lname(i);
+      nco->$vars(i)$@long_name = lname(i);
    end do
    filevardef ( nco, "time",      "float",    (/ "time" /) );
    filevardef ( nco, "time_bnds", "float",    (/ "time", "bounds" /) );
@@ -170,6 +170,7 @@ begin
    ;
    nco->date = (/ ncg->date /);
    nco->time = (/ ncg->time /);
+   nco->time_bnds = (/ ncg->time_bnds /);
    nco->date@comment = "This variable is NOT used when read by datm, the time coordinate is used";
    ;
    ; CO2
```
