### ISSUE TITLE
QDRIP diagnostic field misleadingly named

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#709]
The QDRIP diagnostic field is defined as:

```Fortran
    call hist_addfld1d ( &
         fname=this%info%fname('QDRIP'), &
         units='mm/s',  &
         avgflag='A', &
         long_name=this%info%lname('throughfall'), &
         ptr_patch=this%qflx_prec_grnd_patch, c2l_scale_type='urbanf')
```

The short and long name give the impression that this just includes water that hits the canopy and then falls through. (From https://en.wikipedia.org/wiki/Throughfall - "In Hydrology, throughfall is the process which describes how wet leaves shed excess water onto the ground surface. These drops have greater erosive power because they are heavier than rain drops.") However, `qflx_prec_grnd_patch` includes ALL rain/snow reaching the ground or snowpack, including anything that never interacted with the canopy at all. For example, if there is no vegetation at all, it looks to me like this will be the total incoming rain+snow.

@olyson @swensosc - Can we come up with a better name and description for this variable?

**Comment by swensosc** [comment]
I agree that qdrip should just be the amount of precip that is intercepted and then reaches the ground. Qthroughfall would be the water reaching the ground. As lai goes to zero qthroughfall should go to total precip. Not sure if these terms should be separated by phase

**Comment by billsacks** [comment]
Thanks for your thoughts @swensosc 

We already have QFLX_RAIN_GRND and QFLX_SNOW_GRND, which give the total amount of liquid water and snow reaching the ground, though those are inactive by default. qflx_prec_grnd_patch is the sum of those. I'm not sure 'QTHROUGHFALL' is the right name based on the wikipedia definition of throughfall. Maybe QFLX_PREC_GRND? (though it also includes irrigation, so "PREC" is a bit of a misnomer, as is "RAIN" for that matter in the existing hist field)

As to this:

> qdrip should just be the amount of precip that is intercepted and then reaches the ground

I don't think we currently have a term in the model that exactly equates to that.

@olyson do you know if the diagnostics package (or users in general) relies on the QDRIP field? Will I break anything if I rename that field.

**Comment by swensosc** [comment]
Qdrip would be the flux from h2ocan

**Comment by billsacks** [comment]
> Qdrip would be the flux from h2ocan

So do you mean `qflx_liqcanfall`? (On master that's a local variable, but on the branch I'm working on, I have moved that to WaterFluxType, so it's easy for me to add a diagnostic field for it if that's what you want.)

**Comment by olyson** [comment]
Removing/renaming QDRIP shouldn't break anything in the diagnostics package.  I don't think any of our standards scripts rely on that.

**Comment by billsacks** [comment]
Clarifications from @swensosc 

Throughfall does include precipitation that never hits the canopy.

QDRIP - `qflx_liqcanfall` - default inactive

QDRIP_SNOW - `qflx_snocanfall` - default inactive

QDIRECT_THROUGHFALL - `qflx_through_rain` - default inactive

QDIRECT_THROUGHFALL_SNOW - `qflx_through_snow` - default inactive

We'll get rid of a variable giving `qflx_prec_grnd_patch`.
