### ISSUE TITLE
Climate accumulator fields incorrect for CNDV

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#71]
**Bill Sacks < sacks@ucar.edu > - 2017-11-22 14:24:36 -0700**
**Bugzilla Id:** [2537](http://bugz.cgd.ucar.edu/show_bug.cgi?id=2537)
**Bugzilla CC:**  dlawren@ucar.edu,  rfisher@ucar.edu, 

CNDV's establishment rules use a number of climate accumulators, including some GDD accumulators. However, the temperature field used in these GDD accumulators is t_ref2m, which I believe is only valid over active (non-zero-weight) patches. This is a problem, since it appears that these GDD accumulators are used to determine the establishment of not-yet-active patches. Thus, I believe that CNDV is using a garbage GDD field in its establishment rules.

With some upcoming changes I'm planning to make, accumulator fields will only accumulate over active points - in contrast to the current situation where they accumulate constantly (including over inactive points), but may be accumulating garbage over inactive points. This will change the behavior somewhat for these GDD accumulators in CNDV, though I'm not sure that either is more "right" than the other: both the old and new seem to be doing the wrong thing with respect to CNDV establishment.

My proposed solution is to change the CNDV code to depend on the atmosphere's forcing temperature (the downscaled column-level variable) rather than t_ref2m. Dave Lawrence thinks this is reasonable - that, for these purposes, atmospheric forcing temperature is close enough to 2-m reference temperature. This column-level variable would be valid whenever there is a vegetated column, which should be sufficient for CNDV.

**Comment by billsacks** [comment]
**Bill Sacks < sacks@ucar.edu > - 2017-11-22 14:58:59 -0700**

*** Bug 2538 has been marked as a duplicate of this bug. ***

**Comment by billsacks** [comment]
**Bill Sacks < sacks@ucar.edu > - 2017-11-22 15:00:02 -0700**

Note that AGDDTW is also used to determine heat stress. I'm not sure if that should also be changed to use column-level forcing temperature for consistency and simplicity, or if it's important to continue to use 2-m temperature for that.

Also, note that AGDDTW is based on another accumulator (of 10-day running average temperature). So that one would also need to be changed to use column-level forcing temperature.

**Comment by billsacks** [comment]
**Bill Sacks < sacks@ucar.edu > - 2017-11-22 15:04:51 -0700**

See also the somewhat-related bug 2539

**Comment by billsacks** [comment]
**Bill Sacks < sacks@ucar.edu > - 2017-11-27 10:15:47 -0700**

Note that changing these patch-level CNDV variables to column-level will carry some challenges for backwards compatibility. This is do-able, but needs to be done carefully.

We've found that it's problematic to change the subgrid level of a restart variable without changing its name - particularly for init_interp. So we should give new names to the column-level versions of these variables.

If these variable changes only affect CNDV, we probably don't need to put in place special logic to give continuous results with old restart files. i.e., it's probably okay if these accumulators get reset when using old restart files. However, this should be given some more thought. It's possible that we'd at least want to hack together a new-style restart file (with these variables at col-level rather than patch-level) for the sake of CNDV tests in our test suite?

**Comment by billsacks** [comment]
**Bill Sacks < sacks@ucar.edu > - 2017-11-27 11:19:57 -0700**

TDA (used to set t_mo_patch and t_mo_min_patch) should also be moved to column-level. This should be easy, since it's fundamentally based on a col-level variable.

**Comment by billsacks** [comment]
**Bill Sacks < sacks@ucar.edu > - 2017-11-29 16:09:12 -0700**

CNDV also uses patch-level PREC365 for establishment rules. I think that field is currently okay for CNDV, but with my upcoming changes for bug 2526, this would become broken. I plan to move that field to column-level as part of fixing bug 2526: this should be pretty easy to do.

**Comment by ekluzek** [comment]
Since, we've deprecated CNDV, I'm closing this as a wontfix.
