### ISSUE TITLE
fcansno shouldn't depend on dewmx

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#710]
In the parameter extraction of ctsm1.0.dev040, this code in CanopyHydrologyMod.F90:

```Fortran
                   dewmxi  = 1.0_r8/dewmx(p)
                   fcansno(p) = ((dewmxi/(vegt*6.0_r8*10.0_r8))*snocan(p))**0.15_r8 ! must match snocanmx 
```

was changed to:

```Fortran
                   dewmxi  = 1.0_r8/params_inst%dewmx  ! wasteful division
                   fcansno(p) = ((dewmxi / (vegt * params_inst%sno_stor_max * 10.0_r8)) * snocan(p))**0.15_r8 ! must match snocanmx 
```

However, this looks wrong to me: I think this should be simply:

```Fortran
                   fcansno(p) = ((1._r8 / (vegt * params_inst%sno_stor_max)) * snocan(p))**0.15_r8 ! must match snocanmx 
```

i.e., fcansno should only depend on `sno_stor_max`, not on `dewmx`. (And that change would agree with `snocanmx` earlier in the module.)

Currently, the two give the same answers because dewmx is set to 0.1 on the paramfile. But if someone changed dewmx, they would inadvertently change fcansno, which I think would not be what they intended.

@slevisconsulting can you look at this and decide if you agree, and if so, make a small tag with this change at some point. (Or it could be combined with other changes, but I have a feeling this could change answers by roundoff, so it might be best to isolate this.)

**Comment by slevisconsulting** [comment]
Bill, you may be right, but first full disclosure, the definition of snocanmx earlier in the module used to say:
`snocanmx = 60._r8*dewmx(p) * (elai(p) + esai(p))  ! 6*(LAI+SAI)`
...and I changed it to
`snocanmx = params_inst%sno_stor_max * (elai(p) + esai(p))  ! 6*(LAI+SAI)`
because of the comment at the end of the line which indicates the value of sno_stor_max.

In the line that you're discussing, I saw the value 6 explicitly written in the formula, so I replaced it with sno_stor_max without touching the rest; however, I see now that my choice could lead to an inconsistency.

So in fact we may prefer to reintroduce dewmx to the snocanmx formula. And to ensure consistency, we may want to use snocanmx in the line that you're discussing instead of recalculating it there.

**Comment by billsacks** [comment]
@slevisconsulting thanks for clarifying this and raising these additional points. I see that it's unclear what's right here, but I do think we want to be consistent between these two uses of sno_stor_max. Can you please talk to the relevant people to determine what's desired here - i.e., if someone changes dewmx without changing anything else, do they expect snocanmx and fcansno to change?

**Comment by slevisconsulting** [comment]
@billsacks , Sean's response seems clear, so I can go ahead with this. One question though... Should I go back and modify the param files again to rename the two parameters as Sean recommends?

**Comment by slevisconsulting** [comment]
1) Made only the two parameter name-changes in the code.
2) Ran the test  ERS_D_Ld10.f10_f10_musgs.I2000Clm50BgcCropGs.cheyenne_intel.clm-rm_indiv_lunits_and_collapse_to_dom  and confirmed BFB against dev040. First Commit.
3) Made Sean's change to fcansno: the test returns not bfb anymore. Second commit.
4) Generated baseline for above test.
5) Updated fwet to the same format as fcansno: test comparing to baseline from (4) returns not bfb. Third commit.

**Comment by billsacks** [comment]
@slevisconsulting given that this changes answers, can you please hold off on doing full testing for a few days? I have massively reworked CanopyHydrology such that any changes you make probably will not merge cleanly with mine. I get nervous when merging two answer-changing tags together, especially when the merge needs to be done by hand. So I think it will be safest if you wait to do full testing & tagging until after I have made my next tag. Does that work for you?

At that point: I do like @swensosc 's suggested name changes, so if it's not too much trouble, then yes: I'd suggest making that change, too.

**Comment by slevisconsulting** [comment]
@billsacks I hope this thought doesn't arrive too late:
If you're reworking CanopyHydrology, then Sean's changes are minor enough that they could be folded into your reworking, no?

**Comment by billsacks** [comment]
@slevisconsulting I'd prefer to keep this separate, particularly because it involves some answer changes. (I don't like mixing together unrelated answer-changing things.)

Also: what do you think about @swensosc 's suggestion of changing these to be pft-dependent?

**Comment by slevisconsulting** [comment]
Sounds good.

I would not worry about making them pft-dependent, unless somebody is currently researching values to use for each pft. We have other scalars in the params file that should be pft-dependent, and it's easy to change any of them to pft-dependent when we obtain corresponding values for them.
