### ISSUE TITLE
CNDV logic for agdd20 and tmomin20 needs to be revised to account for when a given patch/column becomes active

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#72]
**Bill Sacks < sacks@ucar.edu > - 2017-11-22 15:04:27 -0700**
**Bugzilla Id:** [2539](http://bugz.cgd.ucar.edu/show_bug.cgi?id=2539)
**Bugzilla CC:**  rfisher@ucar.edu, 

CNDVDriver has the following logic:

      do p = bounds%begp, bounds%endp
         if (kyr == 2) then ! slevis: add ".and. start_type==arb_ic" here?
            tmomin20(p) = t_mo_min(p) ! NO, b/c want to be able to start dgvm
            agdd20(p) = agdd(p)       ! w/ clmi file from non-dgvm simulation
         end if
         tmomin20(p) = (19._r8 * tmomin20(p) + t_mo_min(p)) / 20._r8
         agdd20(p)   = (19._r8 * agdd20(p)   + agdd(p)    ) / 20._r8
      end do

However, this assumes that t_mo_min and agdd are valid from the start of the simulation. I believe that this is not the case for these patch-level variables. And with some changes I'm planning to make soon, accumulator fields will always be invalid for inactive points, making this certainly not the case.

I think the solution here is to use something like the nyrs_crop_active_patch that's used for crop gdd accumulation, rather than using a scalar year counter for all patches.

See also the somewhat-related bug 2537.

**Comment by ekluzek** [comment]
Since, we've deprecated CNDV, I'm closing this as a wontfix.
