### ISSUE TITLE
Proposed rework of issue labels

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#730]
Motivated by recent conversations with @ekluzek , I'd like to propose the following changes to our issue labels. I don't feel super strongly about any of this, but I think these changes will help make our issue labeling easier to use, both at the time of assigning labels, and in later searches.

(1) For "type" labels: Add a prefix of "c" for types that require changes to the repository (e.g., "type: c - bug") and "nc" for types that do not require changes (e.g., "type: nc - discussion"). This is to group together these two categories. I'm not at all tied to these particular prefixes.

(2) Slightly rework our "type" labels for types requiring changes, so that we have the following type labels in this category. I feel that each issue should get one and only one type label, so this is an attempt to simplify this "type" system and try to make it more obvious which type applies to a given issue. The labels I'm dropping have some value, but less than others, and it seems that streamlining our labels could lead to less confusion overall, so I feel it's worth weeding out those that provide the least value.
- `type: c - bug`
  - This no longer distinguishes between bugs that do / don't impact science. My rationale for consolidating those two labels is to reduce the number of "type" labels, and because whether or not a bug impacts science feels similar to whether a bug is "critical", and so seems to be more appropriate for a tag, just like we have a "critical" tag.
- `type: c - enhancement`
  - This no longer distinguishes between science & software enhancements because I feel we weren't gaining value from that distinction, and the distinction often seems quite subjective (many enhancements involve a mix of science & software enhancements).
- `type: c - code cleanup`
  - This would still include in-code comments, but would not include any user-facing documentation
- `type: c - documentation`
  - This would include any user-facing documentation. Previously I tried to distinguish between documentation that touched files that require testing (e.g., xml files) vs. documentation that only touches non-tested files. I feel that distinction is less useful than a distinction between user-facing documentation (sphinx-based documentation, wiki, README files, and documentation in xml files) vs. in-code documentation (comments).
  - Note that issues with this label are *just* about adding documentation. Other issues may have documentation needs as part of them.
- `type: c - tests`
  - Note that issues with this label are *just* about adding / changing tests. Other issues may have test changes as part of them.

(Labels for issues not requiring changes would be the same as before, but now with a "nc" prefix: `type: nc - discussion`, `type: nc - needs investigation`, `type: nc - support needed`).

(3) Add new "tag" labels, replacing some existing labels:
- `tag: bug - critical`
  - This is a rename of `severity: critical` in order to group this with `tag: bug - impacts science` and because it feels kind of funny to have one `severity:` label with no others
- `tag: bug - impacts science`
  - This replaces the `type: bug - impacts science` type label, both to reduce the number of "type" labels and to group this with the `tag: bug - critical` tag, because the two have similar flavors
- `tag: support tools only`
  - This replaces the `support tools` "type" label. The point of making this a tag is that this will typically be added on top of a bug, enhancement, code cleanup or documentation issue.

(4) Remove this tag:
- `tag: help wanted`
  - We haven't been using this label, and so I propose removing it to clean up our labeling unless we find a need for it

**Comment by billsacks** [comment]
@ekluzek let me know if you have thoughts on this, via comments in this issue or in person. If you don't have any further thoughts, I'll go ahead and make the proposed changes and we can try them out to see if things feel smoother that way.

**Comment by ekluzek** [comment]
@billsacks I think I like this -- other than "c" versus "nc". I like those two categories, but would like the "c" and "nc" to be more explicit. Maybe "change" vs "no-change"?

**Comment by billsacks** [comment]
@ekluzek Thanks for your feedback. You're right that "c" versus "nc" is confusing. However, I'm inclined to take this in a different direction, making the mechanism for separating these two categories more subtle rather than more pronounced, using something like an underscore for the "no-change" labels (so we'd have `type: _discussion`, etc.). The way I see it, the main goal here is just to group together the two sets of "type" labels; I don't see a need to explicitly add "change" or "no-change" to the name, and I feel that doing so will make it harder to quickly read through the labels of a lot of issues, as well as harder to type labels in search queries. The leading underscore doesn't make it clear why it's there (though I would add a note about it on the wiki page), but it would accomplish the main goal, and I don't see it as being confusing in practice.

Let me know if you disagree.

**Comment by billsacks** [comment]
I'm also going to shorten some labels: `type: needs investigation` -> `type: _investigation`, and `type: support needed` -> `type: _support`.

**Comment by billsacks** [comment]
> using something like an underscore for the "no-change" labels (so we'd have `type: _discussion`, etc.)

Apparently an underscore doesn't affect GitHub's sort order. A dash does (and of the many [but not all] special characters I tried, it was the only one that did) so I'll use that.

**Comment by billsacks** [comment]
Reviewing the issues with label, `type: enhance - science`, I realized that there are a handful that really represent big science developments, and it does feel worthwhile calling this out explicitly. I'm introducing a new tag, `tag: en - major new science` to capture these. (Apologies for the shortened "en" rather than "enhancement": I had a hard time fitting the label on one line.) I realize this is somewhat subjective, but it seems worth trying to have this label.

**Comment by billsacks** [comment]
Okay, I have reworked the issue labels as per this discussion, and have updated the wiki page (https://github.com/ESCOMP/ctsm/wiki/Issue-Labels). I have also added some helpful starting points for issue searches to that page (https://github.com/ESCOMP/ctsm/wiki/Issue-Labels#some-good-starting-points-for-issue-searches).
