### ISSUE TITLE
update fates_next_api to tag clm5.0.25

### ISSUE THREAD

**Issue by rgknox** [ESCOMP/CTSM#739]
CTSM release-clm5.0 is now compatible with FATES tag s1.21.0.a7.0.0, woohoo, thanks @ekluzek 

See: 
https://github.com/ESCOMP/ctsm/releases/tag/release-clm5.0.25
https://github.com/ESCOMP/ctsm/pull/687

I would like to now update (sync) fates_next_api to up-to-date with clm5.0.25.

**Comment by rgknox** [comment]
Not surprisingly, its easier to see the differences when merging fates_next_api onto release-clm5.0:

https://github.com/ESCOMP/ctsm/compare/release-clm5.0...fates_next_api?expand=1

But there are some divergences in these two files that I don't know the provenance of:
https://github.com/ESCOMP/ctsm/compare/release-clm5.0...fates_next_api?expand=1#diff-2e96c9c04940de331de6264cb46ffdcaR326

https://github.com/ESCOMP/ctsm/compare/release-clm5.0...fates_next_api?expand=1#diff-d8f969e5a5d4fe5f7706f9fb72cb3c2bR69

**Comment by rgknox** [comment]
Here it is:

https://github.com/ESCOMP/ctsm/commit/0a24f4bc069bef7f901239946ca1fa1c41746949

Are these changes @ckoven useful for your releases? Unless I hear otherwise, I will maintain these changes in fates_next_api as I merge in CLM5.0.25.

**Comment by ckoven** [comment]
yes as far as I know the code in 0a24f4b should be in all branches (master and fates_next_api). see #85. somehow it got reverted from the fates_next_api but shouldn't have.

**Comment by ekluzek** [comment]
In light of #1008 I think this one can now be closed as a WONTFIX. @ckoven and @rgknox do you agree?

**Comment by rgknox** [comment]
yeah, it seems this thread is out-dated now
