### ISSUE TITLE
Automatically download required raw data for making a new surface dataset

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#742]
As part of making the toolchain more usable on other systems, we want to provide a mechanism for automatically downloading required raw data for making a new surface dataset.

**Comment by ekluzek** [comment]
Here's what I would in slightly older versions of CLM...

http://www.cesm.ucar.edu/models/cesm1.2/clm/models/lnd/clm/doc/UsersGuide/x11868.html#getmksurfdata_map_datasets

I think the above will work with some modifications to paths. Obviously long term we need a tool that can just do this.

**Comment by billsacks** [comment]
Great, thanks @ekluzek . Yes, something like this needs to be folded into the toolchain so it happens without any extra work from the user.

**Comment by slevisconsulting** [comment]
Relates to #645

**Comment by slevisconsulting** [comment]
> Here's what I would in slightly older versions of CLM...
> 
> http://www.cesm.ucar.edu/models/cesm1.2/clm/models/lnd/clm/doc/UsersGuide/x11868.html#getmksurfdata_map_datasets
> 
> I think the above will work with some modifications to paths. Obviously long term we need a tool that can just do this.

From discussion with @ekluzek 
we don't want user to have to modify a namelist when running check_inputdata
but otherwise check_inputdata seems like the way to go for easy downloads because it's supported by the cime community.

**Comment by billsacks** [comment]
I agree that using check_inputdata is probably the way to go here. However, if I remember correctly from when I was leveraging check_inputdata for lilac, I think you'll need to create a fake case to do this and then put together an input data list in the correct location in the case directory. (Here's the wrapper script for downloading input data for lilac, though this assumes that the fake case directory has already been set up: https://github.com/escomp/CTSM/blob/master/python/ctsm/lilac_download_input_data.py .)

**Comment by slevisconsulting** [comment]
Thank you @billsacks

**Comment by slevisconsulting** [comment]
Works for mksurfdata_esmf (see #1748). Ok to close this issue?

**Comment by billsacks** [comment]
> Works for mksurfdata_esmf (see #1748). Ok to close this issue?

Yes - thank you for getting this working!
