### ISSUE TITLE
Prevent user from trying to use the same filename for init_interp source and destination files

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#750]
I accidentally set:

```
finidat = `/path/to/this/case/run/finidat_interp_dest.nc`
use_init_interp = .true.
```

I had meant to use `use_init_interp = .false.` - i.e., bypassing the interpolation by using an already-interpolated file.

Disturbingly, the case ran but gave incorrect results. I think what happened was:
- The case wrote out the cold start initial conditions to `finidat_interp_dest.nc`
- Then it read in these cold start initial conditions and used them for interpolation

So my guess is that it gave the same answers as if I had done a cold start run. (Though it's possible that trying to read and write from the same file caused additional problems, too.)

I'll put in a check to prevent users from making the same mistake I did. I'll try to write the check in a way that also catches and prevents #329 .

**Comment by ekluzek** [comment]
I like your explanation of this and the check that you are adding. But, my initial reading of your title was that you weren't going to allow LII tests to work. So you might want to clarify that in your title.

**Comment by billsacks** [comment]
Good point @ekluzek . I have changed the title.
