### ISSUE TITLE
Softlinks of files in the inputdata repo get saved as a symlink rather than datafile

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#757]
### Brief summary of bug

This was found by Simon Bursten

> ERROR: data file for this resolution does NOT exist (/home/vongalixor/Git/land_cover/inputdata/lnd/clm2/rawdata/pftcftdynharv.0.05x0.05.LUH2.histsimyr2005.c190119/mksrf_landuse_clm52deg005_histLUH2_1850.c190119.nc).
> 
> now, this file exists on my harddrive, checked out from svn, but it turns out to be a hardcoded symlink to a location i dont have on my system:
> 
> /home/vongalixor/Git/land_cover/inputdata/lnd/clm2/rawdata/pftcftdynharv.0.05x0.05.LUH2.histsimyr2005.c190119/mksrf_landuse_clm52deg005_histLUH2_1850.c190119.nc -> /glade/p/cesm/sdwg_dev/thesis/data/cesm_tools/surfacedata/clm52deg005rawdata/globalclm52histLUH2deg005_190119/mksrf_landuse_clm52deg005_histLUH2_1850.c190119.nc

### General bug information

**CTSM version you are using:** release-clm5.0.25

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** high resolution datasets in repo for mksurfdata_map

### Details of bug

It looks like softlinks to individual files (rather than softlinks at a directory level) when imported into svn end up saving the softlink rather than the datafile. So we need to save the datafiles by having the softlink at the directory level rather than the file level.

I think this only applies to the high resolution data for mksurfdata_map. In that case I did a softlink to the datafiles rather than through a softlink at the directory level.

**Comment by ekluzek** [comment]
There are two other files under inputdata for CLM that this applies to:

./lnd/clm2/surfdata_map/surfdata_13x12pt_f19_alaskaUSA_simyr2000.nc
./lnd/clm2/mappingdata/grids/fv0.9x1.25_070727.nc

But, they are no longer being used. So I'm not going to worry about them. Everything else as far as CTSM is considered is a softlink to a directory and hence doesn't have this problem.

It does look like: cpl, cesm, cam, waccm, ocn/roms and cice have such files though.

**Comment by lstrebel** [comment]
Hello,

I just noticed the same error as found by Simon Bursten for another file in the same directory:

ftp://ftp.cgd.ucar.edu/cesm/inputdata/lnd/clm2/rawdata/pftcftdynharv.0.05x0.05.LUH2.histsimyr2005.c190119/mksrf_lai_histclm52deg005_earthstatmirca_2005.c190119.nc

contains only:

link /glade/p/cesm/sdwg_dev/thesis/data/cesm_tools/surfacedata/clm52deg005rawdata/globalclm52histlaideg005_190119/mksrf_lai_histclm52deg005_earthstatmirca_2005.c190119.nc

Without access to glade, this keeps me from being able to use the -hirespft option of mksurfdata.pl.

**Comment by ekluzek** [comment]
I created new directory **lnd/clm2/rawdata/pftcftdynharv.0.05x0.05.LUH2.histsimyr2005.c190116** and copied the files from the "thesis" location into there. I also uploaded them into svn. The next release tag will update to point to these files.

@lawrencepj1

**Comment by ekluzek** [comment]
This was resolved on the release branch. So I'm closing it.
