### ISSUE TITLE
(CLM-only) Don't set h2osoi_vol for lake or urban

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#78]
**Erik Kluzek < erik > - 2010-08-24 11:09:10 -0600**
**Bugzilla Id:** [1205](http://bugz.cgd.ucar.edu/show_bug.cgi?id=1205)
**Bugzilla CC:**  dlawren,  rfisher,  sacks,  subin, 

BiogeophysRest has the following...

       do c = begc,endc
          l = clandunit(c)
          if ( ltype(l) == istdlak .or. ltype(l) == istslak )then
             nlevs = nlevlak
          else if ( ltype(l) == isturb )then
             nlevs = nlevurb
          else
             nlevs = nlevgrnd
          end if
          ! NOTE: THIS IS A MEMORY INEFFICIENT COPY
          do j = 1,nlevs
             cptr%cws%h2osoi_vol(c,j) = cptr%cws%h2osoi_liq(c,j)/(cptr%cps%dz(c,j)*denh2o) &
                                      + cptr%cws%h2osoi_ice(c,j)/(cptr%cps%dz(c,j)*denice)
          end do
       end do

It really should always run over nlevgrnd, and NOT do this step if it's a lake or urban land unit. We'll need to initialize h2osoi_vol to spval to do this, so that it will work for history output. But, I think that everything now has appropriate filtering so that it isn't needed by anything else later on.

Here's email from Zack Subin on this...

Hi Erik,

Yes, I think that h2osoi_vol shouldn't be set at all for the (current
unimproved) lakes; I'm not sure about urban.

--Zack

On Mon, 23 Aug 2010 17:59 -0600, "Erik Kluzek" <erik@ucar.edu> wrote:
Hey Zack

Yes, if you ran with nlevlak>nlevgrnd you would have subscript overflow,
and mess up memory. Whether that would screw up your results depends on
exactly what part of memory gets corrupted, and if it's critical or not.

I think the issue is that for urban and lake, dz and h2osoi_liq/ice are
only set to something reasonable up to nlevurb or nlevlak, but are set to
NaN after that, so if floating-point-trapping is on, it will die with an
error.

So possibly what should be done is that maybe these shouldn't be set at
all for urban and lake in BiogeoRestMod?

On Aug 5, 2010, at 9:21 PM, Zack Subin wrote:

Hi,

The code below doesn't make any sense to me.  For the current lake
model, h2osoi_vol is meaningless (so it's at best redundant), but
moreover should have dimensions 1:nlevgrnd, not 1:nlevlak.  This doesn't
mess up the history because h2osoi_vol is reset to spval in
HydrologyLake.  However, if someone ran with nlevlak > nlevsoi, then
this could cause a seg fault or memory corruption, yes?  Not sure why
that hasn't happened to me when running with 25 lake layers (or it
didn't change another variable egregiously enough for me to notice it if
it did...), and I must not have used restarts with debugging on.

--Zack

     do c = begc,endc
        l = clandunit(c)
        if ( ltype(l) == istdlak .or. ltype(l) == istslak )then
           nlevs = nlevlak
        else if ( ltype(l) == isturb )then
           nlevs = nlevurb
        else
           nlevs = nlevgrnd
        end if
        ! NOTE: THIS IS A MEMORY INEFFICIENT COPY
        do j = 1,nlevs
           cptr%cws%h2osoi_vol(c,j) =
           cptr%cws%h2osoi_liq(c,j)/(cptr%cps%dz(c,j)*denh2o) &
                                    +
                                    cptr%cws%h2osoi_ice(c,j)/(cptr%cps%dz(c,j)*denice)
        end do
     end do
___________________________________________________
Zack Subin
PhD Student, UC Berkeley Energy & Resources Group /
Lawrence Berkeley Lab Earth Sciences Division

subin@berkeley.edu | subin@post.harvard.edu
zack.subin@fastmail.fm | zmsubin@lbl.gov

Erik Kluzek, (CGD at NCAR)
National Center for Atmospheric Research
Boulder CO, (off) (303)497-1326 (fax) (303)497-1348
------------------ Home page ------------------------
         http://www.cgd.ucar.edu/~erik
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

___________________________________________________
Zack Subin
PhD Student, UC Berkeley Energy & Resources Group /
Lawrence Berkeley Lab Earth Sciences Division

subin@berkeley.edu | subin@post.harvard.edu
zack.subin@fastmail.fm | zmsubin@lbl.gov

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2010-08-31 14:21:50 -0600**

So I tried making this change, but I ended up with an exact restart problem. The restart problem makes me think that an incorrect usage of h2osoi_vol is being done for possibly urban points.

Here's the code change I put in...

> diff -c BiogeophysRestMod.F90 BiogeophysRestMod.F90.new
*** BiogeophysRestMod.F90       Tue Aug 31 13:52:10 2010
--- BiogeophysRestMod.F90.new   Tue Aug 31 13:50:36 2010
***************
*** 1551,1577 ****
      if (flag == 'read' ) then
         do c = begc,endc
            l = clandunit(c)
!           if ( ltype(l) == istdlak .or. ltype(l) == istslak )then
!              nlevs = nlevlak
!           else if ( ltype(l) == isturb )then
!              nlevs = nlevurb
!           else
!              nlevs = nlevgrnd
            end if
-           ! NOTE: THIS IS A MEMORY INEFFICIENT COPY
-           do j = 1,nlevs
-              cptr%cws%h2osoi_vol(c,j) = cptr%cws%h2osoi_liq(c,j)/(cptr%cps%dz(c,j)*denh2o) &
-                                       + cptr%cws%h2osoi_ice(c,j)/(cptr%cps%dz(c,j)*denice)
-           end do
         end do
-

         ! ------------------------------------------------------------
         ! If initial run -- ensure that water is properly bounded
--- 1551,1564 ----
      if (flag == 'read' ) then
         do c = begc,endc
            l = clandunit(c)
!           if ( ltype(l) /= istdlak .and. ltype(l) /= istslak .and. ltype(l) /= isturb )then
!              ! NOTE: THIS IS A MEMORY INEFFICIENT COPY
!              do j = 1,nlevgrnd
!                 cptr%cws%h2osoi_vol(c,j) = cptr%cws%h2osoi_liq(c,j)/(cptr%cps%dz(c,j)*denh2o) &
!                                          + cptr%cws%h2osoi_ice(c,j)/(cptr%cps%dz(c,j)*denice)
!              end do
            end if
         end do

         ! ------------------------------------------------------------
         ! If initial run -- ensure that water is properly bounded

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2010-08-31 14:27:47 -0600**

Here's a list of restart tests that both PASS and fail with the change in it...

grep FAIL td.795346.status | grep TER
007 erHS3 TER.sh _nrcnsc_do clm_usrdat 20030101:NONE:1800 13x12pt_f19_alaskaUSA gx1v6 -3+-3 arb_ic FAIL! rc= 13
011 erCA4 TER.sh _nrsc_ds clm_std^nl_urb 20021001:NONE:3600 1x1_camdenNJ navy -45+-45 arb_ic ....FAIL! rc= 13
015 erNB4 TER.sh _nrmexsc_ds clm_urb1pt^nl_urb 19931201:NONE:3600 1x1_mexicocityMEX navy 57+100 arb_FAIL! rc= 13
025 erAK4 TER.sh _sc_ds clm_std^nl_ptsmode 20030101:NONE:1800 1.9x2.5 gx1v6 -5+-5 cold ..........FAIL! rc= 7
034 erF93 TER.sh 17p_vodsrsc_do clm_std^nl_urb 20021230:NONE:1800 4x5 gx3v7 10+38 cold ..........FAIL! rc= 13
038 erL83 TER.sh _nrsc_do clm_std^nl_urb 20020115:NONE:3600 5x5_amazon navy -5+-5 arb_ic ........FAIL! rc= 13
> !124
grep PASS td.411417.status | grep TER
051 erV61 TER.sh _mec10sc_dh clm_glcmec 19980115:NONE:1800 1.9x2.5 gx1v6 10+38 arb_ic ...........PASS
> grep FAIL td.411417.status | grep TER
002 erA91 TER.sh _sc_dh clm_std^nl_urb 20030101:NONE:3600 4x5 gx3v7 -3+-3 arb_ic ................FAIL! rc= 13
006 erD91 TER.sh _persc_dh clm_per^nl_urb 20021231:NONE:1200 4x5 gx3v7 72+72 cold ...............FAIL! rc= 5
009 erE91 TER.sh 4p_vodsrsc_dh clm_std^nl_urb 20021230:NONE:1800 4x5 gx3v7 10+38 arb_ic .........FAIL! rc= 13
014 erF92 TER.sh 17p_vodsrsc_dm clm_std^nl_urb 20021230:NONE:1800 4x5 gx3v7 10+38 cold ..........FAIL! rc= 13
018 erEH1 TER.sh 4p_vodsrsc_dh clm_std^nl_urb 20021231:NONE:3600 1.9x2.5^0.9x1.25 gx1v6 10+38 arb_icFAIL! rc= 13
022 erHN1 TER.sh 17p_cnsc_dh clm_transient_rcp8.5 20051220:NONE:1800 1.9x2.5 gx1v6@1850-2100 -3+-7 cFAIL! rc= 5
026 erHO2 TER.sh 17p_cnsc_dm clm_drydep 20000704:NONE:1800 10x15 USGS@2000 -3+-7 cold ...........FAIL! rc= 13
030 erG41 TER.sh 17p_sc_dh clm_pftdyn 10001230:NONE:1800 10x15 USGS@1000-1002 72+72 arb_ic ......FAIL! rc= 5
035 erH41 TER.sh 17p_cnsc_dh clm_std^nl_noicertm_sclharv 20021230:NONE:1800 10x15 USGS@2000 10+38 coFAIL! rc= 13
039 erC45 TER.sh 17p_sc_m clm_pftdyn 18501230:NONE:3600 10x15 USGS@1850-2000 -3+-7 arb_ic .......FAIL! rc= 13
043 erC61 TER.sh _scnv_dh clm_std^nl_urb 20020101:NONE:1800 1.9x2.5 gx1v6 10+38 startup .........FAIL! rc= 13
047 erH52 TER.sh 17p_cnsc_dm clm_std^nl_urb 20020115:NONE:1800 10x15 USGS@2000 10+38 cold .......FAIL! rc= 13
056 erLI1 TER.sh _sc_dh clm_std 20020101:NONE:1800 94x192 T62 -5+-5 arb_ic ......................FAIL! rc= 5
060 erL58 TER.sh _sc_dh clm_std^nl_crcrop 20020115:NONE:1800 10x15 USGS 72+72 arb_ic ............FAIL! rc= 13
064 erJ61 TER.sh 4p_casasc_dh clm_std^nl_urb 20021230:NONE:1800 1.9x2.5 gx1v6 10+38 cold ........FAIL! rc= 13
> grep PASS td.795346.status | grep TER
002 erA74 TER.sh _nrsc_ds clm_std^nl_urb 20030101:NONE:1800 1x1_brazil navy -5+-5 arb_ic ........PASS
019 erJ74 TER.sh 4p_nrcasasc_ds clm_std^nl_urb 10001230:NONE:3600 1x1_tropicAtl test -10+-10 arb_ic PASS
029 erAK8 TER.sh _sc_ds clm_std^nl_ptsmode_ocn 20030101:NONE:1800 1.9x2.5 gx1v6 -5+-5 cold ......PASS
042 erK74 TER.sh 17p_cndvsc_s clm_std 19971231:NONE:1800 1x1_brazil navy -334+-336 arb_ic .......PASS
046 erV63 TER.sh _mec10sc_do clm_glcmec 19980115:NONE:1800 1.9x2.5 gx1v6 10+38 arb_ic ...........PASS
050 erHQ4 TER.sh _nrcnsc_ds clm_drydep 20000214:NONE:1800 1x1_brazil navy@2000 -3+-7 cold .......PASS

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2010-09-09 15:10:07 -0600**

I tried adding the "-lastmonth" option to the build_streams call in datm.cpl7.template and it now works correctly. The template change is as follows...

***************
*** 992,998 ****

  EOF

! set bs0opts = "$bsopts -b $year_start -e $year_end -lastmonth"

  cat >> $CASEBUILD/datm.buildnml.csh << EOF
  cat >! $STREAM1TXT << EOF1
--- 992,998 ----

  EOF

! set bs0opts = "$bsopts -b $year_start -e $year_end "

  cat >> $CASEBUILD/datm.buildnml.csh << EOF
  cat >! $STREAM1TXT << EOF1

(To test running over a single year, I also had to set the year_start=year_end=2).

**Comment by ekluzek** [comment]
I think this is still an issue. And it looks like datm streams isn't using -lastmonth either, which might be a problem as well.

**Comment by billsacks** [comment]
From looking at the Restart routine in WaterStateType, it looks like this issue may now be fixed.
