### ISSUE TITLE
Possible bugs in CNFireLi2016Mod.F90

### ISSUE THREAD

**Issue by olyson** [ESCOMP/ctsm#780]
The following possible bug(s) were reported by Fanwei Zeng.  I won't have time until after next week to investigate this, but in the interest of getting this out there so that someone else could possibly take a look at it, I'm filing an issue.  Below is verbatim from Fanwei: 

![image](https://user-images.githubusercontent.com/18671367/62395485-a0f3d180-b52d-11e9-9409-a11f915ac5ef.png)

**Comment by lifang0209** [comment]
Hi Fanwei,

   (1) Thanks for pointing out the bug. You are correct.  cos(3*min(60._r8,abs(grc%latdeg(g)))) should be changed to cos(pi/180._r8*3*min(60._r8,abs(grc%latdeg(g)))) in CNFireLi2016Mod.F90. 
   (2) In PM1997, it's cloud/cloud-ground=4.16+2.16cos(3lat), so we could derive that cloud-groud/total=1/(5.16+2.16cos(3lat)). forc_lnfm in CLM is the total lightning. Therefore, the default code is correct. It's not a bug in CLM or typo in Li12. 

Best,
Fang

**Comment by fwzeng** [comment]
Hi Fang,

Thanks for the reply! We have fixed the bug, and will keep the code about lightning fraction as it is. Thanks for the explanation!

Best,
Fanwei

**Comment by olyson** [comment]
I have a simulation in the queue to assess the impact of this.

**Comment by olyson** [comment]
Here are diagnostics from a run branched from a historical control at year 1989:

http://webext.cgd.ucar.edu/I20TR/clm50_cesm20R_2deg_GSWP3V1_issue780_hist/lnd/clm50_cesm20R_2deg_GSWP3V1_issue780_hist.1995_2014-clm50_cesm20R_2deg_GSWP3V1_hist.1995_2014/setsIndex.html

The differences look small to me.

**Comment by fwzeng** [comment]
Thanks Keith for assessing the impact! It's great to hear that the impact is small.

**Comment by dlawrenncar** [comment]
Hey Keith,

It looks like the timeseries mostly didn't run (Set 6 and only the
differences are shown in Set 1).  If possible, I'd like to be able to see
the full timeseries.  I did notice that the carbon emissions are different
by order 1PgC/yr in some years, which isn't 0, but I would like to assess
how big this impact is relative to the mean.  I could resort to looking at
other diagnostics sets if the issue with these timeseries is something
specific to this run.  So, only redo if easy or if it is indication of
something more generally going wrong with diagnostics package.

Dave

**Comment by olyson** [comment]
I see what's wrong, rerunning now.

**Comment by olyson** [comment]
Ok, they are up now.

**Comment by ekluzek** [comment]
@olyson do you have a branch with the bug fix on it? Or did you do it as SourceMods? In either case, let me know so I can get a branch in place to come to master.

**Comment by wwieder** [comment]
Not huge differences, but I wonder what would happen to initial C states during spinup / initialization? For example, at high latitudes increases in fire with the bug causes declines in CWD pools and litter pools that should cascade down to soil C pools. Hard to tell from these simulations if it's a large magnitude effect?

**Comment by olyson** [comment]
/glade/work/oleson/release-cesm2.0.0/cime/scripts/clm50_cesm20R_2deg_GSWP3V1_issue780_hist/SourceMods/src.clm/CNFireLi2016Mod.F90

**Comment by ekluzek** [comment]
OK the change is on the release branch and it converts from latdeg to radians as follows...

``` fortran
diff -r /glade/work/oleson/release-cesm2.0.0/components/clm/src/biogeochem/CNFireLi2016Mod.F90 ./CNFireLi2016Mod.F90
608c608,611
<               ig       = (lh+this%forc_lnfm(g)/(5.16_r8+2.16_r8*cos(3*min(60._r8,abs(grc%latdeg(g)))))*0.22_r8)  &
---
> !KO              ig       = (lh+this%forc_lnfm(g)/(5.16_r8+2.16_r8*cos(3*min(60._r8,abs(grc%latdeg(g)))))*0.22_r8)  &
> !KO                         *(1._r8-fs)*(1._r8-cropf_col(c))
> !KO
>               ig       = (lh+this%forc_lnfm(g)/(5.16_r8+2.16_r8*cos(SHR_CONST_PI/180._r8*3*min(60._r8,abs(grc%latdeg(g)))))*0.22_r8)  &
609a613
> !KO
```

We should probably either use "cosd" or use the latitude that's already in radians (lat rather than latdeg) rather than do the conversion each time. Note, the CNFireLi2014Mod.F90 has the same line and has it correct by using lat() in place of latdeg().

**Comment by ekluzek** [comment]
I also checked other uses of 'sin(' and 'cos(' in the code to make sure the radians version is being used and it is. It either for example uses an angle that's already in radians, or does the conversion. So you never see a use of "sind(' or "cosd(". Looks like there is both a constant called rpi as well as SHR_CONST_PI (although rpi is set to SHR_CONST_PI, so they are equivalent).
