### ISSUE TITLE
cheyenne machine change is causing FUNITCTSM tests to fail for me

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#790]
### Brief summary of bug

I didn't use to have this problem, but have recently. The FUNITCTSM tests aren't working for me
now. But, note they work for @billsacks. I've also tried it with recent versions ctsm1.0.dev055, as well as older versions ctsm1.0.dev042 and get the same problem. Since, it's occurring in both I'm thinking this is a machine or environment change that is causing this since my testing for ctsm1.0.dev048 worked.

### General bug information

**CTSM version you are using:** ctsm1.0.dev055 and ctsm1.0.dev042
**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** FUNITCTSM tests

### Details of bug

I see this when running the test

FUNITCTSM_P1x1.f10_f10_musgs.I2000Clm50SpGs.cheyenne_intel

When I run the unit test by hand under src, it runs successfully (making sure I delete the the temp directory beforehand).

### Important details of your setup / configuration so we can reproduce the bug

I tried playing around with my environment a bit, but it still seems to fail. The latest module environment is as follows...

> Currently Loaded Modules:
>   1) nco/4.7.9   2) ncview/2.1.7   3) ncarenv/1.3   4) intel/18.0.5   5) mpt/2.19   6) ncarcompilers/0.5.0   7) netcdf/4.6.3   8) ncl/6.6.2   9) python/3.6.8

I've tried with and without loading python as well as loading cmake. And I'm using tcsh.

The default cmake version is

> scripts/FUNITCTSM_P1x1.f10_f10_musgs.I2000Clm50SpGs.cheyenne_intel.20190821_164742_0jtmw5> which cmake
> /usr/bin/cmake
> scripts/FUNITCTSM_P1x1.f10_f10_musgs.I2000Clm50SpGs.cheyenne_intel.20190821_164742_0jtmw5> cmake --version
> cmake version 3.5.2
> 

$PATH is /glade/u/apps/ch/opt/lmod/8.1.7/bin:/ncar/opt/slurm/latest//bin:/opt/clmgr/sbin:/opt/clmgr/bin:/opt/sgi/sbin:/opt/sgi/bin:/glade/u/apps/ch/opt/ncl/6.6.2/intel/18.0.5/bin:/glade/u/apps/ch/opt/netcdf/4.6.3/intel/18.0.5/bin:/glade/u/apps/ch/opt/ncarcompilers/0.5.0/intel/18.0.5:/glade/u/apps/ch/opt/ncarcompilers/0.5.0/intel/18.0.5/mpi:/glade/u/apps/ch/opt/mpt/2.19/bin:/glade/u/apps/opt/intel/2018u4/vtune_amplifier/bin64:/glade/u/apps/opt/intel/2018u4/inspector/bin64:/glade/u/apps/opt/intel/2018u4/advisor/bin64:/glade/u/apps/opt/intel/2018u4/compilers_and_libraries/linux/bin/intel64:/glade/u/apps/ch/opt/usr/bin:/glade/u/apps/ch/opt/ncview/2.1.7/gnu/8.3.0/bin:/glade/u/apps/ch/opt/nco/4.7.9/gnu/8.3.0/bin:/glade/u/apps/ch/opt/lmod/8.1.7/bin:/glade/u/home/erik/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin/X11:/usr/games:/opt/ibutils/bin:/usr/lib/mit/bin:/glade/u/apps/opt/hpss/hpss-client.5.0.2.p5/bin:/glade/u/apps/ch/os/usr/bin:/opt/pbs/bin:/sbin:/bin:/glade/p/cesmdata/cseg/tools/cprnc:/glade/u/home/erik/bin:/glade/p/cesmdata/cseg/tools/svn_scripts

### Important output or errors that show the problem

Here's the error it reports...

>  ---------------------------------------------------
> 2019-08-21 16:48:02: Compiler is intel
> Using PFUNIT_PATH: $ENV{CESMDATAROOT}/tools/pFUnit/pFUnit3.2.8_cheyenne_Intel17.0.1_noMPI_noOpenMP
> Setting resource.RLIMIT_STACK to -1 from (-1, -1)
> Setting resource.RLIMIT_STACK to -1 from (-1, -1)
> ==================================================
> Running cmake for __command_line_test__/__command_line_test__.
> ==================================================
> ERROR: Command: 'cmake -C Macros.cmake /glade/scratch/erik/ctsm1.0.dev042/src -DCIMEROOT=/glade/scratch/erik/ctsm1.0.dev042/cime/scripts/fortran_unit_testing/../.. -DCIME_CMAKE_MODULE_DIRECTORY=/glade/scratch/erik/ctsm1.0.dev042/cime/src/CMake -DCMAKE_BUILD_TYPE=CESM_DEBUG -DPFUNIT_MPIRUN='' -DPFUNIT_PATH=$ENV{CESMDATAROOT}/tools/pFUnit/pFUnit3.2.8_cheyenne_Intel17.0.1_noMPI_noOpenMP -DUSE_MPI_SERIAL=ON -DENABLE_GENF90=ON -DCMAKE_PROGRAM_PATH=/glade/scratch/erik/ctsm1.0.dev042/cime/scripts/fortran_unit_testing/../../src/externals/genf90' failed with error 'CMake Error: Could not find CMAKE_ROOT !!!
> CMake has most likely not been installed correctly.
> Modules directory not found in
> /glade/u/apps/ch/os/usr/share/cmake
> CMake Error: Error executing cmake::LoadCache(). Aborting.' from dir '/glade/scratch/erik/FUNITCTSM_P1x1.f10_f10_musgs.I2000Clm50SpGs.cheyenne_intel.20190821_164742_0jtmw5/bld/__command_line_test__/__command_line_test__'
> 
>  ---------------------------------------------------
> 2019-08-21 16:48:02: ERROR: RUN FAIL for FUNIT
>  ---------------------------------------------------
>

**Comment by billsacks** [comment]
Some initial thoughts:

I wonder if this is a tcsh vs. bash thing (I use bash)?

Some differences between running it by hand and running it via the FUNITCTSM test are: (a) when running it by hand, you are (presumably?) running it on the login node, whereas the FUNITCTSM test runs it on a batch node; (b) when running it by hand, it may use your currently-loaded environment, modules, etc. (though I'm not sure about that), whereas the FUNITCTSM test uses the  same environment and modules that are used in system tests in general (set by config_machines.xml).

To address point (a): Could you try running it by hand from a batch node (e.g., via qinteractive)?

To address point (b): Could you try sourcing .env_mach_specific.csh in the case, then running it by hand?

Actually, maybe before all of this, the first thing to try may be adding a module load in config_machines.xml. I see that, for many other machines, config_machines.xml has a module load for cmake, but I don't see that being done for cheyenne. I'd try adding a module load for cmake in config_machines.xml for cheyenne, then try recreating a FUNITCTSM test with this.

**Comment by ekluzek** [comment]
I moved my .cshrc and .tcshrc file away and the test works for me now. So there's something in there that's disabling this...

**Comment by billsacks** [comment]
Closing this since it seems specific to @ekluzek 's environment.
