### ISSUE TITLE
gnu tests fail to run cprnc, so some tests fail...

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#798]
### Brief summary of bug

Tests with gnu on cheyenne can't run cprnc (since it's setup with intel compiler) as it can't fine the path to a dynamic library. As a result some tests fail.

### General bug information

**CTSM version you are using:**ctsm1.0.dev061
**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** Tests that do compare with gnu
Only one test is actually failing for me, but the others aren't able to run cprnc either. So they actually should fail.

The test I see that fails is

ERP_P36x2_D_Ld5.f10_f10_musgs.I2000Clm50Cn.cheyenne_gnu.clm-default

And it does so because it can't run cprnc. Other tests appear to work fine, but can't run cprnc either. So they actually should fail.

### Details of bug

The gnu module environment doesn't seem able to run cprnc (presumably because it's compiled with the intel compiler). There is a dynamic library that needs to be loaded on runtime, and since the gnu environment doesn't include that library, cprnc will fail. Strangely only one of the tests picks up this as a problem.

### Important details of your setup / configuration so we can reproduce the bug

I see this problem on cheyenne with gnu, but looked for cprnc files on hobart and didn't 
see any in my testing, which is also a problem.

### Important output or errors that show the problem

Here's the error message..
> 
/glade/p/cesmdata/cseg/tools/cime/tools/cprnc/cprnc.cheyenne: error while loading shared libraries: libiomp5.so: cannot open shared object file: No such file or directory

**Comment by ekluzek** [comment]
The cime issue I've created for this is here: https://github.com/ESMCI/cime/issues/3224

**Comment by jedwards4b** [comment]
If you build cprnc using the gnu compiler it will work with the intel and pgi environments as well as the gnu environment. cprnc was reinstalled on cheyenne.
