### ISSUE TITLE
Remove / change failing prealpha / prebeta tests on izumi

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#800]
With the move of our testing from hobart to izumi, the following three tests in the prealpha / prebeta test lists are failing:

- ERP_D_Ld5.ne30_g16.I1850Clm50BgcCrop.izumi_nag.clm-default - maybe connected with #174. @ekluzek has removed this test on the release branch, so we just need to make sure that that removal makes it to master

- ERP_Ld5.f19_g17.I2000Clm50SpRtmFl.izumi_pgi.clm-default and SMS_D_Ld1.f19_g17.I1850Clm45Cn.izumi_pgi.clm-default - I get messages like `i011.unified.ucar.edu.44619hfi_userinit: mmap of status page (dabbad0008040000) failed: Operation not permitted`. These seem to work if I change the PE layout to use one node rather than two, so it seems to me like there's a problem with running multiple nodes with pgi on izumi. These tests should be changed or removed. Note that we do _not_ have equivalent tests in the `aux_clm` test list; my feeling is that our prealpha and prebeta test lists should only contain tests that have equivalents in `aux_clm`, so that @fischer-ncar isn't the first to uncover problems.

@ekluzek can you take a stab at tweaking the above tests? Note that this is connected with #276 .

**Comment by billsacks** [comment]
@ekluzek - I see that you resolved #276 - thanks! I'm wondering if you also resolved this related issue at the same time, or if this one is still open?

**Comment by ekluzek** [comment]
Both of these were resolved with ctsm1.0.dev093. The I2000Clm50SpRtmFl case is running on izumi, and the ne30 test with ERP_D_Ld5.ne30_g16.I1850Clm50BgcCrop.izumi_nag.clm-default was removed.
