### ISSUE TITLE
Assumption that building width (Wb) equals street width can be relaxed and Wb can be derived from morphology

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#803]
### Brief summary of bug

There is an implicit assumption in the urban building energy model that building width equals street width.  However, this assumption can/should be relaxed and building width can be derived from the morphology dataset.

### General bug information

**CTSM version you are using:** release-clm

**Does this bug cause significantly incorrect results in the model's science?** Yes for urban (greater than roundoff), No for general climate simulations (same gridcell/regional/global climate).

**Configurations affected:** All configurations with urban landunits

### Details of bug

There is an implicit assumption in the urban building energy model that building width equals street width.  However, this assumption can be relaxed and building width can be derived from the Jackson morphology dataset.  Specifically, the equations which use H/Ws (building height over street width) should use H/Wb (building height over building width).  Building width can be derived from (Ws*froof)/(1-froof), where froof is the roof (building) fraction.
A simulation with the new equations indicate that as expected, for froof=0.5, answers are identical (because H/Ws = H/Wb).  Differences in other cases depend on the degree of departure from froof=0.5 and the presence and magnitude of space heating and air conditioning.  A full assessment of differences by variable, season, density type, and region using ctsm1.0.dev098 can be found in the attached file.  This uses the default CLM5 urban datasets.

[CTSM98_BUILDENERGY_Analysis_Pub.xlsx](https://github.com/ESCOMP/CTSM/files/4820477/CTSM98_BUILDENERGY_Analysis_Pub.xlsx)

A similar assessment using release-cesm2.0.1 but with the optional new urban datasets (Oleson and Feddema 2019) can be found in this attached file:

[CLM50_BUILDENERGY_Analysis_Pub.xlsx](https://github.com/ESCOMP/CTSM/files/4820475/CLM50_BUILDENERGY_Analysis_Pub.xlsx)

I have SourceMods for this currently, but can put together a branch.  It would be nice to get this into the release branch, in particular for the CESM2 large ensemble runs, since it's not going to affect climate and would make the urban output more useful.  Along with the new urban properties data (see [PR#591](https://github.com/ESCOMP/ctsm/pull/591)).

**Comment by olyson** [comment]
I created a branch for the code changes:

https://github.com/olyson/ctsm/tree/fixbuildenergy

**Comment by ekluzek** [comment]
@olyson I looked at your branch, the changes are pretty small and straightforward. And my understanding is that they won't change answers for the current datasets? They just allow different behavior for the future? Is that right?

Do you want to turn the branch into a PR, and we can start moving it to master?

**Comment by olyson** [comment]
No, they will change answers for the current datasets.  The code changes could come to master either by themselves or as part of PR #591 (the change to nlevurb=10, the updated surface dataset, and the updated urbantv file).  It would be nice to have the code changes on master sooner rather than later.  So I will turn the branch into a PR if that is ok.

**Comment by ekluzek** [comment]
@olyson it looks like PR #591 changes answers, so it would be good to have this separated from that with the bit-for-bit part of it as a separate tag. If there's other bit-for-bit parts of #591, we could lift them out into bit-for-bit PR's as well.

**Comment by olyson** [comment]
There actually aren't any bit-for-bit parts of #591.  And this branch with the code changes isn't bit-for-bit either, it's a bug fix.

**Comment by ekluzek** [comment]
Ahh, OK. Thanks for that clarification. As I read #591 I see it as mostly a new feature for CTSM5_1. The new datasets would be triggered with CTSM5_1, but the old used with CLM5_0. It's good to keep things that are a bug fix that change other versions (like clm4_5, and clm5_0) outside of the new feature for a new version. Does that sound right to you? I may need to discuss this with your more to figure this out...

If this changes answers as a bug fix, do we know that the changes are reasonably small?

**Comment by olyson** [comment]
Let's talk at your convenience (I know you are busy with the release and other things this week).

**Comment by olyson** [comment]
The answer changes due to the bug fix are very small, nothing statistically significant.  So it seems like the bug fix itself could go onto master.

http://webext.cgd.ucar.edu/I2000/clm50_ctsm10d098_1deg_GSWP3V1_CON_FIXBUILDENERGY_2000/lnd/clm50_ctsm10d098_1deg_GSWP3V1_CON_FIXBUILDENERGY_2000.1991_2010-clm50_ctsm10d098_1deg_GSWP3V1_CON_2000.1991_2010/setsIndex.html
