### ISSUE TITLE
Soil hydrologic properties for soil organic matter in code are not consistent with tech note

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#813]
The CLM5 tech note describes the following hydrologic properties for soil organic matter as:

om_watsat = 0.9
om_b = 2.7
om_sucsat = 10.3
om_hksat = ??

The code has:

                om_watsat         = max(0.93_r8 - 0.1_r8   *(zsoi(lev)/zsapric), 0.83_r8)
                om_b                 = min(2.7_r8  + 9.3_r8   *(zsoi(lev)/zsapric), 12.0_r8)
                om_sucsat          = min(10.3_r8 - 0.2_r8   *(zsoi(lev)/zsapric), 10.1_r8)
                om_hksat           = max(0.28_r8 - 0.2799_r8*(zsoi(lev)/zsapric), xksat)

I'm assuming the code is right, but can someone confirm this?  Is there a reference associated with the equations in the code?

**Comment by dlawrenncar** [comment]
I don't think there is a reference for this.  We added this feature to
implicitly account for the standard observed profile of organic matter
properties after the original paper was published.  Looks like the Tech
Note was never updated to account for this change.

**Comment by olyson** [comment]
I've updated the tech note for this, so I'm closing this issue.
