### ISSUE TITLE
Have clm4_5 use the same ndep file for 1850 as clm5_0

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#817]
For 1850, clm5_0 is using:

fndep_clm_WACCM6_CMIP6piControl001_y21-50avg_1850monthly_0.95x1.25_c180802.nc

which is from the PI-control.

While clm4_5 is using the 1850 from the historical period...

fndep_clm_hist_b.e21.BWHIST.f09_g17.CMIP6-historical-WACCM.ensmean_1849-2015_monthly_0.9x1.25_c180926.nc

1849 and 1850 are supposed to be and also the same as the PI-control case. And I've verified this is the case.

But, I do see a difference in answers when I run with one versus the other. It does look like it gets the right times from the file in both cases. So I don't have an explanation for the difference. It might just be a small rounding difference that happens in the temporal or spatial interpolation. If so it probably doesn't matter.

**Comment by billsacks** [comment]
From Dave Lawrence: clm45 should be changed to use the same thing as clm50.
