### ISSUE TITLE
SpinupStability.ncl assumes a lat/long grid doesn't work on unstructured grids

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#819]
### Brief summary of bug

Adam Harrington noticed that the script SpinupStability.ncl assumes a 2D lat/lon grid, so can't be used for an unstructured grid as it is.

### General bug information

**CTSM version you are using:** release-clm5.027

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** Won't work for any of the SE grids (ne16np4, ne30np4, etc.)

**Comment by ekluzek** [comment]
@adamrher

**Comment by olyson** [comment]
I've added a note in the script and CLM50_data_tools README that the script is only intended for use with 2-D lat/long grids, so I'm closing this bug report.
/glade/p/cgd/tss/CLM50_data_tools
I'll file another issue regarding the need for a script that works for SE grids.
