### ISSUE TITLE
dqgdT incorrect when there is no snow

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#824]
### Brief summary of bug

The calculation of dqgdT, which gives the derivative, d(qg)/dT, is incorrect for soil/crop landunits when there is no snow.

### General bug information

**CTSM version you are using:** ctsm1.0.dev072. I believe this bug has been present ever since the start of clm45.

**Does this bug cause significantly incorrect results in the model's science?** Yes

**Configurations affected:** All

### Details of bug

Here is the relevant code:

https://github.com/ESCOMP/CTSM/blob/daf1459fea6c3191f4218242c98a5ebf7bebe846/src/biogeophys/SurfaceHumidityMod.F90#L196-L203

In the snl(c) >= 0 conditional, it looks like what was meant was:

```Fortran
               dqgdT(c) = (1._r8 - frac_h2osfc(c))*hr*qsatgdT
```

In the case where frac_sno(c) == 0, the original code results in a double-multiplication by (1._r8 - frac_h2osfc(c)) and a double-multiplication by hr, so dqgdT ends up closer to 0 than it should be (since both of the double-multiplied terms should be fractions less than 1). This new code does what I think is intended: If there is no explicit snow pack, then it calculates dqgdT to be what it would be if frac_sno(c) were 0.

@swensosc agreed that this is a bug, and agreed with my intended fix.

I checked the impact from one-day averages in test `SMS_D_Ld1_P4x1.f10_f10_musgs.I2000Clm50BgcCropQianRsGs.bishorn_gnu.clm-default`, by looking at differences in `EFLX_LH_TOT`. The impact is small: daily-average differences in that variable are typically 0.01 W m-2 or less; most grid cells have significantly less difference than that; only one or a few f10 grid cells have significantly greater differences, with the biggest difference being about 0.1 W m-2.

**Comment by billsacks** [comment]
@olyson @dlawrenncar I wanted to call your attention to this bug that impacts science. I'll fix this bug in my next tag. The good news is that the impact seems to be small, though this may warrant further investigation (I just did a one-day run at coarse resolution).

**Comment by dlawrenncar** [comment]
Perhaps it is close to time to do another evaluation of the science in the
master branch with a few recent bugs having been fixed.  Could potentially
wait until after the optimized reflectance parameters branch has been
brought to master.
