### ISSUE TITLE
Assumed time offset of zero for soil moisture streams is not correct

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#830]
### Brief summary of bug

The soil moisture streams functionality brought in release-clm5.0.27 assumes the time offset is zero. But, the time-stamps for the monthly averages on the file are from the last time-step in the month. Hence we need set the offset to be about a half month. Since, time is in days, we can only use an offset for a particular number of days. So I think it should be 15 days to make it roughly average out. If we accept the offset as a real we could set it to 15.2083333 which would average out a little better.

The other way to handle it would be to postprocess the dataset and move the time-stamps to mid month.

### General bug information

**CTSM version you are using:** release-clm5.0.27-45-g6173fe4f

This is on my branch relfixesfor5028
**Does this bug cause significantly incorrect results in the model's science?** Yes

**Configurations affected:** Only when soil-moisture streams are turned on 

use_soil_moisture_streams = T

### Details of bug

Documentation on this is in this cime issue...

https://github.com/ESMCI/cime/issues/3281

I originally thought it was an issue with cime 3D streams.

### Important details of your setup / configuration so we can reproduce the bug

Here's a sample test case...

SMS_P720x1_D_Ld3.f09_g17.I2000Clm50SpGs.cheyenne_intel.clm-prescribed

Then I experiment with soilm_tintalgo.

### Important output or errors that show the problem

In using the different soilm_tintalgo options (lower, upper, nearest) I compare the results of the input file for H2OSOI:

/glade/p/cesmdata/cseg/inputdata/lnd/clm2/prescribed_data/LFMIP-pdLC-SST.H2OSOI.0.9x1.25.20levsoi.natveg.climo1980-2014.MONS_c190709.nc

to the output history files for fields: H2OSOIL_VOL_PRESCRIBED and H2OSOIL_VOL_PRESCRIBED_GRC.

**Comment by olyson** [comment]
I feel like we've had this discussion before about this file not being the right one, it might have been the one Sean used in his early testing.  The file I created (and used for the actual experiments) is:

/glade/p/cgd/tss/people/oleson/CLM5_h2osoi/LFMIP-pdLC-SST.H2OSOI.natveg.1980-2014.MONS_climo.nc

It's time units are days since 1997-01-01 00:00:00 and the values are mid-month:

time = 15.5, 45, 74.5, 105, 135.5, 166, 196.5, 227.5, 258, 288.5, 319, 349.5

**Comment by ekluzek** [comment]
@olyson thanks for pointing that out. I'l switch my testing to using it. And I'll copy it into inputdata. The other thing here is that I'll make offset a namelist parameter so that you can set it depending on what your file is.

**Comment by ekluzek** [comment]
Offset being sent to streams is integer number of seconds. So for monthly files like the one being used the offset should be -1314000.

**Comment by ekluzek** [comment]
Fixed in release-clm5.028
