### ISSUE TITLE
PEM_Ld1.f10_f10_musgs.I2000Clm50BgcCrop.hobart_intel failing in release-clm5.0.28

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#840]
### Brief summary of bug

PEM_Ld1.f10_f10_musgs.I2000Clm50BgcCrop.hobart_intel fails on hobart, but runs in izumi.

### General bug information

**CTSM version you are using:** release-clm5.0.27

**Does this bug cause significantly incorrect results in the model's science?** N
**Configurations affected:** Just PEM_Ld1.f10_f10_musgs.I2000Clm50BgcCrop.hobart_intel

### Details of bug

On hobart it works with 48, but the case with 24 fails. The izumi case works when using 96 processors and then 48 for the second case. And then on izumi this case with 48 PE's and then 24 PE's works.

### Important details of your setup / configuration so we can reproduce the bug

Looks like this has been failing on the release branch, but I haven't seen it before now. The directory for it doesn't exist in previous release-clm5.0 baselines.

### Important output or errors that show the problem

Fails in the initialization of cism with the following. in the second case (running on 24 tasks)

``` text
 Done in glissade_initialise
  
 Compute ice velocities, time =  0.000000000000000E+000

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 167275 RUNNING AT h032.cgd.ucar.edu
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```

**Comment by billsacks** [comment]
After the recent izumi machine update, this test is failing on izumi, here:

```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
cesm.exe           000000000152273A  Unknown               Unknown  Unknown
libpthread-2.17.s  00007F76297F85F0  Unknown               Unknown  Unknown
cesm.exe           0000000000F0CD5A  glissade_velo_hig         997  glissade_velo_higher.F90
cesm.exe           0000000000F0B504  glissade_velo_mp_          95  glissade_velo.F90
cesm.exe           0000000000E45F63  glissade_mp_gliss        2548  glissade.F90
cesm.exe           000000000110338B  glad_initialise_m         149  glad_initialise.F90
cesm.exe           0000000000E2F92F  glad_main_mp_glad         286  glad_main.F90
cesm.exe           0000000000DB9C48  glc_initmod_mp_gl         305  glc_InitMod.F90
cesm.exe           0000000000DA1F5A  glc_comp_mct_mp_g         188  glc_comp_mct.F90
cesm.exe           000000000043B8A4  component_mod_mp_         257  component_mod.F90
cesm.exe           000000000042A0EC  cime_comp_mod_mp_        1374  cime_comp_mod.F90
cesm.exe           00000000004387E9  MAIN__                    122  cime_driver.F90
cesm.exe           0000000000418662  Unknown               Unknown  Unknown
libc-2.17.so       00007F762943D505  __libc_start_main     Unknown  Unknown
cesm.exe           0000000000418569  Unknown               Unknown  Unknown
```

At first I was going to simply remove it, but it seems like there is some value in having a couple of PEM tests in the test suite (this is one of only two PEM tests). So I'm going to change it to use SGLC (`PEM_Ld1.f10_f10_musgs.I2000Clm50BgcCropGs.izumi_intel.clm-crop`).
