### ISSUE TITLE
Rework mksurfdata_map unit_testers and get them passing

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#842]
We have unit tests for mksurfdata_map in two places: 

(1) tools/mksurfdata_map/unit_testers

(2) tools/mksurfdata_map/src/test

The history is that we first just had (1). Then, when we adopted pFUnit-based unit testing for source code, we began to write new tests leveraging pFUnit in (2), because this is what we want long-term, but we didn't rewrite the old tests at that time.

The tests in (1) should be rewritten to fit with (2), and moved to that location - or some tests can be deleted if they are no longer important to keep around, and it's not worth the time to migrate them to the new unit test system.

I noticed that some of the tests in (1) expect input netcdf files that seem to have been deleted, probably with the migration from svn to git. Also, I expect some of the tests will fail due to the changes in #823 - so, some tests will either need to be modified to accommodate those changes (e.g., to mkgridmapMod and mkindexmapMod, and maybe others) or deleted. And ideally some new tests would be added to test the new behavior of #823 - i.e., ensuring that masked-out source points are excluded from the mapping - if such tests aren't added as part of #823 .

**Comment by billsacks** [comment]
@slevisconsulting - FYI, I noticed this in reviewing #823 , but I don't think this needs to be addressed now.

**Comment by ekluzek** [comment]
This doesn't need to be done in mksurfdata_map. But, we should access if unit tests would be helpful to add to the new mksurfdata_esmf code in #1663.

**Comment by ekluzek** [comment]
I'm going to close this since mksurfdata_map is being removed with mksurfdata_esmf. We'll open an issue for mksurfdata_esmf if we decide to add unit testing there.
