### ISSUE TITLE
Segmentation Fault occur while running  ISSP245Clm50BgcCrop case with CLM5.0.25

### ISSUE THREAD

**Issue by qhgogogo** [ESCOMP/CTSM#848]
I met a problem while I am running the case with compset: ISSP245Clm50BgcCrop.

I  created the case by tryping:  ./create_newcase -case globalBGC5_ssp245 -compset ISSP245Clm50BgcCrop -res f09_g16 -mac constance --run-unsupported 

The case could be successfully set-up and built. All the necessary input files could also be downloaded.

However, the job couldn’t go smoothly,  ‘segmentation fault’ occurs while the job was running.

It seems like the error occurs during interpolating the initial conditions. I attach the log files as ‘logs.zip’.
[logs.zip](https://github.com/ESCOMP/CTSM/files/3919830/logs.zip)

I appreciate your help!

### NOTE: Be sure to read the relevant documentation and user forums

We have limited staff and ability to provide support. Here are some resources that might provide help:
- User's Guide: https://escomp.github.io/ctsm-docs/doc/build/html/users_guide/index.html
- CLM Forum: https://bb.cgd.ucar.edu/forums/land-modeling-clm
- README files amongst the source code
- GitHub CTSM issues: https://github.com/escomp/ctsm/issues/
- Also make sure this issue is unique to CTSM and not really an issue with CESM or CIME

### Details of support request

[Fill in details here.]

### Important details of your setup / configuration so we can better assist you

**CTSM version you are using:** [output of `git describe`]

**Have you made any modifications to code, xml files, etc.?** [Yes / No]

[If Yes: Please point us to your modifications. However: In general we can NOT support problems with modified code. Try to show the problem without modifications.]

**If you are having problems with a specific case: Is your case on a machine accessible to most CTSM developers (e.g., an NCAR machine)?** [Yes / No]

If Yes:

- Location of case directory: [Fill this in]

- Location of run directory: [Fill this in]

[If No: Please make sure you have included all important input and output needed to understand your issue, either by pasting it into the issue text, or by attaching relevant files. However: We are less likely to be able to reproduce your problem if the issue is NOT on an NCAR machine.]

**Comment by billsacks** [comment]
This may be due to running out of memory. If your machine has more processors available, I recommend trying to increase the processor count – for example, doubling or quadrupling it – via `./xmlchange NTASKS=192`.

**Comment by qhgogogo** [comment]
> This may be due to running out of memory. If your machine has more processors available, I recommend trying to increase the processor count – for example, doubling or quadrupling it – via `./xmlchange NTASKS=192`.

Thank you! Bill, this really helps. However it seems like NTASKS=192 is still not enough! I will enlarge this number and try again.

**Comment by ekluzek** [comment]
The other thing I'd suggest is to try simpler cases. I'd try running a single-point case with MPILIB=mpi-serial for example. Just to see that you can get the simplest case to run. And I'd try other simple standard cases like a I1850Clm50BgcCrop compset for example.

Really the issue maybe in porting CTSM/CESM/CIME to your machine constance. So I'd look at the suggestions for porting CIME at...

http://esmci.github.io/cime/users_guide/porting-cime.html

**Comment by ekluzek** [comment]
@qhgogogo is this still a problem? Or did you get it working?

**Comment by qhgogogo** [comment]
This problem is resolved, but I got a new issue while I'm running the
accelerated spin-up case...

Thanks,

Han

**Comment by ekluzek** [comment]
OK, I'm closing this one. Sounds like this was more a issue with porting to a new machine.

Feel free to open a new issue for your new problem.

**Comment by qhgogogo** [comment]
Sure! Thank you, Erik!
