### ISSUE TITLE
Create a build system for LILAC

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#855]
We need a build system that will build LILAC, CTSM and CTSM's dependencies (cime, pio, etc.).

Depending on how it's implemented, this may involve changes in CTSM (and possibly CIME, though we'll probably try to avoid that at first).

See https://github.com/ESCOMP/CTSM/pull/834 for some initial work from @jhamman .

See also #799

**Comment by billsacks** [comment]
See ESMCI/cime#3489 for my current thinking on how I might do this. In summary, I'm thinking of continuing to leverage cime's build system, but to wrap it with a single script that hides the separate steps from the user and makes it so the user doesn't need to learn how to do a cime port of their machine.

Compared with doing this via a CMake-based build, I feel that this solution would have the following pros:
- Easier for me to implement initially
- Easier for us to maintain long-term: With a CMake-based build, we'd end up needing to maintain our own build system parallel to the official cime build system. When directory structures are rearranged, new CPP tokens are introduced, libraries are merged and split, etc., we would need to change our build system accordingly. This could lead to broken builds in the best case scenario, and incorrect builds – causing performance issues or incorrect behavior – in worse case scenarios (where we were supposed to define some new CPP token but didn't).
- About as easy or easier for users to use when things work smoothly

But its con would be:
- This would likely be harder for users to debug and solve issues when things go wrong - which could happen, for example, when very different compiler flags are needed on their system, especially when some standard flags are NOT wanted; in that case, it's more likely we'll be called on to help them. On the other hand, since it would be using the standard cime build system, it will be easier for any of the core CTSM team to help them (as opposed to requiring knowledge of CMake).

Overall, I'm feeling pretty inclined to at least try this solution for now. But I welcome any thoughts from others - e.g., @mvertens @negin513 @ekluzek @dlawrenncar @wwieder @barlage @slevisconsulting . If you're interested in giving feedback, please read through ESMCI/cime#3489 for details.

**Comment by billsacks** [comment]
We'll need a location to store xml template files that are modified and copied into place by the wrapper script. My tentative thought is to put these in a new subdirectory of `bld`: `bld/build_templates`. For now this will contain two files: a template for `config_machines.xml` and one for `config_compilers.xml`. In principle other files could be added there later, if needed.

@ekluzek or others, do you have any opinions on this?

**Comment by billsacks** [comment]
> My tentative thought is to put these in a new subdirectory of `bld`: `bld/build_templates`. For now this will contain two files: a template for `config_machines.xml` and one for `config_compilers.xml`. In principle other files could be added there later, if needed.

Actually, now I'm thinking of putting these in a lilac-specific location: Mariana introduced a `lilac_config` directory at the top level on the lilac branch, and I'm thinking of putting these in `lilac_config/build_templates`.

**Comment by ekluzek** [comment]
I think the LILAC specific place makes the most sense to me.

One question on this. Would this be something where you would run a script that would process cime files to produce ones for LILAC? So the true source is in cime, and you would only need to update them possibly if cime is updated?

This reminds me of other cases where we have processed files in the source tree (where the true source file is in some other format, and then it's processed to create files that we also keep in the repository). We used to keep the *.F90 output from *.F90.in files, but finally decided that we'd keep the true source files.  For the documentation we do something similar, where an admin will run make to create the bld files that you actually look at. But, you do need that admin to rebuild anytime the source files are changed.

I just want to see if the description above is accurate?

**Comment by billsacks** [comment]
@ekluzek I'm not sure I understand the question in your last comment, but let me try to explain, including an example:

We are effectively going to maintain a templated machine port in the CTSM repository. The maintenance of this would be similar to the maintenance of any other CIME machine port – which is to say, in principle we'll need to update it occasionally, but hopefully the CIME maintainers don't force this to happen too often, because it would cause pain for *anyone* maintaining their own CIME port.

In particular, we'll have this file in the repository, along with a small `config_compilers_template.xml` file: <https://github.com/ESCOMP/CTSM/blob/7db2458241e59c51bcd2a1def5f92b626efbcba4/lilac_config/build_templates/config_machines_template.xml>.

Perhaps in answer to your question: I wrote that file by consulting [this file](https://github.com/ESMCI/cime/blob/6d745aa6be0f26fda0117237ea4886897b342506/config/xml_schemas/config_machines_template.xml) and [this file](https://github.com/ESMCI/cime/blob/6d745aa6be0f26fda0117237ea4886897b342506/config/xml_schemas/config_machines.xsd), but I don't see that as meaning that the "true source" is in cime: it's more like I have followed the cime documentation on how to make a machine port.

We can then generate an actual `config_compilers.xml` file in python with code like this (though of course using user-specified arguments rather than hard-coding "Darwin", "gnu", etc.):

```python
with open('/Users/sacks/ctsm/ctsm3/lilac_config/build_templates/config_machines_template.xml') as f:
    contents = f.read()
config_machines_template = string.Template(contents)
config_machines = config_machines_template.substitute(OS='Darwin', COMPILER='gnu', MPILIB='mpich', CIME_OUTPUT_ROOT='/path/to/build', GMAKE='gmake', GMAKE_J=4)
with open('/Users/sacks/temporary/config_machines.xml', 'w') as f:
    f.write(config_machines)
```

which generates:

```xml
<?xml version="1.0"?>

<!-- This is a partial cime machine port which should be able to get
     through the case.build step. Trying to get further than that will
     cause problems, because various directory paths won't be set up
     properly.

     If you are looking at the template file: Variable names prefixed
     with a dollar sign will be replaced with machine-specific values. A
     double dollar sign gets replaced with a single dollar sign, so
     something like $MYVAR refers to the MYVAR cime variable.
     -->

<config_machines version="2.0">
  <machine MACH="ctsm_build">

    <!-- Text description of the machine -->
    <DESC>Temporary build information for a CTSM build</DESC>

    <!-- OS: the operating system of this machine. Passed to cppflags for
	 compiled programs as -DVALUE  recognized are LINUX, AIX, Darwin, CNL -->
    <OS>Darwin</OS>

    <!-- COMPILERS: compilers supported on this machine, comma seperated list, first is default -->
    <COMPILERS>gnu</COMPILERS>

    <!-- MPILIBS: mpilibs supported on this machine, comma seperated list,
	 first is default, mpi-serial is assumed and not required in this list-->
    <MPILIBS>mpich</MPILIBS>

    <!-- CIME_OUTPUT_ROOT: Base directory for case output,
	 the case/bld and case/run directories are written below here -->
    <CIME_OUTPUT_ROOT>/path/to/build</CIME_OUTPUT_ROOT>

    <!-- DIN_LOC_ROOT: location of the inputdata data directory
	 inputdata is downloaded automatically on a case by case basis as
	 long as the user has write access to this directory. -->
    <DIN_LOC_ROOT>$CIME_OUTPUT_ROOT/inputdata</DIN_LOC_ROOT>

    <!-- DIN_LOC_ROOT_CLMFORC: override of DIN_LOC_ROOT specific to CLM
	 forcing data -->
    <DIN_LOC_ROOT_CLMFORC>$CIME_OUTPUT_ROOT/inputdata_clmforc</DIN_LOC_ROOT_CLMFORC>

    <!-- DOUT_S_ROOT: root directory of short term archive files, short term
      archiving moves model output data out of the run directory, but
      keeps it on disk-->
    <DOUT_S_ROOT>$CIME_OUTPUT_ROOT/archive/$CASE</DOUT_S_ROOT>

    <!-- GMAKE: gnu compatible make tool, default is 'gmake' -->
    <GMAKE>gmake</GMAKE>

    <!-- GMAKE_J: optional number of threads to pass to the gmake flag -->
    <GMAKE_J>4</GMAKE_J>

    <!-- BATCH_SYSTEM: batch system used on this machine,
         supported values are: none, cobalt, lsf, pbs, slurm.

         This is irrelevant for this build-only port.
    -->
    <BATCH_SYSTEM>none</BATCH_SYSTEM>

    <!-- SUPPORTED_BY: contact information for support for this system
      this field is not used in code -->
    <SUPPORTED_BY>CTSM</SUPPORTED_BY>

    <!-- MAX_TASKS_PER_NODE: maximum number of threads*tasks per shared
         memory node on this machine, should always be >=
         MAX_MPITASKS_PER_NODE.

         This is irrelevant for this build-only port.
    -->
    <MAX_TASKS_PER_NODE>1</MAX_TASKS_PER_NODE>

    <!-- MAX_MPITASKS_PER_NODE: number of physical PES per shared node
         on this machine, in practice the MPI tasks per node will not
         exceed this value.

         This is irrelevant for this build-only port.
    -->
    <MAX_MPITASKS_PER_NODE>1</MAX_MPITASKS_PER_NODE>

    <!-- mpirun: The mpi exec to start a job on this machine, supported values
	 are values listed in MPILIBS above, default and mpi-serial.

         This is irrelevant for this build-only port.
    -->
    <mpirun mpilib="default">
      <!-- name of the exectuable used to launch mpi jobs -->
      <executable>mpirun</executable>
      <!-- arguments to the mpiexec command, the name attribute here is ignored-->
      <arguments>
        <arg name="anum_tasks"> -np $TOTALPES</arg>
        <arg name="labelstdout">-prepend-rank</arg>
      </arguments>
    </mpirun>

    <!-- module system: allowed module_system type values are:
	 module  http://www.tacc.utexas.edu/tacc-projects/mclay/lmod
	 soft http://www.mcs.anl.gov/hs/software/systems/softenv/softenv-intro.html
         none

         For this build-only port, we don't specify a module system:
         instead, we assume that the user has loaded all relevant
         modules prior to starting the build. (Similarly, we assume that
         the user has set all relevant environment variables, so don't
         specify any environment variables here.)
      -->
    <module_system type="none"/>

  </machine>
</config_machines>
```

**Comment by billsacks** [comment]
This is done on the lilac_cap branch, so I'm closing this issue.
