### ISSUE TITLE
LILAC restart are round-off level different in aerosol input fields

### ISSUE THREAD

**Issue by mvertens** [ESCOMP/CTSM#863]
With the latest code base a restart run can be done as follows:
First do a 1 day initial run - set the following in atm_driver_in:
```
  atm_start_day         = 1
  atm_stop_day          = 2
  atm_starttype         = 'startup'
```
Then do a 1 day restart run - set the following in atm_driver_in:
 ```
 atm_start_day         = 1
  atm_stop_day          = 3
  atm_starttype         = 'continue'
```
Save the results to a temporary directory.
Then do a 2 day initial run - set the following in atm_driver_in:
```



```
Compare the results with the results in the temporary directory:
The following changes were seen in the clm history files:
```
cprnc test_lilac.clm2.h0.2000-01-02-46800.nc restart/test_lilac.clm2.h0.2000-01-02-46800.nc | grep RMS
 RMS BCDEP                            6.8312E-29            NORMALIZED  1.0728E-16
 RMS DSTDEP                           4.7609E-26            NORMALIZED  4.1477E-16
 RMS OCDEP                            1.7116E-27            NORMALIZED  1.8652E-16
 RMS SNOBCMSL                         8.6584E-26            NORMALIZED  4.7752E-18
 RMS SNOOCMCL                         2.7707E-24            NORMALIZED  2.1997E-19
 RMS SNOOCMSL                         2.7868E-24            NORMALIZED  2.6882E-17
```
There were no differences in the lilac history files between the restart and the initial

**Comment by billsacks** [comment]
Good news: It appears that @mvertens fixed this issue (perhaps without realizing it?) in her commit 819a3414, which she made right after opening this issue: From the commit prior to that one (1b662f8b), I am able to reproduce this issue, but from 819a3414 (as well as from the current head of the `lilac_cap` branch, 410bf09d), I get bit-for-bit restarts following the procedure documented above.
