### ISSUE TITLE
Work out how orbital parameters will be passed through LILAC

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#865]
According to @mvertens the handling of orbital parameters in LILAC may need to be changed. We need to work out how the atmosphere should pass these orbital parameters to CTSM via LILAC – or if we just want to hard-code a certain set of orbital parameters (e.g., year-2000 parameters) when running with LILAC.

**Comment by dlawrenncar** [comment]
For first pass, I think setting orbital parameters constant at year 2000
values would be fine.  LILAC will be most useful for regional climate
models, which are unlikely to commonly be run in paleo configurations in
which orbital parameters might differ.

**Comment by billsacks** [comment]
See this:

https://github.com/ESCOMP/CTSM/blob/62b8d39a1a60964c87ca82e4849736c3bfd3f4ff/src/cpl/lilac/lnd_comp_esmf.F90#L213-L220

**Comment by billsacks** [comment]
Closing this since this seems good enough for now.
