### ISSUE TITLE
Regenerate all surface datasets

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#868]
After #823 is merged, and also after changes on the release branch are brought to master, @ekluzek will regenerate all surface datasets. We expect answer changes in most / all fields due to #823 , and in some fields due to changes on the release branch. This update will also include the urban update in #591, as well as shifting cultivation (#309). Shifting cultivation will be turned off for clm4_5/clm5_0.

**Comment by ekluzek** [comment]
We decided that we'll point to these new datasets on the main development branch even for clm4_5 and clm5_0, since the updates can be considered bug fixes. The older datasets will still be pointed to on the clm5.0 release branch.

**Comment by ekluzek** [comment]
This is from @lawrencepj1 about the current location of the new PFT rawdata files we need for this. We will likely have Peter rename them to ctsm5_1.

> There are equivalent directories for all the CLM5 raw data:
> 
> /glade/p/cesm/sdwg_dev/thesis/data/cesm_tools/surfacedata/clm52finalrawdata
> 
> globalclm52histsoilcolordeg025_190805  globalclm52SSP2RCP45deg025_190805   globalclm52SSP5RCP85xdeg025_200320
> globalclm52histCMIP5deg025_200213    globalclm52potvegLUH2deg025_190805     globalclm52SSP3RCP70deg025_190805   globalclm52SSPNOLULCC1850deg025_200409
> globalclm52histHIGHdeg025_190805     globalclm52priorLUH2deg025_190805      globalclm52SSP4RCP34deg025_190805   globalclm52SSPNOLULCC2015deg025_200409
> globalclm52histlaideg025_190805      globalclm52RCP85CMIP5deg025_200213     globalclm52SSP4RCP60deg025_190805   globalclm52trendy2019deg025_190806
> globalclm52histLOWdeg025_190805      globalclm52SSP1RCP19deg025_190805      globalclm52SSP5RCP34deg025_190805
> globalclm52histLUH2deg025_190805     globalclm52SSP1RCP26deg025_190805      globalclm52SSP5RCP34xdeg025_200320
> globalclm52histNOLULCCdeg025_200409  globalclm52SSP1RCP26xdeg025_200320     globalclm52SSP5RCP85deg025_190805
> 
> I will hold off on renaming. I have scripts to rename batches of files so let me know what you want to call them. It can be CTSM51 if that works.

**Comment by billsacks** [comment]
Feeling is that this issue isn't helpful for planning, so closing this.
