### ISSUE TITLE
Avoid requiring stop time in LILAC interface

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#877]
It seems like we shouldn't need the stop time in the LILAC interface. Can we create an ESMF clock without knowing the stop time ahead of time, and then just let the model stop whenever it stops? I think @mvertens said this should be possible; if so, we should do that to simplify the interface.

**Comment by ekluzek** [comment]
It looks to me like this can be made to work. The stop date and ymd gets set in both the MCT and NUOPC interfaces. But, it doesn't look like it really needs to be. I think you could remove the query of them at the CPL layer and thus leave them unset in clm_time_manager. It then should use 99991231 as the stop date. There is a check if run_length_specified that will die if it isn't true, 
 and that might have to be modified. But if it uses 99991231 as the stop date, it might actually work as is.

It does do a tiny bit of checking (making sure the stop date is after the start and current date. But, that should already be done at the level higher than this so shouldn't matter.

**Comment by mvertens** [comment]
I don't think this is an issue of the clock - but rather informing CLM of
when to stop. How will it know otherwise?

**Comment by billsacks** [comment]
> I don't think this is an issue of the clock - but rather informing CLM of when to stop. How will it know otherwise?

Can't it just keep running as long as it is called? Once the atm model stops, it will stop calling CTSM, and so CTSM will stop. Am I missing something?

**Comment by ekluzek** [comment]
It checks if the stop alarm is ringing on the ESMF clock that's sent into it. It doesn't actually determine it from the internal time-manager, but from the clock that's sent into it.

The one point where this comes into play is for it to close out the history and restart files.

**Comment by ekluzek** [comment]
Because of how it's handled there is a function in the internal time manager is_last_step, that could be removed. And you could remove all of the stop settings in the internal time-manager as well.

**Comment by mvertens** [comment]
ctsm needs to do a clean exit and write a restart file before it stops. I
think its a problem to do what you are suggesting.

**Comment by mvertens** [comment]
I agree with @Erik Kluzek <erik@ucar.edu> that we should be checking a stop
alarm on the clock - but to do that you need to know when you are stopping.

**Comment by billsacks** [comment]
Okay, I see why this is needed for history tape wrapup. (@mvertens I don't think it's needed for the sake of writing a restart file, because that's done via a different alarm.) Closing as a wontfix for now, though if it becomes a problem for some atmospheres we may want to revisit this.

**Comment by ekluzek** [comment]
Ahh, OK, in the LILAC case LILAC has to create the CPL clock that comes in from the driver. The way this could be gotten around is if the history and restart close happened from a call from the finalize step -- rather than during the run phase. The close could be reconfigured to happen that way, but would require some reconfiguring.

**Comment by billsacks** [comment]
A simple alternative would be to have the atmosphere pass in a logical flag saying whether this is the last time step of the run. I'm not sure if that would be easier or harder for host atmospheres to do in general, compared with telling CTSM the expected stop time up front. Again, we can revisit this later.

**Comment by mvertens** [comment]
A logical flag would be easy to implement via an attribute.

**Comment by billsacks** [comment]
It turns out that @mvertens has already put in place the appropriate hooks to have the atmosphere turn the restart and stop alarms on directly via the lilac_run interface. She agrees that we should do it that way rather than having a stop time set on the lilac clock. So I'm reopening this issue and will address it soon.

**Comment by billsacks** [comment]
I have looked through the time manager code and other CTSM code that uses it, and confirmed what @ekluzek said in his earlier comments: The stop time that is passed in to initialize the clock is never actually used. Instead, CTSM determines when it's time to stop based on the clock that is passed to it every time step. So, to avoid confusion in all modes of operation, I am going to remove all references to stop time in the time manager. At that point, it will more clearly be the case that the only thing that matters in terms of stop time is that the stop alarm is ringing at the appropriate time on the clock passed in to lnd_run.

To say this in another way, from the LILAC perspective: Even now, the stop time that is being passed to LILAC in initialization isn't actually accomplishing anything, as far as I can tell, so I'll remove it to clean things up.

**Comment by billsacks** [comment]
I have made the necessary changes in the LILAC interface on the `lilac_cap` branch.
