### ISSUE TITLE
Remove maxpft and maxpatch_pft

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#881]
We left maxpft and maxpatch_pft both in the code and in the build-namelist. It looks like to me these do nothing now, and should just be removed. It actually makes the code confusing. n_dom_pfts and the reading of what's one the surface dataset replaces the need for these.

**Comment by billsacks** [comment]
Slightly related?: #37

**Comment by negin513** [comment]
`maxpft` is also being used in `test_irrigation.pf` code as an input to `setupEnvironment`. Should I just remove this and change wherever we are using `setupEnvironment` in the test?

https://github.com/ESCOMP/CTSM/blob/d3c31a3764c26135d58797cb2e753dbd438e5e62/src/biogeophys/test/Irrigation_test/test_irrigation.pf#L264-L270

**Comment by billsacks** [comment]
It looks like maxpft is just used within that unit test module. While similar conceptually to maxpft in the main code, I think it's fine to keep maxpft in that unit test module even though you're getting rid of maxpft from the main code. Let me know if you think differently: I just took a very quick look.

**Comment by ekluzek** [comment]
I agree with @billsacks that it's not critical to remove it from a unit test. However, if this is something removed from the main code it might make the unit test harder to understand. So it would be good to remove it, if doing so is reasonably easy.

**Comment by billsacks** [comment]
In the unit test code, this is just used to allocate some variables to be big enough for what the unit test needs. I think it serves the same function as mxpft in pftconMod. I wouldn't spend time trying to change the unit test code right now unless the unit tests aren't working.

**Comment by negin513** [comment]
This has been
