### ISSUE TITLE
Warning if FUN is on, but FlexibleCN is not

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#886]
According to @wwieder , you should only be able to use `use_fun` if you are also using `use_flexibleCN`. i.e., it should be an error if `use_fun` is true but `use_flexibleCN` is not. Currently, CLMBuildNamelist allows you to set `use_fun` without `use_flexibleCN` (by modifying `user_nl_clm` in a CLM4.5 compset). I haven't checked whether this causes a runtime failure, but I don't see any runtime error check in controlMod, which is where I would expect it. We should add checks in both CLMBuildNamelist and in controlMod that prevent this combination of `use_fun = .true.` but `use_flexibleCN = .false.`.

@wwieder should we also prevent the reverse? i.e., is it okay to set `use_flexibleCN = .true.` with `use_fun = .false.`?

**Comment by ekluzek** [comment]
There is logic in FUN to handle the case of flexible-CN on or off. If use_flexibleCN==F frac_ideal_C_use is set to 1.0, otherwise it's calculated.

Is there a reason this logic is suspect? Or do we know it gives bad results?

**Comment by billsacks** [comment]
> There is logic in FUN to handle the case of flexible-CN on or off. If use_flexibleCN==F frac_ideal_C_use is set to 1.0, otherwise it's calculated.
> 
> Is there a reason this logic is suspect? Or do we know it gives bad results?

@wwieder can you comment on this?

**Comment by pengbinpeluo** [comment]
In the bld/namelist_files/namelist_defaults_ctsm.xml, we have:
 409 <carbon_resp_opt            use_flexibleCN=".true." use_fun=".false.">1</carbon_resp_opt>
 410 <carbon_resp_opt            use_flexibleCN=".true." use_fun=".true." >0</carbon_resp_opt>

Does this mean when use_flexibleCN is on, use_fun can be either turned on or off, and use_fun can be only turned on when use_flexibleCN is on?

**Comment by ekluzek** [comment]
> In the bld/namelist_files/namelist_defaults_ctsm.xml, we have:
> 409 <carbon_resp_opt use_flexibleCN=".true." use_fun=".false.">1</carbon_resp_opt>
> 410 <carbon_resp_opt use_flexibleCN=".true." use_fun=".true." >0</carbon_resp_opt>
> 
> Does this mean when use_flexibleCN is on, use_fun can be either turned on or off, and use_fun can be only turned on when use_flexibleCN is on?

That code snippet means that carbon_resp_opt is set to 1 when FUN is on, and 0, when FUN off. Since, it's a flex-CN option, it only applies when flexCN is on. So it handles both the FUN on and off case for flexCN. But, it doesn't say anything about FUN when flexCN is off.

**Comment by ekluzek** [comment]
Note, there is a testmod for FUN off with flex-CN (noFUN_flexCN). Doesn't seem to be one for flex-CN off and FUN on though.

**Comment by pengbinpeluo** [comment]
Just FYI, I had a test run and only turned use_fun on in the user_nl_clm of CLM4.5 (use_fun=.true. AND use_flexiblecn=.false. in lnd_in), and it seems that I am not coming across any issues.

**Comment by wwieder** [comment]
It seems like a nice feature to play around with toggling on/off parts of the N code like @pengbinpeluo is trying to do.  This configuration, however, hasn't really been tested- so maybe it's worth writing an error message to a log file letting users know that running with FUN & without flexCN could result in unexpected results or failures in the model.
