### ISSUE TITLE
Irrigation water withdrawal from runoff and the main channel in MOSART

### ISSUE THREAD

**Issue by felfelan** [ESCOMP/CTSM#887]
### Brief summary of bug

Hi everyone, 

It seems to me that irrigation water (qflx_irrig) is first removed from the qflx_runoff (waterflux_inst%qflx_runoff_col) at the end of HydrologyDrainageMod.F90. Later, qflx_runoff and qflx_irrig are converted to grid scale (lnd2atmMod.F90) to be sent to the MOSART. Finally, the irrigation water will be removed from the main channel in MOSART (if available) as well. If irrigation is removed from both runoff on land and the main channel in MOSART, doesn't it mean that we are withdrawing two times as much? 

### General bug information

**CTSM version you are using:** [release-clm5.0.07-112-g99dec618]

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]

**Comment by billsacks** [comment]
@felfelan thank you for taking the time to open this issue. We always appreciate when people look closely at the code and raise issues for anything that looks like it may be wrong.

In this case, I believe that the code is working correctly, though I do agree that it's somewhat confusing. `qflx_runoff_col` and the gridcell-level `qflx_rofliq_grc` are not actually sent to MOSART – instead, I'm pretty sure this is just a diagnostic quantity that is the sum of all of the other runoff terms. The terms actually sent to MOSART can be found in `src/cpl/lnd_import_export.F90`: these are the individual runoff terms, `qflx_rofliq_qsur_grc`, `qflx_rofliq_qsub_grc`, `qflx_rofliq_qgwl_grc`, `qflx_rofice_grc` and `qirrig_grc`.

I'm going to go ahead and close this issue, but please feel free to comment further if you feel there is still an issue here, or if you have any thoughts on how this could be made less confusing for yourself and others in the future.
