### ISSUE TITLE
Error while I'm running accelerate spin-up with CLM5.0 

### ISSUE THREAD

**Issue by qhgogogo** [ESCOMP/CTSM#890]
### NOTE: Be sure to read the relevant documentation and user forums

We have limited staff and ability to provide support. Here are some resources that might provide help:
- User's Guide: https://escomp.github.io/ctsm-docs/doc/build/html/users_guide/index.html
- CLM Forum: https://bb.cgd.ucar.edu/forums/land-modeling-clm
- README files amongst the source code
- GitHub CTSM issues: https://github.com/escomp/ctsm/issues/
- Also make sure this issue is unique to CTSM and not really an issue with CESM or CIME

### Details of support request
I met the following error information while I'm running the accelerated spin-up case:

In: PMI_Abort(1, Fatal error in MPI_Recv:
Message truncated, error stack:
MPI_Recv(187).....................: MPI_Recv(buf=0x38e7aa0, count=2, MPI_INTEGER, src=1, tag=33, comm=0xc4000044, status=0x38e9ea0) failed
MPIDI_CH3U_Receive_data_found(282): Message from rank 1 and tag 33 truncated; 68 bytes received but buffer size is 8

Could someone help me take a look and give some suggestions? I also attach the log file here.

Any help will be appreciated.

[cesm.log.12113138.200115-060350.txt](https://github.com/ESCOMP/CTSM/files/4067921/cesm.log.12113138.200115-060350.txt)

### Important details of your setup / configuration so we can better assist you

**CTSM version you are using:** [output of `git describe`]
CLM5.0
**Have you made any modifications to code, xml files, etc.?** [Yes / No]

[If Yes: Please point us to your modifications. However: In general we can NOT support problems with modified code. Try to show the problem without modifications.]

**If you are having problems with a specific case: Is your case on a machine accessible to most CTSM developers (e.g., an NCAR machine)?** [Yes / No]

If Yes:

- Location of case directory: [Fill this in]

- Location of run directory: [Fill this in]

[If No: Please make sure you have included all important input and output needed to understand your issue, either by pasting it into the issue text, or by attaching relevant files. However: We are less likely to be able to reproduce your problem if the issue is NOT on an NCAR machine.]

**Comment by olyson** [comment]
Well, personally,  I don't have a clue about this.  Do you have any other log files you can post?
One thing you could try is to compile and run in DEBUG mode and see if you get more information about the error in your log files.

**Comment by qhgogogo** [comment]
Thank you, Keith! Now this problem has been resolved by assigning more
computing nodes.

Best,

Han

**Comment by olyson** [comment]
Thanks for posting the solution.
