### ISSUE TITLE
LILAC: Ability to compile WRF-Chem with LILAC

### ISSUE THREAD

**Issue by negin513** [ESCOMP/CTSM#898]
There is a community of users who wants to run WRF-Chem with LILAC to investigate the impacts of different aerosols and gas deposition/emission on/from the land, etc. 
We need to start thinking about supporting WRF-Chem builds with LILAC/CTSM. I believe this can be easily done by setting an environment variable (`setenv WRF_CHEM 1`or  `export WRF_Chem=1`). One LILAC has the ability to transfer aerosols and gases back and forth, this should be further tested and documented.

**Comment by billsacks** [comment]
It sounds to me like this particular issue is about WRF, not LILAC. I am therefore changing the `type` label. Feel free to correct me if I'm wrong.

**Comment by billsacks** [comment]
Unfortunately, with no current support dedicated to WRF-CTSM, we're going to close this as a wontfix.
