### ISSUE TITLE
flag for overwriting existing baselines in run_sys_tests

### ISSUE THREAD

**Issue by negin513** [ESCOMP/CTSM#899]
`run_sys_tests` is a wrapper script to run one or more `create_test` for running a suite of system tests more convenient.

The option `-o, --allow-baseline-overwrite` in `create_test` can be used for overwriting the existing baselines. However, there is no such option in `run-sys-tests` for over-writing existing baselines.  
It might worth having this flag available in `run-sys-tests` similar to `create_test`.

**Comment by ekluzek** [comment]
@negin513 the option --extra-create-test-args can be used to add extra arguments to create_test. As a matter of fact I used to use it to use just this exact option "-o". I got away from that when @billsacks pointed out to me that it can be buggy. Specifically I think that it might not always copy over namelist files like it should. So I've started deleting my baseline directories explicitly when I have to overwrite them. I do run into problems when I forget to do that, but I at least can be sure they are correct.

**Comment by billsacks** [comment]
Yes, I steer people away from this flag to `create_test`. Here's an email exchange I had with @ekluzek a few months ago:

> I'm getting a bunch of unexpected NLCOMP failures comparing against your latest tag.
>
> [SNIP]
>
> I'm guessing this is arising because you reran tests with the '--allow-baseline-overwrite' flag. I find that flag to be very problematic, partly for cases like this, but even more so if you have a situation like: You initially ran the test and it passed and generated a baseline. Then you realized there was a problem with the baseline, so you reran the test and it failed, but you accidentally overlooked the failure. In that case, the baseline would be from the first run, causing potential massive confusion to anyone comparing against the baselines.
>
> For these reasons, I feel it's (much?) better to first explicitly remove or move aside any problematic baselines, then rerun the test suite without '--allow-baseline-overwrite'. In fact, I kind of wish that flag didn't even exist, so that it didn't tempt people to use it.

So @negin513 I would request that we close this issue as a wontfix. Are you okay with that?

**Comment by negin513** [comment]
@ekluzek and @billsacks : Thanks for explaining the rationale behind not having `-o, --allow-baseline-overwrite` in `run-sys-tests`.  I will keep in mind to stay away from this option for `create_test`. 
I am going to close this issue and tag it as `closed: wontfix`.
