### ISSUE TITLE
mksurfdata_map raw data grids should just be listed in hgrid, not res

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#9]
**Bill Sacks < sacks@ucar.edu > - 2013-04-12 06:02:12 -0600**
**Bugzilla Id:** [1661](http://bugz.cgd.ucar.edu/show_bug.cgi?id=1661)
**Bugzilla CC:**  rfisher@ucar.edu, 

Currently, it looks like grids for mksurfdata_map raw data files are listed in two places in namelist_definition_clm4_5.xml: the valid values for 'res' and the valid values for 'hgrid'. The fact that they're listed in the valid values for 'res' can be an annoyance when making mapping files with mkmapdata/regridbatch, because this tool then tries to make mapping files TO these raw data resolutions (which is unnecessary). 

This annoyance is becoming magnified with my addition of a 1km raw data file, for which mapping files take a long time to generate. 

I think these raw data grids should just be listed in hgrid, not res. But I haven't looked closely at this, so I'm not positive about it. I think this will require changing some things in queryDefaultNamelist.

**Comment by ekluzek** [comment]
With mksurfdata_esmf we can just remove hgrid as well as res.
