### ISSUE TITLE
cheyenne intel debug not catching un-allocated arrays

### ISSUE THREAD

**Issue by rgknox** [ESCOMP/CTSM#908]
### Brief summary of bug

In PR #770, we introduced a FATES bug.  On this line here: https://github.com/ESCOMP/CTSM/pull/770/files#diff-d5aa89e69afc455e4e84461df1cfa3b6R1426

The array "this%fates(nc)%bc_in(s)%qflx_transp_pa(:)" is only allocated when we have our hydraulics module active.  However, this routine looks to zero that array, even when the module is not active, and the array is not allocated.

We have a good number of cheyenne intel tests, debug and non-debug, none of which caught this unallocated array.  The gnu compiler caught this.

Here is the fix we issued: #901 

And we are now going to start running 3 gnu tests during our standard testing.

I just wanted to bring this up to the team though.  Maybe there is a way to turn on array checking with Intel debug. Or perhaps this is a strategic decision, array checking may be costly?

### General bug information

**CTSM version you are using:** [output of `git describe`]

branch: fates_next_api

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]

Potentially, yes?  I suppose if zero'ing an unallocated array ends up zero'ing a memory space that shouldn't be zero'd? (although I don't know if that is what is happening).

**Configurations affected:** [Fill this in if known.]

all cheyenne intel tests

### Details of bug

[Fill in details here.]

### Important details of your setup / configuration so we can reproduce the bug

[Specify anything relevant: the compset, resolution, machine, compiler, any xml or namelist changes, etc. You don't have to repeat anything that you have already noted above.]

### Important output or errors that show the problem

[Fill this in with anything relevant that you haven't already noted; if there is nothing to add, delete this section.]

**Comment by rgknox** [comment]
Note, fates_next_api might have a much older definition of debug compiler flags...

**Comment by billsacks** [comment]
This may be more an issue with the intel compiler than with our use of it.... We include the following flags in debug mode: `-O0 -g -check uninit -check bounds -check pointers -fpe0 -check noarg_temp_created`

https://github.com/ESMCI/cime/blob/4c26f56e6cf3f85b9c5f8b1d54b36522631b5cde/config/cesm/machines/config_compilers.xml#L241

From https://software.intel.com/en-us/fortran-compiler-developer-guide-and-reference-check I can't see anything else that would be useful to catch this; can you? My suspicion is that it permitted assignment to a slice-without-bounds `foo(:) = 0`, even though it probably wouldn't permit assignment to a particular index of the array.

**Comment by billsacks** [comment]
One other note: Testing with multiple different compilers in debug mode is a great idea. You should know, though, that gnu debug checking doesn't check for NaNs due to problems with the gfortran compiler (https://github.com/ESMCI/cime/issues/1974), so beware of relying too heavily on gnu for your debug tests.

**Comment by rgknox** [comment]
I see, so intel is ok with that statement because we are essentially asking it to zero a null set of array indices.  Which it can do.

**Comment by billsacks** [comment]
That's what I'm thinking (though I haven't tested it).

**Comment by billsacks** [comment]
@rgknox do you feel anything more is needed here, or can we close this issue?

**Comment by billsacks** [comment]
Closing this because it seems like compiler behavior that we can't do anything about, but feel free to reopen.
