### ISSUE TITLE
Set restart flags appropriately in WRF-CTSM coupling

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#909]
With the completion of #877 , it's important that we set the stop and restart flags properly in the WRF-CTSM coupling.

**Comment by billsacks** [comment]
@negin513 it seems like you are working on this now (thank you!), so I'm assigning you.

**Comment by billsacks** [comment]
To be clear, this issue is about setting `write_restarts_now` and `stop_now` appropriately in the call to `lilac_run` from WRF, which will ensure that a restart file is written when it needs to be. In contrast, #876 encompasses any changes needed to start up from a restart file (i.e., do a continue as opposed to startup run).

**Comment by negin513** [comment]
I created another issue for the stop time flag (issue #1054  ) since the method for sending the time flag between them and needs inquiring current time and comparing it with the restart flag.
