### ISSUE TITLE
Add handling of sea ice in CTSM-WRF coupling

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#912]
Sea ice and open ocean need special handling in the CTSM-WRF coupling, similarly to what is done for other land surface schemes. WRF considers sea ice to be land (as opposed to ocean), and so it's up to the land scheme to handle it. Noah-MP does this by calling the older Noah sea ice subroutine for points classified as sea ice.

Places where this handling appears, where we likely need some CTSM-specific code, are:

- In the `ctsm_run` routine itself (called from `module_surface_driver`) (see https://github.com/ESCOMP/CTSM/issues/866#issuecomment-564744074)

- In code before and/or after the call to `ctsm_run` from `module_surface_driver` (see what's done in the Noah-MP and/or CLM cases): call to the sea ice routine, and possibly other code for handling sea ice points.

- `module_soil_pre`: Mike says that it could be important to set up the soil layer structure here to work with the sea ice scheme that we're going to use. For example, we may need code like this (around line 790 in `module_soil_pre`):

```Fortran
      ELSE IF ( ( sf_surface_physics .EQ. LSMSCHEME ) .AND. ( num_soil_layers .GT. 1 ) ) THEN
         CALL init_soil_depth_2 ( zs , dzs , num_soil_layers )
         CALL init_soil_2_real ( tsk , tmn , smois , sh2o , tslb , &
                                 st_input , sm_input , sw_input , landmask , sst , &
                                 zs , dzs , &
                                 st_levels_input , sm_levels_input , sw_levels_input , &
                                 num_soil_layers , num_st_levels_input , num_sm_levels_input , num_sw_levels_input , &
                                 num_st_levels_alloc , num_sm_levels_alloc , num_sw_levels_alloc , &
                                 flag_sst , flag_soil_layers , flag_soil_levels , &
                                 ids , ide , jds , jde , kds , kde , &
                                 ims , ime , jms , jme , kms , kme , &
                                 its , ite , jts , jte , kts , kte )
```

- Note that there is a call to `process_soil_pre` from `module_initialize_real`; we may need to update this to call this subroutine when running with CTSM.

**Comment by negin513** [comment]
The following has been addressed in #915 and #913.
> Sea ice and open ocean need special handling in the CTSM-WRF coupling, similarly to what is done for other land surface schemes. WRF considers sea ice to be land (as opposed to ocean), and so it's up to the land scheme to handle it. Noah-MP does this by calling the older Noah sea ice subroutine for points classified as sea ice.
> 
> Places where this handling appears, where we likely need some CTSM-specific code, are:
> 
> * In the `ctsm_run` routine itself (called from `module_surface_driver`) (see [#866 (comment)](https://github.com/ESCOMP/CTSM/issues/866#issuecomment-564744074))
> * In code before and/or after the call to `ctsm_run` from `module_surface_driver` (see what's done in the Noah-MP and/or CLM cases): call to the sea ice routine, and possibly other code for handling sea ice points.

**Comment by negin513** [comment]
> * `module_soil_pre`: Mike says that it could be important to set up the soil layer structure here to work with the sea ice scheme that we're going to use. For example, we may need code like this (around line 790 in `module_soil_pre`):
> 
> ```fortran
>       ELSE IF ( ( sf_surface_physics .EQ. LSMSCHEME ) .AND. ( num_soil_layers .GT. 1 ) ) THEN
>          CALL init_soil_depth_2 ( zs , dzs , num_soil_layers )
>          CALL init_soil_2_real ( tsk , tmn , smois , sh2o , tslb , &
>                                  st_input , sm_input , sw_input , landmask , sst , &
>                                  zs , dzs , &
>                                  st_levels_input , sm_levels_input , sw_levels_input , &
>                                  num_soil_layers , num_st_levels_input , num_sm_levels_input , num_sw_levels_input , &
>                                  num_st_levels_alloc , num_sm_levels_alloc , num_sw_levels_alloc , &
>                                  flag_sst , flag_soil_layers , flag_soil_levels , &
>                                  ids , ide , jds , jde , kds , kde , &
>                                  ims , ime , jms , jme , kms , kme , &
>                                  its , ite , jts , jte , kts , kte )
> ```
> 
> * Note that there is a call to `process_soil_pre` from `module_initialize_real`; we may need to update this to call this subroutine when running with CTSM.

`init_soil_depth_2` and `init_soil_2_real` and similar subroutines are for initializing the soil layer structures (for example how many layers and layer thickness.). This is not relevant for CTSM.  

Based on my discussion with Jimy Dudhia, there are two subroutines doing the adjustment for sea-ice fields. 
* `adjust_for_seaice_pre` is the adjustment for the sea-ice field prior to topmost soil layer temperature computation
* `adjust_for_seaice_post` is the adjustments for the seaice field AFTER the topmost soil layer temperature computation.

**Comment by negin513** [comment]
This also responds to some parts of #914 .

**Comment by ekluzek** [comment]
I'm just curious here. Is the plan to implement the Noah-MP code for sea-ice into CTSM when it's used with WRF? I think that makes sense. It just means we'll have a bit of code that is a bit odd for the rest of CTSM, so the directory it goes in should be thought about a bit. In the CESM context CTSM shouldn't have any capability for handling sea-ice, so it should be located such that a normal CESM user wouldn't see it.

**Comment by negin513** [comment]
@ekluzek 
This is a good question. Currently, the handling of sea-ice in WRF-CTSM simulations is the same as NOAH LSM. NOAH-MP also uses NOAH code handling of sea-ice. 

The subroutine that all three models (NOAH, NOAH-MP, WRF-CTSM) are using is in https://github.com/wrf-model/WRF/blob/develop/phys/module_sf_noah_seaice_drv.F

``` FORTRAN
  subroutine seaice_noah( SEAICE_ALBEDO_OPT, SEAICE_ALBEDO_DEFAULT, SEAICE_THICKNESS_OPT, &
       &                  SEAICE_THICKNESS_DEFAULT, SEAICE_SNOWDEPTH_OPT,               &
       &                  SEAICE_SNOWDEPTH_MAX, SEAICE_SNOWDEPTH_MIN,                   &
       &                  T3D, QV3D, P8W3D, DZ8W, NUM_SOIL_LAYERS, DT, FRPCPN, SR,      &
       &                  GLW, SWDOWN, RAINBL, SNOALB2D, QGH, XICE, XICE_THRESHOLD,     &
       &                  ALBSI, ICEDEPTH, SNOWSI,                                      &
       &                  TSLB, EMISS, ALBEDO, Z02D, TSK, SNOW, SNOWC, SNOWH2D, &
       &                  CHS, CHS2, CQS2,                                              &
       &                  RIB, ZNT, LH, HFX, QFX, POTEVP, GRDFLX, QSFC, ACSNOW,         &
       &                  ACSNOM, SNOPCX, SFCRUNOFF, NOAHRES,                           &
       &                  SF_URBAN_PHYSICS, B_T_BEP, B_Q_BEP, RHO,                      &
       &                  IDS, IDE, JDS, JDE, KDS, KDE,                                 &
       &                  IMS, IME, JMS, JME, KMS, KME,                                 &
       &                  ITS, ITE, JTS, JTE, KTS, KTE  )
```

Please note that we are calling this subroutine from the **WRF surface driver**  (and not within CTSM) after running CTSM for each timestep:
https://github.com/wrf-model/WRF/blob/7df983d896c36575cd6f1934104d63888febb112/phys/module_surface_driver.F#L3979-L3993.

Therefore, I think there is no need for CTSM to have this code internally. 

But @billsacks and @dlawrenncar can probably answer this question better than me.

**Comment by billsacks** [comment]
Yes, there will be no sea ice handling in CTSM itself.

**Comment by billsacks** [comment]
Unfortunately, with no current support dedicated to WRF-CTSM, we're going to close this as a wontfix. It seems like some of it was done, but maybe not all?
