### ISSUE TITLE
Add handling of CTSM in WRF's module_soil_pre

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#914]
There are various conditionals on the land surface scheme in WRF's `module_soil_pre`. We likely need to add some handling of CTSM in at least some of these places, for the following reasons (pointed out by Mike Barlage):

- For the handling of sea ice (see #912 )

- We may want to set soil moisture and possibly other soil-related diagnostic fields to missing values so that they don't show up as confusing, constant values on the WRF diagnostic files (possibly in `process_soil_pre`; then we should make sure this gets called when running with CTSM)

- Eventually, this could also be important if we want to use the standard WRF preprocessor scheme for getting initial values into CTSM (but we'll probably defer this point until later, if at all)

**Comment by negin513** [comment]
Ask Jimy Dudhia about if we need to initialize the soil layer structure at all in WRF.

**Comment by negin513** [comment]
Please see this comment for the some information about `module_soil_pre`: https://github.com/ESCOMP/CTSM/issues/912#issuecomment-705173841

**Comment by negin513** [comment]
> There are various conditionals on the land surface scheme in WRF's `module_soil_pre`. We likely need to add some handling of CTSM in at least some of these places, for the following reasons (pointed out by Mike Barlage):
> 
> * For the handling of sea ice (see #912 )

As per #912 `adjust_for_seaice_pre` and `adjust_for_seaice_post` are added for handling sea-ice points for CTSM cases. 

Based on the discussion I had with Jimy Dudhia (@dudhia), `process_soil_real` subroutine in `module_soil_pre`includes calls such as `init_soil_depth_2` and `init_soil_2_real` that are initializing the soil layer structure during the ****real** step** which produces wrf initial and boundary conditions. For CTSM cases, over the land points initialization of soil layers is done we are calling CTSM initialization so we are bypassing this step and we are not using the information from wrf initial and boundary condition files about soil layer structure, etc. 

@dudhia advised for better generalization we should use WRF pre-processing steps for creating CTSM initial conditions instead and initialization of soil layer structure, etc.
