### ISSUE TITLE
Review fields sent from WRF to CTSM to ensure we're sending the correct things

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#917]
I'd specifically like a review from @barlage on these points, which have TODO notes in the code:

- In the call to `ctsm_run` from `module_surface_driver`: Make sure @negin513 and I have identified the correct fields to pass

- pbot:

```Fortran
    ! TODO(wjs, 2020-01-01) Is this correct? Or does this give the pressure at the
    ! interface, whereas we may want the pressure at the mid-point???
    pbot(its:ite, jts:jte) = p8w(its:ite, 1, jts:jte)
```

- forc_th:

```Fortran
    ! TODO(wjs, 2020-01-01) For now, I'm setting potential temperature equal to
    ! temperature. Line 58470 of module_sf_clm has:
    !
    !     clm_a2l%forc_th(g)  = clm_a2l%forc_t(g) * (clm_a2l%forc_psrf(g) &
    !          / clm_a2l%forc_pbot(g))**(rair/cpair)
    !
    ! but it looks like it is using the same WRF variable for both forc_psrf and
    ! forc_pbot, so the adjustment from forc_t to forc_th isn't actually accomplishing
    ! anything. Should we do some sort of adjustment here?
    forc_th(its:ite, jts:jte) = t_phy(its:ite, 1, jts:jte)
```

- forc_q:

```Fortran
    ! Convert from mixing ratio to specific humidity
    ! TODO(wjs, 2020-01-01) Confirm that this is correct
    forc_q(its:ite, jts:jte) = qv_curr(its:ite, 1, jts:jte)/(1.0 + qv_curr(its:ite, 1, jts:jte))
```

**Comment by weiwangncar** [comment]
Sam directed me to this issue, so I hope you don't mind me commenting here.
p8w is the interface pressure with the first level value equivalent to surface pressure. If you want first mid point pressure, the WRF variable is p_phy. 
If you really wanted potential temp in CLM, then that calculation for forc_th isn't right. But potential temp does exist in surface driver, and it is th_phy.

**Comment by billsacks** [comment]
@weiwangncar thank you very much for commenting on this.

> p8w is the interface pressure with the first level value equivalent to surface pressure. If you want first mid point pressure, the WRF variable is p_phy.

I'm not sure what CTSM expects: pressure at the mid-point of the bottom layer or pressure exactly at the surface. @slevisconsulting is that something you could dig into?

> If you really wanted potential temp in CLM, then that calculation for forc_th isn't right. But potential temp does exist in surface driver, and it is th_phy.

Thanks for this. @negin513 since you're working with this branch, can you please add th_phy to the ctsm_run routine?

----

I also wanted to clarify / expand upon my other requests a bit:

> - forc_q:
> 
> ```Fortran
>     ! Convert from mixing ratio to specific humidity
>     ! TODO(wjs, 2020-01-01) Confirm that this is correct
>     forc_q(its:ite, jts:jte) = qv_curr(its:ite, 1, jts:jte)/(1.0 + qv_curr(its:ite, 1, jts:jte))
> ```

I think @negin513 or I copied this from somewhere (maybe the old CLM code in WRF), but weren't sure whether it was correct. It would be helpful if someone could dig into this, based on the meaning / units of `forc_q` in CTSM vs. that of `qv_curr` in WRF.

> - In the call to `ctsm_run` from `module_surface_driver`: Make sure @negin513 and I have identified the correct fields to pass

To clarify what I mean here: It would be great to get a second set of eyes on each of the fields passed from WRF to CTSM to confirm that the correspondence between WRF fields and CTSM fields is correct in terms of their meaning and units. This amounts to reviewing this code and double-checking the meaning and units of the various fields (see comments near the top of `module_surface_driver.F` for a description / units of some of the WRF fields):

https://github.com/billsacks/WRF/blob/55faee764c4c65d878ace0c68cf7da3a07c03e0c/phys/module_sf_ctsm.F#L482-L542

**Comment by weiwangncar** [comment]
@billsacks The conversion from mixing ratio to specific humidity is correct. If we know what CTSM wants, we can get the right fields from WRF.

**Comment by slevisconsulting** [comment]
@weiwangncar thank you from me, as well, for commenting on this.

> > p8w is the interface pressure with the first level value equivalent to surface pressure. If you want first mid point pressure, the WRF variable is p_phy.
> 
> I'm not sure what CTSM expects: pressure at the mid-point of the bottom layer or pressure exactly at the surface. @slevisconsulting is that something you could dig into?

The CTSM assumes atmospheric inputs at `zatm` (the reference height for flux computations),
where
`𝑧𝑎𝑡𝑚 = 𝑧′𝑎𝑡𝑚 + 𝑧0 + 𝑑`
and
`d` is the displacement height (from zero for bare ground to about 30 m for a 40-m tree)
`z0` is the roughness length (less than 0.1 m) and
`𝑧′𝑎𝑡𝑚` is the atmospheric reference height received from the atmospheric model. In land-only mode, 𝑧′𝑎𝑡𝑚 = 30 m.

So the CTSM expects pressure not exactly at the surface. I don't know the thickness of WRF's bottom layer, but the middle of the bottom layer seems the right choice to me.

**Comment by slevisconsulting** [comment]
> @billsacks The conversion from mixing ratio to specific humidity is correct. If we know what CTSM wants, we can get the right fields from WRF.

The CTSM needs specific humidity, so this seems fine.

To cross-check, I looked at variable QBOT (atmospheric sp. humidity) in CTSM's monthly history files from a 6-month WRF-CTSM simulation. Values range 0.00155 kg/kg (parts of Canada in April) to 0.0216 kg/kg (tropical areas in July), which is reasonable.

**Comment by slevisconsulting** [comment]
@weiwangncar please confirm whether these statements are correct:

In the code that @billsacks referenced, the treatment of precipitation looks correct:
`rainbl` is total precip in mm/tstep and
`sr` is the ratio of frozen precip to total precip

**Comment by weiwangncar** [comment]
@slevisconsulting rainbl is correct, which is the rain per time step. Will get back to you about SR.

**Comment by weiwangncar** [comment]
@slevisconsulting SR from WRF is the ratio of frozen precip over total precip produced by the microphysics.

**Comment by slevisconsulting** [comment]
Thank you, @weiwangncar , and sorry for my delayed response.

We didn't talk about u_phy and v_phy, but these seem correct to me. They are in m/s (same as the CTSM variables) and they correspond to the middle of the bottom atm. layer.

To summarize, we have two pending issues raised in the above conversation:
- p8w must be replaced with p_phy
- forc_th must be set equal to th_phy

@billsacks once we resolve these, we can close this issue.

**Comment by billsacks** [comment]
Thanks, @slevisconsulting 

@negin513 can you please resolve the issues raised by @slevisconsulting in his last comment, when you get a chance?

**Comment by weiwangncar** [comment]
@slevisconsulting Yes, u_phy and v_phy are u and v components of wind, in the middle of bottom layer and co-locate with temp and moisture variables.

**Comment by slevisconsulting** [comment]
Hi @negin513 

I wanted to check whether the fix [related to negative incoming solar](https://github.com/ESCOMP/CTSM/issues/911#issuecomment-643460771)
has gone in the code. If not, I can reimplement my temporary fix.

**Comment by negin513** [comment]
I implemented a flag (switch) that can be used for any WRF field, which basically zeros out negative values of that field. This flag is currently used only for the four radiation components which were causing [the issue related to negative incoming solar](https://github.com/ESCOMP/CTSM/issues/911#issuecomment-643460771)

This optional flag is implemented on the WRF side in `export_to_lilac` subroutine in `phys/module_sf_ctsm.F` and it is by default on for the four radiation fields (`swnirdir`, `swvisdir`, `swnirdif`, `swvisdif`) but this switch can similarly be used for the other atmosphere to land fields. 

This feature might come in useful when we are expanding the fields sent from WRF to CTSM (for example Black Carbon or Dust) and we might want to ignore negative values (if they occur).

**Comment by negin513** [comment]
@billsacks Should I go ahead and close this issue?

**Comment by slevisconsulting** [comment]
Before closing the issue, I wanted to confirm that the following has been addressed:

>> we have two pending issues raised in the above conversation:
>> 
>> * p8w must be replaced with p_phy
>> * forc_th must be set equal to th_phy
>> 
>> @billsacks once we resolve these, we can close this issue.
>
> @negin513 can you please resolve the issues raised by @slevisconsulting in his last comment, when you get a chance?

**Comment by negin513** [comment]
Do we also need forc_t ( = t_phy) in module_sf_ctsm?
With current LILAC API we are passing t_phy to CTSM, do we need th_phy in addition to that or should I just replace t_phy with th_phy?  If we need both this requires a change to the API. 

We currently have this inside module_sf_ctsm.F:

```
    ! TODO(wjs, 2020-01-01) For now, I'm setting potential temperature equal to
    ! temperature. Line 58470 of module_sf_clm has:
    !                              
    !     clm_a2l%forc_th(g)  = clm_a2l%forc_t(g) * (clm_a2l%forc_psrf(g) &
    !          / clm_a2l%forc_pbot(g))**(rair/cpair)
    !                              
    ! but it looks like it is using the same WRF variable for both forc_psrf and
    ! forc_pbot, so the adjustment from forc_t to forc_th isn't actually accomplishing
    ! anything. Should we do some sort of adjustment here?
    ! (See https://github.com/ESCOMP/CTSM/issues/917)
    forc_th(its:ite, jts:jte) = t_phy(its:ite, 1, jts:jte)
                                   
    forc_t(its:ite, jts:jte) = t_phy(its:ite, 1, jts:jte)                                                                                                                                                                            
                                   
```

**Comment by slevisconsulting** [comment]
@negin513 we need to change this to:

```
forc_th(its:ite, jts:jte) = th_phy(its:ite, 1, jts:jte)
forc_t(its:ite, jts:jte) = t_phy(its:ite, 1, jts:jte)
```

**Comment by negin513** [comment]
This issue has been addressed in the latest commits in my WRF lilac_dev fork (commit 6a038127).

**Comment by negin513** [comment]
@billsacks and @slevisconsulting 

Since the comments are addressed here, I am closing this issue.
