### ISSUE TITLE
PGI build fails on izumi for release branch

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#921]
### Brief summary of bug

The build is failing for PGI on izumi

### General bug information

**CTSM version you are using:** release-clm5.0.30
**Does this bug cause significantly incorrect results in the model's science?** N

**Configurations affected:** any build on izumi with PGI

### Details of bug

SMS.f10_f10_musgs.I2000Clm50BgcCrop.izumi_pgi.clm-crop
SMS_D.f10_f10_musgs.I2000Clm50BgcCrop.izumi_pgi.clm-crop

### Important details of your setup / configuration so we can reproduce the bug

Here's the fix:

``` fortran
diff --git a/src/utils/clmfates_paraminterfaceMod.F90 b/src/utils/clmfates_paraminterfaceMod.F90
index 9a3ce58f..2f63389a 100644
--- a/src/utils/clmfates_paraminterfaceMod.F90
+++ b/src/utils/clmfates_paraminterfaceMod.F90
@@ -2,6 +2,7 @@ module CLMFatesParamInterfaceMod
   ! NOTE(bja, 2017-01) this code can not go into the main clm-fates
   ! interface module because of circular dependancies with pftvarcon.
 
+  use shr_kind_mod, only : r8 => shr_kind_r8
   use FatesGlobals, only : fates_log
   
   implicit none
@@ -172,7 +173,6 @@ end subroutine GetUsedDimensionSizes
  !-----------------------------------------------------------------------
  subroutine ParametersFromNetCDF(filename, is_host_file, fates_params)
 
-   use shr_kind_mod, only: r8 => shr_kind_r8
    use abortutils, only : endrun
    use fileutils  , only : getfil
    use ncdio_pio  , only : file_desc_t, ncd_pio_closefile, ncd_pio_openfile

```
### Important output or errors that show the problem

> PGF90-S-0087-Non-constant expression where constant expression required (/fs/cgd/data0/erik/ctsm_relanswerchangesfor5029/src/utils/clmfates_paraminterfaceMod.F90: 197)
> PGF90-S-0081-Illegal selector - KIND parameter has unknown value for data type  (/fs/cgd/data0/erik/ctsm_relanswerchangesfor5029/src/utils/clmfates_paraminterfaceMod.F90: 197)
>   0 inform,   0 warnings,   2 severes, 0 fatal for parametersfromnetcdf
> gmake: *** [clmfates_paraminterfaceMod.o] Error 2
> gmake: *** Waiting for unfinished jobs....
>   Timing stats:

**Comment by ekluzek** [comment]
The fix for this went into the release branch on  Mon Mar 23 15:04:50 2020 -0600. It's also fixed on main-dev CTSM as well. So closing.

**Comment by megranaterogger** [comment]
I feel confused about that, there was no module file named FatesGlobals.* how could it build passed. and my building error is :Fatal Error: Cannot open module file ‘fatesglobals.mod’ for reading at (1): No such file or directory
