### ISSUE TITLE
Segmentation fault in initialization with intel 18.0.3

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#930]
### Brief summary of bug

On hobart, which uses intel 18.0.3, the test `SMS.f10_f10_musgs.I2000Clm50BgcCrop.hobart_intel.clm-crop` fails with a segmentation fault in initialization, pointing to this line (the subroutine declaration line):

https://github.com/ESCOMP/CTSM/blob/95fc9e1622d2765db61d132a7e5d61a3cb4b87e7/src/main/clm_initializeMod.F90#L42

@swensosc originally ran into this bug and found that he could avoid the problem by removing the optional `gindex_ocn` argument. But that argument is needed for the nuopc and (upcoming) lilac caps. I have found that I can also solve the problem by changing the intent of the argument from `out` to `inout`. I'm thinking this is a compiler bug, but I'll make that change on a branch to work around the issue.

### General bug information

**CTSM version you are using:** ctsm1.0.dev084

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** All with particular versions of the intel compiler.

**Comment by billsacks** [comment]
Fixed in 2d277c107940aa941d0649432e0aba9cc3d94cd2 (on `lilac_cap` branch).

**Comment by ekluzek** [comment]
Marius seems to be having a similar problem on his machine in Oslo when running with a single task. I'm going to check with him what version of intel he's using. Thanks for adding this issue!

**Comment by ekluzek** [comment]
Francis would like to have the workaround in place for his work on the NASA machine Pleadies. The work around does work for him.

**Comment by billsacks** [comment]
Cherry-picked onto a branch that should come to master soon as 28dad047
