### ISSUE TITLE
Diagnostic variables SOILWATER_10CM, TOTSOILLIQ, and TOTSOILICE are incorrect

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#932]
### Brief summary of bug

Soil water is updated for saturation excess after SOILWATER_10CM, TOTSOILLIQ, and TOTSOILICE are calculated. Originally reported by Keith Lindsay.

### General bug information

**CTSM version you are using:** release-clm5.0.30

**Does this bug cause significantly incorrect results in the model's science?** The effect on the model's science is probably minimal since the problem only occurs in regions with saturated or near-saturated soils, when changes in soil moisture don't really affect the system (e.g., evaporation).

**Configurations affected:** All.

### Details of bug

h2osoi_liqice_10cm is calculated from h2osoi_liq and h2osoi_ice in HydrologyNoDrainage.
However, h2osoi_liq can be updated later in the time step (in LateralFlowPowerLaw where water is moved upwards to keep layers within the limits of the layer porosity).
LateralFlowPowerLaw is called from HydrologyDrainage, which is called after HydrologyNoDrainage.
Changes to h2osoi_liq may also occur in PerchedLateralFlow as well.
This bug also applies to  h2osoi_liq_tot and h2osoi_ice_tot.

Solution to be discussed at software engineering meeting.  One possibility is to create a separate routine to calculate these diagnostic variables and call it from clm_driver near/at the end of the timestep.  The 10cm tsoi should also be included here, although it isn't affected by this bug.

**Comment by billsacks** [comment]
We talked about this at the CTSM software meeting today.

At least in recent versions of the code, there are already appropriate summary routines in which the water diagnostic terms can be computed: see the subroutines named `Summary` in `WaterDiagnosticBulkType.F90` and `WaterDiagnosticType.F90` (the former is used for diagnostics that only exist for bulk water, and the latter for diagnostics that are – or will eventually be – computed for both bulk water and any water tracers / isotopes; it looks like SOILWATER_10CM is in the latter).

This is called from here:

https://github.com/ESCOMP/CTSM/blob/95fc9e1622d2765db61d132a7e5d61a3cb4b87e7/src/main/clm_driver.F90#L1020-L1026

This seems sufficiently late in the driver loop for any end-of-time-step biogeophysics diagnostic calculations like this.
