### ISSUE TITLE
Add option to mksurfdata.pl to handle "negative" years (ie. BCE)

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#934]
The Holocene simulations will start at 10,000 BCE and run through 850 AD. In order to handle this for the surface datasets we need to have a way to handle "negative" years. We are going to label this with positive years that start at 10,000 BCE and then run through year 10,0000 which will be 1 AD (also note that year 0 is skipped). 

There will be a branch of this for the Holocene, but we might as well bring this addition to the mainline development as well.

@lawrencepj1

**Comment by ekluzek** [comment]
OK, I'm working on this with @lawrencepj1. They are ready to start this simulation. We need the years to match the file CAM is using:

$CSMDATA/atm/waccm/lb/LBC_8501BP-2CE_TransientHolocene_0p5degLat_GlobAnnAvg_c20201029.nc

That file has year 0 as 6551 BCE and year 6552 as 2 CE.

So we need our file to run from year index 501 to 6552. The year index 501 corresponds to year 6050 BCE and 6552 is 2 CE.

     0 = 6551 BCE
     1  = 6550
    10 = 6541
 500 = 6051
 501 = 6050
6550 = 1 BCE
6551 = 1 CE
6552 = 2 CE

**Comment by lawrencepj1** [comment]
Hi Erik

Thanks for putting this up. For the 1CE the idea is to restart at year 1.

Peter
-- 
Dr Peter Lawrence
Terrestrial Science Section
National Center for Atmospheric Research
1850 Table Mesa Drive
Boulder Colorado 80305

Work: 1-303-497-1727
Cell: 1-303-956-6932

**Comment by ekluzek** [comment]
We worked around this for the work that needed it. I'm going to close this as a WONTFIX, unless we run into this need again. The application is specialized enough that it's not a standard thing that will be done.
