### ISSUE TITLE
Land use time series for extensions to 2300

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#944]
It looks like we're going to be able to run SSP5-3.4 overshoot and SSP5-8.5 extensions out to 2300 with CESM2. To do this we'll need 

- Land use time series for each scenario that will go into a 

- Compset for each scenario (Jim Edwards may be creating this)

@lawrencepj1 how did you do this for the CESM1 RCP8.5 extension?  How do we handle wood harvest and LULCC out to 2300?   Let's discuss at the TSS meeting tomorrow.

**Comment by lawrencepj1** [comment]
Hi Will

Yes that sounds good. There are LUH2 LULCC extensions 2100 - 2300 for
SSP1-26, SSP5-34 and SSP5-85. It is just a matter of downloading them and
then generating the CLM data. This should be pretty easy to do.

talk tomorrow
Peter
-- 
Dr Peter Lawrence
Terrestrial Science Section
National Center for Atmospheric Research
1850 Table Mesa Drive
Boulder Colorado 80305

Work: 1-303-497-1727
Cell: 1-303-956-6932

**Comment by wwieder** [comment]
Great, Peter. Can we go ahead a start moving on generating the land use time series for SSP5-34 and SSP5-85?  It seems like we'd like to get these simulations running pretty soon.

**Comment by lawrencepj1** [comment]
Hi Will

Yes absolutely. Will start doing this today.

Peter
-- 
Dr Peter Lawrence
Terrestrial Science Section
National Center for Atmospheric Research
1850 Table Mesa Drive
Boulder Colorado 80305

Work: 1-303-497-1727
Cell: 1-303-956-6932

**Comment by ekluzek** [comment]
This will go on the release-clm5.0 branch and into the next CESM2.1 release. We'll need to have a compset and test in CTSM for this. And CESM will also need a compset for each.

**Comment by lawrencepj1** [comment]
Thanks Erik

Yes this needs to be the same release code as the CMIP6 simulations as they
will be an extension of those runs. I will produce raw files for both that
version of the model and the Trendy2019 version of the model with the crop,
shifting cultivation and other updates. I will let you know when they are
available.

best
Peter
-- 
Dr Peter Lawrence
Terrestrial Science Section
National Center for Atmospheric Research
1850 Table Mesa Drive
Boulder Colorado 80305

Work: 1-303-497-1727
Cell: 1-303-956-6932

**Comment by ekluzek** [comment]
taxmode in both pop-dens and urbantv are setup to "extend". So we'll run over 2100 for popdens and 2100-2106 for urbantv and they'll both use the last value in the file after they get to the end of the data. ndep is monthly and set to cycle (so for I cases it will loop over the last year of data since it has a seasonal cycle). For cases with WACCM, ndep comes from CAM so it doesn't matter what ndep file is being used.

**Comment by wwieder** [comment]
@ekluzek is this close to being ready?  It looks the the CAM tag is ready to go, so once the land is done @jedwards4b can make the final CESM tag.

**Comment by ekluzek** [comment]
This is on the release branch (release-clm5.0.32). We do NOT plan to bring it to master at least for now.

**Comment by lawrencepj1** [comment]
Thanks Erik

Just wanted to remind you it has to be consistent with the CMIP6 CESM
release tag which it will continue on from in the extension simulations.
This might be obvious but it is easier to mention than to assume.

see you
Peter
-- 
Dr Peter Lawrence
Terrestrial Science Section
National Center for Atmospheric Research
1850 Table Mesa Drive
Boulder Colorado 80305

Work: 1-303-497-1727
Cell: 1-303-956-6932
