### ISSUE TITLE
 No default value found for fsurdat

### ISSUE THREAD

**Issue by qhgogogo** [ESCOMP/CTSM#956]
Dear NCAR scientist,

While I'm trying to run a global case using CLM5.0 with grid resolution f05_g16 on constance:
./create_newcase --case casef05g16 --res f05_g16 --compset I2000Clm50BgcCru --mach constance --run-unsupported ,
I got the following error:
ERROR: Command /pic/projects/sif/CLM/clm5.0/bld/build-namelist failed rc=255
out=CLM adding use_case 2000_control defaults for var 'sim_year' with val '2000'
CLM adding use_case 2000_control defaults for var 'sim_year_range' with val 'constant'
CLM adding use_case 2000_control defaults for var 'stream_year_first_ndep' with val '2000'
CLM adding use_case 2000_control defaults for var 'stream_year_first_popdens' with val '2000'
CLM adding use_case 2000_control defaults for var 'stream_year_first_urbantv' with val '2000'
CLM adding use_case 2000_control defaults for var 'stream_year_last_ndep' with val '2000'
CLM adding use_case 2000_control defaults for var 'stream_year_last_popdens' with val '2000'
CLM adding use_case 2000_control defaults for var 'stream_year_last_urbantv' with val '2000'
CLM adding use_case 2000_control defaults for var 'use_case_desc' with val 'Conditions to simulate 2000 land-use'
err=ERROR : CLM build-namelist::CLMBuildNamelist::add_default() : No default value found for fsurdat.
            Are defaults provided for this resolution and land mask?
But if I change the resolution to f09_g16, the case could be successfully built, I'm wondering what is the reason cause the error? Is it the mismatch between compset and resolution or do I need to specify the fsurdat in the namelist?

Thanks a lot,

Han

**Comment by ekluzek** [comment]
We don't have default surface datasets at all resolutions. And f05 is one of the ones we don't have. You'll need to create the surface dataset that you need using the mksurfdata_map tool. It's under tools/mksurfdata_map, there's some README files on how to run it. There's also documentation in the User's Guide.

**Comment by qhgogogo** [comment]
Thank you, Erik. This solved my problem.
