### ISSUE TITLE
The variable "rh_can" is used for VPD when the medlyn stomatal conductance is called

### ISSUE THREAD

**Issue by djk2120** [ESCOMP/CTSM#957]
The Medlyn stomatal conductance uses VPD as its input, whereas Ball-Berry uses RH. In order to use the same code for both, the variable "rh_can" passes in VPD when the medlyn stomatal conductance is called, and more appropriately, relative humidity when the ball-berry model is used. I think this could be potentially very confusing. Might be better to code them up separately and use more appropriately named variables. It would also be very useful to have that VPD variable available for history output.

See L1617 and L3293: PhotosynthesisMod.F90
```
if (      stomatalcond_mtd == stomatalcond_mtd_bb1987 )then
    rh_can = ceair / esat_tv(p)
else if ( stomatalcond_mtd == stomatalcond_mtd_medlyn2011 )then
    ! Put some constraints on RH in the canopy when Medlyn stomatal conductance is being used
    rh_can = max((esat_tv(p) - ceair), 50._r8) * 0.001_r8
end if
```

**Comment by ekluzek** [comment]
Looks like this came in with ctsm1.0.dev111. In the second if above vpd_can is set by rh_can and it's output as VPD_CAN.

**Comment by djk2120** [comment]
I suggest we re-open this issue. The answers are all fine, but the code still reads very confusing.

https://github.com/ESCOMP/CTSM/blob/e7fdb15f755c2a9e7b3b4f0683a1ab624ee99928/src/biogeophys/PhotosynthesisMod.F90#L3554-L3562

We will need to update the hybrid subroutine to include vpd_can in the variable passing infrastructure. L3560 should not reference rh_can, as this is in fact vpd_can.
