### ISSUE TITLE
Bug in snow aerosol numerics can cause aerosol masses to blow up, starting with ctsm1.0.dev065

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#965]
### Brief summary of bug

SMS_Ly5.f19_g17.I1850Clm50Bgc.cheyenne_intel.clm-monthly fails because of a NaN in output from CLM to the cpl

### General bug information

**CTSM version you are using:** ctsm1.0.dev086

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** 

f19_g17
f09_g17 works fine. We have tests for other resolutions that seem to work fine as well (see below)

### Details of bug

I tried running

./check_input_data --chksum

and it didn't show any file errors.

Here are the long tests we currently do...

ERS_Ly6_Mmpi-serial.1x1_smallvilleIA.IHistClm50BgcCropQianGs.cheyenne_intel.clm-cropMonthOutput
ERS_Ly20_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianGs.cheyenne_intel.clm-cropMonthOutput
ERS_Ly5_P144x1.f10_f10_musgs.IHistClm50BgcCrop.cheyenne_intel.clm-cropMonthOutput
ERS_Ly5_P72x1.f10_f10_musgs.IHistClm45BgcCrop.cheyenne_intel.clm-cropMonthOutput
SMS_D_Ly6_Mmpi-serial.1x1_smallvilleIA.IHistClm45BgcCropQianGs.cheyenne_intel.clm-cropMonthOutput

### Important output or errors that show the problem

atm gets this far:

> (shr_dmodel_readstrm) file ub: /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/TPHWL/clmforc.GSWP3.c2011.0.5x0.5.TPQWL.1904-08.nc      17
> (datm_comp_run) atm: model date    40802   82800s
> (datm_comp_run) atm: model date    40802   84600s
> (datm_comp_run) atm: model date    40803       0s

cesm.log shows this...

> 308: # of NaNs =            4
> 308: Which are NaNs =  T T T T F F F F F F F F F F F F F F F F F F F F F F F F F F F
> 308: F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F
> 308: F F
> 308: Sl_avsdr
> 308: Sl_anidr
> 308: Sl_avsdf
> 308: Sl_anidf
> 308: gridcell index =         1092
> 308: ENDRUN:
> 308: ERROR:
> 308: lnd_export                       ERROR: One or more of the output from CLM to t
> 308: he coupler are NaN
> 308:Image              PC                Routine            Line        Source
> 308:cesm.exe           0000000001AB2C8A  Unknown               Unknown  Unknown
> 308:cesm.exe           00000000011AF6F0  shr_abort_mod_mp_         114  shr_abort_mod.F90
> 308:cesm.exe           00000000005032AF  abortutils_mp_end          50  abortutils.F90
> 308:cesm.exe           0000000000502515  lnd_import_export         424  lnd_import_export.F90
> 308:cesm.exe           00000000004F84DD  lnd_comp_mct_mp_l         464  lnd_comp_mct.F90
> 308:cesm.exe           00000000004282A4  component_mod_mp_         737  component_mod.F90
> 308:cesm.exe           0000000000409DCB  cime_comp_mod_mp_        2615  cime_comp_mod.F90
> 308:cesm.exe           0000000000427EDC  MAIN__                    133  cime_driver.F90
> 308:cesm.exe           0000000000407CA2  Unknown               Unknown  Unknown
> 308:libc.so.6          00002AB22D4526E5  __libc_start_main     Unknown  Unknown
> 308:cesm.exe           0000000000407BA9  Unknown               Unknown  Unknown
> 308:MPT ERROR: Rank 308(g:308) is aborting with error code 1001.

**Comment by ekluzek** [comment]
Note, some oddities about this. If I start at 004-08-01 it runs over the same forcing and works fine. Also an Sp case works fine...

SMS_Ly5.f19_g17.I1850Clm50Sp.cheyenne_intel.clm-monthly

I tried a case with Cru forcing and it failed with a problem with h2osoi_ice going "significantly negative" in the first year.

@olyson has found that ctsm1.0.dev074 fails similarily, but ctsm1.0.dev058 works fine.

**Comment by olyson** [comment]
The earliest tag in which this fails is ctsm1.0.dev065.  It's fine in ctsm1.0.dev064 (and other previous tags I tested: ctsm1.0.dev058, ctsm1.0.dev060,)

**Comment by billsacks** [comment]
I can look into this. From looking at @olyson 's case, it looks like the problem is with an *output* field from CTSM being NaN, not an input as @ekluzek said in his initial comment. That explains why @ekluzek wasn't able to reproduce the issue when starting later. ctsm1.0.dev065 is a tag I made. This did change answers by roundoff. I'll start by reproducing the issue, then will see if I can also reproduce it with a minimal set of diffs off of dev064... then will go from there.

**Comment by ekluzek** [comment]
OK, awesome. I corrected the initial paragraph and updated the title.

**Comment by billsacks** [comment]
I have verified @olyson 's findings - the test `SMS_Ly5.f19_g17.I1850Clm50Bgc.cheyenne_intel.clm-monthly` (run out of the box except with `./xmlchange REST_OPTION=nmonths,REST_N=1`) fails in dev065 but passes in dev064.

I have also found that this FAILS if I run from dev064 with just these differences; the case from dev064 with these differences is bit-for-bit with the run from dev065 (as of the restart file written `0004-08-01`):

```diff
diff --git a/src/biogeophys/SnowHydrologyMod.F90 b/src/biogeophys/SnowHydrologyMod.F90
index cad47e28..0abcc49f 100644
--- a/src/biogeophys/SnowHydrologyMod.F90
+++ b/src/biogeophys/SnowHydrologyMod.F90
@@ -1140,17 +1140,17 @@ contains
           c = filter_snowc(fc)
           if (j >= snl(c)+1) then
 
-             h2osoi_liq(c,j) = h2osoi_liq(c,j) + qin(c)
+             h2osoi_liq(c,j) = h2osoi_liq(c,j) + qin(c)*dtime
 
-             mss_bcphi(c,j) = mss_bcphi(c,j) + qin_bc_phi(c)
-             mss_bcpho(c,j) = mss_bcpho(c,j) + qin_bc_pho(c)
-             mss_ocphi(c,j) = mss_ocphi(c,j) + qin_oc_phi(c)
-             mss_ocpho(c,j) = mss_ocpho(c,j) + qin_oc_pho(c)
+             mss_bcphi(c,j) = mss_bcphi(c,j) + qin_bc_phi(c)*dtime
+             mss_bcpho(c,j) = mss_bcpho(c,j) + qin_bc_pho(c)*dtime
+             mss_ocphi(c,j) = mss_ocphi(c,j) + qin_oc_phi(c)*dtime
+             mss_ocpho(c,j) = mss_ocpho(c,j) + qin_oc_pho(c)*dtime
 
-             mss_dst1(c,j)  = mss_dst1(c,j) + qin_dst1(c)
-             mss_dst2(c,j)  = mss_dst2(c,j) + qin_dst2(c)
-             mss_dst3(c,j)  = mss_dst3(c,j) + qin_dst3(c)
-             mss_dst4(c,j)  = mss_dst4(c,j) + qin_dst4(c)
+             mss_dst1(c,j)  = mss_dst1(c,j) + qin_dst1(c)*dtime
+             mss_dst2(c,j)  = mss_dst2(c,j) + qin_dst2(c)*dtime
+             mss_dst3(c,j)  = mss_dst3(c,j) + qin_dst3(c)*dtime
+             mss_dst4(c,j)  = mss_dst4(c,j) + qin_dst4(c)*dtime
 
              if (j <= -1) then
                 ! No runoff over snow surface, just ponding on surface
@@ -1167,8 +1167,8 @@ contains
                 qout(c) = max(0._r8,(vol_liq(c,j) &
                      - ssi*eff_porosity(c,j))*dz(c,j)*frac_sno_eff(c))
              end if
-             qout(c) = qout(c)*1000._r8
-             h2osoi_liq(c,j) = h2osoi_liq(c,j) - qout(c)
+             qout(c) = (qout(c)*1000._r8)/dtime
+             h2osoi_liq(c,j) = h2osoi_liq(c,j) - qout(c)*dtime
              qin(c) = qout(c)
 
              ! mass of ice+water: in extremely rare circumstances, this can
@@ -1187,7 +1187,7 @@ contains
              if (qout_bc_phi(c) > mss_bcphi(c,j)) then
                 qout_bc_phi(c) = mss_bcphi(c,j)
              endif
-             mss_bcphi(c,j) = mss_bcphi(c,j) - qout_bc_phi(c)
+             mss_bcphi(c,j) = mss_bcphi(c,j) - qout_bc_phi(c)*dtime
              qin_bc_phi(c) = qout_bc_phi(c)
 
              ! BCPHO:
@@ -1196,7 +1196,7 @@ contains
              if (qout_bc_pho(c) > mss_bcpho(c,j)) then
                 qout_bc_pho(c) = mss_bcpho(c,j)
              endif
-             mss_bcpho(c,j) = mss_bcpho(c,j) - qout_bc_pho(c)
+             mss_bcpho(c,j) = mss_bcpho(c,j) - qout_bc_pho(c)*dtime
              qin_bc_pho(c) = qout_bc_pho(c)
 
              ! OCPHI:
@@ -1205,7 +1205,7 @@ contains
              if (qout_oc_phi(c) > mss_ocphi(c,j)) then
                 qout_oc_phi(c) = mss_ocphi(c,j)
              endif
-             mss_ocphi(c,j) = mss_ocphi(c,j) - qout_oc_phi(c)
+             mss_ocphi(c,j) = mss_ocphi(c,j) - qout_oc_phi(c)*dtime
              qin_oc_phi(c) = qout_oc_phi(c)
 
              ! OCPHO:
@@ -1214,7 +1214,7 @@ contains
              if (qout_oc_pho(c) > mss_ocpho(c,j)) then
                 qout_oc_pho(c) = mss_ocpho(c,j)
              endif
-             mss_ocpho(c,j) = mss_ocpho(c,j) - qout_oc_pho(c)
+             mss_ocpho(c,j) = mss_ocpho(c,j) - qout_oc_pho(c)*dtime
              qin_oc_pho(c) = qout_oc_pho(c)
 
              ! DUST 1:
@@ -1223,7 +1223,7 @@ contains
              if (qout_dst1(c) > mss_dst1(c,j)) then
                 qout_dst1(c) = mss_dst1(c,j)
              endif
-             mss_dst1(c,j) = mss_dst1(c,j) - qout_dst1(c)
+             mss_dst1(c,j) = mss_dst1(c,j) - qout_dst1(c)*dtime
              qin_dst1(c) = qout_dst1(c)
 
              ! DUST 2:
@@ -1232,7 +1232,7 @@ contains
              if (qout_dst2(c) > mss_dst2(c,j)) then
                 qout_dst2(c) = mss_dst2(c,j)
              endif
-             mss_dst2(c,j) = mss_dst2(c,j) - qout_dst2(c)
+             mss_dst2(c,j) = mss_dst2(c,j) - qout_dst2(c)*dtime
              qin_dst2(c) = qout_dst2(c)
 
              ! DUST 3:
@@ -1241,7 +1241,7 @@ contains
              if (qout_dst3(c) > mss_dst3(c,j)) then
                 qout_dst3(c) = mss_dst3(c,j)
              endif
-             mss_dst3(c,j) = mss_dst3(c,j) - qout_dst3(c)
+             mss_dst3(c,j) = mss_dst3(c,j) - qout_dst3(c)*dtime
              qin_dst3(c) = qout_dst3(c)
 
              ! DUST 4:
@@ -1250,7 +1250,7 @@ contains
              if (qout_dst4(c) > mss_dst4(c,j)) then
                 qout_dst4(c) = mss_dst4(c,j)
              endif
-             mss_dst4(c,j) = mss_dst4(c,j) - qout_dst4(c)
+             mss_dst4(c,j) = mss_dst4(c,j) - qout_dst4(c)*dtime
              qin_dst4(c) = qout_dst4(c)
 
           end if
@@ -1280,9 +1280,9 @@ contains
     do fc = 1, num_snowc
        c = filter_snowc(fc)
        ! Qout from snow bottom
-       qflx_snow_drain(c) = qflx_snow_drain(c) + (qout(c) / dtime)
+       qflx_snow_drain(c) = qflx_snow_drain(c) + qout(c)
 
-       qflx_rain_plus_snomelt(c) = (qout(c) / dtime) &
+       qflx_rain_plus_snomelt(c) = qout(c) &
             + (1.0_r8 - frac_sno_eff(c)) * qflx_liq_grnd(c)
        int_snow(c) = int_snow(c) + frac_sno_eff(c) &
                      * (qflx_dew_snow(c) + qflx_dew_grnd(c) + qflx_liq_grnd(c)) * dtime
```

I can try to track down what aspect of these differences causes the issue, though probably won't get a chance until next week.

**Comment by billsacks** [comment]
By the way, the overall intent of those changes was, as noted in the ChangeLog for ctsm1.0.dev065:

      Roundoff level: answer changes just arise because I have made
      qflx_snow_percolation_col a true flux, with units of
      per-unit-time; this involved dividing by dtime, and later
      multiplying by dtime when it is applied to states. Previously, the
      corresponding variable (qout / qin) was not per-unit-time.

**Comment by billsacks** [comment]
I think I have found the problem: I missed some code that needed to be changed in ctsm1.0.dev065 (see billsacks@ef73c4c682e394330382e416385276b439bcc2cf for change off of my ctsm1.0.dev064 branch). Specifically, I missed some places that needed multiplications or divisions by dtime in some code that ensures that aerosol mass fluxes between the snow layers don't exceed the total mass. **This is potentially a big issue for any case done with ctsm1.0.dev065 or later.**

**The issue can be seen by examining the history variables SNOBCMCL, SNOOCMCL and SNODSTMCL.** In the 5-year test case mentioned here, the first two of these are ridiculously large (e.g., 10^12) in one grid cell. I believe that large positive values or any negative values are a symptom of this bug, and probably cause the albedo calculation to blow up.

Reading through the code, although I'm not positive, I think what can happen is the following:
- Calculation of aerosol mass flux out of a layer can result in slightly more flux than the existing mass; the bug leads this situation to not get picked up
- Thus the mass in this layer goes slightly negative
- The next time step, the condition `qout_bc_phi(c) > mss_bcphi(c,j)` will be triggered (because `qout_bc_phi(c)` will be a very small negative number, and `mss_bcphi(c,j)` will be a larger negative number). This will cause `qout_bc_phi` to be set equal to `mss_bcphi` – i.e., a relatively large negative number (since this was mistakenly a mass rather than a flux).
- Then, in this layer, we'll set `mss_bcphi(c,j) = mss_bcphi(c,j) - qout_bc_phi(c)*dtime`, which becomes `mss_bcphi(c,j) = mss_bcphi(c,j) - mss_bcphi(c,j)*dtime`, which sets `mss_bcphi` to a large-ish positive number in this layer.
- Meanwhile, in the next layer, we'll end up doing `mss_bcphi(c,j) = mss_bcphi(c,j) + qin_bc_phi(c)*dtime`, which potentially sets the next layer's mass to a large-ish negative number.
- Then things can just get worse from there

I'll work on getting a fix in place ASAP, but it probably won't be until early next week.

**Comment by billsacks** [comment]
These crazy high values of SNOBCMCL existed in the one grid cell for a long time in the simulation (at least a year) before causing the model to blow up in this way. **This suggests that the problem could exist in other situations without manifesting as a crash.**

**Comment by billsacks** [comment]
I redid the 5-year test with my branch off of ctsm1.0.dev064 that introduced the buggy answer changes but then added billsacks/ctsm@ef73c4c . The fixes in that commit allowed the 5-year run to pass, and from spot-checking a couple of history files (0004-07 and 0005-02) I don't see any crazy values of SNOBCMCL, SNOOCMCL or SNODSTMCL.

I also diffed the 0004-07 history files between this case and the failing one, looking at these 3 variables. The only grid cell with differences was the one with crazy values in the failing run (although, interestingly, the 0003-06 history files had roundoff-level differences in these variables in two other grid cells). This is a small bit of good news, I think, suggesting that when this bug manifests, it may become quite obvious by looking at these variables (though I wouldn't draw too firm conclusions from this one test).

**Comment by billsacks** [comment]
@olyson reminded me that he ran the LMWG package comparing ctsm1.0.dev074 with ctsm1.0.dev058, and found only small differences (http://webext.cgd.ucar.edu/I20TR/clm50_ctsm10d074_2deg_GSWP3V1_hist/lnd/clm50_ctsm10d074_2deg_GSWP3V1_hist.1995_2014-clm50_ctsm10d058_2deg_GSWP3V1_hist.1995_2014/setsIndex.html). That suggests that the impact of this bug is likely to be relatively small.

**Comment by ekluzek** [comment]
I updated the lunadaylbugs branch to ctsm1.0.dev089 and showed that the original case that failed here now passes.
