### ISSUE TITLE
A few history field units need to be made CF-compliant to work with ILAMB

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#966]
I've been working on an ILAMB CLM configuration file so that CLM history fields don't need to be CMORized.  ILAMB expects CF-compliant units.  There are three CLM history fields that don't have CF-compliant units that ILAMB uses.  The fields and the suggested units changes are listed here:

FAREA_BURNED: proportion/s  ->  1/s or s-1
FPSN:                   umol/m2s     ->  umol m-2 s-1
QFLX_EVAP_TOT:  mm H2O/s   ->  kg m-2 s-1

This is needed to support the parameter perturbation ensemble project that is in development.

**Comment by ekluzek** [comment]
@olyson does this need to go both on master and release-clm5.0 branches?

**Comment by olyson** [comment]
Both.  But priority is master since that's what we'll use for the parameter perturbation ensemble.

**Comment by ekluzek** [comment]
@olyson is the issue with these specific variables or the units that they are set to? If we change these specific variables, but leave the units for other variables and ILAMB starts adding them as well -- won't that be a problem in the future? I'm just wondering if the units for more variables than just these ones need to change in the long run. It's also just a bit odd to have the same units expressed different ways.

**Comment by ekluzek** [comment]
I think the right way to express this is that ILAMB needs the units to be UDUNITS compliant. There are compliant checkers if getting all the units to be compliant is important.

**Comment by olyson** [comment]
Yes, you make a good point that in the long run the units for more variables than just these ones should change in case ILAMB adds them in the future.  The three I originally listed are a more immediate need because ILAMB is currently (trying) to use them. 
Nate Collier expressed the problem with the CLM variable units as not being CF-compliant as well as not being recognized by UDUNITS, so I wasn't clear what the proper terminology was.

**Comment by ekluzek** [comment]
OK I'll make a separate issue for making all units UDUNIT compliant. In the short term we'll bring these changes in for just these few fields.

**Comment by ekluzek** [comment]
the long term issue is in as #973.
