### ISSUE TITLE
SSP landuse.timeseries for CMIP6 ... individual harvest fields show a jump at 2015

### ISSUE THREAD

**Issue by timhoar** [ESCOMP/CTSM#969]
I have plotted the (unweighted) global mean timeseries for each variable from each SSP scenario in **/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_map** i.e. \
landuse.timeseries_0.9x1.25_hist_78pfts_CMIP6_simyr1850-2015_c170824.nc
landuse.timeseries_0.9x1.25_SSP1-2.6_78pfts_CMIP6_simyr1850-2100_c181220.nc
landuse.timeseries_0.9x1.25_SSP2-4.5_78pfts_CMIP6_simyr1850-2100_c190102.nc
landuse.timeseries_0.9x1.25_SSP3-7.0_78pfts_CMIP6_simyr1850-2100_c181220.nc
landuse.timeseries_0.9x1.25_SSP5-8.5_78pfts_CMIP6_simyr1850-2100_c181209.nc

The following plots provide context for the rest:

[clm_harvest_timeseries.pdf](https://github.com/ESCOMP/CTSM/files/4429886/clm_harvest_timeseries.pdf)

The 'harvest from primary forest' variable shows about a 20% jump from 2016 to 2017.
The 'harvest from primary non-forest' variable shows 2015 as almost **double** any other year,
and 2014 and 2016 are only different by a few percent.
The 'harvest from secondary mature-forest' shows about a 30% jump from 2015 to 2016.
The 'harvest from secondary young-forest' shows a similar drop from 2015 to 2016 - are these two compensating by design?
The grazing varibles are show for completeness.
The 'nitrogen fertilizer for each crop' show SSP2-4.5 as a large outlier - basically, I am having a hard time figuring out what to expect from each protocol.

What I need is a dataset that is consistent with  'business as usual' as exhibited by the data up through 2014. The HARVEST_VH2 variable for 2015 is particularly disconcerting.

Anyone have an idea on how much difference it will make for an F compset?
HIST_CAM60_CLM50%BGC-CROP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV

**Comment by ekluzek** [comment]
@timhoar can you run your analysis for the files in the

/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_map/release-clm5.0.18/

directory? The files you are pointing to are older and as such may have issues with them.

**Comment by timhoar** [comment]
Sorry ... doesn't seem to make a difference for HARVEST_VH2 ... have not checked the others:
[harvest_vh2.pdf](https://github.com/ESCOMP/CTSM/files/4430199/harvest_vh2.pdf)

I did not bother to come up with unique linetypes for each SSP.

**Comment by ekluzek** [comment]
OK, thanks for checking. @lawrencepj1 can you comment on @timhoar question here?

**Comment by lawrencepj1** [comment]
Hi Erik

Not sure I understand the question. Here is the wood harvest out of the
CMIP6 simulations for SSP126 and SSP126 with SSP370 Land Use. They both
look right for wood_harvestc. Am I missing something?

thanks
Peter

[image: image.png]

-- 
Dr Peter Lawrence
Terrestrial Science Section
National Center for Atmospheric Research
1850 Table Mesa Drive
Boulder Colorado 80305

Work: 1-303-497-1727
Cell: 1-303-956-6932

**Comment by lawrencepj1** [comment]
Ok so I looked at Tim's original comment. The SSPs are harmonized from all
of the Integrated Assessment Models to meet the end of the historical
period. As the spatial patterns are inconsistent for some of the IAMs this
means that there is some adjusting in the LUH2 time series data. We combine
all the VH1, VH2, SH1, SH2 and SH3 fields together to get a single wood
harvest amount for each gridcell so this adjustment process is not evident
in the actual amount of wood being removed so we have a smooth transition
from 2014 - 2016 for total wood removed. Hence the above plot.

Peter
-- 
Dr Peter Lawrence
Terrestrial Science Section
National Center for Atmospheric Research
1850 Table Mesa Drive
Boulder Colorado 80305

Work: 1-303-497-1727
Cell: 1-303-956-6932

**Comment by lawrencepj1** [comment]
Here is the graph of global wood harvest from historical to SSP

![image](https://user-images.githubusercontent.com/11986105/78420756-45736980-760f-11ea-9f71-45fa09d04445.png)

**Comment by timhoar** [comment]
Since 2015 was part of the historical data, I was surprised at how much variation there was from the individual allocations. I can't really tell much from the scale in the figure Peter included, so I plotted the sum of the VH1, VH2, SH1, SH2, and SH3 fields from the data in the  **/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_map/release-clm5.0.18** directory:
[total_harvest.pdf](https://github.com/ESCOMP/CTSM/files/4431674/total_harvest.pdf)
Seems there is a similar jump in 2010->2011.
I plotted the individual allocations from this directory as well (Erik indicated these files were newer than the ones I used that opened the issue)
[new_clm_harvest_timeseries.pdf](https://github.com/ESCOMP/CTSM/files/4431702/new_clm_harvest_timeseries.pdf)

That had to be quite a challenge to manipulate the allocations from primary_forest, primary non_forest, secondary mature_forest, secondary young_forest and secondary non-forest PFTs
for the different scenarios such that there was anything close to a reasonable transition! The very defintion of an identifiability problem.

**Comment by lawrencepj1** [comment]
Hi Tim

Yes it is even more complex as the harvest rate only applies to tree PFTs so has to be scaled by the tree area to make it a global number. Thanks for looking at this. I will be honest and didn't know there were any discrepancies between the various harvest classes passing from the historical into the SSP timeline in the LUH2 data.

Peter

**Comment by ekluzek** [comment]
So @lawrencepj1 I'm thinking this is an artifact that we can't really do anything about at this point right? And since the total harvest rate is reasonably smooth, we probably don't need to really think of it as wrong either. Since this all comes from LUH2 and the CMIP6 protocol this is just the way it's been defined. We might think about this for the next go around -- presumably CMIP7.

If we had found this earlier before simulations were done -- would we have done anything about it then? Or would that also require other models to make changes as well? So it might not have been able to be changed even then, is what I'm wondering.

I'm thinking we should mark this as a known problem that we aren't going to fix. But, it does provide useful discussion, and discussion that's visible to the entire project which is good. I just want to make sure you agree with that.

**Comment by lawrencepj1** [comment]
@ekluzek Yes exactly. We would not be able to fix it and be consistent with what the other models in CMIP6 are using. This is an artifact of harmonizing historical and IAM future scenarios so just make a comment for future reference. 

thanks
Peter

**Comment by ekluzek** [comment]
OK, I'm going to close it as a wontfix. But, feel free to add to the discussion.
