### ISSUE TITLE
Problems with override_nsrest namelist option

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#97]
**Erik Kluzek < erik > - 2014-03-01 21:20:54 -0700**
**Bugzilla Id:** [1940](http://bugz.cgd.ucar.edu/show_bug.cgi?id=1940)
**Bugzilla CC:**  muszala,  rfisher,  sacks,  slevis, 

The override_nsrest option is not working correctly.

A case with the following in user_nl_clm:

nrevsn = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/initdata_map/clmi.ICRUCLM45BGCCROPmp24.0241-01-01.10x15_USGS_simyr2000_c131028.nc'
override_nsrest=3

Here's an example issue

   0:(   13)  ys6223
   0:(   14)  ys6223
   0:(shr_sys_abort) ERROR: control_init                     ERROR: nsrest NOT set to a valid value
   0:(shr_sys_abort) WARNING: calling shr_mpi_abort() and stopping
   5:(shr_sys_abort) ERROR: control_init                     ERROR: nsrest NOT set to a valid value

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2014-03-04 14:18:33 -0700**

The namelist changes to make to get it to start are as follows...

--- bld/build-namelist	(revision 57227)
+++ bld/build-namelist	(working copy)
@@ -1508,9 +1508,9 @@
   my $nsrest         = $nl->get_value('override_nsrest');
 
   if ( defined($nsrest) ) {
-    if ( $nsrest == 0 ) { $my_start_type = "startup";  }
-    if ( $nsrest == 1 ) { $my_start_type = "continue"; }
-    if ( $nsrest == 3 ) { $my_start_type = "branch";   }
+    if ( $nsrest == 0 ) { $my_start_type = "'startup'";  }
+    if ( $nsrest == 1 ) { $my_start_type = "'continue'"; }
+    if ( $nsrest == 2 ) { $my_start_type = "'branch'";   }
     if ( "$my_start_type" eq "$drv_start_type" ) {
       fatal_error("no need to set override_nsrest to same as start_type.\n");
     }
Index: bld/namelist_files/namelist_definition_clm4_0.xml
===================================================================
--- bld/namelist_files/namelist_definition_clm4_0.xml	(revision 57227)
+++ bld/namelist_files/namelist_definition_clm4_0.xml	(working copy)
@@ -113,9 +113,9 @@
 </entry>
 
 <entry id="override_nsrest" type="integer"  category="clm_restart" 
-       group="clm_inparm" valid_values="3">
+       group="clm_inparm" valid_values="2">
 Override the start type from the driver: it can only be
-set to 3 meaning branch.
+set to 2 meaning branch.
 </entry>
 
 <entry id="fglcmask" type="char*256" category="datasets"
Index: bld/namelist_files/namelist_definition_clm4_5.xml
===================================================================
--- bld/namelist_files/namelist_definition_clm4_5.xml	(revision 57227)
+++ bld/namelist_files/namelist_definition_clm4_5.xml	(working copy)
@@ -132,9 +132,9 @@
 </entry>
 
 <entry id="override_nsrest" type="integer"  category="clm_restart" 
-       group="clm_inparm" valid_values="3">
+       group="clm_inparm" valid_values="2">
 Override the start type from the driver: it can only be
-set to 3 meaning branch.
+set to 2 meaning branch.
 </entry>
 
 <entry id="fglcmask" type="char*256" category="datasets"

**Comment by ekluzek** [comment]
**Erik Kluzek < erik > - 2014-03-05 14:33:33 -0700**

I tried some cases for f10 and f19 with CROP compsets and they fail to run because of Balance Check errors. And numaIA doesn't have initial conditions which is the point of this.

So I don't have a good case for this, but I'll try to reproduce it with a non-CROP compset just to showcase the override functionality.

**Comment by ekluzek** [comment]
**Bill Sacks < sacks > - 2016-06-29 16:07:27 -0600**

We're not sure why override_nsrest would be needed, so will probably just remove it.

**Comment by ekluzek** [comment]
The purpose of this was to provide the ability to setup a CESM configuration as a startup, but tell CLM to branch from a given restart file. The reason for that is when doing a historical simulation and you need to change the forcing from 1901-1920 to 1920-2014, it allows you to branch CLM to get exact answers, but provides a mechanism to change everything else.

I'm not sure this feature is ever used though. The run_clm_historical script runs through this change as a single case. Although I have to say that I thought that wouldn't work. I thought you'd have to remove the datm restart files on the change over.

It looks like the problem is just that the "3" needs to change to a "2".

**Comment by olyson** [comment]
FYI, the run_historical scripts move the datm restart files to a directory below the run directory (restart_dump) to get them out of the way.

**Comment by ekluzek** [comment]
Awesome, thanks @olyson. I see the move and gzip now. That would work. And now that CISM is a part of the system that might be better than using override_nsrest, since I'm not sure that CISM would startup with something equivalent to a branch. Hopefully, it wouldn't be a cold start.

**Comment by billsacks** [comment]
Decision at CLM software meeting: remove this namelist option.
