### ISSUE TITLE
irrigate is turned off for the 2300 extensions

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#972]
### Brief summary of bug

Irrigate is turned off for the 2300 extensions.

### General bug information

**CTSM version you are using:** release-clm5.0.32
**Does this bug cause significantly incorrect results in the model's science?** Yes

**Configurations affected:** 
BWSSP534osextcmip6
BWSSP585sextcmip6

ISSP585ExtClm50BgcCrop
ISSP534ExtClm50BgcCrop
ISSP126ExtClm50BgcCrop

### Details of bug

irrigate also needs to be set for the 2100-2300 year range.

**Comment by wwieder** [comment]
What's the back story here?  Can we at least set irrigation to be the same as 2100 level instead of just turning it all off?  Is this an issue with the forcing dataset, surface data, or pulling water from the ocean when crops get thirsty?

**Comment by olyson** [comment]
Will, we were asked to review the land namelist for the extension experiments that are about to start and noticed that irrigation was turned off.  This is simply a consequence of a bug in the compset logic.  It will be turned back on either through user_nl_clm or a quick tag.

**Comment by wwieder** [comment]
OK thanks, @olyson
