### ISSUE TITLE
Loading ncl from mkmapdata.sh

### ISSUE THREAD

**Issue by negin513** [ESCOMP/CTSM#978]
### Brief summary of bug
In `CTSM/tools/mkmapdata/mkmapdata.sh`, for Cheyenne, we are loading ESMF, intel compiler, and ncl. It seems like there is a mismatch between the versions of the above modules that are being loaded; therefore, ncl module cannot be loaded correctly. 

Fix will be using another version of the intel compiler for Cheyenne. It seems like `intel/18.0.5` should work. 
### General bug information

**CTSM version you are using: `ctsm1.0.dev089`

**Does this bug cause significantly incorrect results in the model's science? N/A

**Configurations affected:N/A

### Details of bug

In `CTSM/tools/mkmapdata/mkmapdata.sh`, we are loading ncl and a bunch of modules. It seems like there is a mismatch between the set of modules chosen to be loaded.

https://github.com/ESCOMP/CTSM/blob/b1418ae95ea86bb3707ba035750cecd2fb4a768d/tools/mkmapdata/mkmapdata.sh#L345-L350

So, we receive the following error:

```
ml purge
ml esmf_libs/7.1.0r intel/17.0.1
ml ncl

mod has detected the following error:  These module(s) exist but cannot be loaded as requested: "esmf_libs/7.1.0r"
   Try: "module spider esmf_libs/7.1.0r" to see how to load the module(s).
```

**Comment by ekluzek** [comment]
I'm pretty sure this is fixed on the release branch, but not on master. So it should be fixed with my release tag to master.

**Comment by ekluzek** [comment]
@negin513 could you try this on the latest release branch and verify it works and is right there?

**Comment by billsacks** [comment]
I also seem to remember @slevisconsulting fixing this in #823 . Actually, I think he removed the ncl step from mkmapdata in that PR because we determined that it is no longer needed.

**Comment by negin513** [comment]
@ekluzek 
Yes, Erik!
It seems this is fixed in release branch but not on the master branch. 

https://github.com/ESCOMP/CTSM/blob/72a29879a66014553aeb334797b41f74bf6d1109/tools/mkmapdata/mkmapdata.sh#L346-L351

**Comment by negin513** [comment]
@billsacks 
I can see this in https://github.com/slevisconsulting/ctsm/blob/mksurfdata_maps_wo_src_masks/tools/mkmapdata/mkmapdata.sh from @slevisconsulting but this is not yet merged in.

**Comment by billsacks** [comment]
So, between these two fixes, can we close this?
