### ISSUE TITLE
Anomaly forcings

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#987]
### Brief summary of bug

CESM2(CAM6) SSP scenarios that were run for CMIP6 scenarios has an aerosol emission bug that causes regional changes in climate (especially land temperatures over Asia).  I'm not sure how widely distributed the new anomaly forcings have been distributed, but we should likely be cautious using or sharing the new CMIP6 anomaly forcings for SSPs. The CESM2(WACCM) simulations are fine.

### General bug information

This bug would cause regional climate changes. New CESM2(CAM6) simulations are being run.

### Details of bug

In CESM2(CAM6) the anthropogenic and biomass burning Secondary Organic Aerosol (SOA) emissions had been set to zero starting in 2015, while the biogenic emissions were fine.

### Important details of your setup / configuration so we can reproduce the bug

Regional climate changes caused by the bug

### Important output or errors that show the problem

Gokhan has decided to "rerun our CESM2(CAM6) SSP Tier 1 simulations as soon as possible. We will also retract any impacted data sets from the ESGF site".

**Comment by billsacks** [comment]
@wwieder can you please add more details to the title of this issue, like "Anomaly forcings for SSP simulations need to be recreated" (did I get the meaning right?). Also, is there anything that actually needs to be done in the ctsm repo to accomplish this? I guess that means: Do we actually point to the SSP anomaly forcings in an xml file?

**Comment by wwieder** [comment]
I know the anomaly forcing for land only future scenarios was (or is) in a recent tag.  @ekluzek, can you comment on the status of this?  @swensosc or @olyson should be able to  recreate the anomaly forcing pretty easily, but I wanted to raise this issue so CTSM users and developers know about the CESM bug.

**Comment by wwieder** [comment]
@olyson and @swensosc were  you able to regenerate the anomaly forcings after the CESM2(CAM6) simulations were rerun to fix the aerosol bug?

**Comment by wwieder** [comment]
@ekluzek can we release the anomaly forcing compsets with CTSM5.1 (if they are not already on master?)

**Comment by olyson** [comment]
I believe Sean has the scripts to generate the anomaly forcing.

**Comment by dlawrenncar** [comment]
I’m addition to updated data, Erik still needs to finish some tasks.

On May 26, 2020, at 5:04 PM, Keith Oleson <notifications@github.com> wrote:

﻿

I believe Sean has the scripts to generate the anomaly forcing.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ESCOMP/CTSM/issues/987#issuecomment-634325803>, or
unsubscribe

**Comment by swensosc** [comment]
I generated the data ~3 weeks ago; it's at:
/glade/scratch/swensosc//anomaly_forcing//

Keith, do you have time to re-run the test simulations that you had done
previously (I think you did that...)?

**Comment by olyson** [comment]
Ok.
I think I just ran a couple of years with AF on and then a couple of years with AF off.
Does that produce the data you need?

**Comment by swensosc** [comment]
yes, I just thought it would be good to make sure it ran ok.

**Comment by olyson** [comment]
There are a couple of years with AF off here (forced with 2005-2006 GSWP3):

/glade/scratch/oleson/archive/clm50_r-clm5.0.30_1deg_GSWP3V1_iso_SSP3-7/lnd/hist

The new simulation with AF on is here (10 years):

/glade/scratch/oleson/archive/clm50_r-clm5.0.30_1deg_GSWP3V1_iso_SSP3-7_AnomalyF2/lnd/hist

**Comment by swensosc** [comment]
I checked the new simulation that keith provided and it looks like it
worked correctly, so I think the new anomaly forcing data is ok.

**Comment by wwieder** [comment]
Thanks @swensosc. @ekluzek do we need a tag  or PR to bring this in with #922 for CTSM5.1?
