### ISSUE TITLE
We should remove the "Copyright" file

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#997]
I noticed that we have an old "Copyright" file at the top level of the repository, that is both out of date and incorrect – critically, using the legally incorrect term, "public domain".

I recently updated this file in CESM: https://github.com/ESCOMP/CESM/pull/141

However, I'd suggest that we simply remove this file from CTSM. It's not clear to me that we really need to maintain this file, since other code isn't included in our repository but rather downloaded separately via manage_externals, and I think it's confusing to have separate LICENSE and COPYRIGHT files. However, we may want to have a note in the LICENSE file saying that this license only applies to the code in this repository, and that externals obtained via manage_externals have their own licenses.

**Comment by ekluzek** [comment]
This makes sense to me. I especially agree that we should have a note about the externals.

As far as removing the file, it seems we should likely get advice from UCAR legal about this. I see the logic in terms that "releases" are all out of CESM and have the LICENSE and Copyright at the top level. But, since the repository is open and separate, maybe it should have its own Copyright?

I also found the UCAR legal page that talks about Copyright, but it didn't make clear to me what we need to do.

https://internal.ucar.edu/counsel/intellectual-property/faq/copyright#distrofcr

**Comment by billsacks** [comment]
@ekluzek note that we DO have a license file, which contains a copyright notice. I'm NOT suggesting getting rid of that, only getting rid of the Copyright file, which contains incorrect, irrelevant, and/or duplicate information to what's in the license file.

**Comment by ekluzek** [comment]
Ahh, OK, that makes sense then.

And I see this from Gokhan's notes on the Co-Chairs meeting. Which clarifies to me that we should delete the Copyright and keep the license...

> If a copyright notice is used, then we are putting the world on notice that UCAR is claiming ownership of the software. If we own it, we can limit how other people use it by requiring a license. There are many types of licenses to choose from, ranging from very restrictive to very permissive (sometimes described as open source). 
> In contrast, if we dedicate the software to the public domain, then we are not claiming any ownership at all. We have abandoned the software. If we don't own it, we can't limit how other people use it.
> CESM websites contained both a copyright notice and a statement that CESM is in the public domain. This cannot be. We have been cleaning the sites in consultation with the UCAR legal. 
> Regarding a copyright & licensing vs. public domain, one important factor is to look at the requirements from our funding agencies…. 
> What did we promise those that paid for CESM's development? 
> Did we promise to dedicate it to the public domain (give up all ownership)?  
> Did we promise to release it under an open source license (we retain ownership, but make it available to other people with few restrictions)?
